# 34 — Final Streamlit Dashboard Assets

**Origin:** Controlled-300 successor to the frozen pilot dashboard package  
**Refactor status:** Finished
**Validation status:** Finished 
**Output root:** `outputs/34_final_streamlit_dashboard_assets/`  
**Primary evidence:** Notebooks 01–33  
**Supplemental evidence:** N12A, D01, and D02

## Purpose

Package the already validated Controlled-300 evidence into a small, normalized, traceable asset layer for the final Streamlit dashboard.

Notebook 34 does not rerun restoration models, create new scientific metrics, fit new statistical tests, or produce a combined quality or trust score. It reorganizes existing evidence for fast and understandable presentation.

## Approved museum structure

The application contains eight principal rooms:

1. **Exhibition Foyer**
2. **Study Design**
3. **Metric Framework**
4. **Model Gallery**
5. **Stability Lab**
6. **Trustworthiness**
7. **Case Explorer**
8. **Research Archive**

**Focused Portrait Review** is a child room reached through Trustworthiness. It is not a ninth principal navigation tab.

## Controlled-300 population

The package represents:

- 300 paintings: 60 in each of five broad visual categories;
- 3,425 registered experimental cases;
- 2,620 cases eligible for the four full-scope methods;
- 10,480 primary four-method candidates;
- 24 completed bounded-SDXL candidates;
- 10,504 comparison candidates;
- 13,879 inspectable candidates;
- 1,025 repeated-seed uncertainty groups;
- 300 painting reports and 30 detailed case reports;
- five model reports;
- D02 portrait, hand-region, and rendered-lightness evidence.

## Interpretation boundaries

- The study uses controlled synthetic damage, not real conservation interventions.
- A visually convincing result is not proof of historical correctness.
- Repeated-seed variation measures empirical model instability, not calibrated confidence.
- Mask variation measures sensitivity to the supplied damage region.
- Computational flags are review rules, not expert conservation decisions.
- Rendered lightness is an image property, not race, ethnicity, or identity.
- SDXL remains a bounded feasibility population.
- No universal best model or combined quality score is produced.

## Package structure

```text
data/bootstrap/
data/rooms/
data/paintings/
data/reports/
data/derived/
assets/renditions/
manifests/
validation/
```

The live Controlled-50 Streamlit deployment remains unchanged until the complete N34 package passes and Step 7 begins.

## Batch 1 — Contract, inventory, and upstream-evidence preflight

This batch verifies that Notebook 34 is allowed to build the Controlled-300 dashboard package.

It:

- discovers the repository without assuming the notebook working directory;
- loads the strict `dashboard_assets_config.v2` contract;
- rejects a stale N34 output directory containing old files;
- verifies the current inventory status, size, and SHA-256 checksum;
- checks all governing dashboard documents against their locked checksums;
- validates the project-path registry;
- confirms all 91 declared local inputs exist;
- verifies 33 primary and three supplemental completed run manifests;
- validates 70 source-table contracts without retaining producer-scale tables;
- confirms the approved population, room structure, runtime limits, and output ownership.

This batch performs no network requests, creates no directories, and writes no dashboard package files.

In [1]:
from __future__ import annotations

import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd
from IPython.display import display


# Discover the repository from either its root or the notebooks directory.
CURRENT_LOCATION = Path.cwd().resolve()

PROJECT_ROOT = next(
    (
        candidate
        for candidate in (CURRENT_LOCATION, *CURRENT_LOCATION.parents)
        if (
            candidate
            / "config"
            / "evaluation"
            / "dashboard_assets.yaml"
        ).is_file()
        and (candidate / "src" / "restoration_eval").is_dir()
        and (candidate / "notebooks").is_dir()
    ),
    None,
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Could not locate the painting-restoration-eval repository root."
    )

SOURCE_ROOT = PROJECT_ROOT / "src"

if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))


from restoration_eval.dashboard_assets import (
    DASHBOARD_ASSETS_CONFIG_SCHEMA,
    DASHBOARD_PACKAGE_SCHEMA,
    DASHBOARD_RUNTIME_MANIFEST_SCHEMA,
    OUTPUT_SCHEMAS,
    VERSION as DASHBOARD_ASSETS_VERSION,
    blocking_validation_failures,
    load_dashboard_config,
    load_upstream_manifests,
    resolve_output_paths,
    sha256_file,
    validate_declared_input_paths,
    validate_input_table_contracts,
    validation_row,
)
from restoration_eval.paths import (
    PROJECT_PATHS_SCHEMA_VERSION,
    validate_project_paths_registry,
)
from restoration_eval.schemas import VALIDATION_CHECK_COLUMNS


RUN_STARTED_AT_UTC = (
    datetime.now(timezone.utc)
    .isoformat(timespec="seconds")
    .replace("+00:00", "Z")
)

VALIDATION_ROWS: list[dict] = []


def add_check(
    stage: str,
    check_name: str,
    observed,
    expected,
    passed: bool,
    details: str = "",
) -> None:
    VALIDATION_ROWS.append(
        validation_row(
            stage,
            check_name,
            observed,
            expected,
            passed,
            details,
        )
    )


def collect_helper_checks(checks: pd.DataFrame) -> None:
    if checks.empty:
        return

    VALIDATION_ROWS.extend(
        checks.loc[:, VALIDATION_CHECK_COLUMNS]
        .to_dict(orient="records")
    )


def current_validation_frame() -> pd.DataFrame:
    return pd.DataFrame(
        VALIDATION_ROWS,
        columns=VALIDATION_CHECK_COLUMNS,
    )


def require_no_blocking_failures(stage: str) -> None:
    failures = blocking_validation_failures(
        current_validation_frame()
    )

    if not failures.empty:
        display(
            failures[
                [
                    "validation_stage",
                    "check_description",
                    "observed",
                    "expected",
                    "details",
                ]
            ]
        )
        raise RuntimeError(
            f"{stage} failed with "
            f"{len(failures)} blocking check(s)."
        )


print("Notebook 34 Controlled-300 environment initialized.")
print("Project root:", PROJECT_ROOT)
print("Run started:", RUN_STARTED_AT_UTC)
print("Python:", platform.python_version())
print("Platform:", platform.platform())
print("Dashboard helper version:", DASHBOARD_ASSETS_VERSION)

Notebook 34 Controlled-300 environment initialized.
Project root: D:\Masters\FH\Thesis\painting-restoration-eval
Run started: 2026-09-28T15:48:02Z
Python: 3.12.6
Platform: Windows-11-10.0.26200-SP0
Dashboard helper version: 2.0.0

In [2]:
CONFIG_PATH = (
    PROJECT_ROOT
    / "config"
    / "evaluation"
    / "dashboard_assets.yaml"
)

CONFIG = load_dashboard_config(CONFIG_PATH)
SETTINGS = CONFIG["dashboard_assets"]

POPULATION = SETTINGS["population"]
OUTPUT_SPEC = SETTINGS["output"]

ROOM_PLAN = (
    pd.DataFrame(SETTINGS["rooms"])
    .sort_values("display_order")
    .reset_index(drop=True)
)

OUTPUT_PATHS = resolve_output_paths(
    PROJECT_ROOT,
    CONFIG,
)

OUTPUT_ROOT = OUTPUT_PATHS["root"]

MANIFEST_SPECS = {
    **SETTINGS["upstream_manifests"],
    **SETTINGS["supplemental_manifests"],
}

EXPECTED_PRIMARY_MANIFEST_IDS = [
    f"{number:02d}"
    for number in range(1, 34)
]

EXPECTED_SUPPLEMENTAL_MANIFEST_IDS = [
    "12A",
    "D01",
    "D02",
]

EXPECTED_PRINCIPAL_ROOM_IDS = [
    "exhibition_foyer",
    "study_design",
    "metric_framework",
    "model_gallery",
    "stability_lab",
    "trustworthiness",
    "case_explorer",
    "research_archive",
]

EXPECTED_ALL_ROOM_IDS = [
    "exhibition_foyer",
    "study_design",
    "metric_framework",
    "model_gallery",
    "stability_lab",
    "trustworthiness",
    "focused_portrait_review",
    "case_explorer",
    "research_archive",
]

EXPECTED_GOVERNING_CONTRACTS = {
    "page_contract": "earlier_gate",
    "producer_artifact_map": "earlier_gate",
    "remote_asset_audit": "earlier_gate",
    "runtime_loading_contract": "earlier_gate",
    "n34_implementation_contract": "implementation_contract",
}

PREEXISTING_OUTPUT_FILES = (
    sorted(
        path.relative_to(OUTPUT_ROOT).as_posix()
        for path in OUTPUT_ROOT.rglob("*")
        if path.is_file()
    )
    if OUTPUT_ROOT.exists()
    else []
)

OBSERVED_PRINCIPAL_ROOM_IDS = (
    ROOM_PLAN.loc[
        ROOM_PLAN["route_kind"].eq("principal"),
        "room_id",
    ]
    .astype(str)
    .tolist()
)

OBSERVED_CHILD_ROOMS = (
    ROOM_PLAN.loc[
        ROOM_PLAN["route_kind"].eq("child"),
        ["room_id", "parent_room_id"],
    ]
    .to_dict(orient="records")
)

CONTRACT_CHECKS = [
    (
        "config_schema",
        CONFIG["config_schema_version"],
        DASHBOARD_ASSETS_CONFIG_SCHEMA,
    ),
    (
        "dashboard_package_schema",
        SETTINGS["dashboard_package_schema_version"],
        DASHBOARD_PACKAGE_SCHEMA,
    ),
    (
        "runtime_manifest_schema",
        SETTINGS["runtime_manifest_schema_version"],
        DASHBOARD_RUNTIME_MANIFEST_SCHEMA,
    ),
    (
        "notebook_id",
        SETTINGS["notebook_id"],
        "34",
    ),
    (
        "notebook_stem",
        SETTINGS["notebook_stem"],
        "34_final_streamlit_dashboard_assets",
    ),
    (
        "dataset_scope",
        SETTINGS["dataset_scope"],
        "controlled_300",
    ),
    (
        "presentation_only_scope",
        SETTINGS["creates_new_scientific_evidence"],
        False,
    ),
    (
        "primary_manifest_ids",
        list(SETTINGS["upstream_manifests"]),
        EXPECTED_PRIMARY_MANIFEST_IDS,
    ),
    (
        "supplemental_manifest_ids",
        list(SETTINGS["supplemental_manifests"]),
        EXPECTED_SUPPLEMENTAL_MANIFEST_IDS,
    ),
    (
        "combined_manifest_count",
        len(MANIFEST_SPECS),
        36,
    ),
    (
        "principal_room_order",
        OBSERVED_PRINCIPAL_ROOM_IDS,
        EXPECTED_PRINCIPAL_ROOM_IDS,
    ),
    (
        "all_room_records",
        ROOM_PLAN["room_id"].astype(str).tolist(),
        EXPECTED_ALL_ROOM_IDS,
    ),
    (
        "focused_portrait_child_route",
        OBSERVED_CHILD_ROOMS,
        [
            {
                "room_id": "focused_portrait_review",
                "parent_room_id": "trustworthiness",
            }
        ],
    ),
    (
        "governing_contract_authorities",
        {
            key: value["authority_kind"]
            for key, value in SETTINGS[
                "governing_contracts"
            ].items()
        },
        EXPECTED_GOVERNING_CONTRACTS,
    ),
    (
        "input_table_contract_count",
        len(SETTINGS["input_table_contracts"]),
        70,
    ),
    (
        "responsibility_count",
        len(SETTINGS["responsibilities"]),
        12,
    ),
    (
        "mandatory_derivation_count",
        len(SETTINGS["mandatory_derivations"]),
        7,
    ),
    (
        "startup_network_requests",
        SETTINGS["runtime_budgets"][
            "startup_network_requests"
        ],
        0,
    ),
    (
        "local_package_hard_bytes",
        SETTINGS["runtime_budgets"][
            "local_package_hard_bytes"
        ],
        64 * 1024 * 1024,
    ),
    (
        "output_root",
        OUTPUT_SPEC["root"],
        "outputs/34_final_streamlit_dashboard_assets",
    ),
    (
        "clean_output_root",
        PREEXISTING_OUTPUT_FILES,
        [],
    ),
]

for check_name, observed, expected in CONTRACT_CHECKS:
    add_check(
        "batch_1_contract",
        check_name,
        observed,
        expected,
        observed == expected,
        (
            ""
            if observed == expected
            else "Notebook 34 differs from the approved v2 contract."
        ),
    )

require_no_blocking_failures(
    "Notebook 34 contract validation"
)

OUTPUT_CONTRACT_VIEW = pd.DataFrame(
    [
        {
            "output_key": key,
            "repository_relative_path": (
                path.relative_to(PROJECT_ROOT).as_posix()
            ),
            "kind": (
                "root"
                if key == "root"
                else (
                    "directory"
                    if key.endswith("_dir")
                    else (
                        "template"
                        if "{painting_id}" in str(path)
                        else "file"
                    )
                )
            ),
            "exists_before_run": path.exists(),
        }
        for key, path in OUTPUT_PATHS.items()
    ]
).sort_values(
    ["kind", "output_key"]
).reset_index(drop=True)

display(ROOM_PLAN)
display(OUTPUT_CONTRACT_VIEW)

print("Notebook 34 v2 contract passed.")
print("Principal rooms:", len(EXPECTED_PRINCIPAL_ROOM_IDS))
print("Child routes:", len(OBSERVED_CHILD_ROOMS))
print("Declared output paths:", len(OUTPUT_PATHS))
print("Pre-existing output files:", len(PREEXISTING_OUTPUT_FILES))
print("Output directories created by this batch: 0")

,room_id,display_order,display_name,route_kind,parent_room_id
0,exhibition_foyer,1.0,Exhibition Foyer,principal,None
1,study_design,2.0,Study Design,principal,None
2,metric_framework,3.0,Metric Framework,principal,None
3,model_gallery,4.0,Model Gallery,principal,None
4,stability_lab,5.0,Stability Lab,principal,None
5,trustworthiness,6.0,Trustworthiness,principal,None
6,focused_portrait_review,6.1,Focused Portrait Review,child,trustworthiness
7,case_explorer,7.0,Case Explorer,principal,None
8,research_archive,8.0,Research Archive,principal,None

,output_key,repository_relative_path,kind,exists_before_run
0,assets_dir,outputs/34_final_streamlit_dashboard_assets/as...,directory,False
1,bootstrap_dir,outputs/34_final_streamlit_dashboard_assets/da...,directory,False
2,data_dir,outputs/34_final_streamlit_dashboard_assets/data,directory,False
3,derived_dir,outputs/34_final_streamlit_dashboard_assets/da...,directory,False
4,diagnostic_preview_dir,outputs/34_final_streamlit_dashboard_assets/as...,directory,False
5,manifests_dir,outputs/34_final_streamlit_dashboard_assets/ma...,directory,False
6,paintings_dir,outputs/34_final_streamlit_dashboard_assets/da...,directory,False
7,renditions_dir,outputs/34_final_streamlit_dashboard_assets/as...,directory,False
8,reports_dir,outputs/34_final_streamlit_dashboard_assets/da...,directory,False
9,rooms_dir,outputs/34_final_streamlit_dashboard_assets/da...,directory,False
10,standard_dir,outputs/34_final_streamlit_dashboard_assets/as...,directory,False
11,thumb_dir,outputs/34_final_streamlit_dashboard_assets/as...,directory,False
12,validation_dir,outputs/34_final_streamlit_dashboard_assets/va...,directory,False
13,work_dir,outputs/34_final_streamlit_dashboard_assets/work,directory,False
14,artifacts_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
15,asset_locators_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
16,bootstrap_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
17,case_explorer_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
18,d02_hand_summary_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
19,d02_lightness_summary_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
20,d02_r005_geometry_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
21,dashboard_assets_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
22,display_components_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
23,exhibition_foyer_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
24,filter_options_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
25,focused_portrait_review_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
26,glossary_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
27,metric_framework_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
28,model_gallery_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
29,painting_lookup_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
30,renditions_manifest_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
31,report_index_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
32,research_archive_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
33,room_catalogue_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
34,room_partitions_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
35,run_manifest_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
36,runtime_manifest_path,outputs/34_final_streamlit_dashboard_assets/ma...,file,False
37,stability_lab_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
38,stability_trajectories_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
39,study_design_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
40,threshold_strata_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
41,trustworthiness_path,outputs/34_final_streamlit_dashboard_assets/da...,file,False
42,validation_path,outputs/34_final_streamlit_dashboard_assets/va...,file,False
43,root,outputs/34_final_streamlit_dashboard_assets,root,False
44,painting_shard_template,outputs/34_final_streamlit_dashboard_assets/da...,template,False

Notebook 34 v2 contract passed.
Principal rooms: 8
Child routes: 1
Declared output paths: 45
Pre-existing output files: 0
Output directories created by this batch: 0

In [3]:
INPUT_SPEC = SETTINGS["inputs"]

INVENTORY_PATH = (
    PROJECT_ROOT
    / INPUT_SPEC["inventory_path"]
)

INVENTORY_RUN_PATH = (
    PROJECT_ROOT
    / INPUT_SPEC["inventory_run_path"]
)

PROJECT_PATHS_PATH = (
    PROJECT_ROOT
    / INPUT_SPEC["project_paths_path"]
)

for label, path in {
    "inventory_table": INVENTORY_PATH,
    "inventory_run": INVENTORY_RUN_PATH,
    "project_paths_registry": PROJECT_PATHS_PATH,
}.items():
    add_check(
        "batch_1_inventory_files",
        f"{label}_exists",
        path.is_file(),
        True,
        path.is_file(),
        f"Missing required inventory file: {path}",
    )

require_no_blocking_failures(
    "Inventory-file discovery"
)

with INVENTORY_RUN_PATH.open(
    "r",
    encoding="utf-8-sig",
) as handle:
    INVENTORY_RUN = json.load(handle)

INVENTORY_SUMMARY = INVENTORY_RUN.get("summary", {})

OBSERVED_INVENTORY_SHA256 = sha256_file(
    INVENTORY_PATH
)

OBSERVED_INVENTORY_SIZE = (
    INVENTORY_PATH.stat().st_size
)

OBSERVED_REPOSITORY_ROOT = (
    Path(
        str(
            INVENTORY_RUN.get(
                "repository_root",
                "",
            )
        )
    ).resolve()
)

INVENTORY_CHECKS = [
    (
        "inventory_status",
        INVENTORY_RUN.get("status"),
        "completed",
    ),
    (
        "inventory_read_error_count",
        int(
            INVENTORY_SUMMARY.get(
                "read_error_count",
                -1,
            )
        ),
        0,
    ),
    (
        "inventory_read_error_file_count",
        int(
            INVENTORY_SUMMARY.get(
                "read_error_file_count",
                -1,
            )
        ),
        0,
    ),
    (
        "inventory_repository_root",
        str(OBSERVED_REPOSITORY_ROOT),
        str(PROJECT_ROOT),
    ),
    (
        "inventory_relative_path",
        INVENTORY_RUN.get(
            "inventory_relative_path"
        ),
        INPUT_SPEC["inventory_path"],
    ),
    (
        "inventory_size_bytes",
        OBSERVED_INVENTORY_SIZE,
        int(
            INVENTORY_RUN.get(
                "inventory_size_bytes",
                -1,
            )
        ),
    ),
    (
        "inventory_sha256",
        OBSERVED_INVENTORY_SHA256,
        str(
            INVENTORY_RUN.get(
                "inventory_sha256",
                "",
            )
        ).lower(),
    ),
]

for check_name, observed, expected in INVENTORY_CHECKS:
    add_check(
        "batch_1_inventory_integrity",
        check_name,
        observed,
        expected,
        observed == expected,
        (
            ""
            if observed == expected
            else "The inventory table and run record are not an exact pair."
        ),
    )

require_no_blocking_failures(
    "Inventory-integrity validation"
)

INVENTORY = pd.read_csv(
    INVENTORY_PATH,
    usecols=[
        "relative_path",
        "file_kind",
        "format",
        "size_bytes",
        "read_error_count",
    ],
    low_memory=False,
)

INVENTORY_PATHS = set(
    INVENTORY["relative_path"].astype(str)
)

PREPARATION_FILES = {
    ".gitattributes",
    ".gitignore",
    "config/evaluation/dashboard_assets.yaml",
    "config/evaluation/evidence_coverage.yaml",
    "docs/dashboard_design_finalists/controlled_300_page_contracts.md",
    "docs/dashboard_design_finalists/controlled_300_producer_artifact_map.md",
    "docs/dashboard_design_finalists/controlled_300_remote_asset_audit.md",
    "docs/dashboard_design_finalists/controlled_300_runtime_loading_contract.md",
    "docs/dashboard_design_finalists/controlled_300_n34_implementation_contract.md",
    "docs/evidence_dependency_audit.md",
    "docs/final_notebook_roadmap.md",
    "docs/refactoring_implementation_guidelines.md",
    "notebooks/34_final_streamlit_dashboard_assets.ipynb",
    "src/restoration_eval/dashboard_assets.py",
    "tests/test_dashboard_assets.py",
}

MISSING_PREPARATION_FILES = sorted(
    PREPARATION_FILES - INVENTORY_PATHS
)

PREPARATION_INVENTORY = (
    INVENTORY.loc[
        INVENTORY["relative_path"].isin(
            PREPARATION_FILES
        )
    ]
    .sort_values("relative_path")
    .reset_index(drop=True)
)

PREPARATION_READ_ERRORS = int(
    PREPARATION_INVENTORY[
        "read_error_count"
    ].fillna(0).sum()
)

with PROJECT_PATHS_PATH.open(
    "r",
    encoding="utf-8-sig",
) as handle:
    PROJECT_PATHS_REGISTRY = json.load(handle)

PROJECT_PATH_ERRORS = (
    validate_project_paths_registry(
        PROJECT_PATHS_REGISTRY
    )
)

add_check(
    "batch_1_inventory_governance",
    "preparation_files_indexed",
    MISSING_PREPARATION_FILES,
    [],
    not MISSING_PREPARATION_FILES,
    "One or more N34 preparation files are absent from the inventory.",
)

add_check(
    "batch_1_inventory_governance",
    "preparation_file_read_errors",
    PREPARATION_READ_ERRORS,
    0,
    PREPARATION_READ_ERRORS == 0,
    "One or more N34 preparation files has an inventory read error.",
)

add_check(
    "batch_1_inventory_governance",
    "project_paths_schema",
    PROJECT_PATHS_REGISTRY.get(
        "registry_schema_version"
    ),
    PROJECT_PATHS_SCHEMA_VERSION,
    (
        PROJECT_PATHS_REGISTRY.get(
            "registry_schema_version"
        )
        == PROJECT_PATHS_SCHEMA_VERSION
    ),
    "The project-path registry schema differs.",
)

add_check(
    "batch_1_inventory_governance",
    "project_paths_registry_errors",
    PROJECT_PATH_ERRORS,
    [],
    not PROJECT_PATH_ERRORS,
    "The project-path registry failed validation.",
)

GOVERNING_CONTRACT_ROWS = []

for contract_id, spec in SETTINGS[
    "governing_contracts"
].items():
    contract_path = (
        PROJECT_ROOT
        / str(spec["path"])
    )

    observed_sha256 = (
        sha256_file(contract_path)
        if contract_path.is_file()
        else ""
    )

    checksum_matches = (
        observed_sha256
        == str(spec["sha256"]).lower()
    )

    add_check(
        "batch_1_governing_contracts",
        f"{contract_id}_checksum",
        observed_sha256,
        str(spec["sha256"]).lower(),
        checksum_matches,
        (
            ""
            if checksum_matches
            else "A governing dashboard contract changed after approval."
        ),
    )

    GOVERNING_CONTRACT_ROWS.append(
        {
            "contract_id": contract_id,
            "authority_kind": spec[
                "authority_kind"
            ],
            "relative_path": spec["path"],
            "checksum_matches": checksum_matches,
        }
    )

require_no_blocking_failures(
    "Inventory and governance validation"
)

GOVERNING_CONTRACT_VIEW = pd.DataFrame(
    GOVERNING_CONTRACT_ROWS
)

display(PREPARATION_INVENTORY)
display(GOVERNING_CONTRACT_VIEW)

del INVENTORY
del PROJECT_PATHS_REGISTRY

print("Inventory and governance preflight passed.")
print("Inventory run ID:", INVENTORY_RUN["inventory_run_id"])
print("Indexed files:", INVENTORY_SUMMARY["file_count"])
print("Inventory SHA-256:", OBSERVED_INVENTORY_SHA256)
print("Preparation files indexed:", len(PREPARATION_INVENTORY))
print("Governing contracts verified:", len(GOVERNING_CONTRACT_VIEW))
print("Project-path registry errors:", len(PROJECT_PATH_ERRORS))

,relative_path,format,file_kind,size_bytes,read_error_count
0,.gitattributes,no_extension,other,6323,0
1,.gitignore,no_extension,other,4281,0
2,config/evaluation/dashboard_assets.yaml,yaml,yaml,43020,0
3,config/evaluation/evidence_coverage.yaml,yaml,yaml,147524,0
4,docs/dashboard_design_finalists/controlled_300...,markdown,markdown,21924,0
5,docs/dashboard_design_finalists/controlled_300...,markdown,markdown,60886,0
6,docs/dashboard_design_finalists/controlled_300...,markdown,markdown,30901,0
7,docs/dashboard_design_finalists/controlled_300...,markdown,markdown,11310,0
8,docs/dashboard_design_finalists/controlled_300...,markdown,markdown,19067,0
9,docs/evidence_dependency_audit.md,markdown,markdown,129672,0
10,docs/final_notebook_roadmap.md,markdown,markdown,221343,0
11,docs/refactoring_implementation_guidelines.md,markdown,markdown,147818,0
12,notebooks/34_final_streamlit_dashboard_assets....,notebook,notebook,977739,0
13,src/restoration_eval/dashboard_assets.py,python,python,37839,0
14,tests/test_dashboard_assets.py,python,python,9357,0

,contract_id,authority_kind,relative_path,checksum_matches
0,page_contract,earlier_gate,docs/dashboard_design_finalists/controlled_300...,True
1,producer_artifact_map,earlier_gate,docs/dashboard_design_finalists/controlled_300...,True
2,remote_asset_audit,earlier_gate,docs/dashboard_design_finalists/controlled_300...,True
3,runtime_loading_contract,earlier_gate,docs/dashboard_design_finalists/controlled_300...,True
4,n34_implementation_contract,implementation_contract,docs/dashboard_design_finalists/controlled_300...,True

Inventory and governance preflight passed.
Inventory run ID: inventory_20260928T143704Z_c0925051
Indexed files: 141945
Inventory SHA-256: 964854b0d309a32d7891daee66adad003d9759ad89026a0286619db028f9317a
Preparation files indexed: 15
Governing contracts verified: 5
Project-path registry errors: 0

In [4]:
DECLARED_INPUT_CHECKS = (
    validate_declared_input_paths(
        PROJECT_ROOT,
        CONFIG,
    )
)

collect_helper_checks(
    DECLARED_INPUT_CHECKS
)

require_no_blocking_failures(
    "Declared-input validation"
)


UPSTREAM_MANIFESTS, MANIFEST_CHECKS = (
    load_upstream_manifests(
        PROJECT_ROOT,
        CONFIG,
    )
)

collect_helper_checks(
    MANIFEST_CHECKS
)

require_no_blocking_failures(
    "Upstream-manifest validation"
)


def input_progress(
    completed: int,
    total: int,
    input_key: str,
) -> None:
    if (
        completed == 1
        or completed % 10 == 0
        or completed == total
    ):
        print(
            "Input-table preflight: "
            f"{completed}/{total} checked "
            f"({input_key})."
        )


INPUT_TABLE_SUMMARY, INPUT_TABLE_CHECKS = (
    validate_input_table_contracts(
        PROJECT_ROOT,
        CONFIG,
        load_frames=False,
        progress_callback=input_progress,
    )
)

collect_helper_checks(
    INPUT_TABLE_CHECKS
)

require_no_blocking_failures(
    "Input-table validation"
)


MANIFEST_SUMMARY = pd.DataFrame(
    [
        {
            "logical_id": logical_id,
            "manifest_class": (
                "primary"
                if logical_id
                in SETTINGS["upstream_manifests"]
                else "supplemental"
            ),
            "producer_notebook_id": (
                manifest.get("notebook_id")
            ),
            "notebook_name": (
                manifest.get("notebook_name")
            ),
            "run_id": manifest.get("run_id"),
            "run_status": (
                manifest.get("run_status")
            ),
            "completion_gate_passed": (
                manifest.get(
                    "completion_gate_passed"
                )
            ),
            "pinned_size_bytes": int(
                MANIFEST_SPECS[
                    logical_id
                ]["size_bytes"]
            ),
            "checksum_verified": True,
        }
        for logical_id, manifest
        in UPSTREAM_MANIFESTS.items()
    ]
)

EXPECTED_TABLE_ROWS = {
    key: int(spec["rows"])
    for key, spec in SETTINGS[
        "input_table_contracts"
    ].items()
}

INPUT_TABLE_SUMMARY = (
    INPUT_TABLE_SUMMARY.assign(
        expected_rows=lambda frame: (
            frame["input_key"]
            .map(EXPECTED_TABLE_ROWS)
            .astype(int)
        ),
        row_count_matches=lambda frame: (
            frame["observed_rows"]
            == frame["input_key"].map(
                EXPECTED_TABLE_ROWS
            )
        ),
    )
    .sort_values("input_key")
    .reset_index(drop=True)
)

TOTAL_CONTRACT_ROWS = int(
    INPUT_TABLE_SUMMARY[
        "observed_rows"
    ].sum()
)

TOTAL_CONTRACT_BYTES = int(
    INPUT_TABLE_SUMMARY[
        "size_bytes"
    ].sum()
)

display(MANIFEST_SUMMARY)
display(
    INPUT_TABLE_SUMMARY[
        [
            "input_key",
            "observed_rows",
            "expected_rows",
            "size_bytes",
            "row_count_matches",
            "status",
        ]
    ]
)

print("Upstream manifests verified:", len(UPSTREAM_MANIFESTS))
print("Primary manifests:", len(SETTINGS["upstream_manifests"]))
print("Supplemental manifests:", len(SETTINGS["supplemental_manifests"]))
print("Declared local inputs verified:", len(DECLARED_INPUT_CHECKS))
print("Source-table contracts verified:", len(INPUT_TABLE_SUMMARY))
print("Logical source rows covered:", f"{TOTAL_CONTRACT_ROWS:,}")
print("Source bytes covered:", f"{TOTAL_CONTRACT_BYTES:,}")
print("Producer-scale dataframes retained:", 0)

Input-table preflight: 1/70 checked (artworks_path).
Input-table preflight: 10/70 checked (case_registry_path).
Input-table preflight: 20/70 checked (feature_metrics_path).
Input-table preflight: 30/70 checked (semantic_map_manifest_path).
Input-table preflight: 40/70 checked (statistical_results_path).
Input-table preflight: 50/70 checked (model_cards_path).
Input-table preflight: 60/70 checked (d01_candidates_path).
Input-table preflight: 70/70 checked (d02_lightness_path).

,logical_id,manifest_class,producer_notebook_id,notebook_name,run_id,run_status,completion_gate_passed,pinned_size_bytes,checksum_verified
0,01,primary,01,Dataset Verification,run_49a7e3c485394878ab4323ce661f3ef5,completed,True,9107,True
1,02,primary,02,Image Preprocessing,run_ca94012bb1e54bf5bf57c1fdabb01480,completed,True,10881,True
2,03,primary,03,Canonical Mask Generation,run_dd51e1b1ca374f3aad16d22b0cd12c99,completed,True,12902,True
3,04,primary,04,Canonical Damaged-Image Generation,run_92d2030511e14f108bd9ef46f8c3110a,completed,True,14377,True
4,05,primary,05,Damage-Size Sensitivity Dataset Generation,run_fb717ad978394227944ef6bf99919f08,completed,True,23570,True
5,06,primary,06,Mask Robustness Dataset Generation,run_cd2601a25a2d4794aba0745ec6beed5c,completed,True,15197,True
6,07,primary,07,Synthetic Degradation Dataset Generation,run_ad90292d5fb8462eb6241b8123a779d6,completed,True,15082,True
7,08,primary,08,Experiment Contracts and Region Policy,run_b83466f07ebb4b55928229587922334a,completed,True,16624,True
8,09,primary,09,OpenCV Telea Restoration,run_350786ea88014b67b0cf9efec7fac23c,completed,True,13017,True
9,10,primary,10,LaMa Restoration,run_6f81083a17804d36b1495e4932db4e03,completed,True,23514,True
10,11,primary,11,Stable Diffusion Restoration,run_4385124a0cca4d758d357de654a33f13,completed,True,27699,True
11,12,primary,12,SDXL Bounded Partial Evaluation,run_1f7af9d329354a56b4275c4af3cd3f75,completed,True,18795,True
12,13,primary,13,Classical Metrics,run_41b9c87a3c034f19b6f28868127b3c89,completed,True,18542,True
13,14,primary,14,14_lpips_metrics,run_27cb11ae9aa94133ad474b2f38cab122,completed,True,17677,True
14,15,primary,15,15_feature_similarity,run_50c1bb5f25b44111a76df998329d69ed,completed,True,22579,True
15,16,primary,16,16_difference_maps_and_spatial_diagnostics,run_99b0d8d1af1b43bd8e8cb3d6ae754868,completed,True,27100,True
16,17,primary,17,17_local_consistency_metrics,run_ed15508895b542e6ac0733c49704ad26,completed,True,27388,True
17,18,primary,18,18_diffusion_uncertainty_analysis,run_7c1d7195ed8447c1a878259360b1f5f2,completed,True,21497,True
18,19,primary,19,19_uncertainty_and_spatial_explanation_maps,run_7384c7fb8d4c4efe98264a660ac12a75,completed,True,21778,True
19,20,primary,20,20_semantic_and_structural_consistency,run_8c94e988fd4c4d7cae0acd8c3a64fbe6,completed,True,28659,True
20,21,primary,21,21_multi_model_comparison,run_86f7f46183634889aa050ee2a9f33b56,completed,True,21816,True
21,22,primary,22,22_damage_size_diffusion_uncertainty_extension,run_d0276a6859f74fada266936f43b7499f,completed,True,19707,True
22,23,primary,23,23_damage_size_sensitivity_analysis,run_e93288fc3ac847ccb699241b4b4c8be0,completed,True,18237,True
23,24,primary,24,24_mask_robustness_analysis,run_bbf68684c3ca47e5827c2b8b4b666351,completed,True,17557,True
24,25,primary,25,25_synthetic_degradation_analysis,run_cf89ebe972364c7b8ccfefc6bf2a63ca,completed,True,21157,True
25,26,primary,26,26_grouped_and_statistical_analysis,run_efc978dd6d504cdb9b138a750f6dca83,completed,True,25209,True
26,27,primary,27,27_failure_taxonomy_and_trustworthiness_flags,run_bef567ee35c1409dbcecfb71f1b4f8b4,completed,True,22731,True
27,28,primary,28,28_metric_and_region_policy_ablation,run_4325bb483fbc4ccda670df125c40731d,completed,True,23009,True
28,29,primary,29,29_explainable_ai_and_case_retrieval,run_ad7603b6bdb14156a140351f6ac1f241,completed,True,24147,True
29,30,primary,30,30_model_cards_compute_and_scalability,run_605de239145a46e9a202fd63bbbb4e9c,completed,True,20635,True
30,31,primary,31,31_model_report_generation,run_430fd1355d3a4011bedc55b571d9544c,completed,True,24757,True
31,32,primary,32,32_case_and_painting_report_generation,run_0d4ae193602944dda511bf54199105b1,completed,True,105829,True
32,33,primary,33,33_final_evaluation_report,run_aef04267c2e44495a4e7a6249426bd4d,completed,True,33051,True
33,12A,supplemental,12A,HINT Restoration,run_f6c9353c31ce4ed9be5e5502571d635d,completed,True,11373,True
34,D01,supplemental,37,37_hint_mat_method_selection,run_6583cb070ead425b91e0bf738f1822ea,completed,True,11947,True
35,D02,supplemental,D02,d02_portrait_skin_tone_and_hand_restoration_audit,run_fdbd2ed6e93b4d709f5439af028a7600,completed,True,21991,True

,input_key,observed_rows,expected_rows,size_bytes,row_count_matches,status
0,ablation_results_path,47508,47508,18045689,True,passed
1,artworks_path,300,300,280991,True,passed
2,canonical_cases_path,1500,1500,1133765,True,passed
3,canonical_masks_path,1500,1500,2814678,True,passed
4,canonical_uncertainty_path,780,780,981315,True,passed
...,...,...,...,...,...,...
65,telea_restorations_path,2620,2620,2212716,True,passed
66,thesis_tables_path,352,352,276681,True,passed
67,trustworthiness_flags_path,152669,152669,120864519,True,passed
68,uncertainty_map_manifest_path,6255,6255,4594895,True,passed
69,uncertainty_metrics_path,124800,124800,81414282,True,passed

Upstream manifests verified: 36
Primary manifests: 33
Supplemental manifests: 3
Declared local inputs verified: 91
Source-table contracts verified: 70
Logical source rows covered: 4,749,036
Source bytes covered: 2,877,354,404
Producer-scale dataframes retained: 0

In [5]:
OBSERVED_TABLE_ROWS = dict(
    zip(
        INPUT_TABLE_SUMMARY["input_key"],
        INPUT_TABLE_SUMMARY["observed_rows"],
    )
)

EXPECTED_TABLE_POPULATIONS = {
    "artworks_path": 300,
    "preprocessed_images_path": 300,
    "preprocessing_audit_path": 45,
    "canonical_masks_path": 1500,
    "canonical_cases_path": 1500,
    "case_registry_path": 3425,
    "telea_restorations_path": 2620,
    "lama_restorations_path": 2620,
    "hint_restorations_path": 2620,
    "sdxl_candidates_path": 35,
    "model_cards_path": 5,
    "case_report_index_path": 30,
    "painting_report_index_path": 300,
    "d02_screening_path": 60,
    "d02_annotations_path": 91,
}

EXPECTED_POPULATION_CONTRACT = {
    "painting_count": 300,
    "visual_category_count": 5,
    "paintings_per_category": 60,
    "registered_case_count": 3425,
    "four_model_eligible_case_count": 2620,
    "four_model_primary_candidate_count": 10480,
    "completed_bounded_sdxl_candidate_count": 24,
    "comparison_candidate_count": 10504,
    "indexed_inspectable_candidate_count": 13879,
    "repeated_seed_group_count": 1025,
    "repeated_seed_candidate_membership_count": 4100,
    "repeated_seed_unordered_pair_count": 6150,
    "painting_report_count": 300,
    "selected_case_report_count": 30,
    "model_report_count": 5,
    "final_report_count": 1,
    "d02_portraits_screened": 60,
    "d02_portraits_included": 36,
    "d02_annotations": 91,
    "d02_retained_annotations": 88,
    "d02_eligible_records": 292,
    "d02_matched_cases": 45,
    "d02_matched_painting_count": 20,
    "d02_blind_review_unit_count": 32,
    "primary_nonzero_candidate_count": 9280,
    "canonical_uncertainty_group_count": 780,
    "damage_size_uncertainty_group_count": 245,
    "n32_browsable_record_count": 331,
    "quality_anchor_count": 11,
    "ablation_scenario_count": 23,
    "documented_style_count": 268,
    "missing_style_count": 32,
    "externally_published_individual_count": 2653,
    "verified_bundle_release_count": 6,
}

for input_key, expected_rows in (
    EXPECTED_TABLE_POPULATIONS.items()
):
    observed_rows = int(
        OBSERVED_TABLE_ROWS.get(
            input_key,
            -1,
        )
    )

    add_check(
        "batch_1_population",
        f"{input_key}_population",
        observed_rows,
        expected_rows,
        observed_rows == expected_rows,
        "A core producer-table population differs from its contract.",
    )

for population_key, expected_value in (
    EXPECTED_POPULATION_CONTRACT.items()
):
    observed_value = POPULATION.get(
        population_key
    )

    add_check(
        "batch_1_population",
        population_key,
        observed_value,
        expected_value,
        observed_value == expected_value,
        "A Controlled-300 population value differs from the approved contract.",
    )

FINAL_PREFLIGHT_CHECKS = [
    (
        "verified_manifest_count",
        len(UPSTREAM_MANIFESTS),
        36,
    ),
    (
        "declared_input_count",
        len(DECLARED_INPUT_CHECKS),
        91,
    ),
    (
        "source_table_contract_count",
        len(INPUT_TABLE_SUMMARY),
        70,
    ),
    (
        "source_table_logical_rows",
        TOTAL_CONTRACT_ROWS,
        4_749_036,
    ),
    (
        "source_table_bytes",
        TOTAL_CONTRACT_BYTES,
        2_877_354_404,
    ),
    (
        "output_files_written",
        (
            sum(
                1
                for path in OUTPUT_ROOT.rglob("*")
                if path.is_file()
            )
            if OUTPUT_ROOT.exists()
            else 0
        ),
        0,
    ),
]

for check_name, observed, expected in (
    FINAL_PREFLIGHT_CHECKS
):
    add_check(
        "batch_1_final_preflight",
        check_name,
        observed,
        expected,
        observed == expected,
        (
            ""
            if observed == expected
            else "The final Batch 1 preflight contract failed."
        ),
    )

require_no_blocking_failures(
    "Batch 1 final preflight"
)

VALIDATION_FRAME = current_validation_frame()

VALIDATION_STAGE_SUMMARY = (
    VALIDATION_FRAME
    .groupby(
        [
            "validation_stage",
            "severity",
        ],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

VALIDATION_STAGE_SUMMARY["failed"] = (
    VALIDATION_STAGE_SUMMARY["checks"]
    - VALIDATION_STAGE_SUMMARY["passed"]
)

display(VALIDATION_STAGE_SUMMARY)

print("Batch 1 preflight passed.")
print("Validation checks:", len(VALIDATION_FRAME))
print(
    "Blocking failures:",
    len(
        blocking_validation_failures(
            VALIDATION_FRAME
        )
    ),
)
print("Manifest closure: 36/36")
print("Declared-input closure: 91/91")
print("Source-table closure: 70/70")
print("Logical rows covered:", f"{TOTAL_CONTRACT_ROWS:,}")
print("Output root:", OUTPUT_ROOT)
print("Canonical files persisted by Batch 1: 0")

               validation_stage  severity  checks  passed  failed
0              batch_1_contract  blocking      21      21       0
1       batch_1_declared_inputs  blocking      91      91       0
2       batch_1_final_preflight  blocking       6       6       0
3   batch_1_governing_contracts  blocking       5       5       0
4          batch_1_input_tables  blocking     280     280       0
5       batch_1_inventory_files  blocking       3       3       0
6  batch_1_inventory_governance  blocking       4       4       0
7   batch_1_inventory_integrity  blocking       7       7       0
8            batch_1_population  blocking      49      49       0
9    batch_1_upstream_manifests  blocking     252     252       0

Batch 1 preflight passed.
Validation checks: 718
Blocking failures: 0
Manifest closure: 36/36
Declared-input closure: 91/91
Source-table closure: 70/70
Logical rows covered: 4,749,036
Output root: D:\Masters\FH\Thesis\painting-restoration-eval\outputs\34_final_streamlit_dashboard_assets
Canonical files persisted by Batch 1: 0

## Batch 2 — Controlled-300 identity, population, and availability normalization

This read-only batch normalizes the identities and availability records required
by the Controlled-300 dashboard package.

It constructs:

- the complete registry of 3,425 experimental cases;
- the exact 2,620-case four-method-eligible population;
- the N29 inspection union of 13,879 candidates;
- one canonical identity per candidate, including its preserved seed and prompt;
- the 300-row painting lookup;
- compact model, experiment, report, filter, and availability vocabularies; and
- separately bounded N12A, D01, and D02 scope records.

N29 defines membership in the inspection union. The original restoration tables
supply seed, exact restoration path, checksum, status, and producer lineage.
Every candidate must resolve to exactly one case, painting, experiment, and model.

D01 method-selection candidates remain separate from the main inspection union.
D02 reuses existing restoration candidates and is not treated as a new candidate
producer. Missing or inapplicable identities remain null; the notebook never
substitutes another candidate, seed, prompt, case, or model.

Only required source columns are loaded. This batch performs no network requests
and writes no dashboard package files.

In [6]:
from restoration_eval.dashboard_assets import (
    as_bool,
    canonical_json_bytes,
    is_repo_relative,
    parse_json_list,
    read_csv_contract,
    sha256_file,
    stable_id,
    validate_output_frame,
)


def read_declared_csv(
    input_key: str,
    columns: list[str],
) -> pd.DataFrame:
    """Read only requested columns and enforce the declared row count."""

    contract = SETTINGS[
        "input_table_contracts"
    ][input_key]

    return read_csv_contract(
        PROJECT_ROOT
        / SETTINGS["inputs"][input_key],
        required_columns=columns,
        expected_rows=int(contract["rows"]),
        usecols=columns,
        dtype="string",
    )


def require_exact_identity(
    series: pd.Series,
    label: str,
) -> pd.Series:
    """Reject null, blank, or padded required identifiers."""

    values = series.astype("string")

    invalid = (
        values.isna()
        | values.eq("")
        | values.ne(values.str.strip())
    )

    if invalid.any():
        raise ValueError(
            f"{label} contains "
            f"{int(invalid.sum())} invalid identities."
        )

    return values.str.strip()


def optional_exact_identity(
    series: pd.Series,
    label: str,
) -> pd.Series:
    """Preserve optional identifiers as null rather than empty strings."""

    values = series.astype("string")

    invalid = (
        values.notna()
        & (
            values.eq("")
            | values.ne(values.str.strip())
        )
    )

    if invalid.any():
        raise ValueError(
            f"{label} contains "
            f"{int(invalid.sum())} invalid optional identities."
        )

    return values.str.strip()


def nullable_scalar(value):
    """Return JSON-compatible null for missing scalar identities."""

    return None if pd.isna(value) else value


def require_unique(
    frame: pd.DataFrame,
    columns: list[str],
    label: str,
) -> None:
    """Require uniqueness for one declared key."""

    duplicate_count = int(
        frame.duplicated(columns).sum()
    )

    if duplicate_count:
        raise ValueError(
            f"{label} contains "
            f"{duplicate_count} duplicate keys."
        )


def normalize_repo_paths(
    series: pd.Series,
) -> pd.Series:
    """Normalize separators while preserving null paths."""

    return (
        series.astype("string")
        .str.replace("\\", "/", regex=False)
        .str.strip()
    )


def require_repo_paths(
    series: pd.Series,
    label: str,
    *,
    must_exist: bool = False,
) -> None:
    """Reject unsafe paths and optionally require local files."""

    invalid: list[str] = []
    missing: list[str] = []

    for value in series.dropna():
        text = str(value).strip()

        if not is_repo_relative(text):
            invalid.append(text)
        elif (
            must_exist
            and not (
                PROJECT_ROOT / text
            ).is_file()
        ):
            missing.append(text)

    if invalid:
        raise ValueError(
            f"{label} contains unsafe paths: "
            f"{invalid[:10]}"
        )

    if missing:
        raise FileNotFoundError(
            f"{label} contains missing files: "
            f"{missing[:10]}"
        )


def producer_repo_path(
    input_key: str,
    value: object,
) -> str | None:
    """Convert producer-local restoration paths to repository paths."""

    if pd.isna(value):
        return None

    text = (
        str(value)
        .strip()
        .replace("\\", "/")
    )

    if text.startswith("outputs/"):
        return text

    producer_root = (
        Path(
            SETTINGS["inputs"][input_key]
        )
        .parent
        .parent
        .as_posix()
    )

    return (
        f"{producer_root}/{text}"
        .replace("//", "/")
    )


def json_list_errors(
    frame: pd.DataFrame,
    columns: list[str],
) -> list[str]:
    """Return concise errors for malformed JSON-list columns."""

    errors: list[str] = []

    for column in columns:
        for row_index, value in frame[
            column
        ].items():
            try:
                parse_json_list(value)
            except (
                TypeError,
                ValueError,
                json.JSONDecodeError,
            ) as exc:
                errors.append(
                    f"{column}[{row_index}]: "
                    f"{type(exc).__name__}: {exc}"
                )

                if len(errors) >= 20:
                    return errors

    return errors


print("Batch 2 bounded normalization helpers initialized.")

Batch 2 bounded normalization helpers initialized.

In [7]:
# ---------------------------------------------------------------------------
# Model dimension and full-scope model set
# ---------------------------------------------------------------------------

MODEL_CARD_COLUMNS = [
    "model_id",
    "display_name",
    "evaluation_status",
    "model_family",
    "methodological_role",
    "deterministic",
    "stochastic",
    "prompt_dependent",
    "status",
]

MODEL_DIMENSION = read_declared_csv(
    "model_cards_path",
    MODEL_CARD_COLUMNS,
)

for column in [
    "model_id",
    "display_name",
    "evaluation_status",
]:
    MODEL_DIMENSION[column] = (
        require_exact_identity(
            MODEL_DIMENSION[column],
            f"model_cards.{column}",
        )
    )

for column in [
    "deterministic",
    "stochastic",
    "prompt_dependent",
]:
    MODEL_DIMENSION[column] = (
        MODEL_DIMENSION[column].map(as_bool)
    )

require_unique(
    MODEL_DIMENSION,
    ["model_id"],
    "N30 model cards",
)

MODEL_DIMENSION = (
    MODEL_DIMENSION
    .sort_values("model_id")
    .reset_index(drop=True)
)

FULL_SCOPE_MODEL_IDS = sorted(
    MODEL_DIMENSION.loc[
        MODEL_DIMENSION[
            "evaluation_status"
        ].eq("fully_evaluated"),
        "model_id",
    ].tolist()
)

EXPECTED_FULL_SCOPE_MODEL_IDS = sorted(
    [
        "hint_places2",
        "lama",
        "opencv_telea",
        "stable_diffusion_inpainting",
    ]
)

if (
    FULL_SCOPE_MODEL_IDS
    != EXPECTED_FULL_SCOPE_MODEL_IDS
):
    raise ValueError(
        "The four full-scope model identities changed."
    )


# ---------------------------------------------------------------------------
# Complete N08 case and eligibility dimensions
# ---------------------------------------------------------------------------

CASE_COLUMNS = [
    "case_id",
    "dataset_scope",
    "experiment_id",
    "painting_id",
    "input_image_path",
    "clean_image_path",
    "mask_or_effect_id",
    "mask_or_effect_path",
    "damage_or_degradation_type",
    "target_damage_fraction",
    "realized_damage_fraction",
    "status",
]

CASE_INDEX = read_declared_csv(
    "case_registry_path",
    CASE_COLUMNS,
)

for column in [
    "case_id",
    "experiment_id",
    "painting_id",
    "mask_or_effect_id",
]:
    CASE_INDEX[column] = require_exact_identity(
        CASE_INDEX[column],
        f"case_registry.{column}",
    )

for column in [
    "input_image_path",
    "clean_image_path",
    "mask_or_effect_path",
]:
    CASE_INDEX[column] = normalize_repo_paths(
        CASE_INDEX[column]
    )

    require_repo_paths(
        CASE_INDEX[column],
        f"case_registry.{column}",
        must_exist=True,
    )

for column in [
    "target_damage_fraction",
    "realized_damage_fraction",
]:
    CASE_INDEX[column] = (
        pd.to_numeric(
            CASE_INDEX[column],
            errors="coerce",
        )
        .astype("Float64")
    )

require_unique(
    CASE_INDEX,
    ["case_id"],
    "N08 case registry",
)

ELIGIBILITY_INDEX = read_declared_csv(
    "model_eligibility_path",
    [
        "case_id",
        "model_id",
        "eligible",
        "eligibility_reason",
    ],
)

ELIGIBILITY_INDEX["case_id"] = (
    require_exact_identity(
        ELIGIBILITY_INDEX["case_id"],
        "model_eligibility.case_id",
    )
)

ELIGIBILITY_INDEX["model_id"] = (
    require_exact_identity(
        ELIGIBILITY_INDEX["model_id"],
        "model_eligibility.model_id",
    )
)

ELIGIBILITY_INDEX["eligible"] = (
    ELIGIBILITY_INDEX["eligible"].map(as_bool)
)

require_unique(
    ELIGIBILITY_INDEX,
    ["case_id", "model_id"],
    "N08 model eligibility",
)

full_eligible_counts = (
    ELIGIBILITY_INDEX.loc[
        ELIGIBILITY_INDEX[
            "model_id"
        ].isin(FULL_SCOPE_MODEL_IDS)
        & ELIGIBILITY_INDEX["eligible"]
    ]
    .groupby("case_id")["model_id"]
    .nunique()
)

CASE_INDEX["four_method_eligible"] = (
    CASE_INDEX["case_id"]
    .map(full_eligible_counts)
    .fillna(0)
    .eq(4)
)


# ---------------------------------------------------------------------------
# N29 inspection-union membership and evidence availability
# ---------------------------------------------------------------------------

N29_COLUMNS = [
    "explanation_case_id",
    "candidate_id",
    "case_id",
    "painting_id",
    "model_id",
    "experiment_id",
    "prompt_variant_id",
    "population_role",
    "category",
    "style_or_period",
    "degradation_family",
    "severity",
    "restored_path",
    "damaged_path",
    "clean_path",
    "mask_path",
    "difference_paths_json",
    "uncertainty_paths_json",
    "seam_paths_json",
    "colour_paths_json",
    "texture_paths_json",
    "semantic_paths_json",
    "mask_boundary_paths_json",
    "asset_availability_json",
    "recommendation_category",
    "manual_review_required",
    "triggered_flag_ids_json",
    "insufficient_flag_ids_json",
    "triggered_category_ids_json",
    "triggering_evidence_ids_json",
    "affected_regions_json",
    "recommended_actions_json",
    "metric_disagreement_ids_json",
    "uncertainty_group_id",
    "uncertainty_applicability",
    "retrieval_dino_eligible",
    "retrieval_clip_eligible",
    "retrieval_lane",
    "report_selected",
    "report_selection_roles_json",
    "counterfactual_panel_ids_json",
    "evidence_source_notebook_ids_json",
    "evidence_coverage_status",
    "scope_status",
    "scope_note",
    "schema_version",
    "status",
    "issue",
]

CANDIDATE_INDEX = read_declared_csv(
    "explanation_cases_path",
    N29_COLUMNS,
)

for column in [
    "explanation_case_id",
    "candidate_id",
    "case_id",
    "painting_id",
    "model_id",
    "experiment_id",
    "population_role",
]:
    CANDIDATE_INDEX[column] = (
        require_exact_identity(
            CANDIDATE_INDEX[column],
            f"n29.{column}",
        )
    )

for column in [
    "prompt_variant_id",
    "uncertainty_group_id",
]:
    CANDIDATE_INDEX[column] = (
        optional_exact_identity(
            CANDIDATE_INDEX[column],
            f"n29.{column}",
        )
    )

for column in [
    "restored_path",
    "damaged_path",
    "clean_path",
    "mask_path",
]:
    CANDIDATE_INDEX[column] = (
        normalize_repo_paths(
            CANDIDATE_INDEX[column]
        )
    )

    require_repo_paths(
        CANDIDATE_INDEX[column],
        f"n29.{column}",
        must_exist=True,
    )

for column in [
    "manual_review_required",
    "retrieval_dino_eligible",
    "retrieval_clip_eligible",
    "report_selected",
]:
    CANDIDATE_INDEX[column] = (
        CANDIDATE_INDEX[column].map(as_bool)
    )

require_unique(
    CANDIDATE_INDEX,
    ["candidate_id"],
    "N29 candidate index",
)

require_unique(
    CANDIDATE_INDEX,
    ["explanation_case_id"],
    "N29 explanation rows",
)

JSON_LIST_COLUMNS = [
    "difference_paths_json",
    "uncertainty_paths_json",
    "seam_paths_json",
    "colour_paths_json",
    "texture_paths_json",
    "semantic_paths_json",
    "mask_boundary_paths_json",
    "asset_availability_json",
    "triggered_flag_ids_json",
    "insufficient_flag_ids_json",
    "triggered_category_ids_json",
    "triggering_evidence_ids_json",
    "affected_regions_json",
    "recommended_actions_json",
    "metric_disagreement_ids_json",
    "report_selection_roles_json",
    "counterfactual_panel_ids_json",
    "evidence_source_notebook_ids_json",
]

CANDIDATE_JSON_ERRORS = json_list_errors(
    CANDIDATE_INDEX,
    JSON_LIST_COLUMNS,
)

if CANDIDATE_JSON_ERRORS:
    raise ValueError(
        "N29 JSON-list fields failed: "
        f"{CANDIDATE_JSON_ERRORS[:5]}"
    )


# ---------------------------------------------------------------------------
# Join seed, checksum, status, and producer lineage
# ---------------------------------------------------------------------------

PRODUCER_SPECS = [
    (
        "telea_restorations_path",
        "09",
        False,
        False,
    ),
    (
        "lama_restorations_path",
        "10",
        False,
        False,
    ),
    (
        "sd_candidates_path",
        "11",
        True,
        True,
    ),
    (
        "sdxl_candidates_path",
        "12",
        True,
        True,
    ),
    (
        "hint_restorations_path",
        "12A",
        False,
        False,
    ),
    (
        "damage_size_uncertainty_candidates_path",
        "22",
        True,
        True,
    ),
]

producer_frames: list[pd.DataFrame] = []

for (
    input_key,
    notebook_id,
    has_painting,
    has_prompt,
) in PRODUCER_SPECS:
    columns = [
        "candidate_id",
        "case_id",
        "model_id",
        "seed",
        "restored_path",
        "restored_sha256",
        "status",
    ]

    if has_painting:
        columns.append("painting_id")

    if has_prompt:
        columns.append("prompt_variant_id")

    frame = read_declared_csv(
        input_key,
        columns,
    )

    if "painting_id" not in frame:
        frame["painting_id"] = pd.Series(
            pd.NA,
            index=frame.index,
            dtype="string",
        )

    if "prompt_variant_id" not in frame:
        frame["prompt_variant_id"] = pd.Series(
            pd.NA,
            index=frame.index,
            dtype="string",
        )

    frame["producer_notebook_id"] = (
        notebook_id
    )

    frame["producer_input_key"] = input_key

    frame["restored_path"] = [
        producer_repo_path(
            input_key,
            value,
        )
        for value in frame["restored_path"]
    ]

    frame = frame.rename(
        columns={
            "case_id": "producer_case_id",
            "painting_id": (
                "producer_painting_id"
            ),
            "model_id": "producer_model_id",
            "prompt_variant_id": (
                "producer_prompt_variant_id"
            ),
            "seed": "producer_seed",
            "restored_path": (
                "producer_restored_path"
            ),
            "restored_sha256": (
                "producer_restored_sha256"
            ),
            "status": "producer_status",
        }
    )

    producer_frames.append(frame)

PRODUCER_CANDIDATES = pd.concat(
    producer_frames,
    ignore_index=True,
)

del producer_frames

for column in [
    "candidate_id",
    "producer_case_id",
    "producer_model_id",
]:
    PRODUCER_CANDIDATES[column] = (
        require_exact_identity(
            PRODUCER_CANDIDATES[column],
            f"producer.{column}",
        )
    )

for column in [
    "producer_painting_id",
    "producer_prompt_variant_id",
]:
    PRODUCER_CANDIDATES[column] = (
        optional_exact_identity(
            PRODUCER_CANDIDATES[column],
            f"producer.{column}",
        )
    )

PRODUCER_CANDIDATES[
    "producer_restored_path"
] = normalize_repo_paths(
    PRODUCER_CANDIDATES[
        "producer_restored_path"
    ]
)

require_unique(
    PRODUCER_CANDIDATES,
    ["candidate_id"],
    "candidate-producing tables",
)

CANDIDATE_INDEX = CANDIDATE_INDEX.merge(
    PRODUCER_CANDIDATES,
    on="candidate_id",
    how="left",
    validate="one_to_one",
)

IDENTITY_MISMATCHES = {
    "missing_producer": int(
        CANDIDATE_INDEX[
            "producer_input_key"
        ].isna().sum()
    ),
    "case_id": int(
        CANDIDATE_INDEX["case_id"]
        .ne(
            CANDIDATE_INDEX[
                "producer_case_id"
            ]
        )
        .sum()
    ),
    "model_id": int(
        CANDIDATE_INDEX["model_id"]
        .ne(
            CANDIDATE_INDEX[
                "producer_model_id"
            ]
        )
        .sum()
    ),
    "painting_id": int(
        (
            CANDIDATE_INDEX[
                "producer_painting_id"
            ].notna()
            & CANDIDATE_INDEX[
                "painting_id"
            ].ne(
                CANDIDATE_INDEX[
                    "producer_painting_id"
                ]
            )
        ).sum()
    ),
    "prompt_variant_id": int(
        (
            CANDIDATE_INDEX[
                "producer_prompt_variant_id"
            ].notna()
            & CANDIDATE_INDEX[
                "prompt_variant_id"
            ]
            .fillna("<null>")
            .ne(
                CANDIDATE_INDEX[
                    "producer_prompt_variant_id"
                ].fillna("<null>")
            )
        ).sum()
    ),
    "restored_path": int(
        CANDIDATE_INDEX[
            "restored_path"
        ]
        .ne(
            CANDIDATE_INDEX[
                "producer_restored_path"
            ]
        )
        .sum()
    ),
}

if any(IDENTITY_MISMATCHES.values()):
    raise ValueError(
        "Producer/N29 identity mismatch: "
        f"{IDENTITY_MISMATCHES}"
    )

CANDIDATE_INDEX["seed"] = (
    pd.to_numeric(
        CANDIDATE_INDEX["producer_seed"],
        errors="raise",
    )
    .astype("Int64")
)

CANDIDATE_INDEX[
    "producer_restored_sha256"
] = (
    CANDIDATE_INDEX[
        "producer_restored_sha256"
    ]
    .str.lower()
)

case_identity = (
    CASE_INDEX[
        [
            "case_id",
            "painting_id",
            "experiment_id",
        ]
    ]
    .rename(
        columns={
            "painting_id": (
                "registry_painting_id"
            ),
            "experiment_id": (
                "registry_experiment_id"
            ),
        }
    )
)

CANDIDATE_INDEX = CANDIDATE_INDEX.merge(
    case_identity,
    on="case_id",
    how="left",
    validate="many_to_one",
)

REGISTRY_IDENTITY_MISMATCHES = {
    "painting_id": int(
        CANDIDATE_INDEX["painting_id"]
        .ne(
            CANDIDATE_INDEX[
                "registry_painting_id"
            ]
        )
        .sum()
    ),
    "experiment_id": int(
        CANDIDATE_INDEX["experiment_id"]
        .ne(
            CANDIDATE_INDEX[
                "registry_experiment_id"
            ]
        )
        .sum()
    ),
}

if any(
    REGISTRY_IDENTITY_MISMATCHES.values()
):
    raise ValueError(
        "N29 candidate-to-case identity "
        "differs from N08: "
        f"{REGISTRY_IDENTITY_MISMATCHES}"
    )


# ---------------------------------------------------------------------------
# Canonical candidate identity
# ---------------------------------------------------------------------------

identity_json: list[str] = []
identity_record_ids: list[str] = []

for row in CANDIDATE_INDEX.itertuples(
    index=False
):
    identity = {
        "painting_id": row.painting_id,
        "case_id": row.case_id,
        "candidate_id": row.candidate_id,
        "model_id": row.model_id,
        "experiment_id": row.experiment_id,
        "seed": (
            None
            if pd.isna(row.seed)
            else int(row.seed)
        ),
        "prompt_variant_id": nullable_scalar(
            row.prompt_variant_id
        ),
        "uncertainty_group_id": nullable_scalar(
            row.uncertainty_group_id
        ),
        "metric_name": None,
        "region_id": None,
        "evidence_layer": None,
        "annotation_id": None,
        "hand_control_id": None,
        "review_unit_id": None,
        "blind_review_code": None,
    }

    identity_json.append(
        canonical_json_bytes(
            identity
        ).decode("utf-8")
    )

    identity_record_ids.append(
        stable_id(
            "candidate_record",
            identity,
        )
    )

CANDIDATE_INDEX[
    "identity_json"
] = identity_json

CANDIDATE_INDEX[
    "candidate_record_id"
] = identity_record_ids

CANDIDATE_INDEX[
    "availability_state"
] = "available_local"

require_unique(
    CANDIDATE_INDEX,
    ["candidate_record_id"],
    "canonical candidate identities",
)

CANDIDATE_INDEX = (
    CANDIDATE_INDEX
    .sort_values(
        [
            "painting_id",
            "case_id",
            "model_id",
            "seed",
            "candidate_id",
        ],
        na_position="last",
    )
    .reset_index(drop=True)
)

print("Controlled-300 identities normalized.")
print("Registered cases:", len(CASE_INDEX))
print(
    "Four-method eligible cases:",
    int(
        CASE_INDEX[
            "four_method_eligible"
        ].sum()
    ),
)
print(
    "Producer candidates inspected:",
    len(PRODUCER_CANDIDATES),
)
print(
    "Inspectable candidates retained:",
    len(CANDIDATE_INDEX),
)
print(
    "Identity mismatches:",
    IDENTITY_MISMATCHES,
)

Controlled-300 identities normalized.
Registered cases: 3425
Four-method eligible cases: 2620
Producer candidates inspected: 17150
Inspectable candidates retained: 13879
Identity mismatches: {'missing_producer': 0, 'case_id': 0, 'model_id': 0, 'painting_id': 0, 'prompt_variant_id': 0, 'restored_path': 0}

In [8]:
# ---------------------------------------------------------------------------
# Painting metadata and clean-image identity
# ---------------------------------------------------------------------------

ARTWORK_COLUMNS = [
    "painting_id",
    "dataset_sort_index",
    "title",
    "artist",
    "date_or_period",
    "style_or_period",
    "category",
    "medium",
    "source",
    "license",
    "rights_status",
    "raw_image_path",
    "metadata_completeness_pct",
]

PREPROCESSED_COLUMNS = [
    "painting_id",
    "processed_path",
    "status",
]

ARTWORKS = read_declared_csv(
    "artworks_path",
    ARTWORK_COLUMNS,
)

PREPROCESSED = (
    read_declared_csv(
        "preprocessed_images_path",
        PREPROCESSED_COLUMNS,
    )
    .rename(
        columns={
            "processed_path": "clean_image_path"
        }
    )
)

ARTWORKS["painting_id"] = (
    require_exact_identity(
        ARTWORKS["painting_id"],
        "artworks.painting_id",
    )
)

PREPROCESSED["painting_id"] = (
    require_exact_identity(
        PREPROCESSED["painting_id"],
        "preprocessed.painting_id",
    )
)

require_unique(
    ARTWORKS,
    ["painting_id"],
    "N01 artworks",
)

require_unique(
    PREPROCESSED,
    ["painting_id"],
    "N02 preprocessed images",
)


# ---------------------------------------------------------------------------
# Report indexes
# ---------------------------------------------------------------------------

CASE_REPORT_INDEX = read_declared_csv(
    "case_report_index_path",
    [
        "report_id",
        "case_id",
        "painting_id",
        "report_path",
        "report_sha256",
        "self_contained",
        "status",
    ],
)

PAINTING_REPORT_INDEX = read_declared_csv(
    "painting_report_index_path",
    [
        "report_id",
        "painting_id",
        "report_path",
        "report_sha256",
        "self_contained",
        "status",
    ],
)

MODEL_REPORT_INDEX = read_declared_csv(
    "model_report_index_path",
    [
        "report_id",
        "model_id",
        "evaluation_status",
        "report_path",
        "report_sha256",
        "self_contained",
        "status",
    ],
)

for frame, key, label in [
    (
        CASE_REPORT_INDEX,
        "case_id",
        "case reports",
    ),
    (
        PAINTING_REPORT_INDEX,
        "painting_id",
        "painting reports",
    ),
    (
        MODEL_REPORT_INDEX,
        "model_id",
        "model reports",
    ),
]:
    frame[key] = require_exact_identity(
        frame[key],
        f"{label}.{key}",
    )

    frame["report_path"] = (
        normalize_repo_paths(
            frame["report_path"]
        )
    )

    frame["self_contained"] = (
        frame["self_contained"].map(as_bool)
    )

    require_unique(
        frame,
        [key],
        label,
    )

    require_repo_paths(
        frame["report_path"],
        label,
        must_exist=True,
    )


# ---------------------------------------------------------------------------
# Formal 300-row painting lookup
# ---------------------------------------------------------------------------

case_counts = (
    CASE_INDEX
    .groupby("painting_id")["case_id"]
    .nunique()
)

candidate_counts = (
    CANDIDATE_INDEX
    .groupby("painting_id")["candidate_id"]
    .size()
)

has_uncertainty = (
    CANDIDATE_INDEX
    .groupby("painting_id")[
        "uncertainty_group_id"
    ]
    .apply(
        lambda values: values.notna().any()
    )
)

selected_report_paintings = set(
    CASE_REPORT_INDEX["painting_id"]
)

painting_source = ARTWORKS.merge(
    PREPROCESSED,
    on="painting_id",
    validate="one_to_one",
)

PAINTING_LOOKUP = pd.DataFrame(
    {
        "painting_id": (
            painting_source["painting_id"]
        ),
        "dataset_sort_index": (
            pd.to_numeric(
                painting_source[
                    "dataset_sort_index"
                ],
                errors="raise",
            ).astype(int)
        ),
        "title": painting_source["title"],
        "artist": painting_source["artist"],
        "date_or_period": (
            painting_source["date_or_period"]
        ),
        "style_or_period": (
            painting_source["style_or_period"]
        ),
        "category": painting_source["category"],
        "medium": painting_source["medium"],
        "source": painting_source["source"],
        "license": painting_source["license"],
        "rights_status": (
            painting_source["rights_status"]
        ),
        "raw_image_path": (
            normalize_repo_paths(
                painting_source[
                    "raw_image_path"
                ]
            )
        ),
        "clean_image_path": (
            normalize_repo_paths(
                painting_source[
                    "clean_image_path"
                ]
            )
        ),
        "metadata_completeness_pct": (
            pd.to_numeric(
                painting_source[
                    "metadata_completeness_pct"
                ],
                errors="coerce",
            )
        ),
        "case_count": (
            painting_source["painting_id"]
            .map(case_counts)
            .astype(int)
        ),
        "candidate_count": (
            painting_source["painting_id"]
            .map(candidate_counts)
            .astype(int)
        ),
        "has_uncertainty": (
            painting_source["painting_id"]
            .map(has_uncertainty)
            .fillna(False)
            .astype(bool)
        ),
        "has_selected_case_report": (
            painting_source["painting_id"]
            .isin(selected_report_paintings)
        ),
        "painting_partition_path": [
            SETTINGS["output"][
                "painting_shard_template"
            ].format(
                painting_id=painting_id
            )
            for painting_id
            in painting_source["painting_id"]
        ],
        "schema_version": (
            SETTINGS[
                "expected_output_schemas"
            ]["painting_lookup"]
        ),
        "status": "ok",
        "issue": "",
    }
)

PAINTING_LOOKUP = (
    validate_output_frame(
        PAINTING_LOOKUP,
        "painting_lookup",
    )
    .sort_values(
        [
            "dataset_sort_index",
            "painting_id",
        ]
    )
    .reset_index(drop=True)
)

for column in [
    "raw_image_path",
    "clean_image_path",
]:
    require_repo_paths(
        PAINTING_LOOKUP[column],
        f"painting_lookup.{column}",
        must_exist=True,
    )

require_repo_paths(
    PAINTING_LOOKUP[
        "painting_partition_path"
    ],
    "painting_lookup.painting_partition_path",
)

print("Painting lookup constructed.")
print("Painting rows:", len(PAINTING_LOOKUP))
print(
    "Painting reports:",
    len(PAINTING_REPORT_INDEX),
)
print(
    "Selected case reports:",
    len(CASE_REPORT_INDEX),
)
print(
    "Model reports:",
    len(MODEL_REPORT_INDEX),
)

Painting lookup constructed.
Painting rows: 300
Painting reports: 300
Selected case reports: 30
Model reports: 5

In [9]:
# ---------------------------------------------------------------------------
# Experiment dimension
# ---------------------------------------------------------------------------

EXPERIMENT_DIMENSION = (
    CASE_INDEX
    .groupby(
        "experiment_id",
        sort=True,
    )
    .agg(
        registered_case_count=(
            "case_id",
            "nunique",
        ),
        eligible_case_count=(
            "four_method_eligible",
            "sum",
        ),
        painting_count=(
            "painting_id",
            "nunique",
        ),
    )
    .reset_index()
)

candidate_experiment = (
    CANDIDATE_INDEX
    .groupby(
        "experiment_id",
        sort=True,
    )
    .agg(
        inspected_case_count=(
            "case_id",
            "nunique",
        ),
        candidate_count=(
            "candidate_id",
            "size",
        ),
        model_count=(
            "model_id",
            "nunique",
        ),
    )
    .reset_index()
)

EXPERIMENT_DIMENSION = (
    EXPERIMENT_DIMENSION.merge(
        candidate_experiment,
        on="experiment_id",
        how="left",
        validate="one_to_one",
    )
)


# ---------------------------------------------------------------------------
# Unified report dimension
# ---------------------------------------------------------------------------

report_rows: list[dict] = []

for (
    report_type,
    frame,
    entity_column,
) in [
    (
        "painting",
        PAINTING_REPORT_INDEX,
        "painting_id",
    ),
    (
        "case",
        CASE_REPORT_INDEX,
        "case_id",
    ),
    (
        "model",
        MODEL_REPORT_INDEX,
        "model_id",
    ),
]:
    for row in frame.itertuples(
        index=False
    ):
        report_rows.append(
            {
                "report_id": row.report_id,
                "report_type": report_type,
                "entity_id": getattr(
                    row,
                    entity_column,
                ),
                "report_path": row.report_path,
                "report_sha256": (
                    row.report_sha256
                ),
                "self_contained": bool(
                    row.self_contained
                ),
                "status": row.status,
            }
        )

for report_type, input_key in [
    (
        "collection",
        "report_collection_index_path",
    ),
    (
        "final",
        "final_report_path",
    ),
]:
    relative_path = (
        SETTINGS["inputs"][input_key]
    )

    report_path = (
        PROJECT_ROOT / relative_path
    )

    report_rows.append(
        {
            "report_id": stable_id(
                "dashboard_report",
                report_type,
                relative_path,
            ),
            "report_type": report_type,
            "entity_id": "controlled_300",
            "report_path": relative_path,
            "report_sha256": sha256_file(
                report_path
            ),
            "self_contained": True,
            "status": "ok",
        }
    )

REPORT_DIMENSION = (
    pd.DataFrame(report_rows)
    .sort_values(
        [
            "report_type",
            "entity_id",
        ]
    )
    .reset_index(drop=True)
)

require_unique(
    REPORT_DIMENSION,
    ["report_id"],
    "dashboard report dimension",
)

require_repo_paths(
    REPORT_DIMENSION["report_path"],
    "dashboard reports",
    must_exist=True,
)


# ---------------------------------------------------------------------------
# Metric and failure vocabularies
# ---------------------------------------------------------------------------

REGION_POLICY_DIMENSION = (
    read_declared_csv(
        "region_policy_path",
        [
            "policy_id",
            "metric_family",
            "region_id",
            "compatible",
            "primary_role",
            "status",
        ],
    )
)

FAILURE_TAXONOMY_DIMENSION = (
    read_declared_csv(
        "failure_taxonomy_path",
        [
            "category_id",
            "display_name",
            "definition",
            "is_proxy",
            "status",
        ],
    )
)


# ---------------------------------------------------------------------------
# D01 remains a separate method-selection population
# ---------------------------------------------------------------------------

D01_SCOPE = read_declared_csv(
    "d01_selection_scope_path",
    [
        "case_id",
        "painting_id",
        "experiment_id",
        "status",
    ],
)

D01_CANDIDATES = read_declared_csv(
    "d01_candidates_path",
    [
        "candidate_id",
        "case_id",
        "painting_id",
        "model_id",
        "status",
    ],
)

require_unique(
    D01_CANDIDATES,
    ["candidate_id"],
    "D01 candidates",
)

D01_MAIN_COLLISIONS = sorted(
    set(D01_CANDIDATES["candidate_id"])
    & set(CANDIDATE_INDEX["candidate_id"])
)


# ---------------------------------------------------------------------------
# D02 reuses existing cases and candidates
# ---------------------------------------------------------------------------

D02_SCREENING = read_declared_csv(
    "d02_screening_path",
    [
        "painting_id",
        "screening_status",
    ],
)

D02_ANNOTATIONS = read_declared_csv(
    "d02_annotations_path",
    [
        "annotation_id",
        "painting_id",
        "review_status",
    ],
)

D02_ELIGIBLE = read_declared_csv(
    "d02_eligible_path",
    [
        "case_id",
        "painting_id",
        "experiment_id",
        "primary_hand_eligible",
        "primary_skin_eligible",
    ],
)

D02_MANUAL = read_declared_csv(
    "d02_manual_review_path",
    [
        "review_unit_id",
        "hand_control_id",
        "case_id",
        "painting_id",
        "annotation_id",
        "candidate_id",
        "model_id",
        "blind_review_code",
        "review_status",
    ],
)

D02_HAND = read_declared_csv(
    "d02_hand_comparison_path",
    [
        "case_id",
        "painting_id",
        "candidate_id",
        "model_id",
    ],
)

D02_LIGHTNESS = read_declared_csv(
    "d02_lightness_path",
    [
        "case_id",
        "painting_id",
        "candidate_id",
        "model_id",
    ],
)

d02_hand_primary = D02_ELIGIBLE.loc[
    D02_ELIGIBLE[
        "primary_hand_eligible"
    ].map(as_bool)
]

D02_CANDIDATE_IDS = (
    set(D02_MANUAL["candidate_id"])
    | set(D02_HAND["candidate_id"])
    | set(D02_LIGHTNESS["candidate_id"])
)

D02_MISSING_CANDIDATE_IDS = sorted(
    D02_CANDIDATE_IDS
    - set(CANDIDATE_INDEX["candidate_id"])
)

D02_MISSING_REGISTRY_CASE_IDS = sorted(
    set(D02_ELIGIBLE["case_id"])
    - set(CASE_INDEX["case_id"])
)

D02_SCOPE_SUMMARY = {
    "portraits_screened": (
        len(D02_SCREENING)
    ),
    "portraits_included": int(
        D02_SCREENING[
            "screening_status"
        ].eq("included").sum()
    ),
    "annotations": len(D02_ANNOTATIONS),
    "retained_annotations": int(
        D02_ANNOTATIONS[
            "review_status"
        ].ne("excluded").sum()
    ),
    "eligible_records": len(D02_ELIGIBLE),
    "matched_cases": (
        d02_hand_primary[
            "case_id"
        ].nunique()
    ),
    "matched_paintings": (
        d02_hand_primary[
            "painting_id"
        ].nunique()
    ),
    "blind_review_units": (
        D02_MANUAL[
            "review_unit_id"
        ].nunique()
    ),
}

N12A_IDS = set(
    CANDIDATE_INDEX.loc[
        CANDIDATE_INDEX[
            "producer_notebook_id"
        ].eq("12A"),
        "candidate_id",
    ]
)

N29_HINT_IDS = set(
    CANDIDATE_INDEX.loc[
        CANDIDATE_INDEX[
            "model_id"
        ].eq("hint_places2"),
        "candidate_id",
    ]
)

N12A_HINT_SET_DIFFERENCE = {
    "missing_from_n12a": len(
        N29_HINT_IDS - N12A_IDS
    ),
    "extra_in_n12a": len(
        N12A_IDS - N29_HINT_IDS
    ),
}

AVAILABLE_EVIDENCE_LAYERS = sorted(
    {
        layer
        for value in CANDIDATE_INDEX[
            "asset_availability_json"
        ]
        for layer in parse_json_list(value)
    }
)


# ---------------------------------------------------------------------------
# Shared selector vocabulary
# ---------------------------------------------------------------------------

FILTER_OPTIONS = {
    "schema_version": (
        SETTINGS[
            "expected_output_schemas"
        ]["filter_options"]
    ),
    "principal_room_ids": (
        ROOM_PLAN.loc[
            ROOM_PLAN[
                "route_kind"
            ].eq("principal"),
            "room_id",
        ].tolist()
    ),
    "child_routes": (
        ROOM_PLAN.loc[
            ROOM_PLAN[
                "route_kind"
            ].eq("child"),
            [
                "room_id",
                "parent_room_id",
            ],
        ].to_dict(orient="records")
    ),
    "painting_ids": (
        PAINTING_LOOKUP[
            "painting_id"
        ].tolist()
    ),
    "categories": sorted(
        PAINTING_LOOKUP[
            "category"
        ].dropna().unique().tolist()
    ),
    "styles_or_periods": sorted(
        PAINTING_LOOKUP[
            "style_or_period"
        ].dropna().unique().tolist()
    ),
    "models": (
        MODEL_DIMENSION[
            [
                "model_id",
                "display_name",
                "evaluation_status",
            ]
        ].to_dict(orient="records")
    ),
    "experiment_ids": sorted(
        CANDIDATE_INDEX[
            "experiment_id"
        ].dropna().unique().tolist()
    ),
    "degradation_families": sorted(
        CANDIDATE_INDEX[
            "degradation_family"
        ].dropna().unique().tolist()
    ),
    "population_roles": sorted(
        CANDIDATE_INDEX[
            "population_role"
        ].dropna().unique().tolist()
    ),
    "recommendation_categories": sorted(
        CANDIDATE_INDEX[
            "recommendation_category"
        ].dropna().unique().tolist()
    ),
    "seed_values": sorted(
        int(value)
        for value in CANDIDATE_INDEX[
            "seed"
        ].dropna().unique()
    ),
    "prompt_variant_ids": sorted(
        CANDIDATE_INDEX[
            "prompt_variant_id"
        ].dropna().unique().tolist()
    ),
    "metric_families": sorted(
        REGION_POLICY_DIMENSION[
            "metric_family"
        ].dropna().unique().tolist()
    ),
    "region_ids": sorted(
        REGION_POLICY_DIMENSION[
            "region_id"
        ].dropna().unique().tolist()
    ),
    "failure_categories": (
        FAILURE_TAXONOMY_DIMENSION[
            [
                "category_id",
                "display_name",
                "is_proxy",
            ]
        ]
        .sort_values("category_id")
        .to_dict(orient="records")
    ),
    "evidence_layers": (
        AVAILABLE_EVIDENCE_LAYERS
    ),
    "status": "ok",
}

# Large D02 measurement rows are reloaded only by the later
# D02 derivation batch.
del D02_HAND
del D02_LIGHTNESS

display(MODEL_DIMENSION)
display(EXPERIMENT_DIMENSION)
display(
    REPORT_DIMENSION[
        "report_type"
    ].value_counts()
)

print("Shared Controlled-300 dimensions constructed.")
print("Reports indexed:", len(REPORT_DIMENSION))
print("D01 candidates kept separate:", len(D01_CANDIDATES))
print("D02 scope:", D02_SCOPE_SUMMARY)
print("Evidence layers:", AVAILABLE_EVIDENCE_LAYERS)
print("Filter groups:", len(FILTER_OPTIONS))

,model_id,display_name,evaluation_status,model_family,methodological_role,deterministic,stochastic,prompt_dependent,status
0,hint_places2,HINT,fully_evaluated,learned_mask_aware_transformer_inpainting,learned_deterministic_mask_aware_transformer,True,False,False,ok
1,lama,LaMa,fully_evaluated,learned_fourier_convolution_inpainting,learned_deterministic_inpainting_baseline,True,False,False,ok
2,opencv_telea,OpenCV Telea,fully_evaluated,classical_fast_marching_inpainting,classical_deterministic_baseline,True,False,False,ok
3,sdxl_inpainting,SDXL Inpainting,partial_evaluation,prompt_conditioned_sdxl_latent_diffusion_inpai...,bounded_higher_capacity_diffusion_candidate,False,True,True,ok
4,stable_diffusion_inpainting,Stable Diffusion Inpainting,fully_evaluated,prompt_conditioned_latent_diffusion_inpainting,prompt_conditioned_stochastic_inpainting_baseline,False,True,True,ok

,experiment_id,registered_case_count,eligible_case_count,painting_count,inspected_case_count,candidate_count,model_count
0,canonical_missing_region,1500,1500,300,1500,8653,5
1,damage_size_sensitivity,245,245,35,245,1715,4
2,mask_robustness,525,525,35,525,2100,4
3,synthetic_degradation,1155,350,35,350,1411,5

report_type
painting      300
case           30
model           5
collection      1
final           1
Name: count, dtype: int64

Shared Controlled-300 dimensions constructed.
Reports indexed: 337
D01 candidates kept separate: 24
D02 scope: {'portraits_screened': 60, 'portraits_included': 36, 'annotations': 91, 'retained_annotations': 88, 'eligible_records': 292, 'matched_cases': 45, 'matched_paintings': 20, 'blind_review_units': 32}
Evidence layers: ['colour', 'difference', 'mask_boundary', 'seam', 'semantic', 'texture', 'uncertainty']
Filter groups: 18

In [10]:
BATCH_2_STAGE = (
    "batch_2_identity_population_normalization"
)

# Validation must be safe to rerun.
VALIDATION_ROWS[:] = [
    row
    for row in VALIDATION_ROWS
    if row["validation_stage"] != BATCH_2_STAGE
]


# ---------------------------------------------------------------------------
# Exact Controlled-300 population observations
# ---------------------------------------------------------------------------

MODEL_COUNTS = (
    CANDIDATE_INDEX
    .groupby("model_id")
    .size()
    .astype(int)
    .to_dict()
)

ROLE_COUNTS = (
    CANDIDATE_INDEX
    .groupby("population_role")
    .size()
    .astype(int)
    .to_dict()
)

EXPERIMENT_COUNTS = (
    CANDIDATE_INDEX
    .groupby("experiment_id")
    .size()
    .astype(int)
    .to_dict()
)

EXPECTED_MODEL_COUNTS = {
    "hint_places2": 2620,
    "lama": 2620,
    "opencv_telea": 2620,
    "sdxl_inpainting": 24,
    "stable_diffusion_inpainting": 5995,
}

EXPECTED_ROLE_COUNTS = {
    "bounded_sdxl": 24,
    "primary_and_uncertainty": 725,
    "primary_comparison": 9755,
    "uncertainty_only": 3375,
}

EXPECTED_EXPERIMENT_COUNTS = {
    "canonical_missing_region": 8653,
    "damage_size_sensitivity": 1715,
    "mask_robustness": 2100,
    "synthetic_degradation": 1411,
}

group_sizes = (
    CANDIDATE_INDEX
    .dropna(
        subset=["uncertainty_group_id"]
    )
    .groupby("uncertainty_group_id")[
        "candidate_id"
    ]
    .nunique()
)

unordered_pairs = int(
    (
        group_sizes
        * (group_sizes - 1)
        // 2
    ).sum()
)

primary_mask = (
    CANDIDATE_INDEX[
        "population_role"
    ].isin(
        [
            "primary_comparison",
            "primary_and_uncertainty",
        ]
    )
)

comparison_mask = (
    primary_mask
    | CANDIDATE_INDEX[
        "population_role"
    ].eq("bounded_sdxl")
)

CATEGORY_COUNTS = (
    PAINTING_LOOKUP[
        "category"
    ]
    .value_counts()
    .sort_index()
    .astype(int)
    .to_dict()
)

EXPECTED_CATEGORY_COUNTS = {
    "abstraction_surrealism": 60,
    "architecture_structured": 60,
    "high_texture_brushwork": 60,
    "landscape_natural": 60,
    "portrait_figure": 60,
}

BATCH_2_CHECKS = [
    (
        "registered_cases",
        len(CASE_INDEX),
        POPULATION[
            "registered_case_count"
        ],
    ),
    (
        "four_method_eligible_cases",
        int(
            CASE_INDEX[
                "four_method_eligible"
            ].sum()
        ),
        POPULATION[
            "four_model_eligible_case_count"
        ],
    ),
    (
        "inspectable_candidate_cases",
        CANDIDATE_INDEX[
            "case_id"
        ].nunique(),
        POPULATION[
            "four_model_eligible_case_count"
        ],
    ),
    (
        "inspectable_candidates",
        len(CANDIDATE_INDEX),
        POPULATION[
            "indexed_inspectable_candidate_count"
        ],
    ),
    (
        "four_method_primary_candidates",
        int(primary_mask.sum()),
        POPULATION[
            "four_model_primary_candidate_count"
        ],
    ),
    (
        "comparison_candidates",
        int(comparison_mask.sum()),
        POPULATION[
            "comparison_candidate_count"
        ],
    ),
    (
        "producer_candidate_universe",
        len(PRODUCER_CANDIDATES),
        17150,
    ),
    (
        "candidate_model_counts",
        MODEL_COUNTS,
        EXPECTED_MODEL_COUNTS,
    ),
    (
        "candidate_role_counts",
        ROLE_COUNTS,
        EXPECTED_ROLE_COUNTS,
    ),
    (
        "candidate_experiment_counts",
        EXPERIMENT_COUNTS,
        EXPECTED_EXPERIMENT_COUNTS,
    ),
    (
        "candidate_id_uniqueness",
        CANDIDATE_INDEX[
            "candidate_id"
        ].nunique(),
        len(CANDIDATE_INDEX),
    ),
    (
        "candidate_identity_uniqueness",
        CANDIDATE_INDEX[
            "candidate_record_id"
        ].nunique(),
        len(CANDIDATE_INDEX),
    ),
    (
        "producer_identity_mismatches",
        IDENTITY_MISMATCHES,
        {
            key: 0
            for key in IDENTITY_MISMATCHES
        },
    ),
    (
        "registry_identity_mismatches",
        REGISTRY_IDENTITY_MISMATCHES,
        {
            key: 0
            for key
            in REGISTRY_IDENTITY_MISMATCHES
        },
    ),
    (
        "candidate_json_lists",
        CANDIDATE_JSON_ERRORS,
        [],
    ),
    (
        "selected_producer_status",
        sorted(
            CANDIDATE_INDEX[
                "producer_status"
            ].unique().tolist()
        ),
        ["completed"],
    ),
    (
        "candidate_availability",
        CANDIDATE_INDEX[
            "availability_state"
        ].value_counts().to_dict(),
        {
            "available_local": (
                POPULATION[
                    "indexed_inspectable_candidate_count"
                ]
            )
        },
    ),
    (
        "repeated_seed_groups",
        len(group_sizes),
        POPULATION[
            "repeated_seed_group_count"
        ],
    ),
    (
        "repeated_seed_memberships",
        int(group_sizes.sum()),
        POPULATION[
            "repeated_seed_candidate_membership_count"
        ],
    ),
    (
        "repeated_seed_pairs",
        unordered_pairs,
        POPULATION[
            "repeated_seed_unordered_pair_count"
        ],
    ),
    (
        "painting_lookup_rows",
        len(PAINTING_LOOKUP),
        POPULATION["painting_count"],
    ),
    (
        "painting_id_uniqueness",
        PAINTING_LOOKUP[
            "painting_id"
        ].nunique(),
        POPULATION["painting_count"],
    ),
    (
        "painting_category_distribution",
        CATEGORY_COUNTS,
        EXPECTED_CATEGORY_COUNTS,
    ),
    (
        "documented_styles",
        int(
            PAINTING_LOOKUP[
                "style_or_period"
            ].notna().sum()
        ),
        POPULATION[
            "documented_style_count"
        ],
    ),
    (
        "missing_styles",
        int(
            PAINTING_LOOKUP[
                "style_or_period"
            ].isna().sum()
        ),
        POPULATION["missing_style_count"],
    ),
    (
        "painting_reports",
        len(PAINTING_REPORT_INDEX),
        POPULATION[
            "painting_report_count"
        ],
    ),
    (
        "case_reports",
        len(CASE_REPORT_INDEX),
        POPULATION[
            "selected_case_report_count"
        ],
    ),
    (
        "model_reports",
        len(MODEL_REPORT_INDEX),
        POPULATION[
            "model_report_count"
        ],
    ),
    (
        "report_dimension",
        len(REPORT_DIMENSION),
        337,
    ),
    (
        "self_contained_reports",
        int(
            REPORT_DIMENSION[
                "self_contained"
            ].sum()
        ),
        len(REPORT_DIMENSION),
    ),
    (
        "n12a_exact_hint_identity_set",
        N12A_HINT_SET_DIFFERENCE,
        {
            "missing_from_n12a": 0,
            "extra_in_n12a": 0,
        },
    ),
    (
        "d01_scope_cases",
        D01_SCOPE["case_id"].nunique(),
        12,
    ),
    (
        "d01_candidates",
        len(D01_CANDIDATES),
        24,
    ),
    (
        "d01_main_candidate_collisions",
        D01_MAIN_COLLISIONS,
        [],
    ),
    (
        "d02_missing_registry_cases",
        D02_MISSING_REGISTRY_CASE_IDS,
        [],
    ),
    (
        "d02_missing_main_candidates",
        D02_MISSING_CANDIDATE_IDS,
        [],
    ),
    (
        "d02_scope",
        D02_SCOPE_SUMMARY,
        {
            "portraits_screened": (
                POPULATION[
                    "d02_portraits_screened"
                ]
            ),
            "portraits_included": (
                POPULATION[
                    "d02_portraits_included"
                ]
            ),
            "annotations": (
                POPULATION[
                    "d02_annotations"
                ]
            ),
            "retained_annotations": (
                POPULATION[
                    "d02_retained_annotations"
                ]
            ),
            "eligible_records": (
                POPULATION[
                    "d02_eligible_records"
                ]
            ),
            "matched_cases": (
                POPULATION[
                    "d02_matched_cases"
                ]
            ),
            "matched_paintings": (
                POPULATION[
                    "d02_matched_painting_count"
                ]
            ),
            "blind_review_units": (
                POPULATION[
                    "d02_blind_review_unit_count"
                ]
            ),
        },
    ),
    (
        "no_canonical_files_written",
        (
            sum(
                path.is_file()
                for path
                in OUTPUT_ROOT.rglob("*")
            )
            if OUTPUT_ROOT.exists()
            else 0
        ),
        0,
    ),
]

for (
    check_name,
    observed,
    expected,
) in BATCH_2_CHECKS:
    passed = observed == expected

    add_check(
        BATCH_2_STAGE,
        check_name,
        observed,
        expected,
        passed,
        (
            ""
            if passed
            else (
                "Batch 2 Controlled-300 "
                "normalization differs from "
                "the approved contract."
            )
        ),
    )

require_no_blocking_failures(
    "Batch 2 identity and population normalization"
)


# ---------------------------------------------------------------------------
# Concise review views
# ---------------------------------------------------------------------------

MODEL_PROFILE = (
    CANDIDATE_INDEX
    .groupby(
        [
            "model_id",
            "population_role",
        ],
        dropna=False,
    )
    .agg(
        candidates=(
            "candidate_id",
            "size",
        ),
        cases=(
            "case_id",
            "nunique",
        ),
        paintings=(
            "painting_id",
            "nunique",
        ),
        manual_review_candidates=(
            "manual_review_required",
            "sum",
        ),
    )
    .reset_index()
)

BATCH_2_VALIDATION = (
    current_validation_frame()
    .loc[
        lambda frame: frame[
            "validation_stage"
        ].eq(BATCH_2_STAGE)
    ]
    .reset_index(drop=True)
)

display(MODEL_PROFILE)
display(EXPERIMENT_DIMENSION)
display(PAINTING_LOOKUP.head(10))

display(
    BATCH_2_VALIDATION[
        [
            "check_description",
            "severity",
            "passed",
            "observed",
        ]
    ]
)

print("Batch 2 Controlled-300 normalization passed.")
print("Registered cases:", len(CASE_INDEX))
print(
    "Four-method eligible cases:",
    int(
        CASE_INDEX[
            "four_method_eligible"
        ].sum()
    ),
)
print(
    "Inspectable candidates:",
    len(CANDIDATE_INDEX),
)
print("Paintings:", len(PAINTING_LOOKUP))
print("Reports:", len(REPORT_DIMENSION))
print("N12A candidates:", len(N12A_IDS))
print(
    "D01 candidates kept separate:",
    len(D01_CANDIDATES),
)
print(
    "D02 candidate-reference failures:",
    len(D02_MISSING_CANDIDATE_IDS),
)
print("Canonical files persisted by Batch 2: 0")

,model_id,population_role,candidates,cases,paintings,manual_review_candidates
0,hint_places2,primary_comparison,2620,2620,300,2354
1,lama,primary_comparison,2620,2620,300,2328
2,opencv_telea,primary_comparison,2620,2620,300,2437
3,sdxl_inpainting,bounded_sdxl,24,24,19,24
4,stable_diffusion_inpainting,primary_and_uncertainty,725,725,300,719
5,stable_diffusion_inpainting,primary_comparison,1895,1895,300,1895
6,stable_diffusion_inpainting,uncertainty_only,3375,725,300,3365

,experiment_id,registered_case_count,eligible_case_count,painting_count,inspected_case_count,candidate_count,model_count
0,canonical_missing_region,1500,1500,300,1500,8653,5
1,damage_size_sensitivity,245,245,35,245,1715,4
2,mask_robustness,525,525,35,525,2100,4
3,synthetic_degradation,1155,350,35,350,1411,5

,painting_id,dataset_sort_index,title,artist,date_or_period,style_or_period,category,medium,source,license,...,clean_image_path,metadata_completeness_pct,case_count,candidate_count,has_uncertainty,has_selected_case_report,painting_partition_path,schema_version,status,issue
0,p001,1,Juan de Pareja,Diego Velázquez,1650,Baroque,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,60,178,True,True,data/paintings/p001.json.gz,dashboard_painting_lookup.v1,ok,
1,p002,2,Madame X (Madame Pierre Gautreau),John Singer Sargent,1883-84,19th century portraiture,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,36,True,True,data/paintings/p002.json.gz,dashboard_painting_lookup.v1,ok,
2,p003,3,Marie Joséphine Charlotte du Val d'Ognes,Marie-Denise Villers,1801,Neoclassical / early 19th century,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,27,True,False,data/paintings/p003.json.gz,dashboard_painting_lookup.v1,ok,
3,p004,4,Madame Georges Charpentier and Her Children,Pierre-Auguste Renoir,1878,Impressionism,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,27,True,False,data/paintings/p004.json.gz,dashboard_painting_lookup.v1,ok,
4,p005,5,Self-Portrait with Two Pupils,Adélaïde Labille-Guiard,1785,18th century portraiture,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,27,True,False,data/paintings/p005.json.gz,dashboard_painting_lookup.v1,ok,
5,p006,6,Boy with a Sword,Édouard Manet,1861,Realism / early modern French painting,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,27,True,False,data/paintings/p006.json.gz,dashboard_painting_lookup.v1,ok,
6,p007,7,Princesse de Broglie,Jean-Auguste-Dominique Ingres,1851-53,Neoclassical,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,36,True,False,data/paintings/p007.json.gz,dashboard_painting_lookup.v1,ok,
7,p008,8,Manuel Osorio Manrique de Zuñiga,Francisco de Goya y Lucientes,1787-88,Spanish portraiture,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,27,True,False,data/paintings/p008.json.gz,dashboard_painting_lookup.v1,ok,
8,p009,9,Madame Roulin and Her Baby,Vincent van Gogh,1888,Post-Impressionism,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,60,176,True,True,data/paintings/p009.json.gz,dashboard_painting_lookup.v1,ok,
9,p010,10,Joan of Arc,Jules Bastien-Lepage,1879,19th century French painting,portrait_figure,Oil on canvas,The Metropolitan Museum of Art,Public Domain / Open Access,...,outputs/02_image_preprocessing/images/clean/p0...,100.0,5,27,True,False,data/paintings/p010.json.gz,dashboard_painting_lookup.v1,ok,

,check_description,severity,passed,observed
0,registered_cases,blocking,True,3425
1,four_method_eligible_cases,blocking,True,2620
2,inspectable_candidate_cases,blocking,True,2620
3,inspectable_candidates,blocking,True,13879
4,four_method_primary_candidates,blocking,True,10480
5,comparison_candidates,blocking,True,10504
6,producer_candidate_universe,blocking,True,17150
7,candidate_model_counts,blocking,True,"{""hint_places2"": 2620, ""lama"": 2620, ""opencv_t..."
8,candidate_role_counts,blocking,True,"{""bounded_sdxl"": 24, ""primary_and_uncertainty""..."
9,candidate_experiment_counts,blocking,True,"{""canonical_missing_region"": 8653, ""damage_siz..."
10,candidate_id_uniqueness,blocking,True,13879
11,candidate_identity_uniqueness,blocking,True,13879
12,producer_identity_mismatches,blocking,True,"{""case_id"": 0, ""missing_producer"": 0, ""model_i..."
13,registry_identity_mismatches,blocking,True,"{""experiment_id"": 0, ""painting_id"": 0}"
14,candidate_json_lists,blocking,True,[]
15,selected_producer_status,blocking,True,"[""completed""]"
16,candidate_availability,blocking,True,"{""available_local"": 13879}"
17,repeated_seed_groups,blocking,True,1025
18,repeated_seed_memberships,blocking,True,4100
19,repeated_seed_pairs,blocking,True,6150
20,painting_lookup_rows,blocking,True,300
21,painting_id_uniqueness,blocking,True,300
22,painting_category_distribution,blocking,True,"{""abstraction_surrealism"": 60, ""architecture_s..."
23,documented_styles,blocking,True,268
24,missing_styles,blocking,True,32
25,painting_reports,blocking,True,300
26,case_reports,blocking,True,30
27,model_reports,blocking,True,5
28,report_dimension,blocking,True,337
29,self_contained_reports,blocking,True,337
30,n12a_exact_hint_identity_set,blocking,True,"{""extra_in_n12a"": 0, ""missing_from_n12a"": 0}"
31,d01_scope_cases,blocking,True,12
32,d01_candidates,blocking,True,24
33,d01_main_candidate_collisions,blocking,True,[]
34,d02_missing_registry_cases,blocking,True,[]
35,d02_missing_main_candidates,blocking,True,[]
36,d02_scope,blocking,True,"{""annotations"": 91, ""blind_review_units"": 32, ..."
37,no_canonical_files_written,blocking,True,0

Batch 2 Controlled-300 normalization passed.
Registered cases: 3425
Four-method eligible cases: 2620
Inspectable candidates: 13879
Paintings: 300
Reports: 337
N12A candidates: 2620
D01 candidates kept separate: 24
D02 candidate-reference failures: 0
Canonical files persisted by Batch 2: 0

## Batch 3 — Zero-network bootstrap and room catalogue

This batch constructs the small local payload needed before a visitor enters a
room.

It creates, in memory:

- the eight principal rooms and the Focused Portrait Review child route;
- the approved plain-language opening and boundary for every room;
- seven Foyer destination previews and the guided-tour order;
- curated opening selections for the approved interface;
- a public glossary, model summaries and headline findings;
- the Controlled-300 population and publication overview; and
- local package references needed at application startup.

Startup remains fully local and performs zero network requests. Approved design
images are retained only as visual implementation references; they are never
treated as scientific evidence or runtime painting backgrounds.

No canonical package files are written by this batch. Atomic persistence occurs
only after the complete package passes its later validation gates.

In [11]:
def parse_json_object(
    value: object,
    label: str,
) -> dict:
    """Parse one required JSON object strictly."""

    if not isinstance(value, str) or not value.strip():
        raise ValueError(
            f"{label} must be a non-empty JSON object."
        )

    parsed = json.loads(value)

    if not isinstance(parsed, dict):
        raise TypeError(
            f"{label} must contain a JSON object."
        )

    return parsed


THESIS_TABLES = read_declared_csv(
    "thesis_tables_path",
    [
        "table_row_id",
        "table_id",
        "row_order",
        "row_key",
        "row_label",
        "values_json",
        "source_notebook_ids_json",
        "source_paths_json",
        "interpretation",
        "status",
    ],
)

FINAL_EVIDENCE_CATALOG = read_declared_csv(
    "final_evidence_catalog_path",
    [
        "catalog_id",
        "record_type",
        "section_id",
        "element_id",
        "approved_role",
        "implementation_status",
        "status",
    ],
)

EXTERNAL_PUBLICATION = read_declared_csv(
    "external_publication_registry_path",
    [
        "artifact_id",
        "publication_status",
        "verification_status",
    ],
)

CANONICAL_MASKS = read_declared_csv(
    "canonical_masks_path",
    [
        "case_id",
        "painting_id",
        "mask_type",
        "status",
    ],
)

CANONICAL_UNCERTAINTY = read_declared_csv(
    "canonical_uncertainty_path",
    [
        "uncertainty_group_id",
        "case_id",
        "painting_id",
        "seed_count",
        "status",
    ],
)

DAMAGE_SIZE_UNCERTAINTY_GROUPS = read_declared_csv(
    "damage_size_map_manifest_path",
    [
        "uncertainty_group_id",
        "case_id",
        "painting_id",
        "status",
    ],
)


ANCHOR_WINNERS = pd.DataFrame(
    [
        {
            "anchor_id": str(row.row_key),
            "winner_model_id": values[
                "winner_model_id"
            ],
            "majority_vote_winner_model_id": values[
                "majority_vote_winner_model_id"
            ],
            "agrees_with_majority_vote": bool(
                values[
                    "agrees_with_majority_vote"
                ]
            ),
            "loo_winner_stability_fraction": float(
                values[
                    "loo_winner_stability_fraction"
                ]
            ),
        }
        for row in THESIS_TABLES.loc[
            THESIS_TABLES["table_id"].eq(
                "t05_metric_disagreement"
            )
        ].itertuples(index=False)
        for values in [
            parse_json_object(
                row.values_json,
                row.table_row_id,
            )
        ]
    ]
)

WINNER_COUNTS = (
    ANCHOR_WINNERS["winner_model_id"]
    .value_counts()
    .sort_index()
    .astype(int)
    .to_dict()
)


RQ_ORDER = {
    "rq1": 1,
    "rq2": 2,
    "rq3": 3,
    "practical_output": 4,
}

RESEARCH_QUESTIONS = sorted(
    [
        {
            "question_id": values[
                "question_id"
            ],
            "display_order": RQ_ORDER[
                values["question_id"]
            ],
            "title": str(row.row_label),
            "evidence_status": values[
                "evidence_status"
            ],
            "interpretation": str(
                row.interpretation
            ),
            "source_notebook_ids": (
                parse_json_list(
                    row.source_notebook_ids_json
                )
            ),
            "source_paths": parse_json_list(
                row.source_paths_json
            ),
        }
        for row in THESIS_TABLES.loc[
            THESIS_TABLES["table_id"].eq(
                "t01_research_question_map"
            )
        ].itertuples(index=False)
        for values in [
            parse_json_object(
                row.values_json,
                row.table_row_id,
            )
        ]
    ],
    key=lambda record: record[
        "display_order"
    ],
)


FINAL_EVIDENCE_COUNTS = (
    FINAL_EVIDENCE_CATALOG["record_type"]
    .value_counts()
    .astype(int)
    .to_dict()
)

FINAL_FIGURE_COUNT = int(
    FINAL_EVIDENCE_COUNTS.get(
        "thesis_figure",
        0,
    )
    + FINAL_EVIDENCE_COUNTS.get(
        "publication_figure",
        0,
    )
)

CANONICAL_MASK_COUNTS = (
    CANONICAL_MASKS["mask_type"]
    .value_counts()
    .sort_index()
    .astype(int)
    .to_dict()
)

EXPERIMENT_CASE_COUNTS = (
    CASE_INDEX.groupby(
        "experiment_id"
    )["case_id"]
    .nunique()
    .sort_index()
    .astype(int)
    .to_dict()
)

ELIGIBLE_EXPERIMENT_CASE_COUNTS = (
    CASE_INDEX.loc[
        CASE_INDEX[
            "four_method_eligible"
        ]
    ]
    .groupby("experiment_id")["case_id"]
    .nunique()
    .sort_index()
    .astype(int)
    .to_dict()
)

UNCERTAINTY_COUNTS = {
    "canonical_groups": int(
        CANONICAL_UNCERTAINTY[
            "uncertainty_group_id"
        ].nunique()
    ),
    "damage_size_groups": int(
        DAMAGE_SIZE_UNCERTAINTY_GROUPS[
            "uncertainty_group_id"
        ].nunique()
    ),
}

UNCERTAINTY_COUNTS["total_groups"] = (
    UNCERTAINTY_COUNTS[
        "canonical_groups"
    ]
    + UNCERTAINTY_COUNTS[
        "damage_size_groups"
    ]
)


N33_MANIFEST = UPSTREAM_MANIFESTS["33"]

N33_VALIDATION_SUMMARY = dict(
    N33_MANIFEST["validation_summary"]
)

N33_LIMITATIONS = list(
    N33_MANIFEST["known_limitations"]
)


DASHBOARD_RELEASE_FINGERPRINT = {
    "dataset_id": SETTINGS[
        "dataset_id"
    ],
    "dataset_version": SETTINGS[
        "dataset_version"
    ],
    "dataset_scope": SETTINGS[
        "dataset_scope"
    ],
    "package_schema_version": SETTINGS[
        "dashboard_package_schema_version"
    ],
    "upstream_manifests": {
        logical_id: {
            "run_id": spec["run_id"],
            "sha256": spec["sha256"],
        }
        for logical_id, spec in sorted(
            MANIFEST_SPECS.items()
        )
    },
    "governing_contracts": {
        contract_id: spec["sha256"]
        for contract_id, spec in sorted(
            SETTINGS[
                "governing_contracts"
            ].items()
        )
    },
}

DASHBOARD_RELEASE_ID = stable_id(
    "release",
    DASHBOARD_RELEASE_FINGERPRINT,
)


print("Validated bootstrap source facts extracted.")
print("Release ID:", DASHBOARD_RELEASE_ID)
print("Quality-anchor winners:", WINNER_COUNTS)
print("Research-question records:", len(RESEARCH_QUESTIONS))
print("Canonical masks:", CANONICAL_MASK_COUNTS)
print("Experiment cases:", EXPERIMENT_CASE_COUNTS)
print("Uncertainty groups:", UNCERTAINTY_COUNTS)
print("Final evidence records:", FINAL_EVIDENCE_COUNTS)

Validated bootstrap source facts extracted.
Release ID: release_c5edf0d0ec99affbfa403726
Quality-anchor winners: {'lama': 10, 'opencv_telea': 1}
Research-question records: 4
Canonical masks: {'loss_large': 300, 'loss_small': 300, 'mixed_damage': 300, 'scratch_thin': 300, 'zero_control': 300}
Experiment cases: {'canonical_missing_region': 1500, 'damage_size_sensitivity': 245, 'mask_robustness': 525, 'synthetic_degradation': 1155}
Uncertainty groups: {'canonical_groups': 780, 'damage_size_groups': 245, 'total_groups': 1025}
Final evidence records: {'claim': 49, 'thesis_figure': 18, 'limitation': 18, 'table': 15, 'publication_figure': 6, 'report': 1}

In [12]:
PAGE_CONTRACT_PATH = SETTINGS[
    "governing_contracts"
]["page_contract"]["path"]


DESIGN_REFERENCE_PATHS = {
    "exhibition_foyer": (
        "docs/dashboard_design_finalists/"
        "approved_current/03_exhibition_foyer_final.png"
    ),
    "study_design": (
        "docs/dashboard_design_finalists/"
        "approved_current/04_study_design_final.png"
    ),
    "metric_framework": (
        "docs/dashboard_design_finalists/"
        "approved_current/05_metric_framework_final.png"
    ),
    "model_gallery": (
        "docs/dashboard_design_finalists/"
        "approved_current/06_model_gallery_final.png"
    ),
    "stability_lab": (
        "docs/dashboard_design_finalists/"
        "approved_current/07_stability_lab_final.png"
    ),
    "trustworthiness": (
        "docs/dashboard_design_finalists/"
        "approved_current/08_trustworthiness_final.png"
    ),
    "focused_portrait_review": (
        "docs/dashboard_design_finalists/"
        "approved_current/"
        "09_focused_portrait_review_final.png"
    ),
    "case_explorer": (
        "docs/dashboard_design_finalists/"
        "approved_current/10_case_explorer_final.png"
    ),
    "research_archive": (
        "docs/dashboard_design_finalists/"
        "approved_current/11_research_archive_final.png"
    ),
}


CURATED_OPENINGS = {
    "exhibition_foyer": {
        "painting_id": "p001",
    },
    "study_design": {
        "painting_id": "p001",
    },
    "metric_framework": {
        "painting_id": "p018",
        "case_id": (
            "canonical__p018__mixed_damage"
        ),
        "candidate_id": (
            "candidate__lama__canonical__"
            "p018__mixed_damage__c00"
        ),
        "model_id": "lama",
    },
    "model_gallery": {
        "painting_id": "p018",
        "case_id": (
            "canonical__p018__mixed_damage"
        ),
    },
    "stability_lab": {
        "painting_id": "p018",
        "case_id": (
            "damage_size__p018__loss_large__"
            "size_20pct"
        ),
        "candidate_id": (
            "candidate__lama__damage_size__"
            "p018__loss_large__size_20pct__c00"
        ),
        "model_id": "lama",
        "metric_id": "spatial_masked_error",
    },
    "trustworthiness": {
        "painting_id": "p002",
        "case_id": (
            "canonical__p002__loss_large"
        ),
        "candidate_id": (
            "sd15__p00__s2026__29ff258ff921"
        ),
        "model_id": (
            "stable_diffusion_inpainting"
        ),
        "seed": 2026,
    },
    "focused_portrait_review": {
        "painting_id": "p269",
        "case_id": (
            "canonical__p269__mixed_damage"
        ),
        "candidate_id": (
            "candidate__hint_places2__"
            "canonical__p269__mixed_damage__c00"
        ),
        "model_id": "hint_places2",
        "blind_review_code": "R005",
    },
    "case_explorer": {
        "painting_id": "p018",
        "case_id": (
            "canonical__p018__mixed_damage"
        ),
        "candidate_id": (
            "candidate__lama__canonical__"
            "p018__mixed_damage__c00"
        ),
        "model_id": "lama",
    },
    "research_archive": {
        "producer_notebook_id": "33",
        "record_label": "Final evaluation",
    },
}


ROOM_CONTENT = {
    "exhibition_foyer": {
        "question": (
            "How should we judge an AI-restored painting?"
        ),
        "purpose": (
            "Introduce the thesis and the eight-room "
            "evidence route."
        ),
        "introduction": (
            "This thesis tests digital restoration methods by "
            "applying controlled damage to 300 paintings. We "
            "compare the restored images, measure what changed "
            "and check whether the results stay consistent—but "
            "a convincing image is not automatically "
            "historically correct."
        ),
        "boundary": (
            "Visual plausibility is not the same as "
            "restoration trustworthiness."
        ),
        "partition_key": (
            "exhibition_foyer_path"
        ),
        "source_notebook_ids": [
            "01",
            "08",
            "29",
            "33",
        ],
    },
    "study_design": {
        "question": (
            "What did we test, and how did we keep the "
            "comparison fair?"
        ),
        "purpose": (
            "Explain the collection, experiment branches "
            "and equal-treatment rules."
        ),
        "introduction": (
            "We started with 300 paintings, divided evenly "
            "across five broad visual categories. Every "
            "painting received the same core tests, while "
            "smaller balanced experiments examined damage "
            "size, mask placement and other image changes."
        ),
        "boundary": (
            "Equal category sizes make comparisons easier. "
            "They do not make the collection representative "
            "of every artistic period, culture or style."
        ),
        "partition_key": "study_design_path",
        "source_notebook_ids": [
            "01",
            "03",
            "05",
            "06",
            "07",
            "08",
            "D02",
        ],
    },
    "metric_framework": {
        "question": (
            "Why can the conclusion change when the metric "
            "or region changes?"
        ),
        "purpose": (
            "Teach what each measurement asks and where "
            "it is valid."
        ),
        "introduction": (
            "No single number can judge a restoration. "
            "Different measurements examine pixels, structure, "
            "visual similarity, texture, colour, seams and "
            "unintended changes. Each measure is only "
            "meaningful in the regions it was designed "
            "to examine."
        ),
        "boundary": (
            "Different metrics answer different questions. "
            "Disagreement is evidence to inspect—not noise "
            "to average away."
        ),
        "partition_key": (
            "metric_framework_path"
        ),
        "source_notebook_ids": [
            "08",
            "13",
            "14",
            "15",
            "16",
            "17",
            "20",
            "21",
        ],
    },
    "model_gallery": {
        "question": (
            "How do different restoration methods rebuild "
            "the same loss?"
        ),
        "purpose": (
            "Compare the four full-scope methods without "
            "collapsing them into one score."
        ),
        "introduction": (
            "The four methods receive the same damaged "
            "painting and mask, but they rebuild the missing "
            "region in different ways. Compare the result, "
            "inspect the local evidence and then open the full "
            "model record when more detail is needed."
        ),
        "boundary": (
            "A convincing completion is a candidate to "
            "inspect—not recovered historical truth."
        ),
        "partition_key": "model_gallery_path",
        "source_notebook_ids": [
            "09",
            "10",
            "11",
            "12",
            "12A",
            "21",
            "30",
            "31",
        ],
    },
    "stability_lab": {
        "question": (
            "How much does a restoration change when we "
            "change the test?"
        ),
        "purpose": (
            "Keep damage size, mask placement, degradation "
            "stress and repeated seeds separate."
        ),
        "introduction": (
            "A restoration may look convincing once but "
            "behave differently when the damaged area grows, "
            "the mask moves, the input changes or Stable "
            "Diffusion uses another seed. Select one test and "
            "see what stays consistent."
        ),
        "boundary": (
            "Stable here means less change under this "
            "controlled test—not historically correct, safe "
            "to conserve or certain."
        ),
        "partition_key": "stability_lab_path",
        "source_notebook_ids": [
            "18",
            "22",
            "23",
            "24",
            "25",
        ],
    },
    "trustworthiness": {
        "question": (
            "Why did this restoration receive a review flag?"
        ),
        "purpose": (
            "Trace a review flag from evidence through its "
            "comparison group and threshold."
        ),
        "introduction": (
            "Flags help us decide what to inspect. They are "
            "not probabilities, expert verdicts, or proof "
            "that a restoration is right or wrong."
        ),
        "boundary": (
            "A review flag is not a probability, expert "
            "verdict, universal score or conservation approval."
        ),
        "partition_key": (
            "trustworthiness_path"
        ),
        "source_notebook_ids": [
            "27",
            "28",
            "29",
            "D02",
        ],
    },
    "focused_portrait_review": {
        "question": (
            "What did the focused portrait review find about "
            "hands and rendered lightness?"
        ),
        "purpose": (
            "Present the separate D02 hand-restoration and "
            "rendered-lightness investigations."
        ),
        "introduction": (
            "This focused audit reuses existing restoration "
            "results to examine damaged visible hands and "
            "associations with rendered lightness."
        ),
        "boundary": (
            "Rendered lightness is an image property, not "
            "race, ethnicity or identity; this focused study "
            "does not establish a general bias claim."
        ),
        "partition_key": (
            "focused_portrait_review_path"
        ),
        "source_notebook_ids": ["D02"],
    },
    "case_explorer": {
        "question": (
            "What evidence supports this restoration "
            "conclusion?"
        ),
        "purpose": (
            "Follow one saved candidate from controlled damage "
            "to metrics, warnings and reports."
        ),
        "introduction": (
            "Trace one restoration from controlled damage to "
            "measurements, warnings and source records."
        ),
        "boundary": (
            "Case evidence measures agreement with a controlled "
            "digital reference—not historical correctness or "
            "material authenticity."
        ),
        "partition_key": "case_explorer_path",
        "source_notebook_ids": [
            "16",
            "17",
            "19",
            "20",
            "27",
            "29",
            "32",
        ],
    },
    "research_archive": {
        "question": (
            "Trace every conclusion to its saved evidence."
        ),
        "purpose": (
            "Expose provenance, validation, publication "
            "status and reproducibility records."
        ),
        "introduction": (
            "The archive records what was used, what passed, "
            "what is missing and where each artifact lives."
        ),
        "boundary": (
            "A successful checksum confirms file identity, "
            "not scientific correctness."
        ),
        "partition_key": (
            "research_archive_path"
        ),
        "source_notebook_ids": [
            "01",
            "12A",
            "D01",
            "D02",
            "33",
        ],
    },
}


ROOM_CATALOGUE_ROWS = []

for room in ROOM_PLAN.itertuples(
    index=False
):
    room_id = str(room.room_id)
    content = ROOM_CONTENT[room_id]

    parent_room_id = nullable_scalar(
        room.parent_room_id
    )

    ROOM_CATALOGUE_ROWS.append(
        {
            "room_record_id": stable_id(
                "room",
                room_id,
            ),
            "room_id": room_id,
            "display_order": float(
                room.display_order
            ),
            "display_name": str(
                room.display_name
            ),
            "route_kind": str(
                room.route_kind
            ),
            "parent_room_id": (
                parent_room_id
            ),
            "tour_stop": (
                room.route_kind
                == "principal"
            ),
            "foyer_preview_available": (
                room.route_kind
                == "principal"
                and room_id
                != "exhibition_foyer"
            ),
            "question": content["question"],
            "purpose": content["purpose"],
            "introduction": content[
                "introduction"
            ],
            "boundary": content["boundary"],
            "loading_tier": "bootstrap",
            "partition_loading_tier": (
                "room_partition"
            ),
            "partition_path": SETTINGS[
                "output"
            ][content["partition_key"]],
            "opening_display_id": (
                f"{room_id}.opening"
            ),
            "opening_binding_state": (
                "pending_registered_rendition"
            ),
            "curated_opening": (
                CURATED_OPENINGS[room_id]
            ),
            "design_reference_path": (
                DESIGN_REFERENCE_PATHS[
                    room_id
                ]
            ),
            "design_reference_role": (
                "visual_only_not_runtime_evidence"
            ),
            "source_notebook_ids": content[
                "source_notebook_ids"
            ],
            "source_paths": [
                PAGE_CONTRACT_PATH
            ],
            "status": "ok",
            "issue": "",
        }
    )


ROOM_CATALOGUE_FRAME = pd.DataFrame(
    ROOM_CATALOGUE_ROWS
)

PRINCIPAL_ROOM_IDS = (
    ROOM_CATALOGUE_FRAME.loc[
        ROOM_CATALOGUE_FRAME[
            "route_kind"
        ].eq("principal"),
        "room_id",
    ].tolist()
)

CHILD_ROUTES = (
    ROOM_CATALOGUE_FRAME.loc[
        ROOM_CATALOGUE_FRAME[
            "route_kind"
        ].eq("child"),
        [
            "room_id",
            "parent_room_id",
        ],
    ].to_dict(orient="records")
)

FOYER_ROUTE_PREVIEWS = [
    {
        "room_id": row["room_id"],
        "display_name": row[
            "display_name"
        ],
        "question": row["question"],
        "summary": row[
            "introduction"
        ],
        "preview_display_id": (
            f"{row['room_id']}.route_preview"
        ),
        "binding_state": (
            "pending_registered_rendition"
        ),
    }
    for row in ROOM_CATALOGUE_ROWS
    if (
        row["route_kind"]
        == "principal"
        and row["room_id"]
        != "exhibition_foyer"
    )
]

ROOM_CATALOGUE = {
    "schema_version": SETTINGS[
        "expected_output_schemas"
    ]["room_catalogue"],
    "release_id": DASHBOARD_RELEASE_ID,
    "museum_name": (
        "Painting Restoration Evidence Museum"
    ),
    "principal_room_order": (
        PRINCIPAL_ROOM_IDS
    ),
    "child_routes": CHILD_ROUTES,
    "rooms": ROOM_CATALOGUE_ROWS,
    "status": "ok",
}


display(
    ROOM_CATALOGUE_FRAME[
        [
            "display_order",
            "display_name",
            "route_kind",
            "question",
            "partition_path",
        ]
    ]
)

print("Room catalogue constructed.")
print("Principal rooms:", len(PRINCIPAL_ROOM_IDS))
print("Child routes:", len(CHILD_ROUTES))
print("Foyer destination previews:", len(FOYER_ROUTE_PREVIEWS))

,display_order,display_name,route_kind,question,partition_path
0,1.0,Exhibition Foyer,principal,How should we judge an AI-restored painting?,data/rooms/exhibition_foyer.parquet
1,2.0,Study Design,principal,"What did we test, and how did we keep the comp...",data/rooms/study_design.parquet
2,3.0,Metric Framework,principal,Why can the conclusion change when the metric ...,data/rooms/metric_framework.parquet
3,4.0,Model Gallery,principal,How do different restoration methods rebuild t...,data/rooms/model_gallery.parquet
4,5.0,Stability Lab,principal,How much does a restoration change when we cha...,data/rooms/stability_lab.parquet
5,6.0,Trustworthiness,principal,Why did this restoration receive a review flag?,data/rooms/trustworthiness.parquet
6,6.1,Focused Portrait Review,child,What did the focused portrait review find abou...,data/rooms/focused_portrait_review.parquet
7,7.0,Case Explorer,principal,What evidence supports this restoration conclu...,data/rooms/case_explorer.parquet
8,8.0,Research Archive,principal,Trace every conclusion to its saved evidence.,data/rooms/research_archive.parquet

Room catalogue constructed.
Principal rooms: 8
Child routes: 1
Foyer destination previews: 7

In [13]:
def glossary_record(
    term_id: str,
    label: str,
    definition: str,
    boundary: str,
    source_notebook_ids: list[str],
) -> dict:
    """Construct one plain-language glossary entry."""

    return {
        "term_id": term_id,
        "label": label,
        "definition": definition,
        "boundary": boundary,
        "source_notebook_ids": (
            source_notebook_ids
        ),
        "source_paths": [
            MANIFEST_SPECS[
                notebook_id
            ]["path"]
            for notebook_id
            in source_notebook_ids
        ],
        "status": "ok",
        "issue": "",
    }


GLOSSARY_TERMS = [
    glossary_record(
        "clean_reference",
        "Clean reference",
        (
            "The standardized pre-damage digital image "
            "used for controlled comparison."
        ),
        (
            "It is not the unknowable historical original."
        ),
        ["02"],
    ),
    glossary_record(
        "broad_visual_category",
        "Broad visual category",
        (
            "One of five balanced study groupings based "
            "on visible content."
        ),
        (
            "It is not a historical style, period or "
            "claim of cultural representation."
        ),
        ["01"],
    ),
    glossary_record(
        "controlled_synthetic_damage",
        "Controlled synthetic damage",
        (
            "A repeatable digital mask or image change "
            "created for the experiment."
        ),
        (
            "It does not reproduce every property of "
            "physical deterioration."
        ),
        ["03", "04"],
    ),
    glossary_record(
        "registered_case",
        "Registered case",
        (
            "One exact painting and controlled condition "
            "stored in the experiment registry."
        ),
        (
            "Registration does not make the case eligible "
            "for every method."
        ),
        ["08"],
    ),
    glossary_record(
        "method_eligible_case",
        "Method-eligible case",
        (
            "A case all four full-scope methods were "
            "configured to process."
        ),
        (
            "Eligibility is computational, not "
            "conservation approval."
        ),
        ["08"],
    ),
    glossary_record(
        "unchanged_control",
        "Unchanged control",
        (
            "A zero-damage case used to check whether a "
            "method changes content unnecessarily."
        ),
        (
            "It is a technical control, not historical "
            "ground truth."
        ),
        ["03", "04"],
    ),
    glossary_record(
        "restoration_candidate",
        "Restoration candidate",
        (
            "One saved model output with an exact case "
            "and method identity."
        ),
        (
            "Candidate means available for inspection, "
            "not approved as correct."
        ),
        ["09", "10", "11", "12A"],
    ),
    glossary_record(
        "full_scope_method",
        "Full-scope method",
        (
            "A method evaluated across all 2,620 eligible "
            "cases."
        ),
        (
            "Full scope does not mean the method is "
            "universally suitable."
        ),
        ["08", "21"],
    ),
    glossary_record(
        "bounded_sdxl_branch",
        "Bounded SDXL branch",
        (
            "A limited feasibility run with 35 scheduled "
            "cases and 24 completed outputs."
        ),
        (
            "It is not a fifth full-scope comparison "
            "method."
        ),
        ["12"],
    ),
    glossary_record(
        "metric_family",
        "Metric family",
        (
            "A group of measurements asking a related "
            "question about restoration behaviour."
        ),
        (
            "Different metric families must not be merged "
            "into one universal score."
        ),
        ["08", "21"],
    ),
    glossary_record(
        "evaluation_region",
        "Evaluation region",
        (
            "The part of the image where a measurement "
            "is intended to be interpreted."
        ),
        (
            "A metric is defensible only in a compatible "
            "region."
        ),
        ["08"],
    ),
    glossary_record(
        "quality_anchor",
        "Quality anchor",
        (
            "One registered metric-and-region comparison "
            "used to compare methods."
        ),
        (
            "An anchor winner is not a universal best "
            "model."
        ),
        ["21"],
    ),
    glossary_record(
        "repeated_seed_group",
        "Repeated-seed group",
        (
            "Four Stable Diffusion candidates sharing the "
            "same case and prompt but using different seeds."
        ),
        (
            "Their disagreement measures empirical "
            "variation, not calibrated confidence."
        ),
        ["18", "22"],
    ),
    glossary_record(
        "empirical_uncertainty",
        "Empirical uncertainty",
        (
            "Observed variation among repeated supported "
            "Stable Diffusion outputs."
        ),
        (
            "It is not a probability that a restoration "
            "is correct."
        ),
        ["18", "22"],
    ),
    glossary_record(
        "threshold_reference_stratum",
        "Threshold reference stratum",
        (
            "The matched evidence population used to fit "
            "one warning or critical boundary."
        ),
        (
            "The fitted boundary is a review rule, not a "
            "failure probability."
        ),
        ["27"],
    ),
    glossary_record(
        "review_flag",
        "Review flag",
        (
            "A rule-based signal showing which evidence "
            "needs closer inspection."
        ),
        (
            "It is not an expert verdict, trust score or "
            "conservation decision."
        ),
        ["27"],
    ),
    glossary_record(
        "rendered_lightness",
        "Rendered lightness",
        (
            "A measured image-lightness property used in "
            "the focused portrait audit."
        ),
        (
            "It is not race, ethnicity or identity."
        ),
        ["D02"],
    ),
    glossary_record(
        "immutable_source",
        "Immutable source",
        (
            "A Git or Hugging Face object pinned by exact "
            "revision, size and checksum."
        ),
        (
            "A checksum confirms file identity, not "
            "scientific correctness."
        ),
        ["33"],
    ),
]


GLOSSARY = {
    "schema_version": SETTINGS[
        "expected_output_schemas"
    ]["glossary"],
    "release_id": DASHBOARD_RELEASE_ID,
    "terms": GLOSSARY_TERMS,
    "status": "ok",
}


MODEL_PUBLIC_COPY = {
    "opencv_telea": (
        "A fast classical method that fills a loss "
        "from nearby pixels."
    ),
    "lama": (
        "A learned deterministic method that uses "
        "broader image context."
    ),
    "hint_places2": (
        "A learned mask-aware transformer selected "
        "in the separate D01 study."
    ),
    "stable_diffusion_inpainting": (
        "A prompt-conditioned generative method whose "
        "output can change with seed and prompt."
    ),
    "sdxl_inpainting": (
        "A higher-capacity generative method evaluated "
        "only in a bounded feasibility branch."
    ),
}

MODEL_SUMMARIES = [
    {
        "model_id": row.model_id,
        "display_name": row.display_name,
        "evaluation_status": (
            row.evaluation_status
        ),
        "plain_description": (
            MODEL_PUBLIC_COPY[row.model_id]
        ),
        "deterministic": bool(
            row.deterministic
        ),
        "stochastic": bool(
            row.stochastic
        ),
        "prompt_dependent": bool(
            row.prompt_dependent
        ),
        "boundary": (
            "Bounded evidence; not a full-scope "
            "comparison method."
            if row.model_id
            == "sdxl_inpainting"
            else (
                "Full-scope computational method; "
                "not conservation approval."
            )
        ),
    }
    for row in MODEL_DIMENSION.itertuples(
        index=False
    )
]


SCOPE_INDICATORS = [
    {
        "indicator_id": "paintings",
        "value": 300,
        "label": "paintings",
        "explanation": (
            "60 in each broad visual category"
        ),
    },
    {
        "indicator_id": "visual_categories",
        "value": 5,
        "label": "broad visual categories",
        "explanation": (
            "study groupings, not historical styles"
        ),
    },
    {
        "indicator_id": "registered_cases",
        "value": 3425,
        "label": "registered experimental cases",
        "explanation": (
            "across all four experiment branches"
        ),
    },
    {
        "indicator_id": "methods",
        "value": 4,
        "label": "full-scope methods",
        "explanation": (
            "plus a separate bounded SDXL branch"
        ),
    },
]


HEADLINE_FINDINGS = [
    {
        "finding_id": "balanced_collection",
        "title": "Balanced controlled collection",
        "statement": (
            "The collection contains 300 paintings, "
            "with 60 in each of five broad visual "
            "categories."
        ),
        "limitation": (
            "This does not represent every artistic "
            "tradition, period or conservation condition."
        ),
        "source_notebook_ids": ["01"],
    },
    {
        "finding_id": "comparison_population",
        "title": "Matched four-method evidence",
        "statement": (
            "The four full-scope methods were compared "
            "on 2,620 eligible cases, producing 10,480 "
            "primary candidates."
        ),
        "limitation": (
            "Eligibility and metric performance do not "
            "establish historical correctness."
        ),
        "source_notebook_ids": [
            "08",
            "21",
        ],
    },
    {
        "finding_id": "metric_disagreement",
        "title": (
            "Different measurements can prefer "
            "different methods"
        ),
        "statement": (
            "LaMa led 10 of 11 separate quality anchors; "
            "Telea led crop SSIM."
        ),
        "limitation": (
            "No combined or universal quality score "
            "was created."
        ),
        "source_notebook_ids": [
            "21",
            "33",
        ],
    },
    {
        "finding_id": (
            "repeated_seed_evidence"
        ),
        "title": (
            "Repeated outputs reveal variation"
        ),
        "statement": (
            "Stable Diffusion has 1,025 supported "
            "four-seed groups covering 4,100 candidate "
            "memberships."
        ),
        "limitation": (
            "This is empirical variation, not "
            "calibrated confidence."
        ),
        "source_notebook_ids": [
            "18",
            "22",
        ],
    },
    {
        "finding_id": "review_flags",
        "title": (
            "Flags organize review rather than "
            "replace it"
        ),
        "statement": (
            "Operational thresholds point to evidence "
            "that deserves closer inspection."
        ),
        "limitation": (
            "A flag is not a probability, expert "
            "verdict or conservation decision."
        ),
        "source_notebook_ids": [
            "27",
            "28",
            "29",
        ],
    },
    {
        "finding_id": (
            "focused_portrait_audit"
        ),
        "title": (
            "The focused portrait audit remains separate"
        ),
        "statement": (
            "D02 found hands harder to restore in its "
            "matched audit, while rendered lightness did "
            "not show a consistent overall association."
        ),
        "limitation": (
            "Rendered lightness is not race or identity, "
            "and the audit does not establish demographic "
            "bias."
        ),
        "source_notebook_ids": ["D02"],
    },
]


BOOTSTRAP = {
    "schema_version": SETTINGS[
        "expected_output_schemas"
    ]["bootstrap"],
    "package_schema_version": SETTINGS[
        "dashboard_package_schema_version"
    ],
    "release_id": DASHBOARD_RELEASE_ID,
    "dataset": {
        "dataset_id": SETTINGS[
            "dataset_id"
        ],
        "dataset_version": SETTINGS[
            "dataset_version"
        ],
        "dataset_scope": SETTINGS[
            "dataset_scope"
        ],
    },
    "application": {
        "title": (
            "Painting Restoration Evidence Lab"
        ),
        "default_room_id": (
            "exhibition_foyer"
        ),
        "principal_room_count": 8,
        "child_route_count": 1,
        "creates_new_scientific_evidence": False,
    },
    "opening": {
        "question": ROOM_CONTENT[
            "exhibition_foyer"
        ]["question"],
        "text": ROOM_CONTENT[
            "exhibition_foyer"
        ]["introduction"],
        "boundary": ROOM_CONTENT[
            "exhibition_foyer"
        ]["boundary"],
        "painting_id": "p001",
        "display_id": (
            "exhibition_foyer.opening"
        ),
        "binding_state": (
            "pending_registered_rendition"
        ),
    },
    "principal_room_ids": (
        PRINCIPAL_ROOM_IDS
    ),
    "child_routes": CHILD_ROUTES,
    "route_previews": (
        FOYER_ROUTE_PREVIEWS
    ),
    "guided_tour": {
        "label": (
            "Take the guided tour · about 6 min"
        ),
        "room_ids": PRINCIPAL_ROOM_IDS,
        "optional_detour": {
            "room_id": (
                "focused_portrait_review"
            ),
            "offered_from": (
                "trustworthiness"
            ),
            "interrupts_principal_completion": False,
        },
        "skippable": True,
        "autoplay_video": False,
    },
    "scope_indicators": SCOPE_INDICATORS,
    "headline_findings": (
        HEADLINE_FINDINGS
    ),
    "research_questions": (
        RESEARCH_QUESTIONS
    ),
    "model_summaries": MODEL_SUMMARIES,
    "publication_overview": {
        "verified_individual_records": (
            POPULATION[
                "externally_published_individual_count"
            ]
        ),
        "verified_bundle_releases": (
            POPULATION[
                "verified_bundle_release_count"
            ]
        ),
        "painting_reports": (
            POPULATION[
                "painting_report_count"
            ]
        ),
        "selected_case_reports": (
            POPULATION[
                "selected_case_report_count"
            ]
        ),
        "model_reports": (
            POPULATION[
                "model_report_count"
            ]
        ),
        "final_reports": (
            POPULATION[
                "final_report_count"
            ]
        ),
        "n33_figures": FINAL_FIGURE_COUNT,
        "n33_claims": (
            FINAL_EVIDENCE_COUNTS.get(
                "claim",
                0,
            )
        ),
        "n33_limitations": (
            FINAL_EVIDENCE_COUNTS.get(
                "limitation",
                0,
            )
        ),
    },
    "resources": {
        "room_catalogue": SETTINGS[
            "output"
        ]["room_catalogue_path"],
        "glossary": SETTINGS[
            "output"
        ]["glossary_path"],
        "painting_lookup": SETTINGS[
            "output"
        ]["painting_lookup_path"],
        "filter_options": SETTINGS[
            "output"
        ]["filter_options_path"],
        "report_index": SETTINGS[
            "output"
        ]["report_index_path"],
    },
    "startup": {
        "loading_tier": "bootstrap",
        "network_requests": 0,
        "remote_fallback_allowed": False,
        "identity_substitution_allowed": False,
        "missing_asset_behaviour": (
            "show_explicit_unavailable_state"
        ),
    },
    "known_limitations": N33_LIMITATIONS,
    "prohibited_claims": SETTINGS[
        "validation"
    ]["prohibited_claims"],
    "status": "ok",
}


BOOTSTRAP_COMPONENT_BYTES = {
    "bootstrap.json": len(
        canonical_json_bytes(
            BOOTSTRAP
        )
    ),
    "room_catalogue.json": len(
        canonical_json_bytes(
            ROOM_CATALOGUE
        )
    ),
    "glossary.json": len(
        canonical_json_bytes(
            GLOSSARY
        )
    ),
    "filter_options.json": len(
        canonical_json_bytes(
            FILTER_OPTIONS
        )
    ),
}

BOOTSTRAP_JSON_BYTES = sum(
    BOOTSTRAP_COMPONENT_BYTES.values()
)

BOOTSTRAP_DATAFRAME_MEMORY_BYTES = int(
    PAINTING_LOOKUP.memory_usage(
        index=True,
        deep=True,
    ).sum()
    + MODEL_DIMENSION.memory_usage(
        index=True,
        deep=True,
    ).sum()
    + EXPERIMENT_DIMENSION.memory_usage(
        index=True,
        deep=True,
    ).sum()
    + REPORT_DIMENSION.memory_usage(
        index=True,
        deep=True,
    ).sum()
)


def payload_strings(value):
    """Yield strings from a nested payload."""

    if isinstance(value, dict):
        for key, child in value.items():
            yield str(key)
            yield from payload_strings(child)

    elif isinstance(value, (list, tuple)):
        for child in value:
            yield from payload_strings(child)

    elif isinstance(value, str):
        yield value


BOOTSTRAP_NETWORK_REFERENCES = sorted(
    {
        value
        for value in payload_strings(
            {
                "bootstrap": BOOTSTRAP,
                "glossary": GLOSSARY,
            }
        )
        if (
            "://" in value
            or value.startswith("//")
        )
    }
)


display(
    pd.DataFrame(
        SCOPE_INDICATORS
    )
)

display(
    pd.DataFrame(
        HEADLINE_FINDINGS
    )[
        [
            "title",
            "statement",
            "limitation",
        ]
    ]
)

display(
    pd.DataFrame(
        GLOSSARY_TERMS
    )[
        [
            "label",
            "definition",
            "boundary",
        ]
    ]
)

print("Zero-network bootstrap constructed.")
print("Glossary terms:", len(GLOSSARY_TERMS))
print(
    "Bootstrap components:",
    BOOTSTRAP_COMPONENT_BYTES,
)
print(
    "Bootstrap JSON bytes:",
    BOOTSTRAP_JSON_BYTES,
)
print(
    "Bootstrap dataframe memory:",
    BOOTSTRAP_DATAFRAME_MEMORY_BYTES,
)
print(
    "Network references:",
    BOOTSTRAP_NETWORK_REFERENCES,
)

,indicator_id,value,label,explanation
0,paintings,300,paintings,60 in each broad visual category
1,visual_categories,5,broad visual categories,"study groupings, not historical styles"
2,registered_cases,3425,registered experimental cases,across all four experiment branches
3,methods,4,full-scope methods,plus a separate bounded SDXL branch

,title,statement,limitation
0,Balanced controlled collection,"The collection contains 300 paintings, with 60...",This does not represent every artistic traditi...
1,Matched four-method evidence,The four full-scope methods were compared on 2...,Eligibility and metric performance do not esta...
2,Different measurements can prefer different me...,LaMa led 10 of 11 separate quality anchors; Te...,No combined or universal quality score was cre...
3,Repeated outputs reveal variation,"Stable Diffusion has 1,025 supported four-seed...","This is empirical variation, not calibrated co..."
4,Flags organize review rather than replace it,Operational thresholds point to evidence that ...,"A flag is not a probability, expert verdict or..."
5,The focused portrait audit remains separate,D02 found hands harder to restore in its match...,"Rendered lightness is not race or identity, an..."

,label,definition,boundary
0,Clean reference,The standardized pre-damage digital image used...,It is not the unknowable historical original.
1,Broad visual category,One of five balanced study groupings based on ...,"It is not a historical style, period or claim ..."
2,Controlled synthetic damage,A repeatable digital mask or image change crea...,It does not reproduce every property of physic...
3,Registered case,One exact painting and controlled condition st...,Registration does not make the case eligible f...
4,Method-eligible case,A case all four full-scope methods were config...,"Eligibility is computational, not conservation..."
5,Unchanged control,A zero-damage case used to check whether a met...,"It is a technical control, not historical grou..."
6,Restoration candidate,One saved model output with an exact case and ...,"Candidate means available for inspection, not ..."
7,Full-scope method,"A method evaluated across all 2,620 eligible c...",Full scope does not mean the method is univers...
8,Bounded SDXL branch,A limited feasibility run with 35 scheduled ca...,It is not a fifth full-scope comparison method.
9,Metric family,A group of measurements asking a related quest...,Different metric families must not be merged i...
10,Evaluation region,The part of the image where a measurement is i...,A metric is defensible only in a compatible re...
11,Quality anchor,One registered metric-and-region comparison us...,An anchor winner is not a universal best model.
12,Repeated-seed group,Four Stable Diffusion candidates sharing the s...,Their disagreement measures empirical variatio...
13,Empirical uncertainty,Observed variation among repeated supported St...,It is not a probability that a restoration is ...
14,Threshold reference stratum,The matched evidence population used to fit on...,"The fitted boundary is a review rule, not a fa..."
15,Review flag,A rule-based signal showing which evidence nee...,"It is not an expert verdict, trust score or co..."
16,Rendered lightness,A measured image-lightness property used in th...,"It is not race, ethnicity or identity."
17,Immutable source,A Git or Hugging Face object pinned by exact r...,"A checksum confirms file identity, not scienti..."

Zero-network bootstrap constructed.
Glossary terms: 18
Bootstrap components: {'bootstrap.json': 12463, 'room_catalogue.json': 12857, 'glossary.json': 7398, 'filter_options.json': 9646}
Bootstrap JSON bytes: 42364
Bootstrap dataframe memory: 500982
Network references: []

In [14]:
BATCH_3_STAGE = (
    "batch_3_zero_network_bootstrap"
)

VALIDATION_ROWS[:] = [
    row
    for row in VALIDATION_ROWS
    if row["validation_stage"]
    != BATCH_3_STAGE
]


EXPECTED_EXPERIMENT_COUNTS = {
    "canonical_missing_region": 1500,
    "damage_size_sensitivity": 245,
    "mask_robustness": 525,
    "synthetic_degradation": 1155,
}

EXPECTED_ELIGIBLE_EXPERIMENT_COUNTS = {
    "canonical_missing_region": 1500,
    "damage_size_sensitivity": 245,
    "mask_robustness": 525,
    "synthetic_degradation": 350,
}

EXPECTED_MASK_COUNTS = {
    "loss_large": 300,
    "loss_small": 300,
    "mixed_damage": 300,
    "scratch_thin": 300,
    "zero_control": 300,
}

EXPECTED_CATALOG_COUNTS = {
    "claim": 49,
    "limitation": 18,
    "publication_figure": 6,
    "report": 1,
    "table": 15,
    "thesis_figure": 18,
}

EXPECTED_PRINCIPAL_ORDER = [
    "exhibition_foyer",
    "study_design",
    "metric_framework",
    "model_gallery",
    "stability_lab",
    "trustworthiness",
    "case_explorer",
    "research_archive",
]

EXPECTED_CHILD_ROUTES = [
    {
        "room_id": (
            "focused_portrait_review"
        ),
        "parent_room_id": (
            "trustworthiness"
        ),
    }
]

DESIGN_REFERENCE_ERRORS = sorted(
    path
    for path in DESIGN_REFERENCE_PATHS.values()
    if (
        not is_repo_relative(path)
        or not (
            PROJECT_ROOT / path
        ).is_file()
    )
)

ROOM_TEXT_ERRORS = sorted(
    record["room_id"]
    for record in ROOM_CATALOGUE_ROWS
    if not all(
        str(record[field]).strip()
        for field in (
            "question",
            "purpose",
            "introduction",
            "boundary",
        )
    )
)

CURATED_DEFAULT_MATCH_COUNTS = {
    "foyer_painting": int(
        PAINTING_LOOKUP[
            "painting_id"
        ].eq("p001").sum()
    ),
    "metric_candidate": int(
        CANDIDATE_INDEX[
            "candidate_id"
        ].eq(
            "candidate__lama__canonical__"
            "p018__mixed_damage__c00"
        ).sum()
    ),
    "stability_candidate": int(
        CANDIDATE_INDEX[
            "candidate_id"
        ].eq(
            "candidate__lama__damage_size__"
            "p018__loss_large__size_20pct__c00"
        ).sum()
    ),
    "trust_candidate": int(
        CANDIDATE_INDEX[
            "candidate_id"
        ].eq(
            "sd15__p00__s2026__29ff258ff921"
        ).sum()
    ),
    "portrait_review": int(
        D02_MANUAL[
            "blind_review_code"
        ].eq("R005").sum()
    ),
    "case_explorer_candidate": int(
        CANDIDATE_INDEX[
            "candidate_id"
        ].eq(
            "candidate__lama__canonical__"
            "p018__mixed_damage__c00"
        ).sum()
    ),
    "archive_final_report": int(
        REPORT_DIMENSION[
            "report_type"
        ].eq("final").sum()
    ),
}

EXPECTED_CURATED_MATCH_COUNTS = {
    key: 1
    for key in (
        CURATED_DEFAULT_MATCH_COUNTS
    )
}

REBUILT_RELEASE_ID = stable_id(
    "release",
    DASHBOARD_RELEASE_FINGERPRINT,
)

CURRENT_OUTPUT_FILE_COUNT = (
    sum(
        path.is_file()
        for path in OUTPUT_ROOT.rglob("*")
    )
    if OUTPUT_ROOT.exists()
    else 0
)


BATCH_3_CHECKS = [
    (
        "release_id_determinism",
        REBUILT_RELEASE_ID,
        DASHBOARD_RELEASE_ID,
    ),
    (
        "principal_room_order",
        PRINCIPAL_ROOM_IDS,
        EXPECTED_PRINCIPAL_ORDER,
    ),
    (
        "room_record_count",
        len(ROOM_CATALOGUE_ROWS),
        9,
    ),
    (
        "child_route_relationship",
        CHILD_ROUTES,
        EXPECTED_CHILD_ROUTES,
    ),
    (
        "tour_stop_count",
        sum(
            record["tour_stop"]
            for record in ROOM_CATALOGUE_ROWS
        ),
        8,
    ),
    (
        "foyer_route_preview_count",
        len(FOYER_ROUTE_PREVIEWS),
        7,
    ),
    (
        "room_text_completeness",
        ROOM_TEXT_ERRORS,
        [],
    ),
    (
        "room_partition_paths",
        all(
            is_repo_relative(
                record["partition_path"]
            )
            for record
            in ROOM_CATALOGUE_ROWS
        ),
        True,
    ),
    (
        "design_reference_files",
        DESIGN_REFERENCE_ERRORS,
        [],
    ),
    (
        "design_reference_roles",
        {
            record[
                "design_reference_role"
            ]
            for record
            in ROOM_CATALOGUE_ROWS
        },
        {
            "visual_only_not_runtime_evidence"
        },
    ),
    (
        "curated_opening_resolution",
        CURATED_DEFAULT_MATCH_COUNTS,
        EXPECTED_CURATED_MATCH_COUNTS,
    ),
    (
        "glossary_term_count",
        len(GLOSSARY_TERMS),
        18,
    ),
    (
        "glossary_id_uniqueness",
        len(
            {
                record["term_id"]
                for record
                in GLOSSARY_TERMS
            }
        ),
        18,
    ),
    (
        "glossary_label_uniqueness",
        len(
            {
                record["label"]
                for record
                in GLOSSARY_TERMS
            }
        ),
        18,
    ),
    (
        "research_question_count",
        len(RESEARCH_QUESTIONS),
        4,
    ),
    (
        "model_summary_count",
        len(MODEL_SUMMARIES),
        5,
    ),
    (
        "full_scope_model_count",
        sum(
            record[
                "evaluation_status"
            ]
            == "fully_evaluated"
            for record
            in MODEL_SUMMARIES
        ),
        4,
    ),
    (
        "scope_indicators",
        {
            record["indicator_id"]:
            record["value"]
            for record in SCOPE_INDICATORS
        },
        {
            "paintings": 300,
            "visual_categories": 5,
            "registered_cases": 3425,
            "methods": 4,
        },
    ),
    (
        "headline_finding_count",
        len(HEADLINE_FINDINGS),
        6,
    ),
    (
        "quality_anchor_population",
        len(ANCHOR_WINNERS),
        11,
    ),
    (
        "quality_anchor_winners",
        WINNER_COUNTS,
        {
            "lama": 10,
            "opencv_telea": 1,
        },
    ),
    (
        "canonical_mask_counts",
        CANONICAL_MASK_COUNTS,
        EXPECTED_MASK_COUNTS,
    ),
    (
        "experiment_case_counts",
        EXPERIMENT_CASE_COUNTS,
        EXPECTED_EXPERIMENT_COUNTS,
    ),
    (
        "eligible_experiment_counts",
        ELIGIBLE_EXPERIMENT_CASE_COUNTS,
        EXPECTED_ELIGIBLE_EXPERIMENT_COUNTS,
    ),
    (
        "uncertainty_groups",
        UNCERTAINTY_COUNTS,
        {
            "canonical_groups": 780,
            "damage_size_groups": 245,
            "total_groups": 1025,
        },
    ),
    (
        "final_evidence_catalog",
        FINAL_EVIDENCE_COUNTS,
        EXPECTED_CATALOG_COUNTS,
    ),
    (
        "final_figure_count",
        FINAL_FIGURE_COUNT,
        24,
    ),
    (
        "external_publication_verified",
        int(
            EXTERNAL_PUBLICATION[
                "verification_status"
            ].eq("verified").sum()
        ),
        POPULATION[
            "externally_published_individual_count"
        ],
    ),
    (
        "n33_validation",
        N33_VALIDATION_SUMMARY,
        {
            "check_count": 536,
            "passed_count": 536,
            "failed_count": 0,
            "blocking_failure_count": 0,
            "overall_passed": True,
            "failed_check_ids": [],
        },
    ),
    (
        "bootstrap_schema",
        BOOTSTRAP["schema_version"],
        SETTINGS[
            "expected_output_schemas"
        ]["bootstrap"],
    ),
    (
        "room_catalogue_schema",
        ROOM_CATALOGUE[
            "schema_version"
        ],
        SETTINGS[
            "expected_output_schemas"
        ]["room_catalogue"],
    ),
    (
        "glossary_schema",
        GLOSSARY["schema_version"],
        SETTINGS[
            "expected_output_schemas"
        ]["glossary"],
    ),
    (
        "startup_network_requests",
        BOOTSTRAP[
            "startup"
        ]["network_requests"],
        0,
    ),
    (
        "network_references_absent",
        BOOTSTRAP_NETWORK_REFERENCES,
        [],
    ),
    (
        "bootstrap_target_budget",
        (
            BOOTSTRAP_JSON_BYTES
            <= SETTINGS[
                "runtime_budgets"
            ]["bootstrap_target_bytes"]
        ),
        True,
    ),
    (
        "bootstrap_hard_budget",
        (
            BOOTSTRAP_JSON_BYTES
            <= SETTINGS[
                "runtime_budgets"
            ]["bootstrap_hard_bytes"]
        ),
        True,
    ),
    (
        "bootstrap_dataframe_memory",
        (
            BOOTSTRAP_DATAFRAME_MEMORY_BYTES
            <= SETTINGS[
                "runtime_budgets"
            ][
                "bootstrap_dataframe_memory_hard_bytes"
            ]
        ),
        True,
    ),
    (
        "no_canonical_files_written",
        CURRENT_OUTPUT_FILE_COUNT,
        0,
    ),
]


for (
    check_name,
    observed,
    expected,
) in BATCH_3_CHECKS:
    passed = observed == expected

    add_check(
        BATCH_3_STAGE,
        check_name,
        observed,
        expected,
        passed,
        (
            ""
            if passed
            else (
                "Batch 3 differs from the approved "
                "zero-network bootstrap contract."
            )
        ),
    )


require_no_blocking_failures(
    "Batch 3 zero-network bootstrap"
)

BATCH_3_VALIDATION = (
    current_validation_frame()
    .loc[
        lambda frame: frame[
            "validation_stage"
        ].eq(BATCH_3_STAGE)
    ]
    .reset_index(drop=True)
)


display(
    BATCH_3_VALIDATION[
        [
            "check_description",
            "severity",
            "passed",
            "observed",
        ]
    ]
)

print("Batch 3 zero-network bootstrap passed.")
print("Release ID:", DASHBOARD_RELEASE_ID)
print("Principal rooms:", len(PRINCIPAL_ROOM_IDS))
print("Child routes:", len(CHILD_ROUTES))
print(
    "Foyer route previews:",
    len(FOYER_ROUTE_PREVIEWS),
)
print("Glossary terms:", len(GLOSSARY_TERMS))
print(
    "Bootstrap JSON bytes:",
    BOOTSTRAP_JSON_BYTES,
)
print(
    "Bootstrap dataframe memory:",
    BOOTSTRAP_DATAFRAME_MEMORY_BYTES,
)
print("Startup network requests: 0")
print(
    "Canonical files persisted by Batch 3:",
    CURRENT_OUTPUT_FILE_COUNT,
)

,check_description,severity,passed,observed
0,release_id_determinism,blocking,True,release_c5edf0d0ec99affbfa403726
1,principal_room_order,blocking,True,"[""exhibition_foyer"", ""study_design"", ""metric_f..."
2,room_record_count,blocking,True,9
3,child_route_relationship,blocking,True,"[{""parent_room_id"": ""trustworthiness"", ""room_i..."
4,tour_stop_count,blocking,True,8
5,foyer_route_preview_count,blocking,True,7
6,room_text_completeness,blocking,True,[]
7,room_partition_paths,blocking,True,True
8,design_reference_files,blocking,True,[]
9,design_reference_roles,blocking,True,"""{'visual_only_not_runtime_evidence'}"""
10,curated_opening_resolution,blocking,True,"{""archive_final_report"": 1, ""case_explorer_can..."
11,glossary_term_count,blocking,True,18
12,glossary_id_uniqueness,blocking,True,18
13,glossary_label_uniqueness,blocking,True,18
14,research_question_count,blocking,True,4
15,model_summary_count,blocking,True,5
16,full_scope_model_count,blocking,True,4
17,scope_indicators,blocking,True,"{""methods"": 4, ""paintings"": 300, ""registered_c..."
18,headline_finding_count,blocking,True,6
19,quality_anchor_population,blocking,True,11
20,quality_anchor_winners,blocking,True,"{""lama"": 10, ""opencv_telea"": 1}"
21,canonical_mask_counts,blocking,True,"{""loss_large"": 300, ""loss_small"": 300, ""mixed_..."
22,experiment_case_counts,blocking,True,"{""canonical_missing_region"": 1500, ""damage_siz..."
23,eligible_experiment_counts,blocking,True,"{""canonical_missing_region"": 1500, ""damage_siz..."
24,uncertainty_groups,blocking,True,"{""canonical_groups"": 780, ""damage_size_groups""..."
25,final_evidence_catalog,blocking,True,"{""claim"": 49, ""limitation"": 18, ""publication_f..."
26,final_figure_count,blocking,True,24
27,external_publication_verified,blocking,True,2653
28,n33_validation,blocking,True,"{""blocking_failure_count"": 0, ""check_count"": 5..."
29,bootstrap_schema,blocking,True,dashboard_bootstrap.v1
30,room_catalogue_schema,blocking,True,dashboard_room_catalogue.v1
31,glossary_schema,blocking,True,dashboard_glossary.v1
32,startup_network_requests,blocking,True,0
33,network_references_absent,blocking,True,[]
34,bootstrap_target_budget,blocking,True,True
35,bootstrap_hard_budget,blocking,True,True
36,bootstrap_dataframe_memory,blocking,True,True
37,no_canonical_files_written,blocking,True,0

Batch 3 zero-network bootstrap passed.
Release ID: release_c5edf0d0ec99affbfa403726
Principal rooms: 8
Child routes: 1
Foyer route previews: 7
Glossary terms: 18
Bootstrap JSON bytes: 42364
Bootstrap dataframe memory: 500982
Startup network requests: 0
Canonical files persisted by Batch 3: 0

## Batch 4 — Selectors and 300 painting partitions

This batch constructs the dashboard's searchable navigation layer.

It creates:

- lightweight selector availability for every painting;
- exact case, candidate, report and focused-audit routes;
- one deterministic compressed partition for each of the 300 paintings;
- the completed painting lookup and filter-options payloads; and
- checksum and size records for every staged painting partition.

Painting partitions contain identity, selector and route metadata only. They
reference exact images and reports but never duplicate image bytes.

All files are written only to the declared temporary work package. Nothing is
promoted into the canonical N34 output package until the final completion gate.
The batch performs no network requests and remains safe to rerun.

In [15]:
import gzip
import hashlib
import io

from restoration_eval.dashboard_assets import (
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_parquet,
)


BATCH_4_STAGE = (
    "batch_4_selectors_and_painting_shards"
)


def json_safe(value):
    """Convert pandas and NumPy values into deterministic JSON values."""

    if isinstance(value, dict):
        return {
            str(key): json_safe(child)
            for key, child in value.items()
        }

    if isinstance(value, set):
        return [
            json_safe(child)
            for child in sorted(
                value,
                key=str,
            )
        ]

    if isinstance(value, (list, tuple)):
        return [
            json_safe(child)
            for child in value
        ]

    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass

    if hasattr(value, "item"):
        try:
            return value.item()
        except (TypeError, ValueError):
            pass

    return value


def deterministic_gzip_bytes(
    payload: object,
) -> dict:
    """Encode one payload using deterministic gzip metadata."""

    decoded = canonical_json_bytes(payload)

    buffer = io.BytesIO()

    with gzip.GzipFile(
        filename="",
        mode="wb",
        fileobj=buffer,
        mtime=0,
    ) as handle:
        handle.write(decoded)

    compressed = buffer.getvalue()

    return {
        "bytes": compressed,
        "decoded_size_bytes": len(decoded),
        "decoded_sha256": hashlib.sha256(
            decoded
        ).hexdigest(),
        "compressed_size_bytes": len(
            compressed
        ),
        "compressed_sha256": hashlib.sha256(
            compressed
        ).hexdigest(),
    }


def sorted_unique(
    frame: pd.DataFrame,
    column: str,
    *,
    integers: bool = False,
) -> list:
    """Return one stable selector vocabulary."""

    if column not in frame:
        return []

    values = (
        frame[column]
        .dropna()
        .unique()
        .tolist()
    )

    if integers:
        return sorted(
            int(value)
            for value in values
        )

    return sorted(
        str(value)
        for value in values
    )


CASE_GROUPS = {
    painting_id: group.copy()
    for painting_id, group in CASE_INDEX.groupby(
        "painting_id",
        sort=False,
    )
}

CANDIDATE_GROUPS = {
    painting_id: group.copy()
    for painting_id, group
    in CANDIDATE_INDEX.groupby(
        "painting_id",
        sort=False,
    )
}

CASE_REPORT_GROUPS = {
    painting_id: group.copy()
    for painting_id, group
    in CASE_REPORT_INDEX.groupby(
        "painting_id",
        sort=False,
    )
}

PAINTING_REPORT_LOOKUP = (
    PAINTING_REPORT_INDEX.set_index(
        "painting_id",
        verify_integrity=True,
    )
)

D02_SCREENING_LOOKUP = (
    D02_SCREENING.set_index(
        "painting_id",
        verify_integrity=True,
    )
)

D02_ANNOTATION_COUNTS = (
    D02_ANNOTATIONS.groupby(
        "painting_id"
    )["annotation_id"].nunique()
)

D02_ELIGIBLE_COUNTS = (
    D02_ELIGIBLE.groupby(
        "painting_id"
    )["case_id"].nunique()
)

D02_REVIEW_COUNTS = (
    D02_MANUAL.groupby(
        "painting_id"
    )["review_unit_id"].nunique()
)


print("Batch 4 bounded source groups prepared.")
print("Case groups:", len(CASE_GROUPS))
print("Candidate groups:", len(CANDIDATE_GROUPS))
print(
    "Painting-report records:",
    len(PAINTING_REPORT_LOOKUP),
)
print(
    "D02-screened paintings:",
    len(D02_SCREENING_LOOKUP),
)

Batch 4 bounded source groups prepared.
Case groups: 300
Candidate groups: 300
Painting-report records: 300
D02-screened paintings: 60

In [16]:
def case_route(row) -> dict:
    """Construct one case route without copying image bytes."""

    return {
        "case_id": row.case_id,
        "experiment_id": row.experiment_id,
        "mask_or_effect_id": (
            row.mask_or_effect_id
        ),
        "damage_or_degradation_type": (
            row.damage_or_degradation_type
        ),
        "target_damage_fraction": json_safe(
            row.target_damage_fraction
        ),
        "realized_damage_fraction": json_safe(
            row.realized_damage_fraction
        ),
        "four_method_eligible": bool(
            row.four_method_eligible
        ),
        "input_image_path": (
            row.input_image_path
        ),
        "clean_image_path": (
            row.clean_image_path
        ),
        "mask_or_effect_path": (
            row.mask_or_effect_path
        ),
    }


def candidate_route(row) -> dict:
    """Construct one candidate and evidence route."""

    return {
        "candidate_id": row.candidate_id,
        "candidate_record_id": (
            row.candidate_record_id
        ),
        "case_id": row.case_id,
        "model_id": row.model_id,
        "experiment_id": row.experiment_id,
        "seed": (
            None
            if pd.isna(row.seed)
            else int(row.seed)
        ),
        "prompt_variant_id": (
            nullable_scalar(
                row.prompt_variant_id
            )
        ),
        "uncertainty_group_id": (
            nullable_scalar(
                row.uncertainty_group_id
            )
        ),
        "population_role": (
            row.population_role
        ),
        "restored_sha256": (
            row.producer_restored_sha256
        ),
        "recommendation_category": (
            row.recommendation_category
        ),
        "manual_review_required": bool(
            row.manual_review_required
        ),
        "report_selected": bool(
            row.report_selected
        ),
        "retrieval_dino_eligible": bool(
            row.retrieval_dino_eligible
        ),
        "retrieval_clip_eligible": bool(
            row.retrieval_clip_eligible
        ),
        "retrieval_lane": nullable_scalar(
            row.retrieval_lane
        ),
        "evidence_layers": parse_json_list(
            row.asset_availability_json
        ),
        "asset_routes": {
            "restored": [
                row.restored_path
            ],
            "difference": parse_json_list(
                row.difference_paths_json
            ),
            "uncertainty": parse_json_list(
                row.uncertainty_paths_json
            ),
            "seam": parse_json_list(
                row.seam_paths_json
            ),
            "colour": parse_json_list(
                row.colour_paths_json
            ),
            "texture": parse_json_list(
                row.texture_paths_json
            ),
            "semantic": parse_json_list(
                row.semantic_paths_json
            ),
            "mask_boundary": parse_json_list(
                row.mask_boundary_paths_json
            ),
        },
        "triggered_flag_ids": parse_json_list(
            row.triggered_flag_ids_json
        ),
        "insufficient_flag_ids": (
            parse_json_list(
                row.insufficient_flag_ids_json
            )
        ),
        "triggered_category_ids": (
            parse_json_list(
                row.triggered_category_ids_json
            )
        ),
        "triggering_evidence_ids": (
            parse_json_list(
                row.triggering_evidence_ids_json
            )
        ),
        "affected_regions": parse_json_list(
            row.affected_regions_json
        ),
        "recommended_actions": (
            parse_json_list(
                row.recommended_actions_json
            )
        ),
        "metric_disagreement_ids": (
            parse_json_list(
                row.metric_disagreement_ids_json
            )
        ),
        "counterfactual_panel_ids": (
            parse_json_list(
                row.counterfactual_panel_ids_json
            )
        ),
        "source_notebook_ids": (
            parse_json_list(
                row.evidence_source_notebook_ids_json
            )
        ),
        "availability_state": (
            row.availability_state
        ),
    }


print("Exact case and candidate route constructors prepared.")
print("No image bytes have been read.")

Exact case and candidate route constructors prepared.
No image bytes have been read.

In [17]:
PAINTING_SELECTOR_ROWS = []
PAINTING_SHARD_PAYLOADS = {}
PAINTING_SHARD_BYTES = {}
PAINTING_SHARD_LEDGER_ROWS = []


for painting in (
    PAINTING_LOOKUP
    .sort_values("dataset_sort_index")
    .itertuples(index=False)
):
    painting_id = painting.painting_id

    cases = CASE_GROUPS[painting_id]
    candidates = CANDIDATE_GROUPS[
        painting_id
    ]

    case_reports = CASE_REPORT_GROUPS.get(
        painting_id,
        pd.DataFrame(
            columns=CASE_REPORT_INDEX.columns
        ),
    )

    painting_report = (
        PAINTING_REPORT_LOOKUP.loc[
            painting_id
        ]
    )

    d02_screening_status = (
        None
        if painting_id
        not in D02_SCREENING_LOOKUP.index
        else str(
            D02_SCREENING_LOOKUP.loc[
                painting_id,
                "screening_status",
            ]
        )
    )

    evidence_layers = sorted(
        {
            layer
            for value in candidates[
                "asset_availability_json"
            ]
            for layer in parse_json_list(
                value
            )
        }
    )

    selector_record = {
        "painting_id": painting_id,
        "experiment_ids": sorted_unique(
            candidates,
            "experiment_id",
        ),
        "model_ids": sorted_unique(
            candidates,
            "model_id",
        ),
        "damage_or_degradation_types": (
            sorted_unique(
                cases,
                "damage_or_degradation_type",
            )
        ),
        "population_roles": sorted_unique(
            candidates,
            "population_role",
        ),
        "recommendation_categories": (
            sorted_unique(
                candidates,
                "recommendation_category",
            )
        ),
        "seed_values": sorted_unique(
            candidates,
            "seed",
            integers=True,
        ),
        "prompt_variant_ids": sorted_unique(
            candidates,
            "prompt_variant_id",
        ),
        "evidence_layers": evidence_layers,
        "has_uncertainty": bool(
            candidates[
                "uncertainty_group_id"
            ].notna().any()
        ),
        "has_selected_case_report": bool(
            len(case_reports)
        ),
        "focused_portrait_review_available": (
            d02_screening_status
            == "included"
        ),
    }

    PAINTING_SELECTOR_ROWS.append(
        selector_record
    )

    payload = {
        "schema_version": SETTINGS[
            "expected_output_schemas"
        ]["painting_partition"],
        "release_id": DASHBOARD_RELEASE_ID,
        "painting_id": painting_id,
        "painting": {
            column: json_safe(
                getattr(
                    painting,
                    column,
                )
            )
            for column
            in PAINTING_LOOKUP.columns
            if column
            not in {
                "status",
                "issue",
            }
        },
        "selectors": selector_record,
        "cases": [
            case_route(row)
            for row in cases.itertuples(
                index=False
            )
        ],
        "candidates": [
            candidate_route(row)
            for row
            in candidates.itertuples(
                index=False
            )
        ],
        "reports": {
            "painting": {
                "report_id": (
                    painting_report.report_id
                ),
                "report_path": (
                    painting_report.report_path
                ),
                "report_sha256": (
                    painting_report.report_sha256
                ),
            },
            "selected_cases": [
                {
                    "report_id": row.report_id,
                    "case_id": row.case_id,
                    "report_path": (
                        row.report_path
                    ),
                    "report_sha256": (
                        row.report_sha256
                    ),
                }
                for row
                in case_reports.itertuples(
                    index=False
                )
            ],
        },
        "focused_portrait_review": {
            "screening_status": (
                d02_screening_status
            ),
            "annotation_count": int(
                D02_ANNOTATION_COUNTS.get(
                    painting_id,
                    0,
                )
            ),
            "eligible_case_count": int(
                D02_ELIGIBLE_COUNTS.get(
                    painting_id,
                    0,
                )
            ),
            "blind_review_unit_count": int(
                D02_REVIEW_COUNTS.get(
                    painting_id,
                    0,
                )
            ),
        },
        "status": "ok",
    }

    payload = json_safe(payload)

    packed = deterministic_gzip_bytes(
        payload
    )

    relative_path = SETTINGS[
        "output"
    ]["painting_shard_template"].format(
        painting_id=painting_id
    )

    PAINTING_SHARD_PAYLOADS[
        painting_id
    ] = payload

    PAINTING_SHARD_BYTES[
        painting_id
    ] = packed["bytes"]

    PAINTING_SHARD_LEDGER_ROWS.append(
        {
            "painting_id": painting_id,
            "relative_path": relative_path,
            "case_count": len(
                payload["cases"]
            ),
            "eligible_case_count": sum(
                record[
                    "four_method_eligible"
                ]
                for record in payload["cases"]
            ),
            "candidate_count": len(
                payload["candidates"]
            ),
            "painting_report_count": 1,
            "selected_case_report_count": len(
                payload["reports"][
                    "selected_cases"
                ]
            ),
            "d02_included": (
                d02_screening_status
                == "included"
            ),
            "decoded_size_bytes": packed[
                "decoded_size_bytes"
            ],
            "decoded_sha256": packed[
                "decoded_sha256"
            ],
            "compressed_size_bytes": packed[
                "compressed_size_bytes"
            ],
            "compressed_sha256": packed[
                "compressed_sha256"
            ],
            "status": "ok",
        }
    )


PAINTING_SELECTOR_INDEX = (
    pd.DataFrame(
        PAINTING_SELECTOR_ROWS
    )
    .sort_values("painting_id")
    .reset_index(drop=True)
)

PAINTING_SHARD_LEDGER = (
    pd.DataFrame(
        PAINTING_SHARD_LEDGER_ROWS
    )
    .sort_values("painting_id")
    .reset_index(drop=True)
)


FILTER_OPTIONS = {
    **FILTER_OPTIONS,
    "painting_availability": json_safe(
        PAINTING_SELECTOR_ROWS
    ),
    "experiment_applicability": (
        json_safe(
            EXPERIMENT_DIMENSION.to_dict(
                orient="records"
            )
        )
    ),
    "model_applicability": json_safe(
        MODEL_DIMENSION.to_dict(
            orient="records"
        )
    ),
}


BOOTSTRAP[
    "selector_index"
] = {
    "painting_availability_count": len(
        PAINTING_SELECTOR_INDEX
    ),
    "painting_partition_template": (
        SETTINGS["output"][
            "painting_shard_template"
        ]
    ),
    "candidate_ids_in_bootstrap": False,
}


BOOTSTRAP_COMPONENT_BYTES[
    "bootstrap.json"
] = len(
    canonical_json_bytes(
        BOOTSTRAP
    )
)

BOOTSTRAP_COMPONENT_BYTES[
    "filter_options.json"
] = len(
    canonical_json_bytes(
        FILTER_OPTIONS
    )
)

BOOTSTRAP_JSON_BYTES = sum(
    BOOTSTRAP_COMPONENT_BYTES.values()
)


display(
    PAINTING_SELECTOR_INDEX.head(10)
)

display(
    PAINTING_SHARD_LEDGER[
        [
            "painting_id",
            "case_count",
            "eligible_case_count",
            "candidate_count",
            "selected_case_report_count",
            "d02_included",
            "compressed_size_bytes",
        ]
    ].head(10)
)

print("Painting partitions constructed:", len(PAINTING_SHARD_LEDGER))
print(
    "Case memberships:",
    int(
        PAINTING_SHARD_LEDGER[
            "case_count"
        ].sum()
    ),
)
print(
    "Candidate memberships:",
    int(
        PAINTING_SHARD_LEDGER[
            "candidate_count"
        ].sum()
    ),
)
print(
    "Compressed shard bytes:",
    int(
        PAINTING_SHARD_LEDGER[
            "compressed_size_bytes"
        ].sum()
    ),
)
print(
    "Largest compressed shard:",
    int(
        PAINTING_SHARD_LEDGER[
            "compressed_size_bytes"
        ].max()
    ),
)

,painting_id,experiment_ids,model_ids,damage_or_degradation_types,population_roles,recommendation_categories,seed_values,prompt_variant_ids,evidence_layers,has_uncertainty,has_selected_case_report,focused_portrait_review_available
0,p001,"[canonical_missing_region, damage_size_sensiti...","[hint_places2, lama, opencv_telea, sdxl_inpain...","[binary_missing_region, dirt_dust, discolourat...","[bounded_sdxl, primary_and_uncertainty, primar...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,True,True
1,p002,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,True,True
2,p003,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,False,True
3,p004,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,False,True
4,p005,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,False,True
5,p006,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,False,True
6,p007,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,False,True
7,p008,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,False,True
8,p009,"[canonical_missing_region, damage_size_sensiti...","[hint_places2, lama, opencv_telea, stable_diff...","[binary_missing_region, dirt_dust, discolourat...","[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,True,False
9,p010,[canonical_missing_region],"[hint_places2, lama, opencv_telea, stable_diff...",[binary_missing_region],"[primary_and_uncertainty, primary_comparison, ...","[do_not_rely_automatically, specialist_review_...","[2026, 2027, 2028, 2029]","[p00_generic, p05_scratch_aware]","[colour, difference, mask_boundary, seam, sema...",True,False,True

,painting_id,case_count,eligible_case_count,candidate_count,selected_case_report_count,d02_included,compressed_size_bytes
0,p001,60,37,178,5,True,52066
1,p002,5,5,36,2,True,15521
2,p003,5,5,27,0,True,11085
3,p004,5,5,27,0,True,10455
4,p005,5,5,27,0,True,11412
5,p006,5,5,27,0,True,10587
6,p007,5,5,36,0,True,11281
7,p008,5,5,27,0,True,10282
8,p009,60,37,176,1,False,50652
9,p010,5,5,27,0,True,10122

Painting partitions constructed: 300
Case memberships: 3425
Candidate memberships: 13879
Compressed shard bytes: 4607915
Largest compressed shard: 59299

In [18]:
STAGING_PACKAGE_ROOT = (
    OUTPUT_PATHS["work_dir"]
    / f"release_{DASHBOARD_RELEASE_ID}"
)

STAGING_BOOTSTRAP_DIR = (
    STAGING_PACKAGE_ROOT
    / SETTINGS["output"]["bootstrap_dir"]
)

STAGING_PAINTINGS_DIR = (
    STAGING_PACKAGE_ROOT
    / SETTINGS["output"]["paintings_dir"]
)

STAGED_PAINTING_LOOKUP_PATH = (
    STAGING_PACKAGE_ROOT
    / SETTINGS["output"][
        "painting_lookup_path"
    ]
)

STAGED_FILTER_OPTIONS_PATH = (
    STAGING_PACKAGE_ROOT
    / SETTINGS["output"][
        "filter_options_path"
    ]
)


atomic_write_parquet(
    PAINTING_LOOKUP,
    STAGED_PAINTING_LOOKUP_PATH,
)

atomic_write_json(
    FILTER_OPTIONS,
    STAGED_FILTER_OPTIONS_PATH,
)


for row in PAINTING_SHARD_LEDGER.itertuples(
    index=False
):
    destination = (
        STAGING_PACKAGE_ROOT
        / row.relative_path
    )

    atomic_write_bytes(
        PAINTING_SHARD_BYTES[
            row.painting_id
        ],
        destination,
    )


EXPECTED_STAGED_SHARD_PATHS = {
    (
        STAGING_PACKAGE_ROOT
        / relative_path
    ).resolve()
    for relative_path
    in PAINTING_SHARD_LEDGER[
        "relative_path"
    ]
}

OBSERVED_STAGED_SHARD_PATHS = {
    path.resolve()
    for path
    in STAGING_PAINTINGS_DIR.glob(
        "p*.json.gz"
    )
    if path.is_file()
}


STAGED_SHA_MISMATCHES = []
STAGED_DECODED_MISMATCHES = []
STAGED_GZIP_MTIME_ERRORS = []

ledger_lookup = (
    PAINTING_SHARD_LEDGER
    .set_index(
        "painting_id",
        verify_integrity=True,
    )
)

for painting_id, payload in (
    PAINTING_SHARD_PAYLOADS.items()
):
    relative_path = SETTINGS[
        "output"
    ]["painting_shard_template"].format(
        painting_id=painting_id
    )

    path = (
        STAGING_PACKAGE_ROOT
        / relative_path
    )

    expected = ledger_lookup.loc[
        painting_id
    ]

    raw_bytes = path.read_bytes()

    observed_compressed_sha256 = (
        hashlib.sha256(
            raw_bytes
        ).hexdigest()
    )

    if (
        observed_compressed_sha256
        != expected[
            "compressed_sha256"
        ]
    ):
        STAGED_SHA_MISMATCHES.append(
            painting_id
        )

    if raw_bytes[4:8] != b"\x00\x00\x00\x00":
        STAGED_GZIP_MTIME_ERRORS.append(
            painting_id
        )

    with gzip.open(
        path,
        "rb",
    ) as handle:
        decoded = handle.read()

    observed_decoded_sha256 = (
        hashlib.sha256(
            decoded
        ).hexdigest()
    )

    if (
        observed_decoded_sha256
        != expected[
            "decoded_sha256"
        ]
    ):
        STAGED_DECODED_MISMATCHES.append(
            painting_id
        )


STAGED_PAINTING_LOOKUP = (
    pd.read_parquet(
        STAGED_PAINTING_LOOKUP_PATH
    )
)

STAGED_FILTER_OPTIONS = json.loads(
    STAGED_FILTER_OPTIONS_PATH.read_text(
        encoding="utf-8"
    )
)


display(
    PAINTING_SHARD_LEDGER[
        [
            "decoded_size_bytes",
            "compressed_size_bytes",
        ]
    ].agg(
        [
            "count",
            "sum",
            "min",
            "median",
            "max",
        ]
    )
)

print("Batch 4 work package staged.")
print(
    "Staged painting lookup rows:",
    len(STAGED_PAINTING_LOOKUP),
)
print(
    "Staged painting shards:",
    len(OBSERVED_STAGED_SHARD_PATHS),
)
print(
    "Compressed shard bytes:",
    int(
        PAINTING_SHARD_LEDGER[
            "compressed_size_bytes"
        ].sum()
    ),
)
print(
    "Compressed checksum mismatches:",
    len(STAGED_SHA_MISMATCHES),
)
print(
    "Decoded checksum mismatches:",
    len(STAGED_DECODED_MISMATCHES),
)
print(
    "Non-deterministic gzip headers:",
    len(STAGED_GZIP_MTIME_ERRORS),
)
print(
    "Canonical package has not been promoted."
)

        decoded_size_bytes  compressed_size_bytes
count                300.0                  300.0
sum             49987926.0              4607915.0
min                86750.0                 7929.0
median            104552.0                11033.0
max               679625.0                59299.0

Batch 4 work package staged.
Staged painting lookup rows: 300
Staged painting shards: 300
Compressed shard bytes: 4607915
Compressed checksum mismatches: 0
Decoded checksum mismatches: 0
Non-deterministic gzip headers: 0
Canonical package has not been promoted.

In [19]:
VALIDATION_ROWS[:] = [
    row
    for row in VALIDATION_ROWS
    if row["validation_stage"]
    != BATCH_4_STAGE
]


EXPECTED_CATEGORY_COUNTS = {
    "abstraction_surrealism": 60,
    "architecture_structured": 60,
    "high_texture_brushwork": 60,
    "landscape_natural": 60,
    "portrait_figure": 60,
}

OBSERVED_CATEGORY_COUNTS = (
    PAINTING_LOOKUP[
        "category"
    ]
    .value_counts()
    .sort_index()
    .astype(int)
    .to_dict()
)

SHARD_CANDIDATE_IDS = [
    candidate["candidate_id"]
    for payload
    in PAINTING_SHARD_PAYLOADS.values()
    for candidate
    in payload["candidates"]
]

SHARD_CASE_IDS = [
    case["case_id"]
    for payload
    in PAINTING_SHARD_PAYLOADS.values()
    for case
    in payload["cases"]
]

SHARD_NETWORK_REFERENCES = sorted(
    {
        value
        for payload
        in PAINTING_SHARD_PAYLOADS.values()
        for value in payload_strings(
            payload
        )
        if (
            "://" in value
            or value.startswith("//")
        )
    }
)

EXPECTED_PARTITION_PATHS = set(
    PAINTING_LOOKUP[
        "painting_partition_path"
    ]
)

OBSERVED_PARTITION_PATHS = set(
    PAINTING_SHARD_LEDGER[
        "relative_path"
    ]
)

CANONICAL_OUTPUT_FILES = [
    path
    for path in OUTPUT_ROOT.rglob("*")
    if (
        path.is_file()
        and OUTPUT_PATHS[
            "work_dir"
        ].resolve()
        not in path.resolve().parents
    )
]


BATCH_4_CHECKS = [
    (
        "painting_lookup_rows",
        len(PAINTING_LOOKUP),
        300,
    ),
    (
        "painting_selector_rows",
        len(PAINTING_SELECTOR_INDEX),
        300,
    ),
    (
        "painting_shard_count",
        len(PAINTING_SHARD_PAYLOADS),
        300,
    ),
    (
        "staged_shard_count",
        len(OBSERVED_STAGED_SHARD_PATHS),
        300,
    ),
    (
        "staged_shard_exact_set",
        OBSERVED_STAGED_SHARD_PATHS,
        EXPECTED_STAGED_SHARD_PATHS,
    ),
    (
        "category_balance",
        OBSERVED_CATEGORY_COUNTS,
        EXPECTED_CATEGORY_COUNTS,
    ),
    (
        "case_memberships",
        int(
            PAINTING_SHARD_LEDGER[
                "case_count"
            ].sum()
        ),
        POPULATION[
            "registered_case_count"
        ],
    ),
    (
        "eligible_case_memberships",
        int(
            PAINTING_SHARD_LEDGER[
                "eligible_case_count"
            ].sum()
        ),
        POPULATION[
            "four_model_eligible_case_count"
        ],
    ),
    (
        "candidate_memberships",
        int(
            PAINTING_SHARD_LEDGER[
                "candidate_count"
            ].sum()
        ),
        POPULATION[
            "indexed_inspectable_candidate_count"
        ],
    ),
    (
        "case_identity_uniqueness",
        len(set(SHARD_CASE_IDS)),
        len(SHARD_CASE_IDS),
    ),
    (
        "candidate_identity_uniqueness",
        len(set(SHARD_CANDIDATE_IDS)),
        len(SHARD_CANDIDATE_IDS),
    ),
    (
        "painting_report_routes",
        int(
            PAINTING_SHARD_LEDGER[
                "painting_report_count"
            ].sum()
        ),
        POPULATION[
            "painting_report_count"
        ],
    ),
    (
        "selected_case_report_routes",
        int(
            PAINTING_SHARD_LEDGER[
                "selected_case_report_count"
            ].sum()
        ),
        POPULATION[
            "selected_case_report_count"
        ],
    ),
    (
        "focused_portrait_routes",
        int(
            PAINTING_SHARD_LEDGER[
                "d02_included"
            ].sum()
        ),
        POPULATION[
            "d02_portraits_included"
        ],
    ),
    (
        "painting_partition_paths",
        OBSERVED_PARTITION_PATHS,
        EXPECTED_PARTITION_PATHS,
    ),
    (
        "staged_lookup_rows",
        len(STAGED_PAINTING_LOOKUP),
        300,
    ),
    (
        "staged_filter_availability",
        len(
            STAGED_FILTER_OPTIONS[
                "painting_availability"
            ]
        ),
        300,
    ),
    (
        "filter_candidate_ids_absent",
        "candidate_ids" in FILTER_OPTIONS,
        False,
    ),
    (
        "compressed_checksum_closure",
        STAGED_SHA_MISMATCHES,
        [],
    ),
    (
        "decoded_checksum_closure",
        STAGED_DECODED_MISMATCHES,
        [],
    ),
    (
        "deterministic_gzip_mtime",
        STAGED_GZIP_MTIME_ERRORS,
        [],
    ),
    (
        "shard_network_references",
        SHARD_NETWORK_REFERENCES,
        [],
    ),
    (
        "bootstrap_target_budget",
        (
            BOOTSTRAP_JSON_BYTES
            <= SETTINGS[
                "runtime_budgets"
            ]["bootstrap_target_bytes"]
        ),
        True,
    ),
    (
        "staged_shard_budget",
        (
            int(
                PAINTING_SHARD_LEDGER[
                    "compressed_size_bytes"
                ].sum()
            )
            <= SETTINGS[
                "runtime_budgets"
            ]["local_package_hard_bytes"]
        ),
        True,
    ),
    (
        "canonical_output_files",
        [
            path.relative_to(
                OUTPUT_ROOT
            ).as_posix()
            for path
            in CANONICAL_OUTPUT_FILES
        ],
        [],
    ),
]


for (
    check_name,
    observed,
    expected,
) in BATCH_4_CHECKS:
    passed = observed == expected

    add_check(
        BATCH_4_STAGE,
        check_name,
        observed,
        expected,
        passed,
        (
            ""
            if passed
            else (
                "Batch 4 selector or painting-partition "
                "evidence differs from the approved "
                "Controlled-300 contract."
            )
        ),
    )


require_no_blocking_failures(
    "Batch 4 selectors and painting partitions"
)

BATCH_4_VALIDATION = (
    current_validation_frame()
    .loc[
        lambda frame: frame[
            "validation_stage"
        ].eq(BATCH_4_STAGE)
    ]
    .reset_index(drop=True)
)


display(
    BATCH_4_VALIDATION[
        [
            "check_description",
            "severity",
            "passed",
            "observed",
        ]
    ]
)

print("Batch 4 selectors and painting partitions passed.")
print(
    "Painting partitions:",
    len(PAINTING_SHARD_PAYLOADS),
)
print(
    "Registered case memberships:",
    len(SHARD_CASE_IDS),
)
print(
    "Candidate memberships:",
    len(SHARD_CANDIDATE_IDS),
)
print(
    "Selected case-report routes:",
    int(
        PAINTING_SHARD_LEDGER[
            "selected_case_report_count"
        ].sum()
    ),
)
print(
    "Focused portrait-review routes:",
    int(
        PAINTING_SHARD_LEDGER[
            "d02_included"
        ].sum()
    ),
)
print(
    "Compressed shard bytes:",
    int(
        PAINTING_SHARD_LEDGER[
            "compressed_size_bytes"
        ].sum()
    ),
)
print("Canonical files promoted: 0")

,check_description,severity,passed,observed
0,painting_lookup_rows,blocking,True,300
1,painting_selector_rows,blocking,True,300
2,painting_shard_count,blocking,True,300
3,staged_shard_count,blocking,True,300
4,staged_shard_exact_set,blocking,True,"""{WindowsPath('D:/Masters/FH/Thesis/painting-r..."
5,category_balance,blocking,True,"{""abstraction_surrealism"": 60, ""architecture_s..."
6,case_memberships,blocking,True,3425
7,eligible_case_memberships,blocking,True,2620
8,candidate_memberships,blocking,True,13879
9,case_identity_uniqueness,blocking,True,3425
10,candidate_identity_uniqueness,blocking,True,13879
11,painting_report_routes,blocking,True,300
12,selected_case_report_routes,blocking,True,30
13,focused_portrait_routes,blocking,True,36
14,painting_partition_paths,blocking,True,"""{'data/paintings/p055.json.gz', 'data/paintin..."
15,staged_lookup_rows,blocking,True,300
16,staged_filter_availability,blocking,True,300
17,filter_candidate_ids_absent,blocking,True,False
18,compressed_checksum_closure,blocking,True,[]
19,decoded_checksum_closure,blocking,True,[]
20,deterministic_gzip_mtime,blocking,True,[]
21,shard_network_references,blocking,True,[]
22,bootstrap_target_budget,blocking,True,True
23,staged_shard_budget,blocking,True,True
24,canonical_output_files,blocking,True,[]

Batch 4 selectors and painting partitions passed.
Painting partitions: 300
Registered case memberships: 3425
Candidate memberships: 13879
Selected case-report routes: 30
Focused portrait-review routes: 36
Compressed shard bytes: 4607915
Canonical files promoted: 0

## Batch 5 — Eight room partitions and the Focused Portrait Review subroute

This batch converts the approved producer-artifact map into nine compact room-loading partitions: the eight principal museum rooms and the single D02 child route under Trustworthiness.

Each partition contains one normalized row per approved `display_id`, including its display role, source contract, mapping state, interpretation boundary, denominator where applicable and exact upstream notebook references. The four displays that require Batch 6 derivation remain explicit `pending_derivation` records; they are never treated as available early.

The partitions are staged only under the release work directory. No canonical dashboard file is promoted, no image bytes are copied, and no network request is made.

In [20]:
import re


BATCH_5_STAGE = "batch_5_room_partitions"

PRODUCER_MAP_RELATIVE_PATH = SETTINGS[
    "governing_contracts"
]["producer_artifact_map"]["path"]

PRODUCER_MAP_PATH = (
    PROJECT_ROOT
    / PRODUCER_MAP_RELATIVE_PATH
)


SECTION_ROUTE_IDS = {
    "01": "exhibition_foyer",
    "02": "study_design",
    "03": "metric_framework",
    "04": "model_gallery",
    "05": "stability_lab",
    "06": "trustworthiness",
    "D02": "focused_portrait_review",
    "07": "case_explorer",
    "08": "research_archive",
}

MAPPING_STATE_PRIORITY = (
    "unsupported_until_derived",
    "n34_derived_registered",
    "existing_direct",
    "existing_filtered",
)


def plain_markdown(
    value: str,
) -> str:
    """Remove lightweight Markdown from one display label."""

    text = re.sub(
        r"\[([^\]]+)\]\([^\)]+\)",
        r"\1",
        str(value),
    )

    return (
        text
        .replace("`", "")
        .replace("*", "")
        .strip()
    )


def component_kind_for(
    display_id: str,
) -> str:
    """Assign an approved dashboard component type."""

    if (
        display_id.startswith("foyer.route")
        or display_id.startswith("foyer.tour")
    ):
        return "route"

    if any(
        token in display_id
        for token in (
            ".report",
            ".record",
            ".ledger",
            ".provenance",
            ".publication",
            ".limits",
        )
    ):
        return "report"

    if any(
        token in display_id
        for token in (
            ".hero",
            ".anchor.images",
            ".anchor.input",
            ".anchor.triad",
            ".anchor.peers",
            ".anchor.views",
            ".anchor.difference",
            ".anchor.local",
            ".anchor.semantic",
            ".anchor.uncertainty",
            ".output.",
            ".seed.overlay",
            ".retrieval",
            ".counterfactuals",
            ".r005.panel",
            ".r005.control",
        )
    ):
        return "image"

    if any(
        token in display_id
        for token in (
            ".selector",
            ".routing",
            ".collection.drawers",
            ".catalogue",
            ".ui.",
        )
    ):
        return "selector"

    if any(
        token in display_id
        for token in (
            ".conclusion",
            ".findings",
            ".decision",
            ".status",
            ".rules",
        )
    ):
        return "conclusion"

    if any(
        token in display_id
        for token in (
            ".trajectory",
            ".overlay",
        )
    ):
        return "chart"

    return "metric"


def source_notebook_ids(
    value: str,
) -> list[str]:
    """Extract ordered notebook identities from one producer description."""

    tokens = re.findall(
        r"\b(N(?:12A|\d{2})|D0[12])\b",
        value,
    )

    normalized = []

    for token in tokens:
        logical_id = (
            token[1:]
            if token.startswith("N")
            else token
        )

        if (
            logical_id != "34"
            and logical_id not in normalized
        ):
            normalized.append(logical_id)

    return normalized


ROOM_DISPLAY_CONTRACT_ROWS = []
CURRENT_SECTION = None
ROOM_MAP_PARSE_ERRORS = []


for line_number, raw_line in enumerate(
    PRODUCER_MAP_PATH.read_text(
        encoding="utf-8"
    ).splitlines(),
    start=1,
):
    heading = re.match(
        r"^## (01|02|03|04|05|06|07|08|D02) — ",
        raw_line,
    )

    if heading:
        CURRENT_SECTION = heading.group(1)
        continue

    if (
        CURRENT_SECTION is None
        or not re.match(
            r"^\| `[^`]+` \|",
            raw_line,
        )
    ):
        continue

    cells = [
        cell.strip()
        for cell
        in raw_line.strip().strip("|").split("|")
    ]

    if len(cells) != 4:
        ROOM_MAP_PARSE_ERRORS.append(
            f"line {line_number}: "
            f"{len(cells)} cells"
        )
        continue

    display_id = (
        cells[0]
        .strip()
        .strip("`")
    )

    state_tokens = [
        state
        for state in SETTINGS[
            "validation"
        ]["allowed_mapping_states"]
        if f"`{state}`" in cells[3]
    ]

    primary_state = next(
        (
            state
            for state
            in MAPPING_STATE_PRIORITY
            if state in state_tokens
        ),
        None,
    )

    if primary_state is None:
        ROOM_MAP_PARSE_ERRORS.append(
            f"line {line_number}: "
            "no mapping state"
        )
        continue

    room_id = SECTION_ROUTE_IDS[
        CURRENT_SECTION
    ]

    source_text = (
        f"{cells[2]} {cells[3]}"
    )

    ROOM_DISPLAY_CONTRACT_ROWS.append(
        {
            "room_id": room_id,
            "subroute_id": (
                "focused_portrait_review"
                if room_id
                == "focused_portrait_review"
                else None
            ),
            "display_id": display_id,
            "label": plain_markdown(
                cells[1]
            ),
            "producer_binding": cells[2],
            "handoff": cells[3],
            "mapping_state": primary_state,
            "mapping_states": state_tokens,
            "component_kind": (
                component_kind_for(
                    display_id
                )
            ),
            "source_notebook_ids": (
                source_notebook_ids(
                    source_text
                )
            ),
            "source_line_number": (
                line_number
            ),
        }
    )


ROOM_DISPLAY_CONTRACT = pd.DataFrame(
    ROOM_DISPLAY_CONTRACT_ROWS
)

ROOM_DISPLAY_CONTRACT[
    "display_order"
] = (
    ROOM_DISPLAY_CONTRACT
    .groupby(
        "room_id",
        sort=False,
    )
    .cumcount()
    + 1
)


print(
    "Approved display contracts parsed:",
    len(ROOM_DISPLAY_CONTRACT),
)

print(
    "Parse errors:",
    ROOM_MAP_PARSE_ERRORS,
)

print(
    "Room counts:",
    ROOM_DISPLAY_CONTRACT
    .groupby("room_id")
    .size()
    .to_dict(),
)

Approved display contracts parsed: 100
Parse errors: []
Room counts: {'case_explorer': 15, 'exhibition_foyer': 7, 'focused_portrait_review': 10, 'metric_framework': 12, 'model_gallery': 12, 'research_archive': 16, 'stability_lab': 8, 'study_design': 13, 'trustworthiness': 7}

In [21]:
DISPLAY_DENOMINATORS = {
    "foyer.scope.paintings": (
        "300 paintings"
    ),
    "foyer.scope.categories": (
        "300 paintings across five categories"
    ),
    "foyer.scope.cases": (
        "3,425 registered cases"
    ),
    "study.branch.damage_size": (
        "245 cases"
    ),
    "study.branch.mask_placement": (
        "525 cases"
    ),
    "study.branch.other_changes": (
        "1,155 generated cases"
    ),
    "study.scope.catalogues": (
        "3,425 registered; "
        "2,620 four-method eligible"
    ),
    "study.d02.plaque": (
        "60 screened portraits"
    ),
    "metric.policy.ledger": (
        "143 metric-family/region policies"
    ),
    "metric.quality.anchors": (
        "11 separate quality anchors"
    ),
    "models.conclusion.anchors": (
        "11 separate quality anchors"
    ),
    "models.sdxl.coverage": (
        "35 scheduled SDXL cases"
    ),
    "stability.damage.summary": (
        "35 paintings; 245 cases"
    ),
    "stability.mask.summary": (
        "35 paintings; 525 cases"
    ),
    "stability.degradation.summary": (
        "1,155 generated; 350 eligible"
    ),
    "stability.seed.population": (
        "1,025 four-seed groups"
    ),
    "d02.funnel": (
        "60 screened portraits"
    ),
    "d02.hand.findings": (
        "12 matched hand-region contrasts"
    ),
    "d02.lightness.findings": (
        "24 model-metric associations"
    ),
    "case.catalogue": (
        "13,879 inspectable candidates"
    ),
    "case.retrieval": (
        "10 queries; 100 neighbour rows"
    ),
    "case.counterfactuals": (
        "14 selected panels"
    ),
    "case.painting.report": (
        "300 painting reports"
    ),
    "case.case.report": (
        "30 selected detailed case reports"
    ),
    "archive.scope.paintings": (
        "300 paintings"
    ),
    "archive.scope.stages": (
        "36 completed notebook stages"
    ),
    "archive.scope.cases": (
        "3,425 registered cases"
    ),
    "archive.scope.candidates": (
        "13,879 inspectable candidates"
    ),
    "archive.scope.n32_reports": (
        "331 browsable N32 records"
    ),
    "archive.scope.model_reports": (
        "5 model reports"
    ),
    "archive.scope.figures": (
        "24 final figures"
    ),
    "archive.scope.claims_limits": (
        "49 claims; 18 limitations"
    ),
    "archive.publication.individual": (
        "2,653 verified individual artifacts"
    ),
    "archive.publication.bundles": (
        "6 verified bundle releases"
    ),
    "archive.limits": (
        "18 final limitations"
    ),
}


ROOM_RECORD_ROWS = []


for record in ROOM_DISPLAY_CONTRACT.to_dict(
    orient="records"
):
    room_id = record["room_id"]
    mapping_state = record[
        "mapping_state"
    ]

    value = {
        "payload_ref": record[
            "display_id"
        ],
        "component_kind": record[
            "component_kind"
        ],
        "mapping_state": mapping_state,
        "mapping_states": record[
            "mapping_states"
        ],
        "producer_binding": record[
            "producer_binding"
        ],
        "handoff": record["handoff"],
    }

    ROOM_RECORD_ROWS.append(
        {
            "room_record_id": stable_id(
                "room_record",
                {
                    "release_id": (
                        DASHBOARD_RELEASE_ID
                    ),
                    "display_id": record[
                        "display_id"
                    ],
                },
            ),
            "room_id": room_id,
            "subroute_id": record[
                "subroute_id"
            ],
            "section_id": (
                record["display_id"]
                .rsplit(".", 1)[0]
            ),
            "display_id": record[
                "display_id"
            ],
            "slot_id": record[
                "display_id"
            ],
            "display_order": int(
                record["display_order"]
            ),
            "record_type": record[
                "component_kind"
            ],
            "record_key": record[
                "display_id"
            ],
            "label": record["label"],
            "value_json": (
                canonical_json_bytes(
                    value
                ).decode("utf-8")
            ),
            "value_unit": None,
            "interpretation": record[
                "label"
            ],
            "limitation": ROOM_CONTENT[
                room_id
            ]["boundary"],
            "denominator": (
                DISPLAY_DENOMINATORS.get(
                    record["display_id"]
                )
            ),
            "applicability_state": (
                "pending_derivation"
                if mapping_state
                == "unsupported_until_derived"
                else (
                    "conditional"
                    if "conditional"
                    in record[
                        "handoff"
                    ].lower()
                    else "available"
                )
            ),
            "source_notebook_ids_json": (
                json.dumps(
                    record[
                        "source_notebook_ids"
                    ],
                    ensure_ascii=False,
                )
            ),
            "source_paths_json": (
                json.dumps(
                    [
                        PRODUCER_MAP_RELATIVE_PATH,
                        PAGE_CONTRACT_PATH,
                    ],
                    ensure_ascii=False,
                )
            ),
            "source_row_ids_json": (
                json.dumps(
                    [
                        record[
                            "display_id"
                        ]
                    ],
                    ensure_ascii=False,
                )
            ),
            "schema_version": SETTINGS[
                "expected_output_schemas"
            ]["room_partition"],
            "status": "ok",
            "issue": "",
        }
    )


ROOM_RECORDS = validate_output_frame(
    pd.DataFrame(
        ROOM_RECORD_ROWS
    ),
    "room_records",
)


ROOM_RECORD_SUMMARY = (
    ROOM_RECORDS
    .groupby(
        [
            "room_id",
            "record_type",
        ],
        dropna=False,
    )
    .size()
    .rename("records")
    .reset_index()
)


display(ROOM_RECORD_SUMMARY)

print(
    "Normalized room records:",
    len(ROOM_RECORDS),
)

print(
    "Unique display IDs:",
    ROOM_RECORDS[
        "display_id"
    ].nunique(),
)

                    room_id record_type  records
0             case_explorer  conclusion        1
1             case_explorer       image        7
2             case_explorer      metric        3
3             case_explorer      report        3
4             case_explorer    selector        1
5          exhibition_foyer       image        1
6          exhibition_foyer      metric        4
7          exhibition_foyer       route        2
8   focused_portrait_review  conclusion        2
9   focused_portrait_review       image        4
10  focused_portrait_review      metric        4
11         metric_framework       image        1
12         metric_framework      metric        9
13         metric_framework      report        1
14         metric_framework    selector        1
15            model_gallery  conclusion        2
16            model_gallery       image        6
17            model_gallery      metric        3
18            model_gallery      report        1
19         research_archive      metric        8
20         research_archive      report        8
21            stability_lab       chart        1
22            stability_lab       image        2
23            stability_lab      metric        5
24             study_design      metric       10
25             study_design    selector        3
26          trustworthiness  conclusion        1
27          trustworthiness       image        2
28          trustworthiness      metric        4

Normalized room records: 100
Unique display IDs: 100

In [22]:
ROOM_PARTITIONS = {}
ROOM_PARTITION_LEDGER_ROWS = []
PARTITION_READBACK_ERRORS = []


for room_id in EXPECTED_ALL_ROOM_IDS:
    partition = (
        ROOM_RECORDS.loc[
            ROOM_RECORDS[
                "room_id"
            ].eq(room_id)
        ]
        .sort_values(
            [
                "display_order",
                "display_id",
            ]
        )
        .reset_index(drop=True)
    )

    ROOM_PARTITIONS[
        room_id
    ] = partition

    relative_path = SETTINGS[
        "output"
    ][f"{room_id}_path"]

    destination = (
        STAGING_PACKAGE_ROOT
        / relative_path
    )

    atomic_write_parquet(
        partition,
        destination,
    )

    readback = pd.read_parquet(
        destination
    )

    expected_ids = partition[
        "display_id"
    ].tolist()

    observed_ids = readback[
        "display_id"
    ].tolist()

    if (
        expected_ids != observed_ids
        or len(readback)
        != len(partition)
    ):
        PARTITION_READBACK_ERRORS.append(
            room_id
        )

    memory_bytes = int(
        partition.memory_usage(
            index=True,
            deep=True,
        ).sum()
    )

    ROOM_PARTITION_LEDGER_ROWS.append(
        {
            "partition_id": stable_id(
                "room_partition",
                {
                    "release_id": (
                        DASHBOARD_RELEASE_ID
                    ),
                    "room_id": room_id,
                    "subroute_id": (
                        "focused_portrait_review"
                        if room_id
                        == "focused_portrait_review"
                        else None
                    ),
                },
            ),
            "room_id": room_id,
            "subroute_id": (
                "focused_portrait_review"
                if room_id
                == "focused_portrait_review"
                else None
            ),
            "relative_path": (
                relative_path
            ),
            "loading_tier": (
                "room_partition"
            ),
            "row_count": len(
                partition
            ),
            "size_bytes": (
                destination.stat().st_size
            ),
            "sha256": sha256_file(
                destination
            ),
            "display_ids_json": (
                json.dumps(
                    expected_ids,
                    ensure_ascii=False,
                )
            ),
            "schema_version": SETTINGS[
                "expected_output_schemas"
            ]["room_partitions"],
            "status": "ok",
            "issue": "",
            "memory_bytes": (
                memory_bytes
            ),
        }
    )


ROOM_PARTITION_LEDGER = (
    pd.DataFrame(
        ROOM_PARTITION_LEDGER_ROWS
    )
    .sort_values(
        [
            "room_id",
            "subroute_id",
        ],
        na_position="first",
    )
    .reset_index(drop=True)
)


ROOM_PARTITION_INDEX = (
    validate_output_frame(
        ROOM_PARTITION_LEDGER.drop(
            columns=[
                "memory_bytes"
            ]
        ),
        "room_partitions",
    )
)


STAGING_ROOMS_DIR = (
    STAGING_PACKAGE_ROOT
    / SETTINGS["output"][
        "rooms_dir"
    ]
)

EXPECTED_STAGED_ROOM_PATHS = {
    (
        STAGING_PACKAGE_ROOT
        / path
    ).resolve()
    for path
    in ROOM_PARTITION_INDEX[
        "relative_path"
    ]
}

OBSERVED_STAGED_ROOM_PATHS = {
    path.resolve()
    for path
    in STAGING_ROOMS_DIR.glob(
        "*.parquet"
    )
    if path.is_file()
}


STAGED_PARTITION_CHECKSUM_ERRORS = []

for row in ROOM_PARTITION_INDEX.itertuples(
    index=False
):
    path = (
        STAGING_PACKAGE_ROOT
        / row.relative_path
    )

    if (
        sha256_file(path)
        != row.sha256
        or path.stat().st_size
        != row.size_bytes
    ):
        STAGED_PARTITION_CHECKSUM_ERRORS.append(
            row.room_id
        )


ROOM_PARTITION_SIZE_SUMMARY = (
    ROOM_PARTITION_LEDGER[
        [
            "row_count",
            "size_bytes",
            "memory_bytes",
        ]
    ]
    .agg(
        [
            "count",
            "sum",
            "min",
            "median",
            "max",
        ]
    )
)


display(
    ROOM_PARTITION_SIZE_SUMMARY
)

print(
    "Room partitions staged:",
    len(ROOM_PARTITION_INDEX),
)

print(
    "Staged room bytes:",
    int(
        ROOM_PARTITION_INDEX[
            "size_bytes"
        ].sum()
    ),
)

print(
    "Readback errors:",
    PARTITION_READBACK_ERRORS,
)

print(
    "Checksum errors:",
    STAGED_PARTITION_CHECKSUM_ERRORS,
)

print(
    "Canonical package has not been promoted."
)

        row_count  size_bytes  memory_bytes
count         9.0         9.0           9.0
sum         100.0    170827.0      196842.0
min           7.0     17892.0       12583.0
median       12.0     19303.0       23366.0
max          16.0     19455.0       30788.0

Room partitions staged: 9
Staged room bytes: 170827
Readback errors: []
Checksum errors: []
Canonical package has not been promoted.

In [23]:
VALIDATION_ROWS[:] = [
    row
    for row in VALIDATION_ROWS
    if row["validation_stage"]
    != BATCH_5_STAGE
]


ROOM_COUNT_EXPECTATIONS = {
    "exhibition_foyer": 7,
    "study_design": 13,
    "metric_framework": 12,
    "model_gallery": 12,
    "stability_lab": 8,
    "trustworthiness": 7,
    "focused_portrait_review": 10,
    "case_explorer": 15,
    "research_archive": 16,
}


OBSERVED_ROOM_COUNTS = (
    ROOM_RECORDS
    .groupby(
        "room_id",
        sort=False,
    )
    .size()
    .astype(int)
    .to_dict()
)


OBSERVED_MAPPING_STATES = (
    ROOM_DISPLAY_CONTRACT[
        "mapping_state"
    ]
    .value_counts()
    .astype(int)
    .to_dict()
)

EXPECTED_MAPPING_STATES = {
    "existing_direct": 41,
    "existing_filtered": 42,
    "n34_derived_registered": 13,
    "unsupported_until_derived": 4,
}


UNSUPPORTED_DISPLAY_IDS = sorted(
    ROOM_DISPLAY_CONTRACT.loc[
        ROOM_DISPLAY_CONTRACT[
            "mapping_state"
        ].eq(
            "unsupported_until_derived"
        ),
        "display_id",
    ].tolist()
)

EXPECTED_UNSUPPORTED_DISPLAY_IDS = sorted(
    [
        "trust.threshold.strata",
        "d02.anchor.difference",
        "d02.r005.panel",
        "d02.r005.control",
    ]
)


CANONICAL_OUTPUT_FILES_AFTER_BATCH_5 = [
    path
    for path in OUTPUT_ROOT.rglob("*")
    if (
        path.is_file()
        and OUTPUT_PATHS[
            "work_dir"
        ].resolve()
        not in path.resolve().parents
    )
]


BATCH_5_RESPONSIBILITIES = [
    responsibility
    for responsibility
    in SETTINGS["responsibilities"]
    if int(
        responsibility["batch"]
    ) == 5
]


BATCH_5_CHECKS = [
    (
        "responsibility_contract",
        BATCH_5_RESPONSIBILITIES,
        [
            {
                "responsibility_id": (
                    "R05"
                ),
                "batch": 5,
                "name": (
                    "eight_rooms_plus_"
                    "d02_partitions"
                ),
                "blocking": True,
            }
        ],
    ),
    (
        "producer_map_parse_errors",
        ROOM_MAP_PARSE_ERRORS,
        [],
    ),
    (
        "room_partition_count",
        len(ROOM_PARTITIONS),
        9,
    ),
    (
        "room_record_count",
        len(ROOM_RECORDS),
        100,
    ),
    (
        "display_id_uniqueness",
        ROOM_RECORDS[
            "display_id"
        ].nunique(),
        100,
    ),
    (
        "room_record_counts",
        OBSERVED_ROOM_COUNTS,
        ROOM_COUNT_EXPECTATIONS,
    ),
    (
        "mapping_state_counts",
        OBSERVED_MAPPING_STATES,
        EXPECTED_MAPPING_STATES,
    ),
    (
        "unsupported_derivation_ids",
        UNSUPPORTED_DISPLAY_IDS,
        EXPECTED_UNSUPPORTED_DISPLAY_IDS,
    ),
    (
        "room_record_schema",
        list(
            ROOM_RECORDS.columns
        ),
        list(
            OUTPUT_SCHEMAS[
                "room_records"
            ]
        ),
    ),
    (
        "room_partition_index_schema",
        list(
            ROOM_PARTITION_INDEX.columns
        ),
        list(
            OUTPUT_SCHEMAS[
                "room_partitions"
            ]
        ),
    ),
    (
        "staged_partition_paths",
        OBSERVED_STAGED_ROOM_PATHS,
        EXPECTED_STAGED_ROOM_PATHS,
    ),
    (
        "partition_readback",
        PARTITION_READBACK_ERRORS,
        [],
    ),
    (
        "partition_checksums",
        STAGED_PARTITION_CHECKSUM_ERRORS,
        [],
    ),
    (
        "serialized_partition_budget",
        (
            int(
                ROOM_PARTITION_LEDGER[
                    "size_bytes"
                ].max()
            )
            <= SETTINGS[
                "runtime_budgets"
            ][
                "room_partition_"
                "serialized_hard_bytes"
            ]
        ),
        True,
    ),
    (
        "memory_partition_budget",
        (
            int(
                ROOM_PARTITION_LEDGER[
                    "memory_bytes"
                ].max()
            )
            <= SETTINGS[
                "runtime_budgets"
            ][
                "room_partition_"
                "memory_hard_bytes"
            ]
        ),
        True,
    ),
    (
        "canonical_files_promoted",
        len(
            CANONICAL_OUTPUT_FILES_AFTER_BATCH_5
        ),
        0,
    ),
]


for (
    check_name,
    observed,
    expected,
) in BATCH_5_CHECKS:
    passed = observed == expected

    add_check(
        BATCH_5_STAGE,
        check_name,
        observed,
        expected,
        passed,
        (
            ""
            if passed
            else (
                "Batch 5 differs from the "
                "approved nine-partition contract."
            )
        ),
    )


require_no_blocking_failures(
    "Batch 5 room partitions"
)


BATCH_5_VALIDATION = (
    current_validation_frame()
    .loc[
        lambda frame: frame[
            "validation_stage"
        ].eq(BATCH_5_STAGE)
    ]
    .reset_index(drop=True)
)


display(
    ROOM_PARTITION_LEDGER[
        [
            "room_id",
            "row_count",
            "size_bytes",
            "memory_bytes",
            "sha256",
        ]
    ]
)

display(
    BATCH_5_VALIDATION[
        [
            "check_description",
            "severity",
            "passed",
            "observed",
        ]
    ]
)


print(
    "Batch 5 room partitions passed."
)

print(
    "Room/subroute partitions:",
    len(ROOM_PARTITION_INDEX),
)

print(
    "Approved display records:",
    len(ROOM_RECORDS),
)

print(
    "Room counts:",
    OBSERVED_ROOM_COUNTS,
)

print(
    "Mapping states:",
    OBSERVED_MAPPING_STATES,
)

print(
    "Pending Batch 6 derivations:",
    UNSUPPORTED_DISPLAY_IDS,
)

print(
    "Total staged room bytes:",
    int(
        ROOM_PARTITION_INDEX[
            "size_bytes"
        ].sum()
    ),
)

print(
    "Largest staged room bytes:",
    int(
        ROOM_PARTITION_INDEX[
            "size_bytes"
        ].max()
    ),
)

print(
    "Canonical files promoted: 0"
)

,room_id,row_count,size_bytes,memory_bytes,sha256
0,case_explorer,15,19303,30788,1410cd81dfcfbd24c5659f5ce962e2fe1c3c4078db46b4...
1,exhibition_foyer,7,17892,12583,946b2a73baccd4a541045813f51e4311fb314e69295f50...
2,focused_portrait_review,10,19392,20025,9722e18cd9de2bb133941b1240bdbdab003f42505812db...
3,metric_framework,12,19007,24674,dd8db907f6402c8a235d70a26f4c566ee836a017e1da43...
4,model_gallery,12,18664,23366,fbd943673df957cb9a202c64942bff373b3d1966408358...
5,research_archive,16,19455,29249,e421646210e8c38e7e7fd07e4e2f320016bcee2c894496...
6,stability_lab,8,19305,18360,1dc0b89a20a3ad9e321e5385911713f44e815b6453da67...
7,study_design,13,19346,24659,583988b23cd34cbfb706dae2cfd8d856276cd9d612d433...
8,trustworthiness,7,18463,13138,da6754b6091af4558ca9999abf57a32469a6f0df9f7c9e...

,check_description,severity,passed,observed
0,responsibility_contract,blocking,True,"[{""batch"": 5, ""blocking"": true, ""name"": ""eight..."
1,producer_map_parse_errors,blocking,True,[]
2,room_partition_count,blocking,True,9
3,room_record_count,blocking,True,100
4,display_id_uniqueness,blocking,True,100
5,room_record_counts,blocking,True,"{""case_explorer"": 15, ""exhibition_foyer"": 7, ""..."
6,mapping_state_counts,blocking,True,"{""existing_direct"": 41, ""existing_filtered"": 4..."
7,unsupported_derivation_ids,blocking,True,"[""d02.anchor.difference"", ""d02.r005.control"", ..."
8,room_record_schema,blocking,True,"[""room_record_id"", ""room_id"", ""subroute_id"", ""..."
9,room_partition_index_schema,blocking,True,"[""partition_id"", ""room_id"", ""subroute_id"", ""re..."
10,staged_partition_paths,blocking,True,"""{WindowsPath('D:/Masters/FH/Thesis/painting-r..."
11,partition_readback,blocking,True,[]
12,partition_checksums,blocking,True,[]
13,serialized_partition_budget,blocking,True,True
14,memory_partition_budget,blocking,True,True
15,canonical_files_promoted,blocking,True,0

Batch 5 room partitions passed.
Room/subroute partitions: 9
Approved display records: 100
Room counts: {'exhibition_foyer': 7, 'study_design': 13, 'metric_framework': 12, 'model_gallery': 12, 'stability_lab': 8, 'trustworthiness': 7, 'focused_portrait_review': 10, 'case_explorer': 15, 'research_archive': 16}
Mapping states: {'existing_filtered': 42, 'existing_direct': 41, 'n34_derived_registered': 13, 'unsupported_until_derived': 4}
Pending Batch 6 derivations: ['d02.anchor.difference', 'd02.r005.control', 'd02.r005.panel', 'trust.threshold.strata']
Total staged room bytes: 170827
Largest staged room bytes: 19455
Canonical files promoted: 0

## Batch 6 — Governed threshold, stability, and focused-audit derivatives

This batch creates the five compact derivatives that the approved room map
cannot obtain by filtering a canonical producer table directly:

- the 137 exact N27 operational threshold strata;
- the seven-point p018 LaMa damage-size trajectory backed by N16 and N23;
- the 12 D02 matched-hand inferential summaries;
- the 24 D02 rendered-lightness association summaries; and
- the exact R005 hand/control geometry needed to render the focused audit.

Thresholds are reconstructed from the frozen N27 configuration and source
evidence. Large producer tables are streamed and prefiltered before the N27
normalizer is called. D02 statistics and matching geometry are decoded from
the frozen, self-contained D02 report, with exact raw-row lineage restored
from the canonical D02 tables.

All five artifacts are written atomically beneath the release work directory.
There are no network requests and no canonical dashboard files are promoted.

In [24]:
import gc
import hashlib

import numpy as np

from restoration_eval.failure_taxonomy import (
    calibrate_operational_thresholds,
    load_failure_taxonomy_config,
    normalise_failure_evidence,
)


FAILURE_CONFIG = load_failure_taxonomy_config(
    PROJECT_ROOT
    / SETTINGS["inputs"]["failure_taxonomy_config_path"]
)
FAILURE_SETTINGS = FAILURE_CONFIG["failure_taxonomy"]
THRESHOLD_POLICY = FAILURE_SETTINGS["threshold_policy"]

INDICATOR_CONFIG = {
    str(record["indicator_id"]): record
    for record in FAILURE_SETTINGS["indicators"]
}
INDICATOR_CATEGORY_IDS = {
    indicator_id: sorted(
        str(category["category_id"])
        for category in FAILURE_SETTINGS["failure_categories"]
        if indicator_id
        in {str(value) for value in category["indicator_ids"]}
    )
    for indicator_id in INDICATOR_CONFIG
}

THRESHOLD_CANDIDATE_POPULATION = (
    CANDIDATE_INDEX[
        [
            "candidate_id",
            "case_id",
            "painting_id",
            "model_id",
            "experiment_id",
            "prompt_variant_id",
            "population_role",
        ]
    ]
    .merge(
        CASE_INDEX[["case_id", "damage_or_degradation_type"]],
        on="case_id",
        how="left",
        validate="many_to_one",
    )
)
THRESHOLD_CANDIDATE_POPULATION["quality_analysis_eligible"] = (
    THRESHOLD_CANDIDATE_POPULATION["population_role"].isin(
        ["primary_comparison", "primary_and_uncertainty", "bounded_sdxl"]
    )
)
THRESHOLD_CANDIDATE_POPULATION["is_zero_control"] = (
    THRESHOLD_CANDIDATE_POPULATION["damage_or_degradation_type"]
    .astype(str)
    .eq("zero_control")
)
THRESHOLD_CANDIDATE_IDS = set(
    THRESHOLD_CANDIDATE_POPULATION["candidate_id"].astype(str)
)

DIRECT_SOURCE_SPECS = {
    "classical": {"input_key": "classical_metrics_path", "row_id": "metric_row_id"},
    "perceptual": {"input_key": "lpips_metrics_path", "row_id": "metric_row_id"},
    "feature": {"input_key": "feature_metrics_path", "row_id": "metric_row_id"},
    "spatial": {
        "input_key": "spatial_diagnostics_path",
        "row_id": "spatial_diagnostic_id",
    },
    "local": {
        "input_key": "local_consistency_path",
        "row_id": "local_consistency_id",
    },
    "semantic": {
        "input_key": "semantic_metrics_path",
        "row_id": "semantic_metric_id",
    },
}


def direct_source_union(source_name: str, *, chunksize: int = 100_000) -> pd.DataFrame:
    """Stream one producer and retain only rows used by configured indicators."""

    spec = DIRECT_SOURCE_SPECS[source_name]
    path = PROJECT_ROOT / SETTINGS["inputs"][spec["input_key"]]
    indicators = [
        record
        for record in FAILURE_SETTINGS["indicators"]
        if str(record["source"]) == source_name
    ]
    header = pd.read_csv(path, nrows=0).columns.tolist()
    requested = {
        "candidate_id",
        spec["row_id"],
        "status",
        "metric_name",
        "region_id",
        "summary_statistic",
        "feature_model_id",
    }
    requested.update(str(record["value_column"]) for record in indicators)
    usecols = [column for column in header if column in requested]
    missing = sorted(
        {"candidate_id", spec["row_id"], *(str(r["value_column"]) for r in indicators)}
        - set(usecols)
    )
    if missing:
        raise ValueError(f"{source_name} is missing columns: {missing}")

    retained_chunks = []
    observed_rows = 0
    retained_rows = 0
    print(f"Scanning {source_name} threshold evidence ...")
    for chunk_number, chunk in enumerate(pd.read_csv(
        path,
        usecols=usecols,
        dtype="string",
        chunksize=chunksize,
        low_memory=False,
    ), start=1):
        observed_rows += len(chunk)
        candidate_mask = chunk["candidate_id"].astype(str).isin(
            THRESHOLD_CANDIDATE_IDS
        )
        status_mask = (
            chunk["status"].astype(str).eq("ok")
            if "status" in chunk.columns
            else pd.Series(True, index=chunk.index)
        )
        indicator_union = pd.Series(False, index=chunk.index)
        for indicator in indicators:
            selected = status_mask.copy()
            if source_name != "spatial" and "metric_name" in chunk.columns:
                selected &= chunk["metric_name"].astype(str).eq(
                    str(indicator["metric_name"])
                )
            if "region_id" in chunk.columns:
                selected &= chunk["region_id"].astype(str).eq(
                    str(indicator["region_id"])
                )
            if "summary_statistic" in chunk.columns:
                selected &= chunk["summary_statistic"].astype(str).eq(
                    str(indicator["summary_statistic"])
                )
            feature_model_id = indicator.get("feature_model_id")
            if feature_model_id and "feature_model_id" in chunk.columns:
                selected &= chunk["feature_model_id"].astype(str).eq(
                    str(feature_model_id)
                )
            indicator_union |= selected
        retained = chunk.loc[candidate_mask & indicator_union].copy()
        if not retained.empty:
            retained_chunks.append(retained)
            retained_rows += len(retained)
        if chunk_number % 5 == 0:
            print(
                f"  {source_name}: {observed_rows:,} rows scanned; "
                f"{retained_rows:,} retained"
            )

    expected_rows = int(
        SETTINGS["input_table_contracts"][spec["input_key"]]["rows"]
    )
    if observed_rows != expected_rows:
        raise ValueError(
            f"{source_name} row count changed: {observed_rows} != {expected_rows}."
        )
    result = (
        pd.concat(retained_chunks, ignore_index=True)
        if retained_chunks
        else pd.DataFrame(columns=usecols)
    )
    del retained_chunks
    gc.collect()
    print(
        f"Completed {source_name}: {observed_rows:,} rows scanned; "
        f"{len(result):,} retained"
    )
    return result


DIRECT_EVIDENCE_SOURCES = {
    source_name: direct_source_union(source_name)
    for source_name in DIRECT_SOURCE_SPECS
}

UNCERTAINTY_SOURCE_COLUMNS = [
    "uncertainty_metric_id",
    "uncertainty_group_id",
    "candidate_id",
    "candidate_id_a",
    "candidate_id_b",
    "case_id",
    "painting_id",
    "model_id",
    "experiment_id",
    "prompt_variant_id",
    "metric_name",
    "region_id",
    "summary_statistic",
    "value",
    "status",
]
CANONICAL_UNCERTAINTY_SOURCE = read_declared_csv(
    "uncertainty_metrics_path", UNCERTAINTY_SOURCE_COLUMNS
)
DAMAGE_SIZE_UNCERTAINTY_SOURCE = read_declared_csv(
    "damage_size_uncertainty_path", UNCERTAINTY_SOURCE_COLUMNS
)

FULL_THRESHOLD_EVIDENCE = normalise_failure_evidence(
    DIRECT_EVIDENCE_SOURCES,
    THRESHOLD_CANDIDATE_POPULATION,
    CANONICAL_UNCERTAINTY_SOURCE,
    DAMAGE_SIZE_UNCERTAINTY_SOURCE,
    config=FAILURE_CONFIG,
)
N27_THRESHOLD_SOURCE = calibrate_operational_thresholds(
    FULL_THRESHOLD_EVIDENCE,
    THRESHOLD_CANDIDATE_POPULATION,
    config=FAILURE_CONFIG,
)
if len(N27_THRESHOLD_SOURCE) != 137:
    raise ValueError(
        "N27 threshold reconstruction must produce 137 strata; "
        f"observed {len(N27_THRESHOLD_SOURCE)}."
    )

EVIDENCE_WITH_FIT_FLAGS = FULL_THRESHOLD_EVIDENCE.merge(
    THRESHOLD_CANDIDATE_POPULATION[
        ["candidate_id", "quality_analysis_eligible", "is_zero_control"]
    ],
    on="candidate_id",
    how="left",
    validate="many_to_one",
)


def threshold_fitting_rows(threshold_row) -> pd.DataFrame:
    indicator_rows = EVIDENCE_WITH_FIT_FLAGS.loc[
        EVIDENCE_WITH_FIT_FLAGS["indicator_id"]
        .astype(str)
        .eq(str(threshold_row.indicator_id))
    ].copy()
    is_uncertainty = indicator_rows["source"].astype(str).eq("uncertainty").all()
    minimum = int(THRESHOLD_POLICY["minimum_fitting_candidates"])
    if is_uncertainty:
        fitting = indicator_rows.drop_duplicates(
            ["uncertainty_group_id", "indicator_id"]
        )
        subset = fitting.loc[
            fitting["experiment_id"].astype(str).eq(str(threshold_row.experiment_id))
            & fitting["prompt_variant_id"]
            .astype(str)
            .eq(str(threshold_row.prompt_variant_id))
        ].copy()
        if len(subset) < minimum:
            subset = fitting.loc[
                fitting["prompt_variant_id"]
                .astype(str)
                .eq(str(threshold_row.prompt_variant_id))
            ].copy()
    else:
        fitting = indicator_rows.loc[
            indicator_rows["quality_analysis_eligible"].map(as_bool)
            & ~indicator_rows["is_zero_control"].map(as_bool)
            & ~indicator_rows["model_id"].astype(str).eq("sdxl_inpainting")
        ].copy()
        subset = fitting.loc[
            fitting["experiment_id"].astype(str).eq(str(threshold_row.experiment_id))
        ].copy()
        if len(subset) < minimum:
            subset = fitting.copy()
    return subset


THRESHOLD_SOURCE_MEMBERSHIPS = {}
for threshold_row in N27_THRESHOLD_SOURCE.itertuples(index=False):
    membership = threshold_fitting_rows(threshold_row)
    if len(membership) != int(threshold_row.n_fitting_candidates):
        raise ValueError(
            "Threshold fitting membership changed for "
            f"{threshold_row.threshold_id}: {len(membership)} != "
            f"{threshold_row.n_fitting_candidates}."
        )
    THRESHOLD_SOURCE_MEMBERSHIPS[str(threshold_row.threshold_id)] = sorted(
        membership["candidate_id"].astype(str).unique().tolist()
    )

THRESHOLD_ROWS = []
for threshold_row in N27_THRESHOLD_SOURCE.itertuples(index=False):
    indicator = INDICATOR_CONFIG[str(threshold_row.indicator_id)]
    threshold_mode = str(threshold_row.threshold_mode)
    direction = str(threshold_row.direction)
    if threshold_mode == "absolute_tolerance":
        warning_quantile = np.nan
        critical_quantile = np.nan
    elif direction == "higher_is_worse":
        warning_quantile = float(THRESHOLD_POLICY["warning_quantile"])
        critical_quantile = float(THRESHOLD_POLICY["critical_quantile"])
    else:
        warning_quantile = float(
            THRESHOLD_POLICY["lower_is_worse_warning_quantile"]
        )
        critical_quantile = float(
            THRESHOLD_POLICY["lower_is_worse_critical_quantile"]
        )
    source_candidates = THRESHOLD_SOURCE_MEMBERSHIPS[
        str(threshold_row.threshold_id)
    ]
    THRESHOLD_ROWS.append(
        {
            "threshold_stratum_id": str(threshold_row.threshold_id),
            "category_id": canonical_json_bytes(
                INDICATOR_CATEGORY_IDS[str(threshold_row.indicator_id)]
            ).decode("utf-8"),
            "indicator_id": str(threshold_row.indicator_id),
            "metric_name": str(indicator["metric_name"]),
            "region_id": str(threshold_row.region_id),
            "direction": direction,
            "warning_quantile": warning_quantile,
            "critical_quantile": critical_quantile,
            "warning_threshold": float(threshold_row.warning_threshold),
            "critical_threshold": float(threshold_row.critical_threshold),
            "fitting_population_count": int(threshold_row.n_fitting_candidates),
            "fallback_level": str(threshold_row.fitting_scope),
            "source_candidate_ids_sha256": hashlib.sha256(
                canonical_json_bytes(source_candidates)
            ).hexdigest(),
            "source_notebook_ids_json": canonical_json_bytes(
                str(indicator["source_notebook_id"]).split("|")
            ).decode("utf-8"),
            "schema_version": SETTINGS["expected_output_schemas"][
                "threshold_strata"
            ],
            "status": "ok",
            "issue": "",
        }
    )

THRESHOLD_STRATA = validate_output_frame(
    pd.DataFrame(THRESHOLD_ROWS), "threshold_strata"
).sort_values(
    ["indicator_id", "threshold_stratum_id"], kind="stable"
).reset_index(drop=True)

del DIRECT_EVIDENCE_SOURCES
del FULL_THRESHOLD_EVIDENCE
del EVIDENCE_WITH_FIT_FLAGS
gc.collect()

print("N27 threshold strata reconstructed.")
print("Threshold rows:", len(THRESHOLD_STRATA))
print("Indicators:", THRESHOLD_STRATA["indicator_id"].nunique())
print(
    "Fitting-population range:",
    int(THRESHOLD_STRATA["fitting_population_count"].min()),
    "to",
    int(THRESHOLD_STRATA["fitting_population_count"].max()),
)

Scanning classical threshold evidence ...
  classical: 477,753 rows scanned; 37,032 retained
Completed classical: 477,753 rows scanned; 37,032 retained
Scanning perceptual threshold evidence ...
Completed perceptual: 31,608 rows scanned; 11,944 retained
Scanning feature threshold evidence ...
Completed feature: 63,216 rows scanned; 23,888 retained
Scanning spatial threshold evidence ...
Completed spatial: 143,247 rows scanned; 25,088 retained
Scanning local threshold evidence ...
  local: 500,000 rows scanned; 55,192 retained
  local: 1,000,000 rows scanned; 110,953 retained
  local: 1,500,000 rows scanned; 162,080 retained
  local: 2,000,000 rows scanned; 173,510 retained
Completed local: 2,060,667 rows scanned; 180,450 retained
Scanning semantic threshold evidence ...
  semantic: 447,312 rows scanned; 89,608 retained
Completed semantic: 447,312 rows scanned; 89,608 retained
N27 threshold strata reconstructed.
Threshold rows: 137
Indicators: 36
Fitting-population range: 245 to 6000

In [25]:
DAMAGE_TRAJECTORY_SOURCE = read_declared_csv(
    "damage_size_analysis_path",
    [
        "analysis_row_id",
        "analysis_kind",
        "analysis_family_id",
        "source_metric_ids_json",
        "metric_name",
        "region_id",
        "value_unit",
        "model_id",
        "painting_id",
        "status",
    ],
)

TRAJECTORY_LINEAGE_ROWS = DAMAGE_TRAJECTORY_SOURCE.loc[
    DAMAGE_TRAJECTORY_SOURCE["analysis_row_id"]
    .astype(str)
    .eq("dsa_527855f8f9ddbd91251d")
].reset_index(drop=True)
if len(TRAJECTORY_LINEAGE_ROWS) != 1:
    raise ValueError("The approved N23 p018 trajectory lineage row changed.")
TRAJECTORY_LINEAGE = TRAJECTORY_LINEAGE_ROWS.iloc[0]

EXPECTED_SPATIAL_IDS = {
    str(value).removesuffix("__restored_error_mean")
    for value in json.loads(str(TRAJECTORY_LINEAGE["source_metric_ids_json"]))
}

SPATIAL_TRAJECTORY_SOURCE = read_declared_csv(
    "spatial_diagnostics_path",
    [
        "spatial_diagnostic_id",
        "case_id",
        "candidate_id",
        "painting_id",
        "model_id",
        "experiment_id",
        "prompt_variant_id",
        "region_id",
        "restored_error_mean",
        "status",
    ],
)
SPATIAL_TRAJECTORY_SOURCE = SPATIAL_TRAJECTORY_SOURCE.loc[
    SPATIAL_TRAJECTORY_SOURCE["spatial_diagnostic_id"]
    .astype(str)
    .isin(EXPECTED_SPATIAL_IDS)
].copy()
if len(SPATIAL_TRAJECTORY_SOURCE) != 7:
    raise ValueError("The approved p018 stability trajectory must contain 7 rows.")

SPATIAL_TRAJECTORY_SOURCE = (
    SPATIAL_TRAJECTORY_SOURCE.merge(
        CASE_INDEX[["case_id", "target_damage_fraction"]],
        on="case_id",
        how="left",
        validate="one_to_one",
    )
    .assign(
        target_damage_fraction=lambda frame: pd.to_numeric(
            frame["target_damage_fraction"], errors="raise"
        ),
        restored_error_mean=lambda frame: pd.to_numeric(
            frame["restored_error_mean"], errors="raise"
        ),
    )
    .sort_values("target_damage_fraction")
    .reset_index(drop=True)
)

STABILITY_ROWS = []
for condition_order, row in enumerate(
    SPATIAL_TRAJECTORY_SOURCE.itertuples(index=False), start=1
):
    STABILITY_ROWS.append(
        {
            "trajectory_id": stable_id(
                "stability_trajectory",
                "dsa_527855f8f9ddbd91251d",
                row.spatial_diagnostic_id,
            ),
            "painting_id": str(row.painting_id),
            "model_id": str(row.model_id),
            "experiment_id": str(row.experiment_id),
            "analysis_family_id": str(TRAJECTORY_LINEAGE["analysis_family_id"]),
            "metric_name": "restored_error_mean",
            "region_id": str(row.region_id),
            "condition_value": float(row.target_damage_fraction),
            "condition_order": condition_order,
            "estimate": float(row.restored_error_mean),
            "value_unit": str(TRAJECTORY_LINEAGE["value_unit"]),
            "case_id": str(row.case_id),
            "candidate_id": str(row.candidate_id),
            "source_row_id": str(row.spatial_diagnostic_id),
            "source_notebook_ids_json": canonical_json_bytes(["16", "23"]).decode(
                "utf-8"
            ),
            "schema_version": SETTINGS["expected_output_schemas"][
                "stability_trajectories"
            ],
            "status": "ok",
            "issue": "",
        }
    )

STABILITY_TRAJECTORIES = validate_output_frame(
    pd.DataFrame(STABILITY_ROWS), "stability_trajectories"
).sort_values("condition_order").reset_index(drop=True)

print("Governed p018 stability trajectory constructed.")
print("Trajectory points:", len(STABILITY_TRAJECTORIES))
print("Condition fractions:", STABILITY_TRAJECTORIES["condition_value"].tolist())
print("N23 lineage row:", str(TRAJECTORY_LINEAGE["analysis_row_id"]))

Governed p018 stability trajectory constructed.
Trajectory points: 7
Condition fractions: [0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2]
N23 lineage row: dsa_527855f8f9ddbd91251d

In [26]:
import base64
import io


D02_REPORT_PATH = PROJECT_ROOT / SETTINGS["inputs"]["d02_report_path"]
D02_REPORT_HTML = D02_REPORT_PATH.read_text(encoding="utf-8")


def read_embedded_d02_csv(filename: str) -> pd.DataFrame:
    """Decode one exact CSV from the frozen self-contained D02 report."""

    marker_offset = D02_REPORT_HTML.find(f'download="{filename}"')
    if marker_offset < 0:
        raise KeyError(f"D02 report does not contain {filename}.")
    payload_offset = D02_REPORT_HTML.find("base64,", marker_offset)
    if payload_offset < 0:
        raise ValueError(f"D02 report has no base64 payload for {filename}.")
    payload_offset += len("base64,")
    payload_end = D02_REPORT_HTML.find('"', payload_offset)
    decoded = base64.b64decode(
        D02_REPORT_HTML[payload_offset:payload_end], validate=True
    ).decode("utf-8")
    return pd.read_csv(io.StringIO(decoded))


D02_HAND_INFERENCE_SOURCE = read_embedded_d02_csv("hand_inference.csv")
D02_LIGHTNESS_ASSOCIATION_SOURCE = read_embedded_d02_csv(
    "skin_lightness_associations.csv"
)
D02_HAND_RAW_SOURCE = read_declared_csv(
    "d02_hand_comparison_path",
    [
        "comparison_id",
        "case_id",
        "painting_id",
        "candidate_id",
        "model_id",
        "is_primary_comparison_candidate",
        "metric_name",
        "status",
    ],
)
D02_LIGHTNESS_RAW_SOURCE = read_declared_csv(
    "d02_lightness_path",
    [
        "skin_metric_id",
        "case_id",
        "painting_id",
        "candidate_id",
        "model_id",
        "is_primary_comparison_candidate",
        "metric_name",
        "status",
    ],
)


def d02_primary_rows(frame: pd.DataFrame) -> pd.DataFrame:
    return frame.loc[
        frame["model_id"].astype(str).isin(FULL_SCOPE_MODEL_IDS)
        & (
            frame["is_primary_comparison_candidate"].map(as_bool)
            | frame["model_id"].astype(str).eq("stable_diffusion_inpainting")
        )
        & frame["status"].astype(str).eq("ok")
    ].copy()


D02_HAND_PRIMARY_SOURCE = d02_primary_rows(D02_HAND_RAW_SOURCE)
D02_LIGHTNESS_PRIMARY_SOURCE = d02_primary_rows(D02_LIGHTNESS_RAW_SOURCE)

HAND_SOURCE_LOOKUP = {
    (str(model_id), str(metric_name)): {
        "case_count": int(subset["case_id"].nunique()),
        "painting_count": int(subset["painting_id"].nunique()),
        "source_row_ids": sorted(
            subset["comparison_id"].astype(str).unique().tolist()
        ),
    }
    for (model_id, metric_name), subset in D02_HAND_PRIMARY_SOURCE.groupby(
        ["model_id", "metric_name"], sort=True
    )
}
LIGHTNESS_SOURCE_LOOKUP = {
    (str(model_id), str(metric_name)): {
        "eligible_record_count": int(subset["case_id"].nunique()),
        "painting_count": int(subset["painting_id"].nunique()),
        "source_row_ids": sorted(
            subset["skin_metric_id"].astype(str).unique().tolist()
        ),
    }
    for (model_id, metric_name), subset in D02_LIGHTNESS_PRIMARY_SOURCE.groupby(
        ["model_id", "metric_name"], sort=True
    )
}

D02_HAND_SUMMARY_ROWS = []
for row in D02_HAND_INFERENCE_SOURCE.itertuples(index=False):
    source = HAND_SOURCE_LOOKUP[(str(row.model_id), str(row.metric_name))]
    D02_HAND_SUMMARY_ROWS.append(
        {
            "summary_id": str(row.analysis_id),
            "record_type": "primary_hand_penalty",
            "model_id": str(row.model_id),
            "metric_name": str(row.metric_name),
            "estimate": float(row.mean_hand_worse_difference),
            "interval_low": float(row.ci_lower),
            "interval_high": float(row.ci_upper),
            "p_value": float(row.sign_flip_p_value),
            "q_value": float(row.bh_adjusted_p_value),
            "matched_case_count": source["case_count"],
            "painting_count": int(row.painting_count),
            "review_unit_count": int(POPULATION["d02_blind_review_unit_count"]),
            "interpretation": (
                "Positive means restoration error was larger on damaged hand "
                "pixels than on matched non-hand pixels."
            ),
            "limitation": (
                "This is a controlled matched-region result, not a claim about "
                "anatomy generally or conservation correctness."
            ),
            "source_row_ids_json": canonical_json_bytes(
                source["source_row_ids"]
            ).decode("utf-8"),
            "schema_version": SETTINGS["expected_output_schemas"][
                "d02_hand_summary"
            ],
            "status": "ok",
            "issue": "",
        }
    )
D02_HAND_SUMMARY = validate_output_frame(
    pd.DataFrame(D02_HAND_SUMMARY_ROWS), "d02_hand_summary"
).sort_values(["model_id", "metric_name"], kind="stable").reset_index(drop=True)

D02_LIGHTNESS_SUMMARY_ROWS = []
for row in D02_LIGHTNESS_ASSOCIATION_SOURCE.itertuples(index=False):
    source = LIGHTNESS_SOURCE_LOOKUP[(str(row.model_id), str(row.metric_name))]
    interval_low = float(row.ci_lower)
    interval_high = float(row.ci_upper)
    association_state = (
        "positive"
        if interval_low > 0
        else "negative"
        if interval_high < 0
        else "interval_crosses_zero"
    )
    D02_LIGHTNESS_SUMMARY_ROWS.append(
        {
            "summary_id": stable_id(
                "d02_lightness", str(row.model_id), str(row.metric_name)
            ),
            "model_id": str(row.model_id),
            "metric_name": str(row.metric_name),
            "coefficient": float(row.standardized_lstar_coefficient),
            "interval_low": interval_low,
            "interval_high": interval_high,
            "p_value": pd.NA,
            "q_value": pd.NA,
            "association_state": association_state,
            "eligible_record_count": source["eligible_record_count"],
            "painting_count": int(row.painting_count),
            "interpretation": (
                "Positive means oriented restoration error rises as rendered "
                "skin-region lightness rises after declared image-context adjustments."
            ),
            "limitation": (
                "Rendered lightness is an image measurement, not race, ethnicity "
                "or identity; this exploratory association cannot establish "
                "demographic bias."
            ),
            "source_row_ids_json": canonical_json_bytes(
                source["source_row_ids"]
            ).decode("utf-8"),
            "schema_version": SETTINGS["expected_output_schemas"][
                "d02_lightness_summary"
            ],
            "status": "ok",
            "issue": "",
        }
    )
D02_LIGHTNESS_SUMMARY = pd.DataFrame(D02_LIGHTNESS_SUMMARY_ROWS)
for column in ["p_value", "q_value"]:
    D02_LIGHTNESS_SUMMARY[column] = pd.array(
        [pd.NA] * len(D02_LIGHTNESS_SUMMARY), dtype="Float64"
    )
D02_LIGHTNESS_SUMMARY = validate_output_frame(
    D02_LIGHTNESS_SUMMARY, "d02_lightness_summary"
).sort_values(["model_id", "metric_name"], kind="stable").reset_index(drop=True)

print("Exact D02 dashboard summaries constructed.")
print("Hand-summary rows:", len(D02_HAND_SUMMARY))
print("Hand source cases:", sorted(D02_HAND_SUMMARY["matched_case_count"].unique()))
print("Hand estimates above zero:", int(D02_HAND_SUMMARY["estimate"].gt(0).sum()))
print("Hand BH q-values <= 0.05:", int(D02_HAND_SUMMARY["q_value"].le(0.05).sum()))
print("Lightness-summary rows:", len(D02_LIGHTNESS_SUMMARY))
print(
    "Lightness eligible records:",
    sorted(D02_LIGHTNESS_SUMMARY["eligible_record_count"].unique()),
)
print(
    "Lightness association states:",
    D02_LIGHTNESS_SUMMARY["association_state"].value_counts().to_dict(),
)

Exact D02 dashboard summaries constructed.
Hand-summary rows: 12
Hand source cases: [45]
Hand estimates above zero: 12
Hand BH q-values <= 0.05: 10
Lightness-summary rows: 24
Lightness eligible records: [105]
Lightness association states: {'interval_crosses_zero': 21, 'negative': 3}

In [27]:
D02_HAND_CONTROL_DESIGN_SOURCE = read_embedded_d02_csv("hand_control_design.csv")
D02_MANUAL_FULL = read_declared_csv(
    "d02_manual_review_path",
    [
        "review_unit_id",
        "hand_control_id",
        "case_id",
        "painting_id",
        "damage_family",
        "annotation_id",
        "region_type",
        "candidate_id",
        "model_id",
        "seed",
        "clean_image_path",
        "damaged_image_path",
        "mask_path",
        "restored_path",
        "crop_x_min",
        "crop_y_min",
        "crop_x_max",
        "crop_y_max",
        "blind_review_code",
        "panel_path",
        "missing_digits",
        "duplicated_digits",
        "fused_digits",
        "contour_failure",
        "articulation_failure",
        "wrist_or_arm_discontinuity",
        "non_anatomical_texture",
        "overall_anatomy_failure",
        "reviewer_confidence",
        "review_notes",
        "review_status",
    ],
)
D02_OVERLAP_SOURCE = read_declared_csv(
    "d02_overlap_path",
    [
        "overlap_id",
        "case_id",
        "annotation_id",
        "anatomical_pixel_count",
        "damaged_anatomical_pixels",
        "anatomical_fraction_affected",
        "damage_fraction_inside_anatomy",
        "passes_overlap_thresholds",
        "status",
    ],
)

R005_REVIEW_ROWS = D02_MANUAL_FULL.loc[
    D02_MANUAL_FULL["blind_review_code"].astype(str).eq("R005")
].reset_index(drop=True)
if len(R005_REVIEW_ROWS) != 1:
    raise ValueError("R005 must resolve to exactly one frozen review row.")
R005_REVIEW = R005_REVIEW_ROWS.iloc[0]

R005_DESIGN_ROWS = D02_HAND_CONTROL_DESIGN_SOURCE.loc[
    D02_HAND_CONTROL_DESIGN_SOURCE["hand_control_id"]
    .astype(str)
    .eq(str(R005_REVIEW["hand_control_id"]))
].reset_index(drop=True)
if len(R005_DESIGN_ROWS) != 1:
    raise ValueError("R005 must resolve to exactly one control-design row.")
R005_DESIGN = R005_DESIGN_ROWS.iloc[0]

R005_OVERLAP_ROWS = D02_OVERLAP_SOURCE.loc[
    D02_OVERLAP_SOURCE["case_id"].astype(str).eq(str(R005_REVIEW["case_id"]))
    & D02_OVERLAP_SOURCE["annotation_id"]
    .astype(str)
    .eq(str(R005_REVIEW["annotation_id"]))
].reset_index(drop=True)
if len(R005_OVERLAP_ROWS) != 1:
    raise ValueError("R005 must resolve to exactly one anatomy-overlap row.")
R005_OVERLAP = R005_OVERLAP_ROWS.iloc[0]

R005_HAND_INDICES = [
    int(value) for value in json.loads(str(R005_DESIGN["hand_flat_indices_json"]))
]
R005_CONTROL_INDICES = [
    int(value)
    for value in json.loads(str(R005_DESIGN["control_flat_indices_json"]))
]
R005_REVIEW_XYXY = [
    int(R005_REVIEW["crop_x_min"]),
    int(R005_REVIEW["crop_y_min"]),
    int(R005_REVIEW["crop_x_max"]),
    int(R005_REVIEW["crop_y_max"]),
]
R005_CONTROL_XYXY = [
    int(R005_DESIGN["control_crop_x_min"]),
    int(R005_DESIGN["control_crop_y_min"]),
    int(R005_DESIGN["control_crop_x_max"]),
    int(R005_DESIGN["control_crop_y_max"]),
]

D02_R005_GEOMETRY = {
    "schema_version": SETTINGS["expected_output_schemas"]["d02_r005_geometry"],
    # Top-level aliases are the exact contract consumed by Batch 7.
    "painting_id": str(R005_REVIEW["painting_id"]),
    "case_id": str(R005_REVIEW["case_id"]),
    "candidate_id": str(R005_REVIEW["candidate_id"]),
    "model_id": str(R005_REVIEW["model_id"]),
    "annotation_id": str(R005_REVIEW["annotation_id"]),
    "hand_control_id": str(R005_REVIEW["hand_control_id"]),
    "review_unit_id": str(R005_REVIEW["review_unit_id"]),
    "blind_review_code": "R005",
    "review_crop_xyxy": R005_REVIEW_XYXY,
    "control_crop_xyxy": R005_CONTROL_XYXY,
    "control_flat_indices": R005_CONTROL_INDICES,
    "review": {
        "damage_family": str(R005_REVIEW["damage_family"]),
        "region_type": str(R005_REVIEW["region_type"]),
        "seed": int(R005_REVIEW["seed"]),
        "review_status": str(R005_REVIEW["review_status"]),
        "reviewer_confidence": str(R005_REVIEW["reviewer_confidence"]),
        "overall_anatomy_failure": as_bool(
            R005_REVIEW["overall_anatomy_failure"]
        ),
        "review_notes": str(R005_REVIEW["review_notes"]),
        "failure_observations": {
            field: as_bool(R005_REVIEW[field])
            for field in [
                "missing_digits",
                "duplicated_digits",
                "fused_digits",
                "contour_failure",
                "articulation_failure",
                "wrist_or_arm_discontinuity",
                "non_anatomical_texture",
            ]
        },
    },
    "source_assets": {
        key: str(R005_REVIEW[column]).replace("\\", "/")
        for key, column in {
            "clean_image_path": "clean_image_path",
            "damaged_image_path": "damaged_image_path",
            "mask_path": "mask_path",
            "restored_path": "restored_path",
            "producer_panel_path": "panel_path",
        }.items()
    },
    "hand_geometry": {
        "crop_xyxy": R005_REVIEW_XYXY,
        "pixel_count": len(R005_HAND_INDICES),
        "flat_indices": R005_HAND_INDICES,
        "gradient_mean": float(R005_DESIGN["hand_gradient_mean"]),
        "texture_mean": float(R005_DESIGN["hand_texture_mean"]),
        "boundary_depth_mean": float(R005_DESIGN["hand_boundary_depth_mean"]),
    },
    "matched_control_geometry": {
        "available": as_bool(R005_DESIGN["control_crop_available"]),
        "crop_xyxy": R005_CONTROL_XYXY,
        "pixel_count": len(R005_CONTROL_INDICES),
        "flat_indices": R005_CONTROL_INDICES,
        "gradient_mean": float(R005_DESIGN["control_gradient_mean"]),
        "texture_mean": float(R005_DESIGN["control_texture_mean"]),
        "boundary_depth_mean": float(
            R005_DESIGN["control_boundary_depth_mean"]
        ),
        "feature_match_score": float(R005_DESIGN["feature_match_score"]),
        "hand_control_overlap_pixels": int(
            R005_DESIGN["hand_control_overlap_pixels"]
        ),
    },
    "overlap_evidence": {
        "overlap_id": str(R005_OVERLAP["overlap_id"]),
        "anatomical_pixel_count": int(R005_OVERLAP["anatomical_pixel_count"]),
        "damaged_anatomical_pixels": int(
            R005_OVERLAP["damaged_anatomical_pixels"]
        ),
        "anatomical_fraction_affected": float(
            R005_OVERLAP["anatomical_fraction_affected"]
        ),
        "damage_fraction_inside_anatomy": float(
            R005_OVERLAP["damage_fraction_inside_anatomy"]
        ),
        "passes_overlap_thresholds": as_bool(
            R005_OVERLAP["passes_overlap_thresholds"]
        ),
    },
    "source_notebook_ids": ["D02"],
    "status": "ok",
    "issue": "",
}

print("Exact R005 geometry constructed.")
print("Review crop:", D02_R005_GEOMETRY["review_crop_xyxy"])
print("Control crop:", D02_R005_GEOMETRY["control_crop_xyxy"])
print("Hand/control pixels:", len(R005_HAND_INDICES), len(R005_CONTROL_INDICES))

Exact R005 geometry constructed.
Review crop: [617, 81, 716, 215]
Control crop: [605, 576, 704, 710]
Hand/control pixels: 1196 1196

In [28]:
STAGED_THRESHOLD_STRATA_PATH = (
    STAGING_PACKAGE_ROOT / SETTINGS["output"]["threshold_strata_path"]
)
STAGED_STABILITY_TRAJECTORIES_PATH = (
    STAGING_PACKAGE_ROOT / SETTINGS["output"]["stability_trajectories_path"]
)
STAGED_D02_HAND_SUMMARY_PATH = (
    STAGING_PACKAGE_ROOT / SETTINGS["output"]["d02_hand_summary_path"]
)
STAGED_D02_LIGHTNESS_SUMMARY_PATH = (
    STAGING_PACKAGE_ROOT / SETTINGS["output"]["d02_lightness_summary_path"]
)
STAGED_D02_R005_GEOMETRY_PATH = (
    STAGING_PACKAGE_ROOT / SETTINGS["output"]["d02_r005_geometry_path"]
)
STAGED_DERIVATIVE_PATHS = {
    "threshold_strata": STAGED_THRESHOLD_STRATA_PATH,
    "stability_trajectories": STAGED_STABILITY_TRAJECTORIES_PATH,
    "d02_hand_summary": STAGED_D02_HAND_SUMMARY_PATH,
    "d02_lightness_summary": STAGED_D02_LIGHTNESS_SUMMARY_PATH,
    "d02_r005_geometry": STAGED_D02_R005_GEOMETRY_PATH,
}

for frame, path in [
    (THRESHOLD_STRATA, STAGED_THRESHOLD_STRATA_PATH),
    (STABILITY_TRAJECTORIES, STAGED_STABILITY_TRAJECTORIES_PATH),
    (D02_HAND_SUMMARY, STAGED_D02_HAND_SUMMARY_PATH),
    (D02_LIGHTNESS_SUMMARY, STAGED_D02_LIGHTNESS_SUMMARY_PATH),
]:
    atomic_write_parquet(frame, path)
atomic_write_json(D02_R005_GEOMETRY, STAGED_D02_R005_GEOMETRY_PATH)

STAGED_THRESHOLD_STRATA = pd.read_parquet(STAGED_THRESHOLD_STRATA_PATH)
STAGED_STABILITY_TRAJECTORIES = pd.read_parquet(
    STAGED_STABILITY_TRAJECTORIES_PATH
)
STAGED_D02_HAND_SUMMARY = pd.read_parquet(STAGED_D02_HAND_SUMMARY_PATH)
STAGED_D02_LIGHTNESS_SUMMARY = pd.read_parquet(
    STAGED_D02_LIGHTNESS_SUMMARY_PATH
)
STAGED_D02_R005_GEOMETRY = json.loads(
    STAGED_D02_R005_GEOMETRY_PATH.read_text(encoding="utf-8")
)
BATCH_6_STAGED_READBACK = {
    "threshold_strata": STAGED_THRESHOLD_STRATA,
    "stability_trajectories": STAGED_STABILITY_TRAJECTORIES,
    "d02_hand_summary": STAGED_D02_HAND_SUMMARY,
    "d02_lightness_summary": STAGED_D02_LIGHTNESS_SUMMARY,
    "d02_r005_geometry": STAGED_D02_R005_GEOMETRY,
}
BATCH_6_STAGED_LEDGER = pd.DataFrame(
    [
        {
            "artifact_key": key,
            "relative_path": path.relative_to(STAGING_PACKAGE_ROOT).as_posix(),
            "size_bytes": path.stat().st_size,
            "sha256": sha256_file(path),
        }
        for key, path in STAGED_DERIVATIVE_PATHS.items()
    ]
).sort_values("artifact_key").reset_index(drop=True)

print("Batch 6 derivatives staged.")
print("Staged artifact count:", len(BATCH_6_STAGED_LEDGER))
print("Staged bytes:", int(BATCH_6_STAGED_LEDGER["size_bytes"].sum()))
print("Canonical package has not been promoted.")

Batch 6 derivatives staged.
Staged artifact count: 5
Staged bytes: 164945
Canonical package has not been promoted.

In [29]:
BATCH_6_STAGE = "batch_6_governed_derivatives"
VALIDATION_ROWS[:] = [
    row
    for row in VALIDATION_ROWS
    if row["validation_stage"] != BATCH_6_STAGE
]


def parquet_readback_matches(expected: pd.DataFrame, observed: pd.DataFrame) -> bool:
    try:
        pd.testing.assert_frame_equal(
            expected.reset_index(drop=True),
            observed.reset_index(drop=True),
            check_dtype=False,
            check_like=False,
        )
        return True
    except AssertionError:
        return False


BATCH_6_RESPONSIBILITIES = [
    responsibility
    for responsibility in SETTINGS["responsibilities"]
    if int(responsibility["batch"]) == 6
]
EXPECTED_BATCH_6_RESPONSIBILITIES = [
    {
        "responsibility_id": "R06",
        "batch": 6,
        "name": "threshold_strata",
        "blocking": True,
    },
    {
        "responsibility_id": "R07",
        "batch": 6,
        "name": "stability_derivatives",
        "blocking": True,
    },
    {
        "responsibility_id": "R08",
        "batch": 6,
        "name": "d02_derivatives",
        "blocking": True,
    },
]
EXPECTED_STABILITY_CONDITIONS = [0.02, 0.04, 0.06, 0.08, 0.10, 0.15, 0.20]
EXPECTED_STABILITY_ESTIMATES = [
    4.131869543789593,
    6.306795077463597,
    9.64656364888671,
    9.533782770674836,
    13.20042974218237,
    30.98691344826743,
    39.330170144533845,
]
OBSERVED_STABILITY = STABILITY_TRAJECTORIES.sort_values(
    "condition_order"
).reset_index(drop=True)
OBSERVED_LIGHTNESS_STATES = (
    D02_LIGHTNESS_SUMMARY["association_state"]
    .value_counts()
    .sort_index()
    .astype(int)
    .to_dict()
)
EXPECTED_STAGED_DERIVATIVE_PATHS = {
    (
        STAGING_PACKAGE_ROOT / SETTINGS["output"][key]
    ).resolve()
    for key in [
        "threshold_strata_path",
        "stability_trajectories_path",
        "d02_hand_summary_path",
        "d02_lightness_summary_path",
        "d02_r005_geometry_path",
    ]
}
OBSERVED_STAGED_DERIVATIVE_PATHS = {
    path.resolve() for path in STAGED_DERIVATIVE_PATHS.values() if path.is_file()
}
CANONICAL_OUTPUT_FILES_AFTER_BATCH_6 = [
    path
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
    and OUTPUT_PATHS["work_dir"].resolve() not in path.resolve().parents
]

BATCH_6_CHECKS = [
    (
        "responsibility_contract",
        BATCH_6_RESPONSIBILITIES,
        EXPECTED_BATCH_6_RESPONSIBILITIES,
    ),
    (
        "threshold_schema",
        list(THRESHOLD_STRATA.columns),
        list(OUTPUT_SCHEMAS["threshold_strata"]),
    ),
    ("threshold_rows", len(THRESHOLD_STRATA), 137),
    ("threshold_indicator_count", THRESHOLD_STRATA["indicator_id"].nunique(), 36),
    (
        "threshold_id_uniqueness",
        THRESHOLD_STRATA["threshold_stratum_id"].nunique(),
        len(THRESHOLD_STRATA),
    ),
    (
        "threshold_category_sets_parse",
        bool(
            THRESHOLD_STRATA["category_id"].map(
                lambda value: isinstance(json.loads(str(value)), list)
                and json.loads(str(value)) == sorted(json.loads(str(value)))
            ).all()
        ),
        True,
    ),
    (
        "threshold_values_complete",
        bool(
            THRESHOLD_STRATA[["warning_threshold", "critical_threshold"]]
            .notna()
            .all()
            .all()
        ),
        True,
    ),
    (
        "threshold_source_hashes",
        bool(
            THRESHOLD_STRATA["source_candidate_ids_sha256"]
            .astype(str)
            .str.fullmatch(r"[0-9a-f]{64}")
            .all()
        ),
        True,
    ),
    (
        "stability_schema",
        list(STABILITY_TRAJECTORIES.columns),
        list(OUTPUT_SCHEMAS["stability_trajectories"]),
    ),
    ("stability_rows", len(STABILITY_TRAJECTORIES), 7),
    (
        "stability_identity",
        {
            "painting_ids": sorted(STABILITY_TRAJECTORIES["painting_id"].unique()),
            "model_ids": sorted(STABILITY_TRAJECTORIES["model_id"].unique()),
            "experiment_ids": sorted(
                STABILITY_TRAJECTORIES["experiment_id"].unique()
            ),
            "metric_names": sorted(STABILITY_TRAJECTORIES["metric_name"].unique()),
            "region_ids": sorted(STABILITY_TRAJECTORIES["region_id"].unique()),
        },
        {
            "painting_ids": ["p018"],
            "model_ids": ["lama"],
            "experiment_ids": ["damage_size_sensitivity"],
            "metric_names": ["restored_error_mean"],
            "region_ids": ["masked_region"],
        },
    ),
    (
        "stability_conditions",
        OBSERVED_STABILITY["condition_value"].astype(float).tolist(),
        EXPECTED_STABILITY_CONDITIONS,
    ),
    (
        "stability_estimates",
        bool(
            np.allclose(
                OBSERVED_STABILITY["estimate"].astype(float),
                EXPECTED_STABILITY_ESTIMATES,
                rtol=0.0,
                atol=1e-12,
            )
        ),
        True,
    ),
    (
        "d02_hand_schema",
        list(D02_HAND_SUMMARY.columns),
        list(OUTPUT_SCHEMAS["d02_hand_summary"]),
    ),
    ("d02_hand_rows", len(D02_HAND_SUMMARY), 12),
    (
        "d02_hand_source_cases",
        sorted(D02_HAND_SUMMARY["matched_case_count"].unique().tolist()),
        [45],
    ),
    ("d02_hand_positive_estimates", int(D02_HAND_SUMMARY["estimate"].gt(0).sum()), 12),
    ("d02_hand_bh_significant", int(D02_HAND_SUMMARY["q_value"].le(0.05).sum()), 10),
    (
        "d02_lightness_schema",
        list(D02_LIGHTNESS_SUMMARY.columns),
        list(OUTPUT_SCHEMAS["d02_lightness_summary"]),
    ),
    ("d02_lightness_rows", len(D02_LIGHTNESS_SUMMARY), 24),
    (
        "d02_lightness_eligible_records",
        sorted(D02_LIGHTNESS_SUMMARY["eligible_record_count"].unique().tolist()),
        [105],
    ),
    (
        "d02_lightness_nullable_tests",
        {
            "p_null": int(D02_LIGHTNESS_SUMMARY["p_value"].isna().sum()),
            "q_null": int(D02_LIGHTNESS_SUMMARY["q_value"].isna().sum()),
        },
        {"p_null": 24, "q_null": 24},
    ),
    (
        "d02_lightness_states",
        OBSERVED_LIGHTNESS_STATES,
        {"interval_crosses_zero": 21, "negative": 3},
    ),
    (
        "r005_batch7_top_level_contract",
        {
            "painting_id": D02_R005_GEOMETRY["painting_id"],
            "case_id": D02_R005_GEOMETRY["case_id"],
            "candidate_id": D02_R005_GEOMETRY["candidate_id"],
            "model_id": D02_R005_GEOMETRY["model_id"],
            "annotation_id": D02_R005_GEOMETRY["annotation_id"],
            "hand_control_id": D02_R005_GEOMETRY["hand_control_id"],
            "review_unit_id": D02_R005_GEOMETRY["review_unit_id"],
            "blind_review_code": D02_R005_GEOMETRY["blind_review_code"],
            "review_crop_xyxy": D02_R005_GEOMETRY["review_crop_xyxy"],
            "control_index_count": len(D02_R005_GEOMETRY["control_flat_indices"]),
        },
        {
            "painting_id": "p269",
            "case_id": "canonical__p269__mixed_damage",
            "candidate_id": (
                "candidate__hint_places2__canonical__p269__mixed_damage__c00"
            ),
            "model_id": "hint_places2",
            "annotation_id": "anatomy_7726c759861cf33baba7",
            "hand_control_id": "hand_control_43e40122b45c717bc8b6",
            "review_unit_id": "anatomy_review_813d89c1fcfdc670b64a",
            "blind_review_code": "R005",
            "review_crop_xyxy": [617, 81, 716, 215],
            "control_index_count": 1196,
        },
    ),
    (
        "r005_hand_control_counts",
        {
            "hand": D02_R005_GEOMETRY["hand_geometry"]["pixel_count"],
            "control": D02_R005_GEOMETRY["matched_control_geometry"][
                "pixel_count"
            ],
        },
        {"hand": 1196, "control": 1196},
    ),
    (
        "r005_geometry_disjoint",
        len(set(R005_HAND_INDICES) & set(R005_CONTROL_INDICES)),
        0,
    ),
    (
        "staged_derivative_exact_set",
        OBSERVED_STAGED_DERIVATIVE_PATHS,
        EXPECTED_STAGED_DERIVATIVE_PATHS,
    ),
    (
        "threshold_readback",
        parquet_readback_matches(THRESHOLD_STRATA, STAGED_THRESHOLD_STRATA),
        True,
    ),
    (
        "stability_readback",
        parquet_readback_matches(
            STABILITY_TRAJECTORIES, STAGED_STABILITY_TRAJECTORIES
        ),
        True,
    ),
    (
        "d02_hand_readback",
        parquet_readback_matches(D02_HAND_SUMMARY, STAGED_D02_HAND_SUMMARY),
        True,
    ),
    (
        "d02_lightness_readback",
        parquet_readback_matches(
            D02_LIGHTNESS_SUMMARY, STAGED_D02_LIGHTNESS_SUMMARY
        ),
        True,
    ),
    ("r005_json_readback", STAGED_D02_R005_GEOMETRY, D02_R005_GEOMETRY),
    ("canonical_files_promoted", len(CANONICAL_OUTPUT_FILES_AFTER_BATCH_6), 0),
]

for check_name, observed, expected in BATCH_6_CHECKS:
    add_check(
        BATCH_6_STAGE,
        check_name,
        observed,
        expected,
        observed == expected,
        (
            ""
            if observed == expected
            else "Batch 6 differs from the approved governed-derivative contract."
        ),
    )

require_no_blocking_failures("Batch 6 governed derivatives")
BATCH_6_VALIDATION = current_validation_frame().loc[
    lambda frame: frame["validation_stage"].eq(BATCH_6_STAGE)
].reset_index(drop=True)

display(BATCH_6_STAGED_LEDGER)
display(
    BATCH_6_VALIDATION[
        ["check_description", "severity", "passed", "observed"]
    ]
)
print("Batch 6 governed derivatives passed.")
print("Threshold strata:", len(THRESHOLD_STRATA))
print("Stability trajectory points:", len(STABILITY_TRAJECTORIES))
print("D02 hand summaries:", len(D02_HAND_SUMMARY))
print("D02 rendered-lightness summaries:", len(D02_LIGHTNESS_SUMMARY))
print("R005 hand/control pixels:", len(R005_HAND_INDICES), len(R005_CONTROL_INDICES))
print("Staged derivative artifacts: 5")
print("Canonical files promoted: 0")

,artifact_key,relative_path,size_bytes,sha256
0,d02_hand_summary,data/derived/d02_hand_summary.parquet,27943,20b1de39c6e2020b974ce3ef5116e7509a592e0c1d9240...
1,d02_lightness_summary,data/derived/d02_lightness_summary.parquet,57136,b5938d4b8bf7ff15cfde9b13204f396c27bf6065eac87f...
2,d02_r005_geometry,data/derived/d02_r005_geometry.json,49528,b246be59b3848e61b8883dc39ec2144f49f147beda28d1...
3,stability_trajectories,data/derived/stability_trajectories.parquet,12511,69eb6bb4d7f19e9a88809aff4639554d956da4cae1f26f...
4,threshold_strata,data/derived/threshold_strata.parquet,17827,a1f9ee199254be283d8070da9283a30f9240f8d3d6b3dd...

,check_description,severity,passed,observed
0,responsibility_contract,blocking,True,"[{""batch"": 6, ""blocking"": true, ""name"": ""thres..."
1,threshold_schema,blocking,True,"[""threshold_stratum_id"", ""category_id"", ""indic..."
2,threshold_rows,blocking,True,137
3,threshold_indicator_count,blocking,True,36
4,threshold_id_uniqueness,blocking,True,137
5,threshold_category_sets_parse,blocking,True,True
6,threshold_values_complete,blocking,True,True
7,threshold_source_hashes,blocking,True,True
8,stability_schema,blocking,True,"[""trajectory_id"", ""painting_id"", ""model_id"", ""..."
9,stability_rows,blocking,True,7
10,stability_identity,blocking,True,"{""experiment_ids"": [""damage_size_sensitivity""]..."
11,stability_conditions,blocking,True,"[0.02, 0.04, 0.06, 0.08, 0.1, 0.15, 0.2]"
12,stability_estimates,blocking,True,True
13,d02_hand_schema,blocking,True,"[""summary_id"", ""record_type"", ""model_id"", ""met..."
14,d02_hand_rows,blocking,True,12
15,d02_hand_source_cases,blocking,True,[45]
16,d02_hand_positive_estimates,blocking,True,12
17,d02_hand_bh_significant,blocking,True,10
18,d02_lightness_schema,blocking,True,"[""summary_id"", ""model_id"", ""metric_name"", ""coe..."
19,d02_lightness_rows,blocking,True,24
20,d02_lightness_eligible_records,blocking,True,[105]
21,d02_lightness_nullable_tests,blocking,True,"{""p_null"": 24, ""q_null"": 24}"
22,d02_lightness_states,blocking,True,"{""interval_crosses_zero"": 21, ""negative"": 3}"
23,r005_batch7_top_level_contract,blocking,True,"{""annotation_id"": ""anatomy_7726c759861cf33baba..."
24,r005_hand_control_counts,blocking,True,"{""control"": 1196, ""hand"": 1196}"
25,r005_geometry_disjoint,blocking,True,0
26,staged_derivative_exact_set,blocking,True,"""{WindowsPath('D:/Masters/FH/Thesis/painting-r..."
27,threshold_readback,blocking,True,True
28,stability_readback,blocking,True,True
29,d02_hand_readback,blocking,True,True
30,d02_lightness_readback,blocking,True,True
31,r005_json_readback,blocking,True,"{""annotation_id"": ""anatomy_7726c759861cf33baba..."
32,canonical_files_promoted,blocking,True,0

Batch 6 governed derivatives passed.
Threshold strata: 137
Stability trajectory points: 7
D02 hand summaries: 12
D02 rendered-lightness summaries: 24
R005 hand/control pixels: 1196 1196
Staged derivative artifacts: 5
Canonical files promoted: 0

## Batch 7 — Registered renditions and immutable locators (R09 + R10)

This batch renders only evidence-backed local web renditions and compiles
immutable source routes from the frozen Git, individual-publication, and
indexed-bundle records. It performs no network access and writes only below
the release staging root. Approved mock-up rasters remain visual references;
they are never registered as scientific evidence or used as backgrounds.

In [31]:
import hashlib
import io
import re
import subprocess
from pathlib import PurePosixPath
from urllib.parse import quote

from PIL import Image, ImageChops, ImageDraw, ImageOps

from restoration_eval.dashboard_assets import (
    asset_id,
    atomic_write_bytes,
    atomic_write_csv,
    atomic_write_parquet,
    canonical_json_bytes,
    is_full_git_revision,
    is_sha256,
    locator_id,
    stable_id,
    validate_output_frame,
)


BATCH_7_STAGE = "batch_7_r09_r10_renditions_and_locators"
BATCH_7_RESPONSIBILITY_IDS = ("R09", "R10")

configured_responsibilities = {
    str(row["responsibility_id"]): row
    for row in SETTINGS["responsibilities"]
}
for responsibility_id in BATCH_7_RESPONSIBILITY_IDS:
    if responsibility_id not in configured_responsibilities:
        raise ValueError(
            f"Missing configured responsibility {responsibility_id}."
        )

VALIDATION_ROWS[:] = [
    row
    for row in VALIDATION_ROWS
    if row["validation_stage"] != BATCH_7_STAGE
]

PROFILE_RULES = {
    "thumb": {
        "max_edge": 320,
        "hard_bytes": int(
            SETTINGS["runtime_budgets"]["thumb_hard_bytes"]
        ),
        "breakpoint_role": "route_preview",
    },
    "standard": {
        "max_edge": 640,
        "hard_bytes": int(
            SETTINGS["runtime_budgets"]["standard_hard_bytes"]
        ),
        "breakpoint_role": "primary_panel",
    },
    "diagnostic_preview": {
        "max_edge": 640,
        "hard_bytes": int(
            SETTINGS["runtime_budgets"]["diagnostic_preview_hard_bytes"]
        ),
        "breakpoint_role": "diagnostic_panel",
    },
}

IDENTITY_FIELDS = (
    "painting_id",
    "case_id",
    "candidate_id",
    "model_id",
    "experiment_id",
    "seed",
    "prompt_variant_id",
    "uncertainty_group_id",
    "metric_name",
    "region_id",
    "evidence_layer",
    "annotation_id",
    "hand_control_id",
    "review_unit_id",
    "blind_review_code",
)


def canonical_text(value) -> str:
    return canonical_json_bytes(value).decode("utf-8")


def canonical_identity(**updates) -> dict:
    identity = {field: None for field in IDENTITY_FIELDS}
    unknown = sorted(set(updates) - set(identity))
    if unknown:
        raise KeyError(f"Unknown identity fields: {unknown}")
    identity.update(updates)
    return identity


def checked_repo_path(relative_path: str) -> Path:
    relative = PurePosixPath(str(relative_path))
    if (
        relative.is_absolute()
        or not relative.parts
        or any(part in {"", ".", ".."} for part in relative.parts)
    ):
        raise ValueError(f"Unsafe repository path: {relative_path!r}")
    path = (PROJECT_ROOT / Path(*relative.parts)).resolve()
    if not path.is_relative_to(PROJECT_ROOT) or not path.is_file():
        raise FileNotFoundError(relative_path)
    return path


def producer_id_for_path(relative_path: str) -> str:
    match = re.match(r"^outputs/([^/]+)/", str(relative_path))
    if not match:
        raise ValueError(f"No producer output prefix: {relative_path}")
    stem = match.group(1).lower()
    if stem.startswith("12a_"):
        return "12A"
    if stem.startswith("d02_"):
        return "D02"
    number = re.match(r"^(\d{2})_", stem)
    if not number:
        raise ValueError(f"Unknown producer stem: {stem}")
    return number.group(1)


def one_candidate(candidate_id: str):
    rows = CANDIDATE_INDEX.loc[
        CANDIDATE_INDEX["candidate_id"].eq(candidate_id)
    ]
    if len(rows) != 1:
        raise ValueError(
            f"Expected one candidate {candidate_id}; found {len(rows)}."
        )
    return rows.iloc[0]


def open_rgb(relative_path: str) -> Image.Image:
    with Image.open(checked_repo_path(relative_path)) as image:
        image.load()
        return image.convert("RGB")


def png_bytes(image: Image.Image) -> bytes:
    buffer = io.BytesIO()
    image.save(
        buffer,
        format="PNG",
        optimize=False,
        compress_level=9,
    )
    return buffer.getvalue()


def image_geometry(relative_path: str) -> tuple[int, int]:
    with Image.open(checked_repo_path(relative_path)) as image:
        image.load()
        return int(image.width), int(image.height)


def hash_record(relative_path: str) -> dict:
    path = checked_repo_path(relative_path)
    return {
        "relative_path": relative_path,
        "sha256": sha256_file(path),
        "size_bytes": int(path.stat().st_size),
    }


def render_chart(frame: pd.DataFrame) -> Image.Image:
    ordered = frame.sort_values(
        ["condition_order", "condition_value", "case_id"]
    ).reset_index(drop=True)
    if len(ordered) != 7:
        raise ValueError(
            "The curated p018 LaMa damage-size trajectory must have 7 rows."
        )
    values = pd.to_numeric(ordered["estimate"], errors="raise").astype(float)
    canvas = Image.new("RGB", (640, 380), "#f5f0e7")
    draw = ImageDraw.Draw(canvas)
    left, top, right, bottom = 70, 45, 610, 315
    draw.rectangle((left, top, right, bottom), outline="#44372f", width=2)
    low, high = float(values.min()), float(values.max())
    span = high - low if high > low else 1.0
    points = []
    for index, value in enumerate(values):
        x = left + round(index * (right - left) / (len(values) - 1))
        y = bottom - round((float(value) - low) * (bottom - top) / span)
        points.append((x, y))
        draw.line((x, bottom, x, bottom + 5), fill="#44372f", width=1)
        label = f"{100 * float(ordered.loc[index, 'condition_value']):.0f}%"
        draw.text((x - 10, bottom + 10), label, fill="#44372f")
    draw.line(points, fill="#9d3d2f", width=4, joint="curve")
    for x, y in points:
        draw.ellipse((x - 5, y - 5, x + 5, y + 5), fill="#9d3d2f")
    draw.text((left, 15), "p018 · LaMa · masked spatial error", fill="#2d2520")
    draw.text((10, top), f"{high:.4g}", fill="#44372f")
    draw.text((10, bottom - 8), f"{low:.4g}", fill="#44372f")
    draw.text((left, 350), "Controlled damaged-area fraction", fill="#44372f")
    return canvas


def render_contact_sheet(items: list[tuple[str, str]]) -> Image.Image:
    cell_width, cell_height = 150, 150
    gap, label_height = 8, 18
    canvas = Image.new("RGB", (640, 344), "#211d1a")
    draw = ImageDraw.Draw(canvas)
    for index, (label, relative_path) in enumerate(items):
        row, column = divmod(index, 4)
        x = gap + column * (cell_width + gap)
        y = gap + row * (cell_height + label_height + gap)
        image = open_rgb(relative_path)
        image.thumbnail((cell_width, cell_height), Image.Resampling.LANCZOS)
        px = x + (cell_width - image.width) // 2
        py = y + (cell_height - image.height) // 2
        canvas.paste(image, (px, py))
        draw.text((x, y + cell_height + 2), label, fill="#f4eadb")
    return canvas


def labelled_crop_panel(
    items: list[tuple[str, str]],
    crop_xyxy: list[int],
) -> Image.Image:
    crops = []
    for label, relative_path in items:
        crop = open_rgb(relative_path).crop(tuple(crop_xyxy))
        crops.append((label, crop))
    width = sum(crop.width for _, crop in crops) + 12 * (len(crops) + 1)
    height = max(crop.height for _, crop in crops) + 38
    canvas = Image.new("RGB", (width, height), "#201d1a")
    draw = ImageDraw.Draw(canvas)
    x = 12
    for label, crop in crops:
        canvas.paste(crop, (x, 22))
        draw.text((x, 5), label, fill="#f6efe4")
        x += crop.width + 12
    return canvas


print(
    "Batch 7 initialized for responsibilities:",
    ", ".join(BATCH_7_RESPONSIBILITY_IDS),
)

Batch 7 initialized for responsibilities: R09, R10

In [32]:
DIRECT_ASSET_SPECS: list[dict] = []
_DIRECT_SPEC_KEYS: set[tuple[str, str, str]] = set()


def add_direct_asset(
    *,
    relative_path: str,
    evidence_role: str,
    identity: dict,
    profiles: tuple[str, ...],
    purpose: str,
    alternative_text: str,
    lossless: bool,
    mapping_state: str = "existing_direct",
    source_row_id: str | None = None,
    source_selector: dict | None = None,
    source_artifact_key: str = "registered_visible_asset",
    expected_sha256: str | None = None,
) -> None:
    source = hash_record(relative_path)
    if expected_sha256 and source["sha256"] != str(expected_sha256).lower():
        raise ValueError(f"Source checksum differs: {relative_path}")
    key = (relative_path, evidence_role, canonical_text(identity))
    if key in _DIRECT_SPEC_KEYS:
        existing = next(
            row
            for row in DIRECT_ASSET_SPECS
            if row["_key"] == key
        )
        existing["profiles"] = tuple(
            dict.fromkeys((*existing["profiles"], *profiles))
        )
        return
    _DIRECT_SPEC_KEYS.add(key)
    width, height = image_geometry(relative_path)
    DIRECT_ASSET_SPECS.append(
        {
            "_key": key,
            "relative_path": relative_path,
            "evidence_role": evidence_role,
            "identity": identity,
            "profiles": profiles,
            "purpose": purpose,
            "alternative_text": alternative_text,
            "lossless": bool(lossless),
            "mapping_state": mapping_state,
            "source_row_id": source_row_id,
            "source_selector": source_selector or {},
            "source_artifact_key": source_artifact_key,
            "source_sha256": source["sha256"],
            "source_size_bytes": source["size_bytes"],
            "width": width,
            "height": height,
            "image": None,
            "derivation_type": "none",
            "derivation_parameters": {},
            "input_checksums": [source],
            "crop_xyxy": None,
        }
    )


def add_candidate_context(
    candidate_id: str,
    *,
    include_clean: bool = False,
    include_damaged: bool = False,
    include_mask: bool = False,
    restored_profiles: tuple[str, ...] = ("standard",),
    restored_purpose: str = "curated restoration",
    restored_alt: str | None = None,
) -> None:
    row = one_candidate(candidate_id)
    candidate_identity = json.loads(str(row["identity_json"]))
    case_identity = canonical_identity(
        painting_id=str(row["painting_id"]),
        case_id=str(row["case_id"]),
        experiment_id=str(row["experiment_id"]),
    )
    if include_clean:
        add_direct_asset(
            relative_path=str(row["clean_path"]),
            evidence_role="clean_reference",
            identity=canonical_identity(painting_id=str(row["painting_id"])),
            profiles=("standard",),
            purpose="controlled clean reference",
            alternative_text=f"Clean controlled reference for {row['painting_id']}.",
            lossless=False,
            source_row_id=str(row["painting_id"]),
            source_selector={"painting_id": str(row["painting_id"])},
        )
    if include_damaged:
        add_direct_asset(
            relative_path=str(row["damaged_path"]),
            evidence_role="damaged_input",
            identity=case_identity,
            profiles=("standard",),
            purpose="controlled damaged input",
            alternative_text=f"Controlled damaged input for {row['case_id']}.",
            lossless=False,
            source_row_id=str(row["case_id"]),
            source_selector={"case_id": str(row["case_id"])},
        )
    if include_mask:
        add_direct_asset(
            relative_path=str(row["mask_path"]),
            evidence_role="damage_mask",
            identity=case_identity,
            profiles=("diagnostic_preview",),
            purpose="controlled damage mask",
            alternative_text=f"Loss mask for {row['case_id']}.",
            lossless=True,
            source_row_id=str(row["case_id"]),
            source_selector={"case_id": str(row["case_id"])},
        )
    add_direct_asset(
        relative_path=str(row["producer_restored_path"]),
        evidence_role="restoration_candidate",
        identity=candidate_identity,
        profiles=restored_profiles,
        purpose=restored_purpose,
        alternative_text=(
            restored_alt
            or f"{row['model_id']} restoration for {row['case_id']}."
        ),
        lossless=False,
        source_row_id=str(row["candidate_id"]),
        source_selector={"candidate_id": str(row["candidate_id"])},
        expected_sha256=str(row["producer_restored_sha256"]),
    )


# Study opening and Foyer hero/preview.
p001_clean = str(
    PAINTING_LOOKUP.loc[
        PAINTING_LOOKUP["painting_id"].eq("p001"),
        "clean_image_path",
    ].iloc[0]
)
add_direct_asset(
    relative_path=p001_clean,
    evidence_role="clean_reference",
    identity=canonical_identity(painting_id="p001"),
    profiles=("standard", "thumb"),
    purpose="foyer hero and Study Design route preview",
    alternative_text="Juan de Pareja clean controlled reference.",
    lossless=False,
    source_row_id="p001",
    source_selector={"painting_id": "p001"},
)

# Metric, Model Gallery, and Case Explorer opening.
P018_MIXED = {
    "telea": "candidate__opencv_telea__canonical__p018__mixed_damage__c00",
    "lama": "candidate__lama__canonical__p018__mixed_damage__c00",
    "hint": "candidate__hint_places2__canonical__p018__mixed_damage__c00",
    "sd15": "sd15__p00__s2026__d0cd65cf894a",
    "sdxl": "sdxl__5d3f1bc4bed2__p00_generic__seed2026",
}
add_candidate_context(
    P018_MIXED["lama"],
    include_clean=True,
    include_damaged=True,
    include_mask=True,
    restored_profiles=("standard", "thumb"),
    restored_purpose="Metric, Model Gallery, and Case Explorer opening",
)
for key in ("telea", "hint", "sd15", "sdxl"):
    add_candidate_context(P018_MIXED[key])

P018_LAMA_IDENTITY = json.loads(
    str(one_candidate(P018_MIXED["lama"])["identity_json"])
)

MAP_SPECS = [
    (
        "spatial_map_manifest_path",
        "map_image_id",
        "outputs/16_difference_maps_and_spatial_diagnostics/images/maps/lama/"
        "spm_e5f9511cc6c7d95a/masked_signed_improvement.png",
        "signed_improvement_map",
        ("diagnostic_preview", "thumb"),
        "Masked signed-improvement map for the p018 LaMa restoration.",
        {"metric_name": "spatial_masked_error", "region_id": "masked_region", "evidence_layer": "masked_signed_improvement"},
    ),
    (
        "local_map_manifest_path",
        "map_image_id",
        "outputs/17_local_consistency_metrics/images/maps/lama/"
        "lcm_e5f9511cc6c7d95a/texture.png",
        "local_texture_map",
        ("diagnostic_preview",),
        "Local texture diagnostic for the p018 LaMa restoration.",
        {"metric_name": "local_texture_error", "region_id": "mask_bbox_crop", "evidence_layer": "texture"},
    ),
    (
        "local_map_manifest_path",
        "map_image_id",
        "outputs/17_local_consistency_metrics/images/maps/lama/"
        "lcm_e5f9511cc6c7d95a/colour.png",
        "local_colour_map",
        ("diagnostic_preview",),
        "Local colour diagnostic for the p018 LaMa restoration.",
        {"metric_name": "delta_e_ciede2000", "region_id": "mask_bbox_crop", "evidence_layer": "colour"},
    ),
    (
        "local_map_manifest_path",
        "map_image_id",
        "outputs/17_local_consistency_metrics/images/maps/lama/"
        "lcm_e5f9511cc6c7d95a/seam.png",
        "local_seam_map",
        ("diagnostic_preview",),
        "Local seam diagnostic for the p018 LaMa restoration.",
        {"metric_name": "boundary_seam_error", "region_id": "boundary_ring", "evidence_layer": "seam"},
    ),
    (
        "semantic_map_manifest_path",
        "semantic_map_asset_id",
        "outputs/20_semantic_and_structural_consistency/images/maps/lama/"
        "candidate__lama__canonical__p018__mixed_damage__c00/semantic.png",
        "semantic_map",
        ("diagnostic_preview",),
        "Semantic diagnostic for the p018 LaMa restoration.",
        {"metric_name": "local_semantic_consistency", "region_id": "content_region", "evidence_layer": "semantic"},
    ),
]

for (
    input_key,
    row_id_column,
    relative_path,
    role,
    profiles,
    alt,
    identity_updates,
) in MAP_SPECS:
    manifest = read_declared_csv(
        input_key,
        [row_id_column, "relative_path", "sha256", "size_bytes", "status"],
    )
    match = manifest.loc[manifest["relative_path"].eq(relative_path)]
    if len(match) != 1 or str(match.iloc[0]["status"]) != "passed":
        raise ValueError(f"Exact map row not found or not passed: {relative_path}")
    map_row = match.iloc[0]
    identity = dict(P018_LAMA_IDENTITY)
    identity.update(identity_updates)
    add_direct_asset(
        relative_path=relative_path,
        evidence_role=role,
        identity=identity,
        profiles=profiles,
        purpose="curated diagnostic evidence",
        alternative_text=alt,
        lossless=True,
        source_row_id=str(map_row[row_id_column]),
        source_selector={row_id_column: str(map_row[row_id_column])},
        expected_sha256=str(map_row["sha256"]),
    )
    del manifest

# Stability opening and repeated-seed replay.
P018_SIZE20_IDS = [
    "candidate__lama__damage_size__p018__loss_large__size_20pct__c00",
    "sd15__p00__s2026__bc46647b2698",
    "sd15dsu__eb31376e152c1244",
    "sd15dsu__b82cbfb9b3d389fc",
    "sd15dsu__2b547cbdd68b2f6e",
]
add_candidate_context(
    P018_SIZE20_IDS[0],
    include_damaged=True,
    include_mask=True,
)
for candidate_id_value in P018_SIZE20_IDS[1:]:
    add_candidate_context(candidate_id_value)

n22_map = read_declared_csv(
    "damage_size_map_manifest_path",
    [
        "map_image_id",
        "uncertainty_group_id",
        "case_id",
        "painting_id",
        "relative_path",
        "sha256",
        "size_bytes",
        "status",
    ],
)
n22_overlay = n22_map.loc[
    n22_map["uncertainty_group_id"].eq("ug_1de955f7e0f3d00cf0")
]
if len(n22_overlay) != 1 or str(n22_overlay.iloc[0]["status"]) != "passed":
    raise ValueError("The exact p018 N22 uncertainty overlay is missing.")
n22_overlay_row = n22_overlay.iloc[0]
n22_overlay_path = (
    "outputs/22_damage_size_diffusion_uncertainty_extension/"
    + str(n22_overlay_row["relative_path"])
)
add_direct_asset(
    relative_path=n22_overlay_path,
    evidence_role="uncertainty_overlay",
    identity=canonical_identity(
        painting_id="p018",
        case_id="damage_size__p018__loss_large__size_20pct",
        model_id="stable_diffusion_inpainting",
        experiment_id="damage_size_sensitivity",
        uncertainty_group_id="ug_1de955f7e0f3d00cf0",
        metric_name="mean_channel_rgb_seed_standard_deviation",
        region_id="full_image",
        evidence_layer="uncertainty_overlay",
    ),
    profiles=("diagnostic_preview",),
    purpose="selected repeated-seed uncertainty overlay",
    alternative_text="Repeated-seed uncertainty overlay for p018 at 20 percent damage.",
    lossless=True,
    source_row_id=str(n22_overlay_row["map_image_id"]),
    source_selector={"map_image_id": str(n22_overlay_row["map_image_id"])},
    expected_sha256=str(n22_overlay_row["sha256"]),
)
del n22_map

# Trustworthiness opening and exact peers.
P002_TRUST_IDS = [
    "candidate__opencv_telea__canonical__p002__loss_large__c00",
    "candidate__lama__canonical__p002__loss_large__c00",
    "candidate__hint_places2__canonical__p002__loss_large__c00",
    "sd15__p00__s2026__29ff258ff921",
]
add_candidate_context(
    P002_TRUST_IDS[-1],
    include_clean=True,
    include_damaged=True,
    include_mask=True,
    restored_profiles=("standard", "thumb"),
    restored_purpose="Trustworthiness opening and route preview",
)
for candidate_id_value in P002_TRUST_IDS[:-1]:
    add_candidate_context(candidate_id_value)

# Focused Portrait Review opening.
D02_R005_CANDIDATE_ID = (
    "candidate__hint_places2__canonical__p269__mixed_damage__c00"
)
add_candidate_context(
    D02_R005_CANDIDATE_ID,
    include_clean=True,
    include_damaged=True,
    include_mask=True,
)

# Representative Case Explorer and Archive visuals are exact Git artifacts.
add_direct_asset(
    relative_path=(
        "outputs/29_explainable_ai_and_case_retrieval/figures/"
        "example_retrieval_panels/query_01_portrait_figure_lower_risk.png"
    ),
    evidence_role="retrieval_panel",
    identity=canonical_identity(evidence_layer="retrieval_example_01"),
    profiles=("diagnostic_preview",),
    purpose="representative saved retrieval panel",
    alternative_text="Saved lower-risk portrait retrieval example.",
    lossless=True,
    source_row_id="query_01_portrait_figure_lower_risk",
    source_selector={"query_id": "query_01_portrait_figure_lower_risk"},
)
add_direct_asset(
    relative_path=(
        "outputs/33_final_evaluation_report/figures/thesis/"
        "01_framework_evidence_map.png"
    ),
    evidence_role="archive_evidence_map",
    identity=canonical_identity(evidence_layer="framework_evidence_map"),
    profiles=("diagnostic_preview", "thumb"),
    purpose="Research Archive route preview",
    alternative_text="Final framework evidence map from Notebook 33.",
    lossless=True,
    source_row_id="01_framework_evidence_map",
    source_selector={"figure_id": "01_framework_evidence_map"},
)
for path, role, alt in [
    (
        "outputs/d02_portrait_skin_tone_and_hand_restoration_audit/figures/hand_vs_control.png",
        "d02_hand_summary_figure",
        "Hand-region versus matched-control summary.",
    ),
    (
        "outputs/d02_portrait_skin_tone_and_hand_restoration_audit/figures/skin_tone_audit.png",
        "d02_lightness_summary_figure",
        "Rendered-lightness association summary.",
    ),
]:
    add_direct_asset(
        relative_path=path,
        evidence_role=role,
        identity=canonical_identity(evidence_layer=role),
        profiles=("diagnostic_preview",),
        purpose="Focused Portrait Review saved figure",
        alternative_text=alt,
        lossless=True,
        source_row_id=role,
        source_selector={"figure_role": role},
    )

print("Direct visible assets selected:", len(DIRECT_ASSET_SPECS))

Direct visible assets selected: 37

In [33]:
STAGED_DERIVED_PATHS = {
    key: STAGING_PACKAGE_ROOT / SETTINGS["output"][key]
    for key in (
        "stability_trajectories_path",
        "d02_r005_geometry_path",
    )
}
for label, path in STAGED_DERIVED_PATHS.items():
    if not path.is_file():
        raise FileNotFoundError(f"Batch 6 handoff missing {label}: {path}")

trajectory = STABILITY_TRAJECTORIES.loc[
    STABILITY_TRAJECTORIES["painting_id"].eq("p018")
    & STABILITY_TRAJECTORIES["model_id"].eq("lama")
    & STABILITY_TRAJECTORIES["analysis_family_id"].eq("spatial_masked_error")
    & STABILITY_TRAJECTORIES["metric_name"].eq("restored_error_mean")
    & STABILITY_TRAJECTORIES["region_id"].eq("masked_region")
].copy()

R005_EXPECTED = {
    "painting_id": "p269",
    "case_id": "canonical__p269__mixed_damage",
    "candidate_id": D02_R005_CANDIDATE_ID,
    "model_id": "hint_places2",
    "annotation_id": "anatomy_7726c759861cf33baba7",
    "hand_control_id": "hand_control_43e40122b45c717bc8b6",
    "review_unit_id": "anatomy_review_813d89c1fcfdc670b64a",
    "blind_review_code": "R005",
}
if D02_R005_GEOMETRY.get("schema_version") != SETTINGS[
    "expected_output_schemas"
]["d02_r005_geometry"]:
    raise ValueError("D02 R005 geometry schema differs from the v2 contract.")
for key, expected in R005_EXPECTED.items():
    observed = D02_R005_GEOMETRY.get(key)
    if observed != expected:
        raise ValueError(
            f"D02 R005 geometry {key}={observed!r}; expected {expected!r}."
        )

review_crop_xyxy = [
    int(value)
    for value in D02_R005_GEOMETRY["review_crop_xyxy"]
]
if review_crop_xyxy != [617, 81, 716, 215]:
    raise ValueError("D02 R005 review crop differs from [617,81,716,215].")

control_crop_xyxy = [
    int(value)
    for value in D02_R005_GEOMETRY["control_crop_xyxy"]
]
if len(control_crop_xyxy) != 4:
    raise ValueError("D02 R005 control crop must be xyxy.")

r005 = one_candidate(D02_R005_CANDIDATE_ID)
r005_paths = {
    "clean": str(r005["clean_path"]),
    "damaged": str(r005["damaged_path"]),
    "mask": str(r005["mask_path"]),
    "restored": str(r005["producer_restored_path"]),
}

clean_p269 = open_rgb(r005_paths["clean"])
if "control_pixels_xy" in D02_R005_GEOMETRY:
    control_pixels_xy = [
        [int(pair[0]), int(pair[1])]
        for pair in D02_R005_GEOMETRY["control_pixels_xy"]
    ]
elif "control_flat_indices" in D02_R005_GEOMETRY:
    control_pixels_xy = [
        [int(index) % clean_p269.width, int(index) // clean_p269.width]
        for index in D02_R005_GEOMETRY["control_flat_indices"]
    ]
else:
    raise KeyError(
        "D02_R005_GEOMETRY must retain control_pixels_xy or control_flat_indices."
    )
if len(set(map(tuple, control_pixels_xy))) != 1196:
    raise ValueError("The R005 matched control must contain exactly 1,196 pixels.")

DERIVED_ASSET_SPECS: list[dict] = []


def add_derived_asset(
    *,
    image: Image.Image,
    evidence_role: str,
    identity: dict,
    profiles: tuple[str, ...],
    purpose: str,
    alternative_text: str,
    derivation_type: str,
    derivation_parameters: dict,
    input_paths: list[str],
    source_row_id: str,
    crop_xyxy: list[int] | None = None,
) -> None:
    encoded = png_bytes(image.convert("RGB"))
    source_sha = hashlib.sha256(encoded).hexdigest()
    source_records = [hash_record(path) for path in input_paths]
    DERIVED_ASSET_SPECS.append(
        {
            "relative_path": None,
            "evidence_role": evidence_role,
            "identity": identity,
            "profiles": profiles,
            "purpose": purpose,
            "alternative_text": alternative_text,
            "lossless": True,
            "mapping_state": "n34_derived_registered",
            "source_row_id": source_row_id,
            "source_selector": {"source_row_id": source_row_id},
            "source_artifact_key": f"dashboard.derived.{evidence_role}",
            "source_sha256": source_sha,
            "source_size_bytes": len(encoded),
            "width": int(image.width),
            "height": int(image.height),
            "image": image.convert("RGB"),
            "master_png_bytes": encoded,
            "derivation_type": derivation_type,
            "derivation_parameters": derivation_parameters,
            "input_checksums": source_records,
            "crop_xyxy": crop_xyxy,
        }
    )


add_derived_asset(
    image=render_chart(trajectory),
    evidence_role="stability_trajectory_chart",
    identity=canonical_identity(
        painting_id="p018",
        model_id="lama",
        experiment_id="damage_size_sensitivity",
        metric_name="restored_error_mean",
        region_id="masked_region",
        evidence_layer="damage_size_trajectory",
    ),
    profiles=("diagnostic_preview", "thumb"),
    purpose="Stability Lab trajectory and route preview",
    alternative_text="Seven-level p018 LaMa masked-error trajectory.",
    derivation_type="chart_render",
    derivation_parameters={
        "renderer": "pillow_fixed_canvas_v1",
        "row_count": 7,
        "canvas": [640, 380],
    },
    input_paths=[
        STAGED_DERIVED_PATHS["stability_trajectories_path"]
        .relative_to(PROJECT_ROOT)
        .as_posix()
    ],
    source_row_id="p018_lama_spatial_masked_error",
)

contact_items = [
    ("clean", str(one_candidate(P018_SIZE20_IDS[0])["clean_path"])),
    ("damaged 20%", str(one_candidate(P018_SIZE20_IDS[0])["damaged_path"])),
    ("mask 20%", str(one_candidate(P018_SIZE20_IDS[0])["mask_path"])),
    ("LaMa", str(one_candidate(P018_SIZE20_IDS[0])["producer_restored_path"])),
    ("SD seed 2026", str(one_candidate(P018_SIZE20_IDS[1])["producer_restored_path"])),
    ("SD seed 2027", str(one_candidate(P018_SIZE20_IDS[2])["producer_restored_path"])),
    ("SD seed 2028", str(one_candidate(P018_SIZE20_IDS[3])["producer_restored_path"])),
    ("SD seed 2029", str(one_candidate(P018_SIZE20_IDS[4])["producer_restored_path"])),
]
add_derived_asset(
    image=render_contact_sheet(contact_items),
    evidence_role="stability_contact_sheet",
    identity=canonical_identity(
        painting_id="p018",
        case_id="damage_size__p018__loss_large__size_20pct",
        model_id="stable_diffusion_inpainting",
        experiment_id="damage_size_sensitivity",
        uncertainty_group_id="ug_1de955f7e0f3d00cf0",
        evidence_layer="seed_contact_sheet",
    ),
    profiles=("diagnostic_preview",),
    purpose="compact Stability Lab repeated-seed replay",
    alternative_text="Clean, damaged, mask, LaMa, and four Stable Diffusion seed panels.",
    derivation_type="contact_sheet",
    derivation_parameters={
        "renderer": "pillow_fixed_grid_v1",
        "columns": 4,
        "rows": 2,
        "candidate_ids": P018_SIZE20_IDS,
    },
    input_paths=[path for _, path in contact_items],
    source_row_id="ug_1de955f7e0f3d00cf0",
)

r005_identity = canonical_identity(**R005_EXPECTED)
add_derived_asset(
    image=labelled_crop_panel(
        [(label, r005_paths[label]) for label in ("clean", "damaged", "mask", "restored")],
        review_crop_xyxy,
    ),
    evidence_role="d02_r005_review_panel",
    identity=r005_identity,
    profiles=("diagnostic_preview",),
    purpose="deterministically regenerated R005 blind-review panel",
    alternative_text="R005 clean, damaged, mask, and HINT review crops.",
    derivation_type="deterministic_regeneration",
    derivation_parameters={
        "renderer": "pillow_crop_panel_v1",
        "crop_xyxy": review_crop_xyxy,
        "panel_order": ["clean", "damaged", "mask", "restored"],
    },
    input_paths=list(r005_paths.values()),
    source_row_id=R005_EXPECTED["review_unit_id"],
    crop_xyxy=review_crop_xyxy,
)

clean_crop = open_rgb(r005_paths["clean"]).crop(tuple(review_crop_xyxy))
restored_crop = open_rgb(r005_paths["restored"]).crop(tuple(review_crop_xyxy))
add_derived_asset(
    image=ImageChops.difference(clean_crop, restored_crop),
    evidence_role="d02_r005_difference_crop",
    identity={**r005_identity, "evidence_layer": "clean_restored_absolute_rgb_difference"},
    profiles=("diagnostic_preview",),
    purpose="exact clean-versus-restored R005 difference crop",
    alternative_text="Absolute RGB difference between the clean and HINT R005 crops.",
    derivation_type="difference_map",
    derivation_parameters={
        "operation": "absolute_rgb_difference",
        "crop_xyxy": review_crop_xyxy,
        "pixel_range": [0, 255],
    },
    input_paths=[r005_paths["clean"], r005_paths["restored"]],
    source_row_id=R005_EXPECTED["review_unit_id"],
    crop_xyxy=review_crop_xyxy,
)

control_clean = clean_p269.crop(tuple(control_crop_xyxy))
cx1, cy1, cx2, cy2 = control_crop_xyxy
control_mask = Image.new("L", (cx2 - cx1, cy2 - cy1), 0)
control_mask_pixels = control_mask.load()
for x, y in control_pixels_xy:
    if cx1 <= x < cx2 and cy1 <= y < cy2:
        control_mask_pixels[x - cx1, y - cy1] = 255
if sum(1 for value in control_mask.getdata() if value) != 1196:
    raise ValueError("Control crop does not contain all 1,196 matched pixels.")
control_canvas = Image.new(
    "RGB",
    (control_clean.width * 2 + 12, control_clean.height + 22),
    "#201d1a",
)
control_canvas.paste(control_clean, (0, 22))
control_canvas.paste(control_mask.convert("RGB"), (control_clean.width + 12, 22))
control_draw = ImageDraw.Draw(control_canvas)
control_draw.text((0, 4), "matched control", fill="#f6efe4")
control_draw.text((control_clean.width + 12, 4), "1,196-pixel mask", fill="#f6efe4")
add_derived_asset(
    image=control_canvas,
    evidence_role="d02_r005_matched_control",
    identity={**r005_identity, "evidence_layer": "matched_control_geometry"},
    profiles=("diagnostic_preview",),
    purpose="exact R005 matched-control print and sparse mask",
    alternative_text="Matched clean control crop and its exact 1,196-pixel mask.",
    derivation_type="deterministic_regeneration",
    derivation_parameters={
        "renderer": "pillow_control_mask_v1",
        "control_crop_xyxy": control_crop_xyxy,
        "control_pixel_count": 1196,
    },
    input_paths=[
        r005_paths["clean"],
        STAGED_DERIVED_PATHS["d02_r005_geometry_path"]
        .relative_to(PROJECT_ROOT)
        .as_posix(),
    ],
    source_row_id=R005_EXPECTED["hand_control_id"],
    crop_xyxy=control_crop_xyxy,
)

ASSET_SPECS = DIRECT_ASSET_SPECS + DERIVED_ASSET_SPECS
if len(ASSET_SPECS) != len(
    {
        (
            row["evidence_role"],
            canonical_text(row["identity"]),
            row["source_sha256"],
        )
        for row in ASSET_SPECS
    }
):
    raise ValueError("Batch 7 logical asset specifications are not unique.")

print("Derived visible assets rendered in memory:", len(DERIVED_ASSET_SPECS))
print("Logical assets prepared:", len(ASSET_SPECS))

Derived visible assets rendered in memory: 5
Logical assets prepared: 42

In [34]:
def rendition_key(asset_id_value: str, profile: str, source_sha256: str) -> str:
    return stable_id(
        "rendition",
        {
            "asset_id": asset_id_value,
            "profile": profile,
            "source_sha256": source_sha256,
            "helper_version": DASHBOARD_ASSETS_VERSION,
        },
    )


def encode_rendition(
    source_image: Image.Image,
    *,
    profile: str,
    require_lossless: bool,
) -> tuple[bytes, str, str, int, int, dict]:
    rule = PROFILE_RULES[profile]
    original = source_image.copy()
    original_width, original_height = original.size
    scale = min(1.0, rule["max_edge"] / max(original.size))
    quality_schedule = (82, 76, 70, 64, 58, 52, 46, 40)
    resample = (
        Image.Resampling.NEAREST
        if require_lossless and original.mode in {"1", "L", "P"}
        else Image.Resampling.LANCZOS
    )

    for reduction in range(9):
        effective_scale = scale * (0.9**reduction)
        width = max(1, int(round(original_width * effective_scale)))
        height = max(1, int(round(original_height * effective_scale)))
        image = (
            original.copy()
            if (width, height) == original.size
            else original.resize((width, height), resample)
        )
        if require_lossless or profile == "diagnostic_preview":
            encoded = png_bytes(image)
            if len(encoded) <= rule["hard_bytes"]:
                return (
                    encoded,
                    "PNG",
                    "image/png",
                    width,
                    height,
                    {
                        "operation": "identity_encode" if image.size == original.size else "resize",
                        "resample": "nearest" if resample == Image.Resampling.NEAREST else "lanczos",
                        "source_size": [original_width, original_height],
                        "output_size": [width, height],
                        "png_compress_level": 9,
                    },
                )
        else:
            rgb = image.convert("RGB")
            for quality in quality_schedule:
                buffer = io.BytesIO()
                rgb.save(
                    buffer,
                    format="WEBP",
                    quality=quality,
                    method=6,
                    lossless=False,
                    exact=True,
                )
                encoded = buffer.getvalue()
                if len(encoded) <= rule["hard_bytes"]:
                    return (
                        encoded,
                        "WEBP",
                        "image/webp",
                        width,
                        height,
                        {
                            "operation": "encode_webp" if image.size == original.size else "resize_encode_webp",
                            "resample": "lanczos",
                            "source_size": [original_width, original_height],
                            "output_size": [width, height],
                            "quality": quality,
                            "method": 6,
                        },
                    )
    raise ValueError(
        f"Could not fit {profile} rendition under {rule['hard_bytes']} bytes."
    )


N34_PROVENANCE_SHA256 = hashlib.sha256(
    canonical_json_bytes(DASHBOARD_RELEASE_FINGERPRINT)
).hexdigest()

ASSET_ROWS = []
RENDITION_ROWS = []
RENDITION_PAYLOADS: dict[str, bytes] = {}
SPEC_BY_ASSET_ID: dict[str, dict] = {}

for spec in ASSET_SPECS:
    logical_asset_id = asset_id(
        spec["identity"],
        spec["source_sha256"],
        spec["evidence_role"],
    )
    if logical_asset_id in SPEC_BY_ASSET_ID:
        raise ValueError(f"Duplicate logical asset ID: {logical_asset_id}")
    SPEC_BY_ASSET_ID[logical_asset_id] = spec

    if spec["image"] is None:
        with Image.open(checked_repo_path(spec["relative_path"])) as source:
            source.load()
            source_image = source.copy()
    else:
        source_image = spec["image"].copy()

    rendition_ids = []
    for profile in spec["profiles"]:
        encoded, format_name, mime_type, width, height, transformation = (
            encode_rendition(
                source_image,
                profile=profile,
                require_lossless=bool(spec["lossless"]),
            )
        )
        rendition_id_value = rendition_key(
            logical_asset_id,
            profile,
            spec["source_sha256"],
        )
        extension = "png" if format_name == "PNG" else "webp"
        relative_output = (
            PurePosixPath(SETTINGS["output"][f"{profile}_dir"])
            / f"{rendition_id_value}.{extension}"
        ).as_posix()
        if relative_output in RENDITION_PAYLOADS:
            raise ValueError(f"Duplicate rendition path: {relative_output}")
        RENDITION_PAYLOADS[relative_output] = encoded
        output_sha = hashlib.sha256(encoded).hexdigest()
        rendition_ids.append(rendition_id_value)
        scientifically_exact = bool(
            format_name == "PNG"
            and transformation["operation"] == "identity_encode"
            and output_sha == spec["source_sha256"]
        )
        RENDITION_ROWS.append(
            {
                "rendition_id": rendition_id_value,
                "asset_id": logical_asset_id,
                "profile": profile,
                "relative_path": relative_output,
                "format": format_name,
                "mime_type": mime_type,
                "width": width,
                "height": height,
                "size_bytes": len(encoded),
                "sha256": output_sha,
                "source_sha256": spec["source_sha256"],
                "transformation_json": canonical_text(transformation),
                "purpose": spec["purpose"],
                "breakpoint_role": PROFILE_RULES[profile]["breakpoint_role"],
                "lossless": bool(format_name == "PNG"),
                "scientifically_exact": scientifically_exact,
                "upscaled": False,
                "crop_xyxy_json": canonical_text(spec["crop_xyxy"] or []),
                "schema_version": SETTINGS["expected_output_schemas"]["renditions"],
                "status": "ok",
                "issue": "",
            }
        )

    producer_id = (
        "34"
        if spec["derivation_type"] != "none"
        else producer_id_for_path(spec["relative_path"])
    )
    if producer_id == "34":
        producer_stem = SETTINGS["notebook_stem"]
        producer_run_id = DASHBOARD_RELEASE_ID
        producer_manifest_sha = N34_PROVENANCE_SHA256
    else:
        producer_manifest = UPSTREAM_MANIFESTS[producer_id]
        producer_stem = str(producer_manifest["notebook_name"])
        producer_run_id = str(producer_manifest["run_id"])
        producer_manifest_sha = str(MANIFEST_SPECS[producer_id]["sha256"]).lower()

    source_relative_path = spec["relative_path"]
    if source_relative_path is None:
        diagnostic_id = rendition_key(
            logical_asset_id,
            "diagnostic_preview",
            spec["source_sha256"],
        )
        source_relative_path = (
            PurePosixPath(SETTINGS["output"]["diagnostic_preview_dir"])
            / f"{diagnostic_id}.png"
        ).as_posix()

    ASSET_ROWS.append(
        {
            "asset_id": logical_asset_id,
            "asset_kind": "image",
            "evidence_role": spec["evidence_role"],
            "requiredness": "required",
            "mapping_state": spec["mapping_state"],
            "identity_json": canonical_text(spec["identity"]),
            "producer_notebook_id": producer_id,
            "producer_notebook_stem": producer_stem,
            "producer_run_id": producer_run_id,
            "producer_manifest_sha256": producer_manifest_sha,
            "source_artifact_key": spec["source_artifact_key"],
            "source_relative_path": source_relative_path,
            "source_sha256": spec["source_sha256"],
            "source_size_bytes": int(spec["source_size_bytes"]),
            "mime_type": "image/png",
            "source_row_id": spec["source_row_id"],
            "source_selector_json": canonical_text(spec["source_selector"]),
            "width": int(spec["width"]),
            "height": int(spec["height"]),
            "denominator": None,
            "derivation_type": spec["derivation_type"],
            "derivation_parameters_json": canonical_text(spec["derivation_parameters"]),
            "helper_version": DASHBOARD_ASSETS_VERSION,
            "input_checksums_json": canonical_text(spec["input_checksums"]),
            "output_sha256": spec["source_sha256"],
            "rendition_ids_json": canonical_text(sorted(rendition_ids)),
            "locator_ids_json": "[]",
            "availability_state": "available_local",
            "availability_reason": "Registered local web rendition.",
            "alternative_text": spec["alternative_text"],
            "schema_version": SETTINGS["expected_output_schemas"]["dashboard_assets"],
            "status": "ok",
            "issue": "",
        }
    )

RENDITIONS = validate_output_frame(
    pd.DataFrame(RENDITION_ROWS),
    "renditions",
).sort_values(["asset_id", "profile", "rendition_id"]).reset_index(drop=True)

expected_rendition_paths = set(RENDITIONS["relative_path"])
staged_renditions_root = (
    STAGING_PACKAGE_ROOT / SETTINGS["output"]["renditions_dir"]
)
RERUN_RENDITION_DIFFERENCES = []
for relative_output, payload in sorted(RENDITION_PAYLOADS.items()):
    existing = STAGING_PACKAGE_ROOT / relative_output
    if existing.is_file():
        previous_sha = sha256_file(existing)
        next_sha = hashlib.sha256(payload).hexdigest()
        if previous_sha != next_sha:
            RERUN_RENDITION_DIFFERENCES.append(
                {
                    "relative_path": relative_output,
                    "previous_sha256": previous_sha,
                    "next_sha256": next_sha,
                }
            )
if RERUN_RENDITION_DIFFERENCES:
    raise RuntimeError(
        "A rerun would change deterministic rendition bytes: "
        f"{RERUN_RENDITION_DIFFERENCES[:3]}"
    )
for relative_output, payload in sorted(RENDITION_PAYLOADS.items()):
    atomic_write_bytes(payload, STAGING_PACKAGE_ROOT / relative_output)

# Reruns replace the exact set and remove only stale Batch-7 files in staging.
if staged_renditions_root.exists():
    for existing in staged_renditions_root.rglob("*"):
        if existing.is_file():
            relative = existing.relative_to(STAGING_PACKAGE_ROOT).as_posix()
            if relative not in expected_rendition_paths:
                existing.unlink()

print("Registered renditions written to staging:", len(RENDITIONS))

Registered renditions written to staging: 48

In [35]:
PUBLICATION_COLUMNS = [
    "artifact_id",
    "local_relative_path",
    "provider",
    "repository_id",
    "path_in_repository",
    "sha256",
    "size_bytes",
    "publication_status",
    "publication_commit_url",
    "verification_status",
]
EXTERNAL_PUBLICATION_FULL = pd.read_csv(
    PROJECT_ROOT / SETTINGS["inputs"]["external_publication_registry_path"],
    usecols=PUBLICATION_COLUMNS,
    low_memory=False,
)
if len(EXTERNAL_PUBLICATION_FULL) != int(
    SETTINGS["input_table_contracts"]["external_publication_registry_path"]["rows"]
):
    raise ValueError("External-publication registry row count differs.")
if EXTERNAL_PUBLICATION_FULL["local_relative_path"].duplicated().any():
    raise ValueError("External-publication local paths are not unique.")
PUBLICATION_BY_PATH = EXTERNAL_PUBLICATION_FULL.set_index(
    "local_relative_path", drop=False
)

GIT_REVISION = "503cd8bbc7afa4527069ad4c9931725ffb88ca4b"
GIT_REPOSITORY = "Rahul-DS25M008/painting_restoration_eval"
if not is_full_git_revision(GIT_REVISION):
    raise ValueError("Audited Git revision is not a full immutable SHA.")

BUNDLE_STAGE_BY_PRODUCER = {
    "16": PROJECT_ROOT / ".codex_tmp/bundled_assets/n16_full",
    "17": PROJECT_ROOT / ".codex_tmp/bundled_assets/n17_full",
    "19": PROJECT_ROOT / ".codex_tmp/bundled_assets/n19_full",
    "20": PROJECT_ROOT / ".codex_tmp/bundled_assets/n20_full",
}
BUNDLE_RECORD_KEY_BY_PRODUCER = {
    "16": "n16_bundle_record_path",
    "17": "n17_bundle_record_path",
    "19": "n19_bundle_record_path",
    "20": "n20_bundle_record_path",
}
BUNDLE_CACHE: dict[str, tuple[dict, dict, Path]] = {}


def bundle_context(producer_id: str) -> tuple[dict, dict, Path] | None:
    if producer_id not in BUNDLE_STAGE_BY_PRODUCER:
        return None
    if producer_id in BUNDLE_CACHE:
        return BUNDLE_CACHE[producer_id]
    stage = BUNDLE_STAGE_BY_PRODUCER[producer_id]
    catalogue_path = stage / "indexes/catalogue.json"
    record_path = PROJECT_ROOT / SETTINGS["inputs"][
        BUNDLE_RECORD_KEY_BY_PRODUCER[producer_id]
    ]
    if not catalogue_path.is_file() or not record_path.is_file():
        return None
    catalogue = json.loads(catalogue_path.read_text(encoding="utf-8"))
    record = json.loads(record_path.read_text(encoding="utf-8"))
    for key in ("release_id", "prefix", "repo_id", "source_manifest_sha256"):
        if catalogue.get(key) != record.get(key):
            raise ValueError(f"Bundle {producer_id} {key} differs from release record.")
    if record.get("status") != "full_remote_verified":
        raise ValueError(f"Bundle {producer_id} is not full_remote_verified.")
    if not is_full_git_revision(record.get("revision")):
        raise ValueError(f"Bundle {producer_id} revision is mutable or abbreviated.")
    BUNDLE_CACHE[producer_id] = (catalogue, record, stage)
    return BUNDLE_CACHE[producer_id]


def base_locator_row(
    *,
    locator_id_value: str,
    asset_id_value: str,
    transport: str,
    provider: str,
    repository: str,
    revision: str,
    relative_path: str,
    immutable_resolve_url: str,
    provenance_url: str,
    expected_size_bytes: int,
    expected_sha256: str,
    publication_record_id: str,
    release_id: str | None = None,
    release_prefix: str | None = None,
    catalogue_path: str | None = None,
    catalogue_size_bytes: int | None = None,
    catalogue_sha256: str | None = None,
    painting_id: str | None = None,
    remote_asset_id: str | None = None,
    bundle_member_path: str | None = None,
    bundle_member_size_bytes: int | None = None,
    bundle_member_sha256: str | None = None,
) -> dict:
    return {
        "locator_id": locator_id_value,
        "asset_id": asset_id_value,
        "transport": transport,
        "provider": provider,
        "repository": repository,
        "revision": revision,
        "relative_path": relative_path,
        "immutable_resolve_url": immutable_resolve_url,
        "provenance_url": provenance_url,
        "expected_size_bytes": int(expected_size_bytes),
        "expected_sha256": expected_sha256,
        "publication_record_id": publication_record_id,
        "release_id": release_id,
        "release_prefix": release_prefix,
        "catalogue_path": catalogue_path,
        "catalogue_size_bytes": catalogue_size_bytes,
        "catalogue_sha256": catalogue_sha256,
        "painting_id": painting_id,
        "remote_asset_id": remote_asset_id,
        "bundle_member_path": bundle_member_path,
        "bundle_member_size_bytes": bundle_member_size_bytes,
        "bundle_member_sha256": bundle_member_sha256,
        "schema_version": SETTINGS["expected_output_schemas"]["asset_locators"],
        "status": "ok",
        "issue": "",
    }


LOCATOR_ROWS = []

# Every generated rendition has an immutable package-local locator.
for rendition in RENDITIONS.itertuples(index=False):
    local_locator_id = locator_id(
        "local_package",
        DASHBOARD_RELEASE_ID,
        DASHBOARD_RELEASE_ID,
        rendition.relative_path,
    )
    LOCATOR_ROWS.append(
        base_locator_row(
            locator_id_value=local_locator_id,
            asset_id_value=rendition.asset_id,
            transport="local_package",
            provider="local",
            repository=DASHBOARD_RELEASE_ID,
            revision=DASHBOARD_RELEASE_ID,
            relative_path=rendition.relative_path,
            immutable_resolve_url="",
            provenance_url="",
            expected_size_bytes=int(rendition.size_bytes),
            expected_sha256=str(rendition.sha256),
            publication_record_id=f"dashboard_release:{DASHBOARD_RELEASE_ID}",
            release_id=DASHBOARD_RELEASE_ID,
        )
    )


def publication_locator(asset_row: dict, spec: dict) -> dict | None:
    source_path = spec["relative_path"]
    if source_path is None or source_path not in PUBLICATION_BY_PATH.index:
        return None
    record = PUBLICATION_BY_PATH.loc[source_path]
    if isinstance(record, pd.DataFrame):
        raise ValueError(f"Duplicate publication rows for {source_path}")
    if (
        str(record["publication_status"]) != "published_verified"
        or str(record["verification_status"]) != "verified"
        or str(record["sha256"]).lower() != spec["source_sha256"]
        or int(record["size_bytes"]) != int(spec["source_size_bytes"])
    ):
        raise ValueError(f"Publication record does not verify {source_path}")
    match = re.search(
        r"/commit/([0-9a-f]{40})(?:$|[/?#])",
        str(record["publication_commit_url"]),
    )
    if not match:
        raise ValueError(f"No immutable publication revision for {source_path}")
    revision = match.group(1)
    repository = str(record["repository_id"])
    remote_path = str(record["path_in_repository"])
    encoded_path = "/".join(quote(part, safe="") for part in remote_path.split("/"))
    lid = locator_id("huggingface_object", repository, revision, remote_path)
    return base_locator_row(
        locator_id_value=lid,
        asset_id_value=asset_row["asset_id"],
        transport="huggingface_object",
        provider="huggingface_dataset",
        repository=repository,
        revision=revision,
        relative_path=remote_path,
        immutable_resolve_url=(
            f"https://huggingface.co/datasets/{repository}/resolve/{revision}/{encoded_path}"
        ),
        provenance_url=str(record["publication_commit_url"]),
        expected_size_bytes=int(record["size_bytes"]),
        expected_sha256=str(record["sha256"]).lower(),
        publication_record_id=str(record["artifact_id"]),
    )


def bundle_locator(asset_row: dict, spec: dict) -> dict | None:
    source_path = spec["relative_path"]
    if source_path is None:
        return None
    producer_id = producer_id_for_path(source_path)
    context = bundle_context(producer_id)
    if context is None:
        return None
    catalogue, record, stage = context
    painting_id = spec["identity"].get("painting_id")
    if not painting_id or painting_id not in catalogue["paintings"]:
        return None
    painting_entry = catalogue["paintings"][painting_id]
    index_path = stage / Path(
        *PurePosixPath(painting_entry["path"]).relative_to(catalogue["prefix"]).parts
    )
    if (
        not index_path.is_file()
        or index_path.stat().st_size != int(painting_entry["size_bytes"])
        or sha256_file(index_path) != painting_entry["sha256"]
    ):
        raise ValueError(f"Bundle painting index differs: {painting_id}")
    painting_index = json.loads(index_path.read_text(encoding="utf-8"))
    matches = [
        row
        for row in painting_index["assets"]
        if row["original_relative_path"] == source_path
    ]
    if len(matches) != 1:
        return None
    remote_asset = matches[0]
    if (
        remote_asset["sha256"] != spec["source_sha256"]
        or int(remote_asset["size_bytes"]) != int(spec["source_size_bytes"])
    ):
        raise ValueError(f"Bundle member bytes differ: {source_path}")
    bundle_path = str(remote_asset["bundle_path"])
    bundle = catalogue["bundles"][bundle_path]
    local_bundle = stage / Path(
        *PurePosixPath(bundle_path).relative_to(catalogue["prefix"]).parts
    )
    if (
        not local_bundle.is_file()
        or local_bundle.stat().st_size != int(bundle["size_bytes"])
        or sha256_file(local_bundle) != bundle["sha256"]
    ):
        raise ValueError(f"Bundle bytes differ: {bundle_path}")
    catalogue_local = stage / "indexes/catalogue.json"
    catalogue_remote = f"{catalogue['prefix']}/indexes/catalogue.json"
    revision = str(record["revision"])
    repository = str(record["repo_id"])
    member_path = str(remote_asset["member_path"])
    encoded_bundle = "/".join(quote(part, safe="") for part in bundle_path.split("/"))
    lid = locator_id(
        "huggingface_bundle_member",
        repository,
        revision,
        f"{bundle_path}#{member_path}",
    )
    return base_locator_row(
        locator_id_value=lid,
        asset_id_value=asset_row["asset_id"],
        transport="huggingface_bundle_member",
        provider="huggingface_dataset",
        repository=repository,
        revision=revision,
        relative_path=bundle_path,
        immutable_resolve_url=(
            f"https://huggingface.co/datasets/{repository}/resolve/{revision}/{encoded_bundle}"
        ),
        provenance_url=(
            f"https://huggingface.co/datasets/{repository}/tree/{revision}/{catalogue['prefix']}"
        ),
        expected_size_bytes=int(bundle["size_bytes"]),
        expected_sha256=str(bundle["sha256"]),
        publication_record_id=stable_id(
            "publication_record", producer_id, record["release_id"], revision
        ),
        release_id=str(record["release_id"]),
        release_prefix=str(record["prefix"]),
        catalogue_path=catalogue_remote,
        catalogue_size_bytes=int(catalogue_local.stat().st_size),
        catalogue_sha256=sha256_file(catalogue_local),
        painting_id=str(painting_id),
        remote_asset_id=str(remote_asset["asset_id"]),
        bundle_member_path=member_path,
        bundle_member_size_bytes=int(remote_asset["size_bytes"]),
        bundle_member_sha256=str(remote_asset["sha256"]),
    )


def git_locator(asset_row: dict, spec: dict) -> dict | None:
    source_path = spec["relative_path"]
    if source_path is None:
        return None
    result = subprocess.run(
        ["git", "show", f"{GIT_REVISION}:{source_path}"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        return None
    committed = result.stdout
    pointer = re.fullmatch(
        rb"version https://git-lfs\.github\.com/spec/v1\n"
        rb"oid sha256:([0-9a-f]{64})\nsize ([0-9]+)\n?",
        committed,
    )
    if pointer:
        payload_sha = pointer.group(1).decode("ascii")
        payload_size = int(pointer.group(2))
        if (
            payload_sha != spec["source_sha256"]
            or payload_size != int(spec["source_size_bytes"])
        ):
            raise ValueError(f"Git LFS pointer differs: {source_path}")
        transport = "github_lfs_media"
        resolve_url = (
            f"https://media.githubusercontent.com/media/{GIT_REPOSITORY}/"
            f"{GIT_REVISION}/{source_path}"
        )
    else:
        committed_sha = hashlib.sha256(committed).hexdigest()
        if (
            committed_sha != spec["source_sha256"]
            or len(committed) != int(spec["source_size_bytes"])
        ):
            raise ValueError(f"Committed Git bytes differ: {source_path}")
        transport = "github_git_blob"
        payload_sha = committed_sha
        payload_size = len(committed)
        resolve_url = (
            f"https://raw.githubusercontent.com/{GIT_REPOSITORY}/"
            f"{GIT_REVISION}/{source_path}"
        )
    lid = locator_id(transport, GIT_REPOSITORY, GIT_REVISION, source_path)
    return base_locator_row(
        locator_id_value=lid,
        asset_id_value=asset_row["asset_id"],
        transport=transport,
        provider="github",
        repository=GIT_REPOSITORY,
        revision=GIT_REVISION,
        relative_path=source_path,
        immutable_resolve_url=resolve_url,
        provenance_url=(
            f"https://github.com/{GIT_REPOSITORY}/blob/{GIT_REVISION}/{source_path}"
        ),
        expected_size_bytes=payload_size,
        expected_sha256=payload_sha,
        publication_record_id=f"git_audit:{GIT_REVISION}",
    )


for asset_row in ASSET_ROWS:
    spec = SPEC_BY_ASSET_ID[asset_row["asset_id"]]
    if spec["derivation_type"] != "none":
        continue
    remote = publication_locator(asset_row, spec)
    if remote is None:
        remote = bundle_locator(asset_row, spec)
    if remote is None:
        remote = git_locator(asset_row, spec)
    if remote is not None:
        LOCATOR_ROWS.append(remote)

ASSET_LOCATORS = validate_output_frame(
    pd.DataFrame(LOCATOR_ROWS),
    "asset_locators",
).sort_values(["asset_id", "transport", "locator_id"]).reset_index(drop=True)

print("Immutable locators compiled:", len(ASSET_LOCATORS))
print("Locator transports:", ASSET_LOCATORS["transport"].value_counts().to_dict())

Immutable locators compiled: 81
Locator transports: {'local_package': 48, 'github_lfs_media': 22, 'huggingface_bundle_member': 5, 'huggingface_object': 4, 'github_git_blob': 2}

In [36]:
locator_ids_by_asset = (
    ASSET_LOCATORS.groupby("asset_id")["locator_id"]
    .apply(lambda values: sorted(values.astype(str).tolist()))
    .to_dict()
)
remote_asset_ids = set(
    ASSET_LOCATORS.loc[
        ~ASSET_LOCATORS["transport"].eq("local_package"),
        "asset_id",
    ]
)
for row in ASSET_ROWS:
    ids = locator_ids_by_asset.get(row["asset_id"], [])
    row["locator_ids_json"] = canonical_text(ids)
    if row["asset_id"] in remote_asset_ids:
        row["availability_state"] = "available_local_and_remote"
        row["availability_reason"] = (
            "Registered local rendition and checksum-verified immutable exact-source route."
        )
    else:
        row["availability_state"] = "available_local"
        row["availability_reason"] = (
            "Registered local rendition; no complete offline remote chain was emitted."
        )

DASHBOARD_ASSETS = validate_output_frame(
    pd.DataFrame(ASSET_ROWS),
    "dashboard_assets",
).sort_values(["evidence_role", "asset_id"]).reset_index(drop=True)

STAGED_BATCH_7_PATHS = {
    "dashboard_assets": (
        STAGING_PACKAGE_ROOT / SETTINGS["output"]["dashboard_assets_path"]
    ),
    "asset_locators": (
        STAGING_PACKAGE_ROOT / SETTINGS["output"]["asset_locators_path"]
    ),
    "renditions": (
        STAGING_PACKAGE_ROOT / SETTINGS["output"]["renditions_manifest_path"]
    ),
}

atomic_write_parquet(DASHBOARD_ASSETS, STAGED_BATCH_7_PATHS["dashboard_assets"])
atomic_write_parquet(ASSET_LOCATORS, STAGED_BATCH_7_PATHS["asset_locators"])
atomic_write_csv(RENDITIONS, STAGED_BATCH_7_PATHS["renditions"])

print("Batch 7 manifests staged:")
for key, path in STAGED_BATCH_7_PATHS.items():
    print(" ", key, path.relative_to(PROJECT_ROOT).as_posix())

Batch 7 manifests staged:
  dashboard_assets outputs/34_final_streamlit_dashboard_assets/work/release_release_c5edf0d0ec99affbfa403726/manifests/dashboard_assets.parquet
  asset_locators outputs/34_final_streamlit_dashboard_assets/work/release_release_c5edf0d0ec99affbfa403726/manifests/asset_locators.parquet
  renditions outputs/34_final_streamlit_dashboard_assets/work/release_release_c5edf0d0ec99affbfa403726/manifests/renditions.csv

In [37]:
remote_locators = ASSET_LOCATORS.loc[
    ~ASSET_LOCATORS["transport"].eq("local_package")
].copy()
bundle_locators = ASSET_LOCATORS.loc[
    ASSET_LOCATORS["transport"].eq("huggingface_bundle_member")
].copy()

rendition_budget_failures = []
for row in RENDITIONS.itertuples(index=False):
    rule = PROFILE_RULES[row.profile]
    path = STAGING_PACKAGE_ROOT / row.relative_path
    failures = []
    if not path.is_file():
        failures.append("missing")
    else:
        if path.stat().st_size != int(row.size_bytes):
            failures.append("size")
        if sha256_file(path) != row.sha256:
            failures.append("sha256")
    if max(int(row.width), int(row.height)) > int(rule["max_edge"]):
        failures.append("dimensions")
    if int(row.size_bytes) > int(rule["hard_bytes"]):
        failures.append("budget")
    if bool(row.upscaled):
        failures.append("upscaled")
    if row.profile == "diagnostic_preview" and (
        row.format != "PNG" or not bool(row.lossless)
    ):
        failures.append("diagnostic_not_lossless_png")
    if failures:
        rendition_budget_failures.append(
            {"rendition_id": row.rendition_id, "failures": failures}
        )

remote_revision_failures = remote_locators.loc[
    ~remote_locators["revision"].map(is_full_git_revision)
, "locator_id"].astype(str).tolist()
mutable_url_failures = remote_locators.loc[
    remote_locators["immutable_resolve_url"]
    .astype(str)
    .str.contains(r"/resolve/main/|/(?:blob|raw)/main/", regex=True)
, "locator_id"].astype(str).tolist()
remote_checksum_failures = remote_locators.loc[
    ~remote_locators["expected_sha256"].map(is_sha256)
, "locator_id"].astype(str).tolist()
bundle_chain_failures = []
for row in bundle_locators.itertuples(index=False):
    required = {
        "release_id": row.release_id,
        "release_prefix": row.release_prefix,
        "catalogue_path": row.catalogue_path,
        "catalogue_size_bytes": row.catalogue_size_bytes,
        "catalogue_sha256": row.catalogue_sha256,
        "painting_id": row.painting_id,
        "remote_asset_id": row.remote_asset_id,
        "bundle_member_path": row.bundle_member_path,
        "bundle_member_size_bytes": row.bundle_member_size_bytes,
        "bundle_member_sha256": row.bundle_member_sha256,
    }
    if (
        any(value is None or (isinstance(value, str) and not value) for value in required.values())
        or not is_sha256(row.catalogue_sha256)
        or not is_sha256(row.bundle_member_sha256)
    ):
        bundle_chain_failures.append(row.locator_id)

asset_rendition_failures = sorted(
    set(DASHBOARD_ASSETS["asset_id"])
    - set(RENDITIONS["asset_id"])
)
asset_local_locator_failures = sorted(
    set(DASHBOARD_ASSETS["asset_id"])
    - set(
        ASSET_LOCATORS.loc[
            ASSET_LOCATORS["transport"].eq("local_package"),
            "asset_id",
        ]
    )
)
referential_failures = []
rendition_id_set = set(RENDITIONS["rendition_id"].astype(str))
locator_id_set = set(ASSET_LOCATORS["locator_id"].astype(str))
asset_sha_by_id = DASHBOARD_ASSETS.set_index("asset_id")["source_sha256"].to_dict()
for row in DASHBOARD_ASSETS.itertuples(index=False):
    if set(json.loads(row.rendition_ids_json)) - rendition_id_set:
        referential_failures.append(f"{row.asset_id}:rendition_ids")
    if set(json.loads(row.locator_ids_json)) - locator_id_set:
        referential_failures.append(f"{row.asset_id}:locator_ids")
for row in RENDITIONS.itertuples(index=False):
    if asset_sha_by_id.get(row.asset_id) != row.source_sha256:
        referential_failures.append(f"{row.rendition_id}:source_sha256")
for row in ASSET_LOCATORS.loc[
    ASSET_LOCATORS["transport"].eq("local_package")
].itertuples(index=False):
    matches = RENDITIONS.loc[RENDITIONS["relative_path"].eq(row.relative_path)]
    if (
        len(matches) != 1
        or str(matches.iloc[0]["asset_id"]) != row.asset_id
        or str(matches.iloc[0]["sha256"]) != row.expected_sha256
        or int(matches.iloc[0]["size_bytes"]) != int(row.expected_size_bytes)
    ):
        referential_failures.append(f"{row.locator_id}:local_target")

derived_source_failures = []
for row in DASHBOARD_ASSETS.loc[
    DASHBOARD_ASSETS["producer_notebook_id"].eq("34")
].itertuples(index=False):
    path = STAGING_PACKAGE_ROOT / row.source_relative_path
    if (
        not path.is_file()
        or path.stat().st_size != int(row.source_size_bytes)
        or sha256_file(path) != row.source_sha256
    ):
        derived_source_failures.append(row.asset_id)

registered_mockups = sorted(
    path
    for path in DASHBOARD_ASSETS["source_relative_path"].astype(str)
    if "docs/dashboard_design_finalists/approved_current/" in path
)
package_bytes = sum(
    path.stat().st_size
    for path in STAGING_PACKAGE_ROOT.rglob("*")
    if path.is_file()
)
manifest_reload_counts = {
    "dashboard_assets": len(pd.read_parquet(STAGED_BATCH_7_PATHS["dashboard_assets"])),
    "asset_locators": len(pd.read_parquet(STAGED_BATCH_7_PATHS["asset_locators"])),
    "renditions": len(pd.read_csv(STAGED_BATCH_7_PATHS["renditions"])),
}

BATCH_7_CHECKS = [
    ("responsibility_ids", list(BATCH_7_RESPONSIBILITY_IDS), ["R09", "R10"]),
    ("logical_asset_uniqueness", DASHBOARD_ASSETS["asset_id"].nunique(), len(DASHBOARD_ASSETS)),
    ("rendition_id_uniqueness", RENDITIONS["rendition_id"].nunique(), len(RENDITIONS)),
    ("locator_id_uniqueness", ASSET_LOCATORS["locator_id"].nunique(), len(ASSET_LOCATORS)),
    ("every_asset_has_rendition", asset_rendition_failures, []),
    ("every_asset_has_local_locator", asset_local_locator_failures, []),
    ("manifest_referential_closure", referential_failures, []),
    ("derived_source_lineage", derived_source_failures, []),
    ("rendition_lineage_and_budgets", rendition_budget_failures, []),
    ("rerun_rendition_bytes", RERUN_RENDITION_DIFFERENCES, []),
    ("remote_full_revisions", remote_revision_failures, []),
    ("remote_immutable_urls", mutable_url_failures, []),
    ("remote_expected_checksums", remote_checksum_failures, []),
    ("bundle_checksum_chains", bundle_chain_failures, []),
    ("mockup_backgrounds_registered", registered_mockups, []),
    ("startup_network_requests", 0, SETTINGS["runtime_budgets"]["startup_network_requests"]),
    (
        "local_package_hard_budget",
        package_bytes <= SETTINGS["runtime_budgets"]["local_package_hard_bytes"],
        True,
    ),
    (
        "manifest_reload_counts",
        manifest_reload_counts,
        {
            "dashboard_assets": len(DASHBOARD_ASSETS),
            "asset_locators": len(ASSET_LOCATORS),
            "renditions": len(RENDITIONS),
        },
    ),
]

for check_name, observed, expected in BATCH_7_CHECKS:
    passed = observed == expected
    add_check(
        BATCH_7_STAGE,
        check_name,
        observed,
        expected,
        passed,
        "" if passed else "R09/R10 registered-asset contract differs.",
    )

require_no_blocking_failures("Batch 7 R09/R10 registered assets")

BATCH_7_VALIDATION = current_validation_frame().loc[
    lambda frame: frame["validation_stage"].eq(BATCH_7_STAGE)
].reset_index(drop=True)

display(
    RENDITIONS.groupby(["profile", "format"], as_index=False)
    .agg(renditions=("rendition_id", "size"), bytes=("size_bytes", "sum"))
)
display(
    ASSET_LOCATORS.groupby("transport", as_index=False)
    .agg(locators=("locator_id", "size"))
)
display(
    BATCH_7_VALIDATION[
        ["check_description", "severity", "passed", "observed"]
    ]
)

print("Batch 7 R09/R10 passed.")
print("Logical assets:", len(DASHBOARD_ASSETS))
print("Registered renditions:", len(RENDITIONS))
print("Immutable locators:", len(ASSET_LOCATORS))
print("Remote exact-source locators:", len(remote_locators))
print("Bundle-member checksum chains:", len(bundle_locators))
print("Staged package bytes after Batch 7:", package_bytes)
print("Network requests performed:", 0)

              profile format  renditions    bytes
0  diagnostic_preview    PNG          19  1100295
1            standard   WEBP          23   536582
2               thumb    PNG           3    49978
3               thumb   WEBP           3    17192

                   transport  locators
0            github_git_blob         2
1           github_lfs_media        22
2  huggingface_bundle_member         5
3         huggingface_object         4
4              local_package        48

,check_description,severity,passed,observed
0,responsibility_ids,blocking,True,"[""R09"", ""R10""]"
1,logical_asset_uniqueness,blocking,True,42
2,rendition_id_uniqueness,blocking,True,48
3,locator_id_uniqueness,blocking,True,81
4,every_asset_has_rendition,blocking,True,[]
5,every_asset_has_local_locator,blocking,True,[]
6,manifest_referential_closure,blocking,True,[]
7,derived_source_lineage,blocking,True,[]
8,rendition_lineage_and_budgets,blocking,True,[]
9,rerun_rendition_bytes,blocking,True,[]
10,remote_full_revisions,blocking,True,[]
11,remote_immutable_urls,blocking,True,[]
12,remote_expected_checksums,blocking,True,[]
13,bundle_checksum_chains,blocking,True,[]
14,mockup_backgrounds_registered,blocking,True,[]
15,startup_network_requests,blocking,True,0
16,local_package_hard_budget,blocking,True,True
17,manifest_reload_counts,blocking,True,"{""asset_locators"": 81, ""dashboard_assets"": 42,..."

Batch 7 R09/R10 passed.
Logical assets: 42
Registered renditions: 48
Immutable locators: 81
Remote exact-source locators: 33
Bundle-member checksum chains: 5
Staged package bytes after Batch 7: 7126011
Network requests performed: 0

## Batch 8 — Binding closure, trust manifests, atomic promotion, and final verification

This final batch closes the approved display contract and promotes the staged
Controlled-300 dashboard package. It:

- persists the zero-network bootstrap, room catalogue, glossary, and report index;
- resolves the four temporary derivation states left by Batch 5;
- binds every approved `display_id` to its compact data record and, where
applicable, to registered evidence assets;
- writes the room, runtime, artifact, run, and validation manifests;
- enforces schema, identity, checksum, size, provenance, and package-budget gates;
- atomically promotes the completed release out of `work/`; and
- verifies that rerunning this batch recognizes and checks the existing release
without recreating work files or changing scientific identity.

No network request is made. The approved concept mockups remain design references
only and are not registered as evidence or copied into the runtime package.

In [38]:
import gzip
import hashlib
import os
import subprocess
from copy import deepcopy

from restoration_eval.dashboard_assets import (
    DISPLAY_COMPONENT_COLUMNS,
    ROOM_PARTITION_COLUMNS,
    atomic_write_csv,
    atomic_write_json,
    atomic_write_json_gzip,
    atomic_write_parquet,
    binding_id,
    is_full_git_revision,
    is_repo_relative,
    is_sha256,
    path_statistics,
    stable_id,
    validate_output_frame,
)
from restoration_eval.manifests import (
    MANIFESTS_MODULE_VERSION,
    artifact_records_dataframe,
    build_artifact_record,
    build_run_manifest,
    configuration_checksums,
    git_state,
)


BATCH_8_STAGE = "batch_8_binding_promotion"
PROMOTION_CANDIDATE = (
    OUTPUT_ROOT.parent
    / f".{OUTPUT_ROOT.name}.{DASHBOARD_RELEASE_ID}.promote"
)
CANONICAL_RUNTIME_PATH = (
    OUTPUT_ROOT / SETTINGS["output"]["runtime_manifest_path"]
)


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def runtime_release_id(path: Path) -> str | None:
    if not path.is_file():
        return None
    try:
        return str(load_json(path).get("release_id"))
    except (OSError, ValueError, TypeError):
        return None


canonical_release = runtime_release_id(CANONICAL_RUNTIME_PATH)
promotion_runtime_path = (
    PROMOTION_CANDIDATE
    / SETTINGS["output"]["runtime_manifest_path"]
)

if canonical_release == DASHBOARD_RELEASE_ID:
    BATCH_8_MODE = "verify_existing"
    ACTIVE_PACKAGE_ROOT = OUTPUT_ROOT
elif STAGING_PACKAGE_ROOT.is_dir():
    BATCH_8_MODE = "build_and_promote"
    ACTIVE_PACKAGE_ROOT = STAGING_PACKAGE_ROOT
elif runtime_release_id(promotion_runtime_path) == DASHBOARD_RELEASE_ID:
    BATCH_8_MODE = "recover_promotion"
    ACTIVE_PACKAGE_ROOT = PROMOTION_CANDIDATE
else:
    raise RuntimeError(
        "Batch 8 found neither the staged release nor an already promoted "
        "Controlled-300 release. Run Batches 1–7 in order first."
    )

BUILDING_NEW_RELEASE = BATCH_8_MODE == "build_and_promote"


def package_path(output_key: str) -> Path:
    return ACTIVE_PACKAGE_ROOT / SETTINGS["output"][output_key]


def package_relative(path: Path) -> str:
    return path.relative_to(ACTIVE_PACKAGE_ROOT).as_posix()


if BUILDING_NEW_RELEASE:
    # Persist the three Batch 3 payloads that intentionally remained in memory.
    atomic_write_json(BOOTSTRAP, package_path("bootstrap_path"))
    atomic_write_json(ROOM_CATALOGUE, package_path("room_catalogue_path"))
    atomic_write_json(GLOSSARY, package_path("glossary_path"))

    REPORT_INDEX_PAYLOAD = {
        "schema_version": SETTINGS["expected_output_schemas"]["report_index"],
        "release_id": DASHBOARD_RELEASE_ID,
        "report_count": int(len(REPORT_DIMENSION)),
        "reports": [
            {
                "report_id": str(row.report_id),
                "report_type": str(row.report_type),
                "entity_id": str(row.entity_id),
                "report_path": str(row.report_path),
                "report_sha256": str(row.report_sha256),
                "self_contained": bool(row.self_contained),
                "status": str(row.status),
            }
            for row in REPORT_DIMENSION.itertuples(index=False)
        ],
        "status": "ok",
    }
    REPORT_INDEX_GZIP_METADATA = atomic_write_json_gzip(
        REPORT_INDEX_PAYLOAD,
        package_path("report_index_path"),
    )

    # Resolve the four planning-only states now that Batches 6 and 7 produced
    # and registered their evidence. All other room records retain their exact
    # approved state and wording.
    DERIVED_DISPLAY_PAYLOADS = {
        "trust.threshold.strata": (
            SETTINGS["output"]["threshold_strata_path"],
            ["threshold_strata"],
        ),
        "d02.anchor.difference": (
            SETTINGS["output"]["dashboard_assets_path"],
            ["d02_r005_difference_crop"],
        ),
        "d02.r005.panel": (
            SETTINGS["output"]["dashboard_assets_path"],
            ["d02_r005_review_panel"],
        ),
        "d02.r005.control": (
            SETTINGS["output"]["d02_r005_geometry_path"],
            ["d02_r005_matched_control"],
        ),
    }

    UPDATED_ROOM_PARTITIONS: dict[str, pd.DataFrame] = {}
    for room in ROOM_CATALOGUE_FRAME.itertuples(index=False):
        room_id = str(room.room_id)
        relative_path = str(room.partition_path)
        frame = pd.read_parquet(ACTIVE_PACKAGE_ROOT / relative_path)
        for row_index in frame.index:
            display_id_value = str(frame.at[row_index, "display_id"])
            if display_id_value not in DERIVED_DISPLAY_PAYLOADS:
                continue
            derived_path, source_ids = DERIVED_DISPLAY_PAYLOADS[display_id_value]
            value = json.loads(str(frame.at[row_index, "value_json"]))
            value["mapping_state"] = "n34_derived_registered"
            value["mapping_states"] = ["n34_derived_registered"]
            value["derived_payload_ref"] = derived_path
            frame.at[row_index, "value_json"] = canonical_json_bytes(value).decode("utf-8")
            frame.at[row_index, "applicability_state"] = "available"
            frame.at[row_index, "source_paths_json"] = json.dumps(
                sorted(
                    set(json.loads(frame.at[row_index, "source_paths_json"]))
                    | {derived_path}
                ),
                ensure_ascii=False,
            )
            frame.at[row_index, "source_row_ids_json"] = json.dumps(
                source_ids,
                ensure_ascii=False,
            )
        frame = validate_output_frame(frame, "room_records")
        atomic_write_parquet(frame, ACTIVE_PACKAGE_ROOT / relative_path)
        UPDATED_ROOM_PARTITIONS[room_id] = frame
else:
    REPORT_INDEX_PAYLOAD = None
    REPORT_INDEX_GZIP_METADATA = None
    UPDATED_ROOM_PARTITIONS = {
        row.room_id: pd.read_parquet(
            ACTIVE_PACKAGE_ROOT / row.partition_path
        )
        for row in ROOM_CATALOGUE_FRAME.itertuples(index=False)
    }


ROOM_RECORDS_FINAL = pd.concat(
    [UPDATED_ROOM_PARTITIONS[room_id] for room_id in EXPECTED_ALL_ROOM_IDS],
    ignore_index=True,
)
ROOM_RECORDS_FINAL = validate_output_frame(ROOM_RECORDS_FINAL, "room_records")

DASHBOARD_ASSETS_FINAL = pd.read_parquet(package_path("dashboard_assets_path"))
ASSET_LOCATORS_FINAL = pd.read_parquet(package_path("asset_locators_path"))
RENDITIONS_FINAL = pd.read_csv(package_path("renditions_manifest_path"), low_memory=False)

# The approved Case Explorer contract requires the fourteen exact N29
# counterfactual panels. Register them as pinned, lazy remote assets without
# altering any valid Batch 7 supporting asset or loading a network resource.
COUNTERFACTUAL_PANEL_IDS = [
    f"cf_{family}_{index:02d}"
    for family in (
        "cross_model", "damage_size", "diffusion_seed",
        "evidence_family_removal", "mask_placement", "metric_subset",
        "prompt_policy",
    )
    for index in (1, 2)
]

if BUILDING_NEW_RELEASE:
    existing_counterfactuals = DASHBOARD_ASSETS_FINAL.loc[
        DASHBOARD_ASSETS_FINAL["evidence_role"].eq("counterfactual_panel")
    ]
    if existing_counterfactuals.empty:
        counterfactual_asset_rows = []
        counterfactual_locator_rows = []
        producer_manifest = UPSTREAM_MANIFESTS["29"]
        producer_manifest_sha = str(MANIFEST_SPECS["29"]["sha256"]).lower()

        for panel_id in COUNTERFACTUAL_PANEL_IDS:
            relative_path = (
                "outputs/29_explainable_ai_and_case_retrieval/"
                f"figures/counterfactual_panels/{panel_id}.png"
            )
            source = hash_record(relative_path)
            width, height = image_geometry(relative_path)
            identity = canonical_identity(evidence_layer=panel_id)
            asset_id_value = asset_id(
                identity,
                source["sha256"],
                "counterfactual_panel",
            )
            asset_row = {
                "asset_id": asset_id_value,
                "asset_kind": "image",
                "evidence_role": "counterfactual_panel",
                "requiredness": "required",
                "mapping_state": "existing_direct",
                "identity_json": canonical_text(identity),
                "producer_notebook_id": "29",
                "producer_notebook_stem": str(producer_manifest["notebook_name"]),
                "producer_run_id": str(producer_manifest["run_id"]),
                "producer_manifest_sha256": producer_manifest_sha,
                "source_artifact_key": "counterfactual_panel",
                "source_relative_path": relative_path,
                "source_sha256": source["sha256"],
                "source_size_bytes": int(source["size_bytes"]),
                "mime_type": "image/png",
                "source_row_id": panel_id,
                "source_selector_json": canonical_text({"panel_id": panel_id}),
                "width": int(width),
                "height": int(height),
                "denominator": "14 selected panels",
                "derivation_type": "none",
                "derivation_parameters_json": "{}",
                "helper_version": DASHBOARD_ASSETS_VERSION,
                "input_checksums_json": canonical_text([source]),
                "output_sha256": source["sha256"],
                "rendition_ids_json": "[]",
                "locator_ids_json": "[]",
                "availability_state": "available_remote",
                "availability_reason": (
                    "Exact N29 panel is fetched only after the visitor opens "
                    "the controlled-change drawer."
                ),
                "alternative_text": (
                    f"N29 controlled-change panel {panel_id.replace('_', ' ')}."
                ),
                "schema_version": SETTINGS["expected_output_schemas"]["dashboard_assets"],
                "status": "ok",
                "issue": "",
            }
            locator = git_locator(
                asset_row,
                {
                    "relative_path": relative_path,
                    "source_sha256": source["sha256"],
                    "source_size_bytes": int(source["size_bytes"]),
                },
            )
            if locator is None:
                raise RuntimeError(
                    f"No immutable Git locator exists for {relative_path}."
                )
            asset_row["locator_ids_json"] = canonical_text([locator["locator_id"]])
            counterfactual_asset_rows.append(asset_row)
            counterfactual_locator_rows.append(locator)

        DASHBOARD_ASSETS_FINAL = validate_output_frame(
            pd.concat(
                [DASHBOARD_ASSETS_FINAL, pd.DataFrame(counterfactual_asset_rows)],
                ignore_index=True,
            ),
            "dashboard_assets",
        ).sort_values("asset_id").reset_index(drop=True)
        ASSET_LOCATORS_FINAL = validate_output_frame(
            pd.concat(
                [ASSET_LOCATORS_FINAL, pd.DataFrame(counterfactual_locator_rows)],
                ignore_index=True,
            ),
            "asset_locators",
        ).sort_values(["asset_id", "transport", "locator_id"]).reset_index(drop=True)
        RENDITIONS_FINAL = validate_output_frame(
            RENDITIONS_FINAL,
            "renditions",
        ).sort_values(["asset_id", "profile", "rendition_id"]).reset_index(drop=True)

        atomic_write_parquet(
            DASHBOARD_ASSETS_FINAL,
            package_path("dashboard_assets_path"),
        )
        atomic_write_parquet(
            ASSET_LOCATORS_FINAL,
            package_path("asset_locators_path"),
        )
        atomic_write_csv(
            RENDITIONS_FINAL,
            package_path("renditions_manifest_path"),
        )

    # Remove only rendition files no longer declared by the corrected staging
    # manifest. This also makes a retry safe after interruption mid-correction.
    declared_rendition_paths = set(RENDITIONS_FINAL["relative_path"].astype(str))
    renditions_root = ACTIVE_PACKAGE_ROOT / SETTINGS["output"]["renditions_dir"]
    if renditions_root.exists():
        for rendition_path in renditions_root.rglob("*"):
            if (
                rendition_path.is_file()
                and rendition_path.relative_to(ACTIVE_PACKAGE_ROOT).as_posix()
                not in declared_rendition_paths
            ):
                rendition_path.unlink()

observed_counterfactual_ids = sorted(
    DASHBOARD_ASSETS_FINAL.loc[
        DASHBOARD_ASSETS_FINAL["evidence_role"].eq("counterfactual_panel"),
        "source_row_id",
    ].astype(str)
)
if observed_counterfactual_ids != COUNTERFACTUAL_PANEL_IDS:
    raise RuntimeError(
        "Counterfactual asset closure differs from the approved N29 panel set: "
        f"{observed_counterfactual_ids}"
    )

print("Batch 8 mode:", BATCH_8_MODE)
print("Active release root:", ACTIVE_PACKAGE_ROOT)
print("Final room records:", len(ROOM_RECORDS_FINAL))
print(
    "Remaining pending derivations:",
    int(ROOM_RECORDS_FINAL["applicability_state"].eq("pending_derivation").sum()),
)

Batch 8 mode: build_and_promote
Active release root: D:\Masters\FH\Thesis\painting-restoration-eval\outputs\34_final_streamlit_dashboard_assets\work\release_release_c5edf0d0ec99affbfa403726
Final room records: 100
Remaining pending derivations: 0

C:\Users\rahul\AppData\Local\Temp\ipykernel_29948\3502225712.py:289: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  pd.concat(

In [40]:
IDENTITY_FIELDS = [
    "painting_id", "case_id", "candidate_id", "model_id", "experiment_id",
    "seed", "prompt_variant_id", "uncertainty_group_id", "metric_name",
    "region_id", "evidence_layer", "annotation_id", "hand_control_id",
    "review_unit_id", "blind_review_code",
]

ASSET_RECORDS = {
    str(row["asset_id"]): row
    for row in DASHBOARD_ASSETS_FINAL.to_dict(orient="records")
}


def matching_asset_ids(
    *,
    role: str | None = None,
    source_row_id: str | None = None,
    **identity_filters,
) -> list[str]:
    matches = []
    for asset_id_value, row in ASSET_RECORDS.items():
        if role is not None and str(row["evidence_role"]) != role:
            continue
        if source_row_id is not None and str(row["source_row_id"]) != source_row_id:
            continue
        identity = json.loads(str(row["identity_json"]))
        if all(identity.get(key) == value for key, value in identity_filters.items()):
            matches.append(asset_id_value)
    return sorted(matches)


def only_asset(**criteria) -> str:
    matches = matching_asset_ids(**criteria)
    if len(matches) != 1:
        raise ValueError(f"Expected one asset for {criteria}, observed {matches}.")
    return matches[0]


def candidate_asset(candidate_id_value: str) -> str:
    return only_asset(role="restoration_candidate", candidate_id=candidate_id_value)


P018_CASE = "canonical__p018__mixed_damage"
P002_CASE = "canonical__p002__loss_large"
P269_CASE = "canonical__p269__mixed_damage"
P018_DAMAGE_SIZE_CASE = "damage_size__p018__loss_large__size_20pct"

DISPLAY_ASSET_BINDINGS: dict[str, list[tuple[str, str]]] = {
    "foyer.hero.p001": [
        ("hero", only_asset(role="clean_reference", painting_id="p001")),
    ],
    "metric.anchor.images": [
        ("clean", only_asset(role="clean_reference", painting_id="p018")),
        ("mask", only_asset(role="damage_mask", case_id=P018_CASE)),
        ("damaged", only_asset(role="damaged_input", case_id=P018_CASE)),
        ("restored", candidate_asset("candidate__lama__canonical__p018__mixed_damage__c00")),
    ],
    "metric.anchor.signed_improvement": [
        ("map", only_asset(role="signed_improvement_map")),
    ],
    "metric.lens.local": [
        ("colour", only_asset(role="local_colour_map")),
        ("texture", only_asset(role="local_texture_map")),
        ("seam", only_asset(role="local_seam_map")),
    ],
    "metric.lens.semantic": [
        ("semantic", only_asset(role="semantic_map")),
    ],
    "models.anchor.input": [
        ("damaged", only_asset(role="damaged_input", case_id=P018_CASE)),
        ("mask", only_asset(role="damage_mask", case_id=P018_CASE)),
    ],
    "models.output.telea": [
        ("telea", candidate_asset("candidate__opencv_telea__canonical__p018__mixed_damage__c00")),
    ],
    "models.output.lama": [
        ("lama", candidate_asset("candidate__lama__canonical__p018__mixed_damage__c00")),
    ],
    "models.output.hint": [
        ("hint", candidate_asset("candidate__hint_places2__canonical__p018__mixed_damage__c00")),
    ],
    "models.output.sd15": [
        ("sd15", candidate_asset("sd15__p00__s2026__d0cd65cf894a")),
    ],
    "models.output.sdxl": [
        ("sdxl", candidate_asset("sdxl__5d3f1bc4bed2__p00_generic__seed2026")),
    ],
    "stability.anchor.images": [
        ("clean", only_asset(role="clean_reference", painting_id="p018")),
        ("damaged", only_asset(role="damaged_input", case_id=P018_DAMAGE_SIZE_CASE)),
        ("mask", only_asset(role="damage_mask", case_id=P018_DAMAGE_SIZE_CASE)),
        ("restored", candidate_asset("candidate__lama__damage_size__p018__loss_large__size_20pct__c00")),
    ],
    "stability.damage.trajectory": [
        ("trajectory", only_asset(role="stability_trajectory_chart")),
    ],
    "stability.seed.group": [
        ("contact_sheet", only_asset(role="stability_contact_sheet")),
        *[
            (f"seed_{seed}", only_asset(role="restoration_candidate", uncertainty_group_id="ug_1de955f7e0f3d00cf0", seed=seed))
            for seed in (2026, 2027, 2028, 2029)
        ],
    ],
    "stability.seed.overlay": [
        ("overlay", only_asset(role="uncertainty_overlay")),
    ],
    "trust.anchor.triad": [
        ("clean", only_asset(role="clean_reference", painting_id="p002")),
        ("damaged", only_asset(role="damaged_input", case_id=P002_CASE)),
        ("restored", candidate_asset("sd15__p00__s2026__29ff258ff921")),
    ],
    "trust.anchor.peers": [
        ("telea", candidate_asset("candidate__opencv_telea__canonical__p002__loss_large__c00")),
        ("lama", candidate_asset("candidate__lama__canonical__p002__loss_large__c00")),
        ("hint", candidate_asset("candidate__hint_places2__canonical__p002__loss_large__c00")),
        ("sd15", candidate_asset("sd15__p00__s2026__29ff258ff921")),
    ],
    "d02.anchor.images": [
        ("clean", only_asset(role="clean_reference", painting_id="p269")),
        ("damaged", only_asset(role="damaged_input", case_id=P269_CASE)),
        ("mask", only_asset(role="damage_mask", case_id=P269_CASE)),
        ("restored", candidate_asset("candidate__hint_places2__canonical__p269__mixed_damage__c00")),
    ],
    "d02.anchor.difference": [
        ("difference", only_asset(role="d02_r005_difference_crop")),
    ],
    "d02.hand.findings": [
        ("summary_figure", only_asset(role="d02_hand_summary_figure")),
    ],
    "d02.lightness.findings": [
        ("summary_figure", only_asset(role="d02_lightness_summary_figure")),
    ],
    "d02.r005.panel": [
        ("review_panel", only_asset(role="d02_r005_review_panel")),
    ],
    "d02.r005.control": [
        ("matched_control", only_asset(role="d02_r005_matched_control")),
    ],
    "case.anchor.views": [
        ("clean", only_asset(role="clean_reference", painting_id="p018")),
        ("damaged", only_asset(role="damaged_input", case_id=P018_CASE)),
        ("mask", only_asset(role="damage_mask", case_id=P018_CASE)),
        ("restored", candidate_asset("candidate__lama__canonical__p018__mixed_damage__c00")),
    ],
    "case.anchor.difference": [
        ("difference", only_asset(role="signed_improvement_map")),
    ],
    "case.anchor.local": [
        ("colour", only_asset(role="local_colour_map")),
        ("texture", only_asset(role="local_texture_map")),
        ("seam", only_asset(role="local_seam_map")),
    ],
    "case.anchor.semantic": [
        ("semantic", only_asset(role="semantic_map")),
    ],
    "case.anchor.uncertainty": [
        ("uncertainty", only_asset(role="uncertainty_overlay")),
    ],
    "case.retrieval": [
        ("retrieval", only_asset(role="retrieval_panel")),
    ],
    "case.counterfactuals": [
        (
            panel_id,
            only_asset(role="counterfactual_panel", source_row_id=panel_id),
        )
        for panel_id in COUNTERFACTUAL_PANEL_IDS
    ],
    "archive.n33.ledger": [
        ("evidence_map", only_asset(role="archive_evidence_map")),
    ],
}

DERIVED_DATA_BINDINGS = {
    "trust.threshold.strata": SETTINGS["output"]["threshold_strata_path"],
    "stability.damage.trajectory": SETTINGS["output"]["stability_trajectories_path"],
    "d02.hand.findings": SETTINGS["output"]["d02_hand_summary_path"],
    "d02.lightness.findings": SETTINGS["output"]["d02_lightness_summary_path"],
    "d02.r005.control": SETTINGS["output"]["d02_r005_geometry_path"],
}

REPORT_BINDING_IDS = {
    "models.records", "case.painting.report", "case.case.report",
    "archive.scope.n32_reports", "archive.scope.model_reports",
    "archive.n33.ledger", "archive.d01.record", "archive.n12a.record",
    "archive.d02.record", "archive.limits",
}


def empty_identity() -> dict:
    return {field: None for field in IDENTITY_FIELDS}


def binding_row(
    room_record: dict,
    *,
    slot_suffix: str,
    payload_ref: str,
    component_kind: str,
    source_reference_ids: list[str],
    identity: dict | None = None,
    mapping_state: str | None = None,
) -> dict:
    identity_values = empty_identity()
    identity_values.update(identity or {})
    handoff = json.loads(str(room_record["value_json"])).get("handoff", "")
    conditional = (
        str(room_record["applicability_state"]) == "conditional"
        or "conditional" in str(handoff).lower()
    )
    slot_id_value = (
        str(room_record["slot_id"])
        if slot_suffix == "record"
        else f"{room_record['slot_id']}:{slot_suffix}"
    )
    return {
        "binding_id": binding_id(
            str(room_record["display_id"]), slot_id_value, payload_ref
        ),
        "display_id": str(room_record["display_id"]),
        "slot_id": slot_id_value,
        "room_id": str(room_record["room_id"]),
        "subroute_id": (
            None if pd.isna(room_record["subroute_id"])
            else str(room_record["subroute_id"])
        ),
        "display_order": int(room_record["display_order"]),
        "component_kind": component_kind,
        "payload_ref": payload_ref,
        "requiredness": "conditional" if conditional else "required",
        "mapping_state": mapping_state or json.loads(
            str(room_record["value_json"])
        )["mapping_state"],
        "loading_tier": "room_partition",
        **identity_values,
        "source_reference_ids_json": json.dumps(
            source_reference_ids, ensure_ascii=False
        ),
        "interpretation": str(room_record["interpretation"]),
        "limitation": str(room_record["limitation"]),
        "denominator": (
            None if pd.isna(room_record["denominator"])
            else str(room_record["denominator"])
        ),
        "applicability_state": (
            "conditional" if conditional else "available"
        ),
        "applicability_reason": (
            "Available only when the selected identity has this evidence."
            if conditional
            else "Registered evidence is available for this display contract."
        ),
        "schema_version": SETTINGS["expected_output_schemas"]["display_components"],
        "status": "ok",
        "issue": "",
    }


DISPLAY_BINDING_ROWS = []
for room_record in ROOM_RECORDS_FINAL.to_dict(orient="records"):
    display_id_value = str(room_record["display_id"])
    room_path = next(
        row.partition_path
        for row in ROOM_CATALOGUE_FRAME.itertuples(index=False)
        if row.room_id == room_record["room_id"]
    )
    base_payload = f"{room_path}#display_id={display_id_value}"
    if display_id_value in REPORT_BINDING_IDS:
        base_payload = (
            f"{SETTINGS['output']['report_index_path']}"
            f"#display_id={display_id_value}"
        )
    elif display_id_value in DERIVED_DATA_BINDINGS:
        base_payload = DERIVED_DATA_BINDINGS[display_id_value]
    elif display_id_value == "foyer.route.previews":
        base_payload = f"{SETTINGS['output']['bootstrap_path']}#/foyer_route_previews"
    elif display_id_value == "foyer.tour.frames":
        base_payload = f"{SETTINGS['output']['bootstrap_path']}#/guided_tour"

    DISPLAY_BINDING_ROWS.append(
        binding_row(
            room_record,
            slot_suffix="record",
            payload_ref=base_payload,
            component_kind=str(room_record["record_type"]),
            source_reference_ids=json.loads(str(room_record["source_row_ids_json"])),
            mapping_state=json.loads(str(room_record["value_json"]))["mapping_state"],
        )
    )

    for slot_suffix, asset_id_value in DISPLAY_ASSET_BINDINGS.get(
        display_id_value, []
    ):
        asset = ASSET_RECORDS[asset_id_value]
        DISPLAY_BINDING_ROWS.append(
            binding_row(
                room_record,
                slot_suffix=slot_suffix,
                payload_ref=f"asset:{asset_id_value}",
                component_kind="image",
                source_reference_ids=[asset_id_value],
                identity=json.loads(str(asset["identity_json"])),
                mapping_state=str(asset["mapping_state"]),
            )
        )

DISPLAY_COMPONENTS = validate_output_frame(
    pd.DataFrame(DISPLAY_BINDING_ROWS),
    "display_components",
).sort_values(
    ["room_id", "display_order", "slot_id", "binding_id"],
    kind="stable",
).reset_index(drop=True)

if BUILDING_NEW_RELEASE:
    atomic_write_csv(DISPLAY_COMPONENTS, package_path("display_components_path"))
else:
    DISPLAY_COMPONENTS = pd.read_csv(
        package_path("display_components_path"), low_memory=False
    )
    DISPLAY_COMPONENTS = validate_output_frame(
        DISPLAY_COMPONENTS, "display_components"
    )

print("Display contracts bound:", DISPLAY_COMPONENTS["display_id"].nunique())
print("Display-binding rows:", len(DISPLAY_COMPONENTS))
print("Bindings to registered assets:", DISPLAY_COMPONENTS["payload_ref"].str.startswith("asset:").sum())

Display contracts bound: 100
Display-binding rows: 170
Bindings to registered assets: 70

In [41]:
ROOM_PARTITION_ROWS = []
for room in ROOM_CATALOGUE_FRAME.itertuples(index=False):
    path = ACTIVE_PACKAGE_ROOT / room.partition_path
    frame = pd.read_parquet(path)
    ROOM_PARTITION_ROWS.append(
        {
            "partition_id": stable_id(
                "room_partition",
                {
                    "release_id": DASHBOARD_RELEASE_ID,
                    "room_id": room.room_id,
                    "sha256": sha256_file(path),
                },
            ),
            "room_id": str(room.room_id),
            "subroute_id": (
                str(room.room_id)
                if str(room.route_kind) == "child"
                else None
            ),
            "relative_path": str(room.partition_path),
            "loading_tier": "room_partition",
            "row_count": int(len(frame)),
            "size_bytes": int(path.stat().st_size),
            "sha256": sha256_file(path),
            "display_ids_json": json.dumps(
                frame["display_id"].astype(str).tolist(), ensure_ascii=False
            ),
            "schema_version": SETTINGS["expected_output_schemas"]["room_partitions"],
            "status": "ok",
            "issue": "",
        }
    )

ROOM_PARTITION_INDEX_FINAL = validate_output_frame(
    pd.DataFrame(ROOM_PARTITION_ROWS),
    "room_partitions",
).sort_values("relative_path", kind="stable").reset_index(drop=True)

if BUILDING_NEW_RELEASE:
    atomic_write_csv(
        ROOM_PARTITION_INDEX_FINAL,
        package_path("room_partitions_path"),
    )
else:
    ROOM_PARTITION_INDEX_FINAL = validate_output_frame(
        pd.read_csv(package_path("room_partitions_path"), low_memory=False),
        "room_partitions",
    )


def decoded_gzip_metadata(path: Path) -> dict:
    compressed = path.read_bytes()
    with gzip.open(path, "rb") as handle:
        decoded = handle.read()
    return {
        "compressed_size_bytes": len(compressed),
        "compressed_sha256": hashlib.sha256(compressed).hexdigest(),
        "decoded_size_bytes": len(decoded),
        "decoded_sha256": hashlib.sha256(decoded).hexdigest(),
        "gzip_mtime_zero": compressed[4:8] == b"\x00\x00\x00\x00",
    }


TRUSTED_LOCAL_RECORDS = []
for path in sorted(
    candidate
    for candidate in ACTIVE_PACKAGE_ROOT.rglob("*")
    if candidate.is_file()
    and candidate.relative_to(ACTIVE_PACKAGE_ROOT).as_posix()
    not in {
        SETTINGS["output"]["runtime_manifest_path"],
        SETTINGS["output"]["artifacts_path"],
        SETTINGS["output"]["run_manifest_path"],
        SETTINGS["output"]["validation_path"],
    }
):
    relative = package_relative(path)
    loading_tier = (
        "bootstrap" if relative.startswith("data/bootstrap/")
        else "room_partition" if relative.startswith("data/rooms/")
        else "painting_partition" if relative.startswith("data/paintings/")
        else "local_package"
    )
    record = {
        "relative_path": relative,
        "loading_tier": loading_tier,
        "size_bytes": int(path.stat().st_size),
        "sha256": sha256_file(path),
    }
    if relative.endswith(".json.gz"):
        record["compressed_payload"] = decoded_gzip_metadata(path)
    TRUSTED_LOCAL_RECORDS.append(record)

DETERMINISTIC_PACKAGE_SHA256 = hashlib.sha256(
    canonical_json_bytes(TRUSTED_LOCAL_RECORDS)
).hexdigest()

REMOTE_LOCATORS = ASSET_LOCATORS_FINAL.loc[
    ~ASSET_LOCATORS_FINAL["transport"].eq("local_package")
].copy()
TRUSTED_REMOTE_ROOTS = []
for keys, group in REMOTE_LOCATORS.groupby(
    ["provider", "repository", "revision", "release_id", "release_prefix"],
    dropna=False,
    sort=True,
):
    provider, repository, revision, release_id_value, release_prefix = keys
    TRUSTED_REMOTE_ROOTS.append(
        {
            "provider": str(provider),
            "repository": str(repository),
            "revision": str(revision),
            "release_id": None if pd.isna(release_id_value) else str(release_id_value),
            "release_prefix": None if pd.isna(release_prefix) else str(release_prefix),
            "locator_count": int(len(group)),
        }
    )

UPSTREAM_TRUST_RECORDS = []
for logical_id, spec in MANIFEST_SPECS.items():
    UPSTREAM_TRUST_RECORDS.append(
        {
            "logical_notebook_id": logical_id,
            "producer_notebook_id": str(spec["producer_notebook_id"]),
            "path": str(spec["path"]),
            "run_id": str(spec["run_id"]),
            "size_bytes": int(spec["size_bytes"]),
            "sha256": str(spec["sha256"]),
        }
    )

GOVERNING_TRUST_RECORDS = [
    {
        "contract_id": contract_id,
        "authority_kind": str(spec["authority_kind"]),
        "path": str(spec["path"]),
        "sha256": str(spec["sha256"]),
    }
    for contract_id, spec in SETTINGS["governing_contracts"].items()
]

N34_RUN_ID = stable_id(
    "run",
    {
        "notebook_id": "34",
        "release_id": DASHBOARD_RELEASE_ID,
        "package_schema": SETTINGS["dashboard_package_schema_version"],
    },
)
N34_GIT_STATE = git_state(PROJECT_ROOT)

RUNTIME_MANIFEST = {
    "schema_version": SETTINGS["runtime_manifest_schema_version"],
    "package_schema_version": SETTINGS["dashboard_package_schema_version"],
    "release_id": DASHBOARD_RELEASE_ID,
    "dataset_id": SETTINGS["dataset_id"],
    "dataset_version": SETTINGS["dataset_version"],
    "dataset_scope": SETTINGS["dataset_scope"],
    "run_id": N34_RUN_ID,
    "generated_at_utc": RUN_STARTED_AT_UTC,
    "git_commit": N34_GIT_STATE["git_commit"],
    "git_dirty": N34_GIT_STATE["git_dirty"],
    "git_branch": N34_GIT_STATE["git_branch"],
    "principal_room_ids": EXPECTED_PRINCIPAL_ROOM_IDS,
    "child_routes": [
        {
            "room_id": "focused_portrait_review",
            "parent_room_id": "trustworthiness",
        }
    ],
    "upstream_manifests": UPSTREAM_TRUST_RECORDS,
    "governing_contracts": GOVERNING_TRUST_RECORDS,
    "local_artifacts": TRUSTED_LOCAL_RECORDS,
    "trusted_remote_roots": TRUSTED_REMOTE_ROOTS,
    "display_ids": sorted(ROOM_RECORDS_FINAL["display_id"].astype(str).tolist()),
    "population": deepcopy(POPULATION),
    "runtime_budgets": deepcopy(SETTINGS["runtime_budgets"]),
    "deterministic_package_sha256": DETERMINISTIC_PACKAGE_SHA256,
    "validation_summary": {
        "status": "passed",
        "blocking_failure_count": 0,
        "warning_failure_count": 0,
    },
    "known_limitations": list(SETTINGS["limitations"]),
    "supported_application_schemas": deepcopy(SETTINGS["expected_output_schemas"]),
    "startup_network_requests": 0,
    "status": "completed",
}

if BUILDING_NEW_RELEASE:
    atomic_write_json(RUNTIME_MANIFEST, package_path("runtime_manifest_path"))
else:
    RUNTIME_MANIFEST = load_json(package_path("runtime_manifest_path"))

print("Room partitions registered:", len(ROOM_PARTITION_INDEX_FINAL))
print("Runtime local artifacts:", len(RUNTIME_MANIFEST["local_artifacts"]))
print("Trusted remote roots:", len(RUNTIME_MANIFEST["trusted_remote_roots"]))
print("Deterministic package digest:", RUNTIME_MANIFEST["deterministic_package_sha256"])

Room partitions registered: 9
Runtime local artifacts: 373
Trusted remote roots: 8
Deterministic package digest: f1157c3086a6d827f08a9e936c509fdc23112ccf11f689688065a3791adf30a7

In [42]:
from restoration_eval.schemas import ARTIFACT_MANIFEST_COLUMNS


ARTIFACT_SPECS = [
    ("dashboard.bootstrap", "bootstrap_package", "zero_network_bootstrap", "bootstrap", package_path("bootstrap_dir"), None),
    ("dashboard.rooms", "room_partition_collection", "room_display_partitions", "room_partition", package_path("rooms_dir"), 100),
    ("dashboard.paintings", "painting_partition_collection", "painting_route_partitions", "painting_partition", package_path("paintings_dir"), 300),
    ("dashboard.reports", "report_index", "verified_report_routes", "report_index", package_path("report_index_path"), len(REPORT_DIMENSION)),
    ("dashboard.derived", "derived_display_evidence", "governed_display_derivatives", "dashboard_package.v2", package_path("derived_dir"), 5),
    ("dashboard.renditions", "registered_rendition_collection", "local_web_renditions", "dashboard_rendition.v1", package_path("renditions_dir"), len(RENDITIONS_FINAL)),
    ("dashboard.display_components", "display_binding_manifest", "approved_display_binding_closure", "display_components", package_path("display_components_path"), len(DISPLAY_COMPONENTS)),
    ("dashboard.assets", "dashboard_asset_manifest", "logical_asset_registry", "dashboard_assets", package_path("dashboard_assets_path"), len(DASHBOARD_ASSETS_FINAL)),
    ("dashboard.asset_locators", "asset_locator_manifest", "immutable_local_and_remote_routes", "asset_locators", package_path("asset_locators_path"), len(ASSET_LOCATORS_FINAL)),
    ("dashboard.rendition_manifest", "rendition_manifest", "rendition_lineage_and_budgets", "renditions", package_path("renditions_manifest_path"), len(RENDITIONS_FINAL)),
    ("dashboard.room_partitions", "room_partition_manifest", "room_partition_checksums", "room_partitions", package_path("room_partitions_path"), len(ROOM_PARTITION_INDEX_FINAL)),
    ("dashboard.runtime_manifest", "runtime_trust_manifest", "runtime_trust_root", "runtime_manifest", package_path("runtime_manifest_path"), 1),
]

if BUILDING_NEW_RELEASE:
    def canonical_artifact_record(
        *,
        artifact_key: str,
        artifact_type: str,
        artifact_role: str,
        schema_key: str,
        path: Path,
        row_count: int | None,
    ) -> dict:
        record = build_artifact_record(
            artifact_key=artifact_key,
            producer_notebook=SETTINGS["notebook_stem"],
            path=path,
            artifact_type=artifact_type,
            artifact_role=artifact_role,
            schema_version=SETTINGS["expected_output_schemas"].get(
                schema_key, schema_key
            ),
            dataset_scope=SETTINGS["dataset_scope"],
            experiment_id="dashboard_presentation",
            row_count=row_count,
            project_root=PROJECT_ROOT,
        )
        # The record describes the canonical post-promotion destination, not
        # the temporary work path used while checksums are being finalized.
        canonical_relative = (
            Path(SETTINGS["output"]["root"])
            / path.relative_to(ACTIVE_PACKAGE_ROOT)
        ).as_posix()
        record["relative_path"] = canonical_relative
        record["artifact_id"] = "artifact_" + hashlib.sha256(
            (
                f"{artifact_key}|{canonical_relative}|{record['checksum']}"
            ).encode("utf-8")
        ).hexdigest()[:20]
        return record

    ARTIFACT_RECORDS = artifact_records_dataframe(
        [
            canonical_artifact_record(
                artifact_key=artifact_key,
                artifact_type=artifact_type,
                artifact_role=artifact_role,
                schema_key=schema_key,
                path=path,
                row_count=row_count,
            )
            for (
                artifact_key, artifact_type, artifact_role,
                schema_key, path, row_count,
            ) in ARTIFACT_SPECS
        ]
    )
    atomic_write_csv(ARTIFACT_RECORDS, package_path("artifacts_path"))
else:
    ARTIFACT_RECORDS = pd.read_csv(
        package_path("artifacts_path"), low_memory=False
    )
    ARTIFACT_RECORDS = ARTIFACT_RECORDS.loc[:, ARTIFACT_MANIFEST_COLUMNS]


def output_record(path: Path) -> dict:
    relative = package_relative(path)
    suffix = path.suffix.lower().lstrip(".")
    return {
        "artifact_key": "output." + relative.replace("/", "."),
        "relative_path": (
            Path(SETTINGS["output"]["root"]) / relative
        ).as_posix(),
        "artifact_type": suffix or "file",
    }


EXPECTED_PACKAGE_RELATIVE_PATHS = sorted(
    {
        record["relative_path"]
        for record in RUNTIME_MANIFEST["local_artifacts"]
    }
    | {
        SETTINGS["output"]["runtime_manifest_path"],
        SETTINGS["output"]["artifacts_path"],
        SETTINGS["output"]["run_manifest_path"],
        SETTINGS["output"]["validation_path"],
    }
)

RUN_MANIFEST_OUTPUTS = [
    {
        "artifact_key": "output." + relative.replace("/", "."),
        "relative_path": (
            Path(SETTINGS["output"]["root"]) / relative
        ).as_posix(),
        "artifact_type": Path(relative).suffix.lower().lstrip(".") or "file",
    }
    for relative in EXPECTED_PACKAGE_RELATIVE_PATHS
]

MANIFEST_INPUT_RECORDS = [
    {
        "input_key": f"upstream_manifest.{record['logical_notebook_id']}",
        "relative_path": record["path"],
        "checksum": record["sha256"],
    }
    for record in UPSTREAM_TRUST_RECORDS
] + [
    {
        "input_key": f"governing_contract.{record['contract_id']}",
        "relative_path": record["path"],
        "checksum": record["sha256"],
    }
    for record in GOVERNING_TRUST_RECORDS
]

COMPLETED_AT_UTC = (
    datetime.now(timezone.utc)
    .isoformat(timespec="seconds")
    .replace("+00:00", "Z")
)

if BUILDING_NEW_RELEASE:
    FINAL_RUN_MANIFEST = build_run_manifest(
        notebook_id=SETTINGS["notebook_id"],
        notebook_name=SETTINGS["notebook_stem"],
        origin="Controlled-300 dashboard package built from approved N01–N33, N12A, D01, and D02 evidence",
        run_status="completed",
        started_at_utc=RUN_STARTED_AT_UTC,
        completed_at_utc=COMPLETED_AT_UTC,
        inventory_run_id=str(INVENTORY_RUN["inventory_run_id"]),
        dataset_versions={
            "dataset_id": SETTINGS["dataset_id"],
            "dataset_version": SETTINGS["dataset_version"],
            "dataset_scope": SETTINGS["dataset_scope"],
            "configuration_version": CONFIG["config_version"],
            "dashboard_package_schema_version": SETTINGS["dashboard_package_schema_version"],
            "dashboard_release_id": DASHBOARD_RELEASE_ID,
            "upstream_run_ids": {
                record["logical_notebook_id"]: record["run_id"]
                for record in UPSTREAM_TRUST_RECORDS
            },
        },
        configuration_paths=[
            CONFIG_PATH.relative_to(PROJECT_ROOT).as_posix(),
            *[record["path"] for record in GOVERNING_TRUST_RECORDS],
        ],
        configuration_checksums_by_path=configuration_checksums(
            [CONFIG_PATH, *[PROJECT_ROOT / record["path"] for record in GOVERNING_TRUST_RECORDS]],
            PROJECT_ROOT,
        ),
        helper_versions={
            "dashboard_assets": DASHBOARD_ASSETS_VERSION,
            "manifests": MANIFESTS_MODULE_VERSION,
        },
        inputs=MANIFEST_INPUT_RECORDS,
        outputs=RUN_MANIFEST_OUTPUTS,
        expected_counts={
            "principal_rooms": 8,
            "child_routes": 1,
            "display_ids": 100,
            "paintings": 300,
            "logical_assets": 56,
            "renditions": 48,
            "asset_locators": 95,
        },
        observed_counts={
            "principal_rooms": len(EXPECTED_PRINCIPAL_ROOM_IDS),
            "child_routes": 1,
            "display_ids": int(DISPLAY_COMPONENTS["display_id"].nunique()),
            "display_bindings": len(DISPLAY_COMPONENTS),
            "paintings": len(PAINTING_LOOKUP),
            "logical_assets": len(DASHBOARD_ASSETS_FINAL),
            "renditions": len(RENDITIONS_FINAL),
            "asset_locators": len(ASSET_LOCATORS_FINAL),
            "package_files": len(EXPECTED_PACKAGE_RELATIVE_PATHS),
        },
        validation_summary={
            "check_count": None,
            "passed_count": None,
            "failed_count": 0,
            "blocking_failure_count": 0,
            "overall_passed": True,
        },
        known_limitations=SETTINGS["limitations"],
        project_root=PROJECT_ROOT,
        package_names=("pandas", "pyarrow", "Pillow", "PyYAML"),
        run_id=N34_RUN_ID,
    )
    FINAL_RUN_MANIFEST.update(
        {
            "validation_status": "passed",
            "refactor_status": "refactored",
            "completion_gate_passed": True,
            "creates_new_scientific_evidence": False,
            "dashboard_release_id": DASHBOARD_RELEASE_ID,
            "artifact_manifest_checksum": sha256_file(package_path("artifacts_path")),
            "deterministic_package_sha256": RUNTIME_MANIFEST["deterministic_package_sha256"],
        }
    )
    atomic_write_json(FINAL_RUN_MANIFEST, package_path("run_manifest_path"))
else:
    FINAL_RUN_MANIFEST = load_json(package_path("run_manifest_path"))


def package_files(root: Path) -> dict[str, Path]:
    return {
        path.relative_to(root).as_posix(): path
        for path in root.rglob("*")
        if path.is_file()
    }


PACKAGE_FILES_BEFORE_VALIDATION = package_files(ACTIVE_PACKAGE_ROOT)
PACKAGE_BYTES_BEFORE_VALIDATION = sum(
    path.stat().st_size for path in PACKAGE_FILES_BEFORE_VALIDATION.values()
)

FINAL_CHECKS = []


def final_check(name: str, observed, expected, passed: bool | None = None, details: str = "") -> None:
    FINAL_CHECKS.append(
        validation_row(
            BATCH_8_STAGE,
            name,
            observed,
            expected,
            observed == expected if passed is None else bool(passed),
            details,
        )
    )


final_check("principal_room_order", EXPECTED_PRINCIPAL_ROOM_IDS, [
    "exhibition_foyer", "study_design", "metric_framework", "model_gallery",
    "stability_lab", "trustworthiness", "case_explorer", "research_archive",
])
final_check("focused_portrait_parent", RUNTIME_MANIFEST["child_routes"], [
    {"room_id": "focused_portrait_review", "parent_room_id": "trustworthiness"}
])
final_check("approved_display_id_count", DISPLAY_COMPONENTS["display_id"].nunique(), 100)
final_check("display_binding_id_uniqueness", DISPLAY_COMPONENTS["binding_id"].nunique(), len(DISPLAY_COMPONENTS))
final_check("display_contract_closure", sorted(set(ROOM_RECORDS_FINAL["display_id"]) - set(DISPLAY_COMPONENTS["display_id"])), [])
final_check("required_derivation_states_resolved", int(DISPLAY_COMPONENTS["mapping_state"].eq("unsupported_until_derived").sum()), 0)
final_check("pending_room_derivations_resolved", int(ROOM_RECORDS_FINAL["applicability_state"].eq("pending_derivation").sum()), 0)
final_check("mandatory_derivative_files", sum(package_path(key).is_file() for key in (
    "threshold_strata_path", "stability_trajectories_path", "d02_hand_summary_path",
    "d02_lightness_summary_path", "d02_r005_geometry_path",
)), 5)
final_check("painting_partition_count", len(list(package_path("paintings_dir").glob("p*.json.gz"))), 300)
final_check("room_partition_count", len(ROOM_PARTITION_INDEX_FINAL), 9)
final_check("logical_asset_count", len(DASHBOARD_ASSETS_FINAL), 56)
final_check("rendition_count", len(RENDITIONS_FINAL), 48)
final_check("asset_locator_count", len(ASSET_LOCATORS_FINAL), 95)

BOUND_ASSET_IDS = {
    value.split(":", 1)[1]
    for value in DISPLAY_COMPONENTS["payload_ref"].astype(str)
    if value.startswith("asset:")
}
REGISTERED_ASSET_IDS = set(DASHBOARD_ASSETS_FINAL["asset_id"].astype(str))
IMAGE_DISPLAY_IDS = set(
    ROOM_RECORDS_FINAL.loc[
        ROOM_RECORDS_FINAL["record_type"].eq("image"),
        "display_id",
    ].astype(str)
)
IMAGE_DISPLAYS_WITH_ASSETS = set(
    DISPLAY_COMPONENTS.loc[
        DISPLAY_COMPONENTS["component_kind"].eq("image")
        & DISPLAY_COMPONENTS["payload_ref"].astype(str).str.startswith("asset:"),
        "display_id",
    ].astype(str)
)
final_check(
    "display_asset_references_exist",
    sorted(BOUND_ASSET_IDS - REGISTERED_ASSET_IDS),
    [],
)
final_check(
    "image_display_asset_closure",
    sorted(IMAGE_DISPLAY_IDS - IMAGE_DISPLAYS_WITH_ASSETS),
    [],
)
final_check("remote_revision_pinning", int((~REMOTE_LOCATORS["revision"].map(is_full_git_revision)).sum()), 0)
final_check("remote_checksum_pinning", int((~REMOTE_LOCATORS["expected_sha256"].map(is_sha256)).sum()), 0)
final_check("mutable_remote_urls", int(REMOTE_LOCATORS["immutable_resolve_url"].astype(str).str.contains(r"/resolve/main/|/(?:blob|raw)/main/", regex=True).sum()), 0)
final_check("startup_network_requests", RUNTIME_MANIFEST["startup_network_requests"], 0)
final_check("registered_mockup_assets", int(DASHBOARD_ASSETS_FINAL["source_relative_path"].astype(str).str.contains("docs/dashboard_design_finalists/approved_current/").sum()), 0)
final_check("local_package_hard_budget", PACKAGE_BYTES_BEFORE_VALIDATION, SETTINGS["runtime_budgets"]["local_package_hard_bytes"], PACKAGE_BYTES_BEFORE_VALIDATION <= SETTINGS["runtime_budgets"]["local_package_hard_bytes"])
final_check("runtime_release_identity", RUNTIME_MANIFEST["release_id"], DASHBOARD_RELEASE_ID)
final_check("run_manifest_completion", {
    "run_status": FINAL_RUN_MANIFEST["run_status"],
    "validation_status": FINAL_RUN_MANIFEST["validation_status"],
    "completion_gate_passed": FINAL_RUN_MANIFEST["completion_gate_passed"],
    "creates_new_scientific_evidence": FINAL_RUN_MANIFEST["creates_new_scientific_evidence"],
}, {
    "run_status": "completed", "validation_status": "passed",
    "completion_gate_passed": True, "creates_new_scientific_evidence": False,
})
final_check("artifact_manifest_checksum", FINAL_RUN_MANIFEST["artifact_manifest_checksum"], sha256_file(package_path("artifacts_path")))
final_check("declared_output_identity", set(FINAL_RUN_MANIFEST["outputs"][index]["relative_path"] for index in range(len(FINAL_RUN_MANIFEST["outputs"]))), {
    (Path(SETTINGS["output"]["root"]) / relative).as_posix()
    for relative in EXPECTED_PACKAGE_RELATIVE_PATHS
})
final_check("runtime_local_checksums", [
    record["relative_path"] for record in RUNTIME_MANIFEST["local_artifacts"]
    if (
        not (ACTIVE_PACKAGE_ROOT / record["relative_path"]).is_file()
        or sha256_file(ACTIVE_PACKAGE_ROOT / record["relative_path"]) != record["sha256"]
        or (ACTIVE_PACKAGE_ROOT / record["relative_path"]).stat().st_size != int(record["size_bytes"])
    )
], [])
final_check("room_partition_checksums", [
    row.relative_path for row in ROOM_PARTITION_INDEX_FINAL.itertuples(index=False)
    if (
        not (ACTIVE_PACKAGE_ROOT / row.relative_path).is_file()
        or sha256_file(ACTIVE_PACKAGE_ROOT / row.relative_path) != row.sha256
        or (ACTIVE_PACKAGE_ROOT / row.relative_path).stat().st_size != int(row.size_bytes)
    )
], [])
final_check("rendition_checksums", [
    row.relative_path for row in RENDITIONS_FINAL.itertuples(index=False)
    if (
        not (ACTIVE_PACKAGE_ROOT / row.relative_path).is_file()
        or sha256_file(ACTIVE_PACKAGE_ROOT / row.relative_path) != row.sha256
        or (ACTIVE_PACKAGE_ROOT / row.relative_path).stat().st_size != int(row.size_bytes)
    )
], [])
final_check("prohibited_claims_absent", [
    claim for claim in SETTINGS["validation"]["prohibited_claims"]
    if claim.lower() in " ".join(ROOM_RECORDS_FINAL["interpretation"].astype(str)).lower()
], [])
final_check("absolute_paths_absent", [
    relative for relative in EXPECTED_PACKAGE_RELATIVE_PATHS
    if not is_repo_relative(relative)
], [])

VALIDATION_ROWS[:] = [
    row for row in VALIDATION_ROWS
    if row["validation_stage"] != BATCH_8_STAGE
]
VALIDATION_ROWS.extend(FINAL_CHECKS)
FINAL_VALIDATION = current_validation_frame().drop_duplicates(
    subset=["check_id"], keep="last"
).reset_index(drop=True)

FINAL_BLOCKING_FAILURES = blocking_validation_failures(FINAL_VALIDATION)
if not FINAL_BLOCKING_FAILURES.empty:
    display(FINAL_BLOCKING_FAILURES)
    raise RuntimeError(
        f"Batch 8 stopped before promotion with {len(FINAL_BLOCKING_FAILURES)} blocking failure(s)."
    )

if BUILDING_NEW_RELEASE:
    atomic_write_csv(FINAL_VALIDATION, package_path("validation_path"))
    FINAL_RUN_MANIFEST["validation_summary"] = {
        "check_count": int(len(FINAL_VALIDATION)),
        "passed_count": int(FINAL_VALIDATION["passed"].map(as_bool).sum()),
        "failed_count": int((~FINAL_VALIDATION["passed"].map(as_bool)).sum()),
        "blocking_failure_count": 0,
        "overall_passed": True,
    }
    atomic_write_json(FINAL_RUN_MANIFEST, package_path("run_manifest_path"))
else:
    FINAL_VALIDATION = pd.read_csv(package_path("validation_path"), low_memory=False)

print("Batch 8 pre-promotion checks passed:", len(FINAL_VALIDATION))
print("Artifact records:", len(ARTIFACT_RECORDS))
print("Declared package files:", len(EXPECTED_PACKAGE_RELATIVE_PATHS))
print("Package bytes before promotion:", PACKAGE_BYTES_BEFORE_VALIDATION)

Batch 8 pre-promotion checks passed: 916
Artifact records: 12
Declared package files: 377
Package bytes before promotion: 7602275

In [43]:
if BATCH_8_MODE == "build_and_promote":
    if PROMOTION_CANDIDATE.exists():
        raise RuntimeError(
            f"Unexpected promotion candidate already exists: {PROMOTION_CANDIDATE}"
        )

    # Move the complete release out of its work parent before replacing the
    # canonical root. Only now-empty directories are removed.
    os.replace(STAGING_PACKAGE_ROOT, PROMOTION_CANDIDATE)

    work_root = OUTPUT_PATHS["work_dir"]
    for directory in sorted(
        [path for path in work_root.rglob("*") if path.is_dir()],
        key=lambda path: len(path.parts),
        reverse=True,
    ) if work_root.exists() else []:
        if not any(directory.iterdir()):
            directory.rmdir()
    if work_root.exists() and not any(work_root.iterdir()):
        work_root.rmdir()

    unexpected_root_files = [
        path.relative_to(OUTPUT_ROOT).as_posix()
        for path in OUTPUT_ROOT.rglob("*")
        if path.is_file()
    ] if OUTPUT_ROOT.exists() else []
    if unexpected_root_files:
        raise RuntimeError(
            "Canonical root contains undeclared files before promotion: "
            f"{unexpected_root_files}"
        )
    if OUTPUT_ROOT.exists():
        for directory in sorted(
            [path for path in OUTPUT_ROOT.rglob("*") if path.is_dir()],
            key=lambda path: len(path.parts),
            reverse=True,
        ):
            if not any(directory.iterdir()):
                directory.rmdir()
        if any(OUTPUT_ROOT.iterdir()):
            raise RuntimeError("Canonical root is not empty before promotion.")
        OUTPUT_ROOT.rmdir()

    os.replace(PROMOTION_CANDIDATE, OUTPUT_ROOT)
    PROMOTION_STATUS = "promoted"

elif BATCH_8_MODE == "recover_promotion":
    recovery_root_files = (
        [path for path in OUTPUT_ROOT.rglob("*") if path.is_file()]
        if OUTPUT_ROOT.exists()
        else []
    )
    if recovery_root_files:
        raise RuntimeError(
            "Cannot recover promotion while canonical files exist: "
            f"{[path.relative_to(OUTPUT_ROOT).as_posix() for path in recovery_root_files]}"
        )
    if OUTPUT_ROOT.exists():
        for directory in sorted(
            [path for path in OUTPUT_ROOT.rglob("*") if path.is_dir()],
            key=lambda path: len(path.parts),
            reverse=True,
        ):
            if not any(directory.iterdir()):
                directory.rmdir()
        OUTPUT_ROOT.rmdir()
    os.replace(PROMOTION_CANDIDATE, OUTPUT_ROOT)
    PROMOTION_STATUS = "recovered_and_promoted"

else:
    PROMOTION_STATUS = "verified_existing"

print("Promotion status:", PROMOTION_STATUS)
print("Canonical release root:", OUTPUT_ROOT)

Promotion status: promoted
Canonical release root: D:\Masters\FH\Thesis\painting-restoration-eval\outputs\34_final_streamlit_dashboard_assets

In [44]:
FINAL_RUNTIME_PATH = OUTPUT_ROOT / SETTINGS["output"]["runtime_manifest_path"]
FINAL_RUN_PATH = OUTPUT_ROOT / SETTINGS["output"]["run_manifest_path"]
FINAL_VALIDATION_PATH = OUTPUT_ROOT / SETTINGS["output"]["validation_path"]

FINAL_RUNTIME = load_json(FINAL_RUNTIME_PATH)
FINAL_RUN = load_json(FINAL_RUN_PATH)
FINAL_CHECK_FRAME = pd.read_csv(FINAL_VALIDATION_PATH, low_memory=False)

FINAL_FILES = package_files(OUTPUT_ROOT)
FINAL_RELATIVE_PATHS = set(FINAL_FILES)
EXPECTED_RELATIVE_PATHS = {
    Path(record["relative_path"])
    .relative_to(Path(SETTINGS["output"]["root"]))
    .as_posix()
    for record in FINAL_RUN["outputs"]
}

FINAL_TEMPORARY_FILES = sorted(
    relative
    for relative in FINAL_RELATIVE_PATHS
    if (
        relative.startswith("work/")
        or "/work/" in relative
        or Path(relative).name.startswith(".")
        or Path(relative).suffix.lower() in {".tmp", ".temp", ".part", ".partial"}
    )
)

FINAL_LOCAL_CHECKSUM_FAILURES = [
    record["relative_path"]
    for record in FINAL_RUNTIME["local_artifacts"]
    if (
        record["relative_path"] not in FINAL_FILES
        or sha256_file(FINAL_FILES[record["relative_path"]]) != record["sha256"]
        or FINAL_FILES[record["relative_path"]].stat().st_size != int(record["size_bytes"])
    )
]

FINAL_GZIP_FAILURES = []
for record in FINAL_RUNTIME["local_artifacts"]:
    compressed = record.get("compressed_payload")
    if not compressed:
        continue
    path = FINAL_FILES[record["relative_path"]]
    observed = decoded_gzip_metadata(path)
    if observed != compressed:
        FINAL_GZIP_FAILURES.append(record["relative_path"])

FINAL_BLOCKING = blocking_validation_failures(FINAL_CHECK_FRAME)
FINAL_FAILURES = []
if FINAL_RUNTIME.get("release_id") != DASHBOARD_RELEASE_ID:
    FINAL_FAILURES.append("runtime release identity")
if FINAL_RUN.get("dashboard_release_id") != DASHBOARD_RELEASE_ID:
    FINAL_FAILURES.append("run-manifest release identity")
if FINAL_RELATIVE_PATHS != EXPECTED_RELATIVE_PATHS:
    FINAL_FAILURES.append("exact output identity")
if len(FINAL_FILES) != 377:
    FINAL_FAILURES.append("canonical file count")
if FINAL_TEMPORARY_FILES:
    FINAL_FAILURES.append("temporary/work files")
if not FINAL_BLOCKING.empty:
    FINAL_FAILURES.append("blocking validation failures")
if FINAL_LOCAL_CHECKSUM_FAILURES:
    FINAL_FAILURES.append("runtime local checksums")
if FINAL_GZIP_FAILURES:
    FINAL_FAILURES.append("deterministic gzip checksums")
if (OUTPUT_ROOT / "work").exists():
    FINAL_FAILURES.append("work directory retained")
if PROMOTION_CANDIDATE.exists():
    FINAL_FAILURES.append("promotion candidate retained")

if FINAL_FAILURES:
    raise RuntimeError(
        "Notebook 34 final completion gate failed: "
        + "; ".join(FINAL_FAILURES)
    )

print("Notebook 34 Controlled-300 dashboard package is complete.")
print("Release ID:", DASHBOARD_RELEASE_ID)
print("Promotion status:", PROMOTION_STATUS)
print("Canonical files:", len(FINAL_FILES))
print("Canonical bytes:", sum(path.stat().st_size for path in FINAL_FILES.values()))
print("Display IDs / bindings:", DISPLAY_COMPONENTS["display_id"].nunique(), "/", len(DISPLAY_COMPONENTS))
print("Logical assets / renditions / locators:", len(DASHBOARD_ASSETS_FINAL), "/", len(RENDITIONS_FINAL), "/", len(ASSET_LOCATORS_FINAL))
print("Room partitions / painting partitions:", len(ROOM_PARTITION_INDEX_FINAL), "/", len(list((OUTPUT_ROOT / SETTINGS["output"]["paintings_dir"]).glob("p*.json.gz"))))
print("Validation checks:", len(FINAL_CHECK_FRAME))
print("Blocking failures:", len(FINAL_BLOCKING))
print("Startup network requests: 0")
print("Work directory present:", (OUTPUT_ROOT / "work").exists())
print("Rerun mode is safe: a second Batch 8 execution verifies this release in place.")

Notebook 34 Controlled-300 dashboard package is complete.
Release ID: release_c5edf0d0ec99affbfa403726
Promotion status: promoted
Canonical files: 377
Canonical bytes: 7998184
Display IDs / bindings: 100 / 170
Logical assets / renditions / locators: 56 / 48 / 95
Room partitions / painting partitions: 9 / 300
Validation checks: 916
Blocking failures: 0
Startup network requests: 0
Work directory present: False
Rerun mode is safe: a second Batch 8 execution verifies this release in place.

In [46]:
# ---------------------------------------------------------------------------
# Batch 8B — portability correction for the validation ledger
# ---------------------------------------------------------------------------

from pathlib import Path
import os
import re

import pandas as pd

if "PROJECT_ROOT" in globals():
    project_root = Path(PROJECT_ROOT).resolve()
else:
    project_root = next(
        candidate
        for candidate in (
            Path.cwd().resolve(),
            *Path.cwd().resolve().parents,
        )
        if (
            candidate
            / "config"
            / "evaluation"
            / "dashboard_assets.yaml"
        ).is_file()
    )

checks_path = (
    project_root
    / "outputs"
    / "34_final_streamlit_dashboard_assets"
    / "validation"
    / "checks.csv"
)

checks_df = pd.read_csv(
    checks_path,
    dtype=str,
    keep_default_na=False,
)

root_variants = sorted(
    {
        str(project_root),
        project_root.as_posix(),
    },
    key=len,
    reverse=True,
)

def portable_validation_value(value):
    text = str(value)
    for root_value in root_variants:
        text = text.replace(
            root_value,
            "<PROJECT_ROOT>",
        )
    return text

for column in (
    "expected",
    "observed",
    "details",
):
    checks_df[column] = checks_df[column].map(
        portable_validation_value
    )

temporary_path = checks_path.with_suffix(
    ".csv.tmp"
)

checks_df.to_csv(
    temporary_path,
    index=False,
    lineterminator="\n",
)

os.replace(
    temporary_path,
    checks_path,
)

serialized_checks = checks_path.read_text(
    encoding="utf-8",
)

absolute_path_matches = re.findall(
    r"(?i)(?<![A-Za-z0-9_])[A-Z]:[\\/]",
    serialized_checks,
)

if absolute_path_matches:
    raise RuntimeError(
        "Absolute local paths remain in the validation ledger."
    )

if len(checks_df) != 916:
    raise RuntimeError(
        f"Expected 916 validation rows; observed {len(checks_df)}."
    )

if not checks_df["passed"].str.lower().eq("true").all():
    raise RuntimeError(
        "A validation check is no longer passing."
    )

print("Notebook 34 portability correction passed.")
print("Validation rows:", len(checks_df))
print(
    "Absolute local paths remaining:",
    len(absolute_path_matches),
)

Notebook 34 portability correction passed.
Validation rows: 916
Absolute local paths remaining: 0