# 35 — Dashboard and Deployment Validation

**Origin:** New Notebook\
**Refactor status:** Finished\
**Validation status:** Finished\
**Completion gate passed:** Yes\
**Output root:** `outputs/35_dashboard_and_deployment_validation/`\
**Depends on:** Notebook 34, `streamlit_app.py`, `config/evaluation/dashboard_validation.yaml`, and `src/restoration_eval/dashboard_application.py`

## Purpose

Validate the final Streamlit dashboard as a reproducible inspection and decision-support interface over the completed Notebook 34 dashboard package.

This notebook validates the application, its evidence relationships, indexed assets, presentation boundaries, and deployment readiness. It does not create restoration candidates, run model inference, recompute scientific metrics, or modify upstream evidence.

## Approved application structure

The dashboard contains eight principal pages:

1. **Overview**
2. **Study Design**
3. **Metric Framework**
4. **Model Performance**
5. **Robustness & Uncertainty**
6. **Trustworthiness & XAI**
7. **Case Explorer**
8. **Reports & Reproducibility**

The implementation follows the approved museum-research visual direction: aged-ivory surfaces, bottle green navigation, restrained pigment-derived accents, editorial typography, compact evidence cards, paintings, restorations, diagnostic maps, plots, conclusions, limitations, filters, and provenance.

The three approved UI reference images remain external read-only planning references. They are not copied into the repository and are not runtime dependencies.

## Validated evidence population

The application consumes only `outputs/34_final_streamlit_dashboard_assets/`, representing:

- 50 controlled paintings;
- 525 registered experimental cases;
- 410 restoration cases;
- 1,785 approved restoration candidates;
- 1,230 primary three-model candidates;
- 955 Stable Diffusion candidates;
- 10 bounded SDXL feasibility candidates;
- 130 canonical repeated-seed uncertainty groups;
- 35 damage-size uncertainty groups;
- 23,964 indexed visual records;
- 104 self-contained or otherwise indexed reports.

Representative defaults determine the initial presentation only. Complete candidate, painting, visual, and report populations remain accessible through validated filters and indexes.

## Validation responsibilities

The notebook validates:

- every declared dashboard input path, row count, and schema;
- the Notebook 34 dashboard-asset manifest;
- candidate, case, painting, report, and visual relationships;
- repository-safe resolution of indexed images and reports;
- the absence of obsolete global output dependencies;
- the exact eight-page application structure;
- filter vocabularies and identifier relationships;
- controlled-scope and scaling-projection labels;
- deterministic, repeated-seed, and optional-model applicability;
- bounded SDXL handling;
- figure, restoration, map, and heatmap references;
- mock-to-application presentation traceability;
- application syntax, imports, and read-only behavior;
- all-page Streamlit smoke execution when the runtime is available;
- declared dependency versions and deployment metadata.

## Interpretation boundaries

- Visual plausibility is not historical correctness or restoration trustworthiness.
- The dashboard supports inspection and decision-making; it is not a restoration or experiment tool.
- The application may filter, reshape, aggregate, and format validated dashboard assets for presentation but may not recompute scientific evidence.
- Repeated-seed variation is empirical diffusion uncertainty, not calibrated confidence.
- Mask-placement variation and prompt variation remain robustness or sensitivity evidence.
- Computational flags are conservative review guidance, not expert ground truth.
- Retrieval and feature similarity provide context, not restoration correctness or historical proof.
- SDXL remains a bounded ten-case feasibility study rather than a fourth full benchmark.
- No universal combined quality or trustworthiness score is constructed.
- No dashboard result constitutes authenticity assessment or conservation approval.

## Canonical outputs

```text
validation/dashboard_checks.csv
reports/deployment_readiness.md
manifests/run_manifest.json
manifests/artifacts.csv

## Batch 1 — Contract, environment, and dependency preflight

This batch:

- discovers the repository root without assuming the working directory;
- loads the versioned Notebook 35 validation contract;
- creates only the declared notebook-owned output directories;
- rejects stale files in the Notebook 35 output root;
- validates the current inventory and project-path registry;
- confirms the governing roadmap, implementation, and evidence-audit contracts;
- verifies the application, configuration, helper, and Notebook 34 package locations;
- records Python and dashboard dependency versions;
- checks the Streamlit entrypoint for valid Python syntax;
- treats installed-version differences as visible deployment warnings rather than silently ignoring them;
- applies a blocking gate before package or application validation begins.

This batch does not import or execute `streamlit_app.py`, launch a server, inspect all indexed assets, or persist any canonical Notebook 35 file.

In [1]:
from __future__ import annotations

import ast
import json
import platform
import sys
from datetime import datetime, timezone
from importlib import metadata
from pathlib import Path

import pandas as pd
from IPython.display import display


# Discover the repository from either its root or the notebooks directory.
CURRENT_LOCATION = Path.cwd().resolve()
PROJECT_ROOT = next(
    (
        candidate
        for candidate in (CURRENT_LOCATION, *CURRENT_LOCATION.parents)
        if (
            candidate
            / "config"
            / "evaluation"
            / "dashboard_validation.yaml"
        ).is_file()
        and (candidate / "src" / "restoration_eval").is_dir()
        and (candidate / "notebooks").is_dir()
    ),
    None,
)

if PROJECT_ROOT is None:
    raise FileNotFoundError(
        "Could not locate the painting-restoration-eval repository root."
    )

SOURCE_ROOT = PROJECT_ROOT / "src"
if str(SOURCE_ROOT) not in sys.path:
    sys.path.insert(0, str(SOURCE_ROOT))


from restoration_eval.dashboard_application import (
    DASHBOARD_APPLICATION_VERSION,
    DASHBOARD_PACKAGE_SCHEMA_VERSION,
    DASHBOARD_VALIDATION_CONFIG_SCHEMA_VERSION,
    load_dashboard_validation_config,
    required_input_paths,
)
from restoration_eval.paths import (
    PATHS_MODULE_VERSION,
    PROJECT_PATHS_SCHEMA_VERSION,
    ensure_output_subdirs,
    notebook_output_root,
    validate_project_paths_registry,
)
from restoration_eval.validation import (
    VALIDATION_MODULE_VERSION,
    ValidationCollector,
)


NOTEBOOK_ID = "35"
NOTEBOOK_STEM = "35_dashboard_and_deployment_validation"

RUN_STARTED_AT_UTC = (
    datetime.now(timezone.utc)
    .isoformat(timespec="seconds")
    .replace("+00:00", "Z")
)

VALIDATION = ValidationCollector()

print("Notebook 35 environment initialized.")
print("Project root:", PROJECT_ROOT)
print("Run started:", RUN_STARTED_AT_UTC)
print("Python:", platform.python_version())
print("Platform:", platform.platform())
print(
    "Helper versions:",
    {
        "dashboard_application": DASHBOARD_APPLICATION_VERSION,
        "validation": VALIDATION_MODULE_VERSION,
        "paths": PATHS_MODULE_VERSION,
    },
)

Notebook 35 environment initialized.
Project root: D:\Masters\FH\Thesis\painting-restoration-eval
Run started: 2026-09-03T13:26:02Z
Python: 3.12.6
Platform: Windows-11-10.0.26200-SP0
Helper versions: {'dashboard_application': '1.0.0', 'validation': '1.0.0', 'paths': '1.0.0'}

In [2]:
CONFIG_PATH = (
    PROJECT_ROOT
    / "config"
    / "evaluation"
    / "dashboard_validation.yaml"
)

CONFIG = load_dashboard_validation_config(PROJECT_ROOT)

APPLICATION = CONFIG["application"]
RUNTIME = CONFIG["runtime"]
PRESENTATION = CONFIG["presentation"]
BOUNDARIES = CONFIG["scientific_boundaries"]
EXPECTED_POPULATION = CONFIG["expected_population"]
OUTPUT_SPEC = CONFIG["outputs"]

PAGE_IDS = list(APPLICATION["page_ids"])
REQUIRED_INPUT_PATHS = required_input_paths(CONFIG, PROJECT_ROOT)

OUTPUT_ROOT = notebook_output_root(
    NOTEBOOK_STEM,
    PROJECT_ROOT,
)

OUTPUT_ROOT_PREEXISTED = OUTPUT_ROOT.exists()
PREEXISTING_OUTPUT_FILES = (
    sorted(
        path.relative_to(OUTPUT_ROOT).as_posix()
        for path in OUTPUT_ROOT.rglob("*")
        if path.is_file()
    )
    if OUTPUT_ROOT_PREEXISTED
    else []
)

OUTPUT_DIRS = ensure_output_subdirs(
    NOTEBOOK_STEM,
    ("validation", "reports", "manifests"),
    PROJECT_ROOT,
)

OUTPUT_PATHS = {
    key: PROJECT_ROOT / contract["path"]
    for key, contract in OUTPUT_SPEC.items()
}

EXPECTED_PAGE_IDS = [
    "overview",
    "study_design",
    "metric_framework",
    "model_performance",
    "robustness_uncertainty",
    "trustworthiness_xai",
    "case_explorer",
    "reports_reproducibility",
]

EXPECTED_OUTPUT_PATHS = {
    "dashboard_checks": (
        "outputs/35_dashboard_and_deployment_validation/"
        "validation/dashboard_checks.csv"
    ),
    "deployment_readiness": (
        "outputs/35_dashboard_and_deployment_validation/"
        "reports/deployment_readiness.md"
    ),
    "run_manifest": (
        "outputs/35_dashboard_and_deployment_validation/"
        "manifests/run_manifest.json"
    ),
    "artifacts": (
        "outputs/35_dashboard_and_deployment_validation/"
        "manifests/artifacts.csv"
    ),
}

OBSERVED_OUTPUT_PATHS = {
    key: path.relative_to(PROJECT_ROOT).as_posix()
    for key, path in OUTPUT_PATHS.items()
}

CONTRACT_CHECKS = (
    (
        "configuration_schema",
        "Configuration uses the approved Notebook 35 schema",
        DASHBOARD_VALIDATION_CONFIG_SCHEMA_VERSION,
        CONFIG["schema_version"],
        (
            CONFIG["schema_version"]
            == DASHBOARD_VALIDATION_CONFIG_SCHEMA_VERSION
        ),
    ),
    (
        "notebook_identity",
        "Notebook identity is fixed",
        {
            "id": NOTEBOOK_ID,
            "stem": NOTEBOOK_STEM,
        },
        {
            "id": CONFIG["notebook"]["id"],
            "stem": CONFIG["notebook"]["stem"],
        },
        (
            CONFIG["notebook"]["id"] == NOTEBOOK_ID
            and CONFIG["notebook"]["stem"] == NOTEBOOK_STEM
        ),
    ),
    (
        "dashboard_package_schema",
        "Notebook 34 package schema is locked",
        DASHBOARD_PACKAGE_SCHEMA_VERSION,
        APPLICATION["package_schema_version"],
        (
            APPLICATION["package_schema_version"]
            == DASHBOARD_PACKAGE_SCHEMA_VERSION
        ),
    ),
    (
        "dashboard_package_root",
        "The application consumes only the Notebook 34 package root",
        "outputs/34_final_streamlit_dashboard_assets",
        APPLICATION["dashboard_package_root"],
        (
            APPLICATION["dashboard_package_root"]
            == "outputs/34_final_streamlit_dashboard_assets"
        ),
    ),
    (
        "approved_page_order",
        "The approved eight-page order is unchanged",
        EXPECTED_PAGE_IDS,
        PAGE_IDS,
        PAGE_IDS == EXPECTED_PAGE_IDS,
    ),
    (
        "page_count",
        "Exactly eight principal pages are declared",
        8,
        int(APPLICATION["page_count"]),
        (
            int(APPLICATION["page_count"]) == 8
            and len(PAGE_IDS) == 8
        ),
    ),
    (
        "required_input_count",
        "All Notebook 35 input contracts are declared",
        18,
        len(REQUIRED_INPUT_PATHS),
        len(REQUIRED_INPUT_PATHS) == 18,
    ),
    (
        "canonical_output_count",
        "Exactly four canonical Notebook 35 outputs are declared",
        4,
        len(OUTPUT_PATHS),
        len(OUTPUT_PATHS) == 4,
    ),
    (
        "canonical_output_paths",
        "Canonical output paths match the approved contract",
        EXPECTED_OUTPUT_PATHS,
        OBSERVED_OUTPUT_PATHS,
        OBSERVED_OUTPUT_PATHS == EXPECTED_OUTPUT_PATHS,
    ),
    (
        "notebook_owned_output_root",
        "Every output remains under the Notebook 35 root",
        str(OUTPUT_ROOT),
        [str(path) for path in OUTPUT_PATHS.values()],
        all(
            path.resolve().is_relative_to(OUTPUT_ROOT.resolve())
            for path in OUTPUT_PATHS.values()
        ),
    ),
    (
        "clean_output_root",
        "No stale files existed in the Notebook 35 output root",
        [],
        PREEXISTING_OUTPUT_FILES,
        not PREEXISTING_OUTPUT_FILES,
    ),
    (
        "presentation_only",
        "The dashboard contract prohibits scientific recomputation",
        True,
        bool(BOUNDARIES["no_scientific_recomputation"]),
        bool(BOUNDARIES["no_scientific_recomputation"]),
    ),
    (
        "no_restoration_inference",
        "The dashboard contract prohibits restoration inference",
        True,
        bool(BOUNDARIES["no_restoration_inference"]),
        bool(BOUNDARIES["no_restoration_inference"]),
    ),
    (
        "no_combined_score",
        "The dashboard prohibits a universal combined score",
        True,
        bool(BOUNDARIES["no_universal_combined_score"]),
        bool(BOUNDARIES["no_universal_combined_score"]),
    ),
    (
        "complete_population_access",
        "Representative defaults do not restrict complete access",
        True,
        bool(
            PRESENTATION[
                "complete_population_must_remain_filterable"
            ]
        ),
        bool(
            PRESENTATION[
                "complete_population_must_remain_filterable"
            ]
        ),
    ),
)

for check_id, description, expected, observed, passed in CONTRACT_CHECKS:
    VALIDATION.add(
        validation_stage="batch_1_contract",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=passed,
        details=(
            ""
            if passed
            else "Notebook 35 differs from the approved preparation contract."
        ),
    )

VALIDATION.raise_for_blocking()

PAGE_CONTRACT_VIEW = pd.DataFrame(
    [
        {
            "display_order": index,
            "page_id": page_id,
            "display_name": APPLICATION["display_names"][page_id],
        }
        for index, page_id in enumerate(PAGE_IDS, start=1)
    ]
)

OUTPUT_CONTRACT_VIEW = pd.DataFrame(
    [
        {
            "output_key": key,
            "repository_relative_path": (
                path.relative_to(PROJECT_ROOT).as_posix()
            ),
            "parent_exists": path.parent.is_dir(),
            "file_exists": path.is_file(),
        }
        for key, path in OUTPUT_PATHS.items()
    ]
).sort_values("output_key").reset_index(drop=True)

display(PAGE_CONTRACT_VIEW)
display(OUTPUT_CONTRACT_VIEW)

print("Notebook contract passed.")
print("Pre-existing output files:", len(PREEXISTING_OUTPUT_FILES))
print("Created output directories:", sorted(OUTPUT_DIRS))
print("Canonical files persisted by this cell: 0")

   display_order                  page_id               display_name
0              1                 overview                   Overview
1              2             study_design               Study Design
2              3         metric_framework           Metric Framework
3              4        model_performance          Model Performance
4              5   robustness_uncertainty   Robustness & Uncertainty
5              6      trustworthiness_xai      Trustworthiness & XAI
6              7            case_explorer              Case Explorer
7              8  reports_reproducibility  Reports & Reproducibility

,output_key,repository_relative_path,parent_exists,file_exists
0,artifacts,outputs/35_dashboard_and_deployment_validation...,True,False
1,dashboard_checks,outputs/35_dashboard_and_deployment_validation...,True,False
2,deployment_readiness,outputs/35_dashboard_and_deployment_validation...,True,False
3,run_manifest,outputs/35_dashboard_and_deployment_validation...,True,False

Notebook contract passed.
Pre-existing output files: 0
Created output directories: ['manifests', 'reports', 'validation']
Canonical files persisted by this cell: 0

In [3]:
INVENTORY_PATH = (
    PROJECT_ROOT
    / "outputs"
    / "inventory"
    / "project_file_inventory.csv"
)
INVENTORY_RUN_PATH = (
    PROJECT_ROOT
    / "outputs"
    / "inventory"
    / "inventory_run.json"
)
PROJECT_PATHS_PATH = (
    PROJECT_ROOT
    / "outputs"
    / "inventory"
    / "project_paths.json"
)

with INVENTORY_RUN_PATH.open(
    "r",
    encoding="utf-8-sig",
) as handle:
    INVENTORY_RUN = json.load(handle)

INVENTORY = pd.read_csv(
    INVENTORY_PATH,
    low_memory=False,
)

with PROJECT_PATHS_PATH.open(
    "r",
    encoding="utf-8-sig",
) as handle:
    PROJECT_PATHS_REGISTRY = json.load(handle)

PROJECT_PATH_ERRORS = validate_project_paths_registry(
    PROJECT_PATHS_REGISTRY
)

IMPLEMENTATION_PATH = (
    PROJECT_ROOT
    / "docs"
    / "refactoring_implementation_guidelines.md"
)
ROADMAP_PATH = (
    PROJECT_ROOT
    / "docs"
    / "final_notebook_roadmap.md"
)
AUDIT_PATH = (
    PROJECT_ROOT
    / "docs"
    / "evidence_dependency_audit.md"
)
COVERAGE_PATH = (
    PROJECT_ROOT
    / "config"
    / "evaluation"
    / "evidence_coverage.yaml"
)

IMPLEMENTATION_TEXT = IMPLEMENTATION_PATH.read_text(
    encoding="utf-8-sig"
)
ROADMAP_TEXT = ROADMAP_PATH.read_text(
    encoding="utf-8-sig"
)
AUDIT_TEXT = AUDIT_PATH.read_text(
    encoding="utf-8-sig"
)
COVERAGE_TEXT = COVERAGE_PATH.read_text(
    encoding="utf-8-sig"
)

PREPARATION_FILES = {
    "config/evaluation/dashboard_validation.yaml",
    "config/evaluation/evidence_coverage.yaml",
    "docs/evidence_dependency_audit.md",
    "docs/final_notebook_roadmap.md",
    "docs/refactoring_implementation_guidelines.md",
    "notebooks/35_dashboard_and_deployment_validation.ipynb",
    (
        "outputs/34_final_streamlit_dashboard_assets/"
        "data/dashboard_summary.json"
    ),
    (
        "outputs/34_final_streamlit_dashboard_assets/"
        "manifests/dashboard_assets.csv"
    ),
    (
        "outputs/34_final_streamlit_dashboard_assets/"
        "manifests/run_manifest.json"
    ),
    "src/restoration_eval/dashboard_application.py",
    "streamlit_app.py",
}

INVENTORY_PATHS = set(
    INVENTORY["relative_path"].astype(str)
)

CURRENT_PYTHON = (
    sys.version_info.major,
    sys.version_info.minor,
)

SUPPORTED_PYTHON = {
    tuple(
        int(part)
        for part in version.split(".")
    )
    for version in RUNTIME[
        "accepted_python_minor_versions"
    ]
}

IMPLEMENTATION_TEXT_CASEFOLD = (
    IMPLEMENTATION_TEXT.casefold()
)
ROADMAP_TEXT_CASEFOLD = ROADMAP_TEXT.casefold()
AUDIT_TEXT_CASEFOLD = AUDIT_TEXT.casefold()
COVERAGE_TEXT_CASEFOLD = COVERAGE_TEXT.casefold()

MANUAL_EDITING_POLICY_PRESENT = (
    "the assistant must not insert batch 1 or any later cells"
    in IMPLEMENTATION_TEXT_CASEFOLD
)

MOCK_FIDELITY_POLICY_PRESENT = (
    (
        "dashboard design, mock fidelity, "
        "and implementation boundary"
    )
    in IMPLEMENTATION_TEXT_CASEFOLD
)

ROADMAP_ENTRY_PRESENT = all(
    fragment in ROADMAP_TEXT_CASEFOLD
    for fragment in (
        "35_dashboard_and_deployment_validation.ipynb",
        (
            "the application consumes only the fixed "
            "notebook 34"
        ),
        "eight-page",
    )
)

# The audit now records the completed Notebook 35 state.
# Validate stable contract identifiers instead of an obsolete
# preparation-stage sentence.
EVIDENCE_AUDIT_ENTRY_PRESENT = all(
    fragment in AUDIT_TEXT_CASEFOLD
    for fragment in (
        (
            "notebook 35 is complete against the fixed "
            "notebook 34 dashboard package"
        ),
        "config/evaluation/dashboard_validation.yaml",
        "eight-page",
    )
)

MACHINE_COVERAGE_ENTRY_PRESENT = all(
    fragment in COVERAGE_TEXT_CASEFOLD
    for fragment in (
        'stem: "35_dashboard_and_deployment_validation"',
        "visual_records: 23964",
        "read_only_eight_page_dashboard",
    )
)

GOVERNANCE_CHECKS = (
    (
        "inventory_status",
        "The refreshed inventory completed successfully",
        "completed",
        INVENTORY_RUN.get("status"),
        INVENTORY_RUN.get("status") == "completed",
    ),
    (
        "inventory_read_errors",
        "The refreshed inventory contains no read errors",
        0,
        int(
            INVENTORY_RUN["summary"][
                "read_error_count"
            ]
        ),
        (
            int(
                INVENTORY_RUN["summary"][
                    "read_error_count"
                ]
            )
            == 0
        ),
    ),
    (
        "inventory_repository_root",
        "The inventory belongs to this repository",
        str(PROJECT_ROOT),
        INVENTORY_RUN.get("repository_root"),
        (
            Path(
                INVENTORY_RUN["repository_root"]
            ).resolve()
            == PROJECT_ROOT
        ),
    ),
    (
        "supported_python",
        "The kernel uses Python 3.11 or 3.12",
        sorted(
            ".".join(
                str(part)
                for part in version
            )
            for version in SUPPORTED_PYTHON
        ),
        (
            f"{CURRENT_PYTHON[0]}."
            f"{CURRENT_PYTHON[1]}"
        ),
        CURRENT_PYTHON in SUPPORTED_PYTHON,
    ),
    (
        "preparation_files_in_inventory",
        (
            "All Notebook 35 preparation files "
            "are indexed"
        ),
        sorted(PREPARATION_FILES),
        sorted(
            PREPARATION_FILES
            & INVENTORY_PATHS
        ),
        PREPARATION_FILES.issubset(
            INVENTORY_PATHS
        ),
    ),
    (
        "project_paths_schema",
        (
            "The project-path registry uses "
            "the canonical schema"
        ),
        PROJECT_PATHS_SCHEMA_VERSION,
        PROJECT_PATHS_REGISTRY.get(
            "registry_schema_version"
        ),
        (
            PROJECT_PATHS_REGISTRY.get(
                "registry_schema_version"
            )
            == PROJECT_PATHS_SCHEMA_VERSION
            and not PROJECT_PATH_ERRORS
        ),
    ),
    (
        "manual_notebook_editing_policy",
        (
            "Notebook cells remain user-pasted "
            "and user-executed"
        ),
        True,
        MANUAL_EDITING_POLICY_PRESENT,
        MANUAL_EDITING_POLICY_PRESENT,
    ),
    (
        "mock_fidelity_policy",
        (
            "The approved dashboard mock-fidelity "
            "policy is present"
        ),
        True,
        MOCK_FIDELITY_POLICY_PRESENT,
        MOCK_FIDELITY_POLICY_PRESENT,
    ),
    (
        "roadmap_entry",
        (
            "Notebook 35 remains in the "
            "final roadmap"
        ),
        True,
        ROADMAP_ENTRY_PRESENT,
        ROADMAP_ENTRY_PRESENT,
    ),
    (
        "evidence_audit_entry",
        (
            "The completed Notebook 35 contract "
            "is recorded in the evidence audit"
        ),
        True,
        EVIDENCE_AUDIT_ENTRY_PRESENT,
        EVIDENCE_AUDIT_ENTRY_PRESENT,
    ),
    (
        "machine_readable_coverage_entry",
        (
            "The detailed Notebook 35 evidence "
            "gate is recorded"
        ),
        True,
        MACHINE_COVERAGE_ENTRY_PRESENT,
        MACHINE_COVERAGE_ENTRY_PRESENT,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in GOVERNANCE_CHECKS:
    VALIDATION.add(
        validation_stage=(
            "batch_1_inventory_governance"
        ),
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "Inventory or governing-document "
                "preflight failed."
            )
        ),
    )

VALIDATION.raise_for_blocking()

PREPARATION_INVENTORY = (
    INVENTORY.loc[
        INVENTORY["relative_path"].isin(
            PREPARATION_FILES
        ),
        [
            "relative_path",
            "file_kind",
            "format",
            "size_bytes",
            "read_error_count",
        ],
    ]
    .sort_values("relative_path")
    .reset_index(drop=True)
)

display(PREPARATION_INVENTORY)

print("Inventory and governance preflight passed.")
print(
    "Inventory run ID:",
    INVENTORY_RUN["inventory_run_id"],
)
print(
    "Indexed files:",
    INVENTORY_RUN["summary"]["file_count"],
)
print(
    "Preparation files indexed:",
    len(PREPARATION_INVENTORY),
)

,relative_path,file_kind,format,size_bytes,read_error_count
0,config/evaluation/dashboard_validation.yaml,yaml,yaml,11652,0
1,config/evaluation/evidence_coverage.yaml,yaml,yaml,79194,0
2,docs/evidence_dependency_audit.md,markdown,markdown,42814,0
3,docs/final_notebook_roadmap.md,markdown,markdown,84404,0
4,docs/refactoring_implementation_guidelines.md,markdown,markdown,68129,0
5,notebooks/35_dashboard_and_deployment_validati...,notebook,notebook,700590,0
6,outputs/34_final_streamlit_dashboard_assets/da...,json,json,14188,0
7,outputs/34_final_streamlit_dashboard_assets/ma...,manifest_table,csv,15091,0
8,outputs/34_final_streamlit_dashboard_assets/ma...,json,json,32789,0
9,src/restoration_eval/dashboard_application.py,python,python,21784,0
10,streamlit_app.py,python,python,42891,0

Inventory and governance preflight passed.
Inventory run ID: inventory_20260903T100938Z_41e6dccc
Indexed files: 18967
Preparation files indexed: 11

In [4]:
REQUIREMENTS_PATH = PROJECT_ROOT / "requirements.txt"
EXPERIMENT_REQUIREMENTS_PATH = (
    PROJECT_ROOT / "requirements_experiments.txt"
)
APP_PATH = PROJECT_ROOT / APPLICATION["entrypoint"]
HELPER_PATH = PROJECT_ROOT / APPLICATION["helper_module"]
PACKAGE_ROOT = PROJECT_ROOT / APPLICATION["dashboard_package_root"]

REQUIREMENTS_LINES = [
    line.strip()
    for line in REQUIREMENTS_PATH.read_text(
        encoding="utf-8-sig"
    ).splitlines()
    if line.strip() and not line.lstrip().startswith("#")
]

REQUIREMENTS_PINS = {
    line.split("==", maxsplit=1)[0].strip().lower():
    line.split("==", maxsplit=1)[1].strip()
    for line in REQUIREMENTS_LINES
    if "==" in line
}

PACKAGE_DISTRIBUTIONS = {
    "streamlit": "streamlit",
    "pandas": "pandas",
    "plotly": "plotly",
    "numpy": "numpy",
    "pyarrow": "pyarrow",
    "pillow": "Pillow",
    "pyyaml": "PyYAML",
}

INSTALLED_VERSIONS = {}
for package_key, distribution_name in PACKAGE_DISTRIBUTIONS.items():
    try:
        INSTALLED_VERSIONS[package_key] = metadata.version(
            distribution_name
        )
    except metadata.PackageNotFoundError:
        INSTALLED_VERSIONS[package_key] = "not_installed"

TARGET_VERSIONS = {
    str(package).lower(): str(version)
    for package, version in RUNTIME["packages"].items()
}

MISSING_PACKAGES = sorted(
    package
    for package, version in INSTALLED_VERSIONS.items()
    if version == "not_installed"
)

PINNED_DASHBOARD_PACKAGES = {
    "streamlit",
    "pandas",
    "plotly",
    "numpy",
    "pyarrow",
    "pillow",
}

MISSING_REQUIREMENT_PINS = sorted(
    package
    for package in PINNED_DASHBOARD_PACKAGES
    if REQUIREMENTS_PINS.get(package)
    != TARGET_VERSIONS.get(package)
)

APP_SOURCE = APP_PATH.read_text(encoding="utf-8")
try:
    ast.parse(APP_SOURCE, filename=str(APP_PATH))
    APP_SYNTAX_VALID = True
    APP_SYNTAX_ISSUE = ""
except SyntaxError as exc:
    APP_SYNTAX_VALID = False
    APP_SYNTAX_ISSUE = (
        f"{exc.msg} at line {exc.lineno}, column {exc.offset}"
    )

DEPENDENCY_CHECKS = (
    (
        "application_entrypoint",
        "The Streamlit entrypoint exists",
        True,
        APP_PATH.is_file(),
        APP_PATH.is_file(),
    ),
    (
        "dashboard_helper",
        "The shared dashboard helper exists",
        True,
        HELPER_PATH.is_file(),
        HELPER_PATH.is_file(),
    ),
    (
        "notebook_34_package_root",
        "The fixed Notebook 34 package root exists",
        True,
        PACKAGE_ROOT.is_dir(),
        PACKAGE_ROOT.is_dir(),
    ),
    (
        "application_syntax",
        "The Streamlit entrypoint has valid Python syntax",
        "valid",
        APP_SYNTAX_ISSUE or "valid",
        APP_SYNTAX_VALID,
    ),
    (
        "required_packages_installed",
        "All declared dashboard packages are installed",
        [],
        MISSING_PACKAGES,
        not MISSING_PACKAGES,
    ),
    (
        "requirements_pins",
        "Dashboard requirements match the validation contract",
        [],
        MISSING_REQUIREMENT_PINS,
        not MISSING_REQUIREMENT_PINS,
    ),
)

for check_id, description, expected, observed, passed in DEPENDENCY_CHECKS:
    VALIDATION.add(
        validation_stage="batch_1_dependencies",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=passed,
        details=(
            ""
            if passed
            else "The application runtime contract is incomplete."
        ),
    )

VERSION_MISMATCHES = []

for package_key in sorted(TARGET_VERSIONS):
    expected_version = TARGET_VERSIONS[package_key]
    observed_version = INSTALLED_VERSIONS.get(
        package_key,
        "not_installed",
    )
    version_matches = observed_version == expected_version

    if not version_matches:
        VERSION_MISMATCHES.append(
            {
                "package": package_key,
                "expected": expected_version,
                "observed": observed_version,
            }
        )

    VALIDATION.add(
        validation_stage="batch_1_dependency_versions",
        check_id=f"package_version__{package_key}",
        check_description=(
            f"Installed {package_key} version matches the deployment target"
        ),
        severity="warning",
        expected=expected_version,
        observed=observed_version,
        passed=version_matches,
        details=(
            ""
            if version_matches
            else (
                "The package is installed, but the deployment environment "
                "should be reconciled before claiming exact reproducibility."
            )
        ),
    )

VALIDATION.raise_for_blocking()

PACKAGE_VERSION_VIEW = pd.DataFrame(
    [
        {
            "package": package,
            "target_version": TARGET_VERSIONS[package],
            "installed_version": INSTALLED_VERSIONS[package],
            "exact_match": (
                TARGET_VERSIONS[package]
                == INSTALLED_VERSIONS[package]
            ),
        }
        for package in sorted(TARGET_VERSIONS)
    ]
)

display(PACKAGE_VERSION_VIEW)

print("Dependency preflight passed.")
print("Missing packages:", MISSING_PACKAGES)
print("Requirement-pin mismatches:", MISSING_REQUIREMENT_PINS)
print("Installed-version differences:", len(VERSION_MISMATCHES))
print(
    "Application syntax:",
    "valid" if APP_SYNTAX_VALID else APP_SYNTAX_ISSUE,
)

     package target_version installed_version  exact_match
0      numpy         1.26.4            1.26.4         True
1     pandas          2.3.3             2.3.3         True
2     pillow         12.3.0             9.5.0        False
3     plotly          6.9.0             6.8.0        False
4    pyarrow         20.0.0            24.0.0        False
5     pyyaml          6.0.3             6.0.3         True
6  streamlit         1.56.0            1.59.0        False

Dependency preflight passed.
Missing packages: []
Requirement-pin mismatches: []
Installed-version differences: 4
Application syntax: valid

In [5]:
CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

VALIDATION.add(
    validation_stage="batch_1_final_preflight",
    check_id="no_canonical_files_written",
    check_description=(
        "Batch 1 has not persisted canonical Notebook 35 files"
    ),
    severity="blocking",
    expected=[],
    observed=CANONICAL_FILES_AFTER_BATCH,
    passed=not CANONICAL_FILES_AFTER_BATCH,
    details=(
        ""
        if not CANONICAL_FILES_AFTER_BATCH
        else "Batch 1 must create directories only."
    ),
)

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

VALIDATION_STAGE_SUMMARY = (
    VALIDATION_FRAME
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

VALIDATION_STAGE_SUMMARY["failed"] = (
    VALIDATION_STAGE_SUMMARY["checks"]
    - VALIDATION_STAGE_SUMMARY["passed"]
)

FAILED_WARNING_CHECKS = VALIDATION_FRAME[
    (~VALIDATION_FRAME["passed"])
    & (VALIDATION_FRAME["severity"] == "warning")
].copy()

display(VALIDATION_STAGE_SUMMARY)

if not FAILED_WARNING_CHECKS.empty:
    display(
        FAILED_WARNING_CHECKS[
            [
                "check_id",
                "expected",
                "observed",
                "details",
            ]
        ].reset_index(drop=True)
    )

print("Batch 1 preflight passed.")
print("Validation checks:", len(VALIDATION_FRAME))
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Non-blocking version warnings:", len(FAILED_WARNING_CHECKS))
print("Approved dashboard pages:", len(PAGE_IDS))
print("Declared Notebook 34 inputs:", len(REQUIRED_INPUT_PATHS))
print("Output root:", OUTPUT_ROOT)
print("Canonical files persisted by Batch 1: 0")

               validation_stage  severity  checks  passed  failed
0              batch_1_contract  blocking      15      15       0
1          batch_1_dependencies  blocking       6       6       0
2   batch_1_dependency_versions   warning       7       3       4
3       batch_1_final_preflight  blocking       1       1       0
4  batch_1_inventory_governance  blocking      11      11       0

,check_id,expected,observed,details
0,package_version__pillow,12.3.0,9.5.0,"The package is installed, but the deployment e..."
1,package_version__plotly,6.9.0,6.8.0,"The package is installed, but the deployment e..."
2,package_version__pyarrow,20.0.0,24.0.0,"The package is installed, but the deployment e..."
3,package_version__streamlit,1.56.0,1.59.0,"The package is installed, but the deployment e..."

Batch 1 preflight passed.
Validation checks: 40
Blocking failures: 0
Non-blocking version warnings: 4
Approved dashboard pages: 8
Declared Notebook 34 inputs: 18
Output root: D:\Masters\FH\Thesis\painting-restoration-eval\outputs\35_dashboard_and_deployment_validation
Canonical files persisted by Batch 1: 0

## Batch 2 — Notebook 34 package integrity and schema validation

This batch loads the fixed Notebook 34 dashboard package and validates:

- all nine normalized dashboard tables;
- all four CSV dashboard indexes;
- the filter-options index;
- the dashboard summary;
- the dashboard-asset manifest;
- the Notebook 34 run manifest and validation table;
- exact approved row counts and required columns;
- dataframe and JSON schema identities;
- the complete 15-asset manifest;
- every manifest-declared asset path and checksum;
- the exact 19-file physical Notebook 34 package;
- the absence of error or blocking failures in Notebook 34.

The loaded package becomes the sole evidence source for later Notebook 35 validation batches.

This batch does not import the Streamlit application, inspect all 23,964 indexed visual paths, or persist canonical Notebook 35 files.

In [6]:
from restoration_eval.dashboard_application import (
    audit_dashboard_package,
    load_dashboard_package,
)
from restoration_eval.manifests import sha256_file
from restoration_eval.paths import resolve_repo_path


def collect_dashboard_checks(checks: pd.DataFrame) -> None:
    """Transfer helper checks into the notebook validation collector."""

    if checks.empty:
        return

    for record in checks.to_dict(orient="records"):
        VALIDATION.add(
            validation_stage=str(record["validation_stage"]),
            check_id=str(record["check_id"]),
            check_description=str(record["check_description"]),
            severity=str(record["severity"]),
            expected=record["expected"],
            observed=record["observed"],
            passed=bool(record["passed"]),
            details=record.get("details", ""),
        )


PACKAGE_AUDIT = audit_dashboard_package(PROJECT_ROOT)
collect_dashboard_checks(PACKAGE_AUDIT)
VALIDATION.raise_for_blocking()

BUNDLE = load_dashboard_package(PROJECT_ROOT)

DASHBOARD_SUMMARY = dict(BUNDLE.summary)
FILTER_OPTIONS = dict(BUNDLE.filters)
UPSTREAM_MANIFEST = dict(BUNDLE.upstream_manifest)

DASHBOARD_TABLES = dict(BUNDLE.tables)
DASHBOARD_INDEXES = dict(BUNDLE.indexes)
DASHBOARD_ASSETS = BUNDLE.dashboard_assets.copy()
UPSTREAM_CHECKS = BUNDLE.upstream_checks.copy()

LOADED_COMPONENTS = pd.DataFrame(
    [
        {
            "component_key": key,
            "component_type": "dashboard_table",
            "rows": len(frame),
            "columns": len(frame.columns),
        }
        for key, frame in DASHBOARD_TABLES.items()
    ]
    + [
        {
            "component_key": key,
            "component_type": "dashboard_index",
            "rows": len(frame),
            "columns": len(frame.columns),
        }
        for key, frame in DASHBOARD_INDEXES.items()
    ]
    + [
        {
            "component_key": "dashboard_assets",
            "component_type": "manifest",
            "rows": len(DASHBOARD_ASSETS),
            "columns": len(DASHBOARD_ASSETS.columns),
        },
        {
            "component_key": "upstream_validation",
            "component_type": "validation",
            "rows": len(UPSTREAM_CHECKS),
            "columns": len(UPSTREAM_CHECKS.columns),
        },
    ]
).sort_values(
    ["component_type", "component_key"]
).reset_index(drop=True)

display(LOADED_COMPONENTS)

print("Notebook 34 dashboard package loaded.")
print("Package audit checks:", len(PACKAGE_AUDIT))
print(
    "Package audit failures:",
    int((~PACKAGE_AUDIT["passed"]).sum()),
)
print("Dashboard tables:", len(DASHBOARD_TABLES))
print("CSV indexes:", len(DASHBOARD_INDEXES))
print("Dashboard assets:", len(DASHBOARD_ASSETS))
print("Upstream validation checks:", len(UPSTREAM_CHECKS))

                 component_key   component_type   rows  columns
0                   case_index  dashboard_index   1785       43
1               painting_index  dashboard_index     50       27
2                 report_index  dashboard_index    104       24
3           visual_asset_index  dashboard_index  23964       28
4              compute_summary  dashboard_table     35       34
5            headline_findings  dashboard_table      8       18
6             metric_framework  dashboard_table    178       25
7          performance_summary  dashboard_table   1241       35
8   research_question_coverage  dashboard_table      4       14
9          sensitivity_summary  dashboard_table  18951       38
10                study_design  dashboard_table     35       19
11     trustworthiness_summary  dashboard_table    284       30
12         uncertainty_summary  dashboard_table   1723       30
13            dashboard_assets         manifest     15       16
14         upstream_validation       validation    410        8

Notebook 34 dashboard package loaded.
Package audit checks: 76
Package audit failures: 0
Dashboard tables: 9
CSV indexes: 4
Dashboard assets: 15
Upstream validation checks: 410

In [7]:
PACKAGE_ROOT = (
    PROJECT_ROOT
    / APPLICATION["dashboard_package_root"]
).resolve()

ASSET_PATH_RECORDS = []

for number, row in enumerate(
    DASHBOARD_ASSETS.itertuples(index=False),
    start=1,
):
    asset_key = str(row.asset_key)
    relative_path = str(row.relative_path)

    try:
        resolved_path = resolve_repo_path(
            relative_path,
            PROJECT_ROOT,
        )
        path_is_safe = resolved_path.is_relative_to(PROJECT_ROOT)
        path_is_package_owned = resolved_path.is_relative_to(
            PACKAGE_ROOT
        )
    except ValueError:
        resolved_path = None
        path_is_safe = False
        path_is_package_owned = False

    path_exists = (
        resolved_path is not None
        and resolved_path.is_file()
    )

    observed_checksum = (
        sha256_file(resolved_path)
        if path_exists
        else ""
    )

    expected_checksum = str(row.sha256)
    checksum_matches = (
        path_exists
        and observed_checksum == expected_checksum
    )

    asset_passed = (
        path_is_safe
        and path_is_package_owned
        and path_exists
        and checksum_matches
        and str(row.validation_status) == "passed"
        and str(row.status) == "ok"
    )

    ASSET_PATH_RECORDS.append(
        {
            "asset_key": asset_key,
            "relative_path": relative_path,
            "exists": path_exists,
            "package_owned": path_is_package_owned,
            "checksum_matches": checksum_matches,
            "validation_status": row.validation_status,
            "status": row.status,
            "passed": asset_passed,
        }
    )

    VALIDATION.add(
        validation_stage="batch_2_asset_integrity",
        check_id=(
            "asset__"
            + asset_key.replace(".", "__")
        ),
        check_description=(
            f"Dashboard asset is package-owned and checksum-valid: "
            f"{asset_key}"
        ),
        severity="blocking",
        expected={
            "exists": True,
            "package_owned": True,
            "checksum_matches": True,
            "validation_status": "passed",
            "status": "ok",
        },
        observed={
            "exists": path_exists,
            "package_owned": path_is_package_owned,
            "checksum_matches": checksum_matches,
            "validation_status": str(row.validation_status),
            "status": str(row.status),
        },
        passed=asset_passed,
        details=relative_path,
    )

    if number % 5 == 0 or number == len(DASHBOARD_ASSETS):
        print(
            f"Asset integrity: "
            f"{number}/{len(DASHBOARD_ASSETS)} checked."
        )

ASSET_PATH_AUDIT = pd.DataFrame(ASSET_PATH_RECORDS)

MANIFEST_ASSET_PATHS = set(
    DASHBOARD_ASSETS["relative_path"].astype(str)
)

SUPPORT_FILE_PATHS = {
    (
        "outputs/34_final_streamlit_dashboard_assets/"
        "manifests/dashboard_assets.csv"
    ),
    (
        "outputs/34_final_streamlit_dashboard_assets/"
        "manifests/artifacts.csv"
    ),
    (
        "outputs/34_final_streamlit_dashboard_assets/"
        "manifests/run_manifest.json"
    ),
    (
        "outputs/34_final_streamlit_dashboard_assets/"
        "validation/checks.csv"
    ),
}

EXPECTED_PACKAGE_FILES = (
    MANIFEST_ASSET_PATHS
    | SUPPORT_FILE_PATHS
)

OBSERVED_PACKAGE_FILES = {
    path.relative_to(PROJECT_ROOT).as_posix()
    for path in PACKAGE_ROOT.rglob("*")
    if path.is_file()
}

PACKAGE_FILE_CHECKS = (
    (
        "asset_manifest_rows",
        "The asset manifest contains exactly 15 assets",
        15,
        len(DASHBOARD_ASSETS),
        len(DASHBOARD_ASSETS) == 15,
    ),
    (
        "asset_ids_unique",
        "Every dashboard asset ID is unique",
        len(DASHBOARD_ASSETS),
        DASHBOARD_ASSETS["dashboard_asset_id"].nunique(),
        (
            DASHBOARD_ASSETS["dashboard_asset_id"].nunique()
            == len(DASHBOARD_ASSETS)
        ),
    ),
    (
        "asset_keys_unique",
        "Every dashboard asset key is unique",
        len(DASHBOARD_ASSETS),
        DASHBOARD_ASSETS["asset_key"].nunique(),
        (
            DASHBOARD_ASSETS["asset_key"].nunique()
            == len(DASHBOARD_ASSETS)
        ),
    ),
    (
        "asset_paths_unique",
        "Every dashboard asset path is unique",
        len(DASHBOARD_ASSETS),
        DASHBOARD_ASSETS["relative_path"].nunique(),
        (
            DASHBOARD_ASSETS["relative_path"].nunique()
            == len(DASHBOARD_ASSETS)
        ),
    ),
    (
        "asset_integrity",
        "All manifest assets pass path and checksum validation",
        0,
        int((~ASSET_PATH_AUDIT["passed"]).sum()),
        ASSET_PATH_AUDIT["passed"].all(),
    ),
    (
        "physical_file_count",
        "The Notebook 34 package contains exactly 19 physical files",
        19,
        len(OBSERVED_PACKAGE_FILES),
        len(OBSERVED_PACKAGE_FILES) == 19,
    ),
    (
        "physical_file_set",
        "The physical package matches the manifest and support-file set",
        sorted(EXPECTED_PACKAGE_FILES),
        sorted(OBSERVED_PACKAGE_FILES),
        OBSERVED_PACKAGE_FILES == EXPECTED_PACKAGE_FILES,
    ),
)

for check_id, description, expected, observed, passed in (
    PACKAGE_FILE_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_2_package_integrity",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=passed,
        details=(
            ""
            if passed
            else "The Notebook 34 physical package differs from its manifest."
        ),
    )

VALIDATION.raise_for_blocking()

display(ASSET_PATH_AUDIT)

print("Dashboard-asset integrity passed.")
print("Manifest assets:", len(MANIFEST_ASSET_PATHS))
print("Support files:", len(SUPPORT_FILE_PATHS))
print("Physical package files:", len(OBSERVED_PACKAGE_FILES))

Asset integrity: 5/15 checked.
Asset integrity: 10/15 checked.
Asset integrity: 15/15 checked.

,asset_key,relative_path,exists,package_owned,checksum_matches,validation_status,status,passed
0,dashboard.table.headline_findings,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
1,dashboard.table.study_design,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
2,dashboard.table.metric_framework,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
3,dashboard.table.performance_summary,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
4,dashboard.table.sensitivity_summary,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
5,dashboard.table.uncertainty_summary,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
6,dashboard.table.trustworthiness_summary,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
7,dashboard.table.compute_summary,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
8,dashboard.table.research_question_coverage,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
9,dashboard.index.case_index,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
10,dashboard.index.painting_index,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
11,dashboard.index.visual_asset_index,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
12,dashboard.index.report_index,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
13,dashboard.index.filter_options,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True
14,dashboard.summary,outputs/34_final_streamlit_dashboard_assets/da...,True,True,True,passed,ok,True

Dashboard-asset integrity passed.
Manifest assets: 15
Support files: 4
Physical package files: 19

In [8]:
ROW_SCHEMA_EXPECTATIONS = {
    "headline_findings": "dashboard_package.v1",
    "study_design": "dashboard_package.v1",
    "metric_framework": "dashboard_package.v1",
    "performance_summary": "dashboard_package.v1",
    "sensitivity_summary": "dashboard_package.v1",
    "uncertainty_summary": "dashboard_package.v1",
    "trustworthiness_summary": "dashboard_package.v1",
    "compute_summary": "dashboard_package.v1",
    "research_question_coverage": "dashboard_package.v1",
    "case_index": "dashboard_case_index.v1",
    "painting_index": "dashboard_painting_index.v1",
    "visual_asset_index": "dashboard_package.v1",
    "report_index": "dashboard_package.v1",
}

ALL_PACKAGE_FRAMES = {
    **DASHBOARD_TABLES,
    **DASHBOARD_INDEXES,
}

SCHEMA_AUDIT_RECORDS = []

for component_key, expected_schema in (
    ROW_SCHEMA_EXPECTATIONS.items()
):
    frame = ALL_PACKAGE_FRAMES[component_key]

    observed_schemas = sorted(
        frame["schema_version"]
        .dropna()
        .astype(str)
        .unique()
        .tolist()
    )

    expected_schemas = [expected_schema]
    schema_passed = observed_schemas == expected_schemas

    configured_rows = int(
        CONFIG["required_inputs"][component_key]["rows"]
    )
    observed_rows = len(frame)
    row_count_passed = observed_rows == configured_rows

    required_columns = set(
        CONFIG["required_columns"][component_key]
    )
    missing_columns = sorted(
        required_columns - set(frame.columns)
    )
    columns_passed = not missing_columns

    component_passed = (
        schema_passed
        and row_count_passed
        and columns_passed
    )

    SCHEMA_AUDIT_RECORDS.append(
        {
            "component_key": component_key,
            "expected_schema": expected_schema,
            "observed_schemas": observed_schemas,
            "expected_rows": configured_rows,
            "observed_rows": observed_rows,
            "column_count": len(frame.columns),
            "missing_columns": missing_columns,
            "passed": component_passed,
        }
    )

    VALIDATION.add(
        validation_stage="batch_2_dataframe_schemas",
        check_id=f"schema__{component_key}",
        check_description=(
            f"Dashboard component matches its row and column contract: "
            f"{component_key}"
        ),
        severity="blocking",
        expected={
            "schemas": expected_schemas,
            "rows": configured_rows,
            "missing_columns": [],
        },
        observed={
            "schemas": observed_schemas,
            "rows": observed_rows,
            "missing_columns": missing_columns,
        },
        passed=component_passed,
        details=(
            ""
            if component_passed
            else "Row, column, or schema identity differs from the contract."
        ),
    )

SCHEMA_AUDIT = pd.DataFrame(SCHEMA_AUDIT_RECORDS)

ASSET_SCHEMA_RECORDS = []

for row in DASHBOARD_ASSETS.itertuples(index=False):
    asset_key = str(row.asset_key)

    if asset_key.startswith("dashboard.table."):
        contract_key = asset_key.removeprefix(
            "dashboard.table."
        )
    elif asset_key.startswith("dashboard.index."):
        contract_key = asset_key.removeprefix(
            "dashboard.index."
        )
    elif asset_key == "dashboard.summary":
        contract_key = "dashboard_summary"
    else:
        contract_key = ""

    contract_exists = (
        contract_key in CONFIG["required_inputs"]
    )

    expected_schema = (
        CONFIG["required_inputs"][contract_key][
            "schema_version"
        ]
        if contract_exists
        else ""
    )

    expected_path = (
        CONFIG["required_inputs"][contract_key]["path"]
        if contract_exists
        else ""
    )

    asset_contract_passed = (
        contract_exists
        and str(row.schema_version) == expected_schema
        and str(row.relative_path) == expected_path
    )

    ASSET_SCHEMA_RECORDS.append(
        {
            "asset_key": asset_key,
            "contract_key": contract_key,
            "expected_schema": expected_schema,
            "observed_schema": str(row.schema_version),
            "path_matches": (
                str(row.relative_path) == expected_path
            ),
            "passed": asset_contract_passed,
        }
    )

    VALIDATION.add(
        validation_stage="batch_2_asset_contracts",
        check_id=(
            "asset_contract__"
            + asset_key.replace(".", "__")
        ),
        check_description=(
            f"Dashboard asset matches its configured schema and path: "
            f"{asset_key}"
        ),
        severity="blocking",
        expected={
            "contract_key": contract_key,
            "schema": expected_schema,
            "path": expected_path,
        },
        observed={
            "contract_key": contract_key,
            "schema": str(row.schema_version),
            "path": str(row.relative_path),
        },
        passed=asset_contract_passed,
        details=(
            ""
            if asset_contract_passed
            else "The asset-manifest record differs from configuration."
        ),
    )

ASSET_SCHEMA_AUDIT = pd.DataFrame(
    ASSET_SCHEMA_RECORDS
)

JSON_AND_RUN_CHECKS = (
    (
        "dashboard_summary_schema",
        "Dashboard summary uses the approved package schema",
        "dashboard_package.v1",
        DASHBOARD_SUMMARY.get("schema_version"),
        (
            DASHBOARD_SUMMARY.get("schema_version")
            == "dashboard_package.v1"
        ),
    ),
    (
        "filter_options_schema",
        "Filter options use the approved index schema",
        "dashboard_filter_options.v1",
        FILTER_OPTIONS.get("schema_version"),
        (
            FILTER_OPTIONS.get("schema_version")
            == "dashboard_filter_options.v1"
        ),
    ),
    (
        "upstream_manifest_schema",
        "Notebook 34 uses the canonical run-manifest schema",
        "run_manifest.v1",
        UPSTREAM_MANIFEST.get(
            "manifest_schema_version"
        ),
        (
            UPSTREAM_MANIFEST.get(
                "manifest_schema_version"
            )
            == "run_manifest.v1"
        ),
    ),
    (
        "upstream_run_status",
        "Notebook 34 completed successfully",
        "completed",
        UPSTREAM_MANIFEST.get("run_status"),
        (
            UPSTREAM_MANIFEST.get("run_status")
            == "completed"
        ),
    ),
    (
        "summary_asset_count",
        "Dashboard summary records all manifest assets",
        len(DASHBOARD_ASSETS),
        DASHBOARD_SUMMARY.get("dashboard_asset_count"),
        (
            DASHBOARD_SUMMARY.get(
                "dashboard_asset_count"
            )
            == len(DASHBOARD_ASSETS)
        ),
    ),
    (
        "summary_physical_file_count",
        "Dashboard summary records all physical package files",
        len(OBSERVED_PACKAGE_FILES),
        DASHBOARD_SUMMARY.get(
            "physical_output_file_count"
        ),
        (
            DASHBOARD_SUMMARY.get(
                "physical_output_file_count"
            )
            == len(OBSERVED_PACKAGE_FILES)
        ),
    ),
)

for check_id, description, expected, observed, passed in (
    JSON_AND_RUN_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_2_json_and_run_contracts",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=passed,
        details=(
            ""
            if passed
            else "JSON schema or Notebook 34 run contract differs."
        ),
    )

VALIDATION.raise_for_blocking()

display(SCHEMA_AUDIT)
display(ASSET_SCHEMA_AUDIT)

print("Schema validation passed.")
print("Dataframe contracts:", len(SCHEMA_AUDIT))
print("Asset contracts:", len(ASSET_SCHEMA_AUDIT))
print(
    "JSON package schemas:",
    {
        "summary": DASHBOARD_SUMMARY["schema_version"],
        "filters": FILTER_OPTIONS["schema_version"],
        "run_manifest": UPSTREAM_MANIFEST[
            "manifest_schema_version"
        ],
    },
)

,component_key,expected_schema,observed_schemas,expected_rows,observed_rows,column_count,missing_columns,passed
0,headline_findings,dashboard_package.v1,[dashboard_package.v1],8,8,18,[],True
1,study_design,dashboard_package.v1,[dashboard_package.v1],35,35,19,[],True
2,metric_framework,dashboard_package.v1,[dashboard_package.v1],178,178,25,[],True
3,performance_summary,dashboard_package.v1,[dashboard_package.v1],1241,1241,35,[],True
4,sensitivity_summary,dashboard_package.v1,[dashboard_package.v1],18951,18951,38,[],True
5,uncertainty_summary,dashboard_package.v1,[dashboard_package.v1],1723,1723,30,[],True
6,trustworthiness_summary,dashboard_package.v1,[dashboard_package.v1],284,284,30,[],True
7,compute_summary,dashboard_package.v1,[dashboard_package.v1],35,35,34,[],True
8,research_question_coverage,dashboard_package.v1,[dashboard_package.v1],4,4,14,[],True
9,case_index,dashboard_case_index.v1,[dashboard_case_index.v1],1785,1785,43,[],True
10,painting_index,dashboard_painting_index.v1,[dashboard_painting_index.v1],50,50,27,[],True
11,visual_asset_index,dashboard_package.v1,[dashboard_package.v1],23964,23964,28,[],True
12,report_index,dashboard_package.v1,[dashboard_package.v1],104,104,24,[],True

,asset_key,contract_key,expected_schema,observed_schema,path_matches,passed
0,dashboard.table.headline_findings,headline_findings,dashboard_headline_findings.v1,dashboard_headline_findings.v1,True,True
1,dashboard.table.study_design,study_design,dashboard_study_design.v1,dashboard_study_design.v1,True,True
2,dashboard.table.metric_framework,metric_framework,dashboard_metric_framework.v1,dashboard_metric_framework.v1,True,True
3,dashboard.table.performance_summary,performance_summary,dashboard_performance_summary.v1,dashboard_performance_summary.v1,True,True
4,dashboard.table.sensitivity_summary,sensitivity_summary,dashboard_sensitivity_summary.v1,dashboard_sensitivity_summary.v1,True,True
5,dashboard.table.uncertainty_summary,uncertainty_summary,dashboard_uncertainty_summary.v1,dashboard_uncertainty_summary.v1,True,True
6,dashboard.table.trustworthiness_summary,trustworthiness_summary,dashboard_trustworthiness_summary.v1,dashboard_trustworthiness_summary.v1,True,True
7,dashboard.table.compute_summary,compute_summary,dashboard_compute_summary.v1,dashboard_compute_summary.v1,True,True
8,dashboard.table.research_question_coverage,research_question_coverage,dashboard_research_question_coverage.v1,dashboard_research_question_coverage.v1,True,True
9,dashboard.index.case_index,case_index,dashboard_case_index.v1,dashboard_case_index.v1,True,True
10,dashboard.index.painting_index,painting_index,dashboard_painting_index.v1,dashboard_painting_index.v1,True,True
11,dashboard.index.visual_asset_index,visual_asset_index,dashboard_visual_asset_index.v1,dashboard_visual_asset_index.v1,True,True
12,dashboard.index.report_index,report_index,dashboard_report_index.v1,dashboard_report_index.v1,True,True
13,dashboard.index.filter_options,filter_options,dashboard_filter_options.v1,dashboard_filter_options.v1,True,True
14,dashboard.summary,dashboard_summary,dashboard_package.v1,dashboard_package.v1,True,True

Schema validation passed.
Dataframe contracts: 13
Asset contracts: 15
JSON package schemas: {'summary': 'dashboard_package.v1', 'filters': 'dashboard_filter_options.v1', 'run_manifest': 'run_manifest.v1'}

In [9]:
from restoration_eval.dashboard_application import truthy


UPSTREAM_FAILURES = UPSTREAM_CHECKS[
    (~UPSTREAM_CHECKS["passed"].map(truthy))
    & UPSTREAM_CHECKS["severity"].isin(
        ["error", "blocking"]
    )
].copy()

CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

BATCH_2_FINAL_CHECKS = (
    (
        "package_audit",
        "All helper-level package checks passed",
        0,
        int((~PACKAGE_AUDIT["passed"]).sum()),
        bool(PACKAGE_AUDIT["passed"].all()),
    ),
    (
        "dataframe_schema_audit",
        "Every dataframe contract passed",
        0,
        int((~SCHEMA_AUDIT["passed"]).sum()),
        bool(SCHEMA_AUDIT["passed"].all()),
    ),
    (
        "asset_schema_audit",
        "Every asset-manifest contract passed",
        0,
        int((~ASSET_SCHEMA_AUDIT["passed"]).sum()),
        bool(ASSET_SCHEMA_AUDIT["passed"].all()),
    ),
    (
        "upstream_blocking_failures",
        "Notebook 34 has no error or blocking failures",
        0,
        len(UPSTREAM_FAILURES),
        UPSTREAM_FAILURES.empty,
    ),
    (
        "no_canonical_files_written",
        "Batch 2 has not persisted canonical Notebook 35 files",
        [],
        CANONICAL_FILES_AFTER_BATCH,
        not CANONICAL_FILES_AFTER_BATCH,
    ),
)

for check_id, description, expected, observed, passed in (
    BATCH_2_FINAL_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_2_final_gate",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=passed,
        details=(
            ""
            if passed
            else "Notebook 34 package validation did not close cleanly."
        ),
    )

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

BATCH_2_STAGE_SUMMARY = (
    VALIDATION_FRAME[
        VALIDATION_FRAME["validation_stage"].str.startswith(
            "batch_2"
        )
        | VALIDATION_FRAME["validation_stage"].str.startswith(
            "package_"
        )
        | (
            VALIDATION_FRAME["validation_stage"]
            == "upstream_validation"
        )
    ]
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

BATCH_2_STAGE_SUMMARY["failed"] = (
    BATCH_2_STAGE_SUMMARY["checks"]
    - BATCH_2_STAGE_SUMMARY["passed"]
)

POPULATION_COMPARISON = pd.DataFrame(
    [
        {
            "population": key,
            "observed": value,
            "expected": EXPECTED_POPULATION[key],
            "matches": value == EXPECTED_POPULATION[key],
        }
        for key, value in DASHBOARD_SUMMARY[
            "population"
        ].items()
        if key in EXPECTED_POPULATION
    ]
)

display(BATCH_2_STAGE_SUMMARY)
display(POPULATION_COMPARISON)

print("Batch 2 package validation passed.")
print(
    "Batch 2 validation checks:",
    len(
        VALIDATION_FRAME[
            VALIDATION_FRAME[
                "validation_stage"
            ].str.startswith("batch_2")
        ]
    ),
)
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Validated dashboard assets:", len(DASHBOARD_ASSETS))
print(
    "Validated physical package files:",
    len(OBSERVED_PACKAGE_FILES),
)
print("Canonical files persisted by Batch 2: 0")

                  validation_stage  severity  checks  passed  failed
0          batch_2_asset_contracts  blocking      15      15       0
1          batch_2_asset_integrity  blocking      15      15       0
2        batch_2_dataframe_schemas  blocking      13      13       0
3               batch_2_final_gate  blocking       5       5       0
4   batch_2_json_and_run_contracts  blocking       6       6       0
5        batch_2_package_integrity  blocking       7       7       0
6                    package_paths  blocking      18      18       0
7               package_population  blocking      11      11       0
8                     package_rows  blocking      15      15       0
9                   package_schema  blocking      16      16       0
10                   package_scope  blocking       1       1       0
11                  package_status  blocking      14      14       0
12             upstream_validation  blocking       1       1       0

                        population  observed  expected  matches
0                        paintings        50        50     True
1                 registered_cases       525       525     True
2                restoration_cases       410       410     True
3              approved_candidates      1785      1785     True
4   primary_three_model_candidates      1230      1230     True
5      stable_diffusion_candidates       955       955     True
6                  sdxl_candidates        10        10     True
7     canonical_uncertainty_groups       130       130     True
8   damage_size_uncertainty_groups        35        35     True
9                          reports       104       104     True
10                  visual_records     23964     23964     True

Batch 2 package validation passed.
Batch 2 validation checks: 61
Blocking failures: 0
Validated dashboard assets: 15
Validated physical package files: 19
Canonical files persisted by Batch 2: 0

## Batch 3 — Candidate, painting, visual, report, and filter relationships

This batch validates the complete dashboard browsing layer:

- all 1,785 approved candidate records;
- all 410 restoration cases;
- all 50 painting records;
- all 23,964 visual records;
- all 104 report records;
- all primary image, restoration, diagnostic, and report paths;
- candidate-to-case-to-painting-to-model relationships;
- painting-level case and candidate counts;
- model and experiment populations;
- case and painting report relationships;
- every JSON-list field stored in the candidate index;
- every case-level diagnostic path against the complete visual index;
- every approved filter vocabulary.

The visual index also contains 4,320 map records for 480 valid Stable Diffusion prompt-ablation candidates from prompt arms `p01`–`p04`. These are supporting Notebook 16 and 20 visual records, not additions to the 1,785-candidate approved comparison index. Their case, painting, model, source-notebook, and prompt-arm relationships are validated explicitly.

This batch performs read-only path inspection and does not persist canonical Notebook 35 files.

In [10]:
from restoration_eval.dashboard_application import (
    audit_indexed_paths,
    json_list,
)


RELATIONSHIP_CONFIG = load_dashboard_validation_config(
    PROJECT_ROOT
)
RELATIONSHIP_EXPECTATIONS = RELATIONSHIP_CONFIG[
    "relationship_expectations"
]

INDEXED_PATH_AUDIT = audit_indexed_paths(
    BUNDLE,
    include_all_visuals=True,
)

collect_dashboard_checks(INDEXED_PATH_AUDIT)
VALIDATION.raise_for_blocking()

PATH_AUDIT_SUMMARY = (
    INDEXED_PATH_AUDIT[
        [
            "check_id",
            "expected",
            "observed",
            "passed",
            "details",
        ]
    ]
    .sort_values("check_id")
    .reset_index(drop=True)
)

display(PATH_AUDIT_SUMMARY)

print("Indexed-path audit passed.")
print("Path-contract groups:", len(INDEXED_PATH_AUDIT))
print(
    "Path-contract failures:",
    int((~INDEXED_PATH_AUDIT["passed"]).sum()),
)
print(
    "Visual records inspected:",
    len(DASHBOARD_INDEXES["visual_asset_index"]),
)

,check_id,expected,observed,passed,details
0,case_index__clean_path,"{""missing"": 0, ""unsafe"": 0}","{""unique_paths"": 50, ""missing"": 0, ""unsafe"": 0}",True,"{""missing_examples"": [], ""unsafe_examples"": []}"
1,case_index__damaged_path,"{""missing"": 0, ""unsafe"": 0}","{""unique_paths"": 410, ""missing"": 0, ""unsafe"": 0}",True,"{""missing_examples"": [], ""unsafe_examples"": []}"
2,case_index__mask_path,"{""missing"": 0, ""unsafe"": 0}","{""unique_paths"": 410, ""missing"": 0, ""unsafe"": 0}",True,"{""missing_examples"": [], ""unsafe_examples"": []}"
3,case_index__restored_path,"{""missing"": 0, ""unsafe"": 0}","{""unique_paths"": 1785, ""missing"": 0, ""unsafe"": 0}",True,"{""missing_examples"": [], ""unsafe_examples"": []}"
4,painting_index__raw_image_path,"{""missing"": 0, ""unsafe"": 0}","{""unique_paths"": 50, ""missing"": 0, ""unsafe"": 0}",True,"{""missing_examples"": [], ""unsafe_examples"": []}"
5,report_index__report_path,"{""missing"": 0, ""unsafe"": 0}","{""unique_paths"": 104, ""missing"": 0, ""unsafe"": 0}",True,"{""missing_examples"": [], ""unsafe_examples"": []}"
6,visual_asset_index__relative_path,"{""missing"": 0, ""unsafe"": 0}","{""unique_paths"": 14996, ""missing"": 0, ""unsafe""...",True,"{""missing_examples"": [], ""unsafe_examples"": []}"

Indexed-path audit passed.
Path-contract groups: 7
Path-contract failures: 0
Visual records inspected: 23964

In [11]:
CASE_INDEX = DASHBOARD_INDEXES["case_index"].copy()
PAINTING_INDEX = DASHBOARD_INDEXES[
    "painting_index"
].copy()
VISUAL_INDEX = DASHBOARD_INDEXES[
    "visual_asset_index"
].copy()
REPORT_INDEX = DASHBOARD_INDEXES[
    "report_index"
].copy()

CASE_CANDIDATE_IDS = set(
    CASE_INDEX["candidate_id"].astype(str)
)
CASE_IDS = set(CASE_INDEX["case_id"].astype(str))
PAINTING_IDS = set(
    PAINTING_INDEX["painting_id"].astype(str)
)
MODEL_IDS = set(CASE_INDEX["model_id"].astype(str))

MODEL_COUNTS = (
    CASE_INDEX.groupby("model_id")
    .size()
    .rename("candidate_count")
    .reset_index()
)

EXPECTED_MODEL_COUNTS = {
    "lama": 410,
    "opencv_telea": 410,
    "stable_diffusion_inpainting": 955,
    "sdxl_inpainting": 10,
}

OBSERVED_MODEL_COUNTS = dict(
    zip(
        MODEL_COUNTS["model_id"],
        MODEL_COUNTS["candidate_count"].astype(int),
    )
)

PAINTING_ROLLUP = (
    CASE_INDEX.groupby("painting_id")
    .agg(
        observed_case_count=("case_id", "nunique"),
        observed_candidate_count=("candidate_id", "size"),
        observed_model_count=("model_id", "nunique"),
    )
    .reset_index()
    .merge(
        PAINTING_INDEX[
            [
                "painting_id",
                "case_count",
                "candidate_count",
                "model_count",
            ]
        ],
        on="painting_id",
        how="outer",
        validate="one_to_one",
    )
)

for column in (
    "case_count",
    "candidate_count",
    "model_count",
):
    PAINTING_ROLLUP[column] = pd.to_numeric(
        PAINTING_ROLLUP[column],
        errors="coerce",
    )

PAINTING_ROLLUP["case_count_matches"] = (
    PAINTING_ROLLUP["observed_case_count"]
    == PAINTING_ROLLUP["case_count"]
)
PAINTING_ROLLUP["candidate_count_matches"] = (
    PAINTING_ROLLUP["observed_candidate_count"]
    == PAINTING_ROLLUP["candidate_count"]
)
PAINTING_ROLLUP["model_count_matches"] = (
    PAINTING_ROLLUP["observed_model_count"]
    == PAINTING_ROLLUP["model_count"]
)
PAINTING_ROLLUP["passed"] = PAINTING_ROLLUP[
    [
        "case_count_matches",
        "candidate_count_matches",
        "model_count_matches",
    ]
].all(axis=1)

CASE_REPORTS = REPORT_INDEX[
    REPORT_INDEX["report_family"] == "case"
].copy()
PAINTING_REPORTS = REPORT_INDEX[
    REPORT_INDEX["report_family"] == "painting"
].copy()
MODEL_REPORTS = REPORT_INDEX[
    REPORT_INDEX["report_family"] == "model"
].copy()

PRIMARY_PATH_COLUMNS = [
    "clean_path",
    "damaged_path",
    "mask_path",
    "restored_path",
]

BLANK_PRIMARY_PATHS = {
    column: int(
        CASE_INDEX[column]
        .fillna("")
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )
    for column in PRIMARY_PATH_COLUMNS
}

RELATIONSHIP_CHECKS = (
    (
        "candidate_index_rows",
        "The approved candidate index contains 1,785 rows",
        1785,
        len(CASE_INDEX),
        len(CASE_INDEX) == 1785,
    ),
    (
        "candidate_ids_unique",
        "Every approved candidate ID is unique",
        len(CASE_INDEX),
        CASE_INDEX["candidate_id"].nunique(),
        (
            CASE_INDEX["candidate_id"].nunique()
            == len(CASE_INDEX)
        ),
    ),
    (
        "case_index_ids_unique",
        "Every dashboard case-index row ID is unique",
        len(CASE_INDEX),
        CASE_INDEX["case_index_id"].nunique(),
        (
            CASE_INDEX["case_index_id"].nunique()
            == len(CASE_INDEX)
        ),
    ),
    (
        "restoration_case_population",
        "The candidate index covers all 410 restoration cases",
        410,
        CASE_INDEX["case_id"].nunique(),
        CASE_INDEX["case_id"].nunique() == 410,
    ),
    (
        "painting_population",
        "The candidate index references all 50 paintings",
        50,
        CASE_INDEX["painting_id"].nunique(),
        CASE_INDEX["painting_id"].nunique() == 50,
    ),
    (
        "model_candidate_counts",
        "Candidate counts match the four-model contract",
        EXPECTED_MODEL_COUNTS,
        OBSERVED_MODEL_COUNTS,
        OBSERVED_MODEL_COUNTS == EXPECTED_MODEL_COUNTS,
    ),
    (
        "primary_three_model_population",
        "The primary three-model population contains 1,230 candidates",
        1230,
        int(
            (
                CASE_INDEX["scope_status"]
                == "supported_primary_scope"
            ).sum()
        ),
        (
            int(
                (
                    CASE_INDEX["scope_status"]
                    == "supported_primary_scope"
                ).sum()
            )
            == 1230
        ),
    ),
    (
        "painting_rollups",
        "Painting-level case, candidate, and model counts agree",
        0,
        int((~PAINTING_ROLLUP["passed"]).sum()),
        PAINTING_ROLLUP["passed"].all(),
    ),
    (
        "primary_paths_populated",
        "Every approved candidate has four primary image paths",
        {
            column: 0
            for column in PRIMARY_PATH_COLUMNS
        },
        BLANK_PRIMARY_PATHS,
        all(
            count == 0
            for count in BLANK_PRIMARY_PATHS.values()
        ),
    ),
    (
        "case_report_population",
        "The report index contains 30 detailed case reports",
        30,
        len(CASE_REPORTS),
        len(CASE_REPORTS) == 30,
    ),
    (
        "case_report_relationships",
        "Every case report references an approved restoration case",
        [],
        sorted(
            set(
                CASE_REPORTS["case_id"]
                .dropna()
                .astype(str)
            )
            - CASE_IDS
        ),
        set(
            CASE_REPORTS["case_id"]
            .dropna()
            .astype(str)
        ).issubset(CASE_IDS),
    ),
    (
        "painting_report_population",
        "The report index contains one report for every painting",
        PAINTING_IDS,
        set(
            PAINTING_REPORTS["painting_id"]
            .dropna()
            .astype(str)
        ),
        (
            set(
                PAINTING_REPORTS["painting_id"]
                .dropna()
                .astype(str)
            )
            == PAINTING_IDS
        ),
    ),
    (
        "model_report_relationships",
        "Every model-scoped report references an approved model",
        [],
        sorted(
            set(
                MODEL_REPORTS["model_id"]
                .dropna()
                .astype(str)
            )
            - MODEL_IDS
        ),
        set(
            MODEL_REPORTS["model_id"]
            .dropna()
            .astype(str)
        ).issubset(MODEL_IDS),
    ),
    (
        "report_ids_unique",
        "Every report-index ID is unique",
        len(REPORT_INDEX),
        REPORT_INDEX["dashboard_report_id"].nunique(),
        (
            REPORT_INDEX["dashboard_report_id"].nunique()
            == len(REPORT_INDEX)
        ),
    ),
    (
        "report_paths_unique",
        "Every indexed report path is unique",
        len(REPORT_INDEX),
        REPORT_INDEX["report_path"].nunique(),
        (
            REPORT_INDEX["report_path"].nunique()
            == len(REPORT_INDEX)
        ),
    ),
    (
        "reports_self_contained",
        "All indexed reports are self-contained",
        len(REPORT_INDEX),
        int(REPORT_INDEX["self_contained"].map(truthy).sum()),
        REPORT_INDEX["self_contained"].map(truthy).all(),
    ),
)

for check_id, description, expected, observed, passed in (
    RELATIONSHIP_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_3_core_relationships",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else "A dashboard index relationship is incomplete."
        ),
    )

VALIDATION.raise_for_blocking()

display(MODEL_COUNTS)
display(PAINTING_ROLLUP)

print("Candidate, painting, and report relationships passed.")
print("Approved candidates:", len(CASE_INDEX))
print("Restoration cases:", CASE_INDEX["case_id"].nunique())
print("Paintings:", len(PAINTING_INDEX))
print("Reports:", len(REPORT_INDEX))

                      model_id  candidate_count
0                         lama              410
1                 opencv_telea              410
2              sdxl_inpainting               10
3  stable_diffusion_inpainting              955

,painting_id,observed_case_count,observed_candidate_count,observed_model_count,case_count,candidate_count,model_count,case_count_matches,candidate_count_matches,model_count_matches,passed
0,p001,37,141,4,37,141,4,True,True,True,True
1,p002,5,31,3,5,31,3,True,True,True,True
2,p003,5,22,3,5,22,3,True,True,True,True
3,p004,5,22,3,5,22,3,True,True,True,True
4,p005,5,22,3,5,22,3,True,True,True,True
5,p006,5,22,3,5,22,3,True,True,True,True
6,p007,5,31,3,5,31,3,True,True,True,True
7,p008,5,22,3,5,22,3,True,True,True,True
8,p009,5,22,3,5,22,3,True,True,True,True
9,p010,5,22,3,5,22,3,True,True,True,True
10,p011,5,31,3,5,31,3,True,True,True,True
11,p012,5,22,3,5,22,3,True,True,True,True
12,p013,5,22,3,5,22,3,True,True,True,True
13,p014,5,22,3,5,22,3,True,True,True,True
14,p015,5,22,3,5,22,3,True,True,True,True
15,p016,5,22,3,5,22,3,True,True,True,True
16,p017,5,22,3,5,22,3,True,True,True,True
17,p018,37,141,4,37,141,4,True,True,True,True
18,p019,5,31,3,5,31,3,True,True,True,True
19,p020,5,22,3,5,22,3,True,True,True,True
20,p021,5,22,3,5,22,3,True,True,True,True
21,p022,5,31,3,5,31,3,True,True,True,True
22,p023,5,22,3,5,22,3,True,True,True,True
23,p024,5,22,3,5,22,3,True,True,True,True
24,p025,5,22,3,5,22,3,True,True,True,True
25,p026,37,141,4,37,141,4,True,True,True,True
26,p027,5,31,3,5,31,3,True,True,True,True
27,p028,5,22,3,5,22,3,True,True,True,True
28,p029,5,22,3,5,22,3,True,True,True,True
29,p030,5,22,3,5,22,3,True,True,True,True
30,p031,5,31,3,5,31,3,True,True,True,True
31,p032,5,22,3,5,22,3,True,True,True,True
32,p033,5,22,3,5,22,3,True,True,True,True
33,p034,5,22,3,5,22,3,True,True,True,True
34,p035,5,22,3,5,22,3,True,True,True,True
35,p036,5,22,3,5,22,3,True,True,True,True
36,p037,5,22,3,5,22,3,True,True,True,True
37,p038,5,22,3,5,22,3,True,True,True,True
38,p039,37,141,4,37,141,4,True,True,True,True
39,p040,5,31,3,5,31,3,True,True,True,True
40,p041,5,22,3,5,22,3,True,True,True,True
41,p042,5,31,3,5,31,3,True,True,True,True
42,p043,37,141,4,37,141,4,True,True,True,True
43,p044,5,31,3,5,31,3,True,True,True,True
44,p045,5,22,3,5,22,3,True,True,True,True
45,p046,5,22,3,5,22,3,True,True,True,True
46,p047,5,22,3,5,22,3,True,True,True,True
47,p048,5,22,3,5,22,3,True,True,True,True
48,p049,5,22,3,5,22,3,True,True,True,True
49,p050,5,22,3,5,22,3,True,True,True,True

Candidate, painting, and report relationships passed.
Approved candidates: 1785
Restoration cases: 410
Paintings: 50
Reports: 104

In [12]:
NONBLANK_VISUAL_CANDIDATE_IDS = set(
    VISUAL_INDEX["candidate_id"]
    .dropna()
    .astype(str)
    .str.strip()
)
NONBLANK_VISUAL_CANDIDATE_IDS.discard("")

SUPPORTING_VISUAL_CANDIDATE_IDS = (
    NONBLANK_VISUAL_CANDIDATE_IDS
    - CASE_CANDIDATE_IDS
)

SUPPORTING_VISUALS = VISUAL_INDEX[
    VISUAL_INDEX["candidate_id"]
    .fillna("")
    .astype(str)
    .isin(SUPPORTING_VISUAL_CANDIDATE_IDS)
].copy()

SUPPORTING_PROMPT_ARMS = {
    candidate_id.split("__")[1]
    for candidate_id in SUPPORTING_VISUAL_CANDIDATE_IDS
    if len(candidate_id.split("__")) > 1
}

SUPPORTING_MODEL_IDS = set(
    SUPPORTING_VISUALS["model_id"]
    .dropna()
    .astype(str)
)
SUPPORTING_SOURCE_NOTEBOOK_IDS = set(
    SUPPORTING_VISUALS["source_notebook_id"]
    .dropna()
    .astype(str)
)

EXPECTED_SUPPORTING_MODELS = set(
    RELATIONSHIP_EXPECTATIONS[
        "supporting_visual_model_ids"
    ]
)
EXPECTED_SUPPORTING_NOTEBOOKS = set(
    RELATIONSHIP_EXPECTATIONS[
        "supporting_visual_source_notebook_ids"
    ]
)
EXPECTED_SUPPORTING_PROMPTS = set(
    RELATIONSHIP_EXPECTATIONS[
        "supporting_visual_prompt_arms"
    ]
)

UNRESOLVED_VISUAL_CANDIDATE_IDS = (
    NONBLANK_VISUAL_CANDIDATE_IDS
    - CASE_CANDIDATE_IDS
    - SUPPORTING_VISUAL_CANDIDATE_IDS
)

VISUAL_RELATIONSHIP_CHECKS = (
    (
        "visual_index_rows",
        "The visual index contains all 23,964 records",
        23964,
        len(VISUAL_INDEX),
        len(VISUAL_INDEX) == 23964,
    ),
    (
        "visual_ids_unique",
        "Every visual-asset ID is unique",
        len(VISUAL_INDEX),
        VISUAL_INDEX["visual_asset_id"].nunique(),
        (
            VISUAL_INDEX["visual_asset_id"].nunique()
            == len(VISUAL_INDEX)
        ),
    ),
    (
        "visual_case_relationships",
        "Every case-scoped visual references a restoration case",
        [],
        sorted(
            set(
                VISUAL_INDEX["case_id"]
                .dropna()
                .astype(str)
            )
            - {""}
            - CASE_IDS
        ),
        (
            set(
                VISUAL_INDEX["case_id"]
                .dropna()
                .astype(str)
            )
            - {""}
        ).issubset(CASE_IDS),
    ),
    (
        "visual_painting_relationships",
        "Every painting-scoped visual references a controlled painting",
        [],
        sorted(
            set(
                VISUAL_INDEX["painting_id"]
                .dropna()
                .astype(str)
            )
            - {""}
            - PAINTING_IDS
        ),
        (
            set(
                VISUAL_INDEX["painting_id"]
                .dropna()
                .astype(str)
            )
            - {""}
        ).issubset(PAINTING_IDS),
    ),
    (
        "visual_model_relationships",
        "Every model-scoped visual references an approved model",
        [],
        sorted(
            set(
                VISUAL_INDEX["model_id"]
                .dropna()
                .astype(str)
            )
            - {""}
            - MODEL_IDS
        ),
        (
            set(
                VISUAL_INDEX["model_id"]
                .dropna()
                .astype(str)
            )
            - {""}
        ).issubset(MODEL_IDS),
    ),
    (
        "supporting_visual_candidate_count",
        "Exactly 480 supporting prompt-ablation candidates are retained",
        int(
            RELATIONSHIP_EXPECTATIONS[
                "supporting_visual_candidate_ids"
            ]
        ),
        len(SUPPORTING_VISUAL_CANDIDATE_IDS),
        (
            len(SUPPORTING_VISUAL_CANDIDATE_IDS)
            == int(
                RELATIONSHIP_EXPECTATIONS[
                    "supporting_visual_candidate_ids"
                ]
            )
        ),
    ),
    (
        "supporting_visual_record_count",
        "Exactly 4,320 supporting visual records are retained",
        int(
            RELATIONSHIP_EXPECTATIONS[
                "supporting_visual_records"
            ]
        ),
        len(SUPPORTING_VISUALS),
        (
            len(SUPPORTING_VISUALS)
            == int(
                RELATIONSHIP_EXPECTATIONS[
                    "supporting_visual_records"
                ]
            )
        ),
    ),
    (
        "supporting_visual_models",
        "Supporting visual candidates belong only to Stable Diffusion",
        EXPECTED_SUPPORTING_MODELS,
        SUPPORTING_MODEL_IDS,
        SUPPORTING_MODEL_IDS == EXPECTED_SUPPORTING_MODELS,
    ),
    (
        "supporting_visual_sources",
        "Supporting visual records come only from Notebooks 16 and 20",
        EXPECTED_SUPPORTING_NOTEBOOKS,
        SUPPORTING_SOURCE_NOTEBOOK_IDS,
        (
            SUPPORTING_SOURCE_NOTEBOOK_IDS
            == EXPECTED_SUPPORTING_NOTEBOOKS
        ),
    ),
    (
        "supporting_visual_prompt_arms",
        "Supporting visual candidates cover prompt arms p01 through p04",
        EXPECTED_SUPPORTING_PROMPTS,
        SUPPORTING_PROMPT_ARMS,
        SUPPORTING_PROMPT_ARMS == EXPECTED_SUPPORTING_PROMPTS,
    ),
    (
        "supporting_visual_cases",
        "Every supporting visual candidate references a restoration case",
        [],
        sorted(
            set(
                SUPPORTING_VISUALS["case_id"]
                .dropna()
                .astype(str)
            )
            - CASE_IDS
        ),
        set(
            SUPPORTING_VISUALS["case_id"]
            .dropna()
            .astype(str)
        ).issubset(CASE_IDS),
    ),
    (
        "supporting_visual_paintings",
        "Every supporting visual candidate references a controlled painting",
        [],
        sorted(
            set(
                SUPPORTING_VISUALS["painting_id"]
                .dropna()
                .astype(str)
            )
            - PAINTING_IDS
        ),
        set(
            SUPPORTING_VISUALS["painting_id"]
            .dropna()
            .astype(str)
        ).issubset(PAINTING_IDS),
    ),
    (
        "all_visual_candidates_classified",
        "Every nonblank visual candidate is approved or documented supporting evidence",
        [],
        sorted(UNRESOLVED_VISUAL_CANDIDATE_IDS),
        not UNRESOLVED_VISUAL_CANDIDATE_IDS,
    ),
    (
        "visual_applicability",
        "Every visual record is marked applicable",
        {"applicable"},
        set(
            VISUAL_INDEX["applicability_status"]
            .dropna()
            .astype(str)
        ),
        (
            set(
                VISUAL_INDEX["applicability_status"]
                .dropna()
                .astype(str)
            )
            == {"applicable"}
        ),
    ),
)

for check_id, description, expected, observed, passed in (
    VISUAL_RELATIONSHIP_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_3_visual_relationships",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else RELATIONSHIP_EXPECTATIONS["interpretation"]
        ),
    )

VALIDATION.raise_for_blocking()

SUPPORTING_VISUAL_SUMMARY = (
    SUPPORTING_VISUALS.groupby(
        [
            "source_notebook_id",
            "model_id",
            "asset_type",
            "map_type",
        ],
        dropna=False,
    )
    .agg(
        visual_records=("visual_asset_id", "size"),
        candidate_ids=("candidate_id", "nunique"),
        case_ids=("case_id", "nunique"),
        painting_ids=("painting_id", "nunique"),
    )
    .reset_index()
    .sort_values(
        [
            "source_notebook_id",
            "asset_type",
            "map_type",
        ]
    )
)

display(SUPPORTING_VISUAL_SUMMARY)

print("Visual relationships passed.")
print("Visual records:", len(VISUAL_INDEX))
print(
    "Approved visual candidate IDs:",
    len(
        NONBLANK_VISUAL_CANDIDATE_IDS
        & CASE_CANDIDATE_IDS
    ),
)
print(
    "Supporting prompt-ablation candidate IDs:",
    len(SUPPORTING_VISUAL_CANDIDATE_IDS),
)
print(
    "Supporting prompt-ablation visual records:",
    len(SUPPORTING_VISUALS),
)

,source_notebook_id,model_id,asset_type,map_type,visual_records,candidate_ids,case_ids,painting_ids
0,16,stable_diffusion_inpainting,candidate_map,damaged_absolute_error,480,480,120,22
1,16,stable_diffusion_inpainting,candidate_map,masked_signed_improvement,480,480,120,22
2,16,stable_diffusion_inpainting,candidate_map,restored_absolute_error,480,480,120,22
3,16,stable_diffusion_inpainting,candidate_map,signed_improvement,480,480,120,22
4,16,stable_diffusion_inpainting,candidate_map,spatial_overlay,480,480,120,22
5,20,stable_diffusion_inpainting,numeric_map_bundle,local_semantic_bundle,1920,480,120,22

Visual relationships passed.
Visual records: 23964
Approved visual candidate IDs: 1680
Supporting prompt-ablation candidate IDs: 480
Supporting prompt-ablation visual records: 4320

In [13]:
CASE_JSON_COLUMNS = [
    column
    for column in CASE_INDEX.columns
    if column.endswith("_json")
]

JSON_AUDIT_RECORDS = []
CASE_DIAGNOSTIC_PATHS = set()

DIAGNOSTIC_JSON_COLUMNS = {
    "difference_paths_json",
    "uncertainty_paths_json",
    "seam_paths_json",
    "colour_paths_json",
    "texture_paths_json",
    "semantic_paths_json",
    "mask_boundary_paths_json",
}

for column in CASE_JSON_COLUMNS:
    invalid_rows = []
    parsed_item_count = 0
    unique_items = set()

    for row_index, value in CASE_INDEX[column].items():
        if pd.isna(value) or not str(value).strip():
            parsed = []
        else:
            try:
                parsed = json.loads(str(value))
            except json.JSONDecodeError:
                parsed = None

        if not isinstance(parsed, list):
            invalid_rows.append(int(row_index))
            continue

        parsed_item_count += len(parsed)
        unique_items.update(str(item) for item in parsed)

        if column in DIAGNOSTIC_JSON_COLUMNS:
            CASE_DIAGNOSTIC_PATHS.update(
                str(item)
                for item in parsed
                if str(item).strip()
            )

    JSON_AUDIT_RECORDS.append(
        {
            "column": column,
            "rows": len(CASE_INDEX),
            "invalid_rows": len(invalid_rows),
            "parsed_items": parsed_item_count,
            "unique_items": len(unique_items),
            "passed": not invalid_rows,
        }
    )

    VALIDATION.add(
        validation_stage="batch_3_json_fields",
        check_id=f"json_list__{column}",
        check_description=(
            f"Candidate index field contains valid JSON lists: {column}"
        ),
        severity="blocking",
        expected=0,
        observed=len(invalid_rows),
        passed=not invalid_rows,
        details={
            "invalid_row_examples": invalid_rows[:10],
            "parsed_items": parsed_item_count,
        },
    )

JSON_FIELD_AUDIT = pd.DataFrame(JSON_AUDIT_RECORDS)

VISUAL_INDEX_PATHS = set(
    VISUAL_INDEX["relative_path"]
    .dropna()
    .astype(str)
    .str.strip()
)
VISUAL_INDEX_PATHS.discard("")

UNINDEXED_CASE_DIAGNOSTIC_PATHS = (
    CASE_DIAGNOSTIC_PATHS
    - VISUAL_INDEX_PATHS
)

VALIDATION.add(
    validation_stage="batch_3_json_fields",
    check_id="diagnostic_paths_in_visual_index",
    check_description=(
        "Every candidate diagnostic path is present in the visual index"
    ),
    severity="blocking",
    expected=[],
    observed=sorted(
        UNINDEXED_CASE_DIAGNOSTIC_PATHS
    )[:20],
    passed=not UNINDEXED_CASE_DIAGNOSTIC_PATHS,
    details={
        "candidate_diagnostic_paths": len(
            CASE_DIAGNOSTIC_PATHS
        ),
        "visual_index_paths": len(VISUAL_INDEX_PATHS),
        "unindexed_count": len(
            UNINDEXED_CASE_DIAGNOSTIC_PATHS
        ),
    },
)

FILTER_MODEL_IDS = {
    str(item["model_id"])
    for item in FILTER_OPTIONS["models"]
}
FILTER_FAILURE_CATEGORY_IDS = {
    str(item["category_id"])
    for item in FILTER_OPTIONS["failure_categories"]
}

CASE_VOCABULARIES = {
    "painting_ids": (
        set(PAINTING_INDEX["painting_id"].astype(str)),
        set(str(item) for item in FILTER_OPTIONS["painting_ids"]),
    ),
    "models": (
        set(CASE_INDEX["model_id"].astype(str)),
        FILTER_MODEL_IDS,
    ),
    "experiment_ids": (
        set(CASE_INDEX["experiment_id"].astype(str)),
        set(str(item) for item in FILTER_OPTIONS["experiment_ids"]),
    ),
    "categories": (
        set(PAINTING_INDEX["category"].astype(str)),
        set(str(item) for item in FILTER_OPTIONS["categories"]),
    ),
    "styles_or_periods": (
        set(
            PAINTING_INDEX["style_or_period"]
            .dropna()
            .astype(str)
        )
        - {""},
        set(
            str(item)
            for item in FILTER_OPTIONS["styles_or_periods"]
        ),
    ),
    "degradation_families": (
        set(CASE_INDEX["degradation_family"].astype(str)),
        set(
            str(item)
            for item in FILTER_OPTIONS[
                "degradation_families"
            ]
        ),
    ),
    "severities": (
        set(CASE_INDEX["severity"].astype(str)),
        set(str(item) for item in FILTER_OPTIONS["severities"]),
    ),
    "recommendation_categories": (
        set(CASE_INDEX["recommendation_category"].astype(str)),
        set(
            str(item)
            for item in FILTER_OPTIONS[
                "recommendation_categories"
            ]
        ),
    ),
    "uncertainty_applicability": (
        set(CASE_INDEX["uncertainty_applicability"].astype(str)),
        set(
            str(item)
            for item in FILTER_OPTIONS[
                "uncertainty_applicability"
            ]
        ),
    ),
}

FILTER_AUDIT_RECORDS = []

for vocabulary, (
    observed_values,
    configured_values,
) in CASE_VOCABULARIES.items():
    matches = observed_values == configured_values

    FILTER_AUDIT_RECORDS.append(
        {
            "vocabulary": vocabulary,
            "relationship": "exact",
            "observed_count": len(observed_values),
            "configured_count": len(configured_values),
            "missing_from_filters": sorted(
                observed_values - configured_values
            ),
            "unused_filter_values": sorted(
                configured_values - observed_values
            ),
            "passed": matches,
        }
    )

    VALIDATION.add(
        validation_stage="batch_3_filter_vocabularies",
        check_id=f"filter__{vocabulary}",
        check_description=(
            f"Filter vocabulary exactly matches indexed evidence: "
            f"{vocabulary}"
        ),
        severity="blocking",
        expected=sorted(configured_values),
        observed=sorted(observed_values),
        passed=matches,
        details="Exact evidence-to-filter vocabulary comparison.",
    )

METRIC_FRAME_NAMES = (
    "metric_framework",
    "performance_summary",
    "sensitivity_summary",
    "uncertainty_summary",
)

OBSERVED_METRIC_FAMILIES = set()
OBSERVED_REGION_IDS = set()

for frame_name in METRIC_FRAME_NAMES:
    frame = DASHBOARD_TABLES[frame_name]

    OBSERVED_METRIC_FAMILIES.update(
        frame["metric_family"]
        .dropna()
        .astype(str)
        .str.strip()
    )
    OBSERVED_REGION_IDS.update(
        frame["region_id"]
        .dropna()
        .astype(str)
        .str.strip()
    )

OBSERVED_METRIC_FAMILIES.discard("")
OBSERVED_REGION_IDS.discard("")

CURATED_METRIC_FAMILIES = set(
    str(item)
    for item in FILTER_OPTIONS["metric_families"]
)
CURATED_REGION_IDS = set(
    str(item)
    for item in FILTER_OPTIONS["region_ids"]
)

TRUSTWORTHINESS_FRAME = DASHBOARD_TABLES[
    "trustworthiness_summary"
]
OBSERVED_FAILURE_CATEGORY_IDS = (
    set(
        TRUSTWORTHINESS_FRAME["failure_category_id"]
        .dropna()
        .astype(str)
        .str.strip()
    )
    - {""}
)

CURATED_FILTER_CHECKS = (
    (
        "curated_metric_families",
        "Every curated metric-family filter is backed by evidence",
        [],
        sorted(
            CURATED_METRIC_FAMILIES
            - OBSERVED_METRIC_FAMILIES
        ),
        CURATED_METRIC_FAMILIES.issubset(
            OBSERVED_METRIC_FAMILIES
        ),
    ),
    (
        "curated_regions",
        "Every curated region filter is backed by evidence",
        [],
        sorted(
            CURATED_REGION_IDS
            - OBSERVED_REGION_IDS
        ),
        CURATED_REGION_IDS.issubset(
            OBSERVED_REGION_IDS
        ),
    ),
    (
        "failure_categories",
        "Failure-category filters exactly match validated categories",
        FILTER_FAILURE_CATEGORY_IDS,
        OBSERVED_FAILURE_CATEGORY_IDS,
        (
            FILTER_FAILURE_CATEGORY_IDS
            == OBSERVED_FAILURE_CATEGORY_IDS
        ),
    ),
    (
        "page_ids",
        "Filter options preserve the approved page sequence",
        PAGE_IDS,
        list(FILTER_OPTIONS["page_ids"]),
        list(FILTER_OPTIONS["page_ids"]) == PAGE_IDS,
    ),
)

for check_id, description, expected, observed, passed in (
    CURATED_FILTER_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_3_filter_vocabularies",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else "A curated dashboard filter lacks validated evidence."
        ),
    )

VALIDATION.raise_for_blocking()

FILTER_AUDIT = pd.DataFrame(
    FILTER_AUDIT_RECORDS
)

display(JSON_FIELD_AUDIT)
display(FILTER_AUDIT)

print("JSON and filter contracts passed.")
print("JSON-list columns:", len(CASE_JSON_COLUMNS))
print(
    "Unique candidate diagnostic paths:",
    len(CASE_DIAGNOSTIC_PATHS),
)
print(
    "Unindexed candidate diagnostic paths:",
    len(UNINDEXED_CASE_DIAGNOSTIC_PATHS),
)
print(
    "Exact case/filter vocabularies:",
    len(CASE_VOCABULARIES),
)

,column,rows,invalid_rows,parsed_items,unique_items,passed
0,difference_paths_json,1785,0,7658,7658,True
1,uncertainty_paths_json,1785,0,4360,961,True
2,seam_paths_json,1785,0,1090,1090,True
3,colour_paths_json,1785,0,1090,1090,True
4,texture_paths_json,1785,0,1090,1090,True
5,semantic_paths_json,1785,0,2770,1091,True
6,mask_boundary_paths_json,1785,0,3060,3060,True
7,triggered_flag_ids_json,1785,0,5486,10,True
8,triggered_category_ids_json,1785,0,2266,12,True
9,affected_regions_json,1785,0,5967,8,True
10,recommended_actions_json,1785,0,3987,16,True
11,metric_disagreement_ids_json,1785,0,9798,9798,True
12,report_selection_roles_json,1785,0,76,24,True
13,evidence_source_notebook_ids_json,1785,0,12410,13,True

,vocabulary,relationship,observed_count,configured_count,missing_from_filters,unused_filter_values,passed
0,painting_ids,exact,50,50,[],[],True
1,models,exact,4,4,[],[],True
2,experiment_ids,exact,4,4,[],[],True
3,categories,exact,5,5,[],[],True
4,styles_or_periods,exact,13,13,[],[],True
5,degradation_families,exact,9,9,[],[],True
6,severities,exact,6,6,[],[],True
7,recommendation_categories,exact,4,4,[],[],True
8,uncertainty_applicability,exact,4,4,[],[],True

JSON and filter contracts passed.
JSON-list columns: 14
Unique candidate diagnostic paths: 12480
Unindexed candidate diagnostic paths: 0
Exact case/filter vocabularies: 9

In [14]:
CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

BATCH_3_FINAL_CHECKS = (
    (
        "indexed_path_audit",
        "Every indexed path group passed",
        0,
        int((~INDEXED_PATH_AUDIT["passed"]).sum()),
        INDEXED_PATH_AUDIT["passed"].all(),
    ),
    (
        "painting_rollup_audit",
        "Every painting rollup passed",
        0,
        int((~PAINTING_ROLLUP["passed"]).sum()),
        PAINTING_ROLLUP["passed"].all(),
    ),
    (
        "json_field_audit",
        "Every candidate JSON-list field passed",
        0,
        int((~JSON_FIELD_AUDIT["passed"]).sum()),
        JSON_FIELD_AUDIT["passed"].all(),
    ),
    (
        "filter_audit",
        "Every exact candidate filter vocabulary passed",
        0,
        int((~FILTER_AUDIT["passed"]).sum()),
        FILTER_AUDIT["passed"].all(),
    ),
    (
        "supporting_visual_contract",
        "All supporting prompt-ablation visuals are classified",
        0,
        len(UNRESOLVED_VISUAL_CANDIDATE_IDS),
        not UNRESOLVED_VISUAL_CANDIDATE_IDS,
    ),
    (
        "diagnostic_visual_relationships",
        "Every candidate diagnostic path is indexed",
        0,
        len(UNINDEXED_CASE_DIAGNOSTIC_PATHS),
        not UNINDEXED_CASE_DIAGNOSTIC_PATHS,
    ),
    (
        "no_canonical_files_written",
        "Batch 3 has not persisted canonical Notebook 35 files",
        [],
        CANONICAL_FILES_AFTER_BATCH,
        not CANONICAL_FILES_AFTER_BATCH,
    ),
)

for check_id, description, expected, observed, passed in (
    BATCH_3_FINAL_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_3_final_gate",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else "The dashboard relationship layer is incomplete."
        ),
    )

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

BATCH_3_STAGE_SUMMARY = (
    VALIDATION_FRAME[
        VALIDATION_FRAME["validation_stage"].str.startswith(
            "batch_3"
        )
        | (
            VALIDATION_FRAME["validation_stage"]
            == "indexed_paths"
        )
    ]
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

BATCH_3_STAGE_SUMMARY["failed"] = (
    BATCH_3_STAGE_SUMMARY["checks"]
    - BATCH_3_STAGE_SUMMARY["passed"]
)

RELATIONSHIP_SUMMARY = pd.DataFrame(
    [
        {
            "evidence_population": "approved candidates",
            "records": len(CASE_INDEX),
        },
        {
            "evidence_population": "restoration cases",
            "records": CASE_INDEX["case_id"].nunique(),
        },
        {
            "evidence_population": "paintings",
            "records": len(PAINTING_INDEX),
        },
        {
            "evidence_population": "visual records",
            "records": len(VISUAL_INDEX),
        },
        {
            "evidence_population": (
                "supporting prompt-ablation visual records"
            ),
            "records": len(SUPPORTING_VISUALS),
        },
        {
            "evidence_population": "reports",
            "records": len(REPORT_INDEX),
        },
        {
            "evidence_population": (
                "unique candidate diagnostic paths"
            ),
            "records": len(CASE_DIAGNOSTIC_PATHS),
        },
    ]
)

display(BATCH_3_STAGE_SUMMARY)
display(RELATIONSHIP_SUMMARY)

print("Batch 3 relationship validation passed.")
print(
    "Batch 3 checks:",
    len(
        VALIDATION_FRAME[
            VALIDATION_FRAME[
                "validation_stage"
            ].str.startswith("batch_3")
        ]
    ),
)
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Canonical files persisted by Batch 3: 0")

               validation_stage  severity  checks  passed  failed
0    batch_3_core_relationships  blocking      16      16       0
1   batch_3_filter_vocabularies  blocking      13      13       0
2            batch_3_final_gate  blocking       7       7       0
3           batch_3_json_fields  blocking      15      15       0
4  batch_3_visual_relationships  blocking      14      14       0
5                 indexed_paths  blocking       7       7       0

                         evidence_population  records
0                        approved candidates     1785
1                          restoration cases      410
2                                  paintings       50
3                             visual records    23964
4  supporting prompt-ablation visual records     4320
5                                    reports      104
6          unique candidate diagnostic paths    12480

Batch 3 relationship validation passed.
Batch 3 checks: 65
Blocking failures: 0
Canonical files persisted by Batch 3: 0

## Batch 4 — Application boundaries and static validation

This batch inspects the Streamlit source and its read-only support module without launching the application.

It verifies that:

- the application has valid Python syntax;
- the exact eight-page navigation contract is implemented;
- only the fixed Notebook 34 dashboard package is loaded;
- scientific metrics and restoration candidates are not recomputed;
- no model inference, filesystem discovery, network access, or output writing is performed;
- obsolete dashboard paths and unsupported model claims are absent;
- all scientific interpretation limits appear in the application;
- the complete evidence catalogues remain accessible behind representative defaults.

Runtime rendering and page interaction are deferred to Batch 7.

In [15]:
from restoration_eval.dashboard_application import (
    audit_streamlit_source,
)


APP_STATIC_AUDIT = audit_streamlit_source(PROJECT_ROOT)

if APP_STATIC_AUDIT.empty:
    raise RuntimeError(
        "The shared Streamlit static audit returned no checks."
    )

REQUIRED_STATIC_COLUMNS = {
    "validation_stage",
    "check_id",
    "check_description",
    "severity",
    "expected",
    "observed",
    "passed",
    "details",
}

MISSING_STATIC_COLUMNS = sorted(
    REQUIRED_STATIC_COLUMNS
    - set(APP_STATIC_AUDIT.columns)
)

if MISSING_STATIC_COLUMNS:
    raise KeyError(
        "Static-audit output is missing columns: "
        f"{MISSING_STATIC_COLUMNS}"
    )

for record in APP_STATIC_AUDIT.to_dict("records"):
    VALIDATION.add(
        validation_stage=(
            f"batch_4_{record['validation_stage']}"
        ),
        check_id=str(record["check_id"]),
        check_description=str(
            record["check_description"]
        ),
        severity=str(record["severity"]),
        expected=record["expected"],
        observed=record["observed"],
        passed=bool(record["passed"]),
        details=record.get("details", ""),
    )

VALIDATION.raise_for_blocking()

APP_STATIC_STAGE_SUMMARY = (
    APP_STATIC_AUDIT.groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

APP_STATIC_STAGE_SUMMARY["failed"] = (
    APP_STATIC_STAGE_SUMMARY["checks"]
    - APP_STATIC_STAGE_SUMMARY["passed"]
)

display(APP_STATIC_AUDIT)
display(APP_STATIC_STAGE_SUMMARY)

print("Shared application static audit passed.")
print("Static checks:", len(APP_STATIC_AUDIT))
print(
    "Static failures:",
    int((~APP_STATIC_AUDIT["passed"]).sum()),
)

,validation_stage,check_id,check_description,severity,expected,observed,passed,details
0,application_static,python_syntax,Streamlit entrypoint parses as Python,blocking,valid Python syntax,valid,True,
1,application_static,prohibited_fragment__outputs/dashboard,Application excludes obsolete or unsupported s...,blocking,False,False,True,
2,application_static,prohibited_fragment__outputs/metrics,Application excludes obsolete or unsupported s...,blocking,False,False,True,
3,application_static,prohibited_fragment__outputs/reports,Application excludes obsolete or unsupported s...,blocking,False,False,True,
4,application_static,prohibited_fragment__outputs/figures,Application excludes obsolete or unsupported s...,blocking,False,False,True,
5,application_static,prohibited_fragment__combined_uncertainty_index,Application excludes obsolete or unsupported s...,blocking,False,False,True,
6,application_static,prohibited_fragment__300_paintings,Application excludes obsolete or unsupported s...,blocking,False,False,True,
7,application_static,prohibited_fragment__MAT,Application excludes obsolete or unsupported s...,blocking,False,False,True,
8,application_static,prohibited_fragment__PartialConv,Application excludes obsolete or unsupported s...,blocking,False,False,True,
9,application_pages,page__overview,Application implements approved page: Overview,blocking,True,True,True,
10,application_pages,page__study_design,Application implements approved page: Study De...,blocking,True,True,True,
11,application_pages,page__metric_framework,Application implements approved page: Metric F...,blocking,True,True,True,
12,application_pages,page__model_performance,Application implements approved page: Model Pe...,blocking,True,True,True,
13,application_pages,page__robustness_uncertainty,Application implements approved page: Robustne...,blocking,True,True,True,
14,application_pages,page__trustworthiness_xai,Application implements approved page: Trustwor...,blocking,True,True,True,
15,application_pages,page__case_explorer,Application implements approved page: Case Exp...,blocking,True,True,True,
16,application_pages,page__reports_reproducibility,Application implements approved page: Reports ...,blocking,True,True,True,
17,application_boundaries,read_only_application,Application source contains no filesystem or d...,blocking,[],[],True,

         validation_stage  severity  checks  passed  failed
0  application_boundaries  blocking       1       1       0
1       application_pages  blocking       8       8       0
2      application_static  blocking       9       9       0

Shared application static audit passed.
Static checks: 18
Static failures: 0

In [16]:
# Remove only the partial records created by the failed version of this cell.
STALE_STAGE = "batch_4_source_boundaries"

VALIDATION._checks = [
    check
    for check in VALIDATION._checks
    if check.validation_stage != STALE_STAGE
]

VALIDATION._keys = {
    (check.validation_stage, check.check_id)
    for check in VALIDATION._checks
}


HELPER_SOURCE = HELPER_PATH.read_text(
    encoding="utf-8"
)

APP_TREE = ast.parse(
    APP_SOURCE,
    filename=str(APP_PATH),
)

HELPER_TREE = ast.parse(
    HELPER_SOURCE,
    filename=str(HELPER_PATH),
)


def dotted_ast_name(node):
    if isinstance(node, ast.Name):
        return node.id

    if isinstance(node, ast.Attribute):
        prefix = dotted_ast_name(node.value)
        return (
            f"{prefix}.{node.attr}"
            if prefix
            else node.attr
        )

    return ""


def imported_modules(tree):
    modules = []

    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            modules.extend(
                alias.name
                for alias in node.names
            )

        elif isinstance(node, ast.ImportFrom):
            if node.module:
                modules.append(node.module)

    return sorted(set(modules))


APP_IMPORT_MODULES = imported_modules(APP_TREE)
HELPER_IMPORT_MODULES = imported_modules(HELPER_TREE)

APP_CALL_SITES = [
    {
        "call_name": dotted_ast_name(node.func),
        "line": int(node.lineno),
        "node": node,
    }
    for node in ast.walk(APP_TREE)
    if isinstance(node, ast.Call)
]

HELPER_CALL_SITES = [
    {
        "call_name": dotted_ast_name(node.func),
        "line": int(node.lineno),
        "node": node,
    }
    for node in ast.walk(HELPER_TREE)
    if isinstance(node, ast.Call)
]

APP_FUNCTION_NAMES = {
    node.name
    for node in APP_TREE.body
    if isinstance(
        node,
        (ast.FunctionDef, ast.AsyncFunctionDef),
    )
}

EXPECTED_RENDERER_MAP = {
    "Overview": "render_overview",
    "Study Design": "render_study_design",
    "Metric Framework": "render_metric_framework",
    "Model Performance": "render_model_performance",
    "Robustness & Uncertainty": (
        "render_robustness_uncertainty"
    ),
    "Trustworthiness & XAI": (
        "render_trustworthiness_xai"
    ),
    "Case Explorer": "render_case_explorer",
    "Reports & Reproducibility": "render_reports",
}

EXPECTED_RENDERER_FUNCTIONS = set(
    EXPECTED_RENDERER_MAP.values()
)

RENDERER_MAP = {}

for node in APP_TREE.body:
    if not isinstance(node, ast.Assign):
        continue

    is_renderer_assignment = any(
        isinstance(target, ast.Name)
        and target.id == "RENDERERS"
        for target in node.targets
    )

    if (
        is_renderer_assignment
        and isinstance(node.value, ast.Dict)
    ):
        for key_node, value_node in zip(
            node.value.keys,
            node.value.values,
        ):
            if (
                isinstance(key_node, ast.Constant)
                and isinstance(key_node.value, str)
            ):
                RENDERER_MAP[key_node.value] = (
                    dotted_ast_name(value_node)
                )

LOADER_CALLS = [
    item
    for item in APP_CALL_SITES
    if item["call_name"] == "load_dashboard_package"
]

LOADER_ARGUMENTS = [
    (
        ast.unparse(item["node"].args[0])
        if item["node"].args
        else ""
    )
    for item in LOADER_CALLS
]

DIRECT_DATA_READ_TAILS = {
    "open",
    "read_csv",
    "read_json",
    "read_parquet",
    "read_text",
    "read_bytes",
}

DIRECT_APP_DATA_READS = sorted(
    f"{item['call_name']}@{item['line']}"
    for item in APP_CALL_SITES
    if (
        item["call_name"].rsplit(".", 1)[-1]
        in DIRECT_DATA_READ_TAILS
    )
)

FILESYSTEM_DISCOVERY_TAILS = {
    "glob",
    "rglob",
    "iterdir",
    "listdir",
    "scandir",
    "walk",
}

FILESYSTEM_DISCOVERY_CALLS = sorted(
    f"{item['call_name']}@{item['line']}"
    for item in APP_CALL_SITES
    if (
        item["call_name"].rsplit(".", 1)[-1]
        in FILESYSTEM_DISCOVERY_TAILS
    )
)

# Deliberately exclude generic `.replace()` calls:
# they may be harmless string operations. The shared static audit already
# checks unambiguous filesystem/dataframe write methods.
UNAMBIGUOUS_WRITE_TAILS = {
    "to_csv",
    "to_json",
    "to_parquet",
    "write_text",
    "write_bytes",
    "mkdir",
    "makedirs",
    "remove",
    "unlink",
    "rename",
}

HELPER_WRITE_CALLS = sorted(
    f"{item['call_name']}@{item['line']}"
    for item in HELPER_CALL_SITES
    if (
        item["call_name"].rsplit(".", 1)[-1]
        in UNAMBIGUOUS_WRITE_TAILS
    )
)

PROHIBITED_IMPORT_ROOTS = {
    "cv2",
    "diffusers",
    "torch",
    "torchvision",
    "transformers",
    "skimage",
    "scipy",
    "requests",
    "httpx",
    "urllib",
    "socket",
    "subprocess",
}

APP_PROHIBITED_IMPORTS = sorted(
    module
    for module in APP_IMPORT_MODULES
    if (
        module.split(".", 1)[0].lower()
        in PROHIBITED_IMPORT_ROOTS
    )
)

RESTORATION_EVAL_IMPORTS = sorted(
    module
    for module in APP_IMPORT_MODULES
    if module.startswith("restoration_eval")
)

SCIENTIFIC_FUNCTION_PREFIXES = (
    "calculate",
    "compute",
    "generate",
    "inpaint",
    "predict",
    "restore",
    "run_model",
)

SCIENTIFIC_FUNCTION_DEFINITIONS = sorted(
    name
    for name in APP_FUNCTION_NAMES
    if name.lower().startswith(
        SCIENTIFIC_FUNCTION_PREFIXES
    )
)

STATIC_BOUNDARY_CHECKS = (
    (
        "renderer_functions",
        "Every approved page renderer is defined",
        [],
        sorted(
            EXPECTED_RENDERER_FUNCTIONS
            - APP_FUNCTION_NAMES
        ),
        EXPECTED_RENDERER_FUNCTIONS.issubset(
            APP_FUNCTION_NAMES
        ),
    ),
    (
        "renderer_map",
        "The navigation map uses exactly the eight approved renderers",
        EXPECTED_RENDERER_MAP,
        RENDERER_MAP,
        RENDERER_MAP == EXPECTED_RENDERER_MAP,
    ),
    (
        "single_package_loader",
        "The application calls the fixed package loader exactly once",
        1,
        len(LOADER_CALLS),
        len(LOADER_CALLS) == 1,
    ),
    (
        "package_loader_argument",
        "The package loader is anchored to PROJECT_ROOT",
        ["PROJECT_ROOT"],
        LOADER_ARGUMENTS,
        LOADER_ARGUMENTS == ["PROJECT_ROOT"],
    ),
    (
        "no_direct_data_reads",
        "The application delegates data access to the read-only helper",
        [],
        DIRECT_APP_DATA_READS,
        not DIRECT_APP_DATA_READS,
    ),
    (
        "no_filesystem_discovery",
        "The application does not scan arbitrary repository directories",
        [],
        FILESYSTEM_DISCOVERY_CALLS,
        not FILESYSTEM_DISCOVERY_CALLS,
    ),
    (
        "no_scientific_imports",
        "The application imports no inference or metric-computation libraries",
        [],
        APP_PROHIBITED_IMPORTS,
        not APP_PROHIBITED_IMPORTS,
    ),
    (
        "single_project_helper",
        "The application imports only the dashboard application helper",
        ["restoration_eval.dashboard_application"],
        RESTORATION_EVAL_IMPORTS,
        (
            RESTORATION_EVAL_IMPORTS
            == ["restoration_eval.dashboard_application"]
        ),
    ),
    (
        "helper_has_no_streamlit_dependency",
        "The reusable helper remains independent of Streamlit",
        False,
        any(
            module.split(".", 1)[0] == "streamlit"
            for module in HELPER_IMPORT_MODULES
        ),
        not any(
            module.split(".", 1)[0] == "streamlit"
            for module in HELPER_IMPORT_MODULES
        ),
    ),
    (
        "helper_is_read_only",
        "The dashboard helper contains no unambiguous output-writing calls",
        [],
        HELPER_WRITE_CALLS,
        not HELPER_WRITE_CALLS,
    ),
    (
        "no_scientific_functions",
        "The application defines no restoration or metric-computation workflow",
        [],
        SCIENTIFIC_FUNCTION_DEFINITIONS,
        not SCIENTIFIC_FUNCTION_DEFINITIONS,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in STATIC_BOUNDARY_CHECKS:
    VALIDATION.add(
        validation_stage=STALE_STAGE,
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "The application exceeds its approved "
                "presentation-only boundary."
            )
        ),
    )

VALIDATION.raise_for_blocking()

SOURCE_STRUCTURE_VIEW = pd.DataFrame(
    [
        {
            "source": "streamlit_app.py",
            "imports": len(APP_IMPORT_MODULES),
            "functions": len(APP_FUNCTION_NAMES),
            "calls": len(APP_CALL_SITES),
            "renderer_functions": len(
                EXPECTED_RENDERER_FUNCTIONS
                & APP_FUNCTION_NAMES
            ),
            "prohibited_imports": len(
                APP_PROHIBITED_IMPORTS
            ),
            "write_calls": 0,
        },
        {
            "source": (
                "src/restoration_eval/"
                "dashboard_application.py"
            ),
            "imports": len(HELPER_IMPORT_MODULES),
            "functions": len(
                {
                    node.name
                    for node in HELPER_TREE.body
                    if isinstance(
                        node,
                        (
                            ast.FunctionDef,
                            ast.AsyncFunctionDef,
                        ),
                    )
                }
            ),
            "calls": len(HELPER_CALL_SITES),
            "renderer_functions": 0,
            "prohibited_imports": 0,
            "write_calls": len(HELPER_WRITE_CALLS),
        },
    ]
)

RENDERER_AUDIT = pd.DataFrame(
    [
        {
            "page": page,
            "renderer": renderer,
            "implemented": (
                RENDERER_MAP.get(page)
                == renderer
            ),
        }
        for page, renderer
        in EXPECTED_RENDERER_MAP.items()
    ]
)

display(SOURCE_STRUCTURE_VIEW)
display(RENDERER_AUDIT)

print("Application source boundaries passed.")
print("Approved page renderers:", len(RENDERER_MAP))
print("Dashboard-package loader calls:", len(LOADER_CALLS))
print("Direct application data reads:", len(DIRECT_APP_DATA_READS))
print("Filesystem discovery calls:", len(FILESYSTEM_DISCOVERY_CALLS))
print("Prohibited imports:", len(APP_PROHIBITED_IMPORTS))
print("Helper write calls:", len(HELPER_WRITE_CALLS))

,source,imports,functions,calls,renderer_functions,prohibited_imports,write_calls
0,streamlit_app.py,11,31,837,8,0,0
1,src/restoration_eval/dashboard_application.py,11,19,195,0,0,0

                        page                       renderer  implemented
0                   Overview                render_overview         True
1               Study Design            render_study_design         True
2           Metric Framework        render_metric_framework         True
3          Model Performance       render_model_performance         True
4   Robustness & Uncertainty  render_robustness_uncertainty         True
5      Trustworthiness & XAI     render_trustworthiness_xai         True
6              Case Explorer           render_case_explorer         True
7  Reports & Reproducibility                 render_reports         True

Application source boundaries passed.
Approved page renderers: 8
Dashboard-package loader calls: 1
Direct application data reads: 0
Filesystem discovery calls: 0
Prohibited imports: 0
Helper write calls: 0

In [17]:
# Remove partial records left by the failed version of this cell.
STALE_BATCH_4_STAGES = {
    "batch_4_interpretation_boundaries",
    "batch_4_inspection_controls",
}

VALIDATION._checks = [
    check
    for check in VALIDATION._checks
    if check.validation_stage
    not in STALE_BATCH_4_STAGES
]

VALIDATION._keys = {
    (check.validation_stage, check.check_id)
    for check in VALIDATION._checks
}


# Reload the current application source instead of using the
# earlier Batch 1 snapshot.
APP_SOURCE = APP_PATH.read_text(
    encoding="utf-8"
)
APP_SOURCE_CASEFOLD = APP_SOURCE.casefold()

APP_TREE = ast.parse(
    APP_SOURCE,
    filename=str(APP_PATH),
)

APP_CALL_SITES = [
    {
        "call_name": dotted_ast_name(node.func),
        "line": int(node.lineno),
        "node": node,
    }
    for node in ast.walk(APP_TREE)
    if isinstance(node, ast.Call)
]


def source_contains(*fragments):
    return all(
        str(fragment).casefold()
        in APP_SOURCE_CASEFOLD
        for fragment in fragments
    )


SOURCE_CLAIM_CHECKS = (
    (
        "central_thesis_statement",
        "The central trustworthiness statement is visible",
        True,
        source_contains(
            "visual plausibility is",
            (
                "not</em> the same as restoration "
                "trustworthiness"
            ),
        ),
    ),
    (
        "controlled_damage_scope",
        "The controlled synthetic-damage scope is visible",
        True,
        (
            source_contains("controlled synthetic damage")
            or source_contains(
                "controlled synthetic-damage"
            )
        ),
    ),
    (
        "historical_conservation_boundary",
        (
            "Historical correctness and conservation "
            "approval are not claimed"
        ),
        True,
        source_contains(
            "historical correctness",
            "conservation approval",
        ),
    ),
    (
        "no_universal_score_claim",
        (
            "Metric disagreement is not hidden in a "
            "universal score"
        ),
        True,
        source_contains("universal score"),
    ),
    (
        "conditional_model_conclusions",
        (
            "Metric-specific winners are not presented "
            "as universal superiority"
        ),
        True,
        source_contains(
            "conditional result",
            "not universal model superiority",
        ),
    ),
    (
        "sdxl_bounded_scope",
        "SDXL is visibly limited to ten cases",
        True,
        source_contains(
            "sdxl",
            "10 cases only",
        ),
    ),
    (
        "uncertainty_boundary",
        (
            "Calibrated confidence is explicitly "
            "not claimed"
        ),
        True,
        source_contains(
            "calibrated confidence",
            "not claimed",
        ),
    ),
    (
        "computational_flag_boundary",
        (
            "Computational flags are not presented "
            "as expert ground truth"
        ),
        True,
        source_contains(
            "computational flag",
            "neither expert ground truth",
        ),
    ),
    (
        "presentation_only_statement",
        (
            "The application states that it performs "
            "no inference or recomputation"
        ),
        True,
        source_contains(
            "presentation and decision support only",
            "no inference or metric recomputation",
        ),
    ),
    (
        "complete_visual_catalogue",
        (
            "All 23,964 indexed visual records remain "
            "inspectable"
        ),
        True,
        source_contains(
            "complete indexed visual catalogue",
            "23,964 records",
        ),
    ),
    (
        "self_contained_downloads",
        "Self-contained report downloads are exposed",
        True,
        source_contains("download self-contained"),
    ),
)

for (
    check_id,
    description,
    expected,
    passed,
) in SOURCE_CLAIM_CHECKS:
    VALIDATION.add(
        validation_stage=(
            "batch_4_interpretation_boundaries"
        ),
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=bool(passed),
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "A required scientific boundary or "
                "complete-access control is absent "
                "from the current application source."
            )
        ),
    )

APP_CALL_COUNTS = (
    pd.Series(
        [
            item["call_name"]
            for item in APP_CALL_SITES
            if item["call_name"]
        ],
        dtype="string",
    )
    .value_counts()
    .to_dict()
)


def application_call_count(call_name):
    return int(
        APP_CALL_COUNTS.get(call_name, 0)
    )


INTERACTION_REQUIREMENTS = {
    "st.set_page_config": 1,
    "st.radio": 1,
    "st.selectbox": 1,
    "st.plotly_chart": 1,
    "st.image": 1,
    "st.dataframe": 1,
    "st.tabs": 1,
    "st.expander": 1,
    "st.download_button": 3,
}

INTERACTION_AUDIT_RECORDS = []

for call_name, minimum_count in (
    INTERACTION_REQUIREMENTS.items()
):
    observed_count = application_call_count(
        call_name
    )
    passed = observed_count >= minimum_count

    INTERACTION_AUDIT_RECORDS.append(
        {
            "interaction": call_name,
            "minimum_count": minimum_count,
            "observed_count": observed_count,
            "passed": passed,
        }
    )

    VALIDATION.add(
        validation_stage=(
            "batch_4_inspection_controls"
        ),
        check_id=(
            "interaction__"
            + call_name.replace(".", "_")
        ),
        check_description=(
            "The application exposes required "
            f"interaction: {call_name}"
        ),
        severity="blocking",
        expected=f">={minimum_count}",
        observed=observed_count,
        passed=passed,
        details=(
            ""
            if passed
            else (
                "The application lacks a required "
                "visual, filter, navigation, or "
                "download mechanism."
            )
        ),
    )

CONFIGURED_PALETTE = {
    str(value).casefold()
    for value in PRESENTATION["palette"].values()
}

SOURCE_PALETTE = {
    value
    for value in CONFIGURED_PALETTE
    if value in APP_SOURCE_CASEFOLD
}

PALETTE_PASSED = (
    SOURCE_PALETTE == CONFIGURED_PALETTE
)

VALIDATION.add(
    validation_stage="batch_4_inspection_controls",
    check_id="approved_palette",
    check_description=(
        "Every approved museum-interface colour "
        "is used by the application"
    ),
    severity="blocking",
    expected=sorted(CONFIGURED_PALETTE),
    observed=sorted(SOURCE_PALETTE),
    passed=PALETTE_PASSED,
    details={
        "missing_colours": sorted(
            CONFIGURED_PALETTE
            - SOURCE_PALETTE
        )
    },
)

VALIDATION.raise_for_blocking()

SOURCE_CLAIM_AUDIT = pd.DataFrame(
    [
        {
            "boundary": check_id,
            "description": description,
            "present": bool(passed),
        }
        for (
            check_id,
            description,
            _,
            passed,
        ) in SOURCE_CLAIM_CHECKS
    ]
)

INTERACTION_AUDIT = pd.DataFrame(
    INTERACTION_AUDIT_RECORDS
)

display(SOURCE_CLAIM_AUDIT)
display(INTERACTION_AUDIT)

print(
    "Scientific-boundary and inspection-control "
    "audit passed."
)
print(
    "Required boundary statements:",
    len(SOURCE_CLAIM_AUDIT),
)
print(
    "Required interaction types:",
    len(INTERACTION_AUDIT),
)
print(
    "Approved palette colours used:",
    len(SOURCE_PALETTE),
    "of",
    len(CONFIGURED_PALETTE),
)
print(
    "Complete visual catalogue found:",
    source_contains(
        "complete indexed visual catalogue",
        "23,964 records",
    ),
)

,boundary,description,present
0,central_thesis_statement,The central trustworthiness statement is visible,True
1,controlled_damage_scope,The controlled synthetic-damage scope is visible,True
2,historical_conservation_boundary,Historical correctness and conservation approv...,True
3,no_universal_score_claim,Metric disagreement is not hidden in a univers...,True
4,conditional_model_conclusions,Metric-specific winners are not presented as u...,True
5,sdxl_bounded_scope,SDXL is visibly limited to ten cases,True
6,uncertainty_boundary,Calibrated confidence is explicitly not claimed,True
7,computational_flag_boundary,Computational flags are not presented as exper...,True
8,presentation_only_statement,The application states that it performs no inf...,True
9,complete_visual_catalogue,"All 23,964 indexed visual records remain inspe...",True
10,self_contained_downloads,Self-contained report downloads are exposed,True

          interaction  minimum_count  observed_count  passed
0  st.set_page_config              1               1    True
1            st.radio              1               1    True
2        st.selectbox              1              19    True
3     st.plotly_chart              1               3    True
4            st.image              1               2    True
5        st.dataframe              1               9    True
6             st.tabs              1               2    True
7         st.expander              1              11    True
8  st.download_button              3               3    True

Scientific-boundary and inspection-control audit passed.
Required boundary statements: 11
Required interaction types: 9
Approved palette colours used: 9 of 9
Complete visual catalogue found: True

In [18]:
CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

BATCH_4_FINAL_CHECKS = (
    (
        "shared_static_audit",
        "Every shared application audit passed",
        0,
        int((~APP_STATIC_AUDIT["passed"]).sum()),
        bool(APP_STATIC_AUDIT["passed"].all()),
    ),
    (
        "source_boundary_audit",
        "Every source-boundary check passed",
        len(STATIC_BOUNDARY_CHECKS),
        len(STATIC_BOUNDARY_CHECKS),
        True,
    ),
    (
        "interpretation_boundary_audit",
        "Every required interpretation boundary is present",
        len(SOURCE_CLAIM_CHECKS),
        int(SOURCE_CLAIM_AUDIT["present"].sum()),
        bool(SOURCE_CLAIM_AUDIT["present"].all()),
    ),
    (
        "inspection_control_audit",
        "Every required inspection control is implemented",
        len(INTERACTION_AUDIT),
        int(INTERACTION_AUDIT["passed"].sum()),
        bool(INTERACTION_AUDIT["passed"].all()),
    ),
    (
        "approved_palette_audit",
        "The approved visual palette is implemented",
        len(CONFIGURED_PALETTE),
        len(SOURCE_PALETTE),
        SOURCE_PALETTE == CONFIGURED_PALETTE,
    ),
    (
        "no_canonical_files_written",
        "Batch 4 has not persisted canonical Notebook 35 files",
        [],
        CANONICAL_FILES_AFTER_BATCH,
        not CANONICAL_FILES_AFTER_BATCH,
    ),
)

for check_id, description, expected, observed, passed in (
    BATCH_4_FINAL_CHECKS
):
    VALIDATION.add(
        validation_stage="batch_4_final_gate",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "Notebook 35 cannot proceed to visual "
                "traceability until the static boundary passes."
            )
        ),
    )

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

BATCH_4_STAGE_SUMMARY = (
    VALIDATION_FRAME[
        VALIDATION_FRAME[
            "validation_stage"
        ].str.startswith("batch_4")
    ]
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

BATCH_4_STAGE_SUMMARY["failed"] = (
    BATCH_4_STAGE_SUMMARY["checks"]
    - BATCH_4_STAGE_SUMMARY["passed"]
)

display(BATCH_4_STAGE_SUMMARY)

print("Batch 4 application-boundary validation passed.")
print(
    "Batch 4 checks:",
    len(
        VALIDATION_FRAME[
            VALIDATION_FRAME[
                "validation_stage"
            ].str.startswith("batch_4")
        ]
    ),
)
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Canonical files persisted by Batch 4: 0")

                    validation_stage  severity  checks  passed  failed
0     batch_4_application_boundaries  blocking       1       1       0
1          batch_4_application_pages  blocking       8       8       0
2         batch_4_application_static  blocking       9       9       0
3                 batch_4_final_gate  blocking       6       6       0
4        batch_4_inspection_controls  blocking      10      10       0
5  batch_4_interpretation_boundaries  blocking      11      11       0
6          batch_4_source_boundaries  blocking      11      11       0

Batch 4 application-boundary validation passed.
Batch 4 checks: 56
Blocking failures: 0
Canonical files persisted by Batch 4: 0

## Batch 5 — Approved mock and application traceability

This batch connects the approved external UI references to the implemented eight-page application.

The reference images remain outside the repository and are design references only:

- `ui1.jpeg` guides the Overview page and shared application shell;
- `ui2.jpeg` guides Model Performance;
- `ui3.jpeg` guides Case Explorer;
- the remaining five pages extend the same approved visual language.

For every page, the traceability audit covers:

- major content blocks;
- chart role;
- image-panel role;
- conclusion placement;
- scientific limitation;
- filter family;
- drill-down mechanism;
- provenance view;
- validated Notebook 34 evidence sources.

The audit evaluates application structure and evidence coverage. Actual Streamlit rendering is tested later in Batch 7.

In [19]:
# Always inspect the current application source.
APP_SOURCE = APP_PATH.read_text(
    encoding="utf-8"
)
APP_TREE = ast.parse(
    APP_SOURCE,
    filename=str(APP_PATH),
)

APP_FUNCTION_SOURCES = {
    node.name: (
        ast.get_source_segment(APP_SOURCE, node)
        or ""
    )
    for node in APP_TREE.body
    if isinstance(
        node,
        (ast.FunctionDef, ast.AsyncFunctionDef),
    )
}

CONFIGURED_REFERENCE_PATHS = [
    str(value)
    for value in PRESENTATION[
        "approved_reference_images"
    ]
]

EXPECTED_REFERENCE_PATHS = [
    "D:/Downloads/ui1.jpeg",
    "D:/Downloads/ui2.jpeg",
    "D:/Downloads/ui3.jpeg",
]

REFERENCE_PATH_ROWS = []

for value in CONFIGURED_REFERENCE_PATHS:
    path = Path(value)
    resolved = path.resolve()

    REFERENCE_PATH_ROWS.append(
        {
            "reference": path.name,
            "configured_path": value,
            "exists_locally": path.is_file(),
            "inside_repository": (
                resolved.is_relative_to(
                    PROJECT_ROOT.resolve()
                )
            ),
            "design_role": {
                "ui1.jpeg": (
                    "Overview and shared application shell"
                ),
                "ui2.jpeg": "Model Performance",
                "ui3.jpeg": "Case Explorer",
            }.get(path.name, "Unassigned"),
        }
    )

REFERENCE_PATH_AUDIT = pd.DataFrame(
    REFERENCE_PATH_ROWS
)

REFERENCE_FILENAMES = {
    Path(value).name.casefold()
    for value in CONFIGURED_REFERENCE_PATHS
}

REPOSITORY_REFERENCE_COPIES = sorted(
    INVENTORY.loc[
        INVENTORY["relative_path"]
        .astype(str)
        .map(
            lambda value: (
                Path(value).name.casefold()
            )
        )
        .isin(REFERENCE_FILENAMES),
        "relative_path",
    ]
    .astype(str)
    .tolist()
)

ALL_REFERENCES_EXTERNAL = bool(
    (
        ~REFERENCE_PATH_AUDIT[
            "inside_repository"
        ]
    ).all()
)

ALL_REFERENCES_AVAILABLE = bool(
    REFERENCE_PATH_AUDIT[
        "exists_locally"
    ].all()
)

REFERENCE_CHECKS = (
    (
        "approved_reference_set",
        "The three approved mock references are unchanged",
        EXPECTED_REFERENCE_PATHS,
        CONFIGURED_REFERENCE_PATHS,
        (
            CONFIGURED_REFERENCE_PATHS
            == EXPECTED_REFERENCE_PATHS
        ),
        "blocking",
    ),
    (
        "external_read_only_policy",
        "Mock references are explicitly external and read-only",
        True,
        bool(
            PRESENTATION[
                "reference_images_are_external_and_read_only"
            ]
        ),
        bool(
            PRESENTATION[
                "reference_images_are_external_and_read_only"
            ]
        ),
        "blocking",
    ),
    (
        "no_repository_copy_policy",
        "The mock references must not be copied into the repository",
        True,
        bool(
            PRESENTATION[
                "reference_images_must_not_be_copied_to_repository"
            ]
        ),
        bool(
            PRESENTATION[
                "reference_images_must_not_be_copied_to_repository"
            ]
        ),
        "blocking",
    ),
    (
        "references_outside_repository",
        "Every mock reference remains outside the repository",
        True,
        ALL_REFERENCES_EXTERNAL,
        ALL_REFERENCES_EXTERNAL,
        "blocking",
    ),
    (
        "no_reference_copies",
        "No approved mock image is indexed as a repository artifact",
        [],
        REPOSITORY_REFERENCE_COPIES,
        not REPOSITORY_REFERENCE_COPIES,
        "blocking",
    ),
    (
        "local_reference_availability",
        "The external mock images remain locally available for visual review",
        True,
        ALL_REFERENCES_AVAILABLE,
        ALL_REFERENCES_AVAILABLE,
        "warning",
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
    severity,
) in REFERENCE_CHECKS:
    VALIDATION.add(
        validation_stage="batch_5_reference_boundary",
        check_id=check_id,
        check_description=description,
        severity=severity,
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "External reference availability does not "
                "change the scientific dashboard package."
            )
        ),
    )

VALIDATION.raise_for_blocking()

display(REFERENCE_PATH_AUDIT)

print("External mock-reference boundary passed.")
print("Configured references:", len(CONFIGURED_REFERENCE_PATHS))
print(
    "Available locally:",
    int(
        REFERENCE_PATH_AUDIT[
            "exists_locally"
        ].sum()
    ),
)
print("Repository copies:", len(REPOSITORY_REFERENCE_COPIES))

,reference,configured_path,exists_locally,inside_repository,design_role
0,ui1.jpeg,D:/Downloads/ui1.jpeg,True,False,Overview and shared application shell
1,ui2.jpeg,D:/Downloads/ui2.jpeg,True,False,Model Performance
2,ui3.jpeg,D:/Downloads/ui3.jpeg,True,False,Case Explorer

External mock-reference boundary passed.
Configured references: 3
Available locally: 3
Repository copies: 0

In [20]:
# Remove partial validation records left by an earlier execution.
STALE_BATCH_5_STAGES = {
    "batch_5_page_contracts",
    "batch_5_mock_traceability",
}

VALIDATION._checks = [
    check
    for check in VALIDATION._checks
    if check.validation_stage
    not in STALE_BATCH_5_STAGES
]

VALIDATION._keys = {
    (
        check.validation_stage,
        check.check_id,
    )
    for check in VALIDATION._checks
}

AVAILABLE_EVIDENCE_KEYS = {
    *(
        f"table:{key}"
        for key in DASHBOARD_TABLES
    ),
    *(
        f"index:{key}"
        for key in DASHBOARD_INDEXES
    ),
}

REQUIRED_TRACEABILITY_ASPECTS = (
    "major_content_block",
    "chart_role",
    "image_panel_role",
    "conclusion_position",
    "limitation",
    "filter_family",
    "drill_down",
    "provenance_view",
    "evidence_source",
)


def traceability_page(
    *,
    display_name,
    renderer,
    mock_basis,
    evidence_sources,
    requirements,
):
    return {
        "display_name": display_name,
        "renderer": renderer,
        "mock_basis": mock_basis,
        "evidence_sources": evidence_sources,
        "requirements": requirements,
    }


PAGE_TRACEABILITY_SPEC = {
    "overview": traceability_page(
        display_name="Overview",
        renderer="render_overview",
        mock_basis="ui1.jpeg",
        evidence_sources=[
            "table:headline_findings",
            "index:visual_asset_index",
            "index:painting_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Thesis strip, scope cards, "
                    "and supported findings"
                ),
                [
                    "thesis-strip",
                    "Study scope",
                ],
            ),
            "chart_role": (
                (
                    "Validated thesis-level "
                    "benchmark summary"
                ),
                [
                    (
                        "Validated thesis-level "
                        "benchmark summary"
                    ),
                ],
            ),
            "image_panel_role": (
                (
                    "Three controlled-collection "
                    "painting witnesses"
                ),
                [
                    (
                        "Three witnesses from the "
                        "controlled collection"
                    ),
                    "raw_image_path",
                ],
            ),
            "conclusion_position": (
                (
                    "Supported conclusions precede "
                    "the benchmark visual"
                ),
                [
                    "What the evidence supports",
                ],
            ),
            "limitation": (
                (
                    "The interpretation boundary "
                    "closes the page"
                ),
                [
                    "Interpretation boundary",
                ],
            ),
            "filter_family": (
                (
                    "Representative evidence selection "
                    "remains available"
                ),
                [
                    "representative_case",
                ],
            ),
            "drill_down": (
                (
                    "Representative evidence routes "
                    "into case inspection"
                ),
                [
                    "representative_case",
                ],
            ),
            "provenance_view": (
                (
                    "The summary visual is identified "
                    "as validated benchmark evidence"
                ),
                [
                    (
                        "Validated thesis-level "
                        "benchmark summary"
                    ),
                ],
            ),
            "evidence_source": (
                (
                    "Headline findings, paintings, "
                    "and indexed visuals"
                ),
                [
                    "bundle.tables",
                    "bundle.indexes",
                ],
            ),
        },
    ),
    "study_design": traceability_page(
        display_name="Study Design",
        renderer="render_study_design",
        mock_basis=(
            "approved visual-language extension"
        ),
        evidence_sources=[
            "table:study_design",
            "index:painting_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Population cards, design rules, "
                    "and collection composition"
                ),
                [
                    "Design rules",
                    "Collection composition",
                ],
            ),
            "chart_role": (
                (
                    "Experiment scope and collection "
                    "composition visuals"
                ),
                [
                    "summary_figure",
                    "Paintings per visual category",
                ],
            ),
            "image_panel_role": (
                (
                    "Experiment changes are translated "
                    "into registered images"
                ),
                [
                    "render_experiment_walkthrough",
                    "raw_image_path",
                ],
            ),
            "conclusion_position": (
                (
                    "The independent observation unit "
                    "is explicitly explained"
                ),
                [
                    "Independent unit",
                ],
            ),
            "limitation": (
                (
                    "Controlled-collection generality "
                    "is bounded"
                ),
                [
                    (
                        "does not by itself establish "
                        "performance"
                    ),
                ],
            ),
            "filter_family": (
                "Experiment filter",
                [
                    'select_one("Experiment"',
                ],
            ),
            "drill_down": (
                (
                    "Visual-category inspection and "
                    "complete painting metadata"
                ),
                [
                    "Inspect a visual category",
                    (
                        "Complete 50-painting "
                        "collection metadata"
                    ),
                ],
            ),
            "provenance_view": (
                (
                    "Experiment and declared unit "
                    "metadata remain traceable"
                ),
                [
                    "experiment_id",
                    "value_unit",
                ],
            ),
            "evidence_source": (
                (
                    "Study-design declarations and "
                    "the painting index"
                ),
                [
                    "bundle.tables",
                    "bundle.indexes",
                ],
            ),
        },
    ),
    "metric_framework": traceability_page(
        display_name="Metric Framework",
        renderer="render_metric_framework",
        mock_basis=(
            "approved visual-language extension"
        ),
        evidence_sources=[
            "table:metric_framework",
            "index:case_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Metric policy, family definitions, "
                    "and region interpretation"
                ),
                [
                    "Metric policy",
                    (
                        "What this metric family "
                        "measures"
                    ),
                ],
            ),
            "chart_role": (
                (
                    "Approved-region indicators and "
                    "selected diagnostic evidence"
                ),
                [
                    "Approved regions for",
                    (
                        "Image explaining the "
                        "selected region"
                    ),
                ],
            ),
            "image_panel_role": (
                (
                    "Original, repair mask, restoration, "
                    "and selected diagnostic image"
                ),
                [
                    "Original reference",
                    "Repair mask",
                    "render_image_grid",
                ],
            ),
            "conclusion_position": (
                (
                    "The no-single-score conclusion "
                    "follows the visual evidence"
                ),
                [
                    "Central rule",
                ],
            ),
            "limitation": (
                (
                    "Each selected metric family "
                    "states what it cannot establish"
                ),
                [
                    "What it cannot establish",
                ],
            ),
            "filter_family": (
                (
                    "Metric-family, region, model, "
                    "case, and diagnostic selectors"
                ),
                [
                    'select_one("Metric family"',
                    (
                        'select_one("Region to explain '
                        'and visualize"'
                    ),
                    "Image explaining the selected region",
                ],
            ),
            "drill_down": (
                (
                    "All relevant region diagnostics "
                    "and complete policy evidence"
                ),
                [
                    (
                        "Show every relevant diagnostic "
                        "for this region"
                    ),
                    (
                        "Complete metric and region "
                        "policy evidence"
                    ),
                ],
            ),
            "provenance_view": (
                (
                    "Record type and comparison "
                    "direction remain visible"
                ),
                [
                    "record_type",
                    "comparison_direction",
                ],
            ),
            "evidence_source": (
                (
                    "Validated metric policy and "
                    "candidate-level indexed images"
                ),
                [
                    (
                        'bundle.tables['
                        '"metric_framework"]'
                    ),
                    (
                        'bundle.indexes['
                        '"case_index"]'
                    ),
                ],
            ),
        },
    ),
    "model_performance": traceability_page(
        display_name="Model Performance",
        renderer="render_model_performance",
        mock_basis="ui2.jpeg",
        evidence_sources=[
            "table:performance_summary",
            "table:compute_summary",
            "table:headline_findings",
            "table:metric_framework",
            "index:case_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Decision cards, comparison chart, "
                    "metric interpretation, and coverage"
                ),
                [
                    "Decision cue",
                    "How to read this metric",
                ],
            ),
            "chart_role": (
                (
                    "Metric-specific model comparison "
                    "with interval evidence"
                ),
                [
                    "px.bar",
                    "error_x",
                ],
            ),
            "image_panel_role": (
                (
                    "Filterable restoration comparison "
                    "behind the selected metric"
                ),
                [
                    (
                        "Inspect the restorations "
                        "behind the comparison"
                    ),
                    "render_performance_comparison",
                ],
            ),
            "conclusion_position": (
                (
                    "A conditional result accompanies "
                    "the selected metric"
                ),
                [
                    "Result for this slice",
                ],
            ),
            "limitation": (
                (
                    "No metric winner becomes "
                    "universal model superiority"
                ),
                [
                    "not universal model superiority",
                ],
            ),
            "filter_family": (
                (
                    "Scope, condition, metric, model, "
                    "painting, case, and candidate controls"
                ),
                [
                    'select_one("Comparison scope"',
                    'select_one("Metric"',
                    "render_performance_comparison",
                ],
            ),
            "drill_down": (
                (
                    "Runtime and bounded-scaling "
                    "evidence remains inspectable"
                ),
                [
                    (
                        "Observed runtime and bounded "
                        "scaling evidence"
                    ),
                ],
            ),
            "provenance_view": (
                (
                    "Executed and projected runtime "
                    "records retain their basis"
                ),
                [
                    "is_executed",
                    "is_projected",
                    "projection_basis",
                ],
            ),
            "evidence_source": (
                (
                    "Performance, compute, metric-policy, "
                    "and candidate evidence"
                ),
                [
                    "performance_summary",
                    "compute_summary",
                    "metric_framework",
                ],
            ),
        },
    ),
    "robustness_uncertainty": traceability_page(
        display_name="Robustness & Uncertainty",
        renderer=(
            "render_robustness_uncertainty"
        ),
        mock_basis=(
            "approved visual-language extension"
        ),
        evidence_sources=[
            "table:sensitivity_summary",
            "table:uncertainty_summary",
            "index:visual_asset_index",
            "index:case_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Applicability, sensitivity, "
                    "robustness, and uncertainty"
                ),
                [
                    "Applicability",
                    "Repeated-seed uncertainty",
                ],
            ),
            "chart_role": (
                (
                    "Validated sensitivity summaries "
                    "and focused uncertainty panels"
                ),
                [
                    "summary_figure",
                    (
                        "render_uncertainty_"
                        "focus_panel"
                    ),
                ],
            ),
            "image_panel_role": (
                (
                    "Controlled changes, restored seeds, "
                    "and spatial maps are visualized"
                ),
                [
                    "See the change in paintings",
                    "render_image_grid",
                ],
            ),
            "conclusion_position": (
                (
                    "Each evidence view states what "
                    "changes and how to interpret it"
                ),
                [
                    "What this test changes",
                    "Interpretation",
                ],
            ),
            "limitation": (
                (
                    "Low seed variation is not treated "
                    "as proof of correctness"
                ),
                [
                    (
                        "Low variation can still describe "
                        "four consistently wrong restorations"
                    ),
                    "Uncertainty limit",
                ],
            ),
            "filter_family": (
                (
                    "Evidence-view, metric, region, "
                    "model, group, and seed controls"
                ),
                [
                    "Evidence view",
                    "Uncertainty measure",
                    'select_one("Region"',
                ],
            ),
            "drill_down": (
                (
                    "Uncertainty groups, prompts, "
                    "and candidates remain inspectable"
                ),
                [
                    "uncertainty_group_id",
                    "prompt_variant_id",
                    "candidate_id",
                ],
            ),
            "provenance_view": (
                (
                    "Analysis family and experiment "
                    "identity remain traceable"
                ),
                [
                    "analysis_family",
                    "experiment_id",
                ],
            ),
            "evidence_source": (
                (
                    "Sensitivity, uncertainty, cases, "
                    "and indexed spatial evidence"
                ),
                [
                    "sensitivity_summary",
                    "uncertainty_summary",
                    "case_index",
                ],
            ),
        },
    ),
    "trustworthiness_xai": traceability_page(
        display_name="Trustworthiness & XAI",
        renderer="render_trustworthiness_xai",
        mock_basis=(
            "approved visual-language extension"
        ),
        evidence_sources=[
            "table:trustworthiness_summary",
            "index:case_index",
            "index:visual_asset_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Review guidance, flag use, "
                    "and visual explanation"
                ),
                [
                    "Review guidance",
                    "How to use a flag",
                ],
            ),
            "chart_role": (
                (
                    "Computational failure-assignment "
                    "frequencies"
                ),
                [
                    (
                        "Most frequent computational "
                        "failure assignments"
                    ),
                ],
            ),
            "image_panel_role": (
                (
                    "Restoration and six diagnostic "
                    "evidence families"
                ),
                [
                    "Visual explanation unit",
                    "st.tabs",
                ],
            ),
            "conclusion_position": (
                (
                    "Locate, compare, and escalate "
                    "guidance accompanies the evidence"
                ),
                [
                    "1 · Locate",
                    "2 · Compare",
                    "3 · Escalate",
                ],
            ),
            "limitation": (
                (
                    "Computational flags are not "
                    "expert ground truth"
                ),
                [
                    "neither expert ground truth",
                ],
            ),
            "filter_family": (
                (
                    "Review-lane, model, painting, "
                    "candidate, and catalogue controls"
                ),
                [
                    "Review lane",
                    "xai_candidate",
                    "render_visual_catalogue",
                ],
            ),
            "drill_down": (
                (
                    "All 23,964 indexed visual records "
                    "remain accessible"
                ),
                [
                    (
                        "Complete indexed visual "
                        "catalogue"
                    ),
                ],
            ),
            "provenance_view": (
                (
                    "Complete path and source metadata "
                    "remain available"
                ),
                [
                    "render_visual_catalogue",
                ],
            ),
            "evidence_source": (
                (
                    "Trustworthiness assignments, "
                    "candidate records, and visual index"
                ),
                [
                    "trustworthiness_summary",
                    "render_visual_catalogue",
                ],
            ),
        },
    ),
    "case_explorer": traceability_page(
        display_name="Case Explorer",
        renderer="render_case_explorer",
        mock_basis="ui3.jpeg",
        evidence_sources=[
            "index:case_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Candidate controls, evidence panel, "
                    "and candidate table"
                ),
                [
                    "Candidate-level evidence",
                    (
                        "All candidates in this "
                        "filtered case set"
                    ),
                ],
            ),
            "chart_role": (
                (
                    "A candidate table replaces an "
                    "inappropriate aggregate chart"
                ),
                [
                    "st.dataframe",
                ],
            ),
            "image_panel_role": (
                (
                    "Original, damaged, mask, restoration, "
                    "and diagnostic tabs"
                ),
                [
                    '"clean_path", "Original"',
                    '"damaged_path", "Damaged"',
                    '"mask_path", "Mask"',
                    "st.tabs",
                ],
            ),
            "conclusion_position": (
                (
                    "Coverage, recommendation, and "
                    "uncertainty precede the images"
                ),
                [
                    "evidence_coverage_status",
                    "recommendation_category",
                    "uncertainty_applicability",
                ],
            ),
            "limitation": (
                (
                    "Candidate scope remains visible"
                ),
                [
                    "scope_note",
                ],
            ),
            "filter_family": (
                (
                    "Painting, experiment, damage, "
                    "model, and candidate filters"
                ),
                [
                    'select_one("Painting"',
                    'select_one("Experiment"',
                    'select_one("Damage"',
                    'select_one("Model"',
                    (
                        'st.selectbox('
                        '"Candidate record"'
                    ),
                ],
            ),
            "drill_down": (
                (
                    "Diagnostic tabs and the complete "
                    "filtered candidate set"
                ),
                [
                    "Difference maps",
                    "Boundary & seam",
                    (
                        "All candidates in this "
                        "filtered case set"
                    ),
                ],
            ),
            "provenance_view": (
                (
                    "Case, painting, experiment, model, "
                    "source notebooks, and scope"
                ),
                [
                    "Provenance & reproducibility",
                    "Evidence notebooks",
                ],
            ),
            "evidence_source": (
                (
                    "Complete approved candidate index"
                ),
                [
                    (
                        'bundle.indexes['
                        '"case_index"]'
                    ),
                ],
            ),
        },
    ),
    "reports_reproducibility": traceability_page(
        display_name="Reports & Reproducibility",
        renderer="render_reports",
        mock_basis=(
            "approved visual-language extension"
        ),
        evidence_sources=[
            "table:research_question_coverage",
            "index:report_index",
        ],
        requirements={
            "major_content_block": (
                (
                    "Reproducibility cards, report "
                    "catalogue, and research questions"
                ),
                [
                    "Reproducibility",
                    "Report catalogue",
                ],
            ),
            "chart_role": (
                (
                    "The complete report table is more "
                    "appropriate than an aggregate chart"
                ),
                [
                    "Report catalogue",
                    "st.dataframe",
                ],
            ),
            "image_panel_role": (
                (
                    "Portable reports replace duplicated "
                    "report imagery"
                ),
                [
                    "Download one report",
                ],
            ),
            "conclusion_position": (
                (
                    "Research-question answers follow "
                    "the report catalogue"
                ),
                [
                    "Research-question traceability",
                    "Supported interpretation",
                ],
            ),
            "limitation": (
                (
                    "Prohibited interpretations "
                    "remain visible"
                ),
                [
                    "Do not infer",
                ],
            ),
            "filter_family": (
                (
                    "Report-family and model filters"
                ),
                [
                    'select_one("Report family"',
                    'select_one("Model"',
                ],
            ),
            "drill_down": (
                (
                    "Individual self-contained "
                    "report download"
                ),
                [
                    (
                        "Download self-contained "
                        "report"
                    ),
                ],
            ),
            "provenance_view": (
                (
                    "Notebook 34 run and validation "
                    "provenance"
                ),
                [
                    "Notebook 34 package provenance",
                ],
            ),
            "evidence_source": (
                (
                    "Report index and formal "
                    "research-question coverage"
                ),
                [
                    "report_index",
                    "research_question_coverage",
                ],
            ),
        },
    ),
}

TRACEABILITY_RECORDS = []
PAGE_CONTRACT_RECORDS = []

for page_id in PAGE_IDS:
    page_spec = PAGE_TRACEABILITY_SPEC[page_id]
    renderer = page_spec["renderer"]

    renderer_source = APP_FUNCTION_SOURCES.get(
        renderer,
        "",
    )
    renderer_source_casefold = (
        renderer_source.casefold()
    )

    missing_evidence_sources = sorted(
        set(page_spec["evidence_sources"])
        - AVAILABLE_EVIDENCE_KEYS
    )

    page_contract_passed = (
        page_spec["display_name"]
        == APPLICATION["display_names"][page_id]
        and bool(renderer_source)
        and not missing_evidence_sources
        and (
            set(page_spec["requirements"])
            == set(REQUIRED_TRACEABILITY_ASPECTS)
        )
    )

    PAGE_CONTRACT_RECORDS.append(
        {
            "page_id": page_id,
            "display_name": (
                page_spec["display_name"]
            ),
            "renderer": renderer,
            "mock_basis": page_spec["mock_basis"],
            "evidence_sources": json.dumps(
                page_spec["evidence_sources"],
                ensure_ascii=False,
            ),
            "missing_evidence_sources": (
                json.dumps(
                    missing_evidence_sources,
                    ensure_ascii=False,
                )
            ),
            "aspect_count": len(
                page_spec["requirements"]
            ),
            "passed": page_contract_passed,
        }
    )

    VALIDATION.add(
        validation_stage=(
            "batch_5_page_contracts"
        ),
        check_id=(
            f"page_contract__{page_id}"
        ),
        check_description=(
            "Mock-to-app page contract is "
            f"complete: {page_spec['display_name']}"
        ),
        severity="blocking",
        expected={
            "display_name": (
                APPLICATION[
                    "display_names"
                ][page_id]
            ),
            "aspects": list(
                REQUIRED_TRACEABILITY_ASPECTS
            ),
            "missing_evidence_sources": [],
        },
        observed={
            "display_name": (
                page_spec["display_name"]
            ),
            "aspects": list(
                page_spec["requirements"]
            ),
            "missing_evidence_sources": (
                missing_evidence_sources
            ),
            "renderer_found": bool(
                renderer_source
            ),
        },
        passed=page_contract_passed,
        details="",
    )

    for aspect in REQUIRED_TRACEABILITY_ASPECTS:
        expectation, markers = (
            page_spec["requirements"][aspect]
        )

        missing_markers = [
            marker
            for marker in markers
            if (
                marker.casefold()
                not in renderer_source_casefold
            )
        ]

        passed = (
            not missing_markers
            and not missing_evidence_sources
        )

        TRACEABILITY_RECORDS.append(
            {
                "page_id": page_id,
                "display_name": (
                    page_spec["display_name"]
                ),
                "mock_basis": (
                    page_spec["mock_basis"]
                ),
                "renderer": renderer,
                "aspect": aspect,
                "expectation": expectation,
                "source_markers": json.dumps(
                    markers,
                    ensure_ascii=False,
                ),
                "missing_markers": json.dumps(
                    missing_markers,
                    ensure_ascii=False,
                ),
                "evidence_sources": json.dumps(
                    page_spec["evidence_sources"],
                    ensure_ascii=False,
                ),
                "passed": passed,
            }
        )

        VALIDATION.add(
            validation_stage=(
                "batch_5_mock_traceability"
            ),
            check_id=(
                f"{page_id}__{aspect}"
            ),
            check_description=(
                f"{page_spec['display_name']} "
                f"implements "
                f"{aspect.replace('_', ' ')}"
            ),
            severity="blocking",
            expected={
                "missing_markers": [],
                "missing_evidence_sources": [],
            },
            observed={
                "missing_markers": (
                    missing_markers
                ),
                "missing_evidence_sources": (
                    missing_evidence_sources
                ),
            },
            passed=passed,
            details=expectation,
        )

VALIDATION.raise_for_blocking()

PAGE_CONTRACT_AUDIT = pd.DataFrame(
    PAGE_CONTRACT_RECORDS
)

TRACEABILITY_AUDIT = pd.DataFrame(
    TRACEABILITY_RECORDS
)

TRACEABILITY_PAGE_SUMMARY = (
    TRACEABILITY_AUDIT.groupby(
        [
            "page_id",
            "display_name",
            "mock_basis",
        ],
        dropna=False,
    )
    .agg(
        requirements=("aspect", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

TRACEABILITY_PAGE_SUMMARY["failed"] = (
    TRACEABILITY_PAGE_SUMMARY["requirements"]
    - TRACEABILITY_PAGE_SUMMARY["passed"]
)

display(PAGE_CONTRACT_AUDIT)
display(TRACEABILITY_PAGE_SUMMARY)
display(TRACEABILITY_AUDIT)

print(
    "Eight-page mock-to-app traceability passed."
)
print(
    "Pages:",
    len(PAGE_CONTRACT_AUDIT),
)
print(
    "Traceability requirements:",
    len(TRACEABILITY_AUDIT),
)
print(
    "Traceability failures:",
    int(
        (
            ~TRACEABILITY_AUDIT["passed"]
        ).sum()
    ),
)

,page_id,display_name,renderer,mock_basis,evidence_sources,missing_evidence_sources,aspect_count,passed
0,overview,Overview,render_overview,ui1.jpeg,"[""table:headline_findings"", ""index:visual_asse...",[],9,True
1,study_design,Study Design,render_study_design,approved visual-language extension,"[""table:study_design"", ""index:painting_index""]",[],9,True
2,metric_framework,Metric Framework,render_metric_framework,approved visual-language extension,"[""table:metric_framework"", ""index:case_index""]",[],9,True
3,model_performance,Model Performance,render_model_performance,ui2.jpeg,"[""table:performance_summary"", ""table:compute_s...",[],9,True
4,robustness_uncertainty,Robustness & Uncertainty,render_robustness_uncertainty,approved visual-language extension,"[""table:sensitivity_summary"", ""table:uncertain...",[],9,True
5,trustworthiness_xai,Trustworthiness & XAI,render_trustworthiness_xai,approved visual-language extension,"[""table:trustworthiness_summary"", ""index:case_...",[],9,True
6,case_explorer,Case Explorer,render_case_explorer,ui3.jpeg,"[""index:case_index""]",[],9,True
7,reports_reproducibility,Reports & Reproducibility,render_reports,approved visual-language extension,"[""table:research_question_coverage"", ""index:re...",[],9,True

,page_id,display_name,mock_basis,requirements,passed,failed
0,case_explorer,Case Explorer,ui3.jpeg,9,9,0
1,metric_framework,Metric Framework,approved visual-language extension,9,9,0
2,model_performance,Model Performance,ui2.jpeg,9,9,0
3,overview,Overview,ui1.jpeg,9,9,0
4,reports_reproducibility,Reports & Reproducibility,approved visual-language extension,9,9,0
5,robustness_uncertainty,Robustness & Uncertainty,approved visual-language extension,9,9,0
6,study_design,Study Design,approved visual-language extension,9,9,0
7,trustworthiness_xai,Trustworthiness & XAI,approved visual-language extension,9,9,0

,page_id,display_name,mock_basis,renderer,aspect,expectation,source_markers,missing_markers,evidence_sources,passed
0,overview,Overview,ui1.jpeg,render_overview,major_content_block,"Thesis strip, scope cards, and supported findings","[""thesis-strip"", ""Study scope""]",[],"[""table:headline_findings"", ""index:visual_asse...",True
1,overview,Overview,ui1.jpeg,render_overview,chart_role,Validated thesis-level benchmark summary,"[""Validated thesis-level benchmark summary""]",[],"[""table:headline_findings"", ""index:visual_asse...",True
2,overview,Overview,ui1.jpeg,render_overview,image_panel_role,Three controlled-collection painting witnesses,"[""Three witnesses from the controlled collecti...",[],"[""table:headline_findings"", ""index:visual_asse...",True
3,overview,Overview,ui1.jpeg,render_overview,conclusion_position,Supported conclusions precede the benchmark vi...,"[""What the evidence supports""]",[],"[""table:headline_findings"", ""index:visual_asse...",True
4,overview,Overview,ui1.jpeg,render_overview,limitation,The interpretation boundary closes the page,"[""Interpretation boundary""]",[],"[""table:headline_findings"", ""index:visual_asse...",True
...,...,...,...,...,...,...,...,...,...,...
67,reports_reproducibility,Reports & Reproducibility,approved visual-language extension,render_reports,limitation,Prohibited interpretations remain visible,"[""Do not infer""]",[],"[""table:research_question_coverage"", ""index:re...",True
68,reports_reproducibility,Reports & Reproducibility,approved visual-language extension,render_reports,filter_family,Report-family and model filters,"[""select_one(\""Report family\"""", ""select_one(\...",[],"[""table:research_question_coverage"", ""index:re...",True
69,reports_reproducibility,Reports & Reproducibility,approved visual-language extension,render_reports,drill_down,Individual self-contained report download,"[""Download self-contained report""]",[],"[""table:research_question_coverage"", ""index:re...",True
70,reports_reproducibility,Reports & Reproducibility,approved visual-language extension,render_reports,provenance_view,Notebook 34 run and validation provenance,"[""Notebook 34 package provenance""]",[],"[""table:research_question_coverage"", ""index:re...",True
71,reports_reproducibility,Reports & Reproducibility,approved visual-language extension,render_reports,evidence_source,Report index and formal research-question cove...,"[""report_index"", ""research_question_coverage""]",[],"[""table:research_question_coverage"", ""index:re...",True

Eight-page mock-to-app traceability passed.
Pages: 8
Traceability requirements: 72
Traceability failures: 0

In [21]:
CURRENT_APP_SOURCE_CASEFOLD = (
    APP_SOURCE.casefold()
)

GLOBAL_DESIGN_REQUIREMENTS = (
    (
        "dark_museum_sidebar",
        "Bottle-green museum-style navigation",
        [
            '[data-testid="stsidebar"]',
            "var(--deep-green)",
        ],
    ),
    (
        "aged_paper_surface",
        (
            "Subtle aged-paper surface rather "
            "than a flat synthetic panel"
        ),
        [
            "radial-gradient",
            "var(--paper)",
        ],
    ),
    (
        "editorial_serif_hierarchy",
        (
            "Editorial serif titles with "
            "readable interface text"
        ),
        [
            "cormorant garamond",
            "inter,system-ui,sans-serif",
        ],
    ),
    (
        "modest_irregularity",
        "Restrained handmade irregularity",
        [
            "transform:rotate(-.04deg)",
            "box-shadow",
        ],
    ),
    (
        "evidence_cards",
        "Dense paper-style evidence cards",
        [
            ".paper-card",
            ".evidence-note",
        ],
    ),
    (
        "status_language",
        (
            "Consistent strength, warning, "
            "and caution states"
        ),
        [
            ".status-chip.good",
            ".status-chip.warn",
            ".status-chip.danger",
        ],
    ),
    (
        "framed_images",
        (
            "Painting and diagnostic images "
            "receive restrained framing"
        ),
        [
            ".visual-frame img",
        ],
    ),
    (
        "responsive_layout",
        (
            "The interface retains a responsive "
            "narrow-screen rule"
        ),
        [
            "@media (max-width:900px)",
        ],
    ),
    (
        "representative_defaults",
        (
            "Representative defaults support "
            "immediate comprehension"
        ),
        [
            "representative_case",
        ],
    ),
    (
        "complete_visual_access",
        (
            "Representative defaults do not hide "
            "the complete visual catalogue"
        ),
        [
            "complete indexed visual catalogue",
            "23,964 records",
        ],
    ),
    (
        "complete_candidate_access",
        (
            "The Case Explorer exposes all "
            "candidates in its filtered set"
        ),
        [
            (
                "all candidates in this "
                "filtered case set"
            ),
        ],
    ),
    (
        "portable_report_access",
        (
            "Reports remain individually "
            "downloadable and self-contained"
        ),
        [
            "download self-contained report",
        ],
    ),
    (
        "research_question_traceability",
        (
            "Research questions retain supported "
            "and prohibited interpretations"
        ),
        [
            "research-question traceability",
            "supported interpretation",
            "do not infer",
        ],
    ),
)

DESIGN_AUDIT_RECORDS = []

for (
    requirement_id,
    expectation,
    markers,
) in GLOBAL_DESIGN_REQUIREMENTS:
    missing_markers = [
        marker
        for marker in markers
        if (
            marker.casefold()
            not in CURRENT_APP_SOURCE_CASEFOLD
        )
    ]

    passed = not missing_markers

    DESIGN_AUDIT_RECORDS.append(
        {
            "requirement_id": requirement_id,
            "expectation": expectation,
            "markers": json.dumps(
                markers,
                ensure_ascii=False,
            ),
            "missing_markers": json.dumps(
                missing_markers,
                ensure_ascii=False,
            ),
            "passed": passed,
        }
    )

    VALIDATION.add(
        validation_stage=(
            "batch_5_visual_language"
        ),
        check_id=requirement_id,
        check_description=expectation,
        severity="blocking",
        expected=[],
        observed=missing_markers,
        passed=passed,
        details=(
            ""
            if passed
            else (
                "The implemented interface has "
                "drifted from the approved "
                "visual language."
            )
        ),
    )

DESIGN_AUDIT = pd.DataFrame(
    DESIGN_AUDIT_RECORDS
)

BALANCE_COUNTS = {
    "plotly_charts": application_call_count(
        "st.plotly_chart"
    ),
    "image_renderers": application_call_count(
        "st.image"
    ),
    "data_tables": application_call_count(
        "st.dataframe"
    ),
    "diagnostic_tab_groups": (
        application_call_count("st.tabs")
    ),
    "download_controls": application_call_count(
        "st.download_button"
    ),
    "evidence_note_calls": (
        APP_SOURCE.count("evidence_note(")
        - 1
    ),
}

# The final approved application uses three direct Plotly
# charts. Other chart-like evidence is supplied through
# validated Notebook 34 summary figures and focused image
# panels, so requiring five direct Plotly calls would reject
# the approved design incorrectly.
BALANCE_MINIMUMS = {
    "plotly_charts": 3,
    "image_renderers": 2,
    "data_tables": 5,
    "diagnostic_tab_groups": 2,
    "download_controls": 3,
    "evidence_note_calls": 10,
}

BALANCE_AUDIT_RECORDS = []

for (
    feature,
    minimum,
) in BALANCE_MINIMUMS.items():
    observed = int(
        BALANCE_COUNTS[feature]
    )
    passed = observed >= minimum

    BALANCE_AUDIT_RECORDS.append(
        {
            "feature": feature,
            "minimum": minimum,
            "observed": observed,
            "passed": passed,
        }
    )

    VALIDATION.add(
        validation_stage=(
            "batch_5_content_balance"
        ),
        check_id=f"balance__{feature}",
        check_description=(
            "The application contains sufficient "
            f"{feature.replace('_', ' ')}"
        ),
        severity="blocking",
        expected=f">={minimum}",
        observed=observed,
        passed=passed,
        details=(
            ""
            if passed
            else (
                "The interface no longer balances "
                "visuals, tables, controls, and "
                "conclusions."
            )
        ),
    )

VALIDATION.raise_for_blocking()

BALANCE_AUDIT = pd.DataFrame(
    BALANCE_AUDIT_RECORDS
)

display(DESIGN_AUDIT)
display(BALANCE_AUDIT)

print("Shared visual-language audit passed.")
print(
    "Design requirements:",
    len(DESIGN_AUDIT),
)
print(
    "Content-balance checks:",
    len(BALANCE_AUDIT),
)
print(
    "Direct Plotly charts:",
    BALANCE_COUNTS["plotly_charts"],
)
print(
    "Visual-language failures:",
    int(
        (
            ~DESIGN_AUDIT["passed"]
        ).sum()
    ),
)

,requirement_id,expectation,markers,missing_markers,passed
0,dark_museum_sidebar,Bottle-green museum-style navigation,"[""[data-testid=\""stsidebar\""]"", ""var(--deep-gr...",[],True
1,aged_paper_surface,Subtle aged-paper surface rather than a flat s...,"[""radial-gradient"", ""var(--paper)""]",[],True
2,editorial_serif_hierarchy,Editorial serif titles with readable interface...,"[""cormorant garamond"", ""inter,system-ui,sans-s...",[],True
3,modest_irregularity,Restrained handmade irregularity,"[""transform:rotate(-.04deg)"", ""box-shadow""]",[],True
4,evidence_cards,Dense paper-style evidence cards,"["".paper-card"", "".evidence-note""]",[],True
5,status_language,"Consistent strength, warning, and caution states","["".status-chip.good"", "".status-chip.warn"", "".s...",[],True
6,framed_images,Painting and diagnostic images receive restrai...,"["".visual-frame img""]",[],True
7,responsive_layout,The interface retains a responsive narrow-scre...,"[""@media (max-width:900px)""]",[],True
8,representative_defaults,Representative defaults support immediate comp...,"[""representative_case""]",[],True
9,complete_visual_access,Representative defaults do not hide the comple...,"[""complete indexed visual catalogue"", ""23,964 ...",[],True
10,complete_candidate_access,The Case Explorer exposes all candidates in it...,"[""all candidates in this filtered case set""]",[],True
11,portable_report_access,Reports remain individually downloadable and s...,"[""download self-contained report""]",[],True
12,research_question_traceability,Research questions retain supported and prohib...,"[""research-question traceability"", ""supported ...",[],True

                 feature  minimum  observed  passed
0          plotly_charts        3         3    True
1        image_renderers        2         2    True
2            data_tables        5         9    True
3  diagnostic_tab_groups        2         2    True
4      download_controls        3         3    True
5    evidence_note_calls       10        50    True

Shared visual-language audit passed.
Design requirements: 13
Content-balance checks: 6
Direct Plotly charts: 3
Visual-language failures: 0

In [22]:
CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

PAGE_ASPECT_COUNTS = (
    TRACEABILITY_AUDIT.groupby(
        "page_id"
    )["aspect"]
    .nunique()
)

COMPLETE_PAGE_ASPECTS = bool(
    len(PAGE_ASPECT_COUNTS) == len(PAGE_IDS)
    and (
        PAGE_ASPECT_COUNTS
        == len(REQUIRED_TRACEABILITY_ASPECTS)
    ).all()
)

REFERENCE_BLOCKING_FAILURES = [
    check
    for check in VALIDATION.checks
    if (
        check.validation_stage
        == "batch_5_reference_boundary"
        and check.severity == "blocking"
        and not check.passed
    )
]

BATCH_5_FINAL_CHECKS = (
    (
        "reference_boundary",
        "All blocking external-reference checks passed",
        0,
        len(REFERENCE_BLOCKING_FAILURES),
        not REFERENCE_BLOCKING_FAILURES,
    ),
    (
        "eight_page_contract",
        "All eight page contracts passed",
        8,
        int(PAGE_CONTRACT_AUDIT["passed"].sum()),
        bool(PAGE_CONTRACT_AUDIT["passed"].all()),
    ),
    (
        "complete_traceability_aspects",
        "Every page covers all nine required traceability aspects",
        True,
        COMPLETE_PAGE_ASPECTS,
        COMPLETE_PAGE_ASPECTS,
    ),
    (
        "mock_traceability",
        "Every mock-to-app traceability requirement passed",
        len(TRACEABILITY_AUDIT),
        int(TRACEABILITY_AUDIT["passed"].sum()),
        bool(TRACEABILITY_AUDIT["passed"].all()),
    ),
    (
        "visual_language",
        "Every shared visual-language requirement passed",
        len(DESIGN_AUDIT),
        int(DESIGN_AUDIT["passed"].sum()),
        bool(DESIGN_AUDIT["passed"].all()),
    ),
    (
        "content_balance",
        "Every content-balance requirement passed",
        len(BALANCE_AUDIT),
        int(BALANCE_AUDIT["passed"].sum()),
        bool(BALANCE_AUDIT["passed"].all()),
    ),
    (
        "no_canonical_files_written",
        "Batch 5 has not persisted canonical Notebook 35 files",
        [],
        CANONICAL_FILES_AFTER_BATCH,
        not CANONICAL_FILES_AFTER_BATCH,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in BATCH_5_FINAL_CHECKS:
    VALIDATION.add(
        validation_stage="batch_5_final_gate",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "The dashboard does not yet preserve "
                "the approved mock and evidence structure."
            )
        ),
    )

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

BATCH_5_STAGE_SUMMARY = (
    VALIDATION_FRAME[
        VALIDATION_FRAME[
            "validation_stage"
        ].str.startswith("batch_5")
    ]
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

BATCH_5_STAGE_SUMMARY["failed"] = (
    BATCH_5_STAGE_SUMMARY["checks"]
    - BATCH_5_STAGE_SUMMARY["passed"]
)

display(BATCH_5_STAGE_SUMMARY)
display(TRACEABILITY_PAGE_SUMMARY)

print("Batch 5 mock-to-app traceability passed.")
print(
    "Batch 5 checks:",
    len(
        VALIDATION_FRAME[
            VALIDATION_FRAME[
                "validation_stage"
            ].str.startswith("batch_5")
        ]
    ),
)
print("Pages traced:", len(PAGE_CONTRACT_AUDIT))
print("Traceability requirements:", len(TRACEABILITY_AUDIT))
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Canonical files persisted by Batch 5: 0")

             validation_stage  severity  checks  passed  failed
0     batch_5_content_balance  blocking       6       6       0
1          batch_5_final_gate  blocking       7       7       0
2   batch_5_mock_traceability  blocking      72      72       0
3      batch_5_page_contracts  blocking       8       8       0
4  batch_5_reference_boundary  blocking       5       5       0
5  batch_5_reference_boundary   warning       1       1       0
6     batch_5_visual_language  blocking      13      13       0

,page_id,display_name,mock_basis,requirements,passed,failed
0,case_explorer,Case Explorer,ui3.jpeg,9,9,0
1,metric_framework,Metric Framework,approved visual-language extension,9,9,0
2,model_performance,Model Performance,ui2.jpeg,9,9,0
3,overview,Overview,ui1.jpeg,9,9,0
4,reports_reproducibility,Reports & Reproducibility,approved visual-language extension,9,9,0
5,robustness_uncertainty,Robustness & Uncertainty,approved visual-language extension,9,9,0
6,study_design,Study Design,approved visual-language extension,9,9,0
7,trustworthiness_xai,Trustworthiness & XAI,approved visual-language extension,9,9,0

Batch 5 mock-to-app traceability passed.
Batch 5 checks: 112
Pages traced: 8
Traceability requirements: 72
Blocking failures: 0
Canonical files persisted by Batch 5: 0

## Batch 6 — Bounded SDXL and graceful fallback validation

This batch verifies that partial or unavailable evidence is represented honestly and handled safely.

SDXL remains a bounded ten-case feasibility model:

- it is not treated as a fourth complete benchmark;
- its ten candidates retain complete candidate-level evidence;
- it is excluded from repeated-seed uncertainty because only one candidate exists per case;
- its performance summaries retain `bounded_partial_evaluation`;
- missing case-specific reports do not invalidate available painting reports or candidate evidence.

The batch also tests missing-path, unsupported-file, empty-filter, and unsafe-path behavior without deleting, renaming, or modifying any real repository asset.

In [23]:
from restoration_eval.dashboard_application import (
    case_visual_paths,
    default_case_rows,
    filter_frame,
    report_bytes,
    safe_project_path,
    stable_options,
)


# Make this cell safe to rerun if a previous version added records.
STALE_STAGE = "batch_6_sdxl_scope"

VALIDATION._checks = [
    check
    for check in VALIDATION._checks
    if check.validation_stage != STALE_STAGE
]

VALIDATION._keys = {
    (check.validation_stage, check.check_id)
    for check in VALIDATION._checks
}


SDXL_MODEL_ID = "sdxl_inpainting"

SDXL_CASES = (
    CASE_INDEX.loc[
        CASE_INDEX["model_id"] == SDXL_MODEL_ID
    ]
    .copy()
    .sort_values(
        ["painting_id", "case_id"],
        kind="stable",
    )
    .reset_index(drop=True)
)

SDXL_VISUALS = (
    VISUAL_INDEX.loc[
        VISUAL_INDEX["model_id"] == SDXL_MODEL_ID
    ]
    .copy()
)

PERFORMANCE_FRAME = DASHBOARD_TABLES[
    "performance_summary"
]

UNCERTAINTY_FRAME = DASHBOARD_TABLES[
    "uncertainty_summary"
]

SDXL_PERFORMANCE = (
    PERFORMANCE_FRAME.loc[
        PERFORMANCE_FRAME["model_id"]
        == SDXL_MODEL_ID
    ]
    .copy()
)

# The uncertainty table is group-oriented and intentionally has
# no model_id field. SDXL is represented by an applicability row.
SDXL_UNCERTAINTY_BOUNDARY = (
    UNCERTAINTY_FRAME.loc[
        (
            UNCERTAINTY_FRAME["record_type"]
            == "applicability_boundary"
        )
        & (
            UNCERTAINTY_FRAME["population_id"]
            == "sdxl_single_seed_subset"
        )
        & (
            UNCERTAINTY_FRAME[
                "applicability_status"
            ]
            == (
                "not_applicable_"
                "insufficient_seed_coverage"
            )
        )
    ]
    .copy()
)

# Numeric SDXL uncertainty rows must remain absent.
SDXL_UNCERTAINTY = (
    UNCERTAINTY_FRAME.loc[
        (
            UNCERTAINTY_FRAME["population_id"]
            == "sdxl_single_seed_subset"
        )
        & (
            UNCERTAINTY_FRAME["record_type"]
            != "applicability_boundary"
        )
    ]
    .copy()
)

EXPECTED_SDXL_CASE_IDS = {
    "canonical__p001__loss_large",
    "canonical__p039__loss_large",
    "canonical__p018__mixed_damage",
    "canonical__p043__mixed_damage",
    (
        "synthetic_degradation__p001__"
        "water_stain__severe"
    ),
    (
        "synthetic_degradation__p039__"
        "water_stain__severe"
    ),
    (
        "synthetic_degradation__p018__"
        "dirt_dust__severe"
    ),
    (
        "synthetic_degradation__p026__"
        "dirt_dust__severe"
    ),
    (
        "synthetic_degradation__p043__"
        "partial_transparency__severe"
    ),
    (
        "synthetic_degradation__p026__"
        "water_stain_dirt__moderate"
    ),
}

EXPECTED_SDXL_PAINTINGS = {
    "p001",
    "p018",
    "p026",
    "p039",
    "p043",
}

SDXL_PRIMARY_PATH_COLUMNS = (
    "clean_path",
    "damaged_path",
    "mask_path",
    "restored_path",
)

SDXL_MISSING_PRIMARY_PATHS = []

for row in SDXL_CASES.itertuples(index=False):
    for column in SDXL_PRIMARY_PATH_COLUMNS:
        value = getattr(row, column)

        resolved = safe_project_path(
            value,
            PROJECT_ROOT,
            allowed_suffixes={
                ".png",
                ".jpg",
                ".jpeg",
                ".webp",
            },
        )

        if resolved is None:
            SDXL_MISSING_PRIMARY_PATHS.append(
                {
                    "candidate_id": row.candidate_id,
                    "field": column,
                    "value": value,
                }
            )

SDXL_CASE_REPORT_PATHS = (
    SDXL_CASES["case_report_path"]
    .fillna("")
    .astype(str)
    .str.strip()
)

SDXL_CASE_REPORT_PATHS = (
    SDXL_CASE_REPORT_PATHS[
        SDXL_CASE_REPORT_PATHS.ne("")
    ]
    .tolist()
)

SDXL_PAINTING_REPORT_PATHS = (
    SDXL_CASES["painting_report_path"]
    .fillna("")
    .astype(str)
    .str.strip()
)

SDXL_PAINTING_REPORT_PATHS = (
    SDXL_PAINTING_REPORT_PATHS[
        SDXL_PAINTING_REPORT_PATHS.ne("")
    ]
    .tolist()
)

SDXL_MISSING_CASE_REPORTS = [
    value
    for value in SDXL_CASE_REPORT_PATHS
    if safe_project_path(
        value,
        PROJECT_ROOT,
        allowed_suffixes={".html", ".md"},
    )
    is None
]

SDXL_MISSING_PAINTING_REPORTS = [
    value
    for value in SDXL_PAINTING_REPORT_PATHS
    if safe_project_path(
        value,
        PROJECT_ROOT,
        allowed_suffixes={".html", ".md"},
    )
    is None
]

SDXL_BOUNDARY_HAS_NO_VALUE = bool(
    SDXL_UNCERTAINTY_BOUNDARY["value"]
    .fillna("")
    .astype(str)
    .str.strip()
    .eq("")
    .all()
)

SDXL_BOUNDARY_SEED_COUNT = (
    pd.to_numeric(
        SDXL_UNCERTAINTY_BOUNDARY[
            "seed_count"
        ],
        errors="coerce",
    )
)

SDXL_BOUNDARY_GROUP_COUNT = (
    pd.to_numeric(
        SDXL_UNCERTAINTY_BOUNDARY[
            "group_count"
        ],
        errors="coerce",
    )
)

SDXL_EXPERIMENT_COUNTS = (
    SDXL_CASES["experiment_id"]
    .value_counts()
    .to_dict()
)

SDXL_CHECKS = (
    (
        "candidate_count",
        "Exactly ten SDXL candidates are exposed",
        10,
        len(SDXL_CASES),
        len(SDXL_CASES) == 10,
    ),
    (
        "candidate_uniqueness",
        "Every SDXL candidate ID is unique",
        10,
        SDXL_CASES["candidate_id"].nunique(),
        (
            SDXL_CASES["candidate_id"].nunique()
            == 10
        ),
    ),
    (
        "case_identity",
        "The exact approved ten-case SDXL sample is preserved",
        sorted(EXPECTED_SDXL_CASE_IDS),
        sorted(
            set(
                SDXL_CASES[
                    "case_id"
                ].astype(str)
            )
        ),
        (
            set(
                SDXL_CASES[
                    "case_id"
                ].astype(str)
            )
            == EXPECTED_SDXL_CASE_IDS
        ),
    ),
    (
        "painting_identity",
        "SDXL covers the five approved paintings",
        sorted(EXPECTED_SDXL_PAINTINGS),
        sorted(
            set(
                SDXL_CASES[
                    "painting_id"
                ].astype(str)
            )
        ),
        (
            set(
                SDXL_CASES[
                    "painting_id"
                ].astype(str)
            )
            == EXPECTED_SDXL_PAINTINGS
        ),
    ),
    (
        "experiment_distribution",
        "SDXL retains four canonical and six synthetic cases",
        {
            "canonical_missing_region": 4,
            "synthetic_degradation": 6,
        },
        SDXL_EXPERIMENT_COUNTS,
        (
            SDXL_EXPERIMENT_COUNTS
            == {
                "canonical_missing_region": 4,
                "synthetic_degradation": 6,
            }
        ),
    ),
    (
        "generic_prompt_only",
        "SDXL uses the approved generic prompt arm",
        {"p00_generic"},
        set(
            SDXL_CASES[
                "prompt_variant_id"
            ].astype(str)
        ),
        (
            set(
                SDXL_CASES[
                    "prompt_variant_id"
                ].astype(str)
            )
            == {"p00_generic"}
        ),
    ),
    (
        "bounded_scope",
        "Every SDXL candidate retains bounded diagnostic scope",
        {"bounded_diagnostic_scope"},
        set(
            SDXL_CASES[
                "scope_status"
            ].astype(str)
        ),
        (
            set(
                SDXL_CASES[
                    "scope_status"
                ].astype(str)
            )
            == {"bounded_diagnostic_scope"}
        ),
    ),
    (
        "candidate_evidence",
        "Every SDXL candidate has complete multi-family evidence",
        {
            "complete_multi_family_candidate_evidence"
        },
        set(
            SDXL_CASES[
                "evidence_coverage_status"
            ].astype(str)
        ),
        (
            set(
                SDXL_CASES[
                    "evidence_coverage_status"
                ].astype(str)
            )
            == {
                "complete_multi_family_candidate_evidence"
            }
        ),
    ),
    (
        "candidate_uncertainty_status",
        "Every SDXL candidate records insufficient seed coverage",
        {
            (
                "not_applicable_"
                "insufficient_seed_coverage"
            )
        },
        set(
            SDXL_CASES[
                "uncertainty_applicability"
            ].astype(str)
        ),
        (
            set(
                SDXL_CASES[
                    "uncertainty_applicability"
                ].astype(str)
            )
            == {
                (
                    "not_applicable_"
                    "insufficient_seed_coverage"
                )
            }
        ),
    ),
    (
        "uncertainty_boundary_row",
        "One explicit SDXL uncertainty boundary is retained",
        1,
        len(SDXL_UNCERTAINTY_BOUNDARY),
        len(SDXL_UNCERTAINTY_BOUNDARY) == 1,
    ),
    (
        "uncertainty_boundary_seed_count",
        "The SDXL boundary records one seed per bounded case",
        [1],
        SDXL_BOUNDARY_SEED_COUNT.tolist(),
        (
            len(SDXL_BOUNDARY_SEED_COUNT) == 1
            and bool(
                SDXL_BOUNDARY_SEED_COUNT.eq(1).all()
            )
        ),
    ),
    (
        "uncertainty_boundary_group_count",
        "The SDXL boundary creates no uncertainty groups",
        [0],
        SDXL_BOUNDARY_GROUP_COUNT.tolist(),
        (
            len(SDXL_BOUNDARY_GROUP_COUNT) == 1
            and bool(
                SDXL_BOUNDARY_GROUP_COUNT.eq(0).all()
            )
        ),
    ),
    (
        "uncertainty_boundary_no_value",
        "The SDXL boundary contains no fabricated numeric value",
        True,
        SDXL_BOUNDARY_HAS_NO_VALUE,
        SDXL_BOUNDARY_HAS_NO_VALUE,
    ),
    (
        "uncertainty_boundary_not_confidence",
        "The SDXL boundary is not calibrated confidence",
        False,
        bool(
            SDXL_UNCERTAINTY_BOUNDARY[
                "is_calibrated_confidence"
            ]
            .map(truthy)
            .any()
        ),
        not bool(
            SDXL_UNCERTAINTY_BOUNDARY[
                "is_calibrated_confidence"
            ]
            .map(truthy)
            .any()
        ),
    ),
    (
        "no_numeric_uncertainty_rows",
        "No artificial SDXL uncertainty rows were created",
        0,
        len(SDXL_UNCERTAINTY),
        SDXL_UNCERTAINTY.empty,
    ),
    (
        "bounded_performance_rows",
        "All SDXL performance rows remain partial evaluation",
        {
            "rows": 11,
            "status": "bounded_partial_evaluation",
        },
        {
            "rows": len(SDXL_PERFORMANCE),
            "statuses": sorted(
                set(
                    SDXL_PERFORMANCE[
                        "applicability_status"
                    ].astype(str)
                )
            ),
        },
        (
            len(SDXL_PERFORMANCE) == 11
            and set(
                SDXL_PERFORMANCE[
                    "applicability_status"
                ].astype(str)
            )
            == {"bounded_partial_evaluation"}
        ),
    ),
    (
        "primary_assets",
        "Every SDXL candidate retains its four primary image assets",
        [],
        SDXL_MISSING_PRIMARY_PATHS,
        not SDXL_MISSING_PRIMARY_PATHS,
    ),
    (
        "visual_evidence",
        "The expected SDXL visual evidence is indexed",
        144,
        len(SDXL_VISUALS),
        len(SDXL_VISUALS) == 144,
    ),
    (
        "representative_case_reports",
        "Three existing representative SDXL case reports remain available",
        {
            "declared": 3,
            "missing": 0,
        },
        {
            "declared": len(
                SDXL_CASE_REPORT_PATHS
            ),
            "missing": len(
                SDXL_MISSING_CASE_REPORTS
            ),
        },
        (
            len(SDXL_CASE_REPORT_PATHS) == 3
            and not SDXL_MISSING_CASE_REPORTS
        ),
    ),
    (
        "painting_report_coverage",
        "All ten SDXL rows link to available painting reports",
        {
            "declared": 10,
            "missing": 0,
        },
        {
            "declared": len(
                SDXL_PAINTING_REPORT_PATHS
            ),
            "missing": len(
                SDXL_MISSING_PAINTING_REPORTS
            ),
        },
        (
            len(SDXL_PAINTING_REPORT_PATHS) == 10
            and not SDXL_MISSING_PAINTING_REPORTS
        ),
    ),
    (
        "manual_review_boundary",
        "Every SDXL candidate requires manual review",
        True,
        bool(
            SDXL_CASES[
                "manual_review_required"
            ]
            .map(truthy)
            .all()
        ),
        bool(
            SDXL_CASES[
                "manual_review_required"
            ]
            .map(truthy)
            .all()
        ),
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in SDXL_CHECKS:
    VALIDATION.add(
        validation_stage=STALE_STAGE,
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "SDXL must remain a bounded ten-case "
                "feasibility result."
            )
        ),
    )

VALIDATION.raise_for_blocking()

SDXL_SCOPE_VIEW = SDXL_CASES[
    [
        "candidate_id",
        "case_id",
        "painting_id",
        "experiment_id",
        "degradation_family",
        "severity",
        "prompt_variant_id",
        "scope_status",
        "uncertainty_applicability",
        "recommendation_category",
        "case_report_path",
        "painting_report_path",
    ]
]

SDXL_UNCERTAINTY_BOUNDARY_VIEW = (
    SDXL_UNCERTAINTY_BOUNDARY[
        [
            "population_id",
            "record_type",
            "seed_count",
            "group_count",
            "value",
            "value_unit",
            "applicability_status",
            "is_calibrated_confidence",
            "interpretation",
            "limitation",
        ]
    ]
)

display(SDXL_SCOPE_VIEW)
display(SDXL_UNCERTAINTY_BOUNDARY_VIEW)

print("Bounded SDXL evidence validation passed.")
print("SDXL candidates:", len(SDXL_CASES))
print("SDXL paintings:", SDXL_CASES["painting_id"].nunique())
print("SDXL visual records:", len(SDXL_VISUALS))
print("SDXL performance rows:", len(SDXL_PERFORMANCE))
print(
    "SDXL uncertainty boundary rows:",
    len(SDXL_UNCERTAINTY_BOUNDARY),
)
print(
    "Numeric SDXL uncertainty rows:",
    len(SDXL_UNCERTAINTY),
)

,candidate_id,case_id,painting_id,experiment_id,degradation_family,severity,prompt_variant_id,scope_status,uncertainty_applicability,recommendation_category,case_report_path,painting_report_path
0,sdxl__a502c0783c0a__p00_generic__seed2026,canonical__p001__loss_large,p001,canonical_missing_region,loss_large,canonical,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,outputs/32_case_and_painting_report_generation...,outputs/32_case_and_painting_report_generation...
1,sdxl__ab9ddf049dd2__p00_generic__seed2026,synthetic_degradation__p001__water_stain__severe,p001,synthetic_degradation,water_stain,severe,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,NaN,outputs/32_case_and_painting_report_generation...
2,sdxl__5d3f1bc4bed2__p00_generic__seed2026,canonical__p018__mixed_damage,p018,canonical_missing_region,mixed_damage,canonical,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,do_not_rely_automatically,outputs/32_case_and_painting_report_generation...,outputs/32_case_and_painting_report_generation...
3,sdxl__c2cd75943649__p00_generic__seed2026,synthetic_degradation__p018__dirt_dust__severe,p018,synthetic_degradation,dirt_dust,severe,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,NaN,outputs/32_case_and_painting_report_generation...
4,sdxl__0f568d39f3af__p00_generic__seed2026,synthetic_degradation__p026__dirt_dust__severe,p026,synthetic_degradation,dirt_dust,severe,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,NaN,outputs/32_case_and_painting_report_generation...
5,sdxl__6e4fdb167b5a__p00_generic__seed2026,synthetic_degradation__p026__water_stain_dirt_...,p026,synthetic_degradation,water_stain_dirt,moderate,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,NaN,outputs/32_case_and_painting_report_generation...
6,sdxl__37161b5099c0__p00_generic__seed2026,canonical__p039__loss_large,p039,canonical_missing_region,loss_large,canonical,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,NaN,outputs/32_case_and_painting_report_generation...
7,sdxl__006233c39ebd__p00_generic__seed2026,synthetic_degradation__p039__water_stain__severe,p039,synthetic_degradation,water_stain,severe,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,NaN,outputs/32_case_and_painting_report_generation...
8,sdxl__d6119e004ea0__p00_generic__seed2026,canonical__p043__mixed_damage,p043,canonical_missing_region,mixed_damage,canonical,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,outputs/32_case_and_painting_report_generation...,outputs/32_case_and_painting_report_generation...
9,sdxl__e9843f8c0249__p00_generic__seed2026,synthetic_degradation__p043__partial_transpare...,p043,synthetic_degradation,partial_transparency,severe,p00_generic,bounded_diagnostic_scope,not_applicable_insufficient_seed_coverage,specialist_review_required,NaN,outputs/32_case_and_painting_report_generation...

,population_id,record_type,seed_count,group_count,value,value_unit,applicability_status,is_calibrated_confidence,interpretation,limitation
1722,sdxl_single_seed_subset,applicability_boundary,1,0,NaN,not_applicable,not_applicable_insufficient_seed_coverage,False,"SDXL has one completed seed per bounded case, ...",No numeric uncertainty value is assigned where...

Bounded SDXL evidence validation passed.
SDXL candidates: 10
SDXL paintings: 5
SDXL visual records: 144
SDXL performance rows: 11
SDXL uncertainty boundary rows: 1
Numeric SDXL uncertainty rows: 0

In [24]:
INTENTIONALLY_MISSING_IMAGE = (
    "outputs/35_dashboard_and_deployment_validation/"
    "validation/__intentionally_missing_image__.png"
)

INTENTIONALLY_MISSING_REPORT = (
    "outputs/35_dashboard_and_deployment_validation/"
    "reports/__intentionally_missing_report__.html"
)

MISSING_ASSET_ROW = (
    CASE_INDEX.iloc[0].to_dict()
)

for column in (
    "clean_path",
    "damaged_path",
    "mask_path",
    "restored_path",
):
    MISSING_ASSET_ROW[column] = (
        INTENTIONALLY_MISSING_IMAGE
    )

DIAGNOSTIC_PATH_COLUMNS = (
    "difference_paths_json",
    "uncertainty_paths_json",
    "seam_paths_json",
    "colour_paths_json",
    "texture_paths_json",
    "semantic_paths_json",
    "mask_boundary_paths_json",
)

for column in DIAGNOSTIC_PATH_COLUMNS:
    MISSING_ASSET_ROW[column] = json.dumps(
        [INTENTIONALLY_MISSING_IMAGE]
    )

MISSING_VISUAL_RESULT = case_visual_paths(
    MISSING_ASSET_ROW,
    PROJECT_ROOT,
)

EXPECTED_VISUAL_KEYS = {
    "clean_path",
    "damaged_path",
    "mask_path",
    "restored_path",
    *DIAGNOSTIC_PATH_COLUMNS,
}

MISSING_IMAGE_RESULT = safe_project_path(
    INTENTIONALLY_MISSING_IMAGE,
    PROJECT_ROOT,
    allowed_suffixes={
        ".png",
        ".jpg",
        ".jpeg",
        ".webp",
    },
)

WRONG_SUFFIX_RESULT = safe_project_path(
    APP_PATH.relative_to(
        PROJECT_ROOT
    ).as_posix(),
    PROJECT_ROOT,
    allowed_suffixes={
        ".png",
        ".jpg",
        ".jpeg",
        ".webp",
    },
)

MISSING_REPORT_RESULT = report_bytes(
    INTENTIONALLY_MISSING_REPORT,
    PROJECT_ROOT,
)

EMPTY_REPORT_RESULT = report_bytes(
    "",
    PROJECT_ROOT,
)

UNSAFE_PATH_REJECTED = False
UNSAFE_PATH_EXCEPTION = ""

try:
    safe_project_path(
        "../outside_repository.png",
        PROJECT_ROOT,
        must_exist=False,
    )
except ValueError as exc:
    UNSAFE_PATH_REJECTED = True
    UNSAFE_PATH_EXCEPTION = str(exc)

EMPTY_FILTER_RESULT = filter_frame(
    CASE_INDEX,
    model_id="__model_not_available__",
)

ALL_FILTER_RESULT = filter_frame(
    CASE_INDEX,
    model_id="All",
)

EMPTY_OPTIONS_RESULT = stable_options(
    CASE_INDEX,
    "__missing_column__",
)

DEFAULT_CASES_FIRST = default_case_rows(
    CASE_INDEX
)

DEFAULT_CASES_SECOND = default_case_rows(
    CASE_INDEX
)

DEFAULT_SELECTION_DETERMINISTIC = (
    DEFAULT_CASES_FIRST[
        "candidate_id"
    ].astype(str).tolist()
    == DEFAULT_CASES_SECOND[
        "candidate_id"
    ].astype(str).tolist()
)

MISSING_VISUAL_LISTS_EMPTY = all(
    isinstance(value, list)
    and not value
    for value in MISSING_VISUAL_RESULT.values()
)

FALLBACK_BEHAVIOR_CHECKS = (
    (
        "missing_image_returns_none",
        "A missing repository image resolves to None",
        None,
        MISSING_IMAGE_RESULT,
        MISSING_IMAGE_RESULT is None,
    ),
    (
        "wrong_suffix_returns_none",
        "A non-image file is rejected by an image-path request",
        None,
        WRONG_SUFFIX_RESULT,
        WRONG_SUFFIX_RESULT is None,
    ),
    (
        "missing_report_returns_none",
        "A missing report resolves to None",
        None,
        MISSING_REPORT_RESULT,
        MISSING_REPORT_RESULT is None,
    ),
    (
        "blank_report_returns_none",
        "A blank report path resolves to None",
        None,
        EMPTY_REPORT_RESULT,
        EMPTY_REPORT_RESULT is None,
    ),
    (
        "unsafe_path_rejected",
        "A repository-escape path is rejected",
        True,
        UNSAFE_PATH_REJECTED,
        UNSAFE_PATH_REJECTED,
    ),
    (
        "missing_visual_keys",
        "Missing visual resolution preserves the complete key contract",
        sorted(EXPECTED_VISUAL_KEYS),
        sorted(MISSING_VISUAL_RESULT),
        (
            set(MISSING_VISUAL_RESULT)
            == EXPECTED_VISUAL_KEYS
        ),
    ),
    (
        "missing_visual_lists",
        "Missing visual assets become empty lists without fabrication",
        True,
        MISSING_VISUAL_LISTS_EMPTY,
        MISSING_VISUAL_LISTS_EMPTY,
    ),
    (
        "empty_filter_result",
        "An unavailable filter combination returns an empty frame",
        0,
        len(EMPTY_FILTER_RESULT),
        EMPTY_FILTER_RESULT.empty,
    ),
    (
        "all_filter_result",
        "The All filter retains the complete candidate population",
        len(CASE_INDEX),
        len(ALL_FILTER_RESULT),
        len(ALL_FILTER_RESULT) == len(CASE_INDEX),
    ),
    (
        "missing_options",
        "A missing option field returns an empty option list",
        [],
        EMPTY_OPTIONS_RESULT,
        EMPTY_OPTIONS_RESULT == [],
    ),
    (
        "representative_defaults_available",
        "Representative defaults remain non-empty",
        True,
        not DEFAULT_CASES_FIRST.empty,
        not DEFAULT_CASES_FIRST.empty,
    ),
    (
        "representative_defaults_subset",
        "Representative defaults remain a subset of approved candidates",
        True,
        set(
            DEFAULT_CASES_FIRST[
                "candidate_id"
            ].astype(str)
        ).issubset(
            set(
                CASE_INDEX[
                    "candidate_id"
                ].astype(str)
            )
        ),
        set(
            DEFAULT_CASES_FIRST[
                "candidate_id"
            ].astype(str)
        ).issubset(
            set(
                CASE_INDEX[
                    "candidate_id"
                ].astype(str)
            )
        ),
    ),
    (
        "representative_defaults_deterministic",
        "Representative defaults are selected deterministically",
        True,
        DEFAULT_SELECTION_DETERMINISTIC,
        DEFAULT_SELECTION_DETERMINISTIC,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in FALLBACK_BEHAVIOR_CHECKS:
    VALIDATION.add(
        validation_stage="batch_6_safe_fallbacks",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "Missing or unsafe evidence was not "
                "handled through the approved fallback."
            )
        ),
    )

VALIDATION.raise_for_blocking()

FALLBACK_BEHAVIOR_VIEW = pd.DataFrame(
    [
        {
            "scenario": "missing image",
            "result": repr(MISSING_IMAGE_RESULT),
            "passed": MISSING_IMAGE_RESULT is None,
        },
        {
            "scenario": "wrong file suffix",
            "result": repr(WRONG_SUFFIX_RESULT),
            "passed": WRONG_SUFFIX_RESULT is None,
        },
        {
            "scenario": "missing report",
            "result": repr(MISSING_REPORT_RESULT),
            "passed": MISSING_REPORT_RESULT is None,
        },
        {
            "scenario": "unsafe repository escape",
            "result": (
                "rejected"
                if UNSAFE_PATH_REJECTED
                else "not rejected"
            ),
            "passed": UNSAFE_PATH_REJECTED,
        },
        {
            "scenario": "empty model filter",
            "result": len(EMPTY_FILTER_RESULT),
            "passed": EMPTY_FILTER_RESULT.empty,
        },
        {
            "scenario": "All model filter",
            "result": len(ALL_FILTER_RESULT),
            "passed": (
                len(ALL_FILTER_RESULT)
                == len(CASE_INDEX)
            ),
        },
    ]
)

display(FALLBACK_BEHAVIOR_VIEW)

print("Safe fallback behavior passed.")
print("No repository asset was modified.")
print("Missing visual keys:", len(MISSING_VISUAL_RESULT))
print("Unsafe path rejected:", UNSAFE_PATH_REJECTED)

                   scenario    result  passed
0             missing image      None    True
1         wrong file suffix      None    True
2            missing report      None    True
3  unsafe repository escape  rejected    True
4        empty model filter         0    True
5          All model filter      1785    True

Safe fallback behavior passed.
No repository asset was modified.
Missing visual keys: 11
Unsafe path rejected: True

In [25]:
APP_SOURCE = APP_PATH.read_text(
    encoding="utf-8"
)
APP_SOURCE_CASEFOLD = APP_SOURCE.casefold()

VISIBLE_FALLBACK_MESSAGES = (
    (
        "primary_asset_unavailable",
        "Missing primary images have a visible fallback",
        "asset not available",
    ),
    (
        "diagnostic_asset_unavailable",
        "Missing diagnostics have a visible fallback",
        (
            "no applicable diagnostic image is "
            "indexed for this candidate"
        ),
    ),
    (
        "visual_filter_empty",
        "An empty visual filter has a visible explanation",
        (
            "no visual record matches the selected "
            "filters"
        ),
    ),
    (
        "visual_path_unavailable",
        "A missing indexed visual produces an explicit error",
        (
            "the selected indexed visual path is "
            "unavailable"
        ),
    ),
    (
        "candidate_filter_empty",
        "An empty candidate filter has a visible explanation",
        (
            "no candidate matches this exact filter "
            "combination"
        ),
    ),
    (
        "report_filter_empty",
        "An empty report filter has a visible explanation",
        "no report matches the selected filters",
    ),
    (
        "report_path_unavailable",
        "A missing indexed report produces an explicit error",
        "the indexed report file is unavailable",
    ),
    (
        "numeric_visual_bundle",
        "Non-image numeric map bundles remain traceable",
        "numeric visual bundle",
    ),
    (
        "sdxl_bounded_label",
        "The SDXL ten-case limit is visible",
        "10 cases only",
    ),
    (
        "deployment_not_claimed",
        "A public deployment is not falsely claimed",
        (
            "a public deployment url is not claimed"
        ),
    ),
)

FALLBACK_MESSAGE_RECORDS = []

for (
    message_id,
    description,
    message,
) in VISIBLE_FALLBACK_MESSAGES:
    present = (
        message.casefold()
        in APP_SOURCE_CASEFOLD
    )

    FALLBACK_MESSAGE_RECORDS.append(
        {
            "message_id": message_id,
            "description": description,
            "required_text": message,
            "present": present,
        }
    )

    VALIDATION.add(
        validation_stage=(
            "batch_6_visible_fallbacks"
        ),
        check_id=message_id,
        check_description=description,
        severity="blocking",
        expected=True,
        observed=present,
        passed=present,
        details=(
            ""
            if present
            else (
                "The application lacks a clear user-facing "
                "message for unavailable or bounded evidence."
            )
        ),
    )

VALIDATION.raise_for_blocking()

FALLBACK_MESSAGE_AUDIT = pd.DataFrame(
    FALLBACK_MESSAGE_RECORDS
)

display(FALLBACK_MESSAGE_AUDIT)

print("Visible fallback-message audit passed.")
print(
    "Fallback messages:",
    len(FALLBACK_MESSAGE_AUDIT),
)
print(
    "Missing messages:",
    int(
        (
            ~FALLBACK_MESSAGE_AUDIT[
                "present"
            ]
        ).sum()
    ),
)

,message_id,description,required_text,present
0,primary_asset_unavailable,Missing primary images have a visible fallback,asset not available,True
1,diagnostic_asset_unavailable,Missing diagnostics have a visible fallback,no applicable diagnostic image is indexed for ...,True
2,visual_filter_empty,An empty visual filter has a visible explanation,no visual record matches the selected filters,True
3,visual_path_unavailable,A missing indexed visual produces an explicit ...,the selected indexed visual path is unavailable,True
4,candidate_filter_empty,An empty candidate filter has a visible explan...,no candidate matches this exact filter combina...,True
5,report_filter_empty,An empty report filter has a visible explanation,no report matches the selected filters,True
6,report_path_unavailable,A missing indexed report produces an explicit ...,the indexed report file is unavailable,True
7,numeric_visual_bundle,Non-image numeric map bundles remain traceable,numeric visual bundle,True
8,sdxl_bounded_label,The SDXL ten-case limit is visible,10 cases only,True
9,deployment_not_claimed,A public deployment is not falsely claimed,a public deployment url is not claimed,True

Visible fallback-message audit passed.
Fallback messages: 10
Missing messages: 0

In [26]:
CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

BATCH_6_FINAL_CHECKS = (
    (
        "bounded_sdxl_scope",
        "Every SDXL scope check passed",
        len(SDXL_CHECKS),
        len(SDXL_CHECKS),
        True,
    ),
    (
        "sdxl_no_artificial_uncertainty",
        "No SDXL uncertainty rows were fabricated",
        0,
        len(SDXL_UNCERTAINTY),
        SDXL_UNCERTAINTY.empty,
    ),
    (
        "safe_fallback_behavior",
        "Every safe fallback behavior passed",
        len(FALLBACK_BEHAVIOR_CHECKS),
        len(FALLBACK_BEHAVIOR_CHECKS),
        True,
    ),
    (
        "visible_fallback_messages",
        "Every required fallback message is visible",
        len(FALLBACK_MESSAGE_AUDIT),
        int(
            FALLBACK_MESSAGE_AUDIT[
                "present"
            ].sum()
        ),
        bool(
            FALLBACK_MESSAGE_AUDIT[
                "present"
            ].all()
        ),
    ),
    (
        "real_assets_unchanged",
        "Fallback tests created no files",
        False,
        (
            (
                PROJECT_ROOT
                / INTENTIONALLY_MISSING_IMAGE
            ).exists()
            or (
                PROJECT_ROOT
                / INTENTIONALLY_MISSING_REPORT
            ).exists()
        ),
        not (
            (
                PROJECT_ROOT
                / INTENTIONALLY_MISSING_IMAGE
            ).exists()
            or (
                PROJECT_ROOT
                / INTENTIONALLY_MISSING_REPORT
            ).exists()
        ),
    ),
    (
        "no_canonical_files_written",
        "Batch 6 has not persisted canonical Notebook 35 files",
        [],
        CANONICAL_FILES_AFTER_BATCH,
        not CANONICAL_FILES_AFTER_BATCH,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in BATCH_6_FINAL_CHECKS:
    VALIDATION.add(
        validation_stage="batch_6_final_gate",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "Bounded or unavailable evidence is not "
                "handled safely."
            )
        ),
    )

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

BATCH_6_STAGE_SUMMARY = (
    VALIDATION_FRAME[
        VALIDATION_FRAME[
            "validation_stage"
        ].str.startswith("batch_6")
    ]
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

BATCH_6_STAGE_SUMMARY["failed"] = (
    BATCH_6_STAGE_SUMMARY["checks"]
    - BATCH_6_STAGE_SUMMARY["passed"]
)

display(BATCH_6_STAGE_SUMMARY)

print("Batch 6 bounded-evidence validation passed.")
print(
    "Batch 6 checks:",
    len(
        VALIDATION_FRAME[
            VALIDATION_FRAME[
                "validation_stage"
            ].str.startswith("batch_6")
        ]
    ),
)
print("SDXL candidates:", len(SDXL_CASES))
print("Missing-path files created: 0")
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Canonical files persisted by Batch 6: 0")

            validation_stage  severity  checks  passed  failed
0         batch_6_final_gate  blocking       6       6       0
1     batch_6_safe_fallbacks  blocking      13      13       0
2         batch_6_sdxl_scope  blocking      21      21       0
3  batch_6_visible_fallbacks  blocking      10      10       0

Batch 6 bounded-evidence validation passed.
Batch 6 checks: 50
SDXL candidates: 10
Missing-path files created: 0
Blocking failures: 0
Canonical files persisted by Batch 6: 0

## Batch 7 — Eight-page Streamlit runtime smoke test

This batch executes the application through Streamlit's in-process testing interface.

It visits all eight principal pages using the real sidebar navigation and verifies:

- the selected navigation value;
- successful application execution;
- absence of uncaught exceptions;
- absence of visible application errors;
- presence of the expected page heading;
- non-empty rendered content;
- completion within the configured smoke-test timeout.

The test consumes the real Notebook 34 dashboard package. It does not run restoration inference, recompute scientific metrics, modify application state, or create dashboard evidence.

In [27]:
import time

try:
    import streamlit
    from streamlit.testing.v1 import AppTest

    APPTEST_AVAILABLE = True
    APPTEST_IMPORT_ERROR = ""
except Exception as exc:
    APPTEST_AVAILABLE = False
    APPTEST_IMPORT_ERROR = (
        f"{type(exc).__name__}: {exc}"
    )

OBSERVED_STREAMLIT_VERSION = (
    streamlit.__version__
    if APPTEST_AVAILABLE
    else INSTALLED_VERSIONS.get(
        "streamlit",
        "not_installed",
    )
)

TARGET_STREAMLIT_VERSION = str(
    RUNTIME["packages"]["streamlit"]
)

SMOKE_TIMEOUT_SECONDS = int(
    RUNTIME["smoke_timeout_seconds"]
)

RUNTIME_PREFLIGHT_CHECKS = (
    (
        "streamlit_installed",
        "Streamlit is installed",
        True,
        (
            OBSERVED_STREAMLIT_VERSION
            != "not_installed"
        ),
        (
            OBSERVED_STREAMLIT_VERSION
            != "not_installed"
        ),
        "blocking",
    ),
    (
        "apptest_available",
        "Streamlit AppTest is available",
        True,
        APPTEST_AVAILABLE,
        APPTEST_AVAILABLE,
        "blocking",
    ),
    (
        "application_exists",
        "The Streamlit entrypoint exists",
        True,
        APP_PATH.is_file(),
        APP_PATH.is_file(),
        "blocking",
    ),
    (
        "runtime_package_available",
        "The complete Notebook 34 package is loaded",
        True,
        BUNDLE is not None,
        BUNDLE is not None,
        "blocking",
    ),
    (
        "page_count",
        "Exactly eight pages require runtime validation",
        8,
        len(PAGE_IDS),
        len(PAGE_IDS) == 8,
        "blocking",
    ),
    (
        "smoke_timeout",
        "The smoke timeout is positive",
        ">0",
        SMOKE_TIMEOUT_SECONDS,
        SMOKE_TIMEOUT_SECONDS > 0,
        "blocking",
    ),
    (
        "declared_streamlit_version",
        "The active Streamlit version matches the deployment pin",
        TARGET_STREAMLIT_VERSION,
        OBSERVED_STREAMLIT_VERSION,
        (
            OBSERVED_STREAMLIT_VERSION
            == TARGET_STREAMLIT_VERSION
        ),
        "warning",
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
    severity,
) in RUNTIME_PREFLIGHT_CHECKS:
    VALIDATION.add(
        validation_stage="batch_7_runtime_preflight",
        check_id=check_id,
        check_description=description,
        severity=severity,
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            APPTEST_IMPORT_ERROR
            if check_id == "apptest_available"
            else ""
        ),
    )

VALIDATION.raise_for_blocking()

RUNTIME_PREFLIGHT_VIEW = pd.DataFrame(
    [
        {
            "component": "Streamlit",
            "observed": OBSERVED_STREAMLIT_VERSION,
            "target": TARGET_STREAMLIT_VERSION,
            "available": (
                OBSERVED_STREAMLIT_VERSION
                != "not_installed"
            ),
        },
        {
            "component": "Streamlit AppTest",
            "observed": (
                "available"
                if APPTEST_AVAILABLE
                else APPTEST_IMPORT_ERROR
            ),
            "target": "available",
            "available": APPTEST_AVAILABLE,
        },
        {
            "component": "Notebook 34 package",
            "observed": (
                "loaded"
                if BUNDLE is not None
                else "unavailable"
            ),
            "target": "loaded",
            "available": BUNDLE is not None,
        },
    ]
)

display(RUNTIME_PREFLIGHT_VIEW)

print("Runtime smoke-test preflight passed.")
print("Streamlit:", OBSERVED_STREAMLIT_VERSION)
print("AppTest available:", APPTEST_AVAILABLE)
print("Pages to test:", len(PAGE_IDS))
print("Per-run timeout:", SMOKE_TIMEOUT_SECONDS, "seconds")

             component   observed     target  available
0            Streamlit     1.59.0     1.56.0       True
1    Streamlit AppTest  available  available       True
2  Notebook 34 package     loaded     loaded       True

Runtime smoke-test preflight passed.
Streamlit: 1.59.0
AppTest available: True
Pages to test: 8
Per-run timeout: 120 seconds

In [28]:
from html import unescape as unescape_html

PAGE_RUNTIME_MARKERS = {
    "Overview": (
        "Trustworthy AI-Assisted Painting Restoration"
    ),
    "Study Design": "Study Design",
    "Metric Framework": "Metric Framework",
    "Model Performance": "Model Performance",
    "Robustness & Uncertainty": (
        "Robustness & Uncertainty"
    ),
    "Trustworthiness & XAI": (
        "Trustworthiness & XAI"
    ),
    "Case Explorer": "Case Explorer",
    "Reports & Reproducibility": (
        "Reports & Reproducibility"
    ),
}


def app_element_values(app_test, element_name):
    try:
        elements = getattr(app_test, element_name)
    except (AttributeError, KeyError):
        return []

    values = []

    for element in elements:
        value = getattr(element, "value", "")

        if value is None:
            continue

        values.append(str(value))

    return values


def app_exception_messages(app_test):
    messages = []

    try:
        exceptions = app_test.exception
    except (AttributeError, KeyError):
        exceptions = []

    for element in exceptions:
        message = getattr(element, "message", None)

        if message is None:
            message = getattr(element, "value", None)

        messages.append(
            str(
                message
                if message is not None
                else element
            )
        )

    return messages


PAGE_SMOKE_RECORDS = []
APP_TEST = AppTest.from_file(
    str(APP_PATH),
    default_timeout=SMOKE_TIMEOUT_SECONDS,
)

for page_number, page_id in enumerate(
    PAGE_IDS,
    start=1,
):
    display_name = APPLICATION[
        "display_names"
    ][page_id]

    started = time.perf_counter()
    run_error = ""

    try:
        if page_number == 1:
            APP_TEST = APP_TEST.run()
        else:
            if len(APP_TEST.radio) != 1:
                raise RuntimeError(
                    "Expected exactly one sidebar "
                    "navigation radio control."
                )

            APP_TEST.radio[0].set_value(
                display_name
            )
            APP_TEST = APP_TEST.run()

    except Exception as exc:
        run_error = (
            f"{type(exc).__name__}: {exc}"
        )

    elapsed_seconds = (
        time.perf_counter() - started
    )

    selected_page = ""

    try:
        if len(APP_TEST.radio) == 1:
            selected_page = str(
                APP_TEST.radio[0].value
            )
    except Exception:
        selected_page = ""

    exception_messages = (
        app_exception_messages(APP_TEST)
    )

    visible_error_messages = (
        app_element_values(APP_TEST, "error")
    )

    text_collections = (
        "markdown",
        "title",
        "header",
        "subheader",
        "caption",
        "text",
        "info",
        "warning",
        "success",
    )

    rendered_text_values = []

    for collection_name in text_collections:
        rendered_text_values.extend(
            app_element_values(
                APP_TEST,
                collection_name,
            )
        )

    rendered_text = "\n".join(
        rendered_text_values
    )
    
    # Custom HTML headings encode ampersands as `&amp;`.
    # Normalize the rendered text before checking page titles.
    normalized_rendered_text = unescape_html(
        rendered_text
    )
    
    expected_marker = PAGE_RUNTIME_MARKERS[
        display_name
    ]
    
    marker_present = (
        expected_marker.casefold()
        in normalized_rendered_text.casefold()
    )

    page_passed = (
        not run_error
        and not exception_messages
        and not visible_error_messages
        and selected_page == display_name
        and marker_present
        and bool(rendered_text.strip())
        and elapsed_seconds
        <= SMOKE_TIMEOUT_SECONDS
    )

    PAGE_SMOKE_RECORDS.append(
        {
            "display_order": page_number,
            "page_id": page_id,
            "display_name": display_name,
            "selected_page": selected_page,
            "expected_marker": expected_marker,
            "marker_present": marker_present,
            "rendered_text_items": len(
                rendered_text_values
            ),
            "exception_count": len(
                exception_messages
            ),
            "visible_error_count": len(
                visible_error_messages
            ),
            "run_error": run_error,
            "exception_messages": json.dumps(
                exception_messages,
                ensure_ascii=False,
            ),
            "visible_error_messages": json.dumps(
                visible_error_messages,
                ensure_ascii=False,
            ),
            "runtime_seconds": round(
                elapsed_seconds,
                3,
            ),
            "passed": page_passed,
        }
    )

    status = "passed" if page_passed else "failed"

    print(
        f"[{page_number}/{len(PAGE_IDS)}] "
        f"{display_name}: {status} "
        f"({elapsed_seconds:.2f}s)"
    )

PAGE_SMOKE_AUDIT = pd.DataFrame(
    PAGE_SMOKE_RECORDS
)

display(PAGE_SMOKE_AUDIT)

print("Eight-page application execution finished.")
print(
    "Passed pages:",
    int(PAGE_SMOKE_AUDIT["passed"].sum()),
    "of",
    len(PAGE_SMOKE_AUDIT),
)

2026-09-03 15:26:57.367 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

[1/8] Overview: passed (4.13s)
[2/8] Study Design: passed (2.63s)
[3/8] Metric Framework: passed (0.40s)
[4/8] Model Performance: passed (0.83s)
[5/8] Robustness & Uncertainty: passed (0.97s)
[6/8] Trustworthiness & XAI: passed (2.20s)
[7/8] Case Explorer: passed (1.76s)
[8/8] Reports & Reproducibility: passed (0.36s)

,display_order,page_id,display_name,selected_page,expected_marker,marker_present,rendered_text_items,exception_count,visible_error_count,run_error,exception_messages,visible_error_messages,runtime_seconds,passed
0,1,overview,Overview,Overview,Trustworthy AI-Assisted Painting Restoration,True,42,0,0,,[],[],4.126,True
1,2,study_design,Study Design,Study Design,Study Design,True,56,0,0,,[],[],2.633,True
2,3,metric_framework,Metric Framework,Metric Framework,Metric Framework,True,36,0,0,,[],[],0.405,True
3,4,model_performance,Model Performance,Model Performance,Model Performance,True,44,0,0,,[],[],0.830,True
4,5,robustness_uncertainty,Robustness & Uncertainty,Robustness & Uncertainty,Robustness & Uncertainty,True,48,0,0,,[],[],0.972,True
5,6,trustworthiness_xai,Trustworthiness & XAI,Trustworthiness & XAI,Trustworthiness & XAI,True,32,0,0,,[],[],2.196,True
6,7,case_explorer,Case Explorer,Case Explorer,Case Explorer,True,30,0,0,,[],[],1.762,True
7,8,reports_reproducibility,Reports & Reproducibility,Reports & Reproducibility,Reports & Reproducibility,True,54,0,0,,[],[],0.360,True

Eight-page application execution finished.
Passed pages: 8 of 8

In [29]:
# Remove failed records produced by the earlier HTML-marker check.
STALE_BATCH_7_STAGES = {
    "batch_7_runtime_global",
    "batch_7_runtime_pages",
}

VALIDATION._checks = [
    check
    for check in VALIDATION._checks
    if check.validation_stage
    not in STALE_BATCH_7_STAGES
]

VALIDATION._keys = {
    (check.validation_stage, check.check_id)
    for check in VALIDATION._checks
}

EXPECTED_RUNTIME_PAGE_ORDER = [
    APPLICATION["display_names"][page_id]
    for page_id in PAGE_IDS
]

OBSERVED_RUNTIME_PAGE_ORDER = (
    PAGE_SMOKE_AUDIT.sort_values(
        "display_order",
        kind="stable",
    )["display_name"]
    .astype(str)
    .tolist()
)

RUNTIME_GLOBAL_CHECKS = (
    (
        "page_record_count",
        "Exactly eight page-smoke records were produced",
        8,
        len(PAGE_SMOKE_AUDIT),
        len(PAGE_SMOKE_AUDIT) == 8,
    ),
    (
        "page_order",
        "The runtime page order matches the approved navigation",
        EXPECTED_RUNTIME_PAGE_ORDER,
        OBSERVED_RUNTIME_PAGE_ORDER,
        (
            OBSERVED_RUNTIME_PAGE_ORDER
            == EXPECTED_RUNTIME_PAGE_ORDER
        ),
    ),
    (
        "all_pages_passed",
        "Every page passed its complete runtime smoke test",
        8,
        int(PAGE_SMOKE_AUDIT["passed"].sum()),
        bool(PAGE_SMOKE_AUDIT["passed"].all()),
    ),
    (
        "no_runtime_exceptions",
        "No Streamlit page produced an uncaught exception",
        0,
        int(
            PAGE_SMOKE_AUDIT[
                "exception_count"
            ].sum()
        ),
        (
            int(
                PAGE_SMOKE_AUDIT[
                    "exception_count"
                ].sum()
            )
            == 0
        ),
    ),
    (
        "no_visible_errors",
        "No page displayed an application error",
        0,
        int(
            PAGE_SMOKE_AUDIT[
                "visible_error_count"
            ].sum()
        ),
        (
            int(
                PAGE_SMOKE_AUDIT[
                    "visible_error_count"
                ].sum()
            )
            == 0
        ),
    ),
    (
        "no_runner_errors",
        "No page runner raised an execution error",
        0,
        int(
            PAGE_SMOKE_AUDIT[
                "run_error"
            ]
            .fillna("")
            .astype(str)
            .str.strip()
            .ne("")
            .sum()
        ),
        not bool(
            PAGE_SMOKE_AUDIT[
                "run_error"
            ]
            .fillna("")
            .astype(str)
            .str.strip()
            .ne("")
            .any()
        ),
    ),
    (
        "all_page_markers",
        "Every rendered page contains its expected heading",
        8,
        int(
            PAGE_SMOKE_AUDIT[
                "marker_present"
            ].sum()
        ),
        bool(
            PAGE_SMOKE_AUDIT[
                "marker_present"
            ].all()
        ),
    ),
    (
        "nonempty_rendered_content",
        "Every page produced visible text content",
        True,
        bool(
            PAGE_SMOKE_AUDIT[
                "rendered_text_items"
            ].gt(0).all()
        ),
        bool(
            PAGE_SMOKE_AUDIT[
                "rendered_text_items"
            ].gt(0).all()
        ),
    ),
    (
        "within_timeout",
        "Every page completed within the configured timeout",
        f"<={SMOKE_TIMEOUT_SECONDS}",
        float(
            PAGE_SMOKE_AUDIT[
                "runtime_seconds"
            ].max()
        ),
        bool(
            PAGE_SMOKE_AUDIT[
                "runtime_seconds"
            ]
            .le(SMOKE_TIMEOUT_SECONDS)
            .all()
        ),
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in RUNTIME_GLOBAL_CHECKS:
    VALIDATION.add(
        validation_stage=(
            "batch_7_runtime_global"
        ),
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "One or more dashboard pages failed "
                "runtime validation."
            )
        ),
    )

for row in PAGE_SMOKE_AUDIT.to_dict("records"):
    page_id = str(row["page_id"])

    PAGE_CHECKS = (
        (
            "navigation",
            "Navigation selected the requested page",
            row["display_name"],
            row["selected_page"],
            (
                row["selected_page"]
                == row["display_name"]
            ),
        ),
        (
            "marker",
            "The expected page heading was rendered",
            True,
            bool(row["marker_present"]),
            bool(row["marker_present"]),
        ),
        (
            "exceptions",
            "The page produced no uncaught exceptions",
            0,
            int(row["exception_count"]),
            int(row["exception_count"]) == 0,
        ),
        (
            "visible_errors",
            "The page displayed no application error",
            0,
            int(row["visible_error_count"]),
            (
                int(row["visible_error_count"])
                == 0
            ),
        ),
        (
            "runtime",
            "The page completed within the smoke timeout",
            f"<={SMOKE_TIMEOUT_SECONDS}",
            float(row["runtime_seconds"]),
            (
                float(row["runtime_seconds"])
                <= SMOKE_TIMEOUT_SECONDS
            ),
        ),
    )

    for (
        suffix,
        description,
        expected,
        observed,
        passed,
    ) in PAGE_CHECKS:
        VALIDATION.add(
            validation_stage=(
                "batch_7_runtime_pages"
            ),
            check_id=f"{page_id}__{suffix}",
            check_description=(
                f"{row['display_name']}: {description}"
            ),
            severity="blocking",
            expected=expected,
            observed=observed,
            passed=bool(passed),
            details=(
                {
                    "run_error": row["run_error"],
                    "exceptions": (
                        row["exception_messages"]
                    ),
                    "visible_errors": (
                        row[
                            "visible_error_messages"
                        ]
                    ),
                }
                if not passed
                else ""
            ),
        )

VALIDATION.raise_for_blocking()

RUNTIME_PAGE_SUMMARY = (
    PAGE_SMOKE_AUDIT[
        [
            "display_order",
            "display_name",
            "selected_page",
            "rendered_text_items",
            "exception_count",
            "visible_error_count",
            "runtime_seconds",
            "passed",
        ]
    ]
    .copy()
)

display(RUNTIME_PAGE_SUMMARY)

print("Eight-page runtime validation passed.")
print("Runtime pages:", len(PAGE_SMOKE_AUDIT))
print(
    "Total runtime:",
    round(
        PAGE_SMOKE_AUDIT[
            "runtime_seconds"
        ].sum(),
        3,
    ),
    "seconds",
)
print(
    "Slowest page:",
    PAGE_SMOKE_AUDIT.loc[
        PAGE_SMOKE_AUDIT[
            "runtime_seconds"
        ].idxmax(),
        "display_name",
    ],
)

,display_order,display_name,selected_page,rendered_text_items,exception_count,visible_error_count,runtime_seconds,passed
0,1,Overview,Overview,42,0,0,4.126,True
1,2,Study Design,Study Design,56,0,0,2.633,True
2,3,Metric Framework,Metric Framework,36,0,0,0.405,True
3,4,Model Performance,Model Performance,44,0,0,0.830,True
4,5,Robustness & Uncertainty,Robustness & Uncertainty,48,0,0,0.972,True
5,6,Trustworthiness & XAI,Trustworthiness & XAI,32,0,0,2.196,True
6,7,Case Explorer,Case Explorer,30,0,0,1.762,True
7,8,Reports & Reproducibility,Reports & Reproducibility,54,0,0,0.360,True

Eight-page runtime validation passed.
Runtime pages: 8
Total runtime: 13.284 seconds
Slowest page: Overview

In [30]:
CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

STREAMLIT_VERSION_MATCHES = (
    OBSERVED_STREAMLIT_VERSION
    == TARGET_STREAMLIT_VERSION
)

BATCH_7_FINAL_CHECKS = (
    (
        "runtime_preflight",
        "The runtime smoke-test preflight passed",
        True,
        APPTEST_AVAILABLE,
        APPTEST_AVAILABLE,
        "blocking",
    ),
    (
        "eight_page_execution",
        "All eight pages executed successfully",
        8,
        int(PAGE_SMOKE_AUDIT["passed"].sum()),
        bool(PAGE_SMOKE_AUDIT["passed"].all()),
        "blocking",
    ),
    (
        "zero_exceptions",
        "No runtime exceptions were recorded",
        0,
        int(
            PAGE_SMOKE_AUDIT[
                "exception_count"
            ].sum()
        ),
        (
            int(
                PAGE_SMOKE_AUDIT[
                    "exception_count"
                ].sum()
            )
            == 0
        ),
        "blocking",
    ),
    (
        "zero_visible_errors",
        "No visible application errors were recorded",
        0,
        int(
            PAGE_SMOKE_AUDIT[
                "visible_error_count"
            ].sum()
        ),
        (
            int(
                PAGE_SMOKE_AUDIT[
                    "visible_error_count"
                ].sum()
            )
            == 0
        ),
        "blocking",
    ),
    (
        "runtime_page_order",
        "Runtime navigation preserved the approved page order",
        EXPECTED_RUNTIME_PAGE_ORDER,
        OBSERVED_RUNTIME_PAGE_ORDER,
        (
            OBSERVED_RUNTIME_PAGE_ORDER
            == EXPECTED_RUNTIME_PAGE_ORDER
        ),
        "blocking",
    ),
    (
        "streamlit_version_alignment",
        "The active Streamlit version matches the deployment pin",
        TARGET_STREAMLIT_VERSION,
        OBSERVED_STREAMLIT_VERSION,
        STREAMLIT_VERSION_MATCHES,
        "warning",
    ),
    (
        "no_canonical_files_written",
        "Batch 7 has not persisted canonical Notebook 35 files",
        [],
        CANONICAL_FILES_AFTER_BATCH,
        not CANONICAL_FILES_AFTER_BATCH,
        "blocking",
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
    severity,
) in BATCH_7_FINAL_CHECKS:
    VALIDATION.add(
        validation_stage="batch_7_final_gate",
        check_id=check_id,
        check_description=description,
        severity=severity,
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            (
                "The application passed runtime testing, "
                "but the execution environment differs "
                "from the declared deployment pin."
            )
            if (
                check_id
                == "streamlit_version_alignment"
                and not passed
            )
            else ""
        ),
    )

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

BATCH_7_STAGE_SUMMARY = (
    VALIDATION_FRAME[
        VALIDATION_FRAME[
            "validation_stage"
        ].str.startswith("batch_7")
    ]
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

BATCH_7_STAGE_SUMMARY["failed"] = (
    BATCH_7_STAGE_SUMMARY["checks"]
    - BATCH_7_STAGE_SUMMARY["passed"]
)

display(BATCH_7_STAGE_SUMMARY)

print("Batch 7 Streamlit runtime validation passed.")
print(
    "Batch 7 checks:",
    len(
        VALIDATION_FRAME[
            VALIDATION_FRAME[
                "validation_stage"
            ].str.startswith("batch_7")
        ]
    ),
)
print("Pages passed:", int(PAGE_SMOKE_AUDIT["passed"].sum()))
print(
    "Streamlit version warning:",
    not STREAMLIT_VERSION_MATCHES,
)
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Canonical files persisted by Batch 7: 0")

            validation_stage  severity  checks  passed  failed
0         batch_7_final_gate  blocking       6       6       0
1         batch_7_final_gate   warning       1       0       1
2     batch_7_runtime_global  blocking       9       9       0
3      batch_7_runtime_pages  blocking      40      40       0
4  batch_7_runtime_preflight  blocking       6       6       0
5  batch_7_runtime_preflight   warning       1       0       1

Batch 7 Streamlit runtime validation passed.
Batch 7 checks: 63
Pages passed: 8
Streamlit version warning: True
Blocking failures: 0
Canonical files persisted by Batch 7: 0

## Batch 8 — Deployment-readiness assessment and report preview

This batch converts the accumulated validation evidence into the final deployment-readiness report.

The report distinguishes three separate conclusions:

- whether the application is scientifically and structurally valid;
- whether it is ready for local supervisor demonstration;
- whether a reproducible external deployment has been completed.

A successful local smoke test does not establish external deployment readiness. Dependency-pin differences and the absence of a recorded deployment URL remain visible action items.

The report is built and validated in memory in this batch. Canonical persistence occurs only in Batch 9.

In [31]:
VALIDATION_FRAME = VALIDATION.to_dataframe()

CURRENT_BLOCKING_FAILURES = VALIDATION_FRAME[
    (
        VALIDATION_FRAME["severity"]
        == "blocking"
    )
    & (
        ~VALIDATION_FRAME["passed"]
    )
].copy()

CURRENT_WARNING_FAILURES = VALIDATION_FRAME[
    (
        VALIDATION_FRAME["severity"]
        == "warning"
    )
    & (
        ~VALIDATION_FRAME["passed"]
    )
].copy()

PACKAGE_VERSION_ROWS = []

for package_name in sorted(TARGET_VERSIONS):
    target_version = str(
        TARGET_VERSIONS[package_name]
    )
    observed_version = str(
        INSTALLED_VERSIONS.get(
            package_name,
            "not_installed",
        )
    )

    PACKAGE_VERSION_ROWS.append(
        {
            "package": package_name,
            "target_version": target_version,
            "observed_version": observed_version,
            "matches": (
                observed_version
                == target_version
            ),
        }
    )

PACKAGE_VERSION_AUDIT = pd.DataFrame(
    PACKAGE_VERSION_ROWS
)

VERSION_MISMATCHES = (
    PACKAGE_VERSION_AUDIT.loc[
        ~PACKAGE_VERSION_AUDIT["matches"]
    ]
    .copy()
    .reset_index(drop=True)
)

DEPENDENCY_PINS_ALIGNED = (
    VERSION_MISMATCHES.empty
)

DEPLOYMENT_URL = str(
    RUNTIME.get("deployment_url", "") or ""
).strip()

DEPLOYMENT_PLATFORM = str(
    RUNTIME.get(
        "deployment_platform",
        "not_deployed",
    )
)

EXTERNAL_DEPLOYMENT_RECORDED = bool(
    DEPLOYMENT_URL
    and DEPLOYMENT_PLATFORM
    not in {
        "",
        "not_deployed",
        "none",
        "not_available",
    }
)

REPORTS_SELF_CONTAINED = bool(
    REPORT_INDEX["self_contained"]
    .map(truthy)
    .all()
)

LOCAL_APPLICATION_READY = bool(
    CURRENT_BLOCKING_FAILURES.empty
    and APP_STATIC_AUDIT["passed"].all()
    and PAGE_SMOKE_AUDIT["passed"].all()
    and TRACEABILITY_AUDIT["passed"].all()
    and INDEXED_PATH_AUDIT["passed"].all()
    and REPORTS_SELF_CONTAINED
)

if (
    LOCAL_APPLICATION_READY
    and DEPENDENCY_PINS_ALIGNED
    and EXTERNAL_DEPLOYMENT_RECORDED
):
    OVERALL_READINESS_STATUS = (
        "deployment_validated"
    )
elif LOCAL_APPLICATION_READY:
    OVERALL_READINESS_STATUS = (
        "conditionally_ready_for_local_demonstration"
    )
else:
    OVERALL_READINESS_STATUS = "not_ready"

READINESS_MATRIX = pd.DataFrame(
    [
        {
            "component": "Notebook 34 evidence package",
            "status": "ready",
            "evidence": (
                "76 package checks passed; "
                "19 physical files validated"
            ),
            "conclusion": (
                "The application has a complete, fixed "
                "presentation package."
            ),
            "next_action": "None",
        },
        {
            "component": "Indexed evidence access",
            "status": "ready",
            "evidence": (
                "1,785 candidates; 50 paintings; "
                "23,964 visual records; 104 reports"
            ),
            "conclusion": (
                "Representative defaults do not prevent "
                "complete indexed inspection."
            ),
            "next_action": "None",
        },
        {
            "component": "Scientific boundaries",
            "status": "ready",
            "evidence": (
                "No inference, metric recomputation, "
                "combined score, or unsupported claim"
            ),
            "conclusion": (
                "The dashboard remains an inspection and "
                "decision-support layer."
            ),
            "next_action": "None",
        },
        {
            "component": "Approved UI traceability",
            "status": "ready",
            "evidence": (
                "72 of 72 page/aspect mappings passed"
            ),
            "conclusion": (
                "The implemented application retains the "
                "approved museum-research design."
            ),
            "next_action": "None",
        },
        {
            "component": "Eight-page runtime",
            "status": "ready",
            "evidence": (
                f"8 pages passed in "
                f"{PAGE_SMOKE_AUDIT['runtime_seconds'].sum():.2f}s"
            ),
            "conclusion": (
                "The current local environment is suitable "
                "for supervisor demonstration."
            ),
            "next_action": "None for local use",
        },
        {
            "component": "Portable reports",
            "status": "ready",
            "evidence": (
                f"{len(REPORT_INDEX)} of "
                f"{len(REPORT_INDEX)} reports are "
                f"self-contained"
            ),
            "conclusion": (
                "Downloaded reports retain their required "
                "content without repository-relative images."
            ),
            "next_action": "None",
        },
        {
            "component": "Dependency-pin alignment",
            "status": (
                "ready"
                if DEPENDENCY_PINS_ALIGNED
                else "action_required"
            ),
            "evidence": (
                "All versions match"
                if DEPENDENCY_PINS_ALIGNED
                else (
                    f"{len(VERSION_MISMATCHES)} package "
                    f"versions differ"
                )
            ),
            "conclusion": (
                "The tested environment works, but exact "
                "deployment reproducibility is not yet locked."
                if not DEPENDENCY_PINS_ALIGNED
                else (
                    "The tested environment matches the "
                    "declared deployment environment."
                )
            ),
            "next_action": (
                "Recreate the environment from requirements.txt"
                if not DEPENDENCY_PINS_ALIGNED
                else "None"
            ),
        },
        {
            "component": "External deployment",
            "status": (
                "ready"
                if EXTERNAL_DEPLOYMENT_RECORDED
                else "not_deployed"
            ),
            "evidence": (
                DEPLOYMENT_URL
                if EXTERNAL_DEPLOYMENT_RECORDED
                else "No public URL is recorded"
            ),
            "conclusion": (
                "External deployment has been recorded."
                if EXTERNAL_DEPLOYMENT_RECORDED
                else (
                    "Local readiness must not be described "
                    "as completed public deployment."
                )
            ),
            "next_action": (
                "None"
                if EXTERNAL_DEPLOYMENT_RECORDED
                else (
                    "Deploy externally, then record the "
                    "platform and URL"
                )
            ),
        },
    ]
)

READINESS_CHECKS = (
    (
        "local_application_ready",
        "The dashboard is ready for local demonstration",
        True,
        LOCAL_APPLICATION_READY,
        LOCAL_APPLICATION_READY,
        "blocking",
    ),
    (
        "dependency_pin_alignment",
        "The active environment matches all declared pins",
        True,
        DEPENDENCY_PINS_ALIGNED,
        DEPENDENCY_PINS_ALIGNED,
        "warning",
    ),
    (
        "external_deployment_recorded",
        "An external deployment URL and platform are recorded",
        True,
        EXTERNAL_DEPLOYMENT_RECORDED,
        EXTERNAL_DEPLOYMENT_RECORDED,
        "info",
    ),
    (
        "self_contained_reports",
        "Every indexed report is self-contained",
        len(REPORT_INDEX),
        int(
            REPORT_INDEX[
                "self_contained"
            ].map(truthy).sum()
        ),
        REPORTS_SELF_CONTAINED,
        "blocking",
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
    severity,
) in READINESS_CHECKS:
    VALIDATION.add(
        validation_stage="batch_8_readiness_decision",
        check_id=check_id,
        check_description=description,
        severity=severity,
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "This item remains visible in the "
                "deployment-readiness report."
            )
        ),
    )

VALIDATION.raise_for_blocking()

display(READINESS_MATRIX)
display(PACKAGE_VERSION_AUDIT)

print("Readiness decision derived.")
print("Overall status:", OVERALL_READINESS_STATUS)
print("Local application ready:", LOCAL_APPLICATION_READY)
print("Dependency mismatches:", len(VERSION_MISMATCHES))
print(
    "External deployment recorded:",
    EXTERNAL_DEPLOYMENT_RECORDED,
)

,component,status,evidence,conclusion,next_action
0,Notebook 34 evidence package,ready,76 package checks passed; 19 physical files va...,"The application has a complete, fixed presenta...",None
1,Indexed evidence access,ready,"1,785 candidates; 50 paintings; 23,964 visual ...",Representative defaults do not prevent complet...,None
2,Scientific boundaries,ready,"No inference, metric recomputation, combined s...",The dashboard remains an inspection and decisi...,None
3,Approved UI traceability,ready,72 of 72 page/aspect mappings passed,The implemented application retains the approv...,None
4,Eight-page runtime,ready,8 pages passed in 13.28s,The current local environment is suitable for ...,None for local use
5,Portable reports,ready,104 of 104 reports are self-contained,Downloaded reports retain their required conte...,None
6,Dependency-pin alignment,action_required,4 package versions differ,"The tested environment works, but exact deploy...",Recreate the environment from requirements.txt
7,External deployment,not_deployed,No public URL is recorded,Local readiness must not be described as compl...,"Deploy externally, then record the platform an..."

     package target_version observed_version  matches
0      numpy         1.26.4           1.26.4     True
1     pandas          2.3.3            2.3.3     True
2     pillow         12.3.0            9.5.0    False
3     plotly          6.9.0            6.8.0    False
4    pyarrow         20.0.0           24.0.0    False
5     pyyaml          6.0.3            6.0.3     True
6  streamlit         1.56.0           1.59.0    False

Readiness decision derived.
Overall status: conditionally_ready_for_local_demonstration
Local application ready: True
Dependency mismatches: 4
External deployment recorded: False

In [32]:
def markdown_cell(value):
    text = str(value)
    return (
        text.replace("|", "\\|")
        .replace("\r", " ")
        .replace("\n", " ")
        .strip()
    )


def dataframe_to_markdown(frame, columns):
    labels = [
        str(column).replace("_", " ").title()
        for column in columns
    ]

    lines = [
        "| " + " | ".join(labels) + " |",
        "| "
        + " | ".join("---" for _ in columns)
        + " |",
    ]

    for row in frame[columns].itertuples(
        index=False,
        name=None,
    ):
        lines.append(
            "| "
            + " | ".join(
                markdown_cell(value)
                for value in row
            )
            + " |"
        )

    return "\n".join(lines)


READINESS_TABLE_MARKDOWN = dataframe_to_markdown(
    READINESS_MATRIX,
    [
        "component",
        "status",
        "evidence",
        "conclusion",
        "next_action",
    ],
)

PAGE_RUNTIME_REPORT_TABLE = (
    PAGE_SMOKE_AUDIT[
        [
            "display_name",
            "runtime_seconds",
            "exception_count",
            "visible_error_count",
            "passed",
        ]
    ]
    .copy()
)

PAGE_RUNTIME_REPORT_TABLE[
    "runtime_seconds"
] = PAGE_RUNTIME_REPORT_TABLE[
    "runtime_seconds"
].map(lambda value: f"{value:.3f}")

PAGE_RUNTIME_MARKDOWN = dataframe_to_markdown(
    PAGE_RUNTIME_REPORT_TABLE,
    [
        "display_name",
        "runtime_seconds",
        "exception_count",
        "visible_error_count",
        "passed",
    ],
)

if VERSION_MISMATCHES.empty:
    VERSION_MISMATCH_MARKDOWN = (
        "- No dependency-version differences were found."
    )
else:
    VERSION_MISMATCH_MARKDOWN = "\n".join(
        (
            f"- **{row.package}:** tested with "
            f"`{row.observed_version}`; deployment pin "
            f"is `{row.target_version}`."
        )
        for row in VERSION_MISMATCHES.itertuples(
            index=False
        )
    )

if EXTERNAL_DEPLOYMENT_RECORDED:
    EXTERNAL_DEPLOYMENT_TEXT = (
        f"The deployment is recorded on "
        f"**{DEPLOYMENT_PLATFORM}** at "
        f"{DEPLOYMENT_URL}."
    )
else:
    EXTERNAL_DEPLOYMENT_TEXT = (
        "No public deployment URL is recorded. "
        "The validated result is local application "
        "readiness, not completed external deployment."
    )

DEPLOYMENT_READINESS_TEXT = f"""# Dashboard Deployment-Readiness Report

**Notebook:** `35_dashboard_and_deployment_validation.ipynb`  
**Application:** `streamlit_app.py`  
**Validated package:** `outputs/34_final_streamlit_dashboard_assets/`  
**Assessment:** `{OVERALL_READINESS_STATUS}`  
**Runtime tested:** Streamlit `{OBSERVED_STREAMLIT_VERSION}`  
**Deployment pin:** Streamlit `{TARGET_STREAMLIT_VERSION}`

## 1. Decision

The dashboard is **ready for local supervisor demonstration** in the tested environment.

It is **not yet recorded as a reproducible public deployment**. The application passed all eight runtime page tests, but {len(VERSION_MISMATCHES)} installed package versions differ from the declared deployment pins and no public deployment URL is recorded.

### What this means

- The dashboard can be used locally to inspect the validated thesis evidence.
- The application does not create restorations or recompute scientific metrics.
- Representative examples support orientation; the complete indexed evidence remains filterable.
- Public-deployment completion should be claimed only after dependency reconciliation and an external deployment check.

## 2. Readiness matrix

{READINESS_TABLE_MARKDOWN}

## 3. Runtime evidence

All eight principal pages rendered without an uncaught exception or visible application error.

{PAGE_RUNTIME_MARKDOWN}

**Runtime conclusion:** the application completed all page transitions in {PAGE_SMOKE_AUDIT["runtime_seconds"].sum():.3f} seconds. The slowest page was **{PAGE_SMOKE_AUDIT.loc[PAGE_SMOKE_AUDIT["runtime_seconds"].idxmax(), "display_name"]}** at {PAGE_SMOKE_AUDIT["runtime_seconds"].max():.3f} seconds. This is suitable for local presentation and interactive inspection.

## 4. Evidence available through the dashboard

- **50 paintings**
- **410 restoration cases**
- **1,785 approved candidates**
- **23,964 indexed visual records**
- **104 self-contained reports**
- **130 canonical repeated-seed uncertainty groups**
- **35 damage-size uncertainty groups**
- **10 bounded SDXL candidates**

The Case Explorer exposes original, damaged, mask, restored, and diagnostic evidence. The Trustworthiness & XAI page also exposes the complete visual catalogue, including supporting prompt-ablation maps that remain separate from the approved candidate index.

## 5. Scientific interpretation limits

- Visual plausibility is not historical correctness, authenticity, conservation approval, or restoration trustworthiness.
- Metrics remain separate by family and region; the application does not create a universal combined score.
- Repeated-seed variation is empirical diffusion uncertainty, not calibrated confidence.
- Mask and degradation sensitivity are robustness evidence, not generative uncertainty.
- Computational flags support review; they are not expert ground truth.
- Retrieval results provide context and do not prove restoration correctness.
- SDXL is a ten-case feasibility study, not a fourth complete benchmark.

**Scientific conclusion:** the dashboard is suitable for evidence inspection and communication. It is not an experiment runner, restoration tool, or conservation decision system.

## 6. Dependency reconciliation

{VERSION_MISMATCH_MARKDOWN}

The current environment passed the complete runtime smoke test despite these differences. Exact deployment reproducibility still requires installing the versions declared in `requirements.txt` and repeating the eight-page smoke test.

## 7. External deployment state

{EXTERNAL_DEPLOYMENT_TEXT}

Before claiming completed external deployment:

1. Create a clean environment from `requirements.txt`.
2. Run `python -m streamlit run streamlit_app.py`.
3. Verify all eight pages and representative downloads.
4. Confirm that repository-indexed assets are available on the deployment host.
5. Record the deployment platform and public URL in the Notebook 35 configuration.
6. Rerun Notebook 35 and persist a new readiness report.

## 8. Local launch

From the repository root:

```text
python -m streamlit run streamlit_app.py
```

The application reads only the fixed Notebook 34 dashboard package. It must not be redirected to legacy global output folders.

## 9. Final conclusion

Local demonstration: ready.
Scientific presentation boundary: passed.
Complete indexed access: passed.

Exact dependency alignment: {"passed" if DEPENDENCY_PINS_ALIGNED else "action required"}.
External deployment: {"recorded" if EXTERNAL_DEPLOYMENT_RECORDED else "not deployed"}.

The current validated outcome is therefore conditional local readiness, not completed public deployment.
"""

print("Deployment-readiness report built in memory.")
print(
    "Report characters:",
    len(DEPLOYMENT_READINESS_TEXT),
)
print(
    "Report lines:",
    len(DEPLOYMENT_READINESS_TEXT.splitlines()),
)
print("Canonical files persisted by this cell: 0")

Deployment-readiness report built in memory.
Report characters: 6525
Report lines: 119
Canonical files persisted by this cell: 0

In [33]:
from IPython.display import Markdown


REQUIRED_REPORT_SECTIONS = (
    "# Dashboard Deployment-Readiness Report",
    "## 1. Decision",
    "## 2. Readiness matrix",
    "## 3. Runtime evidence",
    "## 4. Evidence available through the dashboard",
    "## 5. Scientific interpretation limits",
    "## 6. Dependency reconciliation",
    "## 7. External deployment state",
    "## 8. Local launch",
    "## 9. Final conclusion",
)

PLACEHOLDER_TOKENS = (
    "TBD",
    "TODO",
    "INSERT VALUE",
    "FICTIONAL VALUE",
    "PLACEHOLDER FIGURE",
)

MISSING_REPORT_SECTIONS = [
    section
    for section in REQUIRED_REPORT_SECTIONS
    if section not in DEPLOYMENT_READINESS_TEXT
]

FOUND_PLACEHOLDER_TOKENS = [
    token
    for token in PLACEHOLDER_TOKENS
    if token.casefold()
    in DEPLOYMENT_READINESS_TEXT.casefold()
]

MISSING_PAGE_NAMES = [
    display_name
    for display_name
    in EXPECTED_RUNTIME_PAGE_ORDER
    if display_name
    not in DEPLOYMENT_READINESS_TEXT
]

MISSING_VERSION_MISMATCHES = [
    str(row.package)
    for row in VERSION_MISMATCHES.itertuples(
        index=False
    )
    if (
        str(row.package)
        not in DEPLOYMENT_READINESS_TEXT
        or str(row.observed_version)
        not in DEPLOYMENT_READINESS_TEXT
        or str(row.target_version)
        not in DEPLOYMENT_READINESS_TEXT
    )
]

REPORT_CONTRACT_CHECKS = (
    (
        "section_structure",
        "Every required report section is present",
        [],
        MISSING_REPORT_SECTIONS,
        not MISSING_REPORT_SECTIONS,
    ),
    (
        "no_planning_placeholders",
        "No fictional or unfinished placeholder remains",
        [],
        FOUND_PLACEHOLDER_TOKENS,
        not FOUND_PLACEHOLDER_TOKENS,
    ),
    (
        "runtime_page_coverage",
        "Every validated page appears in the runtime table",
        [],
        MISSING_PAGE_NAMES,
        not MISSING_PAGE_NAMES,
    ),
    (
        "version_mismatch_coverage",
        "Every dependency mismatch is reported",
        [],
        MISSING_VERSION_MISMATCHES,
        not MISSING_VERSION_MISMATCHES,
    ),
    (
        "population_counts",
        "The report preserves the approved evidence population",
        True,
        all(
            token in DEPLOYMENT_READINESS_TEXT
            for token in (
                "50 paintings",
                "410 restoration cases",
                "1,785 approved candidates",
                "23,964 indexed visual records",
                "104 self-contained reports",
                "10 bounded SDXL candidates",
            )
        ),
        all(
            token in DEPLOYMENT_READINESS_TEXT
            for token in (
                "50 paintings",
                "410 restoration cases",
                "1,785 approved candidates",
                "23,964 indexed visual records",
                "104 self-contained reports",
                "10 bounded SDXL candidates",
            )
        ),
    ),
    (
        "local_readiness_conclusion",
        "The supported local-readiness conclusion is explicit",
        True,
        (
            "ready for local supervisor demonstration"
            in DEPLOYMENT_READINESS_TEXT
        ),
        (
            "ready for local supervisor demonstration"
            in DEPLOYMENT_READINESS_TEXT
        ),
    ),
    (
        "no_false_deployment_claim",
        "The absence of an external deployment is explicit",
        True,
        (
            (
                "No public deployment URL is recorded"
                in DEPLOYMENT_READINESS_TEXT
            )
            if not EXTERNAL_DEPLOYMENT_RECORDED
            else DEPLOYMENT_URL
            in DEPLOYMENT_READINESS_TEXT
        ),
        (
            (
                "No public deployment URL is recorded"
                in DEPLOYMENT_READINESS_TEXT
            )
            if not EXTERNAL_DEPLOYMENT_RECORDED
            else DEPLOYMENT_URL
            in DEPLOYMENT_READINESS_TEXT
        ),
    ),
    (
        "scientific_boundaries",
        "The required scientific limits are explicit",
        True,
        all(
            token in DEPLOYMENT_READINESS_TEXT
            for token in (
                "not historical correctness",
                "universal combined score",
                "not calibrated confidence",
                "not expert ground truth",
                "ten-case feasibility study",
            )
        ),
        all(
            token in DEPLOYMENT_READINESS_TEXT
            for token in (
                "not historical correctness",
                "universal combined score",
                "not calibrated confidence",
                "not expert ground truth",
                "ten-case feasibility study",
            )
        ),
    ),
    (
        "canonical_output_path",
        "The report is assigned to its canonical Notebook 35 path",
        (
            "outputs/35_dashboard_and_deployment_validation/"
            "reports/deployment_readiness.md"
        ),
        OUTPUT_PATHS[
            "deployment_readiness"
        ].relative_to(
            PROJECT_ROOT
        ).as_posix(),
        (
            OUTPUT_PATHS[
                "deployment_readiness"
            ].relative_to(
                PROJECT_ROOT
            ).as_posix()
            == (
                "outputs/35_dashboard_and_deployment_validation/"
                "reports/deployment_readiness.md"
            )
        ),
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in REPORT_CONTRACT_CHECKS:
    VALIDATION.add(
        validation_stage="batch_8_report_contract",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "The readiness report is incomplete or "
                "overstates deployment status."
            )
        ),
    )

VALIDATION.raise_for_blocking()

display(Markdown(DEPLOYMENT_READINESS_TEXT))

print("Deployment-readiness report preview passed.")
print("Required sections:", len(REQUIRED_REPORT_SECTIONS))
print("Missing sections:", len(MISSING_REPORT_SECTIONS))
print("Unresolved placeholders:", len(FOUND_PLACEHOLDER_TOKENS))
print("Canonical files persisted by this cell: 0")

# Dashboard Deployment-Readiness Report

**Notebook:** `35_dashboard_and_deployment_validation.ipynb`
**Application:** `streamlit_app.py`
**Validated package:** `outputs/34_final_streamlit_dashboard_assets/`
**Assessment:** `conditionally_ready_for_local_demonstration`
**Runtime tested:** Streamlit `1.59.0`
**Deployment pin:** Streamlit `1.56.0`

## 1. Decision

The dashboard is **ready for local supervisor demonstration** in the tested environment.

It is **not yet recorded as a reproducible public deployment**. The application passed all eight runtime page tests, but 4 installed package versions differ from the declared deployment pins and no public deployment URL is recorded.

### What this means

- The dashboard can be used locally to inspect the validated thesis evidence.
- The application does not create restorations or recompute scientific metrics.
- Representative examples support orientation; the complete indexed evidence remains filterable.
- Public-deployment completion should be claimed only after dependency reconciliation and an external deployment check.

## 2. Readiness matrix

| Component | Status | Evidence | Conclusion | Next Action |
| --- | --- | --- | --- | --- |
| Notebook 34 evidence package | ready | 76 package checks passed; 19 physical files validated | The application has a complete, fixed presentation package. | None |
| Indexed evidence access | ready | 1,785 candidates; 50 paintings; 23,964 visual records; 104 reports | Representative defaults do not prevent complete indexed inspection. | None |
| Scientific boundaries | ready | No inference, metric recomputation, combined score, or unsupported claim | The dashboard remains an inspection and decision-support layer. | None |
| Approved UI traceability | ready | 72 of 72 page/aspect mappings passed | The implemented application retains the approved museum-research design. | None |
| Eight-page runtime | ready | 8 pages passed in 13.28s | The current local environment is suitable for supervisor demonstration. | None for local use |
| Portable reports | ready | 104 of 104 reports are self-contained | Downloaded reports retain their required content without repository-relative images. | None |
| Dependency-pin alignment | action_required | 4 package versions differ | The tested environment works, but exact deployment reproducibility is not yet locked. | Recreate the environment from requirements.txt |
| External deployment | not_deployed | No public URL is recorded | Local readiness must not be described as completed public deployment. | Deploy externally, then record the platform and URL |

## 3. Runtime evidence

All eight principal pages rendered without an uncaught exception or visible application error.

| Display Name | Runtime Seconds | Exception Count | Visible Error Count | Passed |
| --- | --- | --- | --- | --- |
| Overview | 4.126 | 0 | 0 | True |
| Study Design | 2.633 | 0 | 0 | True |
| Metric Framework | 0.405 | 0 | 0 | True |
| Model Performance | 0.830 | 0 | 0 | True |
| Robustness & Uncertainty | 0.972 | 0 | 0 | True |
| Trustworthiness & XAI | 2.196 | 0 | 0 | True |
| Case Explorer | 1.762 | 0 | 0 | True |
| Reports & Reproducibility | 0.360 | 0 | 0 | True |

**Runtime conclusion:** the application completed all page transitions in 13.284 seconds. The slowest page was **Overview** at 4.126 seconds. This is suitable for local presentation and interactive inspection.

## 4. Evidence available through the dashboard

- **50 paintings**
- **410 restoration cases**
- **1,785 approved candidates**
- **23,964 indexed visual records**
- **104 self-contained reports**
- **130 canonical repeated-seed uncertainty groups**
- **35 damage-size uncertainty groups**
- **10 bounded SDXL candidates**

The Case Explorer exposes original, damaged, mask, restored, and diagnostic evidence. The Trustworthiness & XAI page also exposes the complete visual catalogue, including supporting prompt-ablation maps that remain separate from the approved candidate index.

## 5. Scientific interpretation limits

- Visual plausibility is not historical correctness, authenticity, conservation approval, or restoration trustworthiness.
- Metrics remain separate by family and region; the application does not create a universal combined score.
- Repeated-seed variation is empirical diffusion uncertainty, not calibrated confidence.
- Mask and degradation sensitivity are robustness evidence, not generative uncertainty.
- Computational flags support review; they are not expert ground truth.
- Retrieval results provide context and do not prove restoration correctness.
- SDXL is a ten-case feasibility study, not a fourth complete benchmark.

**Scientific conclusion:** the dashboard is suitable for evidence inspection and communication. It is not an experiment runner, restoration tool, or conservation decision system.

## 6. Dependency reconciliation

- **pillow:** tested with `9.5.0`; deployment pin is `12.3.0`.
- **plotly:** tested with `6.8.0`; deployment pin is `6.9.0`.
- **pyarrow:** tested with `24.0.0`; deployment pin is `20.0.0`.
- **streamlit:** tested with `1.59.0`; deployment pin is `1.56.0`.

The current environment passed the complete runtime smoke test despite these differences. Exact deployment reproducibility still requires installing the versions declared in `requirements.txt` and repeating the eight-page smoke test.

## 7. External deployment state

No public deployment URL is recorded. The validated result is local application readiness, not completed external deployment.

Before claiming completed external deployment:

1. Create a clean environment from `requirements.txt`.
2. Run `python -m streamlit run streamlit_app.py`.
3. Verify all eight pages and representative downloads.
4. Confirm that repository-indexed assets are available on the deployment host.
5. Record the deployment platform and public URL in the Notebook 35 configuration.
6. Rerun Notebook 35 and persist a new readiness report.

## 8. Local launch

From the repository root:

```text
python -m streamlit run streamlit_app.py
```

The application reads only the fixed Notebook 34 dashboard package. It must not be redirected to legacy global output folders.

## 9. Final conclusion

Local demonstration: ready.
Scientific presentation boundary: passed.
Complete indexed access: passed.

Exact dependency alignment: action required.
External deployment: not deployed.

The current validated outcome is therefore conditional local readiness, not completed public deployment.

Deployment-readiness report preview passed.
Required sections: 10
Missing sections: 0
Unresolved placeholders: 0
Canonical files persisted by this cell: 0

In [34]:
CANONICAL_FILES_AFTER_BATCH = sorted(
    path.relative_to(OUTPUT_ROOT).as_posix()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
)

BATCH_8_FINAL_CHECKS = (
    (
        "readiness_matrix",
        "Every readiness component has a supported status",
        8,
        len(READINESS_MATRIX),
        len(READINESS_MATRIX) == 8,
    ),
    (
        "local_readiness",
        "The application is ready for local demonstration",
        True,
        LOCAL_APPLICATION_READY,
        LOCAL_APPLICATION_READY,
    ),
    (
        "report_contract",
        "Every readiness-report contract check passed",
        len(REPORT_CONTRACT_CHECKS),
        len(REPORT_CONTRACT_CHECKS),
        True,
    ),
    (
        "runtime_rows",
        "The report contains all eight runtime rows",
        8,
        len(PAGE_RUNTIME_REPORT_TABLE),
        len(PAGE_RUNTIME_REPORT_TABLE) == 8,
    ),
    (
        "deployment_status_honesty",
        "Overall status does not overstate external deployment",
        (
            "conditionally_ready_for_local_demonstration"
            if not EXTERNAL_DEPLOYMENT_RECORDED
            else "deployment_validated"
        ),
        OVERALL_READINESS_STATUS,
        (
            OVERALL_READINESS_STATUS
            == (
                "conditionally_ready_for_local_demonstration"
                if not EXTERNAL_DEPLOYMENT_RECORDED
                else "deployment_validated"
            )
        ),
    ),
    (
        "no_canonical_files_written",
        "Batch 8 has not persisted canonical Notebook 35 files",
        [],
        CANONICAL_FILES_AFTER_BATCH,
        not CANONICAL_FILES_AFTER_BATCH,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in BATCH_8_FINAL_CHECKS:
    VALIDATION.add(
        validation_stage="batch_8_final_gate",
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details=(
            ""
            if passed
            else (
                "The readiness decision or report is "
                "not ready for persistence."
            )
        ),
    )

VALIDATION.raise_for_blocking()

VALIDATION_FRAME = VALIDATION.to_dataframe()

BATCH_8_STAGE_SUMMARY = (
    VALIDATION_FRAME[
        VALIDATION_FRAME[
            "validation_stage"
        ].str.startswith("batch_8")
    ]
    .groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
    .reset_index()
)

BATCH_8_STAGE_SUMMARY["failed"] = (
    BATCH_8_STAGE_SUMMARY["checks"]
    - BATCH_8_STAGE_SUMMARY["passed"]
)

display(BATCH_8_STAGE_SUMMARY)

print("Batch 8 deployment-readiness report passed.")
print(
    "Batch 8 checks:",
    len(
        VALIDATION_FRAME[
            VALIDATION_FRAME[
                "validation_stage"
            ].str.startswith("batch_8")
        ]
    ),
)
print("Overall status:", OVERALL_READINESS_STATUS)
print("Blocking failures:", len(VALIDATION.blocking_failures))
print("Canonical files persisted by Batch 8: 0")

             validation_stage  severity  checks  passed  failed
0          batch_8_final_gate  blocking       6       6       0
1  batch_8_readiness_decision  blocking       2       2       0
2  batch_8_readiness_decision      info       1       0       1
3  batch_8_readiness_decision   warning       1       0       1
4     batch_8_report_contract  blocking       9       9       0

Batch 8 deployment-readiness report passed.
Batch 8 checks: 19
Overall status: conditionally_ready_for_local_demonstration
Blocking failures: 0
Canonical files persisted by Batch 8: 0

## Batch 9 — Canonical persistence and completion gate

This final batch persists exactly four Notebook 35 artifacts:

- consolidated dashboard validation;
- deployment-readiness report;
- universal artifact manifest;
- completed run manifest.

The batch then reloads every artifact, verifies checksums and output identity, confirms all roadmap responsibilities, and distinguishes non-blocking deployment warnings from completion failures.

Notebook 35 may complete with documented dependency-alignment and deployment-state warnings. It may not complete with a blocking validation failure or an overstated deployment claim.

In [35]:
from restoration_eval.manifests import (
    ARTIFACT_MANIFEST_SCHEMA_VERSION,
    MANIFESTS_MODULE_VERSION,
    RUN_MANIFEST_SCHEMA_VERSION,
    artifact_records_dataframe,
    build_artifact_record,
    build_run_manifest,
    configuration_checksums,
    sha256_file,
    sha256_path,
    write_artifact_manifest,
    write_run_manifest,
)


ROADMAP_TRACEABILITY = pd.DataFrame(
    [
        {
            "responsibility_id": "n35_r01",
            "responsibility": (
                "Validate every dashboard input path and schema"
            ),
            "evidence": (
                "Batch 2 package, schema, and indexed-path audits"
            ),
            "passed": bool(
                PACKAGE_AUDIT["passed"].all()
                and INDEXED_PATH_AUDIT["passed"].all()
            ),
        },
        {
            "responsibility_id": "n35_r02",
            "responsibility": (
                "Validate asset-manifest completeness"
            ),
            "evidence": (
                "15 asset contracts and 19 physical package files"
            ),
            "passed": bool(
                len(DASHBOARD_ASSETS) == 15
                and ASSET_SCHEMA_AUDIT["passed"].all()
                and ASSET_PATH_AUDIT["passed"].all()
            ),
        },
        {
            "responsibility_id": "n35_r03",
            "responsibility": (
                "Validate case, report, and image links"
            ),
            "evidence": (
                "Batch 3 relationships and 12,480 diagnostic paths"
            ),
            "passed": bool(
                not UNINDEXED_CASE_DIAGNOSTIC_PATHS
                and INDEXED_PATH_AUDIT["passed"].all()
            ),
        },
        {
            "responsibility_id": "n35_r04",
            "responsibility": (
                "Exclude missing legacy global paths"
            ),
            "evidence": (
                "Batch 4 prohibited-source audit"
            ),
            "passed": bool(
                APP_STATIC_AUDIT["passed"].all()
            ),
        },
        {
            "responsibility_id": "n35_r05",
            "responsibility": (
                "Validate controlled scope and scaling labels"
            ),
            "evidence": (
                "Scientific boundaries and bounded runtime evidence"
            ),
            "passed": bool(
                SOURCE_CLAIM_AUDIT["present"].all()
            ),
        },
        {
            "responsibility_id": "n35_r06",
            "responsibility": (
                "Validate model availability handling"
            ),
            "evidence": (
                "Complete model filters and empty-filter fallback"
            ),
            "passed": bool(
                EMPTY_FILTER_RESULT.empty
                and len(MODEL_IDS) == 4
            ),
        },
        {
            "responsibility_id": "n35_r07",
            "responsibility": (
                "Validate missing and optional SDXL behavior"
            ),
            "evidence": (
                "Ten bounded candidates and no numeric uncertainty"
            ),
            "passed": bool(
                len(SDXL_CASES) == 10
                and SDXL_UNCERTAINTY.empty
                and len(
                    SDXL_UNCERTAINTY_BOUNDARY
                ) == 1
            ),
        },
        {
            "responsibility_id": "n35_r08",
            "responsibility": (
                "Validate figure and heatmap references"
            ),
            "evidence": (
                "23,964 visual records and complete path audit"
            ),
            "passed": bool(
                len(VISUAL_INDEX) == 23964
                and INDEXED_PATH_AUDIT[
                    "passed"
                ].all()
            ),
        },
        {
            "responsibility_id": "n35_r09",
            "responsibility": (
                "Validate filter values and ID relationships"
            ),
            "evidence": (
                "Batch 3 exact vocabularies and relationships"
            ),
            "passed": bool(
                FILTER_AUDIT["passed"].all()
                and JSON_FIELD_AUDIT[
                    "passed"
                ].all()
            ),
        },
        {
            "responsibility_id": "n35_r10",
            "responsibility": (
                "Prevent scientific metric recomputation"
            ),
            "evidence": (
                "Read-only static and import boundary audits"
            ),
            "passed": bool(
                not APP_PROHIBITED_IMPORTS
                and not SCIENTIFIC_FUNCTION_DEFINITIONS
            ),
        },
        {
            "responsibility_id": "n35_r11",
            "responsibility": (
                "Run safe import and static checks"
            ),
            "evidence": "Batch 4 static validation",
            "passed": bool(
                APP_STATIC_AUDIT["passed"].all()
            ),
        },
        {
            "responsibility_id": "n35_r12",
            "responsibility": (
                "Run an authorized application smoke test"
            ),
            "evidence": (
                "All eight Streamlit pages passed"
            ),
            "passed": bool(
                PAGE_SMOKE_AUDIT["passed"].all()
            ),
        },
        {
            "responsibility_id": "n35_r13",
            "responsibility": (
                "Record deployment URL and metadata when available"
            ),
            "evidence": (
                "Deployment state explicitly records no deployment"
            ),
            "passed": bool(
                (
                    EXTERNAL_DEPLOYMENT_RECORDED
                    and bool(DEPLOYMENT_URL)
                )
                or (
                    not EXTERNAL_DEPLOYMENT_RECORDED
                    and not DEPLOYMENT_URL
                    and DEPLOYMENT_PLATFORM
                    == "not_deployed"
                )
            ),
        },
        {
            "responsibility_id": "n35_r14",
            "responsibility": (
                "State that the dashboard is not an experiment "
                "or restoration tool"
            ),
            "evidence": (
                "Application and readiness-report boundaries"
            ),
            "passed": bool(
                source_contains(
                    "presentation and decision support only",
                    "no inference or metric recomputation",
                )
                and (
                    "not an experiment runner, restoration tool"
                    in DEPLOYMENT_READINESS_TEXT
                )
            ),
        },
    ]
)

for row in ROADMAP_TRACEABILITY.to_dict(
    "records"
):
    VALIDATION.add(
        validation_stage=(
            "batch_9_roadmap_traceability"
        ),
        check_id=row["responsibility_id"],
        check_description=row["responsibility"],
        severity="blocking",
        expected=True,
        observed=bool(row["passed"]),
        passed=bool(row["passed"]),
        details=row["evidence"],
    )

EXPECTED_CANONICAL_OUTPUT_PATHS = {
    path.resolve()
    for path in OUTPUT_PATHS.values()
}

PERSISTENCE_PREFLIGHT_CHECKS = (
    (
        "roadmap_responsibilities",
        "All fourteen Notebook 35 responsibilities are covered",
        14,
        int(
            ROADMAP_TRACEABILITY[
                "passed"
            ].sum()
        ),
        (
            len(ROADMAP_TRACEABILITY) == 14
            and ROADMAP_TRACEABILITY[
                "passed"
            ].all()
        ),
    ),
    (
        "canonical_output_count",
        "Exactly four canonical outputs are declared",
        4,
        len(EXPECTED_CANONICAL_OUTPUT_PATHS),
        len(EXPECTED_CANONICAL_OUTPUT_PATHS) == 4,
    ),
    (
        "local_application_ready",
        "Local application readiness passed",
        True,
        LOCAL_APPLICATION_READY,
        LOCAL_APPLICATION_READY,
    ),
    (
        "report_ready",
        "The deployment-readiness report passed its contract",
        True,
        not MISSING_REPORT_SECTIONS,
        not MISSING_REPORT_SECTIONS,
    ),
    (
        "no_existing_blocking_failure",
        "No blocking failure exists before persistence",
        0,
        len(VALIDATION.blocking_failures),
        not VALIDATION.blocking_failures,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in PERSISTENCE_PREFLIGHT_CHECKS:
    VALIDATION.add(
        validation_stage=(
            "batch_9_persistence_preflight"
        ),
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details="",
    )

VALIDATION.raise_for_blocking()

display(ROADMAP_TRACEABILITY)

print("Final persistence preflight passed.")
print(
    "Roadmap responsibilities:",
    f"{int(ROADMAP_TRACEABILITY['passed'].sum())}/14",
)
print(
    "Declared canonical outputs:",
    len(EXPECTED_CANONICAL_OUTPUT_PATHS),
)
print("Blocking failures:", len(VALIDATION.blocking_failures))

,responsibility_id,responsibility,evidence,passed
0,n35_r01,Validate every dashboard input path and schema,"Batch 2 package, schema, and indexed-path audits",True
1,n35_r02,Validate asset-manifest completeness,15 asset contracts and 19 physical package files,True
2,n35_r03,"Validate case, report, and image links","Batch 3 relationships and 12,480 diagnostic paths",True
3,n35_r04,Exclude missing legacy global paths,Batch 4 prohibited-source audit,True
4,n35_r05,Validate controlled scope and scaling labels,Scientific boundaries and bounded runtime evid...,True
5,n35_r06,Validate model availability handling,Complete model filters and empty-filter fallback,True
6,n35_r07,Validate missing and optional SDXL behavior,Ten bounded candidates and no numeric uncertainty,True
7,n35_r08,Validate figure and heatmap references,"23,964 visual records and complete path audit",True
8,n35_r09,Validate filter values and ID relationships,Batch 3 exact vocabularies and relationships,True
9,n35_r10,Prevent scientific metric recomputation,Read-only static and import boundary audits,True
10,n35_r11,Run safe import and static checks,Batch 4 static validation,True
11,n35_r12,Run an authorized application smoke test,All eight Streamlit pages passed,True
12,n35_r13,Record deployment URL and metadata when available,Deployment state explicitly records no deployment,True
13,n35_r14,State that the dashboard is not an experiment ...,Application and readiness-report boundaries,True

Final persistence preflight passed.
Roadmap responsibilities: 14/14
Declared canonical outputs: 4
Blocking failures: 0

In [36]:
import os
import uuid


def atomic_write_utf8_text(path, text):
    target = Path(path)
    target.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary = target.with_name(
        f"{target.name}.{uuid.uuid4().hex}.tmp"
    )

    try:
        temporary.write_text(
            text,
            encoding="utf-8",
            newline="\n",
        )
        os.replace(temporary, target)
    finally:
        temporary.unlink(missing_ok=True)

    return target


REPORT_TEXT_TO_WRITE = (
    DEPLOYMENT_READINESS_TEXT.rstrip()
    + "\n"
)

atomic_write_utf8_text(
    OUTPUT_PATHS["deployment_readiness"],
    REPORT_TEXT_TO_WRITE,
)

RELOADED_DEPLOYMENT_REPORT = (
    OUTPUT_PATHS["deployment_readiness"]
    .read_text(encoding="utf-8")
)

REPORT_PERSISTENCE_CHECKS = (
    (
        "report_exists",
        "The deployment-readiness report exists",
        True,
        OUTPUT_PATHS[
            "deployment_readiness"
        ].is_file(),
        OUTPUT_PATHS[
            "deployment_readiness"
        ].is_file(),
    ),
    (
        "report_exact_reload",
        "The report reloads without content changes",
        len(REPORT_TEXT_TO_WRITE),
        len(RELOADED_DEPLOYMENT_REPORT),
        (
            RELOADED_DEPLOYMENT_REPORT
            == REPORT_TEXT_TO_WRITE
        ),
    ),
    (
        "report_nonempty",
        "The persisted report is non-empty",
        ">0",
        OUTPUT_PATHS[
            "deployment_readiness"
        ].stat().st_size,
        (
            OUTPUT_PATHS[
                "deployment_readiness"
            ].stat().st_size
            > 0
        ),
    ),
    (
        "report_status",
        "The persisted report retains conditional local readiness",
        True,
        (
            "conditional local readiness"
            in RELOADED_DEPLOYMENT_REPORT
        ),
        (
            "conditional local readiness"
            in RELOADED_DEPLOYMENT_REPORT
        ),
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in REPORT_PERSISTENCE_CHECKS:
    VALIDATION.add(
        validation_stage=(
            "batch_9_report_persistence"
        ),
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details="",
    )

VALIDATION.raise_for_blocking()

VALIDATION.write_csv(
    OUTPUT_PATHS["dashboard_checks"]
)

RELOADED_DASHBOARD_CHECKS = pd.read_csv(
    OUTPUT_PATHS["dashboard_checks"],
    low_memory=False,
)

RELOADED_CHECK_PASSED = (
    RELOADED_DASHBOARD_CHECKS[
        "passed"
    ]
    .astype(str)
    .str.strip()
    .str.casefold()
    .eq("true")
)

RELOADED_BLOCKING_FAILURES = int(
    (
        ~RELOADED_CHECK_PASSED
        & RELOADED_DASHBOARD_CHECKS[
            "severity"
        ]
        .astype(str)
        .str.casefold()
        .eq("blocking")
    ).sum()
)

if RELOADED_BLOCKING_FAILURES:
    raise RuntimeError(
        "Persisted validation contains blocking failures."
    )

print("Report and provisional validation persisted.")
print(
    "Report bytes:",
    OUTPUT_PATHS[
        "deployment_readiness"
    ].stat().st_size,
)
print(
    "Validation rows:",
    len(RELOADED_DASHBOARD_CHECKS),
)
print(
    "Blocking failures:",
    RELOADED_BLOCKING_FAILURES,
)

Report and provisional validation persisted.
Report bytes: 6525
Validation rows: 572
Blocking failures: 0

In [37]:
MANIFEST_INPUT_PATHS = {
    "configuration.dashboard_validation": CONFIG_PATH,
    "configuration.evidence_coverage": COVERAGE_PATH,
    "governance.implementation_guidelines": (
        IMPLEMENTATION_PATH
    ),
    "governance.notebook_roadmap": ROADMAP_PATH,
    "governance.evidence_dependency_audit": (
        AUDIT_PATH
    ),
    "application.streamlit_entrypoint": APP_PATH,
    "application.dashboard_helper": HELPER_PATH,
    "environment.requirements": REQUIREMENTS_PATH,
    "environment.experiment_requirements": (
        EXPERIMENT_REQUIREMENTS_PATH
    ),
    "inventory.project_file_inventory": INVENTORY_PATH,
    "inventory.inventory_run": INVENTORY_RUN_PATH,
    "inventory.project_paths": PROJECT_PATHS_PATH,
}

for input_key, input_path in (
    REQUIRED_INPUT_PATHS.items()
):
    MANIFEST_INPUT_PATHS[
        f"dashboard_package.{input_key}"
    ] = input_path

MANIFEST_INPUT_RECORDS = [
    {
        "input_key": input_key,
        "relative_path": (
            path.relative_to(
                PROJECT_ROOT
            ).as_posix()
        ),
        "checksum": sha256_path(path),
    }
    for input_key, path in sorted(
        MANIFEST_INPUT_PATHS.items()
    )
]

MANIFEST_OUTPUT_RECORDS = [
    {
        "artifact_key": (
            f"notebook_35.{output_key}"
        ),
        "relative_path": (
            output_path.relative_to(
                PROJECT_ROOT
            ).as_posix()
        ),
        "artifact_type": (
            output_path.suffix
            .lower()
            .lstrip(".")
            or "file"
        ),
    }
    for output_key, output_path in sorted(
        OUTPUT_PATHS.items()
    )
]

CONFIGURATION_CHECKSUMS = (
    configuration_checksums(
        [
            CONFIG_PATH,
            COVERAGE_PATH,
        ],
        PROJECT_ROOT,
    )
)

RUN_COMPLETED_AT_UTC = (
    datetime.now(timezone.utc)
    .isoformat(timespec="seconds")
    .replace("+00:00", "Z")
)

VALIDATION_STATUS = (
    "warning"
    if len(
        VALIDATION.to_dataframe().loc[
            (
                VALIDATION.to_dataframe()[
                    "severity"
                ]
                == "warning"
            )
            & (
                ~VALIDATION.to_dataframe()[
                    "passed"
                ]
            )
        ]
    )
    else "passed"
)


def build_n35_artifact_records():
    validation_rows = len(
        pd.read_csv(
            OUTPUT_PATHS["dashboard_checks"],
            low_memory=False,
        )
    )

    return [
        build_artifact_record(
            artifact_key=(
                "dashboard.deployment_readiness"
            ),
            producer_notebook=NOTEBOOK_STEM,
            path=OUTPUT_PATHS[
                "deployment_readiness"
            ],
            artifact_type=(
                "deployment_readiness_report"
            ),
            artifact_role=(
                "dashboard_deployment_decision"
            ),
            schema_version=OUTPUT_SPEC[
                "deployment_readiness"
            ]["schema_version"],
            dataset_scope=(
                "controlled_50_dashboard_validation"
            ),
            experiment_id=(
                "dashboard_deployment_validation"
            ),
            validation_status=(
                VALIDATION_STATUS
            ),
            project_root=PROJECT_ROOT,
        ),
        build_artifact_record(
            artifact_key="dashboard.validation",
            producer_notebook=NOTEBOOK_STEM,
            path=OUTPUT_PATHS[
                "dashboard_checks"
            ],
            artifact_type="validation_table",
            artifact_role=(
                "consolidated_dashboard_checks"
            ),
            schema_version=OUTPUT_SPEC[
                "dashboard_checks"
            ]["schema_version"],
            dataset_scope=(
                "controlled_50_dashboard_validation"
            ),
            experiment_id=(
                "dashboard_deployment_validation"
            ),
            validation_status=(
                VALIDATION_STATUS
            ),
            row_count=validation_rows,
            project_root=PROJECT_ROOT,
        ),
    ]


ARTIFACT_RECORD_PAYLOADS = (
    build_n35_artifact_records()
)

ARTIFACT_RECORDS = (
    artifact_records_dataframe(
        ARTIFACT_RECORD_PAYLOADS
    )
)

write_artifact_manifest(
    OUTPUT_PATHS["artifacts"],
    ARTIFACT_RECORD_PAYLOADS,
)

RELOADED_ARTIFACT_RECORDS = pd.read_csv(
    OUTPUT_PATHS["artifacts"],
    low_memory=False,
)


EXPECTED_COUNTS = {
    "dashboard_pages": 8,
    "paintings": 50,
    "restoration_cases": 410,
    "approved_candidates": 1785,
    "visual_records": 23964,
    "reports": 104,
    "sdxl_candidates": 10,
    "roadmap_responsibilities": 14,
    "canonical_outputs": 4,
    "artifact_records": 2,
    "dependency_mismatches": 0,
}

OBSERVED_COUNTS = {
    "dashboard_pages": len(PAGE_SMOKE_AUDIT),
    "paintings": len(PAINTING_INDEX),
    "restoration_cases": (
        CASE_INDEX["case_id"].nunique()
    ),
    "approved_candidates": len(CASE_INDEX),
    "visual_records": len(VISUAL_INDEX),
    "reports": len(REPORT_INDEX),
    "sdxl_candidates": len(SDXL_CASES),
    "roadmap_responsibilities": len(
        ROADMAP_TRACEABILITY
    ),
    "canonical_outputs": len(OUTPUT_PATHS),
    "artifact_records": len(
        RELOADED_ARTIFACT_RECORDS
    ),
    "dependency_mismatches": len(
        VERSION_MISMATCHES
    ),
}

MANIFEST_KNOWN_LIMITATIONS = [
    *[
        str(value)
        for value in CONFIG["known_limitations"]
    ],
    *[
        (
            f"{row.package}: tested "
            f"{row.observed_version}, pinned "
            f"{row.target_version}"
        )
        for row in VERSION_MISMATCHES.itertuples(
            index=False
        )
    ],
]


def build_n35_run_manifest(run_id=None):
    validation_summary = VALIDATION.summary()

    manifest = build_run_manifest(
        notebook_id=NOTEBOOK_ID,
        notebook_name=NOTEBOOK_STEM,
        origin="New Notebook",
        run_status="completed",
        started_at_utc=RUN_STARTED_AT_UTC,
        completed_at_utc=RUN_COMPLETED_AT_UTC,
        inventory_run_id=str(
            INVENTORY_RUN["inventory_run_id"]
        ),
        dataset_versions={
            "dataset_scope": "controlled_50",
            "dashboard_package_schema_version": (
                DASHBOARD_PACKAGE_SCHEMA_VERSION
            ),
            "dashboard_validation_schema_version": (
                CONFIG["schema_version"]
            ),
            "dashboard_configuration_version": (
                CONFIG["configuration_version"]
            ),
            "notebook_34_run_id": (
                BUNDLE.upstream_manifest.get(
                    "run_id",
                    "",
                )
            ),
        },
        configuration_paths=[
            CONFIG_PATH.relative_to(
                PROJECT_ROOT
            ).as_posix(),
            COVERAGE_PATH.relative_to(
                PROJECT_ROOT
            ).as_posix(),
        ],
        configuration_checksums_by_path=(
            CONFIGURATION_CHECKSUMS
        ),
        helper_versions={
            "dashboard_application": (
                DASHBOARD_APPLICATION_VERSION
            ),
            "manifests": MANIFESTS_MODULE_VERSION,
            "validation": VALIDATION_MODULE_VERSION,
            "paths": PATHS_MODULE_VERSION,
        },
        inputs=MANIFEST_INPUT_RECORDS,
        outputs=MANIFEST_OUTPUT_RECORDS,
        expected_counts=EXPECTED_COUNTS,
        observed_counts={
            **OBSERVED_COUNTS,
            "validation_rows": (
                validation_summary["check_count"]
            ),
        },
        validation_summary=validation_summary,
        known_limitations=(
            MANIFEST_KNOWN_LIMITATIONS
        ),
        project_root=PROJECT_ROOT,
        package_names=(
            "streamlit",
            "pandas",
            "plotly",
            "numpy",
            "pyarrow",
            "Pillow",
            "PyYAML",
        ),
        hardware={
            "analysis_mode": (
                "dashboard_application_validation"
            ),
            "streamlit_apptest_used": True,
            "tested_page_count": 8,
            "restoration_inference_performed": False,
            "scientific_metric_recomputation_performed": False,
            "external_deployment_performed": (
                EXTERNAL_DEPLOYMENT_RECORDED
            ),
        },
        run_id=run_id,
    )

    manifest.update(
        {
            "validation_status": (
                VALIDATION_STATUS
            ),
            "refactor_status": "refactored",
            "completion_gate_passed": True,
            "creates_new_scientific_evidence": False,
            "local_application_ready": (
                LOCAL_APPLICATION_READY
            ),
            "deployment_readiness_status": (
                OVERALL_READINESS_STATUS
            ),
            "external_deployment_recorded": (
                EXTERNAL_DEPLOYMENT_RECORDED
            ),
            "deployment_platform": (
                DEPLOYMENT_PLATFORM
            ),
            "deployment_url": DEPLOYMENT_URL,
            "dashboard_page_count": 8,
            "artifact_manifest_checksum": (
                sha256_file(
                    OUTPUT_PATHS["artifacts"]
                )
            ),
            "output_checksums": {
                (
                    OUTPUT_PATHS[
                        "deployment_readiness"
                    ]
                    .relative_to(PROJECT_ROOT)
                    .as_posix()
                ): sha256_file(
                    OUTPUT_PATHS[
                        "deployment_readiness"
                    ]
                ),
                (
                    OUTPUT_PATHS[
                        "dashboard_checks"
                    ]
                    .relative_to(PROJECT_ROOT)
                    .as_posix()
                ): sha256_file(
                    OUTPUT_PATHS[
                        "dashboard_checks"
                    ]
                ),
                (
                    OUTPUT_PATHS[
                        "artifacts"
                    ]
                    .relative_to(PROJECT_ROOT)
                    .as_posix()
                ): sha256_file(
                    OUTPUT_PATHS[
                        "artifacts"
                    ]
                ),
            },
        }
    )

    return manifest


PROVISIONAL_RUN_MANIFEST = (
    build_n35_run_manifest()
)

N35_RUN_ID = PROVISIONAL_RUN_MANIFEST[
    "run_id"
]

write_run_manifest(
    OUTPUT_PATHS["run_manifest"],
    PROVISIONAL_RUN_MANIFEST,
)

print("Provisional manifests persisted.")
print(
    "Manifest inputs:",
    len(MANIFEST_INPUT_RECORDS),
)
print(
    "Manifest outputs:",
    len(MANIFEST_OUTPUT_RECORDS),
)
print(
    "Artifact records:",
    len(RELOADED_ARTIFACT_RECORDS),
)
print("Run ID:", N35_RUN_ID)

Provisional manifests persisted.
Manifest inputs: 30
Manifest outputs: 4
Artifact records: 2
Run ID: run_e04d0dfa163b4a15966c5420b01d74c7

In [38]:
OBSERVED_CANONICAL_OUTPUT_PATHS = {
    path.resolve()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
}

TEMPORARY_OUTPUT_FILES = sorted(
    path.relative_to(
        OUTPUT_ROOT
    ).as_posix()
    for path in OBSERVED_CANONICAL_OUTPUT_PATHS
    if (
        ".tmp" in path.name.casefold()
        or ".building" in path.name.casefold()
        or path.suffix.casefold()
        in {
            ".temp",
            ".part",
            ".partial",
        }
        or path.name.startswith(".")
    )
)

with OUTPUT_PATHS["run_manifest"].open(
    "r",
    encoding="utf-8-sig",
) as handle:
    PROVISIONAL_RELOADED_MANIFEST = (
        json.load(handle)
    )

PROVISIONAL_MANIFEST_OUTPUT_PATHS = {
    (
        PROJECT_ROOT
        / str(record["relative_path"])
    ).resolve()
    for record in PROVISIONAL_RELOADED_MANIFEST[
        "outputs"
    ]
}

PROVISIONAL_ARTIFACT_CHECKSUM_FAILURES = []

for row in RELOADED_ARTIFACT_RECORDS.to_dict(
    "records"
):
    artifact_path = (
        PROJECT_ROOT
        / str(row["relative_path"])
    )

    if (
        sha256_path(artifact_path)
        != str(row["checksum"])
    ):
        PROVISIONAL_ARTIFACT_CHECKSUM_FAILURES.append(
            str(row["artifact_key"])
        )

FINAL_COMPLETION_CHECKS = (
    (
        "physical_output_set",
        "The exact four canonical files exist",
        sorted(
            path.relative_to(
                PROJECT_ROOT
            ).as_posix()
            for path in EXPECTED_CANONICAL_OUTPUT_PATHS
        ),
        sorted(
            path.relative_to(
                PROJECT_ROOT
            ).as_posix()
            for path in OBSERVED_CANONICAL_OUTPUT_PATHS
        ),
        (
            OBSERVED_CANONICAL_OUTPUT_PATHS
            == EXPECTED_CANONICAL_OUTPUT_PATHS
        ),
    ),
    (
        "temporary_files",
        "No temporary file remains",
        [],
        TEMPORARY_OUTPUT_FILES,
        not TEMPORARY_OUTPUT_FILES,
    ),
    (
        "artifact_record_count",
        "Exactly two produced artifacts are registered",
        2,
        len(RELOADED_ARTIFACT_RECORDS),
        len(RELOADED_ARTIFACT_RECORDS) == 2,
    ),
    (
        "artifact_checksums",
        "Provisional artifact checksums match",
        [],
        PROVISIONAL_ARTIFACT_CHECKSUM_FAILURES,
        not PROVISIONAL_ARTIFACT_CHECKSUM_FAILURES,
    ),
    (
        "manifest_output_set",
        "The run manifest declares the exact output set",
        sorted(
            path.relative_to(
                PROJECT_ROOT
            ).as_posix()
            for path in EXPECTED_CANONICAL_OUTPUT_PATHS
        ),
        sorted(
            path.relative_to(
                PROJECT_ROOT
            ).as_posix()
            for path in PROVISIONAL_MANIFEST_OUTPUT_PATHS
        ),
        (
            PROVISIONAL_MANIFEST_OUTPUT_PATHS
            == EXPECTED_CANONICAL_OUTPUT_PATHS
        ),
    ),
    (
        "report_exact_content",
        "The persisted report matches its validated text",
        True,
        (
            OUTPUT_PATHS[
                "deployment_readiness"
            ].read_text(encoding="utf-8")
            == REPORT_TEXT_TO_WRITE
        ),
        (
            OUTPUT_PATHS[
                "deployment_readiness"
            ].read_text(encoding="utf-8")
            == REPORT_TEXT_TO_WRITE
        ),
    ),
    (
        "roadmap_completion",
        "All roadmap responsibilities passed",
        14,
        int(
            ROADMAP_TRACEABILITY[
                "passed"
            ].sum()
        ),
        bool(
            ROADMAP_TRACEABILITY[
                "passed"
            ].all()
        ),
    ),
    (
        "runtime_completion",
        "All eight pages passed runtime validation",
        8,
        int(PAGE_SMOKE_AUDIT["passed"].sum()),
        bool(PAGE_SMOKE_AUDIT["passed"].all()),
    ),
    (
        "honest_deployment_state",
        "The deployment status remains conditional",
        (
            "conditionally_ready_for_local_demonstration"
        ),
        OVERALL_READINESS_STATUS,
        (
            OVERALL_READINESS_STATUS
            == (
                "conditionally_ready_for_local_demonstration"
            )
        ),
    ),
    (
        "no_blocking_failures",
        "No blocking validation failure exists",
        0,
        len(VALIDATION.blocking_failures),
        not VALIDATION.blocking_failures,
    ),
)

for (
    check_id,
    description,
    expected,
    observed,
    passed,
) in FINAL_COMPLETION_CHECKS:
    VALIDATION.add(
        validation_stage=(
            "batch_9_completion_gate"
        ),
        check_id=check_id,
        check_description=description,
        severity="blocking",
        expected=expected,
        observed=observed,
        passed=bool(passed),
        details="",
    )

VALIDATION.raise_for_blocking()

# Rewrite validation now that the completion checks are included.
VALIDATION.write_csv(
    OUTPUT_PATHS["dashboard_checks"]
)

# Rebuild artifact records because the validation checksum changed.
ARTIFACT_RECORD_PAYLOADS = (
    build_n35_artifact_records()
)

ARTIFACT_RECORDS = (
    artifact_records_dataframe(
        ARTIFACT_RECORD_PAYLOADS
    )
)

write_artifact_manifest(
    OUTPUT_PATHS["artifacts"],
    ARTIFACT_RECORD_PAYLOADS,
)

RELOADED_ARTIFACT_RECORDS = pd.read_csv(
    OUTPUT_PATHS["artifacts"],
    low_memory=False,
)

# Rebuild the run manifest with the final validation summary
# and final artifact-manifest checksum.
FINAL_RUN_MANIFEST = build_n35_run_manifest(
    run_id=N35_RUN_ID
)

write_run_manifest(
    OUTPUT_PATHS["run_manifest"],
    FINAL_RUN_MANIFEST,
)


# Final independent reload.
FINAL_RELOADED_VALIDATION = pd.read_csv(
    OUTPUT_PATHS["dashboard_checks"],
    low_memory=False,
)

FINAL_RELOADED_ARTIFACTS = pd.read_csv(
    OUTPUT_PATHS["artifacts"],
    low_memory=False,
)

FINAL_RELOADED_REPORT = (
    OUTPUT_PATHS["deployment_readiness"]
    .read_text(encoding="utf-8")
)

with OUTPUT_PATHS["run_manifest"].open(
    "r",
    encoding="utf-8-sig",
) as handle:
    FINAL_RELOADED_MANIFEST = json.load(
        handle
    )

FINAL_OUTPUT_PATHS = {
    path.resolve()
    for path in OUTPUT_ROOT.rglob("*")
    if path.is_file()
}

FINAL_TEMPORARY_FILES = sorted(
    path.relative_to(
        OUTPUT_ROOT
    ).as_posix()
    for path in FINAL_OUTPUT_PATHS
    if (
        ".tmp" in path.name.casefold()
        or path.suffix.casefold()
        in {
            ".temp",
            ".part",
            ".partial",
        }
        or path.name.startswith(".")
    )
)

FINAL_PASSED_VALUES = (
    FINAL_RELOADED_VALIDATION["passed"]
    .astype(str)
    .str.strip()
    .str.casefold()
    .eq("true")
)

FINAL_BLOCKING_FAILURES = int(
    (
        ~FINAL_PASSED_VALUES
        & FINAL_RELOADED_VALIDATION[
            "severity"
        ]
        .astype(str)
        .str.casefold()
        .eq("blocking")
    ).sum()
)

FINAL_WARNING_FAILURES = int(
    (
        ~FINAL_PASSED_VALUES
        & FINAL_RELOADED_VALIDATION[
            "severity"
        ]
        .astype(str)
        .str.casefold()
        .eq("warning")
    ).sum()
)

FINAL_ARTIFACT_CHECKSUM_FAILURES = []

for row in FINAL_RELOADED_ARTIFACTS.to_dict(
    "records"
):
    artifact_path = (
        PROJECT_ROOT
        / str(row["relative_path"])
    )

    if (
        sha256_path(artifact_path)
        != str(row["checksum"])
    ):
        FINAL_ARTIFACT_CHECKSUM_FAILURES.append(
            str(row["artifact_key"])
        )

FINAL_MANIFEST_OUTPUT_PATHS = {
    (
        PROJECT_ROOT
        / str(record["relative_path"])
    ).resolve()
    for record in FINAL_RELOADED_MANIFEST[
        "outputs"
    ]
}

FINAL_COMPLETION_FAILURES = []

if FINAL_OUTPUT_PATHS != EXPECTED_CANONICAL_OUTPUT_PATHS:
    FINAL_COMPLETION_FAILURES.append(
        "physical output identity"
    )

if len(FINAL_OUTPUT_PATHS) != 4:
    FINAL_COMPLETION_FAILURES.append(
        "physical output count"
    )

if FINAL_TEMPORARY_FILES:
    FINAL_COMPLETION_FAILURES.append(
        "temporary files"
    )

if FINAL_BLOCKING_FAILURES:
    FINAL_COMPLETION_FAILURES.append(
        "blocking validation failures"
    )

if len(FINAL_RELOADED_ARTIFACTS) != 2:
    FINAL_COMPLETION_FAILURES.append(
        "artifact record count"
    )

if FINAL_ARTIFACT_CHECKSUM_FAILURES:
    FINAL_COMPLETION_FAILURES.append(
        "artifact checksums"
    )

if (
    FINAL_MANIFEST_OUTPUT_PATHS
    != EXPECTED_CANONICAL_OUTPUT_PATHS
):
    FINAL_COMPLETION_FAILURES.append(
        "manifest output identity"
    )

if (
    FINAL_RELOADED_REPORT
    != REPORT_TEXT_TO_WRITE
):
    FINAL_COMPLETION_FAILURES.append(
        "report content"
    )

if (
    FINAL_RELOADED_MANIFEST[
        "run_status"
    ]
    != "completed"
):
    FINAL_COMPLETION_FAILURES.append(
        "run status"
    )

if (
    FINAL_RELOADED_MANIFEST[
        "completion_gate_passed"
    ]
    is not True
):
    FINAL_COMPLETION_FAILURES.append(
        "manifest completion gate"
    )

if (
    FINAL_RELOADED_MANIFEST[
        "local_application_ready"
    ]
    is not True
):
    FINAL_COMPLETION_FAILURES.append(
        "local readiness"
    )

if (
    FINAL_RELOADED_MANIFEST[
        "external_deployment_recorded"
    ]
    is not False
):
    FINAL_COMPLETION_FAILURES.append(
        "external deployment state"
    )

if (
    int(
        FINAL_RELOADED_MANIFEST[
            "validation_summary"
        ]["check_count"]
    )
    != len(FINAL_RELOADED_VALIDATION)
):
    FINAL_COMPLETION_FAILURES.append(
        "manifest validation count"
    )

if (
    FINAL_RELOADED_MANIFEST[
        "artifact_manifest_checksum"
    ]
    != sha256_file(
        OUTPUT_PATHS["artifacts"]
    )
):
    FINAL_COMPLETION_FAILURES.append(
        "artifact manifest checksum"
    )

if FINAL_COMPLETION_FAILURES:
    raise RuntimeError(
        "Notebook 35 completion gate failed: "
        + ", ".join(
            FINAL_COMPLETION_FAILURES
        )
    )

print("Final persistence and checksum verification passed.")
print("Physical output files:", len(FINAL_OUTPUT_PATHS))
print("Validation rows:", len(FINAL_RELOADED_VALIDATION))
print("Blocking failures:", FINAL_BLOCKING_FAILURES)
print("Warning failures:", FINAL_WARNING_FAILURES)
print("Artifact records:", len(FINAL_RELOADED_ARTIFACTS))

Final persistence and checksum verification passed.
Physical output files: 4
Validation rows: 582
Blocking failures: 0
Warning failures: 7
Artifact records: 2

In [39]:
FINAL_STAGE_PROFILE = (
    FINAL_RELOADED_VALIDATION.groupby(
        ["validation_stage", "severity"],
        dropna=False,
    )
    .agg(
        checks=("check_id", "size"),
        passed=(
            "passed",
            lambda values: int(
                values.astype(str)
                .str.strip()
                .str.casefold()
                .eq("true")
                .sum()
            ),
        ),
    )
    .reset_index()
)

FINAL_STAGE_PROFILE["failed"] = (
    FINAL_STAGE_PROFILE["checks"]
    - FINAL_STAGE_PROFILE["passed"]
)

FINAL_OUTPUT_PROFILE = pd.DataFrame(
    [
        {
            "relative_path": (
                path.relative_to(
                    PROJECT_ROOT
                ).as_posix()
            ),
            "format": (
                path.suffix
                .lower()
                .lstrip(".")
                or "file"
            ),
            "size_bytes": int(
                path.stat().st_size
            ),
            "sha256": sha256_file(path),
        }
        for path in sorted(
            FINAL_OUTPUT_PATHS,
            key=lambda value: value.as_posix(),
        )
    ]
)

FINAL_NOTEBOOK_SUMMARY = pd.DataFrame(
    [
        {
            "completion_item": "dashboard pages",
            "observed": int(
                PAGE_SMOKE_AUDIT[
                    "passed"
                ].sum()
            ),
            "expected": 8,
            "passed": bool(
                PAGE_SMOKE_AUDIT[
                    "passed"
                ].all()
            ),
        },
        {
            "completion_item": "roadmap responsibilities",
            "observed": int(
                ROADMAP_TRACEABILITY[
                    "passed"
                ].sum()
            ),
            "expected": 14,
            "passed": bool(
                ROADMAP_TRACEABILITY[
                    "passed"
                ].all()
            ),
        },
        {
            "completion_item": "canonical files",
            "observed": len(
                FINAL_OUTPUT_PATHS
            ),
            "expected": 4,
            "passed": (
                len(FINAL_OUTPUT_PATHS) == 4
            ),
        },
        {
            "completion_item": "artifact records",
            "observed": len(
                FINAL_RELOADED_ARTIFACTS
            ),
            "expected": 2,
            "passed": (
                len(
                    FINAL_RELOADED_ARTIFACTS
                )
                == 2
            ),
        },
        {
            "completion_item": "blocking failures",
            "observed": FINAL_BLOCKING_FAILURES,
            "expected": 0,
            "passed": (
                FINAL_BLOCKING_FAILURES == 0
            ),
        },
        {
            "completion_item": "local readiness",
            "observed": (
                LOCAL_APPLICATION_READY
            ),
            "expected": True,
            "passed": (
                LOCAL_APPLICATION_READY
            ),
        },
        {
            "completion_item": "external deployment",
            "observed": (
                EXTERNAL_DEPLOYMENT_RECORDED
            ),
            "expected": False,
            "passed": (
                not EXTERNAL_DEPLOYMENT_RECORDED
            ),
        },
    ]
)

display(FINAL_NOTEBOOK_SUMMARY)
display(FINAL_STAGE_PROFILE)
display(FINAL_OUTPUT_PROFILE)
display(FINAL_RELOADED_ARTIFACTS)
display(ROADMAP_TRACEABILITY)

print("Notebook 35 completion gate passed.")
print(
    "Run ID:",
    FINAL_RELOADED_MANIFEST["run_id"],
)
print(
    "Run status:",
    FINAL_RELOADED_MANIFEST["run_status"],
)
print(
    "Validation status:",
    FINAL_RELOADED_MANIFEST[
        "validation_status"
    ],
)
print(
    "Deployment readiness:",
    FINAL_RELOADED_MANIFEST[
        "deployment_readiness_status"
    ],
)
print(
    "Local application ready:",
    FINAL_RELOADED_MANIFEST[
        "local_application_ready"
    ],
)
print(
    "External deployment recorded:",
    FINAL_RELOADED_MANIFEST[
        "external_deployment_recorded"
    ],
)
print(
    "Completion gate:",
    FINAL_RELOADED_MANIFEST[
        "completion_gate_passed"
    ],
)
print(
    "Canonical files:",
    f"{len(FINAL_OUTPUT_PATHS)}/4",
)
print(
    "Roadmap responsibilities:",
    f"{int(ROADMAP_TRACEABILITY['passed'].sum())}/14",
)
print("Notebook 35 is complete.")

            completion_item observed expected  passed
0           dashboard pages        8        8    True
1  roadmap responsibilities       14       14    True
2           canonical files        4        4    True
3          artifact records        2        2    True
4         blocking failures        0        0    True
5           local readiness     True     True    True
6       external deployment    False    False    True

                     validation_stage  severity  checks  passed  failed
0                    batch_1_contract  blocking      15      15       0
1                batch_1_dependencies  blocking       6       6       0
2         batch_1_dependency_versions   warning       7       3       4
3             batch_1_final_preflight  blocking       1       1       0
4        batch_1_inventory_governance  blocking      11      11       0
5             batch_2_asset_contracts  blocking      15      15       0
6             batch_2_asset_integrity  blocking      15      15       0
7           batch_2_dataframe_schemas  blocking      13      13       0
8                  batch_2_final_gate  blocking       5       5       0
9      batch_2_json_and_run_contracts  blocking       6       6       0
10          batch_2_package_integrity  blocking       7       7       0
11         batch_3_core_relationships  blocking      16      16       0
12        batch_3_filter_vocabularies  blocking      13      13       0
13                 batch_3_final_gate  blocking       7       7       0
14                batch_3_json_fields  blocking      15      15       0
15       batch_3_visual_relationships  blocking      14      14       0
16     batch_4_application_boundaries  blocking       1       1       0
17          batch_4_application_pages  blocking       8       8       0
18         batch_4_application_static  blocking       9       9       0
19                 batch_4_final_gate  blocking       6       6       0
20        batch_4_inspection_controls  blocking      10      10       0
21  batch_4_interpretation_boundaries  blocking      11      11       0
22          batch_4_source_boundaries  blocking      11      11       0
23            batch_5_content_balance  blocking       6       6       0
24                 batch_5_final_gate  blocking       7       7       0
25          batch_5_mock_traceability  blocking      72      72       0
26             batch_5_page_contracts  blocking       8       8       0
27         batch_5_reference_boundary  blocking       5       5       0
28         batch_5_reference_boundary   warning       1       1       0
29            batch_5_visual_language  blocking      13      13       0
30                 batch_6_final_gate  blocking       6       6       0
31             batch_6_safe_fallbacks  blocking      13      13       0
32                 batch_6_sdxl_scope  blocking      21      21       0
33          batch_6_visible_fallbacks  blocking      10      10       0
34                 batch_7_final_gate  blocking       6       6       0
35                 batch_7_final_gate   warning       1       0       1
36             batch_7_runtime_global  blocking       9       9       0
37              batch_7_runtime_pages  blocking      40      40       0
38          batch_7_runtime_preflight  blocking       6       6       0
39          batch_7_runtime_preflight   warning       1       0       1
40                 batch_8_final_gate  blocking       6       6       0
41         batch_8_readiness_decision  blocking       2       2       0
42         batch_8_readiness_decision      info       1       0       1
43         batch_8_readiness_decision   warning       1       0       1
44            batch_8_report_contract  blocking       9       9       0
45            batch_9_completion_gate  blocking      10      10       0
46      batch_9_persistence_preflight  blocking       5       5       0
47         batch_9_report_persistence  blocking       4       4       0
48       batch_9_roadmap_traceability  blocking      14      14       0
49                      indexed_paths  blocking       7       7       0
50                      package_paths  blocking      18      18       0
51                 package_population  blocking      11      11       0
52                       package_rows  blocking      15      15       0
53                     package_schema  blocking      16      16       0
54                      package_scope  blocking       1       1       0
55                     package_status  blocking      14      14       0
56                upstream_validation  blocking       1       1       0

,relative_path,format,size_bytes,sha256
0,outputs/35_dashboard_and_deployment_validation...,csv,1010,463353e3b7267a5630067bbebb634551234201fb1dc50e...
1,outputs/35_dashboard_and_deployment_validation...,json,13294,be072144cade45550a32f61aef27c2aa5517ca51f9084e...
2,outputs/35_dashboard_and_deployment_validation...,md,6525,d98e0a5aaf1d45480fd80396161cd6612f771532cc9a20...
3,outputs/35_dashboard_and_deployment_validation...,csv,129692,f1ea933fb69e269daf4f128207f352231477c63b67e2eb...

,artifact_id,artifact_key,producer_notebook,artifact_type,artifact_role,relative_path,format,dataset_scope,experiment_id,schema_version,row_count,file_count,size_bytes,checksum,validation_status
0,artifact_bbed200bcdea162772bd,dashboard.deployment_readiness,35_dashboard_and_deployment_validation,deployment_readiness_report,dashboard_deployment_decision,outputs/35_dashboard_and_deployment_validation...,md,controlled_50_dashboard_validation,dashboard_deployment_validation,deployment_readiness_report.v1,NaN,1,6525,d98e0a5aaf1d45480fd80396161cd6612f771532cc9a20...,warning
1,artifact_4863799c59e55726be9f,dashboard.validation,35_dashboard_and_deployment_validation,validation_table,consolidated_dashboard_checks,outputs/35_dashboard_and_deployment_validation...,csv,controlled_50_dashboard_validation,dashboard_deployment_validation,validation_checks.v1,582.0,1,129692,f1ea933fb69e269daf4f128207f352231477c63b67e2eb...,warning

,responsibility_id,responsibility,evidence,passed
0,n35_r01,Validate every dashboard input path and schema,"Batch 2 package, schema, and indexed-path audits",True
1,n35_r02,Validate asset-manifest completeness,15 asset contracts and 19 physical package files,True
2,n35_r03,"Validate case, report, and image links","Batch 3 relationships and 12,480 diagnostic paths",True
3,n35_r04,Exclude missing legacy global paths,Batch 4 prohibited-source audit,True
4,n35_r05,Validate controlled scope and scaling labels,Scientific boundaries and bounded runtime evid...,True
5,n35_r06,Validate model availability handling,Complete model filters and empty-filter fallback,True
6,n35_r07,Validate missing and optional SDXL behavior,Ten bounded candidates and no numeric uncertainty,True
7,n35_r08,Validate figure and heatmap references,"23,964 visual records and complete path audit",True
8,n35_r09,Validate filter values and ID relationships,Batch 3 exact vocabularies and relationships,True
9,n35_r10,Prevent scientific metric recomputation,Read-only static and import boundary audits,True
10,n35_r11,Run safe import and static checks,Batch 4 static validation,True
11,n35_r12,Run an authorized application smoke test,All eight Streamlit pages passed,True
12,n35_r13,Record deployment URL and metadata when available,Deployment state explicitly records no deployment,True
13,n35_r14,State that the dashboard is not an experiment ...,Application and readiness-report boundaries,True

Notebook 35 completion gate passed.
Run ID: run_e04d0dfa163b4a15966c5420b01d74c7
Run status: completed
Validation status: warning
Deployment readiness: conditionally_ready_for_local_demonstration
Local application ready: True
External deployment recorded: False
Completion gate: True
Canonical files: 4/4
Roadmap responsibilities: 14/14
Notebook 35 is complete.