# 36 — Supervisor, Publication, and Reproducibility Package

**Origin:** Consolidates Existing Previous Versions of Notebooks 30 and 35, Pre-refactor  
**Refactor status:** Finished                         
**Validation status:** Finished                       
**Completion gate passed:** Yes                            
**Output root:** `outputs/36_supervisor_publication_reproducibility_package/`  
**Depends on:** N01–N35, including N12A; supplemental D02; separate D01 decision evidence

## Purpose

Assemble a portable review package from the completed Controlled-300 evidence.
This notebook packages, indexes and verifies existing results. It performs no
restoration inference, scientific metric recomputation or new statistical testing.

## Evidence population

- 300 paintings and 3,425 registered experimental cases.
- 2,620 restoration-eligible cases and 10,480 matched primary candidates.
- 13,879 retained report candidates, distinct from all executed candidates.
- Four full-scope methods: Telea, LaMa, HINT and Stable Diffusion.
- SDXL: 24 completed candidates from a bounded 35-case schedule.
- 11 separate quality anchors and 1,025 supported repeated-seed groups.
- Five model cards, five model reports, 30 detailed case reports and 300 painting reports.
- 18 thesis figures and six publication figures.
- 38 upstream manifests: N01–N35, N12A, D02 and D01's original manifest ID 37.

D01 remains separate 12-case method-selection evidence. D02 remains a focused
portrait audit. Neither is pooled into the main benchmark.

## Package and interpretation boundaries

The package includes selected reports, figures, compact tables, configurations,
run manifests, provenance and application-source snapshots. Large image,
candidate and report collections remain indexed rather than duplicated.
This is a review bundle, not a complete runnable application clone.

Preserve the N29 historical manifest discrepancy and N35's accepted limitations:
14 warning nonpasses, unmeasured qualifications and the documented notebook-source
mismatch. Packaging does not convert these into passed scientific or deployment tests.

Controlled synthetic damage does not establish real conservation generality.
Seed variability is not calibrated confidence; computational flags are not expert
judgement; visual plausibility is not historical correctness or conservation approval.

## Canonical outputs

- `reports/supervisor_summary.md`
- `reports/reproducibility_appendix.md`
- `reports/limitations_and_deviations.md`
- `data/artifact_index.csv`
- `data/key_findings.json`
- `data/open_questions.md`
- `data/feedback_agenda.md`
- `package/`, including its README and provenance snapshot
- `manifests/package_manifest.json`
- `manifests/run_manifest.json`
- `manifests/artifacts.csv`
- `validation/checks.csv`

The principal standalone summary is `reports/supervisor_summary.md`.
Existing self-contained HTML reports are copied without rewriting their evidence.

## Execution plan

Nine batches: preflight; upstream audit; synthesis; supervisor documents;
reproducibility; assembly; indexes/manifests; portability; final completion.

Batches 1–3 are read-only and preserve the historical N36 output tree.
Later batches use isolated staging before verified promotion.

## Batch 1 — Contract, environment and inventory preflight

Load the Controlled-300 package contract, verify inventory health and prepare
the bounded copy plan. Record source hashes and a snapshot of the historical
N36 outputs without creating or replacing canonical files.

The package must remain below the existing 50 MiB ceiling. Its source snapshots
are for traceability, not a claim that the review bundle can run the dashboard.

In [1]:
import ast
import hashlib
import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path
from time import perf_counter

import pandas as pd
import yaml
from IPython.display import display

ROOT = next(p for p in (Path.cwd().resolve(), *Path.cwd().resolve().parents)
            if (p / "config/evaluation/supervisor_package.yaml").is_file()
            and (p / "src/restoration_eval").is_dir())
sys.path.insert(0, str(ROOT / "src"))

from restoration_eval.manifests import sha256_file, sha256_path
from restoration_eval.paths import validate_project_paths_registry
from restoration_eval.supervisor_package import (
    build_copy_plan, copy_plan_frame, load_supervisor_package_config,
    output_paths, required_input_paths, safe_repo_path,
)
from restoration_eval.validation import ValidationCollector

CHECK_LOG, SOURCE_LOCK = {}, {}
RUN_STARTED_AT_UTC = datetime.now(timezone.utc).isoformat()

def check(key, ok, observed="", severity="blocking"):
    stage, name = key.split("/", 1)
    CHECK_LOG[key] = dict(
        validation_stage=stage, check_id=name, check_description=name,
        severity=severity, expected=True, observed=observed,
        passed=bool(ok), details="")
    if not ok and severity in {"blocking", "error"}:
        raise RuntimeError(f"{key}: {observed}")

def path(value):
    return safe_repo_path(value, ROOT, must_exist=True)

def lock_file(value):
    p = path(value)
    rel = p.relative_to(ROOT).as_posix()
    digest = sha256_file(p)
    if rel in SOURCE_LOCK and SOURCE_LOCK[rel] != digest:
        raise RuntimeError(f"Source changed during this run: {rel}")
    SOURCE_LOCK[rel] = digest
    return p

def read_json(value):
    return json.loads(lock_file(value).read_text(encoding="utf-8-sig"))

def read_table(value):
    return pd.read_csv(lock_file(value), keep_default_na=False)

def tree_snapshot(folder):
    return {p.relative_to(folder).as_posix(): sha256_file(p)
            for p in sorted(folder.rglob("*")) if p.is_file()}

CONFIG = load_supervisor_package_config(ROOT)
lock_file("config/evaluation/supervisor_package.yaml")
check("b1/configuration", CONFIG["configuration_version"] == "2.0.0"
      and CONFIG["dataset_scope"] == "controlled_300")
check("b1/python", platform.python_version().startswith("3.12."),
      platform.python_version())
ast.parse(path("src/restoration_eval/supervisor_package.py").read_text(encoding="utf-8"))
lock_file("src/restoration_eval/supervisor_package.py")
OUTPUT_ROOT = ROOT / CONFIG["notebook"]["output_root"]
OUTPUT_PATHS = output_paths(CONFIG, ROOT)
HISTORICAL_OUTPUT_SNAPSHOT = tree_snapshot(OUTPUT_ROOT)
print("Historical N36 files preserved:", len(HISTORICAL_OUTPUT_SNAPSHOT))
print("No directories or canonical files created.")

Historical N36 files preserved: 0
No directories or canonical files created.

In [2]:
REQUIRED_INPUTS = required_input_paths(CONFIG, ROOT)
INVENTORY_RUN = read_json(CONFIG["governing_inputs"]["inventory_run"])
summary = INVENTORY_RUN["summary"]
check("b1/inventory_errors",
      summary["read_error_count"] == 0 and summary["read_error_file_count"] == 0,
      summary["read_error_count"])
check("b1/inventory_status", INVENTORY_RUN["status"] == "completed")
check("b1/inventory_root", Path(INVENTORY_RUN["repository_root"]).resolve() == ROOT)

INVENTORY = pd.read_csv(
    lock_file(CONFIG["governing_inputs"]["inventory_csv"]),
    usecols=["relative_path", "read_error_count"], keep_default_na=False)
REGISTRY = read_json(CONFIG["governing_inputs"]["project_paths_json"])
check("b1/registry_schema", not validate_project_paths_registry(REGISTRY))

COPY_PLAN = build_copy_plan(CONFIG, ROOT)
COPY_PLAN_TABLE = copy_plan_frame(COPY_PLAN, ROOT)
needed = {i.source.relative_to(ROOT).as_posix() for i in COPY_PLAN}
needed.update(CONFIG["evidence_inputs"].values())
needed.update(["config/evaluation/supervisor_package.yaml",
               "config/evaluation/evidence_coverage.yaml"])
check("b1/indexed_sources", needed <= set(INVENTORY.relative_path),
      sorted(needed - set(INVENTORY.relative_path)))
check("b1/indexed_source_errors",
      pd.to_numeric(INVENTORY.loc[INVENTORY.relative_path.isin(needed),
                                   "read_error_count"]).eq(0).all())
check("b1/destinations",
      COPY_PLAN_TABLE.destination_path.is_unique
      and all(i.destination.resolve().is_relative_to(OUTPUT_ROOT.resolve())
              for i in COPY_PLAN))
check("b1/path_lengths",
      COPY_PLAN_TABLE.destination_path.str.len().max()
      <= CONFIG["package_policy"]["maximum_relative_path_characters"])
check("b1/copy_budget",
      int(COPY_PLAN_TABLE.size_bytes.sum())
      < CONFIG["package_policy"]["maximum_package_size_mib"] * 1024**2,
      round(COPY_PLAN_TABLE.size_bytes.sum() / 1024**2, 3))
for source in sorted(needed | {
        p.relative_to(ROOT).as_posix() for p in REQUIRED_INPUTS.values()
        if p.is_file()}):
    lock_file(source)
display(COPY_PLAN_TABLE.groupby("group").agg(
    files=("source_path", "size"), bytes=("size_bytes", "sum")))
print("Batch 1 passed; planned copy inputs:", len(COPY_PLAN))
print("Package is a review bundle, not a runnable application clone.")

                     files     bytes
group
application              2    239388
configuration           26    608416
environment              2      2142
manifests               38    930840
model_cards              5     51404
provenance               3    146441
publication_figures      6    869160
reports                  7  28348672
tables                   8   2338458
thesis_figures          18   1818165

Batch 1 passed; planned copy inputs: 115
Package is a review bundle, not a runnable application clone.

## Batch 2 — Upstream completion, integrity and provenance

Audit all 38 declared manifests using their actual completion contracts.
Nested validation summaries must explicitly report zero blocking failures.
N35 is checked against its accepted closeout, not an invented legacy gate field.

Verify the selected package-input groups against producer artifact checksums.
Retain the precise N29 metadata exception while independently verifying its six
payload groups. Preserve N35's 14 warning nonpasses and accepted source mismatch.

A missing historical run-level ledger checksum is reported as not declared,
not as a successful hash comparison. New or different mismatches remain blocking.

This batch does not rerun upstream notebooks, sweep the deployed website,
download remote collections or write canonical N36 outputs.

In [3]:
def blocking_counts(value):
    found = []
    if isinstance(value, dict):
        for key, child in value.items():
            if key in {"blocking_failure_count", "blocking_failures"}:
                found.append(int(child))
            else:
                found.extend(blocking_counts(child))
    elif isinstance(value, list):
        for child in value:
            found.extend(blocking_counts(child))
    return found

RAW_RUNS, ARTIFACT_LEDGERS, UPSTREAM_ROWS = {}, {}, []
for rel in CONFIG["upstream_run_manifests"]:
    run = read_json(rel)
    nid = str(run["notebook_id"])
    check(f"b2/unique_{nid}", nid not in RAW_RUNS)
    check(f"b2/completed_{nid}", run["run_status"] == "completed")
    counts = blocking_counts(run.get("validation_summary", {}))
    check(f"b2/blocking_summary_{nid}", bool(counts) and all(x == 0 for x in counts),
          counts)
    gate = (run.get("closeout", {}).get("n35_delivery_complete") is True
            and run.get("closeout", {}).get("n36_may_start") is True
            if nid == "35" else run.get("completion_gate_passed") is True)
    check(f"b2/completion_basis_{nid}", gate)
    for out in run.get("outputs", []):
        path(out.get("relative_path", out.get("path", "")))
    ledger_path = path(rel).with_name("artifacts.csv")
    ledger = read_table(ledger_path)
    check(f"b2/artifact_keys_{nid}", ledger.artifact_key.is_unique)
    for out in ledger.itertuples(index=False):
        path(out.relative_path)
    recorded = run.get("artifact_manifest_checksum")
    actual = sha256_file(ledger_path)
    if recorded and nid != "29":
        check(f"b2/ledger_hash_{nid}", actual == recorded)
    RAW_RUNS[nid], ARTIFACT_LEDGERS[nid] = run, ledger
    UPSTREAM_ROWS.append(dict(
        notebook_id=nid, run_id=run["run_id"], run_status=run["run_status"],
        completion_basis="accepted_closeout" if nid == "35" else "producer_gate",
        ledger_hash_state=("historical_exception" if nid == "29" else
                           "matched" if recorded else "not_declared_by_producer"),
        manifest_path=rel))

UPSTREAM = pd.DataFrame(UPSTREAM_ROWS)
expected_ids = {f"{i:02d}" for i in range(1, 36)} | {"12A", "D02", "37"}
check("b2/upstream_population", set(RAW_RUNS) == expected_ids
      and len(UPSTREAM) == CONFIG["expected_population"]["upstream_notebooks"])
check("b2/unique_run_ids", UPSTREAM.run_id.is_unique)
check("b2/d01_scope", RAW_RUNS["37"]["dataset_versions"]["dataset_scope"]
      == "controlled_50_method_selection_pilot")
display(UPSTREAM)
print("38 completed manifests; D01/37 remains separate decision evidence.")

,notebook_id,run_id,run_status,completion_basis,ledger_hash_state,manifest_path
0,01,run_49a7e3c485394878ab4323ce661f3ef5,completed,producer_gate,not_declared_by_producer,outputs/01_dataset_verification/manifests/run_...
1,02,run_ca94012bb1e54bf5bf57c1fdabb01480,completed,producer_gate,not_declared_by_producer,outputs/02_image_preprocessing/manifests/run_m...
2,03,run_dd51e1b1ca374f3aad16d22b0cd12c99,completed,producer_gate,not_declared_by_producer,outputs/03_canonical_mask_generation/manifests...
3,04,run_92d2030511e14f108bd9ef46f8c3110a,completed,producer_gate,not_declared_by_producer,outputs/04_canonical_damaged_image_generation/...
4,05,run_fb717ad978394227944ef6bf99919f08,completed,producer_gate,not_declared_by_producer,outputs/05_damage_size_sensitivity_dataset_gen...
5,06,run_cd2601a25a2d4794aba0745ec6beed5c,completed,producer_gate,not_declared_by_producer,outputs/06_mask_robustness_dataset_generation/...
6,07,run_ad90292d5fb8462eb6241b8123a779d6,completed,producer_gate,not_declared_by_producer,outputs/07_synthetic_degradation_dataset_gener...
7,08,run_b83466f07ebb4b55928229587922334a,completed,producer_gate,not_declared_by_producer,outputs/08_experiment_contracts_and_region_pol...
8,09,run_350786ea88014b67b0cf9efec7fac23c,completed,producer_gate,not_declared_by_producer,outputs/09_opencv_telea_restoration/manifests/...
9,10,run_6f81083a17804d36b1495e4932db4e03,completed,producer_gate,not_declared_by_producer,outputs/10_lama_restoration/manifests/run_mani...
10,11,run_4385124a0cca4d758d357de654a33f13,completed,producer_gate,not_declared_by_producer,outputs/11_stable_diffusion_restoration/manife...
11,12,run_1f7af9d329354a56b4275c4af3cd3f75,completed,producer_gate,not_declared_by_producer,outputs/12_sdxl_feasibility_or_restoration/man...
12,12A,run_f6c9353c31ce4ed9be5e5502571d635d,completed,producer_gate,not_declared_by_producer,outputs/12a_hint_restoration/manifests/run_man...
13,13,run_41b9c87a3c034f19b6f28868127b3c89,completed,producer_gate,not_declared_by_producer,outputs/13_classical_metrics/manifests/run_man...
14,14,run_27cb11ae9aa94133ad474b2f38cab122,completed,producer_gate,not_declared_by_producer,outputs/14_lpips_metrics/manifests/run_manifes...
15,15,run_50c1bb5f25b44111a76df998329d69ed,completed,producer_gate,not_declared_by_producer,outputs/15_feature_similarity/manifests/run_ma...
16,16,run_99b0d8d1af1b43bd8e8cb3d6ae754868,completed,producer_gate,not_declared_by_producer,outputs/16_difference_maps_and_spatial_diagnos...
17,17,run_ed15508895b542e6ac0733c49704ad26,completed,producer_gate,not_declared_by_producer,outputs/17_local_consistency_metrics/manifests...
18,18,run_7c1d7195ed8447c1a878259360b1f5f2,completed,producer_gate,matched,outputs/18_diffusion_uncertainty_analysis/mani...
19,19,run_7384c7fb8d4c4efe98264a660ac12a75,completed,producer_gate,matched,outputs/19_uncertainty_and_spatial_explanation...
20,20,run_8c94e988fd4c4d7cae0acd8c3a64fbe6,completed,producer_gate,matched,outputs/20_semantic_and_structural_consistency...
21,21,run_86f7f46183634889aa050ee2a9f33b56,completed,producer_gate,matched,outputs/21_multi_model_comparison/manifests/ru...
22,22,run_d0276a6859f74fada266936f43b7499f,completed,producer_gate,matched,outputs/22_damage_size_diffusion_uncertainty_e...
23,23,run_e93288fc3ac847ccb699241b4b4c8be0,completed,producer_gate,matched,outputs/23_damage_size_sensitivity_analysis/ma...
24,24,run_bbf68684c3ca47e5827c2b8b4b666351,completed,producer_gate,matched,outputs/24_mask_robustness_analysis/manifests/...
25,25,run_cf89ebe972364c7b8ccfefc6bf2a63ca,completed,producer_gate,matched,outputs/25_synthetic_degradation_analysis/mani...
26,26,run_efc978dd6d504cdb9b138a750f6dca83,completed,producer_gate,matched,outputs/26_grouped_and_statistical_analysis/ma...
27,27,run_bef567ee35c1409dbcecfb71f1b4f8b4,completed,producer_gate,matched,outputs/27_failure_taxonomy_and_trustworthines...
28,28,run_4325bb483fbc4ccda670df125c40731d,completed,producer_gate,matched,outputs/28_metric_and_region_policy_ablation/m...
29,29,run_ad7603b6bdb14156a140351f6ac1f241,completed,producer_gate,historical_exception,outputs/29_explainable_ai_and_case_retrieval/m...
30,30,run_605de239145a46e9a202fd63bbbb4e9c,completed,producer_gate,matched,outputs/30_model_cards_compute_and_scalability...
31,31,run_430fd1355d3a4011bedc55b571d9544c,completed,producer_gate,matched,outputs/31_model_report_generation/manifests/r...
32,32,run_0d4ae193602944dda511bf54199105b1,completed,producer_gate,matched,outputs/32_case_and_painting_report_generation...
33,33,run_aef04267c2e44495a4e7a6249426bd4d,completed,producer_gate,matched,outputs/33_final_evaluation_report/manifests/r...
34,34,run_1e831de6e27f9ead0147bb30,completed,producer_gate,matched,outputs/34_final_streamlit_dashboard_assets/ma...
35,35,run_3d52ae7863c44fb1b7f56a99ea0c01fa,completed,accepted_closeout,matched,outputs/35_dashboard_and_deployment_validation...
36,D02,run_fdbd2ed6e93b4d709f5439af028a7600,completed,producer_gate,matched,outputs/d02_portrait_skin_tone_and_hand_restor...
37,37,run_6583cb070ead425b91e0bf738f1822ea,completed,producer_gate,matched,outputs/37_hint_mat_method_selection/manifests...

38 completed manifests; D01/37 remains separate decision evidence.

In [4]:
ALL_ARTIFACTS = pd.concat(
    [frame.assign(source_notebook_id=nid)
     for nid, frame in ARTIFACT_LEDGERS.items()], ignore_index=True)
SELECTED_GROUP_HASHES = {}

def verify_selected_source(value):
    source = path(value)
    rel = source.relative_to(ROOT).as_posix()
    matches = [r for r in ALL_ARTIFACTS.to_dict("records")
               if rel == r["relative_path"]
               or rel.startswith(r["relative_path"].rstrip("/") + "/")]
    check("b2/producer_coverage_" + rel, bool(matches), rel)
    record = max(matches, key=lambda r: len(r["relative_path"]))
    artifact = record["relative_path"]
    if artifact not in SELECTED_GROUP_HASHES:
        actual = sha256_path(path(artifact))
        check("b2/payload_" + artifact, actual == record["checksum"], artifact)
        SELECTED_GROUP_HASHES[artifact] = actual
    return record

selected = set(CONFIG["evidence_inputs"].values())
selected.update(i.source.relative_to(ROOT).as_posix() for i in COPY_PLAN
                if i.group != "manifests"
                and i.source.relative_to(ROOT).as_posix().startswith("outputs/"))
for rel in sorted(selected):
    verify_selected_source(rel)

# Compare current N34/N35 registry rows by path; registry keys may be aliases.
for nid in ("34", "35"):
    owner = RAW_RUNS[nid]["notebook_name"]
    registered = {r["relative_path"]: r for r in REGISTRY["artifacts"]
                  if r["producer_notebook"] == owner}
    ledger = ARTIFACT_LEDGERS[nid]
    check(f"b2/registry_paths_{nid}", set(registered) == set(ledger.relative_path))
    check(f"b2/registry_records_{nid}", all(
        registered[r.relative_path]["checksum"] == r.checksum
        and registered[r.relative_path]["validation_status"] == r.validation_status
        for r in ledger.itertuples(index=False)))

n29 = CONFIG["provenance_exceptions"]["n29"]
ledger29 = path(n29["manifest_path"]).with_name("artifacts.csv")
check("b2/n29_known_exception",
      RAW_RUNS["29"]["artifact_manifest_checksum"]
      == n29["recorded_artifact_manifest_sha256"]
      and sha256_file(ledger29)
      in n29["permitted_observed_artifact_manifest_sha256"])
check("b2/n29_six_groups", len(ARTIFACT_LEDGERS["29"]) == 6)
for row in ARTIFACT_LEDGERS["29"].itertuples(index=False):
    verify_selected_source(row.relative_path)
check("b2/n29_metadata_discrepancy", False,
      n29["disposition"], severity="warning")
print("Selected payload groups verified:", len(SELECTED_GROUP_HASHES))

Selected payload groups verified: 27

In [5]:
N35 = RAW_RUNS["35"]
N35_CHECKS = read_table(CONFIG["evidence_inputs"]["n35_checks"])
passed = N35_CHECKS.passed.astype(str).str.lower().eq("true")
nonpasses = N35_CHECKS.loc[~passed].copy()
n35 = CONFIG["provenance_exceptions"]["n35"]
check("b2/n35_warning_contract",
      int(passed.sum()) == n35["expected_passed_checks"]
      and len(nonpasses) == n35["expected_warning_nonpasses"]
      and nonpasses.severity.eq("warning").all()
      and nonpasses.validation_stage.eq("batch_1_dependency_versions").sum()
          == n35["expected_dependency_warnings"]
      and nonpasses.validation_stage.eq("batch_11_qualification").sum()
          == n35["expected_unmeasured_qualifications"])
check("b2/n35_not_full_certification",
      N35["deployment"]["all_planned_checks_verified"] is False)
check("b2/n35_deployment_url", N35["deployment"]["url"]
      == "https://fhtw-painting-restoration-main.streamlit.app/")

notebook35 = read_json(n35["notebook_path"])
source35 = [(c["cell_type"], "".join(c["source"])) for c in notebook35["cells"]]
saved_digest = hashlib.sha256(
    json.dumps(source35, ensure_ascii=True).encode()).hexdigest()
check("b2/n35_known_source_exception",
      saved_digest == n35["accepted_saved_source_sha256"]
      and N35["notebook_source_sha256"] == n35["recorded_source_sha256"])
check("b2/n35_source_discrepancy", False, n35["disposition"], severity="warning")
for row in nonpasses.to_dict("records"):
    check("b2/n35_inherited_" + row["validation_stage"] + "_" + row["check_id"],
          False, row, severity="warning")

INHERITED_LIMITATIONS = {
    nid: run.get("known_limitations", []) for nid, run in RAW_RUNS.items()
}
PROVENANCE_EXCEPTIONS = CONFIG["provenance_exceptions"]
DEPLOYMENT_RECORD = N35["deployment"]
display(nonpasses[["validation_stage", "check_id", "severity", "observed"]])
print("Batch 2 passed with explicit inherited warnings; none were converted to passes.")

,validation_stage,check_id,severity,observed
61,batch_1_dependency_versions,version__pillow,warning,9.5.0
62,batch_1_dependency_versions,version__plotly,warning,6.8.0
63,batch_1_dependency_versions,version__pyarrow,warning,24.0.0
64,batch_1_dependency_versions,version__streamlit,warning,1.59.0
520,batch_11_qualification,desktop_1672x941_all_rooms,warning,owner_accepted_without_measurement
521,batch_11_qualification,tablet_1024x1366_all_rooms,warning,owner_accepted_without_measurement
522,batch_11_qualification,mobile_390x844_all_rooms,warning,owner_accepted_without_measurement
523,batch_11_qualification,keyboard_focus_and_dialogs,warning,owner_accepted_without_measurement
524,batch_11_qualification,firefox_reload_and_second_monitor,warning,owner_accepted_without_measurement
525,batch_11_qualification,same_room_no_document_reload,warning,owner_accepted_without_measurement
526,batch_11_qualification,cross_room_links_and_guided_tour,warning,owner_accepted_without_measurement
527,batch_11_qualification,downloaded_reports_open_self_contained,warning,owner_accepted_without_measurement
528,batch_11_qualification,browser_warm_navigation_p95,warning,owner_accepted_without_measurement
529,batch_11_qualification,remote_action_budget_and_peak_memory,warning,owner_accepted_without_measurement

Batch 2 passed with explicit inherited warnings; none were converted to passes.

## Batch 3 — Controlled-300 evidence synthesis

Use N33's typed thesis tables and N34's v2 bootstrap to construct the package's
population, model summary, research-question mapping and headline findings.

Tally existing quality-anchor winners without recalculating scientific metrics.
Keep all executed method candidates distinct from the retained report population.
SDXL's scheduled, completed and noncompleted records must remain distinguishable.

Retain all six current producer-backed headline findings, their limitations and
source identities. Do not recreate the old pilot's eight findings or strengthen
computational review flags into expert judgements.

All synthesis remains in memory. N36 is not complete after this batch.

In [6]:
EVIDENCE = CONFIG["evidence_inputs"]
BOOTSTRAP = read_json(EVIDENCE["bootstrap"])
TABLES = {key: read_table(EVIDENCE[key]) for key in (
    "thesis_tables", "model_cards", "compute", "model_reports",
    "case_reports", "painting_reports")}
THESIS = TABLES["thesis_tables"]
MODEL_CARDS = TABLES["model_cards"]
check("b3/package_v2", BOOTSTRAP["package_schema_version"] == "dashboard_package.v2"
      and BOOTSTRAP["dataset"]["dataset_scope"] == "controlled_300")
check("b3/thesis_schema", THESIS.schema_version.eq("thesis_tables.v1").all()
      and THESIS.status.eq("ok").all())
check("b3/model_ids", set(MODEL_CARDS.model_id) == {
    "opencv_telea", "lama", "hint_places2",
    "stable_diffusion_inpainting", "sdxl_inpainting"})
check("b3/table_row_ids", THESIS.table_row_id.is_unique)

def table_values(table_id):
    frame = THESIS.loc[THESIS.table_id.eq(table_id)].copy()
    check("b3/unique_keys_" + table_id, frame.row_key.is_unique)
    return {row.row_key: json.loads(row.values_json)
            for row in frame.itertuples(index=False)}

scope = table_values("t02_dataset_design_scope")
uncertainty = table_values("t09_uncertainty")
groups = COPY_PLAN_TABLE.groupby("group").size().to_dict()
sdxl = MODEL_CARDS.set_index("model_id").loc["sdxl_inpainting"]
POPULATION = {
    "upstream_notebooks": len(UPSTREAM),
    "paintings": int(scope["paintings"]["count"]),
    "registered_cases": int(scope["registered_cases"]["count"]),
    "restoration_cases": int(scope["eligible_cases"]["count"]),
    "primary_candidates": int(scope["primary_candidates"]["count"]),
    "approved_candidates": int(RAW_RUNS["33"]["observed_counts"]["approved_report_candidate_count"]),
    "uncertainty_groups": int(uncertainty["canonical_uncertainty"]["estimate"]
                              + uncertainty["damage_size_uncertainty"]["estimate"]),
    "sdxl_scheduled_cases": int(sdxl.evaluated_case_count),
    "sdxl_completed_candidates": int(sdxl.completed_count),
    "thesis_figures": int(groups["thesis_figures"]),
    "publication_figures": int(groups["publication_figures"]),
    "model_reports": len(TABLES["model_reports"]),
    "model_cards": len(MODEL_CARDS),
    "case_report_records": len(TABLES["case_reports"]),
    "painting_report_records": len(TABLES["painting_reports"]),
}
ANCHOR_ROWS = THESIS.loc[THESIS.table_id.eq("t04_quality_anchor_summary")].copy()
ANCHOR_ROWS["anchor_id"] = ANCHOR_ROWS.row_key.str.rsplit("__", n=1).str[0]
ANCHOR_ROWS["winner"] = ANCHOR_ROWS.values_json.map(
    lambda s: json.loads(s)["winner_model_id"])
check("b3/anchor_agreement",
      ANCHOR_ROWS.groupby("anchor_id").winner.nunique().eq(1).all())
ANCHORS = ANCHOR_ROWS.drop_duplicates("anchor_id")
POPULATION["quality_anchors"] = len(ANCHORS)
check("b3/population_contract", POPULATION == CONFIG["expected_population"],
      POPULATION)
wins = ANCHORS.winner.value_counts()
check("b3/saved_anchor_result", wins.to_dict() == {"lama": 10, "opencv_telea": 1},
      wins.to_dict())
MODEL_SUMMARY = MODEL_CARDS[[
    "model_id", "evaluation_status", "evaluated_case_count",
    "evaluated_candidate_count", "completed_count", "failed_count",
    "median_runtime_seconds"]].copy()
MODEL_SUMMARY["quality_anchor_wins"] = MODEL_SUMMARY.model_id.map(wins)
MODEL_SUMMARY.loc[
    MODEL_SUMMARY.evaluation_status.eq("fully_evaluated"),
    "quality_anchor_wins"] = MODEL_SUMMARY.loc[
        MODEL_SUMMARY.evaluation_status.eq("fully_evaluated"),
        "quality_anchor_wins"].fillna(0)
display(pd.Series(POPULATION, name="observed").to_frame())
display(MODEL_SUMMARY)
print("Execution coverage is not the retained report-candidate population.")
print("SDXL has no full-benchmark anchor rank; its missing value is intentional.")

                           observed
upstream_notebooks               38
paintings                       300
registered_cases               3425
restoration_cases              2620
primary_candidates            10480
approved_candidates           13879
uncertainty_groups             1025
sdxl_scheduled_cases             35
sdxl_completed_candidates        24
thesis_figures                   18
publication_figures               6
model_reports                     5
model_cards                       5
case_report_records              30
painting_report_records         300
quality_anchors                  11

,model_id,evaluation_status,evaluated_case_count,evaluated_candidate_count,completed_count,failed_count,median_runtime_seconds,quality_anchor_wins
0,opencv_telea,fully_evaluated,2620,2620,2620,0,0.519020,1.0
1,lama,fully_evaluated,2620,2620,2620,0,1.450884,10.0
2,hint_places2,fully_evaluated,2620,2620,2620,0,6.677000,0.0
3,stable_diffusion_inpainting,fully_evaluated,2620,8520,8520,0,8.620316,0.0
4,sdxl_inpainting,partial_evaluation,35,35,24,11,198.031500,NaN

Execution coverage is not the retained report-candidate population.
SDXL has no full-benchmark anchor rank; its missing value is intentional.

In [7]:
RQ_ROWS = THESIS.loc[
    THESIS.table_id.eq("t01_research_question_map")
    & THESIS.row_key.isin(["rq1", "rq2", "rq3"])].sort_values("row_order")
check("b3/rq_ids", RQ_ROWS.row_key.tolist() == ["rq1", "rq2", "rq3"])
RQ_ANSWERS = {
    "rq1": "Complementary region-aware metrics expose disagreements; no single or combined score establishes restoration trustworthiness.",
    "rq2": "LaMa leads 10 of 11 saved quality anchors and Telea leads crop SSIM. HINT is a full deterministic method; SDXL remains bounded. Conclusions apply to this controlled benchmark.",
    "rq3": "The 780 canonical and 245 damage-size groups characterize repeated-seed variation. Disagreement supports inspection, not calibrated confidence or historical correctness.",
}
RQ_LIMITS = {
    "rq1": "Metrics and feature similarity are not conservation approval.",
    "rq2": "No universal model superiority or independently established art-historical style effect.",
    "rq3": "Only supported repeated-seed groups; deterministic methods do not acquire seed uncertainty.",
}
RQ_TABLE_BINDINGS = {
    "rq1": ["t05_metric_disagreement", "t12_ablation"],
    "rq2": ["t03_model_coverage", "t04_quality_anchor_summary"],
    "rq3": ["t09_uncertainty"],
}
rq_records = []
for row in RQ_ROWS.itertuples(index=False):
    supporting = THESIS.loc[THESIS.table_id.isin(RQ_TABLE_BINDINGS[row.row_key])]
    sources = sorted({p for value in supporting.source_paths_json
                      for p in json.loads(value)})
    for source in sources:
        path(source)
    rq_records.append(dict(
        question_id=row.row_key,
        question=CONFIG["research_questions"][row.row_key],
        answer=RQ_ANSWERS[row.row_key], limitation=RQ_LIMITS[row.row_key],
        source_table_path=EVIDENCE["thesis_tables"],
        source_table_sha256=SOURCE_LOCK[EVIDENCE["thesis_tables"]],
        source_row_ids=supporting.table_row_id.tolist(), source_paths=sources))
RQ_SYNTHESIS = pd.DataFrame(rq_records)
HEADLINE_FINDINGS = pd.DataFrame(BOOTSTRAP["headline_findings"])
check("b3/headline_records", len(HEADLINE_FINDINGS) == 6
      and HEADLINE_FINDINGS.finding_id.is_unique
      and HEADLINE_FINDINGS.limitation.str.len().gt(0).all())
check("b3/headline_producers", all(
    set(ids) <= set(RAW_RUNS) for ids in HEADLINE_FINDINGS.source_notebook_ids))
display(RQ_SYNTHESIS[["question_id", "question", "answer", "limitation"]])
display(HEADLINE_FINDINGS[["title", "statement", "limitation"]])
print("Six producer-backed headline findings retained without stronger claims.")

,question_id,question,answer,limitation
0,rq1,"What additional evidence does a region-aware, ...",Complementary region-aware metrics expose disa...,Metrics and feature similarity are not conserv...
1,rq2,How do selected inpainting methods differ in r...,LaMa leads 10 of 11 saved quality anchors and ...,No universal model superiority or independentl...
2,rq3,How can repeated-candidate disagreement be use...,The 780 canonical and 245 damage-size groups c...,Only supported repeated-seed groups; determini...

,title,statement,limitation
0,Balanced controlled collection,"The collection contains 300 paintings, with 60...",This does not represent every artistic traditi...
1,Matched four-method evidence,The four full-scope methods were compared on 2...,Eligibility and metric performance do not esta...
2,Different measurements can prefer different me...,LaMa led 10 of 11 separate quality anchors; Te...,No combined or universal quality score was cre...
3,Repeated outputs reveal variation,"Stable Diffusion has 1,025 supported four-seed...","This is empirical variation, not calibrated co..."
4,Flags organize review rather than replace it,Operational thresholds point to evidence that ...,"A flag is not a probability, expert verdict or..."
5,The focused portrait audit remains separate,D02 found hands harder to restore in its match...,"Rendered lightness is not race or identity, an..."

Six producer-backed headline findings retained without stronger claims.

In [8]:
changed = [rel for rel, digest in SOURCE_LOCK.items()
           if sha256_file(path(rel)) != digest]
check("b3/input_freeze", not changed, changed)
changed_groups = [rel for rel, digest in SELECTED_GROUP_HASHES.items()
                  if sha256_path(path(rel)) != digest]
check("b3/selected_payload_freeze", not changed_groups, changed_groups)
check("b3/historical_outputs_unchanged",
      tree_snapshot(OUTPUT_ROOT) == HISTORICAL_OUTPUT_SNAPSHOT)
VALIDATION = ValidationCollector()
for record in CHECK_LOG.values():
    VALIDATION.add(**record)
VALIDATION.raise_for_blocking()
display(VALIDATION.to_dataframe().groupby(
    ["validation_stage", "severity"]).agg(
        checks=("check_id", "size"), passed=("passed", "sum")))
print("Batches 1-3 complete in memory; no canonical N36 outputs written.")
print("N36 completion gate remains NO. Stop here and save the notebook.")

                           checks  passed
validation_stage severity
b1               blocking      11      11
b2               blocking     302     302
                 warning       16       0
b3               blocking      15      15

Batches 1-3 complete in memory; no canonical N36 outputs written.
N36 completion gate remains NO. Stop here and save the notebook.

## Batch 4 — Supervisor summary and meeting documents

Create the supervisor summary, structured key findings, open questions and
feedback agenda in isolated staging under this notebook's owned output root.

The summary covers the evaluated population, exact research questions,
bounded answers, model coverage, interpretation limits and requested decisions.
Figures and evidence links have explicit standalone and package-local variants.

Canonical delivery files remain untouched. No scientific evidence is recomputed.

In [9]:
import os
import uuid
from importlib import metadata
from restoration_eval.manifests import git_state
from restoration_eval.supervisor_package import atomic_write_text

def verify_frozen_inputs(stage):
    changed = [rel for rel, digest in SOURCE_LOCK.items()
               if not path(rel).is_file() or sha256_file(path(rel)) != digest]
    check(f"{stage}/source_freeze", not changed, changed)

def canonical_snapshot():
    return {rel: digest for rel, digest in tree_snapshot(OUTPUT_ROOT).items()
            if rel.split("/", 1)[0] != "work"}

verify_frozen_inputs("b4")
check("b4/baseline_has_no_work",
      not any(rel.split("/", 1)[0] == "work"
              for rel in HISTORICAL_OUTPUT_SNAPSHOT))
check("b4/canonical_baseline",
      canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT)

if "N36_RUN_ID" not in globals():
    N36_RUN_ID = "run_" + uuid.uuid4().hex
    STAGE_ROOT = OUTPUT_ROOT / "work" / N36_RUN_ID
    STAGE_WRITES = {}

check("b4/stage_boundary",
      STAGE_ROOT.resolve().is_relative_to((OUTPUT_ROOT / "work").resolve()))
STAGE_ROOT.mkdir(parents=True, exist_ok=True)

def stage_path(relative):
    target = (STAGE_ROOT / relative).resolve()
    if not target.is_relative_to(STAGE_ROOT.resolve()):
        raise RuntimeError(f"Staging path escape: {relative}")
    return target

def write_stage(relative, text):
    target = stage_path(relative)
    expected = hashlib.sha256(text.encode("utf-8")).hexdigest()
    if target.exists():
        observed = sha256_file(target)
        if observed not in {expected, STAGE_WRITES.get(relative)}:
            raise RuntimeError(f"Refusing to overwrite unowned/changed file: {relative}")
    atomic_write_text(target, text)
    check("b4/write_" + relative, sha256_file(target) == expected)
    STAGE_WRITES[relative] = expected
    return target

def json_text(value):
    return json.dumps(value, indent=2, ensure_ascii=False, allow_nan=False) + "\n"

def records(frame):
    return json.loads(frame.to_json(orient="records", force_ascii=False))

def markdown_table(frame):
    def escape(value):
        if isinstance(value, (dict, list)):
            value = json.dumps(value, ensure_ascii=False)
        elif pd.isna(value):
            value = "not applicable"
        return str(value).replace("|", r"\|").replace("\n", " ")
    rows = [list(frame.columns), ["---"] * len(frame.columns)]
    rows += frame.astype(object).values.tolist()
    return "\n".join("| " + " | ".join(map(escape, row)) + " |" for row in rows)

def document_relative(key):
    return OUTPUT_PATHS[key].relative_to(OUTPUT_ROOT).as_posix()

DOC_TEMPLATES = globals().get("DOC_TEMPLATES", {})

def save_document(key, text):
    DOC_TEMPLATES[key] = text
    return write_stage(document_relative(key), text.replace("@BUNDLE@", "../package"))

write_stage("staging_owner.json", json_text({
    "notebook_id": "36", "run_id": N36_RUN_ID,
    "state": "staging_only", "completion_gate_passed": False,
    "source_config_sha256": SOURCE_LOCK["config/evaluation/supervisor_package.yaml"],
}))
print("Staging only:", STAGE_ROOT.relative_to(ROOT))
print("Canonical files at run start:", len(HISTORICAL_OUTPUT_SNAPSHOT))

Staging only: outputs\36_supervisor_publication_reproducibility_package\work\run_e3133aca48134968896bcd1b97af72c4
Canonical files at run start: 0

In [10]:
from IPython.display import Markdown

model_view = MODEL_SUMMARY[[
    "model_id", "evaluation_status", "evaluated_case_count",
    "completed_count", "quality_anchor_wins"]].rename(columns={
    "evaluated_case_count": "scheduled cases",
    "completed_count": "completed executions",
    "quality_anchor_wins": "saved anchor wins",
})

rq_sections = "\n\n".join(
    f"### {r.question_id.upper()}\n\n{r.question}\n\n"
    f"**Answer:** {r.answer}\n\n**Boundary:** {r.limitation}\n\n"
    f"Trace: {len(r.source_row_ids)} saved rows in "
    "[thesis tables](@BUNDLE@/tables/thesis_tables.csv)."
    for r in RQ_SYNTHESIS.itertuples(index=False))

headlines = "\n\n".join(
    f"### {r.title}\n\n{r.statement}\n\n**Limit:** {r.limitation}"
    for r in HEADLINE_FINDINGS.itertuples(index=False))

SUPERVISOR_TEXT = f"""# Controlled-300: supervisor review summary

## Decision snapshot

The evidence supports a region-aware, multi-metric evaluation workflow—not a
universal restoration score or conservation approval. **LaMa leads 10 of 11
saved quality anchors; Telea leads crop SSIM.** This is bounded comparative
evidence, not universal model superiority.

The collection contains **{POPULATION['paintings']:,} paintings**,
**{POPULATION['registered_cases']:,} registered cases** and
**{POPULATION['restoration_cases']:,} restoration-eligible cases**.
The matched four-method comparison has **{POPULATION['primary_candidates']:,}
primary candidates**. The broader retained report population contains
**{POPULATION['approved_candidates']:,} candidates**; it is not the same
denominator as all model executions.

## Model coverage

{markdown_table(model_view)}

Four methods have full coverage: Telea, LaMa, HINT and Stable Diffusion.
SDXL has **24 completed candidates from a bounded 35-case schedule**.
Its other 11 scheduled records include timeout/skipped outcomes, not 11
demonstrated inference crashes. SDXL has no full-benchmark anchor rank.
Zero anchor wins do not mean a method never performs well on individual cases.

D01 is separate 12-case HINT/MAT selection evidence; D02 is a separate focused
portrait audit. Neither is pooled into the main benchmark.

## Research questions

{rq_sections}

## Principal evidence

{headlines}

## Robustness, trustworthiness and explanation

Damage-size, mask-geometry and synthetic-degradation evidence must retain their
own conditions and denominators. The extension populations do not independently
separate painting identity from category. Inspect the saved condition-specific
results rather than treating one mean as universal robustness.

Repeated-seed evidence comprises 780 canonical and 245 damage-size groups.
It describes variability, not calibrated confidence. Computational flags,
threshold sensitivity, counterfactual views and retrieval neighbours support
inspection; they are not expert truth or proof of historical correctness.

![Canonical comparison](@BUNDLE@/figures/thesis/04_canonical_model_comparison.png)

![Uncertainty summary](@BUNDLE@/figures/thesis/12_uncertainty_summary.png)

## Delivery and reproducibility

[Open the full evaluation](@BUNDLE@/reports/final_evaluation.html) for the
complete scientific narrative and embedded evidence.
[Open the deployed dashboard]({DEPLOYMENT_RECORD['url']}) for exploration.

N35 closed with **519 passes, 14 warning nonpasses and zero blocking failures**.
Four warnings concern dependencies; ten are unmeasured, owner-accepted
qualifications. Successful availability checks do not establish p95 latency,
peak memory, exhaustive browser coverage or clean Linux reproduction.
The deployed server revision was not independently attested.

The N29 historical manifest discrepancy and N35 notebook-source mismatch remain
disclosed. See the [limitations](@BUNDLE@/reports/limitations_and_deviations.md)
and [reproducibility appendix](@BUNDLE@/reports/reproducibility_appendix.md).
This bundle is not a runnable repository clone.

## Decisions requested

1. Confirm that the bounded research-question answers are suitable for the thesis.
2. Choose the principal figures and representative cases for the final narrative.
3. Agree how prominently to present SDXL feasibility and the separate D01/D02 studies.
4. Review the limitations and decide whether any additional expert study is future work.
5. Approve the publication/freeze plan without treating planned publication as completed.

Visual plausibility is not historical correctness or conservation approval.
"""
save_document("supervisor_summary", SUPERVISOR_TEXT)

KEY_FINDINGS = {
    "schema_version": "supervisor_key_findings.v2",
    "dataset_scope": "controlled_300",
    "population": POPULATION,
    "model_coverage": records(MODEL_SUMMARY),
    "research_questions": records(RQ_SYNTHESIS),
    "headline_findings": records(HEADLINE_FINDINGS),
    "headline_source": {
        "path": EVIDENCE["bootstrap"],
        "sha256": SOURCE_LOCK[EVIDENCE["bootstrap"]],
    },
    "scientific_boundaries": CONFIG["scientific_boundaries"],
    "provenance_exceptions": PROVENANCE_EXCEPTIONS,
}
save_document("key_findings", json_text(KEY_FINDINGS))

save_document("open_questions", """# Open questions for supervisor review

These are review decisions and future-work questions, not missing measurements
that the present package claims to have completed.

1. Does the thesis clearly distinguish reference fidelity from historical correctness?
2. Which metric disagreements and cases best illustrate why multiple regions matter?
3. Is the SDXL feasibility boundary sufficiently clear beside four fully evaluated methods?
4. Should D01 and D02 remain separate supporting studies in the thesis structure?
5. Which deployment qualifications need measurement for a future operational service?
6. What expert annotation or real-conservation dataset would be needed for external validation?
7. When should a versioned archival deposit be made after the final pipeline freeze?
""")

save_document("feedback_agenda", """# Supervisor feedback agenda

## Suggested 30-minute meeting

- 0–5 min: scope, principal result and the three bounded research-question answers.
- 5–12 min: comparison figure, metric disagreement and two representative cases.
- 12–18 min: robustness, repeated-seed variation, flags and interpretation limits.
- 18–23 min: D01 selection, D02 portrait audit and bounded SDXL feasibility.
- 23–27 min: deployment acceptance, provenance exceptions and reproducibility.
- 27–30 min: agree thesis edits, figure selection and publication/freeze decisions.

## Record after the meeting

- Decisions accepted:
- Changes requested:
- Owner and due date:
- Questions deferred to future work:

This agenda is a proposed review structure, not evidence that a meeting occurred.
""")

for question in CONFIG["research_questions"].values():
    check("b4/question_" + hashlib.sha256(question.encode()).hexdigest()[:10],
          question in SUPERVISOR_TEXT)

check("b4/findings_roundtrip",
      json.loads(stage_path(document_relative("key_findings")).read_text("utf-8"))
      == KEY_FINDINGS)
check("b4/no_canonical_writes",
      canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT)

display(Markdown(SUPERVISOR_TEXT.split("## Model coverage")[0]))
print("Batch 4: four supervisor documents staged; completion gate remains NO.")

# Controlled-300: supervisor review summary

## Decision snapshot

The evidence supports a region-aware, multi-metric evaluation workflow—not a
universal restoration score or conservation approval. **LaMa leads 10 of 11
saved quality anchors; Telea leads crop SSIM.** This is bounded comparative
evidence, not universal model superiority.

The collection contains **300 paintings**,
**3,425 registered cases** and
**2,620 restoration-eligible cases**.
The matched four-method comparison has **10,480
primary candidates**. The broader retained report population contains
**13,879 candidates**; it is not the same
denominator as all model executions.

Batch 4: four supervisor documents staged; completion gate remains NO.

## Batch 5 — Reproducibility, limitations and publication references

Preserve the packaging environment, exact source hashes, upstream execution
records, model revisions, seed policies, compute evidence and scope boundaries.

Carry forward all 18 N33 limitations, all 14 N35 warning nonpasses and the
documented N29/N35 provenance exceptions. Missing or unmeasured evidence remains
missing or unmeasured.

Publication references describe existing records. This batch performs no remote
verification, upload or archival deposit. The package is not a runnable clone.

In [11]:
verify_frozen_inputs("b5")
current_git = git_state(ROOT)
check("b5/git_identity", bool(current_git["git_commit"])
      and not current_git["git_error"], current_git)

local_versions = {
    name: metadata.version(name)
    for name in CONFIG["runtime"]["packages"]
}

LIMITATION_ROWS = THESIS.loc[THESIS.table_id.eq("t15_limitations")].copy()
check("b5/n33_limitations",
      len(LIMITATION_ROWS) == 18 and LIMITATION_ROWS.table_row_id.is_unique)

N35_NONPASSES = N35_CHECKS.loc[
    ~N35_CHECKS.passed.astype(str).str.lower().eq("true")].copy()

# New read-only provenance references; the approved copy plan is unchanged.
policy_relative = "config/publication/external_storage.yaml"
readme_relative = "README.md"
policy_text = lock_file(policy_relative).read_text(encoding="utf-8-sig")
readme_text = lock_file(readme_relative).read_text(encoding="utf-8-sig")

check("b5/publication_inputs_indexed",
      {policy_relative, readme_relative} <= set(INVENTORY.relative_path))

PUBLICATION_REFERENCES = {
    "github": "https://github.com/Rahul-DS25M008/painting_restoration_eval",
    "hf_candidates": "https://huggingface.co/datasets/RahulMaddineni264/painting-restoration-eval-candidates",
    "hf_diagnostics": "https://huggingface.co/datasets/RahulMaddineni264/painting-restoration-eval-diagnostics",
    "dashboard": DEPLOYMENT_RECORD["url"],
}
check("b5/publication_references",
      PUBLICATION_REFERENCES["github"] in readme_text
      and PUBLICATION_REFERENCES["hf_candidates"] in policy_text
      and PUBLICATION_REFERENCES["hf_diagnostics"] in policy_text)

REPRODUCIBILITY_SNAPSHOT = {
    "schema_version": "reproducibility_snapshot.v2",
    "notebook_id": "36",
    "run_id": N36_RUN_ID,
    "started_at_utc": RUN_STARTED_AT_UTC,
    "snapshot_at_utc": datetime.now(timezone.utc).isoformat(),
    "dataset_scope": "controlled_300",
    "configuration_version": CONFIG["configuration_version"],
    "packaging_environment": {
        "python": platform.python_version(),
        "platform": platform.platform(),
        "machine": platform.machine(),
        "processor": platform.processor(),
        "packages": local_versions,
        "git": current_git,
        "boundary": "Packaging environment, not a fresh experimental reproduction.",
    },
    "population": POPULATION,
    "inventory_run_id": INVENTORY_RUN["inventory_run_id"],
    "source_file_sha256": dict(SOURCE_LOCK),
    "selected_payload_group_sha256": SELECTED_GROUP_HASHES,
    "copy_plan": records(COPY_PLAN_TABLE),
    "upstream_completion_audit": records(UPSTREAM),
    "upstream_execution_records": RAW_RUNS,
    "upstream_known_limitations": INHERITED_LIMITATIONS,
    "upstream_validation_summaries": {
        nid: run.get("validation_summary")
        for nid, run in RAW_RUNS.items()
    },
    "model_cards": records(MODEL_CARDS),
    "compute_and_scalability": records(TABLES["compute"]),
    "n33_limitations": records(LIMITATION_ROWS),
    "n35_nonpasses": records(N35_NONPASSES),
    "provenance_exceptions": PROVENANCE_EXCEPTIONS,
    "deployment": DEPLOYMENT_RECORD,
    "publication_references": PUBLICATION_REFERENCES,
    "recorded_publication_overview": BOOTSTRAP["publication_overview"],
    "publication_boundary": {
        "new_upload_performed": False,
        "remote_reverified_this_run": False,
        "zenodo": "Planned after pipeline freeze; no deposit claimed by N36.",
        "reference_policy_path": policy_relative,
        "reference_policy_sha256": SOURCE_LOCK[policy_relative],
    },
    "package_boundary": {
        "portable_review_bundle": True,
        "complete_repository_clone": False,
        "scientific_recomputation": False,
        "new_model_inference": False,
        "indexed_not_bundled": CONFIG["package_policy"]["indexed_not_bundled"],
    },
    "scope_separation": {
        "37": "D01: 12-case method selection only",
        "D02": "Focused portrait audit; not pooled",
    },
}

check("b5/snapshot_serializable",
      json.loads(json_text(REPRODUCIBILITY_SNAPSHOT))
      == REPRODUCIBILITY_SNAPSHOT)

print("Provenance preserves all 38 upstream execution records and validation summaries.")
print("No network test, upload, inference or scientific recomputation performed.")

Provenance preserves all 38 upstream execution records and validation summaries.
No network test, upload, inference or scientific recomputation performed.

In [12]:
model_provenance = MODEL_CARDS[[
    "model_id", "model_identifier", "model_revision", "seed_policy",
    "execution_device", "precision"]]

publication_links = "\n".join(
    f"- [{name.replace('_', ' ').title()}]({url})"
    for name, url in PUBLICATION_REFERENCES.items())

upstream_table = markdown_table(UPSTREAM[[
    "notebook_id", "run_id", "completion_basis", "ledger_hash_state"]])

APPENDIX_TEXT = f"""# Reproducibility appendix

## What this delivery reproduces

N36 consolidates validated saved artifacts and verifies copied bytes.
It does not repeat restoration inference, metric computation or statistical tests.
The bundle is not a complete runnable checkout; application files are source snapshots.

## Packaging environment and revision

- Python: {platform.python_version()}
- Platform: {platform.platform()}
- Git commit: {current_git['git_commit']}
- Git branch: {current_git['git_branch']}
- Uncommitted changes present: {current_git['git_dirty']}
- Inventory record: {INVENTORY_RUN['inventory_run_id']}

{markdown_table(pd.DataFrame(local_versions.items(), columns=['package', 'version']))}

The recorded commit identifies HEAD, not every uncommitted byte.
The [snapshot](@BUNDLE@/provenance/reproducibility_snapshot.json) records exact
selected-source hashes and preserves upstream environments. This packaging
environment is not proof of a clean Linux app installation or a reproduction of
all GPU experiments.

## Model revisions, seeds and hardware

{markdown_table(model_provenance)}

The five [model cards](@BUNDLE@/tables/model_cards.csv), their complete records
in the snapshot and the 38 copied run manifests retain model identifiers,
revisions, seeds, configuration, dataset and hardware evidence as recorded.
Missing upstream fields remain missing; no revision or seed is invented.

## Compute and scaling

Saved compute/scalability records are included in the snapshot with their
original scenario and observation/projection fields. Projections are not executed
measurements or confidence intervals. Runtime and memory characterize recorded
hardware and producer-specific populations, not deployment latency.
The legacy experiment requirements and current dashboard requirements have
different scopes; neither is silently substituted for recorded producer versions.

## Upstream acceptance

{upstream_table}

N35 uses its accepted closeout, not an invented completion_gate_passed field.
A ledger hash not declared by an early producer is labelled accordingly.
Selected payload groups were independently checked; this is not a claim that
every upstream image or remote object was rehashed by N36.

## Known exceptions and deployment qualification

N29's historical artifact-ledger checksum differs from its recorded value.
All six payload groups were independently checked; the historical record is unchanged.
N35's recorded notebook-source digest differs from the accepted saved source.
Both digests and the owner's accepted disposition are retained in the snapshot.

N35 records 519 passes and 14 warning nonpasses: four dependency warnings and ten
unmeasured qualifications. Availability success is not p95 latency or peak-memory
measurement. The server checkout revision remains independently unattested.
See [deployment readiness](@BUNDLE@/reports/deployment_readiness.md) and
[limitations](@BUNDLE@/reports/limitations_and_deviations.md).

## Publication references

{publication_links}

N34 records {BOOTSTRAP['publication_overview']['verified_individual_records']:,}
individually published artifacts and
{BOOTSTRAP['publication_overview']['verified_bundle_releases']} bundle releases.
These are inherited records, not new remote checks. Immutable revisions and
checksums must be taken from the original release records, not a floating URL.
Zenodo remains planned after pipeline freeze; N36 does not claim a deposit or DOI.

## Reproduction route

1. Use the full repository and the exact producer manifests, not this review bundle alone.
2. Resolve the required local/remote assets through their pinned publication records.
3. Recreate each producer's documented environment, model revisions and configuration.
4. Follow the numbered dependency order, keeping D01 and D02 scopes separate.
5. Compare identifiers, dimensions, byte checksums and validation evidence.
6. Treat the disclosed provenance and deployment qualifications as unresolved limits.

## Integrity and portability

Copied sources must match their frozen SHA-256 digests.
N36-generated documents are identified separately from copied sources.
The final package manifest and integrity gate are produced in Batches 7–9;
this appendix alone does not certify completion.
"""
save_document("reproducibility_appendix", APPENDIX_TEXT)

limitation_list = "\n".join(
    f"- {r.row_label} (source row: {r.table_row_id})."
    for r in LIMITATION_ROWS.itertuples(index=False))

warning_sections = "\n\n".join(
    f"### {r.validation_stage} / {r.check_id}\n\n"
    f"Observed: {r.observed}\n\nDetails: {r.details}"
    for r in N35_NONPASSES.itertuples(index=False))

LIMITATIONS_TEXT = f"""# Limitations and deviations

## The 18 limitations retained from N33

{limitation_list}

These are preserved from the [thesis tables](@BUNDLE@/tables/thesis_tables.csv).
The complete producer records and limitations remain in the provenance snapshot.

## Scope separation

D01 is a separate 12-case method-selection study. D02 is a focused portrait audit,
not demographic-bias ground truth. Rendered lightness is not race or identity.
SDXL's 35-case schedule yielded 24 completed candidates; it is not a fifth
fully evaluated benchmark method.

## Historical provenance exceptions

- N29: historical artifact-manifest mismatch, with all six payload groups checked.
- N35: recorded notebook-source hash differs from the accepted saved source.
  The exact cause was not established; the owner accepted proceeding without rerun.

These exceptions are disclosed, not repaired or converted into passed checks.
Exact recorded/observed digests appear in the
[provenance snapshot](@BUNDLE@/provenance/reproducibility_snapshot.json).

## The 14 inherited N35 warning nonpasses

{warning_sections}

## Delivery boundaries

Only selected upstream payloads were rehashed. Remote availability was not
retested here. The recorded checker revision is not proof of the deployed
server revision. Case/painting reports and bulk collections are indexed, not
duplicated. Source snapshots do not make this a runnable application clone.

Visual plausibility is not historical correctness, expert truth or conservation
approval. No universal combined quality or trustworthiness score is constructed.
"""
save_document("limitations_and_deviations", LIMITATIONS_TEXT)

for row in LIMITATION_ROWS.itertuples(index=False):
    check("b5/limitation_" + row.row_key, row.row_label in LIMITATIONS_TEXT)

check("b5/warnings_preserved",
      len(N35_NONPASSES) == 14 and all(
          r.check_id in LIMITATIONS_TEXT
          for r in N35_NONPASSES.itertuples(index=False)))
check("b5/no_canonical_writes",
      canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT)

print("Batch 5: appendix and limitations staged; six documents prepared in total.")

Batch 5: appendix and limitations staged; six documents prepared in total.

## Batch 6 — Byte-preserving package assembly

Copy the 115 approved source files into staging and verify each against its
frozen SHA-256 digest. Add the six N36 documents, package README and provenance
snapshot: 123 package files are expected at this stage.

Copied upstream evidence remains byte-identical. N36-generated Markdown uses
explicit package-local links rather than modifying upstream reports.

Reload the package, reconcile the exact file set, check size and path boundaries,
inspect the six HTML reports and verify all 24 PNG figures.

Do not promote the package or declare completion yet. Batches 7–9 will create
the final indexes/manifests, complete portability checks and perform guarded
promotion.

In [13]:
import shutil
from restoration_eval.supervisor_package import (
    package_file_records, package_tree_checksum,
)

verify_frozen_inputs("b6")
check("b6/canonical_baseline",
      canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT)

PACKAGE_ROOT = stage_path("package")
FIXED_COPY_AUDIT_RECORDS = []

for number, row in enumerate(COPY_PLAN_TABLE.itertuples(index=False), 1):
    source = path(row.source_path)
    relative = (ROOT / row.destination_path).relative_to(OUTPUT_ROOT).as_posix()
    destination = stage_path(relative)

    check("b6/source_" + relative,
          sha256_file(source) == row.source_sha256)

    if destination.exists():
        if sha256_file(destination) != row.source_sha256:
            raise RuntimeError(f"Refusing to replace different copy: {relative}")
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary = destination.with_name(
            destination.name + "." + uuid.uuid4().hex + ".tmp")
        try:
            shutil.copy2(source, temporary)
            if sha256_file(temporary) != row.source_sha256:
                raise RuntimeError(f"Copy checksum mismatch: {relative}")
            os.replace(temporary, destination)
        finally:
            temporary.unlink(missing_ok=True)

    matched = sha256_file(destination) == row.source_sha256
    check("b6/copy_" + relative, matched)

    FIXED_COPY_AUDIT_RECORDS.append({
        "source_path": row.source_path,
        "destination_path": row.destination_path,
        "package_relative_path": destination.relative_to(PACKAGE_ROOT).as_posix(),
        "source_sha256": row.source_sha256,
        "matches": matched,
    })

    if number % 20 == 0 or number == len(COPY_PLAN_TABLE):
        print(f"Verified copy {number}/{len(COPY_PLAN_TABLE)}")

GENERATED_PACKAGE_PATHS = set()
for key, template in DOC_TEMPLATES.items():
    relative = "package/" + document_relative(key)
    write_stage(relative, template.replace("@BUNDLE@", ".."))
    GENERATED_PACKAGE_PATHS.add(relative)

model_links = "\n".join(
    f"- [{r.display_name}](reports/models/{r.model_id}.html)"
    for r in MODEL_CARDS.itertuples(index=False))

PACKAGE_README_TEXT = f"""# Controlled-300 review package

## Begin here

1. [Supervisor summary](reports/supervisor_summary.md)
2. [Full self-contained evaluation report](reports/final_evaluation.html)
3. [Reproducibility appendix](reports/reproducibility_appendix.md)
4. [Limitations and deviations](reports/limitations_and_deviations.md)
5. [Deployment readiness](reports/deployment_readiness.md)

## Model reports

{model_links}

## Meeting and evidence aids

- [Key findings](data/key_findings.json)
- [Open questions](data/open_questions.md)
- [Feedback agenda](data/feedback_agenda.md)
- [Thesis tables](tables/thesis_tables.csv)
- [Case report index](tables/case_report_index.csv)
- [Painting report index](tables/painting_report_index.csv)
- [Provenance snapshot](provenance/reproducibility_snapshot.json)

## Included

The package carries six self-contained scientific HTML reports, 24 figures,
five model cards, eight compact tables/indexes, 38 upstream run manifests,
evaluation configurations, requirements files and provenance documents.
D01 and D02 retain their separate scopes.

## Intentionally absent

The 30 detailed case reports, 300 painting reports, selected-case grids,
full dashboard visuals, raw/restored image collections, diagnostic maps,
model weights and caches are not duplicated. Repository paths inside copied
tables/manifests are provenance references, not promises of package-local files.
Use the full repository and pinned publication records for those assets.

Application files are source snapshots only: **this is not a runnable clone**.
Zenodo publication remains planned; no new upload is performed by N36.

## Integrity handoff

Distribute the completed N36 directory with its sibling manifests directory,
not package alone. Batches 7–9 create the package manifest, artifact index,
validation ledger and final run record. Until that final gate passes, this is
staged work, not a completed release.

For an accepted release, compare the package manifest's package-relative paths,
byte sizes and SHA-256 values against every bundled file. The tree digest is
computed from sorted package-relative-path, tab, file-hash records joined by
newlines. Integrity does not imply scientific correctness or conservation approval.

## Limits travel with the evidence

N35's 14 warning nonpasses and the N29/N35 provenance exceptions remain explicit.
Repeated-seed variability is not calibrated confidence. SDXL is bounded
feasibility evidence, not a fifth complete benchmark method.
"""
write_stage("package/README.md", PACKAGE_README_TEXT)
GENERATED_PACKAGE_PATHS.add("package/README.md")

REPRODUCIBILITY_SNAPSHOT["assembly"] = {
    "copied_file_count": len(COPY_PLAN_TABLE),
    "generated_document_count": len(DOC_TEMPLATES),
    "generated_package_file_count": len(DOC_TEMPLATES) + 2,
    "source_bytes_preserved": True,
    "document_link_policy": "Generate explicit standalone and package-local variants.",
}
write_stage(
    "package/provenance/reproducibility_snapshot.json",
    json_text(REPRODUCIBILITY_SNAPSHOT),
)
GENERATED_PACKAGE_PATHS.add("package/provenance/reproducibility_snapshot.json")

FIXED_COPY_AUDIT = pd.DataFrame(FIXED_COPY_AUDIT_RECORDS)
print("Assembly finished in staging; checking exact contents next.")

Verified copy 20/115
Verified copy 40/115
Verified copy 60/115
Verified copy 80/115
Verified copy 100/115
Verified copy 115/115
Assembly finished in staging; checking exact contents next.

In [14]:
from PIL import Image
from restoration_eval.supervisor_package import audit_self_contained_html

PACKAGE_FILES_BATCH_6 = package_file_records(PACKAGE_ROOT, ROOT)

fixed_paths = {
    (ROOT / row.destination_path).relative_to(OUTPUT_ROOT).as_posix()
    for row in COPY_PLAN_TABLE.itertuples(index=False)
}
expected_paths = fixed_paths | GENERATED_PACKAGE_PATHS
actual_paths = {
    "package/" + p
    for p in PACKAGE_FILES_BATCH_6.package_relative_path
}

check("b6/exact_file_set", actual_paths == expected_paths,
      sorted(actual_paths.symmetric_difference(expected_paths)))
check("b6/no_plan_overlap", not (fixed_paths & GENERATED_PACKAGE_PATHS))
check("b6/fixed_copies", len(FIXED_COPY_AUDIT) == len(COPY_PLAN_TABLE)
      and FIXED_COPY_AUDIT.matches.all())
check("b6/document_count", len(DOC_TEMPLATES) == 6)
check("b6/file_count", len(PACKAGE_FILES_BATCH_6)
      == len(COPY_PLAN_TABLE) + len(DOC_TEMPLATES) + 2)
check("b6/size", int(PACKAGE_FILES_BATCH_6.size_bytes.sum())
      <= CONFIG["package_policy"]["maximum_package_size_mib"] * 1024**2)
check("b6/final_path_lengths", all(
    len((OUTPUT_ROOT / "package" / rel).relative_to(ROOT).as_posix())
    <= CONFIG["package_policy"]["maximum_relative_path_characters"]
    for rel in PACKAGE_FILES_BATCH_6.package_relative_path))
check("b6/no_temporary_files",
      not any(p.name.endswith(".tmp") for p in STAGE_ROOT.rglob("*")))

# Validate generated Markdown links at their actual staged locations.
import re
from urllib.parse import unquote, urlsplit

for relative in GENERATED_PACKAGE_PATHS:
    file = stage_path(relative)
    if file.suffix != ".md":
        continue
    text = file.read_text(encoding="utf-8")
    for target in re.findall(r"!?\[[^\]]*\]\(([^)]+)\)", text):
        parsed = urlsplit(target)
        if parsed.scheme or parsed.netloc or target.startswith("#"):
            continue
        resolved = (file.parent / unquote(parsed.path)).resolve()
        check("b6/link_" + relative + "_" + target,
              resolved.is_relative_to(PACKAGE_ROOT.resolve())
              and resolved.is_file())

HTML_AUDIT_BATCH_6 = [
    audit_self_contained_html(p)
    for p in sorted(PACKAGE_ROOT.rglob("*.html"))
]
check("b6/html_count", len(HTML_AUDIT_BATCH_6) == 6)
check("b6/html_local_dependencies",
      all(r["self_contained"] for r in HTML_AUDIT_BATCH_6),
      [r["local_references"] for r in HTML_AUDIT_BATCH_6])

pngs = sorted((PACKAGE_ROOT / "figures").rglob("*.png"))
check("b6/figure_count", len(pngs) == 24)
for image_path in pngs:
    with Image.open(image_path) as opened:
        opened.verify()
check("b6/figures_reload", True, len(pngs))

reloaded = json.loads(
    stage_path("package/provenance/reproducibility_snapshot.json")
    .read_text("utf-8")
)
check("b6/provenance_reload", reloaded == REPRODUCIBILITY_SNAPSHOT)
check("b6/preserved_warnings", len(reloaded["n35_nonpasses"]) == 14)

verify_frozen_inputs("b6_end")
check("b6/payload_groups_unchanged", all(
    sha256_path(path(rel)) == digest
    for rel, digest in SELECTED_GROUP_HASHES.items()))
check("b6/canonical_unchanged",
      canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT)

VALIDATION = ValidationCollector()
for record in CHECK_LOG.values():
    VALIDATION.add(**record)
VALIDATION.raise_for_blocking()

PACKAGE_TREE_CHECKSUM_BATCH_6 = package_tree_checksum(PACKAGE_FILES_BATCH_6)
PACKAGE_SIZE_MIB_BATCH_6 = PACKAGE_FILES_BATCH_6.size_bytes.sum() / 1024**2
PACKAGE_SNAPSHOT_BATCH_6 = tree_snapshot(PACKAGE_ROOT)

display(VALIDATION.to_dataframe().groupby(
    ["validation_stage", "severity"]).agg(
        checks=("check_id", "size"), passed=("passed", "sum")))

print("Batches 4–6 passed; staged package files:", len(PACKAGE_FILES_BATCH_6))
print("Package size MiB:", round(PACKAGE_SIZE_MIB_BATCH_6, 3))
print("Package tree SHA-256:", PACKAGE_TREE_CHECKSUM_BATCH_6)
print("Staging location:", STAGE_ROOT.relative_to(ROOT))
print("Canonical release NOT promoted. N36 completion gate remains NO.")
print("Save the notebook and stop here. Batches 7–9 remain.")

                           checks  passed
validation_stage severity
b1               blocking      11      11
b2               blocking     302     302
                 warning       16       0
b3               blocking      15      15
b4               blocking      24      24
b5               blocking      26      26
b6               blocking     277     277
b6_end           blocking       1       1

Batches 4–6 passed; staged package files: 123
Package size MiB: 35.038
Package tree SHA-256: a547080695e8e8a392b743e2f3b1ff85aaee1512d48019b590fa363549f482ac
Staging location: outputs\36_supervisor_publication_reproducibility_package\work\run_e3133aca48134968896bcd1b97af72c4
Canonical release NOT promoted. N36 completion gate remains NO.
Save the notebook and stop here. Batches 7–9 remain.

## Execution plan

Eight delivered batches: preflight; upstream audit; synthesis; supervisor
documents; reproducibility; assembly; final integrity and indexes; completion
and promotion.

The original nine-step plan is consolidated without omitting checks.
Batches 1–3 are read-only. Later batches use isolated staging before verified
promotion.

## Batch 7 — Final indexes, omissions and integrity

Complete the artifact index, explicitly distinguish copied/generated/indexed-only
evidence, and retain the reasons for every omitted collection.

Compare artifact families against the immutable pilot baseline. Validate all
bundled formats, required document links, HTML resource dependencies, exact
copied bytes, package size and source stability.

This batch incorporates the originally separate portability batch. No checks
are omitted and no canonical release is promoted yet.

In [15]:
import subprocess
from io import StringIO
from html.parser import HTMLParser
from urllib.parse import unquote, urlsplit

verify_frozen_inputs("b7")
check("b7/package_checkpoint", tree_snapshot(PACKAGE_ROOT)
      == globals().get("PACKAGE_SNAPSHOT_B7_PREP", PACKAGE_SNAPSHOT_BATCH_6))
check("b7/canonical_empty",
      canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT == {})

def control_write(relative, text):
    """Write an owned staging file without self-referential validation checks."""
    target = stage_path(relative)
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()
    if target.exists() and sha256_file(target) not in {
        digest, STAGE_WRITES.get(relative)
    }:
        raise RuntimeError(f"Unowned or changed control file: {relative}")
    atomic_write_text(target, text)
    STAGE_WRITES[relative] = digest
    return target

def notebook_source_identity():
    notebook = json.loads(path(
        "notebooks/36_supervisor_publication_reproducibility_package.ipynb"
    ).read_text(encoding="utf-8"))
    cells = notebook["cells"]
    if len(cells) != 29:
        raise RuntimeError("Save exactly cells 0–28; remove the old pilot tail.")

    payload, raw = [], []
    prefixes = (
        "**Refactor status:**",
        "**Validation status:**",
        "**Completion gate passed:**",
    )
    for i, cell in enumerate(cells):
        text = "".join(cell["source"])
        raw.append((cell["cell_type"], text))
        if i == 0:
            text = "\n".join(
                line for line in text.splitlines()
                if not line.startswith(prefixes)
            )
        if cell["cell_type"] == "code":
            ast.parse(text)
        payload.append((cell["cell_type"], text))

    digest = lambda x: hashlib.sha256(
        json.dumps(x, ensure_ascii=True).encode("utf-8")
    ).hexdigest()
    return {
        "path": "notebooks/36_supervisor_publication_reproducibility_package.ipynb",
        "cell_count": len(cells),
        "raw_saved_source_sha256_before_closeout": digest(raw),
        "completion_normalized_source_sha256": digest(payload),
        "normalization": (
            "Ignore only the three opening status lines; "
            "exclude outputs and execution counts."
        ),
    }

NOTEBOOK_IDENTITY = notebook_source_identity()

old = (
    "The final package manifest and integrity gate are produced in Batches 7–9;\n"
    "this appendix alone does not certify completion."
)
new = (
    "Consult the companion package manifest and completed run record for final integrity.\n"
    "The original nine-step plan was delivered in eight batches: the last two combine\n"
    "indexing, portability, completion and promotion without omitting those checks."
)
appendix = DOC_TEMPLATES["reproducibility_appendix"]
check("b7/appendix_edit_target", old in appendix or new in appendix)
save_document("reproducibility_appendix", appendix.replace(old, new))
write_stage(
    "package/reports/reproducibility_appendix.md",
    DOC_TEMPLATES["reproducibility_appendix"].replace("@BUNDLE@", ".."),
)

old = (
    "Distribute the completed N36 directory with its sibling manifests directory,\n"
    "not package alone. Batches 7–9 create the package manifest, artifact index,\n"
    "validation ledger and final run record. Until that final gate passes, this is\n"
    "staged work, not a completed release."
)
new = (
    "Distribute the full N36 delivery directory, including package, data, reports,\n"
    "manifests and validation. The manifest is ../manifests/package_manifest.json;\n"
    "the artifact index is ../data/artifact_index.csv. Accept this delivery only when\n"
    "../manifests/run_manifest.json records completed status and a passed completion gate."
)
check("b7/readme_edit_target",
      old in PACKAGE_README_TEXT or new in PACKAGE_README_TEXT)
PACKAGE_README_TEXT = PACKAGE_README_TEXT.replace(old, new)
write_stage("package/README.md", PACKAGE_README_TEXT)

baseline_raw = subprocess.check_output([
    "git", "show",
    "pilot-50-complete:outputs/36_supervisor_publication_reproducibility_package/manifests/run_manifest.json",
], cwd=ROOT, text=True)
BASELINE = json.loads(baseline_raw)

check("b7/baseline_roles",
      {r["artifact_key"].split(".", 1)[1] for r in BASELINE["outputs"]}
      == set(OUTPUT_PATHS))

BASELINE_COMPARISON = [
    {
        "item": "package files", "pilot": 114, "current": 123,
        "reason": (
            "HINT report/card +2; additional manifests +3; "
            "evaluation configuration +1; provenance copies +3."
        ),
    },
    {
        "item": "physical delivery files", "pilot": 125, "current": 134,
        "reason": "Same standalone/control artifact families; nine additional package files.",
    },
    {
        "item": "artifact records", "pilot": 12, "current": 12,
        "reason": "All original artifact roles retained.",
    },
    {
        "item": "upstream manifests", "pilot": 35, "current": 38,
        "reason": "N12A, supplemental D02 and separate D01/37.",
    },
]

REPRODUCIBILITY_SNAPSHOT["delivery_plan"] = {
    "original_planned_batches": 9,
    "delivered_batches": 8,
    "change": (
        "Owner requested final two batches; indexing/portability "
        "and closeout/promotion combined."
    ),
}
REPRODUCIBILITY_SNAPSHOT["notebook_source_identity"] = NOTEBOOK_IDENTITY
REPRODUCIBILITY_SNAPSHOT["baseline_comparison"] = BASELINE_COMPARISON

write_stage(
    "package/provenance/reproducibility_snapshot.json",
    json_text(REPRODUCIBILITY_SNAPSHOT),
)
PACKAGE_SNAPSHOT_B7_PREP = tree_snapshot(PACKAGE_ROOT)

display(pd.DataFrame(BASELINE_COMPARISON))
print("Source identity captured. Do not edit code or narrative until closeout finishes.")

,item,pilot,current,reason
0,package files,114,123,HINT report/card +2; additional manifests +3; ...
1,physical delivery files,125,134,Same standalone/control artifact families; nin...
2,artifact records,12,12,All original artifact roles retained.
3,upstream manifests,35,38,"N12A, supplemental D02 and separate D01/37."

Source identity captured. Do not edit code or narrative until closeout finishes.

In [16]:
PACKAGE_FILES_FINAL = package_file_records(PACKAGE_ROOT, ROOT)
copied_by_path = {
    r["package_relative_path"]: r
    for r in FIXED_COPY_AUDIT_RECORDS
}
index_rows = []

def index_row(disposition, relative="", source="", checksum="", basis="",
              reason="", size="", producer="36"):
    return dict(
        disposition=disposition,
        relative_path=relative,
        source_path=source,
        checksum=checksum,
        checksum_basis=basis,
        omission_reason=reason,
        size_bytes=size,
        producer_notebook=producer,
    )

for row in PACKAGE_FILES_FINAL.itertuples(index=False):
    copied = copied_by_path.get(row.package_relative_path)
    final = (
        OUTPUT_ROOT / "package" / row.package_relative_path
    ).relative_to(ROOT).as_posix()
    index_rows.append(index_row(
        "copied" if copied else "generated_by_notebook_36",
        relative=final,
        source=copied["source_path"] if copied else "",
        checksum=row.sha256,
        basis="N36 verified file SHA-256",
        size=row.size_bytes,
    ))

for key in DOC_TEMPLATES:
    relative = document_relative(key)
    file = stage_path(relative)
    index_rows.append(index_row(
        "generated_by_notebook_36",
        relative=(OUTPUT_ROOT / relative).relative_to(ROOT).as_posix(),
        checksum=sha256_file(file),
        basis="N36 verified file SHA-256",
        size=file.stat().st_size,
    ))

copied_sources = set(COPY_PLAN_TABLE.source_path)
for row in ALL_ARTIFACTS.to_dict("records"):
    if row["relative_path"] in copied_sources:
        continue
    index_rows.append(index_row(
        "indexed_not_bundled",
        source=row["relative_path"],
        checksum=row["checksum"],
        basis=(
            "N36 verified producer payload group"
            if row["relative_path"] in SELECTED_GROUP_HASHES
            else "Producer-declared checksum; not rehashed by N36"
        ),
        reason="Not bundled as a whole; selected members may be copied separately.",
        size=row.get("size_bytes", ""),
        producer=str(row["source_notebook_id"]),
    ))

for key in ("case_reports", "painting_reports"):
    for row in TABLES[key].itertuples(index=False):
        path(row.report_path)
        index_rows.append(index_row(
            "indexed_not_bundled",
            source=row.report_path,
            checksum=row.report_sha256,
            size=row.size_bytes,
            producer="32",
            basis="N32 report index; source index verified, report bytes not rehashed here",
            reason="Discover through the bundled report index and pinned publication records.",
        ))

for label in ("External model weights", "External model caches"):
    index_rows.append(index_row(
        "indexed_not_bundled",
        basis="Explicit policy exclusion; no checksum asserted",
        reason=label + " are not review-package artifacts; use producer prerequisites.",
        producer="external",
    ))

ARTIFACT_INDEX = pd.DataFrame(index_rows)
ARTIFACT_INDEX.insert(0, "index_id", [
    f"n36_index_{i:04d}" for i in range(1, len(ARTIFACT_INDEX) + 1)
])

check("b7/index_dispositions", set(ARTIFACT_INDEX.disposition)
      == {"copied", "generated_by_notebook_36", "indexed_not_bundled"})
check("b7/omission_reasons", ARTIFACT_INDEX.loc[
    ARTIFACT_INDEX.disposition.eq("indexed_not_bundled"),
    "omission_reason",
].str.len().gt(0).all())
check("b7/copied_count",
      ARTIFACT_INDEX.disposition.eq("copied").sum() == 115)
check("b7/report_indexes",
      len(TABLES["case_reports"]) == 30
      and len(TABLES["painting_reports"]) == 300)

control_write(
    "data/artifact_index.csv",
    ARTIFACT_INDEX.to_csv(index=False, lineterminator="\n"),
)

PACKAGE_MANIFEST = {
    "schema_version": "supervisor_package_manifest.v2",
    "run_id": N36_RUN_ID,
    "dataset_scope": "controlled_300",
    "package_relative_root": "package",
    "file_count": len(PACKAGE_FILES_FINAL),
    "size_bytes": int(PACKAGE_FILES_FINAL.size_bytes.sum()),
    "tree_sha256": package_tree_checksum(PACKAGE_FILES_FINAL),
    "tree_algorithm": (
        "SHA-256 of sorted package_relative_path + TAB + sha256, "
        "joined with LF, no trailing LF"
    ),
    "files": records(PACKAGE_FILES_FINAL.drop(columns=["relative_path"])),
    "artifact_index": {
        "delivery_relative_path": "data/artifact_index.csv",
        "sha256": sha256_file(stage_path("data/artifact_index.csv")),
    },
    "control_records": [
        "manifests/package_manifest.json",
        "manifests/artifacts.csv",
        "manifests/run_manifest.json",
        "validation/checks.csv",
    ],
    "control_boundary": (
        "Controls are outside package and are not included in its tree digest. "
        "The artifact index excludes itself and final controls to avoid recursive hashing."
    ),
    "omission_policy": CONFIG["package_policy"]["indexed_not_bundled"],
    "baseline_comparison": BASELINE_COMPARISON,
    "acceptance": (
        "Only accepted with matching completed run manifest "
        "and passed completion gate."
    ),
}

control_write(
    "manifests/package_manifest.json",
    json_text(PACKAGE_MANIFEST),
)
check("b7/index_roundtrip",
      len(pd.read_csv(stage_path("data/artifact_index.csv")))
      == len(ARTIFACT_INDEX))

display(
    ARTIFACT_INDEX.groupby("disposition").size()
    .rename("records").to_frame()
)

                          records
disposition
copied                        115
generated_by_notebook_36       14
indexed_not_bundled           564

In [17]:
class ResourceParser(HTMLParser):
    def __init__(self):
        super().__init__()
        self.dependencies = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if tag in {"img", "script", "iframe", "source", "video", "audio", "embed"}:
            if attrs.get("src"):
                self.dependencies.append(attrs["src"])
            if attrs.get("srcset"):
                self.dependencies.append(attrs["srcset"])
        if tag == "link" and any(
            x in attrs.get("rel", "").lower()
            for x in ("stylesheet", "preload", "icon")
        ):
            if attrs.get("href"):
                self.dependencies.append(attrs["href"])
        if tag == "object" and attrs.get("data"):
            self.dependencies.append(attrs["data"])

for row in PACKAGE_FILES_FINAL.itertuples(index=False):
    file = PACKAGE_ROOT / row.package_relative_path
    check("b7/hash_" + row.package_relative_path,
          sha256_file(file) == row.sha256
          and file.stat().st_size == row.size_bytes)

    suffix = file.suffix.lower()
    if suffix == ".json":
        json.loads(file.read_text(encoding="utf-8-sig"))
    elif suffix in {".yaml", ".yml"}:
        yaml.safe_load(file.read_text(encoding="utf-8-sig"))
    elif suffix == ".csv":
        pd.read_csv(file, keep_default_na=False)
    elif suffix == ".png":
        with Image.open(file) as opened:
            opened.verify()
    elif suffix == ".py":
        ast.parse(file.read_text(encoding="utf-8-sig"))
    else:
        file.read_text(encoding="utf-8-sig")

    if suffix == ".html":
        text = file.read_text(encoding="utf-8")
        parser = ResourceParser()
        parser.feed(text)
        dependencies = parser.dependencies + re.findall(
            r"url\(\s*[\"']?([^)'\"\s]+)", text, flags=re.I
        )
        external = [
            x for x in dependencies
            if not x.lower().startswith(("data:", "#"))
        ]
        check("b7/html_resources_" + file.name, not external, external)
        check("b7/no_css_import_" + file.name,
              re.search(r"@import\s", text, re.I) is None)

# Generated document links must work locally.
# Copied source prose retains its original provenance references.
generated_markdown = [
    stage_path("package/" + document_relative(k))
    for k in DOC_TEMPLATES
    if OUTPUT_PATHS[k].suffix == ".md"
] + [stage_path("package/README.md")] + [
    stage_path(document_relative(k))
    for k in DOC_TEMPLATES
    if OUTPUT_PATHS[k].suffix == ".md"
]

for file in generated_markdown:
    for target in re.findall(
        r"!?\[[^\]]*\]\(([^)]+)\)", file.read_text("utf-8")
    ):
        parsed = urlsplit(target)
        if parsed.scheme or parsed.netloc or target.startswith("#"):
            continue
        resolved = (file.parent / unquote(parsed.path)).resolve()
        check(
            "b7/link_" + file.relative_to(STAGE_ROOT).as_posix() + "_" + target,
            resolved.is_relative_to(PACKAGE_ROOT.resolve())
            and resolved.is_file(),
        )

check("b7/package_count", len(PACKAGE_FILES_FINAL) == 123)
check("b7/package_budget", PACKAGE_MANIFEST["size_bytes"] <= 50 * 1024**2)
check("b7/copy_bytes", all(
    sha256_file(PACKAGE_ROOT / r["package_relative_path"]) == r["source_sha256"]
    for r in FIXED_COPY_AUDIT_RECORDS
))
check("b7/no_temporary_files",
      not any(p.name.endswith(".tmp") for p in STAGE_ROOT.rglob("*")))
check("b7/canonical_untouched",
      canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT)
verify_frozen_inputs("b7_end")

RESPONSIBILITY_MAP = {
    "supervisor_summary_and_exact_rqs": ["reports/supervisor_summary.md"],
    "six_scientific_html_reports": ["package/reports"],
    "eight_compact_tables": ["package/tables"],
    "24_thesis_and_publication_figures": ["package/figures"],
    "five_model_cards": ["package/model_cards"],
    "case_and_painting_discovery": [
        "package/tables/case_report_index.csv",
        "package/tables/painting_report_index.csv",
    ],
    "38_upstream_manifests": ["package/manifests/notebook_runs"],
    "configuration_and_dataset_trace": ["package/configuration/evaluation"],
    "environment_git_hardware_seeds": [
        "package/provenance/reproducibility_snapshot.json"
    ],
    "compute_projection_boundaries": ["reports/reproducibility_appendix.md"],
    "limitations_and_exceptions": ["reports/limitations_and_deviations.md"],
    "meeting_documents_and_findings": [
        "data/key_findings.json", "data/open_questions.md", "data/feedback_agenda.md"
    ],
    "artifact_index_and_omissions": ["data/artifact_index.csv"],
    "copy_and_tree_integrity": ["manifests/package_manifest.json"],
    "portability_and_formats": ["manifests/package_manifest.json"],
    "honest_deployment_acceptance": ["package/reports/deployment_readiness.md"],
}
check("b7/responsibility_coverage",
      len(RESPONSIBILITY_MAP) == 16
      and all(
          stage_path(p).exists()
          for items in RESPONSIBILITY_MAP.values()
          for p in items
      ))

PACKAGE_SNAPSHOT_FINAL = tree_snapshot(PACKAGE_ROOT)
VALIDATION = ValidationCollector()
for record in CHECK_LOG.values():
    VALIDATION.add(**record)
VALIDATION.raise_for_blocking()

print("Batch 7 passed: indexing, omissions, formats, links and integrity.")
print("Package files:", len(PACKAGE_FILES_FINAL))
print("Package MiB:", round(PACKAGE_MANIFEST["size_bytes"] / 1024**2, 3))
print("No canonical release promoted yet.")

Batch 7 passed: indexing, omissions, formats, links and integrity.
Package files: 123
Package MiB: 35.04
No canonical release promoted yet.

## Batch 8 — Final manifests, promotion and completion

Persist the consolidated validation ledger, canonical artifact records and run
manifest. Independently reload and verify the staged delivery before promotion.

Promote only the five validated delivery directories into the empty canonical
output location. Remove only the known staging marker and empty work directories.
If promotion fails, return moved directories to staging without deleting evidence.

Completion remains explicitly qualified by the inherited warning records.
A final canonical reload must pass before the opening notebook status is updated.
Registry, documentation and inventory maintenance follow the saved-notebook audit.

In [18]:
from restoration_eval.manifests import (
    build_artifact_record,
    artifact_records_dataframe,
    build_run_manifest,
)
from restoration_eval.supervisor_package import SUPERVISOR_PACKAGE_VERSION

ARTIFACT_KEYS = [
    k for k in OUTPUT_PATHS
    if k not in {"run_manifest", "artifacts"}
]
EXPECTED_RELEASE_PATHS = (
    {"package/" + p for p in PACKAGE_SNAPSHOT_FINAL}
    | {document_relative(k) for k in DOC_TEMPLATES}
    | {
        "data/artifact_index.csv",
        "manifests/package_manifest.json",
        "manifests/artifacts.csv",
        "manifests/run_manifest.json",
        "validation/checks.csv",
    }
)

def consolidated_validation():
    value = ValidationCollector()
    for record in CHECK_LOG.values():
        value.add(**record)
    value.raise_for_blocking()
    return value

def build_final_records():
    result = []
    for key in ARTIFACT_KEYS:
        relative = OUTPUT_PATHS[key].relative_to(OUTPUT_ROOT).as_posix()
        file = stage_path(relative)
        row_count = (
            len(ARTIFACT_INDEX) if key == "artifact_index"
            else len(CHECK_LOG) if key == "validation"
            else None
        )
        record = build_artifact_record(
            artifact_key="supervisor_package." + key,
            producer_notebook=CONFIG["notebook"]["stem"],
            path=file,
            artifact_type="directory" if file.is_dir() else "file",
            artifact_role=key,
            schema_version="supervisor_package_delivery.v2",
            dataset_scope="controlled_300",
            validation_status="warning",
            row_count=row_count,
            project_root=ROOT,
        )
        record["relative_path"] = OUTPUT_PATHS[key].relative_to(ROOT).as_posix()
        identity = (
            f"{record['artifact_key']}|"
            f"{record['relative_path']}|{record['checksum']}"
        )
        record["artifact_id"] = (
            "artifact_" + hashlib.sha256(identity.encode()).hexdigest()[:20]
        )
        result.append(record)
    return artifact_records_dataframe(result)

def persist_final_controls():
    validation = consolidated_validation()
    control_write(
        "validation/checks.csv",
        validation.to_dataframe().to_csv(index=False, lineterminator="\n"),
    )
    artifacts = build_final_records()
    control_write(
        "manifests/artifacts.csv",
        artifacts.to_csv(index=False, lineterminator="\n"),
    )
    configurations = {
        k: v for k, v in SOURCE_LOCK.items()
        if k.startswith("config/")
    }
    manifest = build_run_manifest(
        notebook_id="36",
        notebook_name=CONFIG["notebook"]["stem"],
        origin=CONFIG["notebook"]["origin"],
        run_status="running",
        started_at_utc=RUN_STARTED_AT_UTC,
        completed_at_utc="",
        inventory_run_id=INVENTORY_RUN["inventory_run_id"],
        dataset_versions={"dataset_scope": "controlled_300"},
        configuration_paths=sorted(configurations),
        configuration_checksums_by_path=configurations,
        helper_versions={"supervisor_package": SUPERVISOR_PACKAGE_VERSION},
        inputs=[
            {"relative_path": p, "checksum": h}
            for p, h in sorted(SOURCE_LOCK.items())
        ],
        outputs=records(artifacts),
        expected_counts={
            "physical_output_files": 134,
            "artifact_records": 12,
            "package_files": 123,
            "canonical_output_roles": 14,
        },
        observed_counts={
            "physical_output_files": len(EXPECTED_RELEASE_PATHS),
            "artifact_records": len(artifacts),
            "package_files": 123,
            "canonical_output_roles": len(OUTPUT_PATHS),
            "artifact_index_records": len(ARTIFACT_INDEX),
            "upstream_notebooks": len(UPSTREAM),
            "validation_rows": len(validation.checks),
            "roadmap_responsibilities": len(RESPONSIBILITY_MAP),
        },
        validation_summary=validation.summary(),
        known_limitations=(
            CONFIG["scientific_boundaries"]["statements"]
            + LIMITATION_ROWS.row_label.tolist()
        ),
        project_root=ROOT,
        package_names=CONFIG["runtime"]["packages"],
        run_id=N36_RUN_ID,
    )
    manifest.update(
        refactor_status="in_progress",
        validation_status="warning",
        completion_gate_passed=False,
        depends_on=sorted(RAW_RUNS),
        applicable_dataset_scopes=["controlled_300"],
        applicable_experiment_scopes=["saved_evidence_packaging"],
        artifact_manifest_checksum=sha256_file(
            stage_path("manifests/artifacts.csv")
        ),
        notebook_source_identity=NOTEBOOK_IDENTITY,
        provenance_exceptions=PROVENANCE_EXCEPTIONS,
        deployment=DEPLOYMENT_RECORD,
        upstream_validation_summaries=(
            REPRODUCIBILITY_SNAPSHOT["upstream_validation_summaries"]
        ),
        baseline_comparison=BASELINE_COMPARISON,
        roadmap_responsibilities=RESPONSIBILITY_MAP,
        execution_plan_adjustment=REPRODUCIBILITY_SNAPSHOT["delivery_plan"],
        runtime_note=(
            "Manual batch wall time includes review/idle time; "
            "active total was not measured."
        ),
        post_run_handoff={
            "registry_and_inventory": "Refresh after saved-notebook audit.",
            "documentation": "Update after accepted final reload.",
        },
    )
    control_write("manifests/run_manifest.json", json_text(manifest))
    return manifest

def verify_release(base, completed=False):
    """Independent reload; ignore staging ownership metadata before promotion."""
    observed = set(tree_snapshot(base))
    if base == STAGE_ROOT:
        observed.discard("staging_owner.json")
    if observed != EXPECTED_RELEASE_PATHS:
        raise RuntimeError(
            f"Release file-set mismatch: {observed ^ EXPECTED_RELEASE_PATHS}"
        )

    run = json.loads(
        (base / "manifests/run_manifest.json").read_text("utf-8")
    )
    ledger_path = base / "manifests/artifacts.csv"
    ledger = pd.read_csv(ledger_path, keep_default_na=False)
    artifact_records_dataframe(ledger.to_dict("records"))

    if (
        len(ledger) != 12
        or sha256_file(ledger_path) != run["artifact_manifest_checksum"]
    ):
        raise RuntimeError("Artifact ledger mismatch")

    for row in ledger.itertuples(index=False):
        relative = (ROOT / row.relative_path).relative_to(OUTPUT_ROOT)
        if sha256_path(base / relative) != row.checksum:
            raise RuntimeError(f"Artifact hash mismatch: {row.artifact_key}")

    checks = pd.read_csv(
        base / "validation/checks.csv", keep_default_na=False
    )
    failed = ~checks.passed.astype(str).str.lower().eq("true")
    if (failed & checks.severity.isin(["blocking", "error"])).any():
        raise RuntimeError("Blocking/error validation nonpass")
    if (
        len(checks) != run["validation_summary"]["check_count"]
        or int(failed.sum()) != 16
    ):
        raise RuntimeError("Validation counts or inherited warnings changed")

    package = json.loads(
        (base / "manifests/package_manifest.json").read_text("utf-8")
    )
    files = package_file_records(base / "package", ROOT)
    if (
        len(files) != package["file_count"]
        or int(files.size_bytes.sum()) != package["size_bytes"]
    ):
        raise RuntimeError("Package count/size mismatch")

    actual = records(files.drop(columns=["relative_path"]))
    if (
        actual != package["files"]
        or package_tree_checksum(files) != package["tree_sha256"]
    ):
        raise RuntimeError("Package contents differ from the package manifest")

    if (
        sha256_file(base / "data/artifact_index.csv")
        != package["artifact_index"]["sha256"]
    ):
        raise RuntimeError("Artifact index mismatch")
    if run["run_id"] != N36_RUN_ID:
        raise RuntimeError("Unexpected run identity")
    if completed and not (
        run["run_status"] == "completed"
        and run["completion_gate_passed"] is True
    ):
        raise RuntimeError("Completion gate is not accepted")

    return run

print("Final verifier ready. Next cell performs guarded promotion.")

Final verifier ready. Next cell performs guarded promotion.

In [19]:
def close_n36():
    canonical_run = OUTPUT_PATHS["run_manifest"]
    if canonical_run.exists():
        existing = json.loads(canonical_run.read_text("utf-8"))
        if (
            existing.get("run_id") == N36_RUN_ID
            and existing.get("completion_gate_passed") is True
        ):
            verify_release(OUTPUT_ROOT, completed=True)
            print("Already completed; verified without rewriting.")
            return
        raise RuntimeError(
            "Unexpected canonical run exists; stop rather than overwrite it."
        )

    verify_frozen_inputs("b8")
    check(
        "b8/notebook_source",
        notebook_source_identity()["completion_normalized_source_sha256"]
        == NOTEBOOK_IDENTITY["completion_normalized_source_sha256"],
    )
    check("b8/package_freeze",
          tree_snapshot(PACKAGE_ROOT) == PACKAGE_SNAPSHOT_FINAL)
    check("b8/selected_payload_freeze", all(
        sha256_path(path(rel)) == digest
        for rel, digest in SELECTED_GROUP_HASHES.items()
    ))
    check("b8/canonical_empty",
          canonical_snapshot() == HISTORICAL_OUTPUT_SNAPSHOT == {})
    check(
        "b8/only_owned_work",
        {p.name for p in (OUTPUT_ROOT / "work").iterdir()} == {N36_RUN_ID},
    )
    check("b8/final_roles",
          len(ARTIFACT_KEYS) == 12 and len(EXPECTED_RELEASE_PATHS) == 134)
    check("b8/warnings_retained",
          sum(not r["passed"] for r in CHECK_LOG.values()) == 16)

    manifest = persist_final_controls()
    verify_release(STAGE_ROOT)
    check(
        "b8/independent_staging_reload",
        True,
        "All final artifact hashes and counts match",
    )
    manifest = persist_final_controls()
    verify_release(STAGE_ROOT)

    # Promote only validated directories into the empty canonical tree.
    names = ["data", "reports", "package", "validation", "manifests"]
    owner = stage_path("staging_owner.json").read_text("utf-8")
    check_owner = json.loads(owner)
    if check_owner["run_id"] != N36_RUN_ID:
        raise RuntimeError("Staging owner mismatch")

    for name in names:
        source = stage_path(name)
        destination = OUTPUT_ROOT / name
        if not source.is_dir() or destination.exists():
            raise RuntimeError(f"Unsafe promotion target: {name}")

    if (
        {p.name for p in STAGE_ROOT.iterdir()}
        != set(names) | {"staging_owner.json"}
    ):
        raise RuntimeError("Unexpected staging content; refusing cleanup")

    moved = []
    try:
        for name in names:
            os.replace(stage_path(name), OUTPUT_ROOT / name)
            moved.append(name)

        # Remove only the known marker and now-empty work directories.
        stage_path("staging_owner.json").unlink()
        STAGE_ROOT.rmdir()
        (OUTPUT_ROOT / "work").rmdir()
        verify_release(OUTPUT_ROOT)

        manifest.update(
            run_status="completed",
            completed_at_utc=datetime.now(timezone.utc).isoformat(),
            refactor_status="finished",
            completion_gate_passed=True,
        )
        atomic_write_text(canonical_run, json_text(manifest))
        verify_release(OUTPUT_ROOT, completed=True)

    except Exception:
        # Restore moved directories to staging; delete no evidence.
        STAGE_ROOT.mkdir(parents=True, exist_ok=True)
        for name in reversed(moved):
            destination = stage_path(name)
            if destination.exists():
                raise RuntimeError(
                    f"Rollback destination unexpectedly exists: {destination}"
                )
            os.replace(OUTPUT_ROOT / name, destination)

        atomic_write_text(stage_path("staging_owner.json"), owner)
        provisional = dict(manifest)
        provisional.update(
            run_status="running",
            completion_gate_passed=False,
            refactor_status="in_progress",
            completed_at_utc="",
        )
        atomic_write_text(
            stage_path("manifests/run_manifest.json"),
            json_text(provisional),
        )
        STAGE_WRITES["manifests/run_manifest.json"] = sha256_file(
            stage_path("manifests/run_manifest.json")
        )
        raise

    print("N36 completed and promoted. No upstream evidence changed.")
    print("Removed only this run's staging marker and empty work directories.")

close_n36()

N36 completed and promoted. No upstream evidence changed.
Removed only this run's staging marker and empty work directories.

In [20]:
FINAL_RUN = verify_release(OUTPUT_ROOT, completed=True)
FINAL_CHECKS = pd.read_csv(
    OUTPUT_PATHS["validation"], keep_default_na=False
)
FINAL_ARTIFACTS = pd.read_csv(
    OUTPUT_PATHS["artifacts"], keep_default_na=False
)
FINAL_PACKAGE = json.loads(
    OUTPUT_PATHS["package_manifest"].read_text("utf-8")
)

current_identity = notebook_source_identity()
if (
    current_identity["completion_normalized_source_sha256"]
    != FINAL_RUN["notebook_source_identity"]["completion_normalized_source_sha256"]
):
    raise RuntimeError(
        "Saved notebook source changed beyond the permitted opening status lines."
    )

display(
    FINAL_CHECKS.groupby(["validation_stage", "severity"]).agg(
        checks=("check_id", "size"),
        passed=("passed", "sum"),
    )
)
display(FINAL_ARTIFACTS[[
    "artifact_key", "format", "file_count", "validation_status"
]])

print("NOTEBOOK 36 COMPLETION GATE: PASSED")
print("Run ID:", FINAL_RUN["run_id"])
print("Physical delivery files:", len(tree_snapshot(OUTPUT_ROOT)))
print("Package files:", FINAL_PACKAGE["file_count"])
print("Package MiB:", round(FINAL_PACKAGE["size_bytes"] / 1024**2, 3))
print("Artifact records:", len(FINAL_ARTIFACTS))
print("Validation rows:", len(FINAL_CHECKS))
print(
    "Inherited warning nonpasses:",
    int((~FINAL_CHECKS.passed.astype(str).str.lower().eq("true")).sum()),
)
print("Next: update only the three opening status lines and save.")
print(
    "Then request the saved-notebook audit, registry/docs/inventory refresh "
    "and commit instructions."
)

                           checks  passed
validation_stage severity
b1               blocking      11      11
b2               blocking     302     302
                 warning       16       0
b3               blocking      15      15
b4               blocking      24      24
b5               blocking      26      26
b6               blocking     277     277
b6_end           blocking       1       1
b7               blocking     193     193
b7_end           blocking       1       1
b8               blocking       9       9

,artifact_key,format,file_count,validation_status
0,supervisor_package.supervisor_summary,md,1,warning
1,supervisor_package.reproducibility_appendix,md,1,warning
2,supervisor_package.limitations_and_deviations,md,1,warning
3,supervisor_package.artifact_index,csv,1,warning
4,supervisor_package.key_findings,json,1,warning
5,supervisor_package.open_questions,md,1,warning
6,supervisor_package.feedback_agenda,md,1,warning
7,supervisor_package.package_root,directory,123,warning
8,supervisor_package.package_readme,md,1,warning
9,supervisor_package.reproducibility_snapshot,json,1,warning
10,supervisor_package.package_manifest,json,1,warning
11,supervisor_package.validation,csv,1,warning

NOTEBOOK 36 COMPLETION GATE: PASSED
Run ID: run_e3133aca48134968896bcd1b97af72c4
Physical delivery files: 134
Package files: 123
Package MiB: 35.04
Artifact records: 12
Validation rows: 875
Inherited warning nonpasses: 16
Next: update only the three opening status lines and save.
Then request the saved-notebook audit, registry/docs/inventory refresh and commit instructions.